Repository Azure/azure-powershell, pull requests merged in 2018-10, with the labels that each got.

#7435 Un-skip more tests; drop outdated traits
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpAddressTests/TestPublicIpAddressCRUDIpTag.json
Labels: needs-review

#7419 Versioning Traffic Manager for out of band release
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/AzureRM.TrafficManager.psd1
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/ChangeLog.md
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/Properties/AssemblyInfo.cs
Labels: Waiting for CI :shipit:

#7424 [Compute-Preview] Update AzureRmGalleryImageVersion example
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmGalleryImageVersion.md
  src/ResourceManager/Compute/Commands.Compute/help/Update-AzureRmGalleryImageVersion.md
Labels: needs-review

#7403 [ResourceGraph] Fetch subscriptions from ARM if AzureContext is not populated
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph.Test/ScenarioTests/TestController.cs
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph.Test/SessionRecords/Microsoft.Azure.Commands.ResourceGraph.Test.ScenarioTests.ResourceGraphQueryTests/PagedQuery.json
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph.Test/SessionRecords/Microsoft.Azure.Commands.ResourceGraph.Test.ScenarioTests.ResourceGraphQueryTests/Query.json
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph.Test/SessionRecords/Microsoft.Azure.Commands.ResourceGraph.Test.ScenarioTests.ResourceGraphQueryTests/QueryError.json
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph.Test/SessionRecords/Microsoft.Azure.Commands.ResourceGraph.Test.ScenarioTests.ResourceGraphQueryTests/Subscriptions.json
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/Az.ResourceGraph.psd1
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/AzureRM.ResourceGraph.psd1
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/ChangeLog.md
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/Cmdlets/SearchAzureRmGraph.cs
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/Commands.ResourceGraph.csproj
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/Properties/AssemblyInfo.cs
  src/ResourceManager/ResourceGraph/Commands.ResourceGraph/Utilities/SubscriptionCache.cs
Labels: needs-revision

#7186 6989 fix : Add example for simple param set to the New-AzureRmVmss cmdlet hep
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmss.md
Labels: needs-review

#7414 [Storage] Add warning message for get global usage is obsolete
  src/ResourceManager/Storage/Commands.Management.Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageUsage.cs
  src/ResourceManager/Storage/documentation/upcoming-breaking-changes.md
Labels: needs-review

#7423 New cmdlets to create/enter PSSession in remote container app
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
  src/ResourceManager/Websites/Commands.Websites.Test/Commands.Websites.Test.csproj
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.cs
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestWindowsContainerWebAppCanIssuePSSession.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestWindowsContainerWebAppPSSessionOpened.json
  src/ResourceManager/Websites/Commands.Websites/Az.Websites.psd1
  src/ResourceManager/Websites/Commands.Websites/AzureRM.Websites.psd1
  src/ResourceManager/Websites/Commands.Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/EnterAzureRmWebAppContainerPSSession.cs
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/NewAzureRmWebAppContainerPSSession.cs
  src/ResourceManager/Websites/Commands.Websites/Commands.Websites.csproj
  src/ResourceManager/Websites/Commands.Websites/Properties/Resources.Designer.cs
  src/ResourceManager/Websites/Commands.Websites/Properties/Resources.resx
  src/ResourceManager/Websites/Commands.Websites/Utilities/WebsitesClient.cs
  src/ResourceManager/Websites/Commands.Websites/help/AzureRM.Websites.md
  src/ResourceManager/Websites/Commands.Websites/help/Enter-AzureRmWebAppContainerPSSession.md
  src/ResourceManager/Websites/Commands.Websites/help/New-AzureRmWebAppContainerPSSession.md
Labels: needs-revision

#7304 [GuestConfiguration] Introducing Get-AzureRmGuestConfigurationPolicy …
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/Commands.GuestConfiguration.Test.Netcore.csproj
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/Commands.GuestConfiguration.Test.csproj
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/MSSharedLibKey.snk
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/ScenarioTests/Common.ps1
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/ScenarioTests/GetVmGuestPolicyReportTests.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/ScenarioTests/GetVmGuestPolicyReportTests.ps1
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/ScenarioTests/TestController.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/InitiativeIdScope.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/InitiativeIdScopeDetailed.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/InitiativeIdScopeDetailedLatest.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/InitiativeNameScope.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/InitiativeNameScopeDetailed.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/InitiativeNameScopeDetailedLatest.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/VmNameScope.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/VmNameScopeDetailed.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/SessionRecords/Microsoft.Azure.Commands.GuestConfiguration.Test.ScenarioTests.GetVmGuestPolicyReportTests/VmNameScopeDetailedLatest.json
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration.Test/packages.config
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/AzureRM.GuestConfiguration.psd1
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/ChangeLog.md
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Cmdlets/GetAzureRmVMGuestPolicyReport.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Commands.GuestConfiguration.csproj
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Common/Constants.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Common/GuestConfigurationCmdletBase.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Common/ParameterHelpMessages.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Common/ParameterSetNames.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Helpers/CommonHelpers.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/MSSharedLibKey.snk
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Microsoft.Azure.Commands.GuestConfiguration.format.ps1xml
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Models/GuestConfigurationPolicyAssignment.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Models/GuestConfigurationPolicyAssignmentReport.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Properties/AssemblyInfo.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Resources.Designer.cs
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/Resources.resx
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/help/AzureRM.GuestConfiguration.md
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/help/Get-AzureRmVMGuestPolicyReport.md
  src/ResourceManager/GuestConfiguration/Commands.GuestConfiguration/packages.config
  src/ResourceManager/GuestConfiguration/GuestConfiguration.sln
  src/ResourceManager/GuestConfiguration/NuGet.Config
  src/ResourceManager/GuestConfiguration/documentation/current-breaking-changes.md
  src/ResourceManager/GuestConfiguration/documentation/upcoming-breaking-changes.md
  src/ResourceManager/Network/Commands.Network/Az.Network.psd1
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.psd1
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
Labels: Preview, needs-revision

#7426 Announce upcoming Azure Batch breaking changes
  src/ResourceManager/AzureBatch/documentation/upcoming-breaking-changes.md
Labels: needs-review

#7447 Update Set-AzureRmDataFactoryV2IntegrationRuntime.md With Extra Example
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/help/Set-AzureRmDataFactoryV2IntegrationRuntime.md
Labels: Waiting for CI :shipit:, needs-review

#7365 Fix Get-AzureRmVM paging with ResourceGroupName
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
Labels: Waiting for CI :shipit:

#7450 Updating ADF nuget to 2.3.0
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.Netcore.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/packages.config
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Changelog.md
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Commands.DataFactoryV2.Netcore.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Commands.DataFactoryV2.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/packages.config
Labels: Waiting for CI :shipit:

#7383 NetStandard Tests v1
  .gitignore
  src/Azure.PowerShell.Netcore.Test.sln
  src/ResourceManager/Cdn/Commands.Cdn.Test/Commands.Cdn.Test.Netcore.csproj
  src/ResourceManager/Cdn/Commands.Cdn.Test/ScenarioTests/TestController.cs
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/Commands.Management.CognitiveServices.Test.Netcore.csproj
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/TestController.cs
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.Netcore.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/ScenarioTests/DnsTestsBase.cs
  src/ResourceManager/MachineLearning/Commands.MachineLearning.Test/Commands.MachineLearning.Test.Netcore.csproj
  src/ResourceManager/MachineLearning/Commands.MachineLearning.Test/ScenarioTests/BaseTestController.cs
  src/ResourceManager/MachineLearningCompute/Commands.MachineLearningCompute.Test/Commands.MachineLearningCompute.Test.Netcore.csproj
  src/ResourceManager/MachineLearningCompute/Commands.MachineLearningCompute.Test/ScenarioTests/TestController.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/Commands.ServiceBus.Test.Netcore.csproj
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusController.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusQueueTests.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusServiceTests.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusTopicTests.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.Netcore.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/ScenarioTests/ServceFabricSetupHelper.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/ScenarioTests/TestController.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/ScenarioTests/TestServiceFabric.ps1
  src/ResourceManager/ServiceFabric/ServiceFabric.sln
  src/ResourceManager/TrafficManager/Commands.TrafficManager2.Test/Commands.TrafficManager.Test.Netcore.csproj
  src/ResourceManager/TrafficManager/Commands.TrafficManager2.Test/ScenarioTests/TestController.cs
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
  src/TestPrerequisites/Storage.Test.Prerequisites/Storage.TestPrerequisites.csproj
Labels: needs-review

#7464 Fixes Az Travis build
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/Commands.Management.CognitiveServices.Test.Netcore.csproj
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
Labels: needs-review

#7465 Fix error in help generate for DataFactoryV2 cmdlet
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/help/Set-AzureRmDataFactoryV2IntegrationRuntime.md
Labels: needs-review

#7470 Fix typos and capitalization
  documentation/announcing-az-module.md
Labels: Waiting for CI :shipit:, needs-review

#7405 Update description for -SubscriptionId
  src/ResourceManager/Profile/Commands.Profile/help/Set-AzureRmContext.md
Labels: needs-revision

#7490 Skip failing test for build
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppBackupRestoreTests.cs
Labels: needs-review

#7495 Fix alias mappings
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
  tools/CreateAliasMapping.ps1
Labels: needs-review

#7491 [Compute-Preview] Add expand parameter to Get-AzureRmGalleryImageVersion
  src/ResourceManager/Compute/Commands.Compute/Generated/GalleryImageVersion/GalleryImageVersionGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/help/Get-AzureRmGalleryImageVersion.md
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppBackupRestoreTests.cs
Labels: needs-review

#7411 Update version of DeploymentManager to 0.9.1
  src/ResourceManager/DeploymentManager/Commands.DeploymentManager/AzureRM.DeploymentManager.psd1
  src/ResourceManager/DeploymentManager/Commands.DeploymentManager/ChangeLog.md
  src/ResourceManager/DeploymentManager/Commands.DeploymentManager/Properties/AssemblyInfo.cs
  tools/LocalFeed/Microsoft.Azure.Management.DeploymentManager.0.9.0-preview.nupkg
Labels: needs-review

#7503 Add new SKUs that are Accel Net compatible
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Common/Utils.cs
Labels: needs-review

#7492 Adding the output model change in Get-AzureRmResource
  documentation/migration-guides/Stack/migration-guide.2.3.0.md
Labels: Azure Stack, Waiting for CI :shipit:

#7500 Update Add-AzureRmLogProfile.md
  src/ResourceManager/Insights/Commands.Insights/help/Add-AzureRmLogProfile.md
Labels: Waiting for CI :shipit:

#7523 Add ArgumentCompleter for Subnet's ServiceEndpoints
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/VirtualNetwork/Subnet/AzureVirtualNetworkSubnetConfigBase.cs
Labels: needs-review

#7529 Azure firewall fqdn tags
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallFqdnTagTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallFqdnTagTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallFqdnTagTests/TestListAzureFirewallFqdnTag.json
  src/ResourceManager/Network/Commands.Network/Az.Network.psd1
  src/ResourceManager/Network/Commands.Network/AzureFirewall/ApplicationRule/NewAzureFirewallApplicationRuleCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/AzureFirewallBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewallFqdnTag/AzureFirewallFqdnTagHelper.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewallFqdnTag/GetAzureFirewallFqdnTagCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.psd1
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallFqdnTag.cs
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmFirewallFqdnTag.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewallApplicationRule.md
Labels: Cmdlet Review Complete, needs-review

#7482 Juliet/fix/protocol
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectivityCheck.json
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/TestAzureNetworkWatcherConnectivityCommand.cs
Labels: needs-revision

#7425 application gateway waf config
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.Netcore.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Commands.KeyVault.Test.Netcore.csproj
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Commands.KeyVault.Test.csproj
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/packages.config
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD2.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD3.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableSslOptions.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableWafRuleSets.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/FirewallConfiguration/AzureApplicationGatewayWebApplicationFirewallConfigurationBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/FirewallConfiguration/NewAzureApplicationGatewayWebApplicationFirewallConfigurationCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/FirewallConfiguration/SetAzureApplicationGatewayWebApplicationFirewallConfigurationCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/FirewallExclusion/AzureApplicationGatewayFirewallExclusionConfigBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/FirewallExclusion/NewAzureApplicationGatewayFirewallExclusionConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/Az.Network.psd1
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.psd1
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayFirewallExclusion.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayWebApplicationFirewallConfiguration.cs
  src/ResourceManager/Network/Commands.Network/help/AzureRM.Network.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayFirewallExclusionConfig.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayWebApplicationFirewallConfiguration.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayWebApplicationFirewallConfiguration.md
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.Netcore.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  tools/AzureRM/AzureRM.psm1
  tools/CredScanSuppressions.json
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.6.0.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.6.0.symbols.nupkg
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Network/SignatureIssues.csv
Labels: Cmdlet Review Complete, Network, needs-revision

#7580 Re-record failing Websites test
  src/ResourceManager/Profile/Commands.Profile/packages.config
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestGetDeletedWebApp.json
Labels: Waiting for CI :shipit:

#7511 Update Start-AzureRmRecoveryServicesAsrTestFailoverCleanupJob.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.SiteRecovery/help/Start-AzureRmRecoveryServicesAsrTestFailoverCleanupJob.md
Labels: needs-review

#7588 Change TestVirtualNetworkTapCRUDUsingIpConfig's owner to SDN NRP
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTapTests.cs
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTapTests/TestVirtualNetworkTapCRUDUsingIpConfig.json
Labels: Waiting for CI :shipit:

#7585 Fix automapping for VirtualNetworkPeering
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
Labels: Waiting for CI :shipit:

#7557 [Backup] Deprecating Azure Backup.
  src/ResourceManager/AzureBackup/Commands.AzureBackup/ChangeLog.md
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Backup/BackupAzureRMBackupItem.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Container/EnableAzureRMBackupContainerReregistration.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Container/GetAzureRMBackupContainer.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Container/RegisterAzureRMBackupContainer.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Container/UnregisterAzureRMBackupContainer.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Item/Disable-AzureRMBackupProtection.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Item/Enable-AzureRMBackupProtection.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Item/GetAzureRMBackupItem.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/GetAzureRMBackupJob.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/GetAzureRMBackupJobDetails.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/StopAzureRMBackukpJob.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Jobs/WaitAzureRMBackupJob.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/ProtectionPolicy/GetAzureRMBackupProtectionPolicy.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/ProtectionPolicy/NewAzureRMBackupProtectionPolicy.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/ProtectionPolicy/NewAzureRMBackupRetentionPolicyObject.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/ProtectionPolicy/RemoveAzureRMBackupProtectionPolicy.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/ProtectionPolicy/SetAzureRMBackupProtectionPolicy.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/RecoveryPoint/GetAzureRMBackupRecoveryPoint.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Restore/RestoreAzureRMBackupItem.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Vault/GetAzureRMBackupVault.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Vault/NewAzureRMBackupVault.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Vault/RemoveAzureRMBackupVault.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Vault/SetAzureRMBackupVault.cs
  src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/VaultCredentials/GetAzureRMBackupVaultCredentials.cs
  src/ResourceManager/AzureBackup/documentation/upcoming-breaking-changes.md
Labels: needs-review

#7592 Fix for issue #7479
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/RoleDefinitions/GetAzureRoleDefinitionCommand.cs
Labels: needs-review

#7559 Fix incorrect logic for RouteFilter parameter set in ExpressRouteCircuit's Peering
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCircuitTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCircuitTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ExpressRouteCircuitTests/TestExpressRouteCircuitPeeringWithRouteFilter.json
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/AddAzureExpressRouteCircuitPeeringConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/AzureExpressRouteCircuitPeeringConfigBase.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/NewAzureExpressRouteCircuitPeeringConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/SetAzureExpressRouteCircuitPeeringConfigCommand.cs
Labels: Network, needs-review

#7595 add remove-AzureRmFrontDoorContent cmdlet
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Az.FrontDoor.psd1
  src/ResourceManager/FrontDoor/Commands.FrontDoor/AzureRM.FrontDoor.psd1
  src/ResourceManager/FrontDoor/Commands.FrontDoor/ChangeLog.md
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Cmdlets/NewAzureRmFrontDoorFireWallPolicy.cs
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Cmdlets/RemoveAzureRmFrontDoorContent.cs
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Commands.FrontDoor.csproj
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Properties/Resources.Designer.cs
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Properties/Resources.resx
  src/ResourceManager/FrontDoor/Commands.FrontDoor/help/AzureRM.FrontDoor.md
  src/ResourceManager/FrontDoor/Commands.FrontDoor/help/New-AzureRmFrontDoorFireWallPolicy.md
  src/ResourceManager/FrontDoor/Commands.FrontDoor/help/Remove-AzureRmFrontDoorContent.md
Labels: needs-revision

#7624 RC2 for 2018-10-23
  ChangeLog.md
  src/ResourceManager/Aks/Commands.Aks/AzureRM.Aks.psd1
  src/ResourceManager/Aks/Commands.Aks/ChangeLog.md
  src/ResourceManager/Aks/Commands.Aks/Properties/AssemblyInfo.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/AzureRM.DataLakeStore.psd1
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#7622 Version change to release a newer preview module for Deployment Manager preview
  src/ResourceManager/DeploymentManager/Commands.DeploymentManager/AzureRM.DeploymentManager.psd1
  src/ResourceManager/DeploymentManager/Commands.DeploymentManager/ChangeLog.md
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.DeploymentManager.dll.json
Labels: needs-review

#7458 Add DnsZonePartner Parameter for New-AzureRmSqlManagedInstance cmdlet
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/Common.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstance.json
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/Instance Failover Group/Services/AzureSqlInstanceFailoverGroupAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/packages.config
Labels: needs-revision

#7531 Fix -Tags for New-AzureRmSqlDatabaseCopy #6049
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
Labels: Waiting for CI :shipit:

#7618 Automation DLL rename
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.Netcore.csproj
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.csproj
  src/ResourceManager/Automation/Commands.Automation/Az.Automation.psd1
  src/ResourceManager/Automation/Commands.Automation/AzureRM.Automation.psd1
  src/ResourceManager/Automation/Commands.Automation/ChangeLog.md
  src/ResourceManager/Automation/Commands.Automation/Commands.Automation.Netcore.csproj
  src/ResourceManager/Automation/Commands.Automation/Commands.Automation.csproj
  src/ResourceManager/Automation/Commands.Automation/Properties/AssemblyInfo.cs
  src/ServiceManagement/Automation/Commands.Automation.Test/Commands.Automation.Test.csproj
  src/ServiceManagement/Automation/Commands.Automation/Commands.Automation.csproj
  src/ServiceManagement/Automation/Commands.Automation/Microsoft.WindowsAzure.Commands.Automation.dll-help.xml
  src/ServiceManagement/Automation/Commands.Automation/Properties/AssemblyInfo.cs
  src/ServiceManagement/Azure.psd1
  tools/CredScanSuppressions.json
  tools/Docs/Add-AzureHelpKeywords.ps1
  tools/StaticAnalysis/Exceptions/Az.Automation/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Automation/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Automation/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Automation/SignatureIssues.csv
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.Automation.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.ResourceManager.Automation.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.WindowsAzure.Commands.Automation.dll.json
  tools/Tools.Common/Tools.Common.csproj
Labels: Waiting for On Demand

#7635 Update Azure.Batch version
  src/ResourceManager/AzureBatch/Commands.Batch.Test/Commands.Batch.Test.csproj
  src/ResourceManager/AzureBatch/Commands.Batch.Test/packages.config
  src/ResourceManager/AzureBatch/Commands.Batch/Commands.Batch.Netcore.csproj
  src/ResourceManager/AzureBatch/Commands.Batch/Commands.Batch.csproj
  src/ResourceManager/AzureBatch/Commands.Batch/packages.config
Labels: needs-review

#7615 Added Auth changes section
  documentation/announcing-az-module.md
Labels: Waiting for CI :shipit:

#7519 [CognitiveServices] Support getting account types (kinds).
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/Commands.Management.CognitiveServices.Test.csproj
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.cs
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.ps1
  src/ResourceManager/CognitiveServices/CognitiveServices.Test/SessionRecords/CognitiveServices.Test.ScenarioTests.CognitiveServicesAccountTests/TestGetAccountType.json
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/Az.CognitiveServices.psd1
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/AzureRM.CognitiveServices.psd1
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/ChangeLog.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/CognitiveServicesAccount/CognitiveServicesAccountBaseCmdlet.cs
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/CognitiveServicesAccount/GetAzureCognitiveServicesAccountType.cs
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/Commands.Management.CognitiveServices.csproj
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/AzureRM.CognitiveServices.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/Get-AzureRmCognitiveServicesAccountType.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/New-AzureRmCognitiveServicesAccount.md
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
Labels: Cmdlet Review Complete, Waiting for CI :shipit:

#7640 Update NRP's test ownership
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/NrpTeamAlias.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationSecurityGroupTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AvailableDelegationsTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AvailableEndpointServicesTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallFqdnTagTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/CortexTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/DdosProtectionPlanTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCircuitTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCrossConnectionTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteServiceProviderTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/ApplicationSecurityGroupTestsGenerated.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/LoadBalancerTestsGenerated.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/RouteTableTestsGenerated.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/UsageTestsGenerated.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/LoadBalancerTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/LocalNetworkGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/MultiIpConfigOnNicTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkCloudExceptionTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkInterfaceTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkProfileTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkSecurityGroupTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpPrefixTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/TestDnsAvailabilityTest.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/UsageTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTapTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTests.cs
Labels: needs-review

#7636 Adding a warning before starting on update operation
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Azs.Update.Admin.psd1
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/ChangeLog.md
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Install-AzsUpdate.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: needs-review

#7597 Fix bug adding certificate to linux vmss, flatten exception and fix service fabric durability upgrade issue
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/ChangeLog.md
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/ServiceFabricClusterCertificateCmdlet.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/ServiceFabricClusterCmdlet.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/UpdateAzureRmServiceFabricDurability.cs
Labels: needs-review

#7619 [Insights] Make sure the diagnostic settings can be added without explicitly specifying the categories. (Issue #7513)
  src/ResourceManager/Insights/Commands.Insights.Test/Commands.Insights.Test.csproj
  src/ResourceManager/Insights/Commands.Insights.Test/ScenarioTests/AzureRmDiagnosticSettingTests.cs
  src/ResourceManager/Insights/Commands.Insights.Test/ScenarioTests/AzureRmDiagnosticSettingTests.ps1
  src/ResourceManager/Insights/Commands.Insights.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AzureRmDiagnosticSettingTests/TestSetAzureRmDiagnosticSettingCreate.json
  src/ResourceManager/Insights/Commands.Insights.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AzureRmDiagnosticSettingTests/TestSetAzureRmDiagnosticSettingUpdate.json
  src/ResourceManager/Insights/Commands.Insights/ChangeLog.md
  src/ResourceManager/Insights/Commands.Insights/Diagnostics/SetAzureRmDiagnosticSettingCommand.cs
  src/ResourceManager/Insights/Commands.Insights/help/Set-AzureRmDiagnosticSetting.md
Labels: Waiting for CI :shipit:

#7645 Allow Network tests to include prefix in generate resource and resource group names
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Common.ps1
Labels: needs-review

#7617 PolicyInsights policy remediation cmdlets
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/Commands.PolicyInsights.Test.Netcore.csproj
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/Commands.PolicyInsights.Test.csproj
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/ScenarioTests/Common.ps1
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/ScenarioTests/RemediationTests.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/ScenarioTests/RemediationTests.ps1
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.RemediationTests/BackgroundJobs.json
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.RemediationTests/ManagementGroupScopeCrud.json
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.RemediationTests/ResourceGroupScopeCrud.json
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.RemediationTests/ResourceScopeCrud.json
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.RemediationTests/SubscriptionScopeCrud.json
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights.Test/packages.config
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Az.PolicyInsights.psd1
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/AzureRM.PolicyInsights.psd1
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/ChangeLog.md
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Cmdlets/Remediation/GetAzureRmPolicyRemediation.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Cmdlets/Remediation/RemoveAzureRmPolicyRemediation.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Cmdlets/Remediation/StartAzureRmPolicyRemediation.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Cmdlets/Remediation/StopAzureRmPolicyRemediation.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Commands.PolicyInsights.Netcore.csproj
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Commands.PolicyInsights.csproj
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Common/PaginationHelper.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Common/ParameterHelpMessages.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Common/ParameterSetNames.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Common/RemediationCmdletBase.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Common/ResourceIdHelper.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Models/Remediation/PSErrorDefinition.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Models/Remediation/PSRemediation.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Models/Remediation/PSRemediationDeployment.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Models/Remediation/PSRemediationDeplyomentSummary.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Models/Remediation/PSRemediationFilter.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Models/Remediation/PSTypedErrorInfo.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Properties/Resources.Designer.cs
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/Properties/Resources.resx
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/help/AzureRM.PolicyInsights.md
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/help/Get-AzureRmPolicyRemediation.md
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/help/Remove-AzureRmPolicyRemediation.md
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/help/Start-AzureRmPolicyRemediation.md
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/help/Stop-AzureRmPolicyRemediation.md
  src/ResourceManager/PolicyInsights/Commands.PolicyInsights/packages.config
  src/ResourceManager/PolicyInsights/PolicyInsights.sln
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
Labels: Waiting for CI :shipit:

#7514 Add ICMP back to supported AzFw Network protocols
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUD.json
  src/ResourceManager/Network/Commands.Network/AzureFirewall/NetworkRule/NewAzureFirewallNetworkRuleCommand.cs
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewallNetworkRule.md
Labels: Network, needs-revision

#7448 appgw custom error cmdlet
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD2.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD3.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableSslOptions.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableWafRuleSets.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/AddAzureApplicationGatewayCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/AddAzureApplicationGatewayHttpListenerCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/AzureCustomErrorBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/GetAzureApplicationGatewayCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/GetAzureApplicationGatewayHttpListenerCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/NewAzureApplicationGatewayCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/RemoveAzureApplicationGatewayCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/RemoveAzureApplicationGatewayHttpListenerCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/SetAzureApplicationGatewayCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/CustomError/SetAzureApplicationGatewayHttpListenerCustomErrorCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/HttpListener/AzureApplicationGatewayHttpListenerBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/NewAzureApplicationGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/Az.Network.psd1
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.psd1
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGateway.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayCustomError.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayHttpListener.cs
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayHttpListenerCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmApplicationGatewayCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmApplicationGatewayHttpListenerCustomError.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmApplicationGatewayCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmApplicationGatewayHttpListenerCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayCustomError.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayHttpListenerCustomError.md
  src/ResourceManager/Network/Commands.Network/packages.config
  tools/CredScanSuppressions.json
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.6.0.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.6.0.symbols.nupkg
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Network/SignatureIssues.csv
Labels: Cmdlet Review Complete, Waiting for CI :shipit:

#7565 Ensure that Az.psm1 is signed and used by Az.psd1 as RootModule
  .gitignore
  build.proj
  tools/Az/Az.psd1
  tools/Az/Az.psm1
  tools/PublishModules.ps1
Labels: needs-review

#7642 Fix error message for failed login when providing tenant domain
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/Models/RMProfileClient.cs
  src/ResourceManager/Profile/Commands.Profile/Properties/Resources.Designer.cs
  src/ResourceManager/Profile/Commands.Profile/Properties/Resources.resx
Labels: needs-review

#7655 Fix for issue #7278
  src/ResourceManager/Profile/Commands.Profile.Test/LoginCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile.Test/TenantCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile/Account/ConnectAzureRmAccount.cs
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  tools/StaticAnalysis/Exceptions/Az.Profile/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Profile/BreakingChangeIssues.csv
Labels: needs-review

#7631 AzureRM.Automation 6.0.1-preview version update
  src/ResourceManager/Automation/Commands.Automation/AzureRM.Automation.psd1
  src/ResourceManager/Automation/Commands.Automation/ChangeLog.md
  src/ResourceManager/Automation/Commands.Automation/Properties/AssemblyInfo.cs
Labels: needs-review

#7604 Fix resource id list scenario for Get-AzureRmResource
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Resource/GetAzureResourceCmdlet.cs
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
Labels: needs-review

#7666 make resource name more unique random
  src/ResourceManager/Insights/Commands.Insights.Test/Commands.Insights.Test.csproj
  src/ResourceManager/Insights/Commands.Insights.Test/ScenarioTests/AzureRmDiagnosticSettingTests.cs
  src/ResourceManager/Insights/Commands.Insights.Test/ScenarioTests/AzureRmDiagnosticSettingTests.ps1
  src/ResourceManager/Insights/Commands.Insights.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AzureRmDiagnosticSettingTests/TestSetAzureRmDiagnosticSettingCreate.json
  src/ResourceManager/Insights/Commands.Insights.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AzureRmDiagnosticSettingTests/TestSetAzureRmDiagnosticSettingUpdate.json
  src/ResourceManager/Insights/Commands.Insights/ChangeLog.md
  src/ResourceManager/Insights/Commands.Insights/Diagnostics/SetAzureRmDiagnosticSettingCommand.cs
  src/ResourceManager/Insights/Commands.Insights/help/Set-AzureRmDiagnosticSetting.md
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectionMonitor.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectivityCheck.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestFlowLog.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestGetNextHop.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestGetSecurityGroupView.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestGetTopology.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestPacketCapture.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestProvidersList.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestReachabilityReport.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestTroubleshoot.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestVerifyIPFlow.json
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/ChangeLog.md
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/ServiceFabricClusterCertificateCmdlet.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/ServiceFabricClusterCmdlet.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/UpdateAzureRmServiceFabricDurability.cs
Labels: needs-review

#7676 [Storage] Fix help to Create storage context with Oauth
  src/Storage/Commands.Storage/help/New-AzureStorageContext.md
Labels: needs-review

#7628 Masked Enumeration Property Fixes for ScaleAction and MetricTrigger
  src/ResourceManager/Insights/Commands.Insights/ChangeLog.md
  src/ResourceManager/Insights/Commands.Insights/TransitionalClasses/MetricTrigger.cs
  src/ResourceManager/Insights/Commands.Insights/TransitionalClasses/ScaleAction.cs
Labels: needs-review

#7694 Fixed typo
  src/ResourceManager/Insights/Commands.Insights/help/Get-AzureRmAlertRule.md
Labels: Waiting for CI :shipit:

#7675 Fix bug in StaticAnalysis that threw when renaming a parameter
  tools/StaticAnalysis/BreakingChangeAnalyzer/ParameterSetMetadataHelper.cs
  tools/StaticAnalysis/Exceptions/Az.Profile/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Profile/BreakingChangeIssues.csv
  tools/StaticAnalysis/StaticAnalysis.Test/BreakingChangeAnalyzerTests.cs
  tools/StaticAnalysis/StaticAnalysis.Test/TestCmdlets/BreakingChangeAnalyzer_Cmdlet.cs
  tools/Tools.Common/SerializedCmdlets/TestCmdletsModule.dll.json
Labels: needs-review

#7684 Fix issue where Disconnect-AzureRmAccount would throw if not connected
  src/ResourceManager/Profile/Commands.Profile/Account/DisconnectAzureRmAccount.cs
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
Labels: needs-review

#7686 Fix Network test recordings for October release
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectionMonitor.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectivityCheck.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestFlowLog.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestGetNextHop.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestGetSecurityGroupView.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestGetTopology.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestPacketCapture.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestProvidersList.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestReachabilityReport.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestTroubleshoot.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestVerifyIPFlow.json
Labels: needs-review

#7654 Removing psm1 placeholder files
  .gitignore
  build.proj
  src/StackAdmin/AzureRM/AzureRM.psd1
  src/StackAdmin/AzureRM/AzureRM.psm1
  src/StackAdmin/AzureStack/AzureStack.psd1
  src/StackAdmin/AzureStack/AzureStack.psm1
  tools/Az/Az.psm1
  tools/AzureRM/AzureRM.psm1
  tools/CheckSignature.ps1
  tools/UpdateModules.ps1
Labels: Waiting for CI :shipit:, needs-review

#7704 Update generated NRP's cmdlets & tests
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/ApplicationSecurityGroupTestsGenerated.ps1
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/LoadBalancerTestsGenerated.ps1
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/RouteTableTestsGenerated.ps1
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Generated/UsageTestsGenerated.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationSecurityGroupTestsGenerated/TestApplicationSecurityGroupCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationSecurityGroupTestsGenerated/TestApplicationSecurityGroupCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestBackendAddressPoolCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestFrontendIPConfigurationCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestFrontendIPConfigurationCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestInboundNatPoolCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestInboundNatPoolCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestInboundNatRuleCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestInboundNatRuleCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestLoadBalancerCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestLoadBalancerCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestLoadBalancingRuleCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestLoadBalancingRuleCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestOutboundRuleCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestOutboundRuleCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestProbeCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTestsGenerated/TestProbeCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteTableCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteTableCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.UsageTestsGenerated/TestUsageCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network/Generated/RouteTable/GetAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/Generated/RouteTable/Route/AddAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/Generated/RouteTable/SetAzureRMRouteTableCommand.cs
Labels: needs-review

#7598 Fix for SetAzureRmVMChefExtension -BootstrapOptions and -JsonAttribute not working
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Extension/Chef/SetAzureVMChefExtension.cs
Labels: Sprint Candidate, needs-revision

#7699 EventHub: Added swtich parameter - EnableKafka in New-AzureRmEventHubNamespace
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/Commands.EventGrid.Test.Netcore.csproj
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/Commands.EventGrid.Test.csproj
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/packages.config
  src/ResourceManager/EventHub/Commands.EventHub.Test/Commands.EventHubs.Test.Netcore.csproj
  src/ResourceManager/EventHub/Commands.EventHub.Test/Commands.EventHubs.Test.csproj
  src/ResourceManager/EventHub/Commands.EventHub.Test/ScenarioTests/EventHubsTests.ps1
  src/ResourceManager/EventHub/Commands.EventHub.Test/ScenarioTests/NamespaceTests.ps1
  src/ResourceManager/EventHub/Commands.EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.EventHubsTests/EventHubsAuthorizationRulesCRUD.json
  src/ResourceManager/EventHub/Commands.EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.NamespaceTests/NamespaceAuthorizationRulesCRUD.json
  src/ResourceManager/EventHub/Commands.EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.NamespaceTests/NamespaceCRUD.json
  src/ResourceManager/EventHub/Commands.EventHub.Test/packages.config
  src/ResourceManager/EventHub/Commands.EventHub/ChangeLog.md
  src/ResourceManager/EventHub/Commands.EventHub/Cmdlets/Namespace/NewAzureEventHubNamespace.cs
  src/ResourceManager/EventHub/Commands.EventHub/Commands.EventHub.Netcore.csproj
  src/ResourceManager/EventHub/Commands.EventHub/Commands.EventHub.csproj
  src/ResourceManager/EventHub/Commands.EventHub/Models/PSNamespaceAttributes.cs
  src/ResourceManager/EventHub/Commands.EventHub/Utilities/EventHubsClient.cs
  src/ResourceManager/EventHub/Commands.EventHub/help/New-AzureRmEventHubNamespace.md
  src/ResourceManager/EventHub/Commands.EventHub/packages.config
  src/ResourceManager/IotHub/Commands.IotHub.Test/Commands.IotHub.Test.Netcore.csproj
  src/ResourceManager/IotHub/Commands.IotHub.Test/Commands.IotHub.Test.csproj
  src/ResourceManager/IotHub/Commands.IotHub.Test/packages.config
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
Labels: needs-review
