Repository Azure/azure-powershell, pull requests merged in 2018-02, with the labels that each got.

#5484 Availability Set Name and Progress fix
  src/Common/Commands.Common/AzureLongRunningJob.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithAvailabilitySet2.json
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: needs-review

#5483 Availabilityset name fix
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithAvailabilitySet2.json
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#5487 Progress Bar update
  src/ResourceManager/Compute/Commands.Compute/Strategies/AsyncCmdletExtensions.cs
Labels: Waiting for On Demand

#5488 Set-AzureRmApplicationGatewayBackendAddressPool doc fix
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayBackendAddressPool.md
Labels: needs-review

#5507 Fix ConvertTo-AzureRmVhd's ShouldProcess function input
  src/ResourceManager/Compute.ManagedService/Commands.Compute.ManagedService/Tools/ConvertTo-AzureRmVhd.ps1
Labels: Preview, needs-review

#5458 Update encryption client for Data Factory to fix encryption issue
  src/ResourceManager/DataFactories/ChangeLog.md
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/Commands.DataFactories.Test.csproj
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/packages.config
  src/ResourceManager/DataFactories/Commands.DataFactories/Commands.DataFactories.csproj
  src/ResourceManager/DataFactories/Commands.DataFactories/packages.config
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.csproj
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/packages.config
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Changelog.md
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Commands.DataFactoryV2.csproj
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/packages.config
Labels: needs-review

#5465 Add missing test project in TestMappings
  TestMappings.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/ScenarioTests/ApiManagementTests.ps1
Labels: needs-review

#5466 Add alias to New-AzureRmAutomationModule
  src/ResourceManager/Automation/AzureRM.Automation.psd1
  src/ResourceManager/Automation/ChangeLog.md
  src/ResourceManager/Automation/Commands.Automation/Cmdlet/NewAzureAutomationModule.cs
  src/ResourceManager/Automation/Commands.Automation/Commands.Automation.csproj
  src/ResourceManager/Automation/Commands.Automation/StartupScripts/AzureRmAutomationStartup.ps1
  src/ResourceManager/Automation/Commands.Automation/StartupScripts/sample.ps1
Labels: needs-review

#5505 Regenerated Route Table, added generated tests
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTestsGenerated.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTestsGenerated.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteTableCRUDAllParameters.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTestsGenerated/TestRouteTableCRUDMinimalParameters.json
  src/ResourceManager/Network/Commands.Network/RouteTable/GetAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/NewAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/RemoveAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/AddAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/GetAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/NewAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/RemoveAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/SetAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/SetAzureRMRouteTableCommand.cs
Labels: needs-review

#5511 Update versions, changelog, and artifacts for VM custom Image processing
  src/ResourceManager/Compute/AzureRM.Compute.psd1
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Properties/AssemblyInfo.cs
Labels: needs-review

#5514 Network tests, minor fixes and documentation
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/ResourceManager/Network/README.md
Labels: Waiting for On Demand

#5456 obsolete enable/disable Encryption in new and set Storage Account
  src/ResourceManager/Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/Common.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.cs
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccountKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNetworkRule.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountEncryptionServiceNone.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingGetAccountToGetKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingSetStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestRemoveAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureRmStorageAccountKeySource.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccountStorageV2.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetCurrentStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/NewAzureStorageAccount.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/SetAzureStorageAccount.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/StorageAccountBaseCmdlet.cs
  src/ResourceManager/Storage/Commands.Management.Storage/help/New-AzureRmStorageAccount.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Set-AzureRmStorageAccount.md
Labels: needs-revision

#5474 Move short running tests from On-Demand to checkin
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/AEMExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/DiskRPTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/RunnerTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/ScenarioTests/DataFactoryGatewayTests.cs
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/ScenarioTests/DataFactoryTests.cs
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/ScenarioTests/HubTests.cs
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/ScenarioTests/LinkedServiceTests.cs
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/ScenarioTests/TableTests.cs
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Models/UtilitiesTests.cs
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights.Test/ScenarioTests/QueryTests.cs
  src/ResourceManager/RedisCache/Commands.RedisCache.Test/ScenarioTests/Utilitytests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Models.ResourceGroups/ResourceClientTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ResourceGroupDeployments/RemoveAzureResourceGroupDeploymentCommandTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ResourceGroupDeployments/StopAzureResourceGroupDeploymentCommandTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ResourceGroupDeployments/TestAzureResourceGroupDeploymentCommandTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/DeploymentTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceLockTests.cs
  src/ServiceManagement/RecoveryServices/Commands.RecoveryServices.Test/ScenarioTests/RecoveryServicesTests.cs
Labels: Waiting for On Demand

#5491 Update module PSM1 creation tools to skip modules with a pre-created …
  src/ResourceManager/Compute.ManagedService/AzureRM.Compute.ManagedService.psd1
  src/ResourceManager/Compute.ManagedService/Commands.Compute.ManagedService/AzureRM.Compute.ManagedService.psm1
  src/ResourceManager/Compute.ManagedService/Commands.Compute.ManagedService/Commands.Compute.ManagedService.csproj
  src/ResourceManager/Compute.ManagedService/Commands.Compute.ManagedService/Tools/ConvertTo-AzureRmVhd.ps1
  tools/PublishModules.ps1
  tools/UpdateModules.ps1
Labels: Waiting for On Demand

#5022 [Network] EnableHttp2 flag in Application Gateway
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD2.json
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/NewAzureApplicationGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGateway.cs
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGateway.md
  src/ResourceManager/Network/Network.sln
Labels: Waiting for On Demand

#5525 Fix changelog
  src/ResourceManager/Network/ChangeLog.md
Labels: needs-review

#5539 Update appveyor.yml
  appveyor.yml
Labels: needs-review

#5516 Make ADE pre-req sample script backwards compatible to older version …
  src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1
Labels: needs-revision

#5542 Update appveyor.yml
  appveyor.yml
Labels: needs-review

#5349 Add edition selection for integration runtime
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.csproj
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/packages.config
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Changelog.md
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Commands.DataFactoryV2.csproj
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Constants.cs
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/IntegrationRuntimes/SetAzureDataFactoryIntegrationRuntimeCommand.cs
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Models/PSManagedIntegrationRuntime.cs
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/help/Set-AzureRmDataFactoryV2IntegrationRuntime.md
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/packages.config
Labels: Waiting for On Demand

#5368 Update developer documentation, templates, and README
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  documentation/Repo-Tasks-Module.md
  documentation/development-docs/azure-powershell-design-guidelines.md
  documentation/development-docs/azure-powershell-developer-guide.md
  documentation/development-docs/cleaning-up-commits.md
  documentation/development-docs/help-generation.md
  documentation/development-docs/piping-in-powershell.md
  documentation/development-docs/should-process-confirm-impact.md
  documentation/migration-guides/Stack/migration-guide.1.2.11.md
  documentation/migration-guides/migration-guide.2.0.0.md
  documentation/migration-guides/migration-guide.3.0.0.md
  documentation/migration-guides/migration-guide.4.0.0.md
  documentation/migration-guides/migration-guide.5.0.0.md
  documentation/testing-docs/RunSmokeTests.md
  documentation/testing-docs/repo-tasks-module.md
  documentation/testing-docs/using-azure-test-framework.md
  tools/Repo-Tasks.psd1
  tools/Repo-Tasks.psm1
Labels: needs-review

#5543 Azure Automation live smoke test fixes
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestRemoveAResourceTest.json
  tools/AutomationTestFramework/Management/ModuleUploader.ps1
  tools/AutomationTestFramework/Management/PackageGenerator.ps1
Labels: needs-review

#5504 Add examples for policy parameter object and file.
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyAssignment.md
Labels: needs-review

#5549 Update GracePeriod explanation for failover groups
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabaseFailoverGroup.md
Labels: Waiting for On Demand

#5558 Update Set-AzureRmSqlDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabase.md
Labels: Waiting for On Demand

#5557 Update Set-AzureRmSqlElasticPool.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlElasticPool.md
Labels: Waiting for On Demand

#5556 Update New-AzureRmSqlElasticPool.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlElasticPool.md
Labels: Waiting for On Demand

#5555 Update New-AzureRmSqlDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlDatabase.md
Labels: Waiting for On Demand

#5554 Adding the Property (DisableBGPRoutePropagation) in a RouteGroup
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/NetworkResourcesController.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteTableTests/TestRouteWithDisableBgpRoutePropagation.json
  src/ResourceManager/Network/Commands.Network/Models/PSRouteTable.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/NewAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmRouteTable.md
Labels: Waiting for On Demand

#5553 SerViceBus: Corrected typo in AzureRM.ServiceBus.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/AzureRM.ServiceBus.md
Labels: Waiting for On Demand

#5546 Add Iptags to Powershell
  src/ResourceManager/Network/AzureRM.Network.Netcore.psd1
  src/ResourceManager/Network/AzureRM.Network.psd1
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpAddressTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpAddressTests/TestPublicIpAddressCRUDIpTag.json
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/PSPublicIpAddress.cs
  src/ResourceManager/Network/Commands.Network/Models/PSPublicIpTag.cs
  src/ResourceManager/Network/Commands.Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
  src/ResourceManager/Network/Commands.Network/PublicIpAddress/NewAzurePublicIpTagCommand.cs
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmPublicIpAddress.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmPublicIpTag.md
Labels: Waiting for On Demand

#5547 Update appveyor.yml
  appveyor.yml
Labels: needs-review

#5529 [Compute] Fix ErrorAction issue for Get cmdlets
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineProfileTests.ps1
  src/ResourceManager/Compute/Commands.Compute/Generated/ContainerService/Config/NewAzureRmContainerServiceConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/ContainerService/ContainerServiceGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Disk/DiskGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Image/Config/NewAzureRmImageConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Image/ImageGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/ResourceSku/ResourceSkuListMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/Config/NewAzureRmSnapshotConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/Config/NewAzureRmSnapshotUpdateConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/SnapshotGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineRunCommand/VirtualMachineRunCommandGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssNetworkInterfaceConfigurationCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssIpConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetListSkusMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetRollingUpgrade/VirtualMachineScaleSetRollingUpgradeGetLatestMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/help/Add-AzureRmVmssNetworkInterfaceConfiguration.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmss.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmssIpConfig.md
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
Labels: Waiting for On Demand

#5572 Update links in developer guide
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: Waiting for On Demand

#5581 Fix example for updating Automation module
  src/ResourceManager/Automation/Commands.Automation/help/Set-AzureRmAutomationModule.md
Labels: needs-review

#5536 Powershell for ManagementGroups
  TestMappings.json
  src/ResourceManager/EventHub/Commands.EventHub/help/Get-AzureRmEventHubGeoDRConfiguration.md
  src/ResourceManager/ManagementGroups/AzureRM.ManagementGroups.psd1
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/Commands.ManagementGroups.Test.csproj
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/GetAzureRmManagementGroupTests.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/GetAzureRmManagementGroupTests.ps1
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/GroupSubscriptionOperationsTests.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/GroupSubscriptionOperationsTests.ps1
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/NewAzureRmManagementGroupTests.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/NewAzureRmManagementGroupTests.ps1
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/RemoveAzureRmManagementGroupTests.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/RemoveAzureRmManagementGroupTests.ps1
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/TestController.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/UpdateAzureRmManagementGroupTests.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/ScenarioTests/UpdateAzureRmManagementGroupTests.ps1
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.GetAzureRmManagementGroupTests/TestGetManagementGroup.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.GetAzureRmManagementGroupTests/TestGetManagementGroupWithExpand.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.GetAzureRmManagementGroupTests/TestGetManagementGroupWithExpandAndRecurse.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.GroupSubscriptionOperationsTests/TestNewRemoveManagementGroupSubscription.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.NewAzureRmManagementGroupTests/TestNewManagementGroup.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.NewAzureRmManagementGroupTests/TestNewManagementGroupWithDisplayName.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.NewAzureRmManagementGroupTests/TestNewManagementGroupWithDisplayNameAndParentId.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.NewAzureRmManagementGroupTests/TestNewManagementGroupWithParentId.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.RemoveAzureRmManagementGroupTests/TestRemoveManagementGroup.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.UpdateAzureRmManagementGroupTests/TestUpdateManagementGroupWithDisplayName.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.UpdateAzureRmManagementGroupTests/TestUpdateManagementGroupWithDisplayNameAndParentId.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/SessionRecords/Commands.ManagementGroups.Test.ScenarioTests.UpdateAzureRmManagementGroupTests/TestUpdateManagementGroupWithParentId.json
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups.Test/packages.config
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Cmdlets/GetAzureRmManagementGroup.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Cmdlets/NewAzureRmManagementGroup.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Cmdlets/NewAzureRmManagementGroupSubscription.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Cmdlets/RemoveAzureRmManagementGroup.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Cmdlets/RemoveAzureRmManagementGroupSubscription.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Cmdlets/UpdateAzureRmManagementGroup.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Commands.ManagementGroups.csproj
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Common/AzureManagementGroupsCmdletBase.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Common/Constants.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Common/Utility.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/MSSharedLibKey.snk
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Microsoft.Azure.Commands.ManagementGroups.Format.ps1xml
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Models/PSManagementGroup.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Models/PSManagementGroupChildInfo.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Models/PSManagementGroupInfo.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Models/PSParentGroupInfo.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Properties/AssemblyInfo.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Resource.Designer.cs
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/Resource.resx
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/AzureRM.ManagementGroups.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/Get-AzureRmManagementGroup.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/New-AzureRmManagementGroup.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/New-AzureRmManagementGroupSubscription.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/Remove-AzureRmManagementGroup.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/Remove-AzureRmManagementGroupSubscription.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/help/Update-AzureRmManagementGroup.md
  src/ResourceManager/ManagementGroups/Commands.ManagementGroups/packages.config
  src/ResourceManager/ManagementGroups/ManagementGroups.sln
  src/ResourceManager/ManagementGroups/NuGet.Config
  tools/CreateMappings_rules.json
Labels: Preview, Waiting for On Demand

#5571 remove redundant tests
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/AuthorizationTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/AuthorizationTests.ps1
Labels: needs-review

#5528 Udpate Notice.txt of Cognitive Services
  src/ResourceManager/CognitiveServices/ChangeLog.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/Properties/Resources.Designer.cs
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/Properties/Resources.resx
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/notice.txt
Labels: needs-review

#5595 Fix for issue https://github.com/Azure/azure-powershell/issues/5295
  src/ResourceManager/Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/RoleAssignmentTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaByServicePrincipal.json
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClientExtensions.cs
Labels: Waiting for On Demand

#5589 Fix for the issue https://github.com/Azure/azure-powershell/issues/5192
  src/ResourceManager/Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClientExtensions.cs
  src/ResourceManager/Resources/Commands.Resources/Properties/Resources.Designer.cs
  src/ResourceManager/Resources/Commands.Resources/Properties/Resources.resx
Labels: Waiting for On Demand

#5515 Scenario tests for image names.
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmImageName.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmImageNameMicrosoftSqlUbuntu.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssImageName.json
Labels: Waiting for On Demand

#5617 Update example in KeyVault
  src/ResourceManager/KeyVault/ChangeLog.md
  src/ResourceManager/KeyVault/Commands.KeyVault/help/Set-AzureRmKeyVaultAccessPolicy.md
Labels: needs-review

#5627 Fix resource tests duration
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourcesController.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourcesRecordMatcher.cs
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestMoveAResourceTest.json
Labels: Waiting for On Demand

#5570 Adls data plane task updateversion
  src/ResourceManager/DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/packages.config
Labels: Waiting for On Demand

#5633 Add support of query scale out and firewall and api version 2017-08-01
  src/ResourceManager/AnalysisServices/AzureRM.AnalysisServices.psd1
  src/ResourceManager/AnalysisServices/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/Commands.AnalysisServices.Test.csproj
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/ScenarioTests/AsTests.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/ScenarioTests/AsTests.ps1
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServer.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerFirewall.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerScaleOutIn.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerScaleUpDown.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestNegativeAnalysisServicesServer.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/packages.config
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands.AnalysisServices.csproj
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands/NewAzureRmAnalysisServicesFirewallConfig.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands/NewAzureRmAnalysisServicesFirewallRule.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands/NewAzureRmAnalysisServicesServer.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands/SetAzureRmAnalysisServicesServer.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/AnalysisServicesClient.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/AzureAnalysisServicesServer.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/PsAzureAnalysisServicesFirewallConfig.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/PsAzureAnalysisServicesFirewallRule.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/ServerSku.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/AzureRM.AnalysisServices.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/New-AzureRmAnalysisServicesFirewallConfig.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/New-AzureRmAnalysisServicesFirewallRule.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/New-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Set-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/packages.config
  tools/StaticAnalysis/Exceptions/SignatureIssues.csv
Labels: Waiting for On Demand

#5476 Scenario Test for New-AzureRmVm with AvailabilitySet.
  src/ResourceManager/Common/Commands.Common.Strategies/Commands.Common.Strategies.csproj
  src/ResourceManager/Common/Commands.Common.Strategies/UniqueId.cs
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithAvailabilitySet.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithDefaultDomainName.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithDefaultDomainName2.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssWithoutDomainName.json
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/PublicIPAddressStrategy.cs
Labels: Waiting for On Demand

#5608 Fix issue in .NET Core where service principal key is being disposed
  src/Common/Commands.Common.Authentication/Authentication/ServicePrincipalTokenProvider.cs
Labels: Waiting for On Demand

#5638 fix netcore2.0 path issue in Kube module
  src/ResourceManager/Kubernetes/AzureRM.Kubernetes.Netcore.psd1
  src/ResourceManager/Kubernetes/Commands.Kubernetes/Commands.Kubernetes.Netcore.csproj
Labels: Waiting for On Demand
