Repository Azure/azure-powershell, pull requests merged in 2018-05, with the labels that each got.

#6077 Fix issue where context autosave isn't enabled by default
  src/Common/Commands.Common.Authentication/AzureSessionInitializer.cs
Labels: needs-review

#6051 KeyVault Network tests
  TestMappings.json
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Commands.KeyVault.Test.csproj
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/ScenarioTests/KeyVaultManagementController.cs
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestNetworkSet.json
  src/ResourceManager/KeyVault/KeyVault.sln
Labels: Preview, needs-review

#6064 Fix for issue #5830
  src/ResourceManager/Compute/Commands.Compute/Properties/Resources.Designer.cs
  src/ResourceManager/Compute/Commands.Compute/Properties/Resources.resx
  src/ResourceManager/Compute/Commands.Compute/Strategies/Client.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#6091 Revert changes to KeyVault stable branch
  TestMappings.json
  src/ResourceManager/KeyVault/AzureRM.KeyVault.psd1
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Commands.KeyVault.Test.csproj
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/ScenarioTests/KeyVaultManagementController.cs
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestNetworkSet.json
  src/ResourceManager/KeyVault/KeyVault.sln
Labels: needs-review

#6071 Make AAD application optional to enable encryption without AAD
  src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1
Labels: needs-review

#6063 LogicApp docfix based on customer response
  src/ResourceManager/LogicApp/ChangeLog.md
  src/ResourceManager/LogicApp/Commands.LogicApp/help/Stop-AzureRmLogicAppRun.md
Labels: needs-revision

#6083 Update Get-AzureRmServiceFabricCluster.md, fixed copy paste mistake in description
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/help/Get-AzureRmServiceFabricCluster.md
Labels: Waiting for CI

#6065 Fix GetCustomArmClient
  src/Common/Commands.Common.Authentication/Factories/ClientFactory.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/LocationCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ResourceGroupCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ResourceTypeCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ScopeCompleter.cs
Labels: needs-review

#6059 [new-doc] how to generate and use format.ps1xml file (iss #865)
  documentation/development-docs/generate-format.ps1xml-file.md
Labels: needs-review

#6100 Update Set-AzureRmVMDiskEncryptionExtension.md
  src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMDiskEncryptionExtension.md
  src/ResourceManager/Compute/Stack/Commands.Compute/help/Set-AzureRmVMDiskEncryptionExtension.md
Labels: Waiting for CI

#5975 SignalR
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/SignalR/Commands.SignalR.Test/Commands.SignalR.Test.csproj
  src/ResourceManager/SignalR/Commands.SignalR.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/ScenarioTests/AzureRmSignalRTests.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/ScenarioTests/AzureRmSignalRTests.ps1
  src/ResourceManager/SignalR/Commands.SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestNewAzureRmSignalR.json
  src/ResourceManager/SignalR/Commands.SignalR.Test/TestController.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/packages.config
  src/ResourceManager/SignalR/Commands.SignalR/AzureRM.SignalR.psd1
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/GetAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/GetAzureRmSignalRKey.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/IWithInputObject.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/IWithResourceGroupAndName.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/IWithResourceId.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/NewAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/NewAzureRmSignalRKey.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/RemoveAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/SignalRCmdletBase.cs
  src/ResourceManager/SignalR/Commands.SignalR/Commands.SignalR.csproj
  src/ResourceManager/SignalR/Commands.SignalR/MSSharedLibKey.snk
  src/ResourceManager/SignalR/Commands.SignalR/Microsoft.Azure.Commands.SignalR.format.ps1xml
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSResource.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSResourceSku.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSSignalRKeys.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSSignalRResource.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSTrackedResource.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/AssemblyInfo.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/Resources.Designer.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/Resources.resx
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/Client.cs
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/CmdletExtensions.cs
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/ResourceManager/ResourceGroupStrategy.cs
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/SignalRRp/SignalRStrategy.cs
  src/ResourceManager/SignalR/Commands.SignalR/help/AzureRM.SignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Get-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Get-AzureRmSignalRKey.md
  src/ResourceManager/SignalR/Commands.SignalR/help/New-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/New-AzureRmSignalRKey.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Remove-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/packages.config
  src/ResourceManager/SignalR/NuGet.config
  src/ResourceManager/SignalR/SignalR.sln
  tools/CreateMappings_rules.json
  tools/LocalFeed/Microsoft.Azure.Management.SignalR.0.9.0-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.SignalR.0.9.0-preview.symbols.nupkg
Labels: Preview, Waiting for On Demand

#6125 Update New-AzureStorageAccountSASToken.md to make hyperlink clickable
  src/Storage/Commands.Storage/help/New-AzureStorageAccountSASToken.md
Labels: Waiting for CI

#6123 Support to set based branch for git clone content repo
  appveyor.yml
Labels: needs-review

#6126 adding support for listing pending certificates
  src/ResourceManager/KeyVault/ChangeLog.md
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands.KeyVault.csproj
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/GetAzureKeyVaultCertificate.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Models/IKeyVaultDataServiceClient.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Models/KeyVaultCertificateFilterOptions.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Models/KeyVaultDataServiceClient.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/help/Get-AzureKeyVaultCertificate.md
Labels: Preview, Waiting for CI

#6121 Updates and fixes according to the SignalR RP changes
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/GetAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/GetAzureRmSignalRKey.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/NewAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/NewAzureRmSignalRKey.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/RemoveAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/help/Get-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Get-AzureRmSignalRKey.md
  src/ResourceManager/SignalR/Commands.SignalR/help/New-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/New-AzureRmSignalRKey.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Remove-AzureRmSignalR.md
Labels: Waiting for On Demand

#6124 Adding cmdlets for Managed Instance and Managed database CRUD operations (new pull request)
  src/ResourceManager/Sql/AzureRM.Sql.Netcore.psd1
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/Common.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedDatabaseCrudScenarioTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedDatabaseCrudScenarioTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestCreateManagedDatabase.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestGetManagedDatabase.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestRemoveManagedDatabase.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestRestoreManagedDatabase.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstance.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstanceWithIdentity.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestGetManagedInstance.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestRemoveManagedInstance.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestSetManagedInstance.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestUpdateManagedInstance.json
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/Common/Constants.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Services/AzureSqlDatabaseBackupCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Cmdlet/AzureSqlManagedDatabaseCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Cmdlet/GetAzureSqlManagedDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Cmdlet/NewAzureSqlManagedDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Cmdlet/RemoveAzureSqlManagedDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Cmdlet/RestoreAzureSqlManagedDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Model/AzureSqlManagedDatabaseModel.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/GetAzureSqlManagedInstance.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/ManagedInstanceCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/RemoveAzureSqlManagedInstance.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Cmdlet/UpdateAzureSqlManagedInstance.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/ManagedInstance/Services/AzureSqlManagedInstanceCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlManagedDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlManagedDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/help/Remove-AzureRmSqlManagedDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Remove-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/help/Restore-AzureRmSqlManagedDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/help/Update-AzureRmSqlManagedInstance.md
  src/ResourceManager/Sql/Commands.Sql/packages.config
Labels: Preview, Waiting for On Demand

#5957 Auditing bug fix: Impossible to remove AuditActionGroups when providing AuditActions(And vice versa)
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/BlobAuditingTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.BlobAuditingTests/TestBlobAuditingOnDatabase.json
  src/ResourceManager/Sql/Commands.Sql/Auditing/Cmdlet/AuditingSettings/SetAzureSqlDatabaseAuditing.cs
Labels: needs-revision

#6101 Add migration guide for Azure PowerShell 6.0.0 release
  documentation/migration-guides/migration-guide.6.0.0.md
Labels: needs-review

#6068 Add New srp features to Storage: Location Usage
  src/ResourceManager/Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.cs
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccountKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageLocationUsage.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageSubscriptionUsage.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNetworkRule.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingGetAccountToGetKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingSetStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestRemoveAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureRmStorageAccountKeySource.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccountStorageV2.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetCurrentStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/packages.config
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.Netcore.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageUsage.cs
  src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageUsage.md
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Storage.7.2.0-preview.nupkg
Labels: Preview, Waiting for On Demand

#6135 Remove spaces from DeviceProvisioningServices tags field
  src/ResourceManager/DeviceProvisioningServices/AzureRM.DeviceProvisioningServices.psd1
Labels: needs-review

#6138 Fix Set-AzureRmSqlDatabaseBackupLongTermRetentionPolicy Cmdlet
  appveyor.yml
  documentation/development-docs/generate-format.ps1xml-file.md
  documentation/migration-guides/migration-guide.6.0.0.md
  src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMDiskEncryptionExtension.md
  src/ResourceManager/Compute/Stack/Commands.Compute/help/Set-AzureRmVMDiskEncryptionExtension.md
  src/ResourceManager/DeviceProvisioningServices/AzureRM.DeviceProvisioningServices.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/BlobAuditingTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.BlobAuditingTests/TestBlobAuditingOnDatabase.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupStretchTests/TestStretchDatabaseListRestorePoints.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestListDatabaseRestorePoints.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2Backup.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2Policy.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestNewDatabaseRestorePoint.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestRemoveDatabaseRestorePoint.json
  src/ResourceManager/Sql/Commands.Sql/Auditing/Cmdlet/AuditingSettings/SetAzureSqlDatabaseAuditing.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/SetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs
  src/ResourceManager/TrafficManager/ChangeLog.md
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/Profile/GetAzureTrafficManagerProfile.cs
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/help/Get-AzureRmTrafficManagerProfile.md
  src/Storage/Commands.Storage/help/New-AzureStorageAccountSASToken.md
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
Labels: Preview, Waiting for CI, needs-review

#6141 [Release 6.0.1] Fix issue where environments are unavailable with no default context
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/AzureRmProfile.cs
  src/ResourceManager/Profile/AzureRM.Profile.psd1
  src/ResourceManager/Profile/ChangeLog.md
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#6139 SignalR bug fix for null pointer exception
  src/ResourceManager/SignalR/ChangeLog.md
  src/ResourceManager/SignalR/Commands.SignalR/AzureRM.SignalR.psd1
  src/ResourceManager/SignalR/Commands.SignalR/Properties/Resources.Designer.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/Resources.resx
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/Client.cs
  src/ResourceManager/SignalR/SignalR.sln
  tools/LocalFeed/Microsoft.Azure.Management.SignalR.0.9.0-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.SignalR.0.9.0-preview.symbols.nupkg
Labels: Waiting for On Demand

#6145 Fix Set-AzureRmSqlDatabaseBackupLongTermRetentionPolicy Cmdlet
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupStretchTests/TestStretchDatabaseListRestorePoints.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestListDatabaseRestorePoints.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2Backup.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2Policy.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestNewDatabaseRestorePoint.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestRemoveDatabaseRestorePoint.json
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/SetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs
Labels: Waiting for On Demand, needs-review

#6120 [Stack] Removing the local nugets and accommodating a rename change in the SDK
  src/StackAdmin/Azs.AzureBridge.Admin/Module/Azs.AzureBridge.Admin/Azs.Azurebridge.Admin.psd1
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Azs.Backup.Admin.psd1
  src/StackAdmin/Azs.Commerce.Admin/Module/Azs.Commerce.Admin.csproj
  src/StackAdmin/Azs.Commerce.Admin/Module/Azs.Commerce.Admin/Azs.Commerce.Admin.psd1
  src/StackAdmin/Azs.Commerce.Admin/Module/packages.config
  src/StackAdmin/Azs.Commerce.Admin/Tests/Azs.Commerce.Admin.Tests.csproj
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Azs.Compute.Admin.psd1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Gallery.Admin/Module/Azs.Gallery.Admin/Azs.Gallery.Admin.psd1
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/Azs.Infrastructureinsights.Admin.psd1
  src/StackAdmin/Azs.KeyVault.Admin/Module/Azs.KeyVault.Admin/Azs.Keyvault.Admin.psd1
  src/StackAdmin/Azs.Network.Admin/Module/Azs.Network.Admin/Azs.Network.Admin.psd1
  src/StackAdmin/Azs.Storage.Admin/Module/Azs.Storage.Admin/Azs.Storage.Admin.psd1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Azs.Subscriptions.Admin.psd1
  src/StackAdmin/Azs.Subscriptions/Help/Get-AzsDelegatedProviderOffer.md
  src/StackAdmin/Azs.Subscriptions/Help/Get-AzsOffer.md
  src/StackAdmin/Azs.Subscriptions/Help/Get-AzsSubscription.md
  src/StackAdmin/Azs.Subscriptions/Help/New-AzsSubscription.md
  src/StackAdmin/Azs.Subscriptions/Help/Set-AzsSubscription.md
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions.csproj
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Azs.Subscriptions.psd1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerDefinitionCommands/New-SubscriptionObject.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsDelegatedProviderOffer.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsOffer.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsSubscription.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerPathCommands/New-AzsSubscription.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerPathCommands/Remove-AzsSubscription.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Generated.PowerShell.Commands/SwaggerPathCommands/Set-AzsSubscription.ps1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/PSSwaggerUtility/PSSwaggerUtility.Resources.psd1
  src/StackAdmin/Azs.Subscriptions/Module/packages.config
  src/StackAdmin/Azs.Subscriptions/Subscriptions.json
  src/StackAdmin/Azs.Subscriptions/Subscriptions.psmeta.json
  src/StackAdmin/Azs.Subscriptions/Tests/Azs.Subscriptions.Tests.csproj
  src/StackAdmin/Azs.Subscriptions/Tests/SessionRecords/SubscriptionsClient/TestGetDelegatedProviderOffers.json
  src/StackAdmin/Azs.Subscriptions/Tests/SessionRecords/SubscriptionsClient/TestGetSubscription.json
  src/StackAdmin/Azs.Subscriptions/Tests/SessionRecords/SubscriptionsClient/TestListDelegatedProviderOffers.json
  src/StackAdmin/Azs.Subscriptions/Tests/SessionRecords/SubscriptionsClient/TestListRootOffers.json
  src/StackAdmin/Azs.Subscriptions/Tests/SessionRecords/SubscriptionsClient/TestListSubscriptions.json
  src/StackAdmin/Azs.Subscriptions/Tests/packages.config
  src/StackAdmin/Azs.Subscriptions/Tests/src/Helper.cs
  src/StackAdmin/Azs.Subscriptions/generate.ps1
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Azs.Update.Admin.psd1
  src/StackAdmin/AzureStack/AzureStack.psd1
  tools/LocalFeed/Microsoft.AzureStack.Management.AzureBridge.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Backup.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Commerce.Admin.0.1.1-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Compute.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Fabric.Admin.0.2.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Gallery.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.InfrastructureInsights.Admin.0.2.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.KeyVault.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Network.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Storage.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Subscriptions.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Subscriptions.Admin.0.1.0-preview.nupkg
  tools/LocalFeed/Microsoft.AzureStack.Management.Update.Admin.0.1.0-preview.nupkg
Labels: Waiting for On Demand

#6153 Fix git push related bug in appveyor.yml
  appveyor.yml
Labels: needs-review

#6158 fixed typo on example #3
  src/ResourceManager/ApiManagement/Commands.ApiManagement/help/Set-AzureRmApiManagementPolicy.md
Labels: Waiting for CI

#6144 Version changes on the "AzureRM.Storage.Location" branch to prepare for the preview release of the storage module
  documentation/migration-guides/migration-guide.6.0.0.md
  src/ResourceManager/DeviceProvisioningServices/AzureRM.DeviceProvisioningServices.psd1
  src/ResourceManager/Storage/AzureRM.Storage.psd1
  src/ResourceManager/Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage/Properties/AssemblyInfo.cs
Labels: needs-review

#6127 Fix issue #5998 - certificates created without server authentication …
  src/ResourceManager/ServiceFabric/ChangeLog.md
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/ServiceFabricClusterCertificateCmdlet.cs
Labels: needs-review

#6023 Upgrade parameters on Cmdlet Get-AzureRmConsumptionUsageDetail
  src/ResourceManager/Consumption/ChangeLog.md
  src/ResourceManager/Consumption/Commands.Consumption.Test/Commands.Consumption.Test.csproj
  src/ResourceManager/Consumption/Commands.Consumption.Test/ScenarioTests/TestController.cs
  src/ResourceManager/Consumption/Commands.Consumption.Test/ScenarioTests/UsageDetailsTests.cs
  src/ResourceManager/Consumption/Commands.Consumption.Test/ScenarioTests/UsageDetailsTests.ps1
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListBillingPeriodUsageDetails.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListBillingPeriodUsageDetailsWithDateFilter.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListBillingPeriodUsageDetailsWithExpand.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListBillingPeriodUsageDetailsWithFilter.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListBillingPeriodUsageDetailsWithFilterOnInstanceName.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListInvoiceUsageDetails.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListInvoiceUsageDetailsWithExpand.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListInvoiceUsageDetailsWithFilter.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListUsageDetails.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListUsageDetailsWithDateFilter.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListUsageDetailsWithExpand.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListUsageDetailsWithFilter.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.UsageDetailsTests/TestListUsageDetailsWithMeterDetailsExpand.json
  src/ResourceManager/Consumption/Commands.Consumption.Test/packages.config
  src/ResourceManager/Consumption/Commands.Consumption/Cmdlets/UsageDetails/GetAzureRmConsumptionUsageDetail.cs
  src/ResourceManager/Consumption/Commands.Consumption/Commands.Consumption.Netcore.csproj
  src/ResourceManager/Consumption/Commands.Consumption/Commands.Consumption.csproj
  src/ResourceManager/Consumption/Commands.Consumption/Common/AzureConsumptionCmdletBase.cs
  src/ResourceManager/Consumption/Commands.Consumption/Common/Constants.cs
  src/ResourceManager/Consumption/Commands.Consumption/Models/PSUsageDetail.cs
  src/ResourceManager/Consumption/Commands.Consumption/help/Get-AzureRmConsumptionUsageDetail.md
  src/ResourceManager/Consumption/Commands.Consumption/packages.config
  src/ResourceManager/Consumption/documentation/upcoming-breaking-changes.md
Labels: Cmdlet Review Complete, Waiting for On Demand

#6167 [Release 6.0.1] Merge master --> preview
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/AzureRmProfile.cs
  src/ResourceManager/Profile/AzureRM.Profile.psd1
  src/ResourceManager/Profile/ChangeLog.md
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#6147 Improving naming for Long Running Operations
  src/Common/Commands.Common/AzurePSCmdlet.cs
Labels: needs-review

#6184 Update Remove-AzureRmVirtualNetworkGatewayDefaultSite.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmVirtualNetworkGatewayDefaultSite.md
Labels: needs-review

#6187 Update azure-powershell-design-guidelines.md for AsJob
  documentation/development-docs/azure-powershell-design-guidelines.md
Labels: needs-review

#6131 Update SQL version for preview release
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/AssemblyInfo.cs
Labels: Preview, needs-review

#6190 Update Set-AzureRmVirtualNetwork.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmVirtualNetwork.md
Labels: needs-review

#6094 Add PS CmdLets for Express Route Circuit Connection Resource
  src/ResourceManager/Network/AzureRM.Network.psd1
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Common.ps1
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCircuitTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCircuitTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ExpressRouteCircuitTests/TestExpressRouteCircuitConnectionCRUD.json
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/Connection/AddAzureExpressRouteCircuitConnectionConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/Connection/AzureExpressRouteCircuitConnectionConfigBase.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/Connection/GetAzureExpressRouteCircuitConnectionConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/Connection/RemoveAzureExpressRouteCircuitConnectionConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/PSExpressRouteCircuitConnection.cs
  src/ResourceManager/Network/Commands.Network/Models/PSPeering.cs
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmExpressRouteCircuitConnectionConfig.md
  src/ResourceManager/Network/Commands.Network/help/AzureRM.Network.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmExpressRouteCircuitConnectionConfig.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmExpressRouteCircuitConnectionConfig.md
Labels: Cmdlet Review Complete, Waiting for On Demand

#6197 Update License.rtf
  setup/media/License.rtf
Labels: needs-review

#6200 Fix flaky ArgumentCompleter tests
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/LocationCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ResourceGroupCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ResourceTypeCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ScopeCompleter.cs
  src/ResourceManager/Profile/Commands.Profile.Test/ArgumentCompleterTests.cs
  src/ResourceManager/Profile/Commands.Profile.Test/ArgumentCompleterTests.ps1
  src/ResourceManager/Profile/Commands.Profile.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ArgumentCompleterTests/TestLocationCompleter.json
  src/ResourceManager/Profile/Commands.Profile.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ArgumentCompleterTests/TestResourceGroupCompleter.json
Labels: needs-review

#5960 [Storage] Support create storage context with OAuth
  src/Common/Commands.Common.Authentication.Abstractions/AzureEnvironment.cs
  src/Common/Commands.Common.Authentication.Abstractions/AzureEnvironmentConstants.cs
  src/Common/Commands.Common.Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/Models/PSAzureEnvironment.cs
  src/ResourceManager/Profile/Commands.Profile.Test/EnvironmentCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile.Test/TypeConversionTests.cs
  src/ResourceManager/Profile/Commands.Profile/Environment/AddAzureRMEnvironment.cs
  src/ResourceManager/Profile/Commands.Profile/Environment/SetAzureRMEnvironment.cs
  src/ResourceManager/Profile/Commands.Profile/help/Add-AzureRmEnvironment.md
  src/ResourceManager/Profile/Commands.Profile/help/Set-AzureRmEnvironment.md
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/packages.config
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  src/Storage/Commands.Storage.Test/Commands.Storage.Test.csproj
  src/Storage/Commands.Storage.Test/app.config
  src/Storage/Commands.Storage.Test/packages.config
  src/Storage/Commands.Storage/Commands.Storage.Netcore.csproj
  src/Storage/Commands.Storage/Commands.Storage.csproj
  src/Storage/Commands.Storage/Common/Cmdlet/NewAzureStorageContext.cs
  src/Storage/Commands.Storage/help/New-AzureStorageContext.md
  src/Storage/Commands.Storage/packages.config
  tools/LocalFeed/Microsoft.Azure.Storage.DataMovement.0.7.2.nupkg
  tools/LocalFeed/WindowsAzure.Storage.9.2.0.nupkg
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/MissingAssemblies.csv
Labels: Preview

#6043 [Azure Analysis Services] Enable associate/dissociate gateway with AS.
  src/ResourceManager/AnalysisServices/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/ScenarioTests/AsTests.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/ScenarioTests/AsTests.ps1
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands.AnalysisServices.csproj
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands/NewAzureRmAnalysisServicesServer.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Commands/SetAzureRmAnalysisServicesServer.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/AnalysisServicesClient.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/AzureAnalysisServicesServer.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/ServerGateway.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/ServerSku.cs
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/AzureRM.AnalysisServices.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Get-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/New-AzureRmAnalysisServicesFirewallConfig.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/New-AzureRmAnalysisServicesFirewallRule.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/New-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Remove-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Resume-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Set-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Suspend-AzureRmAnalysisServicesServer.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/help/Test-AzureRmAnalysisServicesServer.md
Labels: Waiting for On Demand

#6188 Fix null parameter for recurse in set-azurermstoreitemaclentry
  src/ResourceManager/DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/ScenarioTests/AdlsAliasTests.ps1
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/ScenarioTests/AdlsTests.ps1
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.Netcore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/SetAzureRmDataLakeStoreItemAclEntry.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Remove-AzureRmDataLakeStoreItemAclEntry.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Set-AzureRmDataLakeStoreItemAcl.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Set-AzureRmDataLakeStoreItemAclEntry.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/packages.config
Labels: needs-revision

#6207 [Azure Stack] BugFix for Shutdown ScaleUnit node cmdlet.
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerDefinitionCommands/Submit-AzsScaleUnitNodeForceShutdown.ps1
Labels: needs-review

#6210 [Storage] Support OAuth (moves PR #5960) to AzureRM.Storage.Location
  src/Common/Commands.Common.Authentication.Abstractions/AzureEnvironment.cs
  src/Common/Commands.Common.Authentication.Abstractions/AzureEnvironmentConstants.cs
  src/Common/Commands.Common.Authentication.Abstractions/Extensions/AzureEnvironmentExtensions.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/Models/PSAzureEnvironment.cs
  src/ResourceManager/Profile/Commands.Profile.Test/EnvironmentCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile.Test/TypeConversionTests.cs
  src/ResourceManager/Profile/Commands.Profile/Environment/AddAzureRMEnvironment.cs
  src/ResourceManager/Profile/Commands.Profile/Environment/SetAzureRMEnvironment.cs
  src/ResourceManager/Profile/Commands.Profile/help/Add-AzureRmEnvironment.md
  src/ResourceManager/Profile/Commands.Profile/help/Set-AzureRmEnvironment.md
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/packages.config
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  src/Storage/Commands.Storage.Test/Commands.Storage.Test.csproj
  src/Storage/Commands.Storage.Test/app.config
  src/Storage/Commands.Storage.Test/packages.config
  src/Storage/Commands.Storage/Commands.Storage.Netcore.csproj
  src/Storage/Commands.Storage/Commands.Storage.csproj
  src/Storage/Commands.Storage/Common/Cmdlet/NewAzureStorageContext.cs
  src/Storage/Commands.Storage/help/New-AzureStorageContext.md
  src/Storage/Commands.Storage/packages.config
  tools/LocalFeed/Microsoft.Azure.Storage.DataMovement.0.7.2.nupkg
  tools/LocalFeed/WindowsAzure.Storage.9.2.0.nupkg
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/MissingAssemblies.csv
Labels: needs-review

#6213 Example fixes for `New-AzureRmStorageAccount`.
  src/ResourceManager/Storage/Commands.Management.Storage/help/New-AzureRmStorageAccount.md
Labels: Waiting for CI

#6222 Fix Export-AzureRmDataLakeStoreChildItemProperties help file
  src/ResourceManager/DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Export-AzureRmDataLakeStoreChildItemProperties.md
Labels: Waiting for CI

#6221 Update Test-AzureRmTestDnsAvailability Help
  src/ResourceManager/Network/Commands.Network/help/AzureRM.Network.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmVirtualNetworkPeering.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmVirtualNetworkPeering.md
  src/ResourceManager/Network/Commands.Network/help/Test-AzureRmDnsAvailability.md
Labels: Waiting for CI

#6148 Add -ExtendedProperty parameter to hosted service cmdlets
  src/ServiceManagement/ChangeLog.md
  src/ServiceManagement/Common/Commands.ScenarioTest/Resources/ServiceManagement/ServiceManagementTests.ps1
  src/ServiceManagement/Common/Commands.ScenarioTest/SessionRecords/Microsoft.WindowsAzure.Commands.ScenarioTest.ServiceManagementTests/TestGetAzureVM.json
  src/ServiceManagement/Compute/Commands.ServiceManagement/HostedServices/NewAzureDeployment.cs
  src/ServiceManagement/Compute/Commands.ServiceManagement/HostedServices/NewAzureService.cs
  src/ServiceManagement/Compute/Commands.ServiceManagement/HostedServices/SetAzureService.cs
  src/ServiceManagement/Compute/Commands.ServiceManagement/Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml
Labels: needs-review

#6235 Fix to `New-AzureRmAks` help text.
  src/ResourceManager/Aks/Commands.Aks/help/New-AzureRmAks.md
Labels: Waiting for CI

#6117 Juliet/feat/addprotocolconfig
  src/ResourceManager/Network/AzureRM.Network.psd1
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Models/PSNetworkWatcherProtocolConfiguration.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTroubleshootingDetails.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTroubleshootingRecommendedActions.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTroubleshootingResult.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/ConnectionMonitor/SetAzureNetworkWatcherConnectionMonitorCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherFlowLogStatusCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherNextHopCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherReachabilityProvidersListCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherSecurityGroupViewCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherTopologyCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureNetworkWatcherTroubleshootingResult.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/GetAzureRMNetworkWatcherReachabilityReportCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/NetworkWatcherBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/NewAzureNetworkWatcherProtocolConfiguration.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/PacketCapture/GetAzureNetworkWatcherPacketCaptureCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/PacketCapture/NewAzureNetworkWatcherPacketCaptureCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/PacketCapture/NewPacketCaptureFilterCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/PacketCapture/PacketCaptureBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/PacketCapture/RemoveAzureNetworkWatcherPacketCaptureCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/PacketCapture/StopAzureNetworkWatcherPacketCaptureCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/RemoveAzureNetworkWatcherCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/SetAzureNetworkWatcherConfigFlowLogCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/StartAzureNetworkWatcherResourceTroubleshootingCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/TestAzureNetworkWatcherConnectivityCommand.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/TestAzureNetworkWatcherIPFlowCommand.cs
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRMNetworkWatcherReachabilityReport.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcher.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherConnectionMonitor.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherConnectionMonitorReport.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherFlowLogStatus.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherNextHop.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherPacketCapture.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherReachabilityProvidersList.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherSecurityGroupView.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherTopology.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherTroubleshootingResult.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmNetworkWatcher.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmNetworkWatcherConnectionMonitor.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmNetworkWatcherPacketCapture.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmNetworkWatcherProtocolConfiguration.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmPacketCaptureFilterConfig.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmNetworkWatcher.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmNetworkWatcherConnectionMonitor.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmNetworkWatcherPacketCapture.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmNetworkWatcherConfigFlowLog.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmNetworkWatcherConnectionMonitor.md
  src/ResourceManager/Network/Commands.Network/help/Start-AzureRmNetworkWatcherConnectionMonitor.md
  src/ResourceManager/Network/Commands.Network/help/Start-AzureRmNetworkWatcherResourceTroubleshooting.md
  src/ResourceManager/Network/Commands.Network/help/Stop-AzureRmNetworkWatcherConnectionMonitor.md
  src/ResourceManager/Network/Commands.Network/help/Stop-AzureRmNetworkWatcherPacketCapture.md
  src/ResourceManager/Network/Commands.Network/help/Test-AzureRmNetworkWatcherConnectivity.md
  src/ResourceManager/Network/Commands.Network/help/Test-AzureRmNetworkWatcherIPFlow.md
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/SignatureIssues.csv
Labels: Waiting for On Demand

#6237 Fix issue with Clear-AzureRmContext
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchApplicationPackageTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/CertificateTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeUserTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/FileTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobScheduleTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/PoolTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/TaskTests.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/AzureRmProfile.cs
  src/ResourceManager/Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile.Test/ContextCmdletTests.cs
Labels: Waiting for On Demand

#6151 [Storage] Support Immutability Policy in AzureRm.Storage
  src/ResourceManager/Storage/AzureRM.Storage.psd1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageBlobTests.cs
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageBlobTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainer.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerLegalHold.json
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/AddAzureStorageContainerLegalHold.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/GetAzureStorageContainer.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/GetAzureStorageContainerImmutabilityPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/LockAzureStorageContainerImmutabilityPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/NewAzureStorageContainer.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/RemoveAzureStorageContainer.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/RemoveAzureStorageContainerImmutabilityPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/RemoveAzureStorageContainerLegalHold.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/SetAzureStorageContainerImmutabilityPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/StorageBlobBaseCmdlet.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Blob/UpdateAzureStorageContainer.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/Microsoft.Azure.Commands.Management.Storage.format.ps1xml
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSContainer.cs
  src/ResourceManager/Storage/Commands.Management.Storage/help/Add-AzureRmStorageContainerLegalHold.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/AzureRM.Storage.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageContainer.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageContainerImmutabilityPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Lock-AzureRmStorageContainerImmutabilityPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/New-AzureRmStorageContainer.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Remove-AzureRmStorageContainer.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Remove-AzureRmStorageContainerImmutabilityPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Remove-AzureRmStorageContainerLegalHold.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Set-AzureRmStorageContainerImmutabilityPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Update-AzureRmStorageContainer.md
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Storage.7.2.0-preview.nupkg
  tools/StaticAnalysis/Exceptions/AssemblyVersionConflict.csv
Labels: needs-revision

#6229 Updating Networking tests with owner attributes
  src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/Constants.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationSecurityGroupTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AvailableEndpointServicesTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/DdosProtectionPlanTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCircuitTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteServiceProviderTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/LoadBalancerTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/LocalNetworkGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/MultiIpConfigOnNicTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkInterfaceTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkSecurityGroupTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/RouteTableTestsGenerated.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/TestDnsAvailabilityTest.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/UsageTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTests.cs
Labels: needs-review

#6264 Add example to Stop-AzureRmResourceGroupDeployment.md
  src/ResourceManager/Resources/Commands.Resources/help/Stop-AzureRmResourceGroupDeployment.md
Labels: needs-review

#6239 Websites: Websites.Strategies are replaced by Common.Strategies library.
  src/ResourceManager/Common/Commands.Common.Strategies.UnitTest/AsyncCmdletExtensionsTest.cs
  src/ResourceManager/Common/Commands.Common.Strategies/AsyncCmdletExtensions.cs
  src/ResourceManager/Common/Commands.Common.Strategies/Commands.Common.Strategies.csproj
  src/ResourceManager/Common/Commands.Common.Strategies/Common.Strategies.Netcore.csproj
  src/ResourceManager/Common/Commands.Common.Strategies/IAsyncCmdlet.cs
  src/ResourceManager/Common/Commands.Common.Strategies/ICmdlet.cs
  src/ResourceManager/Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/Compute/AzureRM.Compute.psd1
  src/ResourceManager/Compute/Commands.Compute/Strategies/AsyncCmdletExtensions.cs
  src/ResourceManager/Websites/AzureRM.Websites.Netcore.psd1
  src/ResourceManager/Websites/AzureRM.Websites.psd1
  src/ResourceManager/Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites.Test/Commands.Websites.Test.csproj
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.cs
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestCreateNewWebAppSimple.json
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/NewAzureWebApp.cs
  src/ResourceManager/Websites/Commands.Websites/Commands.Websites.csproj
  src/ResourceManager/Websites/Commands.Websites/Strategies/ExternalCommand.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/GitCommand.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/ICmdletAdapter.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/PSCmdletAdapter.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/ResourceGroupStrategy.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/SiteStrategy.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/WebClient.cs
  src/ResourceManager/Websites/WebSites.sln
Labels: Waiting for On Demand

#6279 Fix sign job failure with Commands.Common.Websites
  src/Stack.sln
Labels: needs-review

#6275 Remove spaces in location before comparision
  src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1
Labels: needs-review

#6204 Fix flaky long running operation test
  src/ResourceManager/Profile/Commands.Profile.Test/LongRunningCmdletTests.cs
Labels: Waiting for CI

#6282 Update azure-powershell-developer-guide.md
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: Waiting for CI

#6285 Fix local build issues because of a netcore sln file introduced accidentally
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands.ServiceFabric.Netcore.sln
Labels: Waiting for CI

#6196 Fix Issue 5545 - Set Auth Values on UpdateAzureSchedulerServiceBusQueueJobCommand
  src/ResourceManager/Scheduler/ChangeLog.md
  src/ResourceManager/Scheduler/Commands.Scheduler/Cmdlets/UpdateAzureSchedulerServiceBusQueueJobCommand.cs
Labels: Waiting for CI

#6288 Fix AKS doc
  src/ResourceManager/Aks/Commands.Aks/Commands/GetAzureRmAks.cs
  src/ResourceManager/Aks/Commands.Aks/help/Get-AzureRmAks.md
Labels: needs-review

#6218 Fix issue with Properties property of PSResource
  src/ResourceManager/Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/SdkModels/Resources/PSResource.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourcesController.cs
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestGetResourceByComponentsAndProperties.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestGetResourceByIdAndProperties.json
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
Labels: Waiting for On Demand

#6287 Release Maps
  src/ResourceManager/Maps/AzureRM.Maps.psd1
  src/ResourceManager/Maps/ChangeLog.md
Labels: Waiting for CI

#6253 Powershell changes to onboard additional traffic analytics parameters with existing networkwatcher flowlog parameters
  src/Common/Commands.Common.Network/Commands.Common.Network.csproj
  src/Common/Commands.Common.Network/Common/IOperationalInsightWorkspace.cs
  src/ResourceManager/Common/Commands.Common.Strategies/Common.Strategies.Netcore.csproj
  src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/EnvironmentSetupHelper.cs
  src/ResourceManager/Compute.ManagedService/Commands.Compute.ManagedService.Test/Commands.Compute.ManagedService.Test.csproj
  src/ResourceManager/Compute.ManagedService/Commands.Compute.ManagedService.Test/packages.config
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/Network/AzureRM.Network.Netcore.psd1
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/NetworkResourcesController.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestFlowLog.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/PSFlowLog.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTrafficAnalyticsConfigurationProperties.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTrafficAnalyticsProperties.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/SetAzureNetworkWatcherConfigFlowLogCommand.cs
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmNetworkWatcherConfigFlowLog.md
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/Network/Network.sln
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Commands.OperationalInsights.Netcore.csproj
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Commands.OperationalInsights.csproj
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Models/PSWorkspace.cs
  src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.0.1-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.0.1-preview.symbols.nupkg
  tools/StaticAnalysis/Exceptions/SignatureIssues.csv
Labels: Waiting for On Demand

#6296 Update AzureRM.psm1
  tools/AzureRM/AzureRM.psm1
Labels: Waiting for CI

#6303 adding right powershell command
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayRequestRoutingRule.md
Labels: needs-review

#6304 removing adding space causing powershell error in example
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayFrontendPort.md
Labels: needs-review

#6305 Typo in powershell command
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmApplicationGatewayFrontendPort.md
Labels: needs-review

#6271 Add ManagementGroups to AzureRM.Resources and Update to use latest SDK for GA
  src/ResourceManager/Resources/AzureRM.Resources.Netcore.psd1
  src/ResourceManager/Resources/AzureRM.Resources.psd1
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ManagementGroupsTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ManagementGroupsTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourcesController.cs
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroupWithExpand.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroupWithExpandAndRecurse.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroupWithDisplayName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroupWithDisplayNameAndParentId.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroupWithParentId.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewRemoveManagementGroupSubscription.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestRemoveManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateManagementGroupWithDisplayName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateManagementGroupWithDisplayNameAndParentId.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateManagementGroupWithParentId.json
  src/ResourceManager/Resources/Commands.Resources.Test/packages.config
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.Netcore.csproj
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.csproj
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/Common/AzureManagementGroupsCmdletBase.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/Common/Constants.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/Common/Resource.Designer.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/Common/Resource.resx
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/Common/Utility.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/GetAzureRmManagementGroup.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/NewAzureRmManagementGroup.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/NewAzureRmManagementGroupSubscription.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/RemoveAzureRmManagementGroup.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/RemoveAzureRmManagementGroupSubscription.cs
  src/ResourceManager/Resources/Commands.Resources/ManagementGroups/UpdateAzureRmManagementGroup.cs
  src/ResourceManager/Resources/Commands.Resources/Microsoft.Azure.Commands.Resources.format.ps1xml
  src/ResourceManager/Resources/Commands.Resources/Models.ManagementGroups/PSManagementGroup.cs
  src/ResourceManager/Resources/Commands.Resources/Models.ManagementGroups/PSManagementGroupChildInfo.cs
  src/ResourceManager/Resources/Commands.Resources/Models.ManagementGroups/PSManagementGroupInfo.cs
  src/ResourceManager/Resources/Commands.Resources/Models.ManagementGroups/PSParentGroupInfo.cs
  src/ResourceManager/Resources/Commands.Resources/help/AzureRM.Resources.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmManagementGroup.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmManagementGroup.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmManagementGroupSubscription.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmManagementGroup.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmManagementGroupSubscription.md
  src/ResourceManager/Resources/Commands.Resources/help/Update-AzureRmManagementGroup.md
  src/ResourceManager/Resources/Commands.Resources/packages.config
Labels: Waiting for On Demand

#6307 Fix issue with double quotes in change log for versioning tool
  tools/VersionController/Models/VersionBumper.cs
Labels: needs-review

#6319 Fixed Parameter Name
  src/ResourceManager/Storage/Commands.Management.Storage/help/Add-AzureRmStorageAccountNetworkRule.md
Labels: Waiting for CI

#6316 Fix tests JSON recorded files
  src/ResourceManager/PowerBIEmbedded/Commands.PowerBI.Test/SessionRecords/Microsoft.Azure.Commands.PowerBI.Test.ScenarioTests.PowerBITests/TestNegativePBIECapacity.json
  src/ResourceManager/PowerBIEmbedded/Commands.PowerBI.Test/SessionRecords/Microsoft.Azure.Commands.PowerBI.Test.ScenarioTests.PowerBITests/TestPBIECapacity.json
  src/ResourceManager/PowerBIEmbedded/Commands.PowerBI.Test/SessionRecords/Microsoft.Azure.Commands.PowerBI.Test.ScenarioTests.PowerBITests/TestPBIECapacityScale.json
Labels: Waiting for On Demand

#6315 Updating ADF .Net SDK version
  src/ResourceManager/DataFactoryV2/Changelog.md
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/packages.config
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Commands.DataFactoryV2.Netcore.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Commands.DataFactoryV2.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/packages.config
Labels: Waiting for On Demand

#6325 Merge master -> preview
  ChangeLog.md
  src/Common/Commands.Common/AzurePowerShell.cs
  src/ResourceManager/Resources/AzureRM.Resources.psd1
  src/ResourceManager/Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Properties/AssemblyInfo.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ActiveDirectoryTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ActiveDirectoryTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestNewADServicePrincipalWithCustomScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestNewADServicePrincipalWithReaderRole.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestNewADServicePrincipalWithoutApp.json
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADServicePrincipalCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/UpdateAzureADServicePrincipalCommand.cs
  src/ResourceManager/Resources/Commands.Resources/Properties/AssemblyInfo.cs
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmADServicePrincipal.md
  tools/AzureRM/AzureRM.psd1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.ResourceManager.Cmdlets.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.Resources.dll.json
Labels: needs-review

#6243 Fix the issue that AdalConfiguration can't create from real value of resource
  src/Common/Commands.Common.Authentication/Factories/AuthenticationFactory.cs
Labels: Waiting for On Demand

#6240 Create generic task filter and apply to tests, help, and StaticAnalysis
  AzurePowershell.Test.targets
  ModuleMappings.json
  TestMappings.json
  build.proj
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks.Test/Microsoft.Azure.Build.Tasks.Test.csproj
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks.Test/SetGeneratorTester.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks.Test/packages.config
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/FilesChangedTask.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/FilterTask.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/Microsoft.Azure.Build.Tasks.csproj
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/SetGenerator.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/TestSetGenerator.cs
  tools/GenerateHelp.ps1
  tools/StaticAnalysis/BreakingChangeAnalyzer/BreakingChangeAnalyzer.cs
  tools/StaticAnalysis/BreakingChangeAttributesAnalyzer/BreakingChangeAttributesAnalyzer.cs
  tools/StaticAnalysis/DependencyAnalyzer/DependencyAnalyzer.cs
  tools/StaticAnalysis/HelpAnalyzer/HelpAnalyzer.cs
  tools/StaticAnalysis/IStaticAnalyzer.cs
  tools/StaticAnalysis/Program.cs
  tools/StaticAnalysis/SignatureVerifier/SignatureVerifier.cs
Labels: Waiting for On Demand

#6314 Remove Default sku setting from NewAzureVirtualNetworkGateway commandlet
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestVirtualNetworkGatewayCRUD.json
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
Labels: Waiting for On Demand

#6333 Network preview release for Gateway Az support
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestVirtualNetworkGatewayCRUD.json
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
Labels: Waiting for On Demand

#6274 Fix for #4965,
  src/Common/Commands.Common/MetricHelper.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/AzureRMCmdlet.cs
  src/ResourceManager/Profile/ChangeLog.md
Labels: needs-review

#6348 Fix issue with example
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/help/Remove-AzureRmTrafficManagerEndpointConfig.md
Labels: Waiting for CI

#6351 Merge Network updates
  src/Common/Commands.Common.Network/Commands.Common.Network.csproj
  src/Common/Commands.Common.Network/Common/IOperationalInsightWorkspace.cs
  src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/EnvironmentSetupHelper.cs
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/Network/AzureRM.Network.Netcore.psd1
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/NetworkResourcesController.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestFlowLog.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/PSFlowLog.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTrafficAnalyticsConfigurationProperties.cs
  src/ResourceManager/Network/Commands.Network/Models/PSTrafficAnalyticsProperties.cs
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/SetAzureNetworkWatcherConfigFlowLogCommand.cs
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmNetworkWatcherConfigFlowLog.md
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/Network/Network.sln
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Commands.OperationalInsights.Netcore.csproj
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Commands.OperationalInsights.csproj
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Models/PSWorkspace.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  tools/AzureRM/AzureRM.psm1
  tools/StaticAnalysis/Exceptions/AzureRM.Network/SignatureIssues.csv
Labels: Waiting for On Demand
