Repository Azure/azure-powershell, pull requests merged in 2018-06, with the labels that each got.

#6069 [Storage] Support Management Policy in Storage
  src/ResourceManager/Storage/AzureRM.Storage.psd1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.cs
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestAzureStorageAccountManagementPolicy.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccountKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageLocationUsage.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageSubscriptionUsage.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNetworkRule.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingGetAccountToGetKey.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingSetStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestRemoveAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureRmStorageAccountKeySource.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccountStorageV2.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetCurrentStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainer.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerLegalHold.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/packages.config
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.Netcore.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSDataPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Resources.Designer.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Resources.resx
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageAccountManagementPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/RemoveAzureStorageAccountManagementPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/SetAzureStorageAccountManagementPolicy.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/StorageAccountBaseCmdlet.cs
  src/ResourceManager/Storage/Commands.Management.Storage/help/AzureRM.Storage.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageAccountManagementPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Remove-AzureRmStorageAccountManagementPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Set-AzureRmStorageAccountManagementPolicy.md
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Storage.7.3.0-preview.nupkg
  tools/StaticAnalysis/Exceptions/MissingAssemblies.csv
Labels: Preview, needs-review

#6387 Versioning for OperationalInsights
  ChangeLog.md
  src/Common/Commands.Common/AzurePowerShell.cs
  src/ResourceManager/OperationalInsights/AzureRM.OperationalInsights.psd1
  src/ResourceManager/OperationalInsights/ChangeLog.md
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#6326 Add new AzureRM.Sql cmdlets [Get/Set]-AzureRmSqlDatabaseBackupShortTermRetentionPolicy
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestShortTermRetentionPolicy.json
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/AzureSqlDatabaseBackupShortTermRetentionPolicyCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/GetAzureRmSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/SetAzureRmSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Model/AzureSqlDatabaseBackupShortTermRetentionPolicyModel.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Services/AzureSqlDatabaseBackupCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlDatabaseBackupShortTermRetentionPolicy.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabaseBackupShortTermRetentionPolicy.md
  src/ResourceManager/Sql/Commands.Sql/packages.config
  tools/StaticAnalysis/Exceptions/SignatureIssues.csv
Labels: Waiting for On Demand

#6295 Update New-AzureRmAvailabilitySet.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmAvailabilitySet.md
Labels: Waiting for CI

#6381 error in example 2. should be -dayInterval not -dailyInterval
  src/ResourceManager/Automation/Commands.Automation/help/New-AzureRMAutomationSchedule.md
Labels: Waiting for CI

#6380 Update New-AzureRmVirtualNetworkGatewayConnection.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmVirtualNetworkGatewayConnection.md
Labels: Waiting for CI

#6346 Update Get-AzureRmVpnClientConfiguration.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmVpnClientConfiguration.md
Labels: Waiting for CI

#6404 Fixed spelling issue in a code comment.
  src/ResourceManager/Compute/Commands.Compute/Models/PSAvailabilitySet.cs
Labels: Waiting for CI

#6409 Merge release-6.2.1 to master
  ChangeLog.md
  src/Common/Commands.Common/AzurePowerShell.cs
  src/ResourceManager/OperationalInsights/AzureRM.OperationalInsights.psd1
  src/ResourceManager/OperationalInsights/ChangeLog.md
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#6377 Move tests from on-demand to checkin
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/AEMExtensionTests.cs
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/ScenarioTests/HubTests.cs
  src/ResourceManager/Dns/Commands.Dns.Test/ScenarioTests/ZoneTests.cs
  src/ResourceManager/Insights/Commands.Insights.Test/ScenarioTests/ActionGroupsTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights.Test/ScenarioTests/QueryTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Models.ResourceGroups/ResourceClientTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ActiveDirectoryTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/DeploymentTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/MoveResourceTest.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceGroupTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/RoleAssignmentTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ElasticPoolCrudTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ServerDisasterRecoveryConfigurationTests.cs
  src/ServiceManagement/Common/Commands.Common.Test/Common/ProfileClientTests.cs
  src/ServiceManagement/RecoveryServices/Commands.RecoveryServices.Test/ScenarioTests/RecoveryServicesTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/DisableAzureRemoteDesktopCommandTest.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/AddAzureNodeWebRoleTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/AddAzureNodeWorkerRoleTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/AddAzurePHPWebRoleTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/AddAzurePHPWorkerRoleTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/AddAzureWebRoleTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/AddAzureWorkerRoleTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Development/Scaffolding/NewAzureRoleTemplateTests.cs
  src/ServiceManagement/Services/Commands.Test/CloudService/Utilities/CloudServiceClientTests.cs
  src/ServiceManagement/Services/Commands.Test/Environment/SetAzureEnvironmentTests.cs
  src/ServiceManagement/Services/Commands.Test/Profile/GetAzurePublishSettingsFileTests.cs
  src/ServiceManagement/Services/Commands.Test/Profile/SelectAzureProfileTests.cs
  src/ServiceManagement/Services/Commands.Test/Websites/ShowAzurePortalTests.cs
  src/ServiceManagement/Services/Commands.Test/Websites/ShowAzureWebsiteTests.cs
Labels: Waiting for CI

#6428 Update the example members
  src/ResourceManager/Resources/Commands.Resources/help/Add-AzureRmADGroupMember.md
Labels: Waiting for CI

#6426 Update KeyVault ChangeLog.md
  src/ResourceManager/KeyVault/ChangeLog.md
Labels: Waiting for CI

#6425 Remove ValidateNotNullOrEmpty validation conditions for SubjectBeginsWith/SubjectEndsWith in Update-AzureRmEventGridSubscription cmdlet to allow changing these parameters to empty string if needed
  src/ResourceManager/EventGrid/ChangeLog.md
  src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/UpdateAzureEventGridSubscription.cs
Labels: Waiting for On Demand

#6424 Version SQL preview module
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/AssemblyInfo.cs
Labels: needs-review

#6342 Add check for change log update in PRs
  build.proj
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/GetPullRequestFileChanges.ps1
  tools/CheckChangeLog.ps1
Labels: needs-review

#6137 Populate context list when no previous context found
  src/ResourceManager/Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile.Test/LoginCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile/Account/ConnectAzureRmAccount.cs
  src/ResourceManager/Profile/Commands.Profile/Models/RMProfileClient.cs
  src/ResourceManager/Profile/Commands.Profile/Properties/Resources.Designer.cs
  src/ResourceManager/Profile/Commands.Profile/Properties/Resources.resx
  src/ResourceManager/Profile/Commands.Profile/help/Connect-AzureRmAccount.md
Labels: Waiting for On Demand

#6116 Allow version update for NetCore psd1 files
  tools/NetCorePsd1Sync/NetCorePsd1Sync/NetCoreDefinitionGenerator.cs
  tools/NetCorePsd1Sync/NetCorePsd1Sync/Program.cs
  tools/NetCorePsd1Sync/NetCorePsd1Sync/Utility/HashtableExtensions.cs
Labels: Waiting for On Demand

#6245 Handle TaskCanceledExceptions for all clients
  src/Common/Commands.Common.Authentication.Test/ClientFactoryHandlerTests.cs
  src/Common/Commands.Common.Authentication.Test/Commands.Common.Authentication.Test.csproj
  src/Common/Commands.Common.Authentication/Commands.Common.Authentication.csproj
  src/Common/Commands.Common.Authentication/Factories/CancelRetryHandler.cs
  src/Common/Commands.Common.Authentication/Factories/ClientFactory.cs
  src/ResourceManager/Profile/ChangeLog.md
Labels: Waiting for On Demand

#6432 Versioning for EventGrid preview
  src/ResourceManager/EventGrid/AzureRM.EventGrid.psd1
  src/ResourceManager/EventGrid/ChangeLog.md
  src/ResourceManager/EventGrid/Commands.EventGrid/Properties/AssemblyInfo.cs
Labels: needs-review

#6437 Fix MinChildEndpoint help text.
  src/ResourceManager/TrafficManager/ChangeLog.md
  src/ResourceManager/TrafficManager/Commands.TrafficManager2/help/Add-AzureRmTrafficManagerEndpointConfig.md
Labels: Waiting for CI

#6435 The name of the cmdlet is wrong in the example
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlDatabaseExpanded.md
Labels: Waiting for CI

#6421 Fixing exception message in EnableAzureRMContextAutoSave to include invalid paths.
  src/ResourceManager/Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/AutoSave/EnableAzureRmContextAutosave.cs
Labels: Waiting for CI

#6440 Version SQL for preview release
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/AssemblyInfo.cs
  src/ResourceManager/Sql/LegacySdk/Properties/AssemblyInfo.cs
Labels: Preview

#6446 Fix bugs in StaticAnalysis and change log check script
  tools/CheckChangeLog.ps1
  tools/StaticAnalysis/Exceptions/AzureRM.Compute/SignatureIssues.csv
  tools/StaticAnalysis/Program.cs
  tools/StaticAnalysis/SignatureVerifier/SignatureIssue.cs
Labels: Waiting for CI

#6431 Fix logic bug in Get-AzureRmVMDiskEncryptionStatus
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineExtensionTests.ps1
  src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/GetAzureDiskEncryptionStatus.cs
Labels: Waiting for On Demand

#6412 Set-AzureRmWebApp used with AppSettings and AssignIdentity parameters ignores the AppSettings #6294
  src/ResourceManager/Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestCreateNewWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestWebAppSwapWithPreviewCompleteSlotSwap.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestWebAppSwapWithPreviewResetSlotSwap.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetWebApp.json
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/SetAzureWebApp.cs
Labels: needs-revision

#6452 Elastic Jobs cmdlet fixes
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Agent/AzureSqlElasticJobAgentCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Agent/GetAzureSqlElasticJobAgent.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Agent/NewAzureSqlElasticJobAgent.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Agent/RemoveAzureSqlElasticJobAgent.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Agent/SetAzureRmSqlElasticJobAgent.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Common/AzureSqlElasticJobsCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Credential/AzureSqlElasticJobCredentialCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Credential/GetAzureSqlElasticJobCredential.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Credential/NewAzureSqlElasticJobCredential.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Credential/RemoveAzureSqlElasticJobCredential.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Credential/SetAzureSqlElasticJobCredential.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Job/AzureSqlElasticJobCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Job/GetAzureSqlElasticJob.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Job/NewAzureSqlElasticJob.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Job/RemoveAzureSqlElasticJob.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Job/SetAzureSqlElasticJob.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobExecution/AzureSqlElasticJobExecutionCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobExecution/GetAzureSqlElasticJobExecution.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobExecution/GetAzureSqlElasticJobStepExecution.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobExecution/GetAzureSqlElasticJobTargetExecution.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobExecution/StartAzureSqlElasticJob.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobExecution/StopAzureSqlElasticJob.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobStep/AddAzureSqlElasticJobStep.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobStep/AzureSqlElasticJobStepCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobStep/GetAzureSqlElasticJobStep.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobStep/RemoveAzureSqlElasticJobStep.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/JobStep/SetAzureSqlElasticJobStep.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Target/AddAzureSqlElasticJobTarget.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Target/AzureSqlElasticJobTargetCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/Target/RemoveAzureSqlElasticJobTarget.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/TargetGroup/AzureSqlElasticJobTargetGroupCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/TargetGroup/GetAzureSqlElasticJobTargetGroup.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/TargetGroup/NewAzureSqlElasticJobTargetGroup.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Cmdlet/TargetGroup/RemoveAzureSqlElasticJobTargetGroup.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Jobs/Services/AzureSqlElasticJobAdapter.cs
Labels: needs-review

#6453 Version sql for preview release
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/AssemblyInfo.cs
  src/ResourceManager/Sql/LegacySdk/Properties/AssemblyInfo.cs
Labels: Preview

#6163 Tab completer for existing resources (Iss #5415)
  src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters/ResourceIdCompleter.cs
  src/ResourceManager/Common/Commands.ResourceManager.Common/Commands.ResourceManager.Common.csproj
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Action/RestartAzureVMCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Action/SetAzureVMCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Action/VirtualMachineActionBaseCmdlet.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/ResourceManager/Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile.Test/ArgumentCompleterTests.cs
  src/ResourceManager/Profile/Commands.Profile.Test/ArgumentCompleterTests.ps1
  src/ResourceManager/Profile/Commands.Profile.Test/Commands.Profile.Test.csproj
  src/ResourceManager/Profile/Commands.Profile.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ArgumentCompleterTests/TestResourceIdCompleter.json
Labels: Waiting for CI

#6460 Update dependencies in packages for netcore
  src/ResourceManager/ApiManagement/AzureRM.ApiManagement.Netcore.psd1
  src/ResourceManager/ApiManagement/Commands.ApiManagement/Commands.ApiManagement.Netcore.csproj
  src/ResourceManager/AzureBatch/AzureRM.Batch.Netcore.psd1
  src/ResourceManager/AzureBatch/Commands.Batch/Commands.Batch.Netcore.csproj
  src/ResourceManager/Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.Netcore.csproj
  src/ResourceManager/Storage/AzureRM.Storage.Netcore.psd1
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.Netcore.csproj
Labels: needs-review

#6471 Update New-AzureRmAks.md
  src/ResourceManager/Aks/Commands.Aks/help/New-AzureRmAks.md
Labels: needs-review

#6450 Consumption Budget Test Fix: Create and destroy a resource group at test time
  src/ResourceManager/Consumption/Commands.Consumption.Test/ScenarioTests/BudgetTests.ps1
  src/ResourceManager/Consumption/Commands.Consumption.Test/SessionRecords/Microsoft.Azure.Commands.Consumption.Test.ScenarioTests.BudgetTests/TestBudgetAtResourceGroupLevel.json
Labels: needs-review

#6458 documentation examples for using cognitive services powershell cmdlets
  src/ResourceManager/CognitiveServices/ChangeLog.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/Get-AzureRmCognitiveServicesAccount.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/Get-AzureRmCognitiveServicesAccountKey.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/Get-AzureRmCognitiveServicesAccountSkus.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/New-AzureRmCognitiveServicesAccount.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/New-AzureRmCognitiveServicesAccountKey.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/Remove-AzureRmCognitiveServicesAccount.md
  src/ResourceManager/CognitiveServices/Commands.Management.CognitiveServices/help/Set-AzureRmCognitiveServicesAccount.md
Labels: needs-review

#6386 SignalR for Preview branch (from AzureRm.SignalR.0.1.0 branch)
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/SignalR/ChangeLog.md
  src/ResourceManager/SignalR/Commands.SignalR.Test/Commands.SignalR.Test.csproj
  src/ResourceManager/SignalR/Commands.SignalR.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/ScenarioTests/AzureRmSignalRTests.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/ScenarioTests/AzureRmSignalRTests.ps1
  src/ResourceManager/SignalR/Commands.SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestNewAzureRmSignalR.json
  src/ResourceManager/SignalR/Commands.SignalR.Test/TestController.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/packages.config
  src/ResourceManager/SignalR/Commands.SignalR/AzureRM.SignalR.psd1
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/GetAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/GetAzureRmSignalRKey.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/IWithInputObject.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/IWithResourceGroupAndName.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/IWithResourceId.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/NewAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/NewAzureRmSignalRKey.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/RemoveAzureRmSignalR.cs
  src/ResourceManager/SignalR/Commands.SignalR/Cmdlets/SignalRCmdletBase.cs
  src/ResourceManager/SignalR/Commands.SignalR/Commands.SignalR.csproj
  src/ResourceManager/SignalR/Commands.SignalR/MSSharedLibKey.snk
  src/ResourceManager/SignalR/Commands.SignalR/Microsoft.Azure.Commands.SignalR.format.ps1xml
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSResource.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSResourceSku.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSSignalRKeys.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSSignalRResource.cs
  src/ResourceManager/SignalR/Commands.SignalR/Models/PSTrackedResource.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/AssemblyInfo.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/Resources.Designer.cs
  src/ResourceManager/SignalR/Commands.SignalR/Properties/Resources.resx
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/Client.cs
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/CmdletExtensions.cs
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/ResourceManager/ResourceGroupStrategy.cs
  src/ResourceManager/SignalR/Commands.SignalR/Strategies/SignalRRp/SignalRStrategy.cs
  src/ResourceManager/SignalR/Commands.SignalR/help/AzureRM.SignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Get-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Get-AzureRmSignalRKey.md
  src/ResourceManager/SignalR/Commands.SignalR/help/New-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/help/New-AzureRmSignalRKey.md
  src/ResourceManager/SignalR/Commands.SignalR/help/Remove-AzureRmSignalR.md
  src/ResourceManager/SignalR/Commands.SignalR/packages.config
  src/ResourceManager/SignalR/NuGet.config
  src/ResourceManager/SignalR/SignalR.sln
  tools/CreateMappings_rules.json
Labels: Waiting for On Demand

#6465 release -> master for netcore modules
  src/ResourceManager/ApiManagement/AzureRM.ApiManagement.Netcore.psd1
  src/ResourceManager/ApiManagement/Commands.ApiManagement/Commands.ApiManagement.Netcore.csproj
  src/ResourceManager/AzureBatch/AzureRM.Batch.Netcore.psd1
  src/ResourceManager/AzureBatch/Commands.Batch/Commands.Batch.Netcore.csproj
  src/ResourceManager/Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.Netcore.csproj
  src/ResourceManager/Storage/AzureRM.Storage.Netcore.psd1
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.Netcore.csproj
Labels: needs-review

#6273 [Profile] Applying format.ps1xml generation mechanism [Iss #6183]
  documentation/development-docs/generate-format.ps1xml-file.md
  src/Common/Commands.Common/Attributes/Ps1XmlAttribute.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/Models/PSAzureContext.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/Models/PSAzureProfile.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/Models/PSAzureTenant.cs
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/AppDomainWorkerShould.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/NewFormatPs1XmlCommandShould.cs
  tools/RepoTasks/RepoTasks.Cmdlets/NewFormatPs1XmlCommand.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsDummyOutput1.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsDummyOutput2.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsOperation.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/AppDomainWorker.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/IReflectionWorker.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/XmlViewDefinition.cs
Labels: Waiting for On Demand

#6497 Merge master to preview for Netcore release
  src/ResourceManager/Aks/Commands.Aks/help/New-AzureRmAks.md
  src/ResourceManager/ApiManagement/Commands.ApiManagement/AzureRM.ApiManagement.Netcore.psd1
  src/ResourceManager/ApiManagement/Commands.ApiManagement/Commands.ApiManagement.Netcore.csproj
  src/ResourceManager/AzureBatch/Commands.Batch/AzureRM.Batch.Netcore.psd1
  src/ResourceManager/AzureBatch/Commands.Batch/Commands.Batch.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.Netcore.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/AzureRM.Storage.Netcore.psd1
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.Netcore.csproj
Labels: needs-review

#6496 Fix links to old wiki pages
  README.md
  documentation/Debugging-StaticAnalysis-Errors.md
  documentation/development-docs/vm-for-partners.md
  documentation/testing-docs/using-azure-test-framework.md
Labels: needs-review

#6444 [Storage] Upgrade Storage SRP SDK to 8.2.0
  src/ResourceManager/Storage/Commands.Management.Storage.Test/Commands.Management.Storage.Test.csproj
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/packages.config
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.Netcore.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageUsage.cs
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Storage.7.3.0-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.Storage.8.2.0-preview.nupkg
Labels: Preview, needs-revision

#6490 Release Consumption
  src/ResourceManager/Consumption/Commands.Consumption/AzureRM.Consumption.psd1
  src/ResourceManager/Consumption/Commands.Consumption/ChangeLog.md
  src/ResourceManager/Consumption/Commands.Consumption/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#6492 Adding example to get Traffic Analytics status
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkWatcherFlowLogStatus.md
Labels: needs-revision

#6507 Ensure that tests are run during the build
  build.proj
Labels: needs-review

#6511 Move flaky batch tests to on-demand
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchAccountTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchApplicationPackageTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchApplicationTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/CertificateTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeUserTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/FileTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobScheduleTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/LocationTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/PoolTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/TaskTests.cs
Labels: needs-review

#6500 Updated documentation for ComputeGeneration parameter
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/RestoreAzureRMSqlDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Cmdlet/NewAzureSqlElasticPool.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Cmdlet/SetAzureSqlElasticPool.cs
  src/ResourceManager/Sql/Commands.Sql/Replication/Cmdlet/NewAzureSqlDatabaseCopy.cs
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlDatabaseCopy.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlElasticPool.md
  src/ResourceManager/Sql/Commands.Sql/help/Restore-AzureRmSqlDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlElasticPool.md
Labels: Waiting for CI

#6510 Fix tag filtering in Get-AzureRmKeyVault
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestListVaults.json
  src/ResourceManager/KeyVault/Commands.KeyVault/ChangeLog.md
  src/ResourceManager/KeyVault/Commands.KeyVault/Models/KeyVaultManagementCmdletBase.cs
Labels: needs-revision

#6517 Fix wrong parameter in example2 ObjectId vs Id
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmRoleAssignment.md
Labels: Waiting for CI

#6463 Clarified User-Defined Restore Points for SQLDW
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/help/New-AzureRmSqlDatabaseRestorePoint.md
Labels: Waiting for CI

#6481 New VPN Client Protocol
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.Netcore.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/VirtualNetworkGatewayOpenVPNTest.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.Netcore.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.Netcore.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.0.3-preview.nupkg
Labels: Waiting for On Demand

#6482 Update Policy cmdlets with Management Group support
  .gitignore
  src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/Assert.ps1
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Commands.Resources.Rest.csproj
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Components/Constants.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/GetAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/GetAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/GetAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/NewAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/NewAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/NewAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PolicyCmdletBase.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PolicyHelpStrings.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/RemoveAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/RemoveAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/RemoveAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/SetAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/SetAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/SetAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/PolicyTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/PolicyTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestGetPolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestGetPolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestGetPolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestNewPolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestNewPolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestNewPolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyAssignmentCRUD.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyAssignmentWithParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUD.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUDAtManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUDAtSubscription.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionWithParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionWithUri.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionCRUD.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionCRUDAtManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionCRUDAtSubscription.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionWithParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestRemovePolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestRemovePolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestRemovePolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestSetPolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestSetPolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestSetPolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.csproj
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicySetDefinition.md
Labels: Waiting for On Demand

#6480 ServiceBus: Added optional Parameter -KeyValue to New-AzureRmServiceBusKey cmdlet
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusQueueTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusServiceTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusTopicTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueueAuth_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpaceAuth_CURD_Tests.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopicAuth_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus/ChangeLog.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/AuthorizationRule/NewAzureServiceBusKey.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Utilities/ServiceBusClient.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/New-AzureRmServiceBusKey.md
Labels: Waiting for CI

#6390 Reservations RP 2018-06-01
  src/ResourceManager/Reservations/Commands.Reservations.Test/Commands.Reservations.Test.Netcore.csproj
  src/ResourceManager/Reservations/Commands.Reservations.Test/Commands.Reservations.Test.csproj
  src/ResourceManager/Reservations/Commands.Reservations.Test/ScenarioTests/ReservationOrderTests.ps1
  src/ResourceManager/Reservations/Commands.Reservations.Test/ScenarioTests/ReservationTests.cs
  src/ResourceManager/Reservations/Commands.Reservations.Test/ScenarioTests/ReservationTests.ps1
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationOrderTests/TestGetReservationOrder.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationOrderTests/TestListReservationOrders.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestGetCatalog.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestGetReservation.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestGetReservationOrderId.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestListReservationHistory.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestListReservations.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestMergeReservation.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestSplitReservation.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestUpdateReservationToShared.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestUpdateReservationToSingle.json
  src/ResourceManager/Reservations/Commands.Reservations.Test/packages.config
  src/ResourceManager/Reservations/Commands.Reservations/ChangeLog.md
  src/ResourceManager/Reservations/Commands.Reservations/Cmdlets/GetCatalog.cs
  src/ResourceManager/Reservations/Commands.Reservations/Cmdlets/PatchReservation.cs
  src/ResourceManager/Reservations/Commands.Reservations/Commands.Reservations.Netcore.csproj
  src/ResourceManager/Reservations/Commands.Reservations/Commands.Reservations.csproj
  src/ResourceManager/Reservations/Commands.Reservations/Custom/PSCatalog.cs
  src/ResourceManager/Reservations/Commands.Reservations/Custom/PSReservation.cs
  src/ResourceManager/Reservations/Commands.Reservations/Microsoft.Azure.Commands.Reservations.Format.ps1xml
  src/ResourceManager/Reservations/Commands.Reservations/help/AzureRM.Reservations.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Get-AzureRmReservation.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Get-AzureRmReservationCatalog.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Get-AzureRmReservationHistory.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Get-AzureRmReservationOrder.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Get-AzureRmReservationOrderId.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Merge-AzureRmReservation.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Split-AzureRmReservation.md
  src/ResourceManager/Reservations/Commands.Reservations/help/Update-AzureRmReservation.md
  src/ResourceManager/Reservations/Commands.Reservations/packages.config
  tools/StaticAnalysis/Exceptions/AzureRM.Network/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Reservations/BreakingChangeIssues.csv
Labels: Cmdlet Review Complete, needs-review

#6514 [Compute] IP Tag, Auto Rollback and OS Upgrade History features for VMSS
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetAutoRollback.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetProfile.json
  src/ResourceManager/Compute/Commands.Compute/AzureRM.Compute.psd1
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssIpConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssIpTagConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/help/AzureRM.Compute.md
  src/ResourceManager/Compute/Commands.Compute/help/Get-AzureRmVmss.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmssConfig.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmssIpConfig.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmssIpTagConfig.md
  src/ResourceManager/Compute/Commands.Compute/help/Update-AzureRmVmss.md
  tools/StaticAnalysis/Exceptions/AzureRM.Compute/SignatureIssues.csv
Labels: Waiting for CI, Waiting for On Demand

#6527 Fix a few issues with AD cmdlets
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/AddAzureADGroupMemberCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADAppCredentialCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/RemoveAzureADGroupMemberCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/help/Add-AzureRmADGroupMember.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmResource.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmADGroupMember.md
Labels: Waiting for On Demand

#6526 Change deployment name from datetime to guid
  src/ResourceManager/Automation/Commands.Automation/Cmdlet/RegisterAzureAutomationDscNode.cs
  src/ResourceManager/Automation/Commands.Automation/Common/AutomationClientDSC.cs
Labels: Waiting for On Demand

#6523 Add support for KeyVault secret reference in TemplateParameterObject of New-AzureRmResourceGroupDeployment
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/CmdletBase/ResourceWithParameterCmdletBase.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/DeploymentTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/DeploymentTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentWithKeyVaultReferenceInParameterObject.json
  src/ResourceManager/Resources/Commands.Resources.Test/StorageAccountTemplate.json
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
Labels: Waiting for On Demand

#6252 [ADLA] - Adding PS support for Catalog ACLs (v1)
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/Commands.DataLakeAnalytics.Test.csproj
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/ScenarioTests/AdlaAliasTests.ps1
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/ScenarioTests/AdlaTests.ps1
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/ScenarioTests/AdlaTestsBase.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaAccount.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaAccountTiers.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaCatalog.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaComputePolicy.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaFirewallRules.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaJob.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestAdlaJobRelationships.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestNegativeAdlaAccount.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaAliasTests/TestNegativeAdlaJob.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaAccount.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaAccountTiers.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaCatalog.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaComputePolicy.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaFirewallRules.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaJob.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestAdlaJobRelationships.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestNegativeAdlaAccount.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeAnalytics.Test.ScenarioTests.AdlaTests/TestNegativeAdlaJob.json
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics.Test/packages.config
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/AzureRM.DataLakeAnalytics.Netcore.psd1
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/AzureRM.DataLakeAnalytics.psd1
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/ChangeLog.md
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands.DataLakeAnalytics.Netcore.csproj
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands.DataLakeAnalytics.csproj
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands/AddAzureRmDataLakeAnalyticsDataSource.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands/GetAzureRmDataLakeAnalyticsCatalogItemAclEntry.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands/NewAzureRmDataLakeAnalyticsAccount.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands/RemoveAzureRmDataLakeAnalyticsCatalogItemAclEntry.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands/SetAzureRmDataLakeAnalyticsCatalogItemAclEntry.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Commands/SetAzureRmDataLakeAnalyticsDataSource.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/AdlDataSource.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/DataLakeAnalyticsClient.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/DataLakeAnalyticsEnums.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/PSDataLakeAnalyticsAccount.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/PSDataLakeAnalyticsAccountBasic.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/PSDataLakeAnalyticsAcl.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/PSDataLakeAnalyticsComputePolicy.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/PSDataLakeStoreAccountInfo.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Models/PSStorageAccountInfo.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Properties/Resources.Designer.cs
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/Properties/Resources.resx
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/help/AzureRM.DataLakeAnalytics.md
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/help/Get-AzureRmDataLakeAnalyticsCatalogItemAclEntry.md
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/help/Remove-AzureRmDataLakeAnalyticsCatalogItemAclEntry.md
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/help/Set-AzureRmDataLakeAnalyticsCatalogItemAclEntry.md
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/packages.config
  tools/StaticAnalysis/Exceptions/AzureRM.DataLakeAnalytics/BreakingChangeIssues.csv
Labels: Waiting for On Demand

#6532 Updated Azure Networking SDK version to 19.1.0
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.Netcore.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.Netcore.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.Netcore.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  tools/LocalFeed/Microsoft.Azure.Management.Network.19.0.3-preview.nupkg
Labels: Waiting for On Demand

#6536 Update Storage changelog
  src/ResourceManager/Storage/Commands.Management.Storage/ChangeLog.md
Labels: Preview, needs-review

#6537 Add script to generate output types for docs
  .gitignore
  build.proj
  tools/NewOutputTypeIndex.ps1
Labels: needs-review

#6539 Expose new SKUs for zone-redundant VirtualNetworkGateways
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.Netcore.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/VirtualNetworkGatewayOpenVPNTest.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/ResizeAzureVirtualNetworkGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmVirtualNetworkGateway.md
  src/ResourceManager/Network/Commands.Network/help/Resize-AzureRmVirtualNetworkGateway.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmVirtualNetworkGateway.md
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.Netcore.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.Netcore.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/Commands.ServiceFabric.Test.csproj
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
Labels: Waiting for On Demand

#6552 Fail build on Static Analysis failure
  build.proj
  tools/StaticAnalysis/Exceptions/AzureRM.RecoveryServices.SiteRecovery/BreakingChangeIssues.csv
Labels: needs-review

#6441 Task adls fix debug messages and sdk fixes
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsAccount.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsAccountTiers.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystem.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystemPermissions.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFirewallRules.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsTrustedIdProvider.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestNegativeAdlsAccount.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsAccount.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsAccountTiers.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystem.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystemPermissions.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFirewallRules.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsTrustedIdProvider.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestNegativeAdlsAccount.json
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.Netcore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/ExportAzureRmDataLakeStoreChildItemProperties.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/RemoveAzureRmDataLakeStoreItemAclEntry.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/SetAzureRmDataLakeStoreItemAcl.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/SetAzureRmDataLakeStoreItemAclEntry.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Properties/Resources.Designer.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Properties/Resources.resx
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Remove-AzureRmDataLakeStoreItemAclEntry.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Set-AzureRmDataLakeStoreItemAcl.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Set-AzureRmDataLakeStoreItemAclEntry.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/packages.config
Labels: Waiting for CI, Waiting for On Demand

#6538 Fix Output Types
  .gitignore
  build.proj
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Dataplane/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Dataplane/Commands/Synchronize-AzureASInstance.cs
  src/ResourceManager/MachineLearning/Commands.MachineLearning/ChangeLog.md
  src/ResourceManager/MachineLearning/Commands.MachineLearning/Cmdlets/CommitmentPlans/MoveAzureMLCommitmentAssociation.cs
  src/ResourceManager/Reservations/Commands.Reservations/AzureRM.Reservations.psd1
  src/ResourceManager/Reservations/Commands.Reservations/ChangeLog.md
  src/ResourceManager/Reservations/Commands.Reservations/Properties/AssemblyInfo.cs
  src/ResourceManager/SignalR/Commands.SignalR/ChangeLog.md
  tools/NewOutputTypeIndex.ps1
  tools/StaticAnalysis/Exceptions/Azure.AnalysisServices/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.MachineLearning/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.RecoveryServices.SiteRecovery/BreakingChangeIssues.csv
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.Reservations.dll.json
Labels: Waiting for CI

#6540 ListItems labeling added; Issue #6524 fix.
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/NewFormatPs1XmlCommandShould.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/AppDomainWorker.cs
Labels: needs-review

#6495 Adding Get-AzureRmRecoveryServicesBackupStatus cmdlet
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Commands.RecoveryServices.Backup.Models.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/CommonModels/ResourceBackupStatus.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.resx
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/IPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureSqlPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/DpmPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/MabPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/IaasVm/Common.ps1
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ProtectionCheckTests.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ProtectionCheckTests.ps1
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ProtectionCheckTests/TestAzureVMProtectionCheck.json
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/AzureRM.RecoveryServices.Backup.psd1
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ChangeLog.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Cmdlets/Backup/GetAzureRmRecoveryServicesBackupStatus.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/Commands.RecoveryServices.Backup.Cmdlets.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ParamHelpMsgs.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/AzureRM.RecoveryServices.Backup.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/help/Get-AzureRmRecoveryServicesBackupStatus.md
Labels: Waiting for CI, Waiting for On Demand

#6533 Azure Firewall Cmdlets
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/packages.config
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.Netcore.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/Commands.Dns.Test.csproj
  src/ResourceManager/Dns/Commands.Dns.Test/packages.config
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallAllocateAndDeallocate.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUD.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/AzureFirewall/ApplicationRule/NewAzureFirewallApplicationRuleCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/ApplicationRuleCollection/NewAzureFirewallApplicationRuleCollectionCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/AzureFirewallBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/GetAzureFirewallCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/NetworkRule/NewAzureFirewallNetworkRuleCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/NetworkRuleCollection/NewAzureFirewallNetworkRuleCollectionCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/RemoveAzureFirewallCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureFirewall/SetAzureFirewallCommand.cs
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.Netcore.psd1
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.psd1
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallApplicationRule.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallApplicationRuleCollection.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallApplicationRuleProtocol.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallBaseRuleCollection.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallIpConfiguration.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallNetworkRule.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallNetworkRuleCollection.cs
  src/ResourceManager/Network/Commands.Network/Models/AzureFirewall/PSAzureFirewallRCAction.cs
  src/ResourceManager/Network/Commands.Network/NetworkSecurityGroup/NetworkSecurityRule/AzureNetworkSecurityRuleConfigBase.cs
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmFirewall.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewall.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewallApplicationRule.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewallApplicationRuleCollection.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewallNetworkRule.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmFirewallNetworkRuleCollection.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmFirewall.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmFirewall.md
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/Network/Stack/AzureRM.Network.psd1
  src/ResourceManager/Network/Stack/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Stack/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallAllocateAndDeallocate.json
  src/ResourceManager/Network/Stack/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUD.json
  src/ResourceManager/RecoveryServices.Backup/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.Netcore.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
Labels: Waiting for On Demand
