Repository Azure/azure-powershell, pull requests merged in 2018-07, with the labels that each got.

#6508 Adding new Cmdlets for Management.Sql to allow customers to add TDE…
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/AddTransparentDataEncryptionCertificateTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/AddTransparentDataEncryptionCertificateTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForManagedInstanceDefaultParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForManagedInstanceDefaultParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerDefaultParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerDefaultParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerInputObjectParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerInputObjectParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerResourceIdParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerResourceIdParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AddTransparentDataEncryptionCertificateTests/TestAddTdeCertificateForSqlServerWithPiping.json
  src/ResourceManager/Sql/Commands.Sql/AzureRM.Sql.Netcore.psd1
  src/ResourceManager/Sql/Commands.Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/Server/Model/AzureSqlServerModel.cs
  src/ResourceManager/Sql/Commands.Sql/Server/Services/AzureSqlServerAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/AddAzureRmSqlManagedInstanceTransparentDataEncryptionCertificate.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/AddAzureRmSqlServerTransparentDataEncryptionCertificate.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Model/AzureRmSqlManagedInstanceTransparentDataEncryptionCertificateModel.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Model/AzureRmSqlServerTransparentDataEncryptionCertificateModel.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Services/AzureSqlDatabaseTransparentDataEncryptionArmAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Services/AzureSqlDatabaseTransparentDataEncryptionArmCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/help/Add-AzureRmSqlManagedInstanceTransparentDataEncryptionCertificate.md
  src/ResourceManager/Sql/Commands.Sql/help/Add-AzureRmSqlServerTransparentDataEncryptionCertificate.md
  src/ResourceManager/Sql/Commands.Sql/help/AzureRM.Sql.md
  src/ResourceManager/Sql/Commands.Sql/packages.config
Labels: needs-review

#6551 Add binscope and policheck to build.proj
  build.proj
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/ChangeLog.md
  src/ResourceManager/DataLakeAnalytics/Commands.DataLakeAnalytics/help/New-AzureRmDataLakeAnalyticsCatalogCredential.md
  src/ResourceManager/Insights/Commands.Insights.Test/ScenarioTests/AutoscaleTests.ps1
  src/ResourceManager/KeyVault/Commands.KeyVault.Test/Scripts/VaultCertificateTests.ps1
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Maps.Test.ScenarioTests.MapsAccountTests/TestGetAccounts.json
  tools/CheckBinScope.ps1
  tools/CheckPoliCheck.ps1
Labels: needs-review

#6584 Supportability updates
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMAccessExtension.md
Labels: Waiting for CI

#6558 Update command to all for pfxfolder and deployment of default reliability tier
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/ChangeLog.md
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/help/New-AzureRmServiceFabricCluster.md
Labels: Waiting for CI

#6593 Spelling corrections
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/help/Get-AzureRmContextAutosaveSetting.md
Labels: Waiting for CI

#6591 Update version for Sql release
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/TDECertificateTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/TDECertificateTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForManagedInstanceDefaultParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForManagedInstanceDefaultParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerDefaultParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerDefaultParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerInputObjectParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerInputObjectParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerResourceIdParameterSetNoPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerResourceIdParameterSetWithPassword.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.TDECertificateTests/TestAddTdeCertificateForSqlServerWithPiping.json
  src/ResourceManager/Sql/Commands.Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.Sql.dll.json
Labels: needs-review

#6596 Fix case sensitivity issue in Get-AzureRmResource
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/SdkClient/ResourceManagerSdkClient.cs
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
Labels: needs-review

#6291 Update cmdlets to support operations at MG scope
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Commands.Resources.Rest.csproj
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/GetAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/GetAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/GetAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/NewAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/NewAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/NewAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PSPolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PolicyCmdletBase.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PolicyHelpStrings.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PsPolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PsPolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/RemoveAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/RemoveAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/RemoveAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/SetAzurePolicyAssignment.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/SetAzurePolicyDefinition.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/SetAzurePolicySetDefinition.cs
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/PolicyTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/PolicyTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestGetPolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestGetPolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestGetPolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestNewPolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestNewPolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestNewPolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyAssignmentCRUD.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyAssignmentWithParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUD.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUDAtManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUDAtSubscription.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionWithParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionWithUri.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyObjectPiping.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionCRUD.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionCRUDAtManagementGroup.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionCRUDAtSubscription.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicySetDefinitionWithParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestRemovePolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestRemovePolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestRemovePolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestSetPolicyAssignmentParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestSetPolicyDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestSetPolicySetDefinitionParameters.json
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Remove-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicyDefinition.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicySetDefinition.md
  src/ResourceManager/Resources/Resources.sln
  tools/StaticAnalysis/Exceptions/AzureRM.Resources/BreakingChangeIssues.csv
Labels: Preview, needs-revision

#6607 [Azure Analysis Services] Add resource group property to AS
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/ScenarioTests/AsTests.ps1
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServer.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerFirewall.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerScaleUpDown.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestNegativeAnalysisServicesServer.json
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices/Models/AzureAnalysisServicesServer.cs
Labels: needs-revision

#6609 Update with script example in the right page
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/Remove-AzureRmVmssExtension.md
Labels: Waiting for CI

#6610 Update AzureRM.Resources for preview release
  src/ResourceManager/Resources/Commands.Resources/AzureRM.Resources.psd1
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.ResourceManager.Cmdlets.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.Commands.Resources.dll.json
Labels: needs-review

#6614 Update New-AzureRMAutomationSchedule.md
  src/ResourceManager/Automation/Commands.Automation/ChangeLog.md
  src/ResourceManager/Automation/Commands.Automation/help/New-AzureRMAutomationSchedule.md
Labels: Waiting for CI

#6616 Update New-AzureRMAutomationSchedule.md
  src/ResourceManager/Automation/Commands.Automation/ChangeLog.md
  src/ResourceManager/Automation/Commands.Automation/help/New-AzureRMAutomationSchedule.md
Labels: Waiting for CI, needs-review

#6620 Relay: Updated markdown for issue 4543
  src/ResourceManager/Relay/Commands.Relay/ChangeLog.md
  src/ResourceManager/Relay/Commands.Relay/help/New-AzureRmRelayAuthorizationRule.md
  src/ResourceManager/Relay/Commands.Relay/help/New-AzureRmRelayNamespace.md
  src/ResourceManager/Relay/Commands.Relay/help/Remove-AzureRmRelayAuthorizationRule.md
  src/ResourceManager/Relay/Commands.Relay/help/Set-AzureRmRelayNamespace.md
Labels: needs-review

#6617 EventHub: Added a readonly property 'PendingReplicationOperationsCount' to PSEventHubDRConfigurationAttributes
  src/ResourceManager/EventHub/Commands.EventHub.Test/Commands.EventHubs.Test.csproj
  src/ResourceManager/EventHub/Commands.EventHub.Test/ScenarioTests/DRConfigurationTests.ps1
  src/ResourceManager/EventHub/Commands.EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.DRConfigurationTests/DRConfigurationsCURD.json
  src/ResourceManager/EventHub/Commands.EventHub.Test/packages.config
  src/ResourceManager/EventHub/Commands.EventHub/ChangeLog.md
  src/ResourceManager/EventHub/Commands.EventHub/Commands.EventHub.Netcore.csproj
  src/ResourceManager/EventHub/Commands.EventHub/Commands.EventHub.csproj
  src/ResourceManager/EventHub/Commands.EventHub/Models/PSEventHubDRConfigurationAttributes.cs
  src/ResourceManager/EventHub/Commands.EventHub/help/Get-AzureRmEventHubGeoDRConfiguration.md
  src/ResourceManager/EventHub/Commands.EventHub/help/Remove-AzureRmEventHubNamespace.md
  src/ResourceManager/EventHub/Commands.EventHub/packages.config
Labels: needs-review

#6631 Add better error message to Set-AzureRmAccessPolicy
  src/ResourceManager/KeyVault/Commands.KeyVault/ChangeLog.md
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Properties/Resources.Designer.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Properties/Resources.resx
Labels: Waiting for CI, needs-review

#6618 Fix for issue #6498
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmss.json
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmss.md
Labels: Waiting for CI, Waiting for On Demand

#6634 Move flaky tests over to CI
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchAccountTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchApplicationPackageTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchApplicationTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/CertificateTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeUserTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/FileTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobScheduleTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/LocationTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/PoolTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/TaskTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/RoleAssignmentTests.cs
Labels: Waiting for On Demand

#6626 [Storage] Fix issue that can't upload blob/file with write only SAS
  src/Storage/Commands.Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Commands.Storage/Blob/StorageDataMovementCmdletBase.cs
  src/Storage/Commands.Storage/ChangeLog.md
  src/Storage/Commands.Storage/File/Cmdlet/SetAzureStorageFileContent.cs
  src/Storage/Commands.Storage/File/StorageFileDataManagementCmdletBase.cs
Labels: needs-revision

#6590 Update Add vm extension command
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/Add-AzureRmVmssExtension.md
Labels: Waiting for CI

#6640 Correct Example 1 Powershell syntax
  src/ResourceManager/Subscription/Commands.Subscription/ChangeLog.md
  src/ResourceManager/Subscription/Commands.Subscription/help/New-AzureRmSubscription.md
Labels: needs-revision

#6641 MSI feature disable functionality updated
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetWebApp.json
  src/ResourceManager/Websites/Commands.Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/SetAzureWebApp.cs
  src/ResourceManager/Websites/Commands.Websites/help/Get-AzureRmAppServicePlanMetrics.md
  src/ResourceManager/Websites/Commands.Websites/help/Get-AzureRmWebAppMetrics.md
  src/ResourceManager/Websites/Commands.Websites/help/Set-AzureRmWebApp.md
Labels: App Services, needs-review

#6646 Add Tag parameter to New/Update-AvailabilitySet
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/AvailabilitySetTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AvailabilitySetTests/TestAvailabilitySet.json
  src/ResourceManager/Compute/Commands.Compute/AvailabilitySets/NewAzureAvailabilitySetCommand.cs
  src/ResourceManager/Compute/Commands.Compute/AvailabilitySets/UpdateAzureAvailabilitySetCommand.cs
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmAvailabilitySet.md
  src/ResourceManager/Compute/Commands.Compute/help/Update-AzureRmAvailabilitySet.md
  src/ResourceManager/Subscription/Commands.Subscription/ChangeLog.md
  src/ResourceManager/Subscription/Commands.Subscription/help/New-AzureRmSubscription.md
Labels: needs-review

#6643 Regenerated RouteTables; Fixes #5518
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/RouteTable/GetAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/NewAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/RemoveAzureRMRouteTableCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/AddAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/GetAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/NewAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/RemoveAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/Route/SetAzureRmRouteConfigCommand.cs
  src/ResourceManager/Network/Commands.Network/RouteTable/SetAzureRMRouteTableCommand.cs
Labels: needs-revision

#6654 Service Bus: added missing #Examples to Start-AzureRmServiceBusMigration.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/ChangeLog.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Start-AzureRmServiceBusMigration.md
Labels: needs-review

#6650 AppGWv2 Changes
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD3.json
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/NewAzureApplicationGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/Sku/AzureApplicationGatewaySkuBase.cs
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGateway.cs
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGateway.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewaySku.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewaySku.md
Labels: needs-review

#6661 Added the common Aks project to netcore
  Azure.PowerShell.Netcore.sln
Labels: Waiting for CI

#6663 Fix datetime handling incorrectly for non-us base culture
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Data Sync/Cmdlet/GetAzureSqlSyncGroupLog.cs
Labels: Waiting for CI

#6655 Added 3rd Example to New-AzureRMVM Documentation
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVM.md
Labels: Waiting for CI

#6666 Fix issue #6659
  src/ResourceManager/KeyVault/Commands.KeyVault/ChangeLog.md
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/help/Set-AzureRmKeyVaultAccessPolicy.md
  tools/StaticAnalysis/Exceptions/AzureRM.KeyVault/BreakingChangeIssues.csv
Labels: needs-review

#6670 Remove a typo from the example
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/help/Remove-AzureRmSqlServerFirewallRule.md
Labels: Waiting for CI

#6681 Update New-AzureRmDisk.md
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmDisk.md
Labels: Waiting for CI

#6612 [Ps1XmlAttribute] Labels test-case added.
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/AppDomainWorkerShould.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/NewFormatPs1XmlCommandShould.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsDummyOutput1.cs
Labels: needs-review

#6665 6473 fix
  src/ResourceManager/Common/Commands.Common.Strategies/ResourceStrategy.cs
  src/ResourceManager/Common/Commands.Common.Strategies/StateExtensions.cs
  src/ResourceManager/Common/Commands.Common.Strategies/TargetStateExtensions.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmss.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssLbErrorScenario.json
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/LoadBalancerStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkStrategy.cs
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
Labels: needs-review

#6683 [Storage] Add Ps1XmlAttribute to Storage cmdlets output types properties.
  src/Common/Commands.Common.Storage/Adapters/WindowsAzure.Storage.8/ResourceModel/AzureStorageBlob.cs
  src/Common/Commands.Common.Storage/Adapters/WindowsAzure.Storage.8/ResourceModel/AzureStorageContainer.cs
  src/Common/Commands.Common.Storage/Adapters/WindowsAzure.Storage.8/ResourceModel/AzureStorageQueue.cs
  src/Common/Commands.Common.Storage/Adapters/WindowsAzure.Storage.8/ResourceModel/AzureStorageTable.cs
  src/Common/Commands.Common.Storage/Commands.Common.Storage.csproj
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage/Microsoft.Azure.Commands.Management.Storage.format.ps1xml
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSNetworkRule.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSStorageAccount.cs
  src/Storage/Commands.Storage/Azure.Storage.Netcore.psd1
  src/Storage/Commands.Storage/Azure.Storage.psd1
  src/Storage/Commands.Storage/ChangeLog.md
  src/Storage/Commands.Storage/Commands.Storage.Netcore.csproj
  src/Storage/Commands.Storage/Commands.Storage.csproj
  src/Storage/Commands.Storage/Microsoft.WindowsAzure.Commands.Storage.format.ps1xml
  src/Storage/Commands.Storage/Microsoft.WindowsAzure.Commands.Storage.generated.format.ps1xml
  src/Storage/Commands.Storage/Model/ResourceModel/PSSeriviceProperties.cs
Labels: Waiting for On Demand

#6696 Fixed typo in Set-AzureRmVMOSDisk.md
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMOSDisk.md
Labels: needs-review

#6698 Updated Load Balancer PS Examples
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmLoadBalancerInboundNatPoolConfig.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmLoadBalancerInboundNatPoolConfig.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmLoadBalancerInboundNatPoolConfig.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmLoadBalancerInboundNatPoolConfig.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmLoadBalancerInboundNatPoolConfig.md
Labels: Waiting for CI

#6703 Update New-AzureRmADUser.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmADUser.md
Labels: Waiting for CI

#6699 Update new-azurermvm simple param set to enable auto configuration of Accelerated Network for qualifying vms
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVm.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithAccelNet.json
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.csproj
  src/ResourceManager/Compute/Commands.Compute/Common/Utils.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkInterfaceStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for CI

#6697 Update AzureRm.ApiManagement module to 4.0.3 nuget with bug fixes
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/ApiManagementClient.cs
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/Commands.ApiManagement.ServiceManagement.Netcore.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/Commands.ApiManagement.ServiceManagement.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/Commands/GetAzureApiManagementPolicy.cs
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/Models/ErrorBody.cs
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/packages.config
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/Commands.ApiManagement.Test.Netcore.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/Commands.ApiManagement.Test.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestApiManagementHostnamesCrud.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestBackupRestoreApiManagement.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestCrudApiManagement.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestCrudApiManagementWithAdditionalRegions.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestCrudApiManagementWithVirtualNetwork.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestSetApiManagementHostnames.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.Test.ScenarioTests.ApiManagementTests/TestUpdateApiManagementDeployment.json
  src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/packages.config
  src/ResourceManager/ApiManagement/Commands.ApiManagement/ChangeLog.md
  src/ResourceManager/ApiManagement/Commands.ApiManagement/Commands.ApiManagement.Netcore.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement/Commands.ApiManagement.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement/packages.config
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/Commands.ApiManagement.ServiceManagement.Test.Netcore.csproj
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/Commands.ApiManagement.ServiceManagement.Test.csproj
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/ScenarioTests/ApiManagementTests.ps1
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportSwaggerTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportWadlTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportWsdlTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiRevisionCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiVersionSetCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/AuthorizationServerCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/BackendCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/BackendServiceFabricCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/CertificateCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/GroupCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/IdentityProviderCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/OpenIdConnectProviderCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/OperationsCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/PolicyCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ProductCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/PropertiesCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/SubscriptionCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/TenantAccessConfigurationCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/TenantGitConfigurationCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/UserCrudTest.json
  src/ResourceManager/ApiManagement/Commands.SMAPI.Test/packages.config
Labels: Waiting for CI

#6702 Fix allow selecting storage from a different resource group
  src/ResourceManager/Sql/Commands.Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/UpdateAzureSqlDatabaseVulnerabilityAssessmentSettings.cs
  src/ResourceManager/Sql/Commands.Sql/VulnerabilityAssessment/Services/SqlVulnerabilityAssessmentAdapter.cs
Labels: needs-review

#6675 Add script to dynamically create mapping files used during build
  ModuleMappings.json
  TestMappings.json
  build.proj
  src/ResourceManager/DevTestLabs/Commands.DevTestLabs.Test/ScenarioTests/PolicyTests.cs
  src/ResourceManager/MachineLearning/Commands.MachineLearning.Test/Commands.MachineLearning.Test.csproj
  src/ResourceManager/MachineLearning/Commands.MachineLearning.Test/ScenarioTests/BaseTestController.cs
  src/ResourceManager/MachineLearning/Commands.MachineLearning.Test/ScenarioTests/CommitmentPlanTests.ps1
  src/ResourceManager/MachineLearning/Commands.MachineLearning.Test/ScenarioTests/WebServiceTests.cs
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/ScenarioTests/ManagementPartnerTests.cs
  src/ResourceManager/Maps/Maps.Test/Commands.Maps.Test.csproj
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Microsoft.Azure.Commands.Maps.Test.ScenarioTests.MapsAccountTests/TestGetAccountKeys.json
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Microsoft.Azure.Commands.Maps.Test.ScenarioTests.MapsAccountTests/TestGetAccounts.json
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Microsoft.Azure.Commands.Maps.Test.ScenarioTests.MapsAccountTests/TestNewAccount.json
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Microsoft.Azure.Commands.Maps.Test.ScenarioTests.MapsAccountTests/TestNewAccountKey.json
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Microsoft.Azure.Commands.Maps.Test.ScenarioTests.MapsAccountTests/TestPipingToGetKey.json
  src/ResourceManager/Maps/Maps.Test/SessionRecords/Microsoft.Azure.Commands.Maps.Test.ScenarioTests.MapsAccountTests/TestRemoveAccount.json
  src/ResourceManager/Maps/Maps.Test/TestController.cs
  src/ResourceManager/Maps/Maps.sln
  src/ResourceManager/Media/Commands.Media.Test/ScenarioTests/MediaTests.ps1
  src/ResourceManager/Media/Commands.Media.Test/ScenarioTests/TestController.cs
  src/ResourceManager/SignalR/Commands.SignalR.Test/Commands.SignalR.Test.csproj
  src/ServiceManagement/Compute/Commands.ServiceManagement.Test/UnitTests/Cmdlets/IaaS/Extensions/Diagnostics/DiagnosticsHelperTest.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks.Test/SetGeneratorTester.cs
  tools/CreateFilterMappings.ps1
Labels: needs-revision

#6717 Updated the DataPlane SDK version to 1.1.9
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.Netcore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/packages.config
Labels: Waiting for CI

#6700 Add document outlining expected patterns for standard cmdlets
  build.proj
  documentation/development-docs/azure-powershell-design-guidelines.md
  documentation/development-docs/patterns-for-standard-cmdlets.md
Labels: needs-review

#6728 Added Change for /Set-AzureRmVMBginfoExtension.md
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
Labels: Waiting for CI

#6718 [DO NOT MERGE] Test different dynamic mapping builds
  src/ResourceManager/RecoveryServices/RecoveryServices.Backup.sln
  src/ResourceManager/RecoveryServices/RecoveryServices.sln
Labels: Do Not Merge

#6726 [RecoveryServices] Merging NET Core modules
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/AzureRM.RecoveryServices.Backup.Netcore.psd1
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices/AzureRM.RecoveryServices.Netcore.psd1
Labels: Waiting for CI

#6731 Update help-generation.md
  documentation/development-docs/help-generation.md
Labels: needs-review

#6738 Remove incorrect statement from Tag cmdlet help
  src/ResourceManager/Tags/Commands.Tags/ChangeLog.md
  src/ResourceManager/Tags/Commands.Tags/help/Get-AzureRmTag.md
  src/ResourceManager/Tags/Commands.Tags/help/New-AzureRmTag.md
  src/ResourceManager/Tags/Commands.Tags/help/Remove-AzureRmTag.md
Labels: Waiting for CI, needs-review

#6758 Updating ADF .Net SDK nuget
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/packages.config
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Changelog.md
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Commands.DataFactoryV2.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/packages.config
Labels: Waiting for CI

#6760 Fix issue with Get-Location
  src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/Common.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateSecondaryDatabase.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestGetReplicationLink.json
Labels: Waiting for CI

#6768 Remove deprecated cmdlets from AzureRM.Resources.psd1
  src/ResourceManager/Resources/Commands.Resources/AzureRM.Resources.Netcore.psd1
Labels: Waiting for CI

#6771 Fix issue when providing both tag name and value for Get-AzureRmResource
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Resource/GetAzureResourceCmdlet.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestFindAResourceByTag.json
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
Labels: needs-review

#6733 Event Hub: some issues fix and piping for remove cmdlet
  src/ResourceManager/EventHub/Commands.EventHub/ChangeLog.md
  src/ResourceManager/EventHub/Commands.EventHub/Cmdlets/AzureEventHubsCmdletBase.cs
  src/ResourceManager/EventHub/Commands.EventHub/Cmdlets/ConsumerGroup/RemoveAzureEventHubConsumerGroups.cs
  src/ResourceManager/EventHub/Commands.EventHub/Cmdlets/EventHub/RemoveAzureEventHub.cs
  src/ResourceManager/EventHub/Commands.EventHub/Cmdlets/Namespace/RemoveAzureEventHubNamespace.cs
  src/ResourceManager/EventHub/Commands.EventHub/Models/PSConsumerGroupAttributes.cs
  src/ResourceManager/EventHub/Commands.EventHub/Models/PSEventHubsAttributes.cs
  src/ResourceManager/EventHub/Commands.EventHub/help/Remove-AzureRmEventHub.md
  src/ResourceManager/EventHub/Commands.EventHub/help/Remove-AzureRmEventHubConsumerGroup.md
  src/ResourceManager/EventHub/Commands.EventHub/help/Remove-AzureRmEventHubNamespace.md
  tools/StaticAnalysis/Exceptions/AzureRM.EventHub/BreakingChangeIssues.csv
Labels: needs-revision

#6777 Fix for issue #6770
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.NewVhdVMTests/TestWithValidVhdDiskFile.json
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
Labels: Waiting for CI, needs-review

#6732 Service Bus: some issues fix and piping for remove cmdlet
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/Commands.ServiceBus.Test.csproj
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusQueueTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusRuleTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusSubscriptionTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusTopicTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusDRConfigurationTests/ServiceBusDRConfigurationsCURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusDRConfigurationTests/ServiceBusDRConfigurationsCURDAlterName.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusMigrationConfigurationTests/ServiceBusMigrationConfigurationsCURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusPaginationTests/ServiceBusPaginationTests_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueueAuth_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueue_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusRuleTests/ServiceBusRule_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpaceAuth_CURD_Tests.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpace_CURD_Tests.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusSubscriptionTests/ServiceBusSubscription_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopicAuth_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopic_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus/ChangeLog.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/AzureServiceBusCmdletBase.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/DRConfig/GetAzureServiceBusGeoDRConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/DRConfig/NewAzureServiceBusGeoDRConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/DRConfig/RemoveAzureServiceBusGeoDRConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/DRConfig/SetAzureServiceBusGeoDRConfigurationBreakPair.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/DRConfig/SetAzureServiceBusGeoDRConfigurationFailOver.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/MigrationConfiguration/CompleteAzureServiceBusMigrationConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/MigrationConfiguration/GetAzureServiceBusMigrationConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/MigrationConfiguration/RemoveAzureServiceBusMigrationConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/MigrationConfiguration/StopAzureServiceBusMigrationConfiguration.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Namespace/NewAzureServiceBusNamespace.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Namespace/RemoveAzureServiceBusNamespace.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Queue/RemoveAzureServiceBusQueue.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Rule/RemoveAzureServiceBusRule.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Subscription/RemoveAzureServiceBusSubscription.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Topic/RemoveAzureServiceBusTopic.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Models/PSQueueAttributes.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Models/PSSubscriptionAttributes.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Utilities/ServiceBusClient.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Remove-AzureRmServiceBusNamespace.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Remove-AzureRmServiceBusQueue.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Remove-AzureRmServiceBusRule.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Remove-AzureRmServiceBusSubscription.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Remove-AzureRmServiceBusTopic.md
  tools/StaticAnalysis/Exceptions/AzureRM.ServiceBus/SignatureIssues.csv
Labels: needs-review

#6772 Update dependencies in .NET Core to match desktop
  src/ResourceManager/Common/Commands.Common.Strategies/Common.Strategies.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute/Extension/NetcoreExtension.cs
  src/ResourceManager/LogicApp/Commands.LogicApp/Commands.LogicApp.Netcore.csproj
Labels: needs-review

#6759 New-AzsOffer will allow creating offer only as Private, printing a wa…
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/New-AzsOffer.ps1
Labels: needs-review

#6687 Upgrade Nuget Dependency to 0.2 for SubscriptionsAdmin to support moveSubscriptions
  src/StackAdmin/Azs.Subscriptions.Admin/Help/Azs.Subscriptions.Admin.md
  src/StackAdmin/Azs.Subscriptions.Admin/Help/Move-AzsSubscription.md
  src/StackAdmin/Azs.Subscriptions.Admin/Help/Test-AzsMoveSubscription.md
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin.csproj
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Azs.Subscriptions.Admin.psd1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/FormatFiles/MoveSubscriptionsDefinition.ps1xml
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/SwaggerDefinitionCommands/New-MoveSubscriptionsDefinitionObject.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsOperation.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Move-AzsSubscription.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Test-AzsMoveSubscription.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/packages.config
  src/StackAdmin/Azs.Subscriptions.Admin/Subscriptions.json
  src/StackAdmin/Azs.Subscriptions.Admin/Tests/Azs.Subscriptions.Admin.Tests.csproj
  src/StackAdmin/Azs.Subscriptions.Admin/Tests/SessionRecords/SubscriptionsAdminClient/MoveSubscription.json
  src/StackAdmin/Azs.Subscriptions.Admin/Tests/src/Subscriptions.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/generate.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: needs-revision

#6773 Azure Search PS: throw inner exception and fix versioning
  src/ResourceManager/Search/Commands.Management.Search/AzureRM.Search.psd1
  src/ResourceManager/Search/Commands.Management.Search/ChangeLog.md
  src/ResourceManager/Search/Commands.Management.Search/Properties/AssemblyInfo.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/GetSearchServiceAdminKeyPairCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/GetSearchServiceCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/GetSearchServiceQueryKeyCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/NewSearchServiceAdminKeyCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/NewSearchServiceCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/NewSearchServiceQueryKeyCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/RemoveSearchServiceCommand.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/RemoveSearchServiceQueryKey.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/SearchServiceBaseCmdlet.cs
  src/ResourceManager/Search/Commands.Management.Search/SearchService/SetSearchServiceCommand.cs
  tools/CreateMappings_rules.json
Labels: Preview, Waiting for CI, needs-review

#6779 Fixing the description for param `Path`
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/help/Save-AzureRmVMImage.md
Labels: Waiting for CI

#6780 Fix debugging when DebugPreference is set from powershell command line
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs
Labels: needs-review

#6782 Removed -TemplateVersion from Example 1.
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmResourceGroupDeployment.md
Labels: Waiting for CI

#6796 Fixed typo for Set-CscAzureDataLakeStoreACL documentation
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/help/Set-AzureRmDataLakeStoreItemAcl.md
Labels: Waiting for CI

#6805 [Azure Stack] Fix to match documentation
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerDefinitionCommands/New-AzsScaleUnitNodeObject.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Add-AzsScaleUnitNode.ps1
Labels: needs-review

#6806 Test move subscriptios have incorrect parameter bindings.
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Test-AzsMoveSubscription.ps1
Labels: needs-review

#6781 updating versions in azureastack.psd1 file for the release 1.4.0
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: needs-review

#6813 [Storage] Remove the quota limitation in Set-AzureStorageShareQuota
  src/Storage/Commands.Storage/ChangeLog.md
  src/Storage/Commands.Storage/File/Cmdlet/SetAzureStorageShareQuota.cs
  src/Storage/Commands.Storage/help/Set-AzureStorageShareQuota.md
Labels: needs-revision

#6817 fix ManagementPartner tests
  TestMappings.json
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/Commands.Partner.Test.csproj
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/ScenarioTests/ManagementPartnerTests.ps1
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/SessionRecords/Microsoft.Azure.Commands.ManagementPartner.Test.ScenarioTests.ManagementPartnerTests/TestGetPartner.json
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/SessionRecords/Microsoft.Azure.Commands.ManagementPartner.Test.ScenarioTests.ManagementPartnerTests/TestGetPartnerNoParnterId.json
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/SessionRecords/Microsoft.Azure.Commands.ManagementPartner.Test.ScenarioTests.ManagementPartnerTests/TestNewParnter.json
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/SessionRecords/Microsoft.Azure.Commands.ManagementPartner.Test.ScenarioTests.ManagementPartnerTests/TestRemoveParnter.json
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/SessionRecords/Microsoft.Azure.Commands.ManagementPartner.Test.ScenarioTests.ManagementPartnerTests/TestUpdateParnter.json
  src/ResourceManager/ManagementPartner/Commands.Partner.Test/packages.config
Labels: Waiting for CI

#6502 Fix Issue #6398 with Clear-AzureRmContext cmdlet
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/AzureRmProfile.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/ContextModelExtensions.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/ProtectedProfileProvider.cs
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/ResourceManagerProfileProvider.cs
  src/ResourceManager/Profile/Commands.Profile.Test/ContextCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/Context/ClearAzureRmContext.cs
Labels: needs-review

#6820 Update authenticode signing to just sha-2 cert
  build.proj
Labels: Do Not Merge
