Repository Azure/azure-powershell, pull requests merged in 2018-11, with the labels that each got.

#7710 Fix issue where EndDate parameter was not being honored for AD cmdlets
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADAppCredentialCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADApplicationCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADServicePrincipalCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADSpCredentialCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/Properties/Resources.Designer.cs
  src/ResourceManager/Resources/Commands.Resources/Properties/Resources.resx
Labels: needs-revision

#7671 Adding tests for the Source Control cmdlets and enabling Update Management tests
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.Netcore.csproj
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.csproj
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/AutomationScenarioTestsBase.cs
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/HybridWorkerGroupTests.cs
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/HybridWorkerGroupTests.ps1
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/SourceControlTests.cs
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/SourceControlTests.ps1
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/UpdateManagementTests.cs
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/UpdateManagementTests.ps1
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.HybridWorkerGroupTests/E2EHybridWorkerGroup.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.SourceControlTests/CreateGitHubSourceControlAndSync.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.SourceControlTests/CreateVsoGitSourceControlAndSync.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.SourceControlTests/CreateVsoTfvcSourceControlAndSync.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateLinuxOneTimeSUCNonAzureOnly.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateLinuxOneTimeSUCWithAllOption.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateLinuxOneTimeSUCWithDefaults.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateLinuxWeeklySUC.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateWindowsMonthlySUC.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateWindowsOneTimeSUCWithAllOption.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateWindowsOneTimeSUCWithDefaults.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/DeleteSUC.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllMachineRuns.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllMachineRunsWithFilters.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllMachineRunsWithFiltersNoResults.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllRuns.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllRunsWithFilters.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllRunsWithFiltersNoResults.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllSUCs.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllSUCsForVM.json
  src/ResourceManager/Automation/Commands.Automation/Az.Automation.psd1
  src/ResourceManager/Automation/Commands.Automation/Cmdlet/UpdateManagement/RemoveAzureAutomationSoftwareUpdateConfiguration.cs
  src/ResourceManager/Automation/Commands.Automation/Common/AutomationPSClientDSC.cs
  src/ResourceManager/Automation/Commands.Automation/Model/JobStreamRecord.cs
  src/ResourceManager/Automation/Commands.Automation/Model/UpdateManagement/SoftwareUpdateRun.cs
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.cs
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Commands.Resources.Rest.Netcore.csproj
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
  tools/AliasMapping.json
  tools/Common.Netcore.Dependencies.Test.targets
  tools/CredScanSuppressions.json
Labels: needs-review

#7582 Powershell Module For IoT Central Application CRUD Management
  Azure.PowerShell.Netcore.sln
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/Commands.IotCentral.Test.Netcore.csproj
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/Commands.IotCentral.Test.csproj
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/ScenarioTests/Common.ps1
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/ScenarioTests/IotCentralController.cs
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/ScenarioTests/IotCentralTests.cs
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/ScenarioTests/IotCentralTests.ps1
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/packages.config
  src/ResourceManager/IotCentral/Commands.IotCentral/Az.IotCentral.psd1
  src/ResourceManager/IotCentral/Commands.IotCentral/AzureRM.IotCentral.psd1
  src/ResourceManager/IotCentral/Commands.IotCentral/ChangeLog.md
  src/ResourceManager/IotCentral/Commands.IotCentral/Commands.IotCentral.Netcore.csproj
  src/ResourceManager/IotCentral/Commands.IotCentral/Commands.IotCentral.csproj
  src/ResourceManager/IotCentral/Commands.IotCentral/Common/FullParameterSetCmdlet.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Common/IotCentralBaseCmdlet.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Common/IotCentralUtils.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/IotCentral/GetAzureRmIotCentralApp.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/IotCentral/NewAzureRmIotCentralApp.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/IotCentral/RemoveAzureRmIotCentralApp.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/IotCentral/SetAzureRmIotCentralApp.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/MSSharedLibKey.snk
  src/ResourceManager/IotCentral/Commands.IotCentral/Models/PSIotCentralApp.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Models/PSIotCentralAppSku.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Models/PSIotCentralAppSkuInfo.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Properties/AssemblyInfo.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Properties/Resources.Designer.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Properties/Resources.resx
  src/ResourceManager/IotCentral/Commands.IotCentral/StartupScripts/sample.ps1
  src/ResourceManager/IotCentral/Commands.IotCentral/help/AzureRM.IotCentral.md
  src/ResourceManager/IotCentral/Commands.IotCentral/help/Get-AzureRmIotCentralApp.md
  src/ResourceManager/IotCentral/Commands.IotCentral/help/New-AzureRmIotCentralApp.md
  src/ResourceManager/IotCentral/Commands.IotCentral/help/Remove-AzureRmIotCentralApp.md
  src/ResourceManager/IotCentral/Commands.IotCentral/help/Set-AzureRmIotCentralApp.md
  src/ResourceManager/IotCentral/Commands.IotCentral/packages.config
  src/ResourceManager/IotCentral/IotCentral.sln
  src/ResourceManager/IotCentral/NuGet.Config
  src/ResourceManager/IotCentral/documentation/current-breaking-changes.md
  src/ResourceManager/IotCentral/documentation/upcoming-breaking-changes.md
  tools/PS-VSPrompt.lnk
Labels: Waiting for CI :shipit:

#7696 Fix for 7693: Get-ResourceName is not the name of a cmdlet
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/ChangeLog.md
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Add-AzsScaleUnitNode.ps1
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestAddScaleUnitNode.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/src/ScaleUnitNode.tests.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: Azure Stack, needs-review

#7697 add more check on destination id, address and port for connectivity c…
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectivityCheck.json
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/NetworkWatcher/TestAzureNetworkWatcherConnectivityCommand.cs
  src/ResourceManager/Network/Commands.Network/Properties/Resources.Designer.cs
  src/ResourceManager/Network/Commands.Network/Properties/Resources.resx
Labels: needs-review

#7721 Remove file system characters that are now supported by Azure Files Service from the blacklist
  src/ResourceManager/StorageSync/Commands.StorageSync/ChangeLog.md
  src/ResourceManager/StorageSync/Commands.StorageSync/Config.json
Labels: needs-review

#7715 Fixed issue where using Update-AzureRmSqlDatabaseVulnerabilityAssessmentSettings with storage account name parameter set
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/VulnerabilityAssessmentTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/VulnerabilityAssessmentTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentBaselineTest.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentScanConvertTest.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentScanRecordGetListTest.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentSettingsTest.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentWithAtpOffTest.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentWithSettingsNotDefinedTest.json
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.Netcore.csproj
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/UpdateAzureSqlDatabaseVulnerabilityAssessmentSettings.cs
  src/ResourceManager/Sql/Commands.Sql/VulnerabilityAssessment/Services/SqlVulnerabilityAssessmentAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/VulnerabilityAssessment/Services/VulnerabilityAssessmentEndpointsCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/packages.config
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
  tools/CredScanSuppressions.json
Labels: needs-revision

#7747 Update Add-AzureRmServiceEndpointPolicyDefinition.md
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmServiceEndpointPolicyDefinition.md
Labels: Waiting for CI :shipit:

#7728 update the examples description
  src/ResourceManager/MarketplaceOrdering/Commands.MarketplaceOrdering/ChangeLog.md
  src/ResourceManager/MarketplaceOrdering/Commands.MarketplaceOrdering/Common/Constants.cs
  src/ResourceManager/MarketplaceOrdering/Commands.MarketplaceOrdering/help/Set-AzureRmMarketplaceTerms.md
Labels: Waiting for CI :shipit:

#7757 Fix online help for New-AzureRmEventHubNamespace
  src/ResourceManager/EventHub/Commands.EventHub/help/New-AzureRmEventHubNamespace.md
Labels: needs-review

#7711 Updating the warning message to match that of portal UI
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Azs.Update.Admin.psd1
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Install-AzsUpdate.ps1
Labels: Azure Stack, needs-review

#7634 Version Sql for preview release
  src/ResourceManager/Sql/Commands.Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/AssemblyInfo.cs
Labels: needs-review

#7725 Release first version of Az.FrontDoor
  Azure.PowerShell.Netcore.sln
  src/ResourceManager/FrontDoor/Commands.FrontDoor/Az.FrontDoor.psd1
Labels: needs-review

#7669 Add Automation account cmdlet tests
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.csproj
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/AccountTests.cs
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/AccountTests.ps1
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/AutomationScenarioTestsBase.cs
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Microsoft.Azure.Commands.Automation.Test.AccountTests/TestAutomationAcctTags.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Microsoft.Azure.Commands.Automation.Test.AccountTests/TestGetAutomationAccts.json
Labels: needs-revision

#7735 Added Nullcheck in getting JobStreamRecord values and added Runbook, Job, JobOutput tests
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.Netcore.csproj
  src/ResourceManager/Automation/Commands.Automation.Test/Commands.Automation.Test.csproj
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/Resources/RB-GraphTutorial.graphrunbook
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/Resources/RB-PowerShellScriptTutorial.ps1
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/RunbookJobTests.cs
  src/ResourceManager/Automation/Commands.Automation.Test/ScenarioTests/RunbookJobTests.ps1
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.RunbookJobTests/TestCreateRunbookGraph.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.RunbookJobTests/TestImportAndDeleteRunbookGraphical.json
  src/ResourceManager/Automation/Commands.Automation.Test/SessionRecords/Commands.Automation.Test.RunbookJobTests/TestImportRunbookPowerShell.json
  src/ResourceManager/Automation/Commands.Automation/Model/JobStreamRecord.cs
Labels: needs-revision

#7772 fixed example on New-AzureRmRecoveryServicesAsrProtectableItem.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.SiteRecovery/ChangeLog.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.SiteRecovery/help/New-AzureRmRecoveryServicesAsrProtectableItem.md
Labels: needs-review

#7737 Update dev guide with ResourceNameCompleter
  documentation/development-docs/azure-powershell-design-guidelines.md
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: needs-review

#7784 Update naming structure for Context Autosave environment variable
  src/ResourceManager/Profile/Commands.Profile/Common/AzureRmProfileConstants.cs
Labels: needs-review

#7741 Create Az projects for Security and StorageSync
  Azure.PowerShell.Netcore.sln
  src/Azure.PowerShell.Netcore.Test.sln
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
  src/ResourceManager/Security/Commands.Security.Test/Commands.Security.Test.Netcore.csproj
  src/ResourceManager/Security/Commands.Security.Test/Commands.Security.Test.csproj
  src/ResourceManager/Security/Commands.Security.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/Security/Commands.Security/Az.Security.psd1
  src/ResourceManager/Security/Commands.Security/Cmdlets/Alerts/GetAlerts.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/Alerts/SetAlerts.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/AutoProvisioningSettings/GetAutoProvisioningSettings.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/AutoProvisioningSettings/SetAutoProvisioningSettings.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/Compliances/GetCompliances.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/DiscoveredSecuritySolutions/GetDiscoveredSecuritySolutions.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/ExternalSecuritySolutions/GetExternalSecuritySolutions.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/JitNetworkAccessPolicies/GetJitNetworkAccessPolicies.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/JitNetworkAccessPolicies/RemoveJitNetworkAccessPolicies.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/JitNetworkAccessPolicies/SetJitNetworkAccessPolicies.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/JitNetworkAccessPolicies/StartJitNetworkAccessPolicies.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/Locations/GetLocations.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/Pricings/GetPricings.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/Pricings/SetPricings.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/SecurityContacts/GetSecurityContacts.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/SecurityContacts/RemoveSecurityContacts.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/SecurityContacts/SetSecurityContacts.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/Tasks/GetTasks.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/WorkspaceSettings/GetWorkspaceSettings.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/WorkspaceSettings/RemoveWorkspaceSettings.cs
  src/ResourceManager/Security/Commands.Security/Cmdlets/WorkspaceSettings/SetWorkspaceSettings.cs
  src/ResourceManager/Security/Commands.Security/Commands.Security.Netcore.csproj
  src/ResourceManager/Security/Commands.Security/Commands.Security.csproj
  src/ResourceManager/StorageSync/Commands.StorageSync.Test/Commands.StorageSync.Test.Netcore.csproj
  src/ResourceManager/StorageSync/Commands.StorageSync.Test/ScenarioTests/Common.ps1
  src/ResourceManager/StorageSync/Commands.StorageSync.Test/TestController.cs
  src/ResourceManager/StorageSync/Commands.StorageSync.Test/UnitTests/AfsPathTests.cs
  src/ResourceManager/StorageSync/Commands.StorageSync.Test/UnitTests/MaximumTreeDepthValidationTest.cs
  src/ResourceManager/StorageSync/Commands.StorageSync/Az.StorageSync.psd1
  src/ResourceManager/StorageSync/Commands.StorageSync/Commands.StorageSync.Netcore.csproj
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
Labels: Do Not Merge :no_entry_sign:

#7770 [Compute] Fix identity issue for system assigned identity.
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetIdentity.json
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Common/ComputeAutoMapperProfile.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Models/ComputeAutoMapperProfile.cs
Labels: needs-review

#7801 [RecoveryServices.Backup] Fixed modify policy for protected file share
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ChangeLog.md
Labels: needs-review

#7786 Option to override NRP test location through environment variable
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Common.ps1
Labels: needs-review

#7773 Improve test (cover *Base); Drop unreachable code
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDSubItems2.json
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RedirectConfiguration/AzureApplicationGatewayRedirectConfigurationBase.cs
Labels: needs-review

#7788 [RecoveryServices.Backup] Converting policy timezone to upper case
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ChangeLog.md
Labels: Waiting for CI :shipit:

#7783 Add automatic secret generation to New-AzureRmSPCredential
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADServicePrincipalCommand.cs
  src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/NewAzureADSpCredentialCommand.cs
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.csproj
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/PSADCredentialWrapper.cs
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/PSADServicePrincipalWrapper.cs
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmADServicePrincipal.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmADSpCredential.md
Labels: Waiting for CI :shipit:

#7755 Add table format to Profile
  src/ResourceManager/Profile/Commands.Profile/Az.Profile.psd1
  src/ResourceManager/Profile/Commands.Profile/AzureRM.Profile.psd1
  src/ResourceManager/Profile/Commands.Profile/Commands.Profile.Netcore.csproj
  src/ResourceManager/Profile/Commands.Profile/Commands.Profile.csproj
  src/ResourceManager/Profile/Commands.Profile/Microsoft.Azure.Commands.Profile.format.ps1xml
  src/ResourceManager/Profile/Commands.Profile/Microsoft.Azure.Commands.Profile.generated.format.ps1xml
  src/ResourceManager/Profile/Commands.Profile/help/Add-AzureRmEnvironment.md
  src/ResourceManager/Profile/Commands.Profile/help/Connect-AzureRmAccount.md
  src/ResourceManager/Profile/Commands.Profile/help/Get-AzureRmContext.md
  src/ResourceManager/Profile/Commands.Profile/help/Get-AzureRmEnvironment.md
  src/ResourceManager/Profile/Commands.Profile/help/Get-AzureRmSubscription.md
  src/ResourceManager/Profile/Commands.Profile/help/Get-AzureRmTenant.md
  src/ResourceManager/Profile/Commands.Profile/help/Import-AzureRmContext.md
  src/ResourceManager/Profile/Commands.Profile/help/Remove-AzureRmEnvironment.md
  src/ResourceManager/Profile/Commands.Profile/help/Select-AzureRmContext.md
  src/ResourceManager/Profile/Commands.Profile/help/Set-AzureRmContext.md
  src/ResourceManager/Profile/Commands.Profile/help/Set-AzureRmEnvironment.md
Labels: Sprint Candidate, needs-review

#7794 Fix memory issues with network maps
  src/ResourceManager/Aks/Commands.Aks/ChangeLog.md
  src/ResourceManager/Aks/Commands.Aks/Commands.Aks.csproj
  src/ResourceManager/Aks/Commands.Aks/packages.config
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/Commands.ApiManagement.ServiceManagement.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/packages.config
  src/ResourceManager/ApiManagement/Commands.ApiManagement/ChangeLog.md
  src/ResourceManager/ApiManagement/Commands.ApiManagement/Commands.ApiManagement.csproj
  src/ResourceManager/ApiManagement/Commands.ApiManagement/packages.config
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.csproj
  src/ResourceManager/Compute/Commands.Compute/packages.config
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/ChangeLog.md
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/Commands.ContainerInstance.csproj
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/packages.config
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/packages.config
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.SiteRecovery/ChangeLog.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.SiteRecovery/Commands.RecoveryServices.SiteRecovery.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.SiteRecovery/packages.config
Labels: Sprint Candidate

#7727 Implement certificate-based SP authentication in Az
  src/ResourceManager/Profile/Commands.Profile/Account/ConnectAzureRmAccount.cs
  src/ResourceManager/Profile/Commands.Profile/help/Connect-AzureRmAccount.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#7819 Option to override NRP test location through environment variable
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/Common.ps1
Labels: needs-review

#7826 Fix for #7678, #7703: preserve case in Tag keys
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Json/CamelCasePropertyNamesWithOverridesContractResolver.cs
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
Labels: Sprint Candidate, needs-review

#7806 [Compute] Add warning message for upcoming property changes.
  src/ResourceManager/Compute/Commands.Compute/Extension/Diagnostics/AddAzureRmVmssDiagnosticsExtension.cs
  src/ResourceManager/Compute/Commands.Compute/Extension/Diagnostics/RemoveAzureRmVmssDiagnosticsExtension.cs
  src/ResourceManager/Compute/Commands.Compute/Extension/VmssDiskEncryption/DisableAzureVmssDiskEncryption.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/Config/NewAzureRmSnapshotUpdateConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/Config/SetAzureRmSnapshotUpdateDiskEncryptionKeyCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/Config/SetAzureRmSnapshotUpdateKeyEncryptionKeyCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssAdditionalUnattendContentCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssDataDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssExtensionCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssNetworkInterfaceConfigurationCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssSecretCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssSshPublicKeyCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssWinRMListenerCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/RemoveAzureRmVmssDataDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/RemoveAzureRmVmssExtensionCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/RemoveAzureRmVmssNetworkInterfaceConfigurationCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssBootDiagnosticCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssOsProfileCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssRollingUpgradePolicyCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Manual/AddAzureRmVmssVMDataDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/Manual/RemoveAzureRmVmssVMDataDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/AddAzureVMAdditionalUnattendContentCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/AddAzureVMNetworkInterfaceCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/AddAzureVMSecretCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/AddAzureVMSshPublicKeyCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/RemoveAzureVMDataDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/RemoveAzureVMNetworkInterfaceCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/RemoveAzureVMSecretCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMBootDiagnosticsCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMDataDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMOSDiskCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMOperatingSystemCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMPlan.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMSourceImage.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/GetAzureVMBootDiagnosticsDataCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
Labels: Sprint Candidate, needs-revision

#7829 Add an example for New-AzureRmPolicyDefinition that uses -Metadata
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyDefinition.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#7830 Deprecating parameters renamed or removed in sf sdk 1.1.0 for next sdk upgrade change
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/AddAzureRmServiceFabricClientCertificate.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/AddAzureRmServiceFabricClusterCertificate.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/AddAzureRmServiceFabricNode.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/AddAzureRmServiceFabricNodeType.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/GetAzureRmServiceFabricClusterResouce.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/RemoveAzureRmServiceFabricClientCertificate.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/RemoveAzureRmServiceFabricClusterCertificate.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/RemoveAzureRmServiceFabricNode.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/RemoveAzureRmServiceFabricNodeType.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/RemoveAzureRmServiceFabricSetting.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/SetAzureRmServiceFabricSetting.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/SetAzureRmServiceFabricUpgradeType.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/UpdateAzureRmServiceFabricDurability.cs
  src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/UpdateAzureRmServiceFabricReliability.cs
Labels: Sprint Candidate, Waiting for CI :shipit:, needs-review

#7828 Update Microsoft.Authorization/policyAssignments MSI help
  src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PolicyHelpStrings.cs
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/help/New-AzureRmPolicyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/help/Set-AzureRmPolicyAssignment.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#7834 [Stroage] breaking change notice
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageUsage.cs
  src/Storage/Commands.Storage/Common/Cmdlet/NewAzureStorageContext.cs
Labels: needs-review

#7821 [Storage] Support hdfs in PSH official build
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSStorageAccount.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/NewAzureStorageAccount.cs
  src/ResourceManager/Storage/Commands.Management.Storage/help/New-AzureRmStorageAccount.md
Labels: Waiting for CI :shipit:

#7820 Removed storage depedency when inferring storageBlobContainerName
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/VulnerabilityAssessment/Services/BaseSqlVulnerabilityAssessmentAdapter.cs
Labels: Waiting for CI :shipit:

#7810 [Storage] Update Get Last Sync Time call since rest change
  src/ResourceManager/Compute/Commands.Compute.Test/Common/ComputeTestController.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/ComputeTestCommon.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.cs
  src/ResourceManager/Storage/Commands.Management.Storage.Test/ScenarioTests/StorageAccountTests.ps1
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestFailoverAzureStorageAccount.json
  src/ResourceManager/Storage/Commands.Management.Storage.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccountGeoReplicationStats.json
  src/ResourceManager/Storage/Commands.Management.Storage/Az.Storage.psd1
  src/ResourceManager/Storage/Commands.Management.Storage/AzureRM.Storage.psd1
  src/ResourceManager/Storage/Commands.Management.Storage/ChangeLog.md
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSGeoReplicationStats.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Models/PSStorageAccount.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageAccount.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/GetAzureStorageAccountLastSyncTime.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/InvokeAzureStorageAccountFailover.cs
  src/ResourceManager/Storage/Commands.Management.Storage/StorageAccount/StorageAccountBaseCmdlet.cs
  src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageAccount.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageAccountLastSyncTime.md
  src/ResourceManager/Storage/Commands.Management.Storage/help/Invoke-AzureRmStorageAccountFailover.md
  tools/LocalFeed/Microsoft.Azure.Management.Storage.9.1.0-preview.nupkg
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Storage/SignatureIssues.csv
Labels: Preview, needs-review

#7754 Add support for ultrassd and SIG to simple param sets for New-AzVm(ss) cmdlets
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVm.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmFromSIGImage.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleNewVmWithUltraSSD.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmss.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssFromSIGImage.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssWithUltraSSD.json
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ImageEx.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVM.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmss.md
Labels: needs-review

#7870 Update Set-AzureRmSqlDatabase.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabase.md
Labels: needs-review

#7871 Update Enable-AzureRmActivityLogAlert.md
  src/ResourceManager/Insights/Commands.Insights/help/Enable-AzureRmActivityLogAlert.md
Labels: Waiting for CI :shipit:, needs-review

#7779 Added Tabular Format to output and sudomain checking
  src/ResourceManager/IotCentral/Commands.IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/ResourceManager/IotCentral/Commands.IotCentral/AzureRM.IotCentral.psd1
  src/ResourceManager/IotCentral/Commands.IotCentral/ChangeLog.md
  src/ResourceManager/IotCentral/Commands.IotCentral/Commands.IotCentral.csproj
  src/ResourceManager/IotCentral/Commands.IotCentral/Common/IotCentralBaseCmdlet.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Common/IotCentralUtils.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/IotCentral/NewAzureRmIotCentralApp.cs
  src/ResourceManager/IotCentral/Commands.IotCentral/Microsoft.Azure.Commands.IotCentral.generated.format.ps1xml
  src/ResourceManager/IotCentral/Commands.IotCentral/Models/PSIotCentralApp.cs
Labels: Waiting for CI :shipit:

#7811 Improved PublicIpPrefix tests, fixed cmdlets
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/PublicIpPrefixTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpPrefixTests/TestPublicIpPrefixCRUD.json
  src/ResourceManager/Network/Commands.Network/PublicIpPrefix/GetAzurePublicIpPrefixCommand.cs
  src/ResourceManager/Network/Commands.Network/PublicIpPrefix/SetAzurePublicIpPrefixCommand.cs
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmPublicIpPrefix.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmPublicIpPrefix.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmPublicIpPrefix.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmPublicIpPrefix.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Network/BreakingChangeIssues.csv
Labels: needs-revision

#7882 Modify documentation in help files.
  src/ResourceManager/Sql/Commands.Sql/Auditing/AuditingHelpMessages.cs
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabaseAuditing.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlServerAuditing.md
Labels: needs-revision

#7884 Updated ServiceEndpoints tests
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetServiceEndpointPolicies.json
  src/ResourceManager/Network/Commands.Network/ServiceEndpointPolicy/ServiceEndpointPolicyDefinition/GetAzureServiceEndpointPolicyDefinitionCommand.cs
  src/ResourceManager/Network/Commands.Network/ServiceEndpointPolicy/ServiceEndpointPolicyDefinition/SetAzureServiceEndpointPolicyDefinitionCommand.cs
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmServiceEndpointPolicyDefinition.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmServiceEndpointPolicy.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmServiceEndpointPolicyDefinition.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmServiceEndpointPolicy.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmServiceEndpointPolicyDefinition.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmServiceEndpointPolicy.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmServiceEndpointPolicyDefinition.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmServiceEndpointPolicy.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmServiceEndpointPolicyDefinition.md
Labels: Waiting for CI :shipit:

#7888 [RecoveryServices.Backup] Added client side validations for AFS restore
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Models/Properties/Resources.resx
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup/ChangeLog.md
Labels: needs-review

#7893 Update New-AzureRmLoadBalancerOutboundRuleConfig.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmLoadBalancerOutboundRuleConfig.md
Labels: Waiting for CI :shipit:

#7891 Update New-AzureRmOperationalInsightsWorkspace.md
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/help/New-AzureRmOperationalInsightsWorkspace.md
Labels: Waiting for CI :shipit:

#7889 Deprecating Set-AzureRmRecoveryServicesVaultContext cmdlet
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices/ChangeLog.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices/Vault/SetAzureRmRecoveryServicesVaultContext.cs
Labels: needs-review

#7879 [Storage] Support Static Web blob service configuration
  src/Storage/Commands.Storage/Azure.Storage.psd1
  src/Storage/Commands.Storage/ChangeLog.md
  src/Storage/Commands.Storage/Common/Cmdlet/DisableAzureStorageStaticWebsite.cs
  src/Storage/Commands.Storage/Common/Cmdlet/EnableAzureStorageStaticWebsite.cs
Labels: needs-revision

#7877 Add a test script which is to calculate storage container billable size.
  src/Storage/Commands.Storage.Test/Commands.Storage.Test.csproj
  src/Storage/Commands.Storage.Test/Scripts/GetBillableSize.ps1
Labels: needs-revision

#7878 [Storage] Fix Start-AzureStorageFileCopy can't resue source context in destination when not input -DestContext
  src/Storage/Commands.Storage/ChangeLog.md
  src/Storage/Commands.Storage/File/Cmdlet/StartAzureStorageFileCopy.cs
Labels: Waiting for CI :shipit:

#7906 Fixing Bug 3231969: Minor typo in Invoke-AzureRmStorageSyncCompatibilityCheck status
  src/ResourceManager/StorageSync/Commands.StorageSync/ChangeLog.md
  src/ResourceManager/StorageSync/Commands.StorageSync/ProgressReporter.cs
Labels: Waiting for CI :shipit:, needs-review

#7742 Feature/repairswagger: Adding powershell cmdlet for repair alert
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin.csproj
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/Azs.Infrastructureinsights.Admin.psd1
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/ChangeLog.md
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Repair-AzsAlert.ps1
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/packages.config
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Tests/Azs.InfrastructureInsights.Admin.Tests.csproj
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Tests/Properties/AssemblyInfo.cs
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Tests/SessionRecords/InfrastructureInsightsAdminClient/TestRepairAlert.json
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Tests/packages.config
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Tests/src/Alert.Tests.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: Azure Stack, needs-review

#7911 [Azure Stack] Re-Generate Module Help
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Help/Azs.InfrastructureInsights.Admin.md
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Help/Repair-AzsAlert.md
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/Azs.Infrastructureinsights.Admin.psd1
Labels: Azure Stack, needs-review

#7922 Update example in New-AzureRmTag.md
  src/ResourceManager/Tags/Commands.Tags/help/New-AzureRmTag.md
Labels: Waiting for CI :shipit:

#7919 Update Microsoft.DataTransfer.Gateway.Encryption to 3.11.6898.1 to consume nuget.org
  src/ResourceManager/DataFactories/Commands.DataFactories.Test/Commands.DataFactories.Test.Netcore.csproj
  src/ResourceManager/DataFactories/Commands.DataFactories/ChangeLog.md
  src/ResourceManager/DataFactories/Commands.DataFactories/Commands.DataFactories.Netcore.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.Netcore.csproj
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Changelog.md
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Commands.DataFactoryV2.Netcore.csproj
  tools/LocalFeed/Microsoft.DataTransfer.Gateway.Encryption.3.11.6886.9.nupkg
Labels: Waiting for CI :shipit:

#7916 Fix the trailing slash of the domain of adls account
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/AdlsClientFactory.cs
Labels: needs-review

#7874 Supports Create, update, modify, delete of RewriteRuleSet
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDRewriteRuleSet.json
  src/ResourceManager/Network/Commands.Network.Test/packages.config
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/ApplicationGatewayChildResourceHelper.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/NewAzureApplicationGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/PathRule/AzureApplicationGatewayPathRuleConfigBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RequestRoutingRule/AzureApplicationGatewayRequestRoutingRuleBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRule/AzureApplicationGatewayRewriteRuleBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRule/NewAzureApplicationGatewayRewriteRuleCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleActionSet/AzureApplicationGatewayRewriteRuleActionSetBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleActionSet/NewAzureApplicationGatewayRewriteRuleActionSetCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleHeaderConfiguration/AzureApplicationGatewayRewriteRuleHeaderConfigurationBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleHeaderConfiguration/NewAzureApplicationGatewayRewriteRuleHeaderConfigurationCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleSet/AddAzureApplicationGatewayRewriteRuleSetCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleSet/AzureApplicationGatewayRewriteRuleSetBase.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleSet/GetAzureApplicationGatewayRewriteRuleSetCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleSet/NewAzureApplicationGatewayRewriteRuleSetCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleSet/RemoveAzureApplicationGatewayRewriteRuleSetCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/RewriteRuleSet/SetAzureApplicationGatewayRewriteRuleSetCommand.cs
  src/ResourceManager/Network/Commands.Network/ApplicationGateway/UrlPathMap/AzureApplicationGatewayUrlPathMapConfigBase.cs
  src/ResourceManager/Network/Commands.Network/Az.Network.psd1
  src/ResourceManager/Network/Commands.Network/AzureRM.Network.psd1
  src/ResourceManager/Network/Commands.Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Commands.Network.Netcore.csproj
  src/ResourceManager/Network/Commands.Network/Commands.Network.csproj
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGateway.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayHeaderConfiguration.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayPathRule.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayRequestRoutingRule.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayRewriteRule.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayRewriteRuleActionSet.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayRewriteRuleSet.cs
  src/ResourceManager/Network/Commands.Network/Models/PSApplicationGatewayUrlPathMap.cs
  src/ResourceManager/Network/Commands.Network/Properties/Resources.Designer.cs
  src/ResourceManager/Network/Commands.Network/Properties/Resources.resx
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayRequestRoutingRule.md
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayRewriteRuleSet.md
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmApplicationGatewayUrlPathMapConfig.md
  src/ResourceManager/Network/Commands.Network/help/AzureRM.Network.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzureRmApplicationGatewayRewriteRuleSet.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGateway.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayPathRuleConfig.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayRequestRoutingRule.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayRewriteRule.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayRewriteRuleActionSet.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayRewriteRuleHeaderConfiguration.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayRewriteRuleSet.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationGatewayUrlPathMapConfig.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzureRmApplicationGatewayRewriteRuleSet.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayRequestRoutingRule.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayRewriteRuleSet.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmApplicationGatewayUrlPathMapConfig.md
  src/ResourceManager/Network/Commands.Network/packages.config
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Network/SignatureIssues.csv
Labels: Cmdlet Review Complete, needs-review

#7932 Add back skipped Cortex tests
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.csproj
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/CortexTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/CortexTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexCRUD.json
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexDownloadConfig.json
  src/ResourceManager/Network/Commands.Network/Cortex/VirtualHub/VirtualHubBaseCmdlet.cs
Labels: needs-review

#7938 1387770: Fixed 3 broken links to PowerShell cmdlets related to Azure Resource Manager FrontDoor.
  src/ResourceManager/FrontDoor/Commands.FrontDoor/ChangeLog.md
  src/ResourceManager/FrontDoor/Commands.FrontDoor/help/New-AzureRmFrontDoor.md
  src/ResourceManager/FrontDoor/Commands.FrontDoor/help/New-AzureRmFrontDoorManagedRuleObject.md
  src/ResourceManager/FrontDoor/Commands.FrontDoor/help/Set-AzureRmFrontDoor.md
Labels: needs-review

#7869 Add Get-AzureRMDenyAssignment cmdlet
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.Netcore.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/Commands.Resources.Test.csproj
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/DenyAssignmentTests.cs
  src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/DenyAssignmentTests.ps1
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDa.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByEveryoneObjectId.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaById.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByIdAndSpecifiedScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByNameAndSpecifiedScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByObjectId.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByObjectIdAndGroupExpansion.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByObjectIdAndRGName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByObjectIdAndRGNameResourceNameResourceType.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByObjectIdAndScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByRG.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByRGNameResourceNameResourceType.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByServicePrincipalName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByServicePrincipalNameAndRGName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByServicePrincipalNameAndRGNameResourceNameResourceType.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaByServicePrincipalNameAndScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaBySignInName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaBySignInNameAndGroupExpansion.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaBySignInNameAndRGName.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaBySignInNameAndRGNameResourceNameResourceType.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaBySignInNameAndScope.json
  src/ResourceManager/Resources/Commands.Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DenyAssignmentTests/GetDaForEveryoneHasExpectedNameAndType.json
  src/ResourceManager/Resources/Commands.Resources.Test/packages.config
  src/ResourceManager/Resources/Commands.Resources/Az.Resources.psd1
  src/ResourceManager/Resources/Commands.Resources/AzureRM.Resources.psd1
  src/ResourceManager/Resources/Commands.Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.Netcore.csproj
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.csproj
  src/ResourceManager/Resources/Commands.Resources/DenyAssignments/GetAzureDenyAssignmentCommand.cs
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClient.cs
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClientExtensions.cs
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/FilterDenyAssignmentsOptions.cs
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/PSDenyAssignment.cs
  src/ResourceManager/Resources/Commands.Resources/Models.Authorization/PSPrincipal.cs
  src/ResourceManager/Resources/Commands.Resources/help/AzureRM.Resources.md
  src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmDenyAssignment.md
  src/ResourceManager/Resources/Commands.Resources/packages.config
  src/TestPrerequisites/Common.Test.Prerequisites/Common.TestPrerequisites.csproj
  tools/StaticAnalysis/Exceptions/Az.Resources/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/AzureRM.Resources/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#7953 [AzureStack] Fix bug for fabric admin cmdlet
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsDrive.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsStorageSubSystem.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsVolume.ps1
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetDriveByResourceId.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetStorageSubSystemByResourceId.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetVolumeByResourceId.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/src/Drive.tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/Tests/src/StorageSubSystem.tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/Tests/src/Volume.tests.ps1
Labels: Azure Stack, needs-review

#7862 Update az.storage version for preview failover support
  src/ResourceManager/Profile/Commands.Profile/Az.Profile.psd1
  src/ResourceManager/Storage/Commands.Management.Storage/Az.Storage.psd1
  tools/Az/Az.psd1
Labels: needs-revision

#7952 [AzureStack] Add help files for new fabric admin cmdlet
  src/StackAdmin/Azs.Fabric.Admin/Help/Azs.Fabric.Admin.md
  src/StackAdmin/Azs.Fabric.Admin/Help/Get-AzsDrive.md
  src/StackAdmin/Azs.Fabric.Admin/Help/Get-AzsStorageSubSystem.md
  src/StackAdmin/Azs.Fabric.Admin/Help/Get-AzsVolume.md
Labels: Waiting for CI :shipit:

#7967 Fix links in documentation
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  build.proj
  documentation/Debugging-StaticAnalysis-Errors.md
  documentation/azure-powershell-modules.md
  documentation/breaking-changes/breaking-changes-tool-help.md
  documentation/development-docs/azure-powershell-design-guidelines.md
  documentation/development-docs/azure-powershell-developer-guide.md
  documentation/development-docs/generate-format.ps1xml-file.md
  documentation/development-docs/help-generation.md
  documentation/development-docs/patterns-for-standard-cmdlets.md
  documentation/development-docs/piping-in-powershell.md
  documentation/development-docs/vm-for-partners.md
  documentation/testing-docs/using-azure-test-framework.md
  documentation/troubleshoot-ci.md
  documentation/troubleshoot-module-load.md
Labels: needs-review
