Repository Azure/azure-powershell, pull requests merged in 2018-03, with the labels that each got.

#5599 Load Newtonsoft.Json 10.0.3 side-by-side with 6.0.8
  .gitignore
  setup/azurecmdfiles.wxi
  src/ResourceManager/Profile/AzureRM.Profile.psd1
  src/ResourceManager/Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/Commands.Profile.csproj
  src/ResourceManager/Profile/Commands.Profile/StartupScripts/AzureRmProfileStartup.ps1
  src/ResourceManager/Profile/Commands.Profile/packages.config
Labels: Waiting for On Demand

#5371 Fixing compute tests by rerecording against azurestack
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/AddVhdTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/ComputeTestCommon.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/DiagnosticsExtensionTests.cs
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/DiagnosticsExtensionTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/DscExtensionTests.cs
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/DscExtensionTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VMDynamicTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineBootDiagnosticsTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineExtensionTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineNetworkInterfaceTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineProfileTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AvailabilitySetTests/TestAvailabilitySet.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeCloudExceptionTests/RunComputeCloudExceptionTests.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiagnosticsExtensionTests/TestDiagnosticsExtensionCantListSepcifyStorageAccountKey.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineBootDiagnosticsTests/TestLinuxVirtualMachineBootDiagnostics.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineBootDiagnosticsTests/TestVirtualMachineBootDiagnosticsPremium.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineBootDiagnosticsTests/TestVirtualMachineBootDiagnosticsSet.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineAccessExtension.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineBginfoExtension.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineCustomScriptExtension.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineCustomScriptExtensionFileUri.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineCustomScriptExtensionSecureExecution.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineExtension.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineExtensionUsingHashTable.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineExtensionWithSwitch.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineNetworkInterfaceTests/TestAddNetworkInterface.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineNetworkInterfaceTests/TestSingleNetworkInterfaceDnsSettings.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineNetworkInterfaceTests/TestVirtualMachineMultipleNetworkInterface.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineNetworkInterfaceTests/TestVirtualMachineSingleNetworkInterface.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSet.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetReimageUpdate.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestGetVMSizeFromAllLocations.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestLinuxVirtualMachine.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMImageCmdletOutputFormat.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachine.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineCapture.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineDataDisk.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineDataDiskNegative.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineImageList.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineList.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachinePIRv2.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachinePiping.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineRedeploy.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineSizeAndUsage.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineTags.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineWithDifferentStorageResource.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineWithEmptyAuc.json
  src/ResourceManager/Compute/Stack/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineWithVMAgentAutoUpdate.json
  src/ResourceManager/Compute/Stack/Compute.sln
  src/ResourceManager/Compute/Stack/Compute.sln_
Labels: Waiting for On Demand

#5634 Move flaky Batch and Profile tests to on-demand build
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/BatchApplicationPackageTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/CertificateTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/ComputeNodeTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/FileTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobScheduleTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/PoolTests.cs
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/TaskTests.cs
  src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/Constants.cs
  src/ResourceManager/Profile/Commands.Profile.Test/ArgumentCompleterTests.cs
  src/ResourceManager/Profile/Commands.Profile.Test/LongRunningCmdletTests.cs
Labels: Waiting for On Demand

#5644 VMSS: loadbalancer rules, public ip address, NAT rules.
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmss.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssImageName.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssWithoutDomainName.json
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.csproj
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ApiEntityReferenceStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ImageEx.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/LinuxConfigurationStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ManagedDiskParametersStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/NetworkInterfaceReferenceStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/SubResourceStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/WindowsConfigurationStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/FrontendIPConfigurationStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/InboundNetPoolStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/LoadBalancerStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/LoadBalancingRuleStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkInterfaceStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkSecurityGroupPolicy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkStrategy.cs
Labels: Waiting for On Demand

#5618 Re-enable batch uploading for Automation testing
  tools/AutomationTestFramework/Management/ModuleUploader.ps1
Labels: Waiting for On Demand

#5662 Add tag to more flaky tests
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/NewVhdVMTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/StrategiesVmssTests.cs
Labels: needs-review

#5480 Fix Startup Scripts to properly export aliases
  src/ResourceManager/AnalysisServices/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Dataplane/StartupScripts/AnalysisServicesDataplaneStartup.ps1
  src/ResourceManager/Automation/ChangeLog.md
  src/ResourceManager/Automation/Commands.Automation/StartupScripts/AzureRmAutomationStartup.ps1
  src/ResourceManager/Cdn/ChangeLog.md
  src/ResourceManager/Cdn/Commands.Cdn/StartupScripts/CdnStartup.ps1
  src/ResourceManager/HDInsight/ChangeLog.md
  src/ResourceManager/HDInsight/Commands.HDInsight/StartupScripts/AzureRmHDInsightStartup.ps1
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/StartupScripts/AzureRmNetworkStartup.ps1
  src/ResourceManager/OperationalInsights/ChangeLog.md
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/StartupScripts/OperationalInsightsStartup.ps1
  src/ResourceManager/Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/StartupScripts/AzureRmProfileStartup.ps1
  src/ResourceManager/RecoveryServices.SiteRecovery/ChangeLog.md
  src/ResourceManager/RecoveryServices.SiteRecovery/Commands.RecoveryServices.SiteRecovery/StartupScripts/RecoveryServicesAsrStartup.ps1
  src/ResourceManager/RecoveryServices/ChangeLog.md
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices/StartupScripts/AzureRmRecoveryServicesStartup.ps1
  src/ResourceManager/Resources/ChangeLog.md
  src/ResourceManager/Resources/Commands.Resources/StartupScripts/AzureRmResourcesStartup.ps1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/StartupScripts/SqlStartup.ps1
  src/ResourceManager/Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites/StartupScripts/WebsitesStartup.ps1
Labels: Waiting for On Demand

#5671 Grammar correction
  src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMOSDisk.md
  src/ResourceManager/Compute/Stack/Commands.Compute/help/Set-AzureRmVMOSDisk.md
Labels: needs-review

#5656 ServiceBus: Added properties to queue and subscription
  src/ResourceManager/ServiceBus/ChangeLog.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/Commands.ServiceBus.Test.csproj
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusQueueTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/ScenarioTests/ServiceBusSubscriptionTests.ps1
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusDRConfigurationTests/ServiceBusDRConfigurationsCURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueueAuth_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueue_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusRuleTests/ServiceBusRule_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpaceAuth_CURD_Tests.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpace_CURD_Tests.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusSubscriptionTests/ServiceBusSubscription_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopicAuth_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopic_CURD.json
  src/ResourceManager/ServiceBus/Commands.ServiceBus.Test/packages.config
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Queue/NewAzureServiceBusQueue.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Subscription/NewAzureServiceBusSubscription.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Topic/NewAzureServiceBusTopic.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Topic/SetAzureServiceBusTopic.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Commands.ServiceBus.csproj
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Models/PSQueueAttributes.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Models/PSSubscriptionAttributes.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Models/PSTopicAttributes.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Utilities/ServiceBusClient.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/New-AzureRmServiceBusQueue.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/New-AzureRmServiceBusSubscription.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/packages.config
Labels: Waiting for On Demand

#5676 add breaking change instructions for Get-AzureRmRoleDefinition
  src/ResourceManager/Resources/Commands.Resources/RoleDefinitions/GetAzureRoleDefinitionCommand.cs
  src/ResourceManager/Resources/documentation/upcoming-breaking-changes.md
Labels: Waiting for On Demand

#5457 Support soft-delete feature in storge dataplane cmdlet
  src/Common/Commands.Common.Storage/Adapters/WindowsAzure.Storage.8/ResourceModel/AzureStorageBlob.cs
  src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj
  src/ResourceManager/Storage/Commands.Management.Storage/packages.config
  src/Storage/Azure.Storage.psd1
  src/Storage/ChangeLog.md
  src/Storage/Commands.Storage.Test/Commands.Storage.Test.csproj
  src/Storage/Commands.Storage.Test/Common/PSServicePropertiesTest.cs
  src/Storage/Commands.Storage.Test/app.config
  src/Storage/Commands.Storage.Test/packages.config
  src/Storage/Commands.Storage/AzureStorageStartup.ps1
  src/Storage/Commands.Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Commands.Storage/Commands.Storage.csproj
  src/Storage/Commands.Storage/Common/Cmdlet/DisableAzureStorageDeleteRetentionPolicy.cs
  src/Storage/Commands.Storage/Common/Cmdlet/EnableAzureStorageDeleteRetentionPolicy.cs
  src/Storage/Commands.Storage/Common/Cmdlet/SetAzureStorageCORSRule.cs
  src/Storage/Commands.Storage/Common/ServicePropertiesExtension.cs
  src/Storage/Commands.Storage/Common/StorageNouns.cs
  src/Storage/Commands.Storage/Microsoft.WindowsAzure.Commands.Storage.format.ps1xml
  src/Storage/Commands.Storage/Model/ResourceModel/PSSeriviceProperties.cs
  src/Storage/Commands.Storage/help/Azure.Storage.md
  src/Storage/Commands.Storage/help/Disable-AzureStorageDeleteRetentionPolicy.md
  src/Storage/Commands.Storage/help/Enable-AzureStorageDeleteRetentionPolicy.md
  src/Storage/Commands.Storage/help/Get-AzureStorageBlob.md
  src/Storage/Commands.Storage/help/Get-AzureStorageServiceProperty.md
  src/Storage/Commands.Storage/packages.config
  tools/StaticAnalysis/Exceptions/AssemblyVersionConflict.csv
  tools/StaticAnalysis/Exceptions/SignatureIssues.csv
Labels: Waiting for On Demand, needs-review

#5270 Adding new Powershell module for ManagedServiceIdentity
  .gitignore
  TestMappings.json
  src/ResourceManager/ManagedServiceIdentity/AzureRM.ManagedServiceIdentity.psd1
  src/ResourceManager/ManagedServiceIdentity/ChangeLog.md
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/App.config
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/Commands.ManagedServiceIdentity.Test.csproj
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/Properties/AssemblyInfo.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/ScenarioTests/CrudTests.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/ScenarioTests/CrudTests.ps1
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/SessionRecords/Microsoft.Azure.Commands.ManagedServiceIdentity.Test.ScenarioTests.CrudTests/TestCrud.json
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/TestController.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity.Test/packages.config
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Commands.ManagedServiceIdentity.csproj
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Common/MsiBaseCmdlet.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Constants.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/MSSharedLibKey.snk
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Models/PSUserAssignedIdentity.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Properties/AssemblyInfo.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Properties/Resources.Designer.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/Properties/Resources.resx
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/UserAssignedIdentities/GetAzureRmUserAssignedIdentityCmdlet.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/UserAssignedIdentities/NewAzureRmUserAssignedIdentityCmdlet.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/UserAssignedIdentities/RemoveAzureRmUserAssignedIdentityCmdlet.cs
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/help/AzureRM.ManagedServiceIdentity.md
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/help/Get-AzureRmUserAssignedIdentity.md
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/help/New-AzureRmUserAssignedIdentity.md
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/help/Remove-AzureRmUserAssignedIdentity.md
  src/ResourceManager/ManagedServiceIdentity/Commands.ManagedServiceIdentity/packages.config
  src/ResourceManager/ManagedServiceIdentity/ManagedServiceIdentity.sln
  src/ResourceManager/ManagedServiceIdentity/NuGet.Config
  src/ResourceManager/ManagedServiceIdentity/documentation/current-breaking-changes.md
  src/ResourceManager/ManagedServiceIdentity/documentation/upcoming-breaking-changes.md
  tools/CreateMappings_rules.json
Labels: Preview, needs-revision

#5585 Website convenience cmdlets
  src/ResourceManager/Common/Commands.ResourceManager.Common/Commands.ResourceManager.Common.csproj
  src/ResourceManager/Common/Commands.ResourceManager.Common/Utilities/Models/Location.cs
  src/ResourceManager/Websites/AzureRM.Websites.Netcore.psd1
  src/ResourceManager/Websites/AzureRM.Websites.psd1
  src/ResourceManager/Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites.Test/Commands.Websites.Test.csproj
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppBackupRestoreTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppSlotTests.cs
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.cs
  src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.ps1
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestCreateNewWebAppBackup.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestCreateNewWebAppBackupPiping.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestEditAndGetWebAppBackupConfiguration.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestEditAndGetWebAppBackupConfigurationPiping.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestGetWebAppBackup.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestGetWebAppBackupList.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestCloneWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestCloneWebAppToSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestCreateNewWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestGetWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestStartStopRestartWebAppSlot.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestWebAppSlotPublishingProfile.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestCloneNewWebApp.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestCreateNewWebApp.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestRemoveWebApp.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetWebApp.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestStartStopRestartWebApp.json
  src/ResourceManager/Websites/Commands.Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestWebAppPublishingProfile.json
  src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/NewAzureWebApp.cs
  src/ResourceManager/Websites/Commands.Websites/Commands.Websites.Netcore.csproj
  src/ResourceManager/Websites/Commands.Websites/Commands.Websites.csproj
  src/ResourceManager/Websites/Commands.Websites/Models.WebApp/PSSite.cs
  src/ResourceManager/Websites/Commands.Websites/Properties/Resources.Designer.cs
  src/ResourceManager/Websites/Commands.Websites/Properties/Resources.resx
  src/ResourceManager/Websites/Commands.Websites/Strategies/AppServicePolicy.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/ExternalCommand.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/GitCommand.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/ICmdletAdapter.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/PSCmdletAdapter.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/ResourceGroupStrategy.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/ServerFarmStrategy.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/SiteStrategy.cs
  src/ResourceManager/Websites/Commands.Websites/Strategies/WebClient.cs
  src/ResourceManager/Websites/Commands.Websites/help/New-AzureRmWebApp.md
  src/ResourceManager/Websites/WebSites.sln
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
Labels: Waiting for On Demand

#5668 New-AzureRmVMSS: prints connection strings
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Properties/Resources.Designer.cs
  src/ResourceManager/Compute/Commands.Compute/Properties/Resources.resx
  src/ResourceManager/Compute/Commands.Compute/Strategies/AsyncCmdletExtensions.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/AvailabilitySetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ComputeStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ManagedDiskStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#5686 Fix parameter set name
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVM.md
Labels: Waiting for On Demand

#5693 Update NewVhdVMTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/NewVhdVMTests.cs
Labels: needs-review

#5691 Update wxi to include missing assembly from Websites project
  setup/azurecmdfiles.wxi
  src/ResourceManager/AzureBatch/Commands.Batch.Test/ScenarioTests/JobScheduleTests.cs
Labels: Waiting for On Demand

#5672 Fixes for manifest issues in Netcore.
  build.proj
  src/ResourceManager/Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/KeyVault/AzureRM.KeyVault.Netcore.psd1
  src/ResourceManager/Kubernetes/Commands.Kubernetes/Commands.Kubernetes.Netcore.csproj
  src/ResourceManager/Network/AzureRM.Network.Netcore.psd1
  src/ResourceManager/Profile/AzureRM.Profile.Netcore.psd1
  src/ResourceManager/Resources/AzureRM.Resources.Netcore.psd1
  src/ResourceManager/Resources/Commands.Resources/Commands.Resources.Netcore.csproj
  src/ResourceManager/Storage/AzureRM.Storage.Netcore.psd1
  src/ResourceManager/Tags/AzureRM.Tags.Netcore.psd1
  src/ResourceManager/Websites/AzureRM.Websites.Netcore.psd1
  tools/AzureRM.Netcore/AzureRM.Netcore.psd1
  tools/UpdateModules.ps1
Labels: Waiting for On Demand

#5508 This change enables four byte unsigned AS Numbers
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/ExpressRouteCircuit/Peering/AzureExpressRouteCircuitPeeringConfigBase.cs
  src/ResourceManager/Network/Commands.Network/Models/PSPeering.cs
  src/ResourceManager/Network/Commands.Network/help/Add-AzureRmExpressRouteCircuitPeeringConfig.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmExpressRouteCircuitPeeringConfig.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzureRmExpressRouteCircuitPeeringConfig.md
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
Labels: Waiting for On Demand

#5665 [Compute] Add cmdlets for CRP Log Analytics.
  src/ResourceManager/Compute/AzureRM.Compute.psd1
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/Common/ComputeTestController.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/LogAnalyticTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/LogAnalyticTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.LogAnalyticTests/TestExportLogAnalyticRequestRateByIntervalNegative.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.LogAnalyticTests/TestExportLogAnalyticThrottledRequestsNegative.json
  src/ResourceManager/Compute/Commands.Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.LogAnalyticTests/TestExportLogAnalytics.json
  src/ResourceManager/Compute/Commands.Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/ContainerService/ContainerServiceDeleteMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Disk/DiskDeleteMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Disk/DiskGrantAccessMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Image/ImageDeleteMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/InvokeAzureComputeMethodCmdlet.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/LogAnalytic/LogAnalyticExportRequestRateByIntervalMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/LogAnalytic/LogAnalyticExportThrottledRequestsMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Microsoft.Azure.Commands.Compute.Automation.format.generated.ps1xml
  src/ResourceManager/Compute/Commands.Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Models/PSLogAnalyticsOperationResult.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/SnapshotDeleteMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/Snapshot/SnapshotGrantAccessMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetDeallocateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetDeleteInstancesMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetReimageMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetRollingUpgrade/VirtualMachineScaleSetRollingUpgradeCancelMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMGetMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMReimageMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Properties/Resources.Designer.cs
  src/ResourceManager/Compute/Commands.Compute/Properties/Resources.resx
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/SetAzureVMOperatingSystemCommand.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/ResourceManager/Compute/Commands.Compute/help/AzureRM.Compute.md
  src/ResourceManager/Compute/Commands.Compute/help/Export-AzureRmLogAnalyticRequestRateByInterval.md
  src/ResourceManager/Compute/Commands.Compute/help/Export-AzureRmLogAnalyticThrottledRequests.md
  src/ResourceManager/Compute/Commands.Compute/help/Grant-AzureRmDiskAccess.md
  src/ResourceManager/Compute/Commands.Compute/help/Grant-AzureRmSnapshotAccess.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVMConfig.md
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmss.md
  src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVM.md
  src/ResourceManager/Compute/Commands.Compute/help/Update-AzureRmVM.md
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/SignatureIssues.csv
Labels: Waiting for On Demand

#5712 Fixes:#5711- Updating the help for Remove-AzureRmWebAppSlot, missing …
  src/ResourceManager/Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites/help/Remove-AzureRmWebAppSlot.md
Labels: Waiting for On Demand

#5720 [Azure Analysis Services] Fix unique Id is null or empty bug
  src/ResourceManager/AnalysisServices/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Dataplane/Models/TokenCacheItemProvider.cs
Labels: Waiting for On Demand

#5103 New MSI Generation
  .gitignore
  AzurePowershell.Test.targets
  build.proj
  setup/PowerShellSetup.Test/MSSharedLibKey.snk
  setup/PowerShellSetup.Test/MsiLayoutTests.cs
  setup/PowerShellSetup.Test/MsiTestBase.cs
  setup/PowerShellSetup.Test/PowerShellSetup.Test.csproj
  setup/PowerShellSetup.Test/Properties/AssemblyInfo.cs
  setup/PowerShellSetup.Test/packages.config
  setup/Setup/CustomAction.config
  setup/Setup/CustomAction.cs
  setup/Setup/MSSharedLibKey.snk
  setup/Setup/Properties/AssemblyInfo.cs
  setup/Setup/RemoveGalleryModules.ps1
  setup/Setup/SetExecutionPolicy.ps1
  setup/Setup/Setup.csproj
  setup/Setup/ShellLink.cs
  setup/azurecmd.wxs
  setup/azurecmdfiles.wxi
  setup/azurepowershell.sln
  setup/azurepowershell.wixproj
  setup/generate.ps1
Labels: needs-review

#5731 Fix bug to serialize and display IPTags
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/PSPublicIpAddress.cs
Labels: Waiting for On Demand

#5716 Fix VHD test #5692
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/NewVhdVMTests.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ComputeStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#5722 Improved strategy cmdlets for VM and VMSS.
  src/ResourceManager/Common/Commands.Common.Strategies/ResourceConfigExtensions.cs
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.csproj
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/AvailabilitySetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ImageEx.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/LinuxConfigurationStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/WindowsConfigurationStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/IParameters.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkSecurityGroupPolicy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/PublicIPAddressStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/StrategyCmdlet.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#5739 [Doc update] Commands.Common.Compute item added to the "Adding Project References/…
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: Do Not Merge, needs-review

#5758 Changed RunOn description from hybrid agent to hybrid worker group
  src/ResourceManager/Automation/Commands.Automation/help/New-AzureRMAutomationWebhook.md
Labels: Waiting for On Demand

#5755 Updating the SDK version for ADF
  src/ResourceManager/DataFactories/ChangeLog.md
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/Commands.DataFactoryV2.Test.csproj
  src/ResourceManager/DataFactories/Commands.DataFactoryV2.Test/packages.config
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Commands.DataFactoryV2.csproj
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/packages.config
Labels: Waiting for On Demand

#5706 Ensure MSI token auth on all authentication paths
  src/Common/Commands.Common.Authentication/Authentication/RenewingTokenCredential.cs
  src/Common/Commands.Common.Authentication/Authentication/ServicePrincipalTokenProvider.cs
  src/Common/Commands.Common.Authentication/Commands.Common.Authentication.csproj
  src/Common/Commands.Common.Authentication/Factories/AuthenticationFactory.cs
Labels: Waiting for On Demand

#5653 New suppression file for the Credential Scanner (was updated in the ci-signing repo)
  tools/CredScanSuppressions.json
Labels: Waiting for On Demand

#5767 Move change log entry from DataFactories to DataFactoryV2
  src/ResourceManager/DataFactories/ChangeLog.md
  src/ResourceManager/DataFactories/Commands.DataFactoryV2/Changelog.md
Labels: needs-review

#5765 Fix RecoveryServices build issue
  src/ResourceManager/AnalysisServices/ChangeLog.md
  src/ResourceManager/AnalysisServices/Commands.AnalysisServices.Dataplane/StartupScripts/AzureAnalysisServicesStartup.ps1
  src/ResourceManager/Cdn/ChangeLog.md
  src/ResourceManager/Cdn/Commands.Cdn/StartupScripts/AzureRmCdnStartup.ps1
  src/ResourceManager/OperationalInsights/ChangeLog.md
  src/ResourceManager/OperationalInsights/Commands.OperationalInsights/StartupScripts/AzureRmOperationalInsightsStartup.ps1
  src/ResourceManager/RecoveryServices.Backup/ChangeLog.md
  src/ResourceManager/RecoveryServices.SiteRecovery/ChangeLog.md
  src/ResourceManager/RecoveryServices.SiteRecovery/Commands.RecoveryServices.SiteRecovery/StartupScripts/AzureRmRecoveryServicesSiteRecoveryStartup.ps1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/StartupScripts/AzureRmSqlStartup.ps1
  src/ResourceManager/Websites/ChangeLog.md
  src/ResourceManager/Websites/Commands.Websites/StartupScripts/AzureRmWebsitesStartup.ps1
  tools/CleanupBuild.ps1
Labels: needs-review

#5761 Prepare Dns and Network modules for release
  src/ResourceManager/Dns/AzureRM.Dns.psd1
  src/ResourceManager/Dns/ChangeLog.md
  src/ResourceManager/Dns/Commands.Dns/Properties/AssemblyInfo.cs
  src/ResourceManager/Network/AzureRM.Network.psd1
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/Network/Commands.Network/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
Labels: Waiting for On Demand

#5752 Fix defaultresourcegroup in CloudShell
  src/ResourceManager/AnalysisServices/ChangeLog.md
  src/ResourceManager/ApiManagement/ChangeLog.md
  src/ResourceManager/ApplicationInsights/ChangeLog.md
  src/ResourceManager/Automation/ChangeLog.md
  src/ResourceManager/AzureBackup/ChangeLog.md
  src/ResourceManager/AzureBatch/ChangeLog.md
  src/ResourceManager/Cdn/ChangeLog.md
  src/ResourceManager/CognitiveServices/ChangeLog.md
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/ContainerInstance/ChangeLog.md
  src/ResourceManager/ContainerRegistry/ChangeLog.md
  src/ResourceManager/DataFactories/ChangeLog.md
  src/ResourceManager/DataLakeAnalytics/ChangeLog.md
  src/ResourceManager/DevTestLabs/ChangeLog.md
  src/ResourceManager/Dns/ChangeLog.md
  src/ResourceManager/EventHub/ChangeLog.md
  src/ResourceManager/HDInsight/ChangeLog.md
  src/ResourceManager/Insights/ChangeLog.md
  src/ResourceManager/IotHub/ChangeLog.md
  src/ResourceManager/KeyVault/ChangeLog.md
  src/ResourceManager/LogicApp/ChangeLog.md
  src/ResourceManager/MachineLearning/ChangeLog.md
  src/ResourceManager/MachineLearningCompute/ChangeLog.md
  src/ResourceManager/Media/ChangeLog.md
  src/ResourceManager/Network/ChangeLog.md
  src/ResourceManager/OperationalInsights/ChangeLog.md
  src/ResourceManager/PowerBIEmbedded/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/Default/ClearAzureRmDefault.cs
  src/ResourceManager/Profile/Commands.Profile/Default/GetAzureRmDefault.cs
  src/ResourceManager/Profile/Commands.Profile/Default/SetAzureRMDefault.cs
  src/ResourceManager/RecoveryServices/ChangeLog.md
  src/ResourceManager/RedisCache/ChangeLog.md
  src/ResourceManager/Relay/ChangeLog.md
  src/ResourceManager/Resources/ChangeLog.md
  src/ResourceManager/Scheduler/ChangeLog.md
  src/ResourceManager/ServerManagement/ChangeLog.md
  src/ResourceManager/ServiceBus/ChangeLog.md
  src/ResourceManager/ServiceFabric/ChangeLog.md
  src/ResourceManager/SiteRecovery/ChangeLog.md
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Storage/ChangeLog.md
  src/ResourceManager/StreamAnalytics/ChangeLog.md
  src/ResourceManager/TrafficManager/ChangeLog.md
  src/ResourceManager/Websites/ChangeLog.md
  tools/AzureRM.Example.psm1
Labels: Waiting for On Demand

#5734 New-AzureRmVM/VMSS: DataDiskSizeInGb parameter
  src/ResourceManager/Common/Commands.Common.Strategies/Extensions.cs
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.csproj
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ComputeStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/DataDiskStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ImageAndOsType.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ImageDataDiskStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/ImageEx.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/StrategyCmdlet.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#5573 Adls data plane task add debug functionality
  src/ResourceManager/DataLakeStore/ChangeLog.md
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/Commands.DataLakeStore.csproj
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/ExportAzureRmDataLakeStoreItem.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/ImportAzureRmDataLakeStoreItem.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/AdlsLoggerTarget.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemCmdletBase.cs
  src/ResourceManager/DataLakeStore/Commands.DataLakeStore/packages.config
Labels: Waiting for On Demand

#5689 Fix for https://github.com/Azure/azure-powershell/issues/5506
  src/ResourceManager/ContainerInstance/ChangeLog.md
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance.Test/ScenarioTests/ContainerInstanceTests.ps1
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance.Test/SessionRecords/Microsoft.Azure.Commands.ContainerInstance.Test.ScenarioTests.ContainerInstanceTests/TestCreateContainerGroupWithVolume.json
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/Commands/NewAzureContainerGroupCommand.cs
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/Models/ContainerGroupCreationParameters.cs
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/help/AzureRM.ContainerInstance.md
  src/ResourceManager/ContainerInstance/Commands.ContainerInstance/help/New-AzureRmContainerGroup.md
Labels: Waiting for On Demand

#5779 Fix for Netcore build cleanup.
  tools/CleanupBuild.ps1
Labels: needs-revision

#5788 Update New-AzureRmVpnClientConfiguration.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmVpnClientConfiguration.md
Labels: needs-review

#5783 Update New-AzureRmApplicationSecurityGroup.md
  src/ResourceManager/Network/Commands.Network/help/New-AzureRmApplicationSecurityGroup.md
Labels: needs-review

#5707 Fix for Enable-AzureRmContextAutosave in Netcore (#5690).
  src/Common/Commands.Common.Authentication/Authentication/ProtectedFileTokenCache.cs
  src/ServiceManagement/Services/Commands.Test/Profile/ProfileCmdltsTests.cs
Labels: Waiting for On Demand

#5813 Update AzureDiskEncryptionPreRequisiteSetup.ps1 no parameter declared for $volumeType
  src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1
Labels: needs-revision

#5822 Fix issues with signing Netcore modules
  build.proj
  src/Common/Commands.Common.Compute/Commands.Common.Compute.Netcore.csproj
  src/ResourceManager/Aks/Commands.Aks/Commands.Aks.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.Netcore.csproj
  src/ResourceManager/Profile/Commands.Profile/Commands.Profile.Netcore.csproj
  src/ResourceManager/Resources/AzureRM.Resources.Netcore.psd1
  tools/PublishModules.ps1
Labels: Waiting for CI

#5804 add partner name in managementpartner commands response
  src/ResourceManager/ManagementPartner/ChangeLog.md
  src/ResourceManager/ManagementPartner/Commands.Partner/Commands.Partner.csproj
  src/ResourceManager/ManagementPartner/Commands.Partner/ManagementPartner/PSManagementPartner.cs
  src/ResourceManager/ManagementPartner/Commands.Partner/help/Get-AzureRmManagementPartner.md
  src/ResourceManager/ManagementPartner/Commands.Partner/help/New-AzureRmManagementPartner.md
  src/ResourceManager/ManagementPartner/Commands.Partner/help/Update-AzureRmManagementPartner.md
  src/ResourceManager/ManagementPartner/Commands.Partner/packages.config
Labels: needs-revision

#5770 LTR V2 Powershell cmdlets
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestDatabaseBackupLongTermRetentionPolicy.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2Backup.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2Policy.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCancelOperation.json
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/TestLongTermRetentionV2.json
  src/ResourceManager/Sql/Commands.Sql.Test/packages.config
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/AzureSqlDatabaseLongTermRetentionBackupCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/GetAzureRmSqlDatabaseLongTermRetentionBackup.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/GetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/RemoveAzureRmSqlDatabaseLongTermRetentionBackup.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Cmdlet/SetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Model/AzureSqlDatabaseBackupLongTermRetentionPolicyModel.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Model/AzureSqlDatabaseLongTermRetentionBackupModel.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Model/AzureSqlDatabaseLongTermRetentionPolicyModel.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/Database Backup/Services/AzureSqlDatabaseBackupCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/ResourceManager/Sql/Commands.Sql/Properties/Resources.Designer.cs
  src/ResourceManager/Sql/Commands.Sql/Properties/Resources.resx
  src/ResourceManager/Sql/Commands.Sql/StartupScripts/AzureRmSqlStartup.ps1
  src/ResourceManager/Sql/Commands.Sql/help/AzureRM.Sql.md
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy.md
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzureRmSqlDatabaseLongTermRetentionBackup.md
  src/ResourceManager/Sql/Commands.Sql/help/Remove-AzureRmSqlDatabaseLongTermRetentionBackup.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabaseBackupLongTermRetentionPolicy.md
  src/ResourceManager/Sql/Commands.Sql/packages.config
  tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv
Labels: Waiting for On Demand

#5839 Update help message for set database maxSizeBytes parameter
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabase.md
Labels: Waiting for CI

#5820 ServiceBus: updated New-AzureRmServiceBusGeoDRConfiguration help and fixed Rules cmdlet output
  src/ResourceManager/ServiceBus/ChangeLog.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Microsoft.Azure.Commands.ServiceBus.format.ps1xml
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Models/PSRulesAttributes.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/Utilities/ServiceBusClient.cs
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/New-AzureRmServiceBusGeoDRConfiguration.md
Labels: needs-revision

#5825 Update AzureRM.Compute for preview release
  src/ResourceManager/Compute/AzureRM.Compute.psd1
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Properties/AssemblyInfo.cs
  tools/AzureRM/AzureRM.psd1
Labels: needs-review

#5791 New-AzureRmVm(Vmss): simple parameter set: Zones
  src/ResourceManager/Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/SubResourceStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/FrontendIPConfigurationStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/LoadBalancerStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/NetworkSecurityGroupPolicy.cs
  src/ResourceManager/Compute/Commands.Compute/Strategies/Network/PublicIPAddressStrategy.cs
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for On Demand

#5762 Add new cmdlet, update commands.Sql and tests for 'List database operation' and 'List/Cancel elastic pool operation'
  src/ResourceManager/Sql/AzureRM.Sql.psd1
  src/ResourceManager/Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql.Test/Commands.Sql.Test.csproj
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ElasticPoolCrudTests.cs
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ElasticPoolCrudTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestElasticPoolCancelOperation.json
  src/ResourceManager/Sql/Commands.Sql/Commands.Sql.csproj
  src/ResourceManager/Sql/Commands.Sql/Database/Model/AzureSqlDatabaseActivityModel.cs
  src/ResourceManager/Sql/Commands.Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Cmdlet/AzureSqlElasticPoolActivityCmdletBase.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Cmdlet/StopAzureSqlElasticPoolActivity.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Model/AzureSqlElasticPoolActivityModel.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/ResourceManager/Sql/Commands.Sql/Elastic Pools/Services/AzureSqlElasticPoolCommunicator.cs
  src/ResourceManager/Sql/Commands.Sql/help/AzureRM.Sql.md
  src/ResourceManager/Sql/Commands.Sql/help/Stop-AzureRmSqlElasticPoolActivity.md
Labels: Waiting for On Demand

#5666 Tool to generate format.ps1xml
  TestMappings.json
  build.proj
  src/Common/Commands.Common/Attributes/Ps1XmlAttribute.cs
  src/Common/Commands.Common/Commands.Common.csproj
  src/ResourceManager/Common/Commands.Common.Authentication.ResourceManager/Models/PSAzureSubscription.cs
  tools/RepoTasks/NuGet.Config
  tools/RepoTasks/RepoTasks.Attributes/Properties/AssemblyInfo.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/AppDomainWorkerShould.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/Constants.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/Dummy.psd1
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/NewFormatPs1XmlCommandShould.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/Properties/AssemblyInfo.cs
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/RepoTasks.Cmdlets.Tests.csproj
  tools/RepoTasks/RepoTasks.Cmdlets.Tests/packages.config
  tools/RepoTasks/RepoTasks.Cmdlets/NewFormatPs1XmlCommand.cs
  tools/RepoTasks/RepoTasks.Cmdlets/Properties/AssemblyInfo.cs
  tools/RepoTasks/RepoTasks.Cmdlets/RepoTasks.Cmdlets.csproj
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsDummyOutput1.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsDummyOutput2.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsDummyOutputTwo.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Models/PsOperation.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/Properties/AssemblyInfo.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/RepoTasks.CmdletsForTest.csproj
  tools/RepoTasks/RepoTasks.CmdletsForTest/TestDummyCommand.cs
  tools/RepoTasks/RepoTasks.CmdletsForTest/TestDummyCommand1.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/AppDomainWorker.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/IReflectionWorker.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/Properties/AssemblyInfo.cs
  tools/RepoTasks/RepoTasks.RemoteWorker/RepoTasks.RemoteWorker.csproj
  tools/RepoTasks/RepoTasks.RemoteWorker/XmlViewDefinition.cs
  tools/RepoTasks/RepoTasks.sln
Labels: Waiting for On Demand

#5746 [Storage] Fix MD5 not work on FIPS enabled machine issue
  src/Storage/ChangeLog.md
  src/Storage/Commands.Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Commands.Storage/Common/StorageCloudCmdletBase.cs
  src/Storage/Commands.Storage/File/Cmdlet/SetAzureStorageFileContent.cs
Labels: Waiting for On Demand

#5798 Add deprecation messages and fixes for KeyVault
  src/ResourceManager/KeyVault/ChangeLog.md
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/AddAzureKeyVaultCertificate.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/ManagedStorageAccounts/SetAzureKeyVaultManagedStorageSasDefinition.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/RemoveAzureKeyVault.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/SetAzureKeyVaultCertificateIssuer.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/SetAzureKeyVaultSecretAttribute.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/UndoAzureKeyVaultCertificateRemoval.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Commands/UndoAzureKeyVaultRemoval.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Models/ModelExtensions.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Properties/Resources.Designer.cs
  src/ResourceManager/KeyVault/Commands.KeyVault/Properties/Resources.resx
  src/ResourceManager/KeyVault/Commands.KeyVault/help/Remove-AzureRmKeyVault.md
  src/ResourceManager/KeyVault/Commands.KeyVault/help/Set-AzureKeyVaultCertificatePolicy.md
  src/ResourceManager/KeyVault/documentation/upcoming-breaking-changes.md
Labels: Waiting for On Demand

#5790 [Billing RP] Get-AzureRmEnrollmentAccount
  src/ResourceManager/Billing/AzureRM.Billing.Netcore.psd1
  src/ResourceManager/Billing/AzureRM.Billing.psd1
  src/ResourceManager/Billing/ChangeLog.md
  src/ResourceManager/Billing/Commands.Billing.Test/Commands.Billing.Test.csproj
  src/ResourceManager/Billing/Commands.Billing.Test/ScenarioTests/BillingPeriodsTests.ps1
  src/ResourceManager/Billing/Commands.Billing.Test/ScenarioTests/EnrollmentAccountTests.cs
  src/ResourceManager/Billing/Commands.Billing.Test/ScenarioTests/EnrollmentAccountTests.ps1
  src/ResourceManager/Billing/Commands.Billing.Test/ScenarioTests/InvoicesTests.ps1
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.BillingPeriodsTests/TestGetBillingPeriodWithName.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.BillingPeriodsTests/TestGetBillingPeriodWithNames.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.BillingPeriodsTests/TestListBillingPeriods.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.BillingPeriodsTests/TestListBillingPeriodsWithMaxCount.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.EnrollmentAccountTests/TestGetEnrollmentAccountWithName.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.EnrollmentAccountTests/TestListEnrollmentAccounts.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.InvoicesTests/TestGetInvoiceWithName.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.InvoicesTests/TestGetInvoiceWithNames.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.InvoicesTests/TestGetLatestInvoice.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.InvoicesTests/TestListInvoices.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.InvoicesTests/TestListInvoicesWithDownloadUrl.json
  src/ResourceManager/Billing/Commands.Billing.Test/SessionRecords/Microsoft.Azure.Commands.Billing.Test.ScenarioTests.InvoicesTests/TestListInvoicesWithMaxCount.json
  src/ResourceManager/Billing/Commands.Billing/Cmdlets/EnrollmentAccounts/GetAzureRmEnrollmentAccount.cs
  src/ResourceManager/Billing/Commands.Billing/Commands.Billing.Netcore.csproj
  src/ResourceManager/Billing/Commands.Billing/Commands.Billing.csproj
  src/ResourceManager/Billing/Commands.Billing/Microsoft.Azure.Commands.Billing.Format.ps1xml
  src/ResourceManager/Billing/Commands.Billing/Models/PSEnrollmentAccount.cs
  src/ResourceManager/Billing/Commands.Billing/help/Get-AzureRmBillingInvoice.md
  src/ResourceManager/Billing/Commands.Billing/help/Get-AzureRmBillingPeriod.md
  src/ResourceManager/Billing/Commands.Billing/help/Get-AzureRmEnrollmentAccount.md
  src/ResourceManager/Billing/Commands.Billing/packages.config
Labels: Cmdlet Review Complete, Waiting for On Demand

#5829 NetCore Storage changes
  Azure.PowerShell.Netcore.sln
  src/Common/Commands.Common/AzureDataCmdlet.cs
  src/ResourceManager/Compute/AzureRM.Compute.Netcore.psd1
  src/ResourceManager/Network/AzureRM.Network.Netcore.psd1
  src/ResourceManager/Profile/AzureRM.Profile.Netcore.psd1
  src/ResourceManager/Resources/AzureRM.Resources.Netcore.psd1
  src/Storage/Azure.Storage.Netcore.psd1
  src/Storage/Commands.Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Commands.Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Commands.Storage/Commands.Storage.Netcore.csproj
  src/Storage/Commands.Storage/Commands.Storage.csproj
  src/Storage/Commands.Storage/Common/Cmdlet/NewAzureStorageContext.cs
  src/Storage/Commands.Storage/Common/CmdletOperationContext.cs
  src/Storage/Commands.Storage/Common/SasTokenHelper.cs
  src/Storage/Commands.Storage/Common/StorageCloudCmdletBase.cs
  src/Storage/Commands.Storage/Common/Util.cs
  src/Storage/Commands.Storage/File/AzureStorageFileCmdletBase.cs
  src/Storage/Commands.Storage/File/Cmdlet/NewAzureStorageShareStoredAccessPolicy.cs
  src/Storage/Commands.Storage/File/Cmdlet/StartAzureStorageFileCopy.cs
  src/Storage/Commands.Storage/Model/Contract/StorageBlobManagement.cs
  src/Storage/Commands.Storage/Model/Contract/StorageFileManagement.cs
  src/Storage/Commands.Storage/Model/Contract/StorageQueueManagement.cs
  src/Storage/Commands.Storage/Model/Contract/StorageTableManagement.cs
  src/Storage/Commands.Storage/Table/StorageCloudTableCmdletBase.cs
  src/Storage/Storage.sln
  tools/Common.Netcore.Dependencies.targets
Labels: NetCore, Waiting for CI
