Repository Azure/azure-powershell, pull requests merged in 2019-04, with the labels that each got.

#8891 Remove trailing empty argument in ContainerCommand
  src/ContainerInstance/ContainerInstance/ChangeLog.md
  src/ContainerInstance/ContainerInstance/Commands/NewAzureContainerGroupCommand.cs
Labels: Waiting for CI :shipit:

#8903 Update AzureFirewall examples
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/Remove-AzFirewall.md
  src/Network/Network/help/Set-AzFirewall.md
Labels: Waiting for CI :shipit:

#8905 AsJob support for storage upload and download cmdlets
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobContent.md
  src/Storage/Storage.Management/help/Get-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
  src/Storage/Storage.Management/help/Set-AzStorageFileContent.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/StartAzureStorageBlobCopy.cs
  src/Storage/Storage/Blob/StorageDataMovementCmdletBase.cs
  src/Storage/Storage/Common/StorageCloudCmdletBase.cs
  src/Storage/Storage/File/Cmdlet/GetAzureStorageFileContent.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageFileContent.cs
  src/Storage/Storage/File/Cmdlet/StartAzureStorageFileCopy.cs
  src/Storage/Storage/File/StorageFileDataManagementCmdletBase.cs
  src/Storage/Storage/Resources.Designer.cs
Labels: Waiting for CI :shipit:

#8902 [flowlog] fix bug for FormatVersion (issue 8877)
  src/Network/Network/NetworkWatcher/SetAzureNetworkWatcherConfigFlowLogCommand.cs
Labels: needs-review

#8917 Fix parameter name in New-AzActionGroup helper file example
  src/Monitor/Monitor/help/New-AzActionGroup.md
Labels: Waiting for CI :shipit:

#8913 Fix Net472 test build
  build.proj
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.ps1
  tools/TestNet472Modules.ps1
Labels: needs-revision

#8858 Update CI build to run tests for NetCoreApp 2.1 by default
  build.proj
Labels: Waiting for CI :shipit:

#8900 Restructure Analysis Services dataplane cmdlets to use Az module login.
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Environment/AddAzureRMEnvironment.cs
  src/Accounts/Accounts/Environment/SetAzureRMEnvironment.cs
  src/Accounts/Accounts/help/Add-AzEnvironment.md
  src/Accounts/Accounts/help/Set-AzEnvironment.md
  src/AnalysisServices/AnalysisServices.Dataplane/Commands/AddAzureASAccount.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Commands/Export-AzureAsInstanceLog.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Commands/Restart-AzureAsInstance.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Commands/Synchronize-AzureASInstance.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/ASAzureContext.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureAccount.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureAuthenticationProvider.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureClientSession.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureDataplaneClient.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureDataplaneCmdletBase.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureEndpoints.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureEnvironment.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureHttpClient.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureProfile.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/IAsAzureHttpClient.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Models/TokenCacheItemProvider.cs
  src/AnalysisServices/AnalysisServices.Test/InMemoryTests/AddAzureASAccountTests.cs
  src/AnalysisServices/AnalysisServices.Test/InMemoryTests/DataPlaneCommandTests.cs
  src/AnalysisServices/AnalysisServices/ChangeLog.md
  src/AnalysisServices/AnalysisServices/help/Add-AzAnalysisServicesAccount.md
  src/AnalysisServices/AnalysisServices/help/Az.AnalysisServices.md
  src/AnalysisServices/AnalysisServices/help/Export-AzAnalysisServicesInstanceLog.md
  src/AnalysisServices/AnalysisServices/help/Get-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesFirewallConfig.md
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesFirewallRule.md
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Remove-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Restart-AzAnalysisServicesInstance.md
  src/AnalysisServices/AnalysisServices/help/Resume-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Set-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Suspend-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Sync-AzAnalysisServicesInstance.md
  src/AnalysisServices/AnalysisServices/help/Test-AzAnalysisServicesServer.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#8918 Enable build filtering for ADO and Travis
  .gitignore
  .travis.yml
  build.proj
  build/jobs.yml
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks.sln
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/FilesChangedTask.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/Microsoft.Azure.Build.Tasks.csproj
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/VerifyAuthenticodeSignatureTask.cs
  tools/CreateFilterMappings.ps1
Labels: needs-review

#8755 Update docs in repository
  CONTRIBUTING.md
  README.md
  documentation/Debugging-StaticAnalysis-Errors.md
  documentation/development-docs/azure-powershell-design-guidelines.md
  documentation/development-docs/azure-powershell-developer-guide.md
  documentation/development-docs/design-guidelines/README.md
  documentation/development-docs/design-guidelines/cmdlet-best-practices.md
  documentation/development-docs/design-guidelines/module-best-practices.md
  documentation/development-docs/design-guidelines/parameter-best-practices.md
  documentation/development-docs/design-guidelines/piping-best-practices.md
  documentation/development-docs/design-guidelines/should-process-confirm-impact.md
  documentation/development-docs/examples/README.md
  documentation/development-docs/examples/get-cmdlet-example.md
  documentation/development-docs/examples/new-cmdlet-example.md
  documentation/development-docs/examples/remove-cmdlet-example.md
  documentation/development-docs/examples/set-cmdlet-example.md
  documentation/development-docs/examples/update-cmdlet-example.md
  documentation/development-docs/generate-format.ps1xml-file.md
  documentation/development-docs/patterns-for-standard-cmdlets.md
  documentation/development-docs/piping-in-powershell.md
  documentation/images/MicrosoftAzure-32px.png
  documentation/images/MicrosoftPowerShellCore-32px.png
  documentation/installing-az-modules.md
Labels: Waiting for CI :shipit:

#8845 Fixed bug reported in ICM 111756056
  src/Automation/Automation.Test/ScenarioTests/UpdateManagementTests.cs
  src/Automation/Automation.Test/ScenarioTests/UpdateManagementTests.ps1
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateLinuxIncludePackageNameMasksSUC.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateWindowsIncludeKbNumbersSUC.json
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClientSoftwareUpdateConfiguration.cs
Labels: Waiting for CI :shipit:

#8936 Add 2 hour timeout for Test job
  build/jobs.yml
Labels: Waiting for CI :shipit:, needs-review

#8939 Populate missing elements in resources string for Remove-AzRoleAssignment
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
Labels: Waiting for CI :shipit:

#8937 Cmdlets support for redirect routing rule and enforce certificate name check in front-door
  src/FrontDoor/FrontDoor.Test/FrontDoor.Test.csproj
  src/FrontDoor/FrontDoor.Test/ScenarioTests/FrontDoorTests.cs
  src/FrontDoor/FrontDoor.Test/ScenarioTests/FrontDoorTests.ps1
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrud.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrudRedirect.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrudWithPiping.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorEndpointCustomDomainHTTPSFrontDoor.json
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoor.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorRoutingRuleObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/SetAzureRmFrontDoor.cs
  src/FrontDoor/FrontDoor/Common/AzureFrontDoorCmdletBase.cs
  src/FrontDoor/FrontDoor/FrontDoor.csproj
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
  src/FrontDoor/FrontDoor/Models/PSEnforceCertificateNameCheck.cs
  src/FrontDoor/FrontDoor/Models/PSFrontDoor.cs
  src/FrontDoor/FrontDoor/Models/PSRedirectProtocol.cs
  src/FrontDoor/FrontDoor/Models/PSRedirectType.cs
  src/FrontDoor/FrontDoor/Models/PSRoutingRule.cs
  src/FrontDoor/FrontDoor/help/Disable-AzFrontDoorCustomDomainHttps.md
  src/FrontDoor/FrontDoor/help/Enable-AzFrontDoorCustomDomainHttps.md
  src/FrontDoor/FrontDoor/help/Get-AzFrontDoor.md
  src/FrontDoor/FrontDoor/help/Get-AzFrontDoorFireWallPolicy.md
  src/FrontDoor/FrontDoor/help/Get-AzFrontDoorFrontendEndpoint.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoor.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorBackendObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorBackendPoolObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorCustomRuleObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorFireWallPolicy.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorFrontendEndpointObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorHealthProbeSettingObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorLoadBalancingSettingObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorManagedRuleObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorManagedRuleOverrideObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorMatchConditionObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorRoutingRuleObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorRuleGroupOverrideObject.md
  src/FrontDoor/FrontDoor/help/Remove-AzFrontDoor.md
  src/FrontDoor/FrontDoor/help/Remove-AzFrontDoorContent.md
  src/FrontDoor/FrontDoor/help/Remove-AzFrontDoorFireWallPolicy.md
  src/FrontDoor/FrontDoor/help/Set-AzFrontDoor.md
  src/FrontDoor/FrontDoor/help/Update-AzFrontDoorFireWallPolicy.md
  tools/StaticAnalysis/Exceptions/Az.FrontDoor/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#8919 Added new parameter to the Set-AzDataFactoryV2 cmdlet to supporet Rep…
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.cs
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.DataFactoryTests/TestCreateDataFactoryV2WithGitHubRepoConfig.json
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.DataFactoryTests/TestCreateDataFactoryV2WithVSTSRepoConfig.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/DataFactories/SetAzureDataFactoryCommand.cs
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
  src/DataFactory/DataFactoryV2/Models/CreatePSDataFactoryParameters.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.DataFactories.cs
  src/DataFactory/DataFactoryV2/Models/PSActivityRun.cs
  src/DataFactory/DataFactoryV2/Models/PSDataFactory.cs
  src/DataFactory/DataFactoryV2/ParameterSetNames.cs
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2.md
Labels: Cmdlet Review Complete, needs-revision

#8948 Using Pipeline tasks for ADO artifacts
  build/download-build-steps.yml
  build/jobs.yml
  build/publish-artifacts-steps.yml
Labels: needs-review

#8947 Update version for Frontdoor Module
  src/FrontDoor/FrontDoor/Az.FrontDoor.psd1
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Properties/AssemblyInfo.cs
Labels: needs-review

#8951 Fixed example numbering
  src/Accounts/Accounts/help/Connect-AzAccount.md
Labels: Waiting for CI :shipit:

#8949 Update New-AzResourceGroupDeployment.md
  src/Resources/Resources/help/New-AzResourceGroupDeployment.md
Labels: Waiting for CI :shipit:

#8958 Fix help indexing
  tools/CreateMappings_rules.json
Labels: Waiting for CI :shipit:

#8962 [Storage] Add a sub property CanFailover to type PSStorageAccount.GeoReplicationStats
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSGeoReplicationStats.cs
Labels: needs-review

#8966 ADO changes to follow guidelines
  .azure-pipelines/powershell-core.yml
  .azure-pipelines/util/analyze-steps.yml
  .azure-pipelines/util/build-steps.yml
  .azure-pipelines/util/download-build-steps.yml
  .azure-pipelines/util/publish-artifacts-steps.yml
  .azure-pipelines/util/test-steps.yml
  .azure-pipelines/windows-powershell.yml
  Repo.props
  azure-powershell-linux.yml
  azure-powershell-macOS.yml
  azure-powershell-windows.yml
  build.proj
  build/download-build-steps.yml
  build/install-pwsh-steps.yml
  build/jobs.yml
  tools/after.Azure.PowerShell.sln.targets
Labels: Waiting for CI :shipit:

#8941 Update DataClassificationAdapter.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/DataClassification/Services/DataClassificationAdapter.cs
Labels: needs-revision

#8978 Do not break for invalid GuestConfiguration policy definitions
  src/GuestConfiguration/GuestConfiguration/ChangeLog.md
  src/GuestConfiguration/GuestConfiguration/Common/GuestConfigurationCmdletBase.cs
  src/GuestConfiguration/GuestConfiguration/Properties/Resources.Designer.cs
  src/GuestConfiguration/GuestConfiguration/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#8914 Update Websites SDK to v2.1.0. Fix compilation errors and record tests.
  src/Websites/Websites.Test/ScenarioTests/SSLBindingTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestCreateNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestGetNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestGetWebAppCertificate.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestRemoveNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestWebAppSSLBindingPipeSupport.json
  src/Websites/Websites.Test/Websites.Test.csproj
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AppServicePlans/NewAzureAppServicePlan.cs
  src/Websites/Websites/Models.WebApp/PSAppServicePlan.cs
  src/Websites/Websites/Websites.csproj
Labels: needs-review

#8959 Blueprint module updates: remove operation and help message updates
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Cmdlets/RemoveAzureRMBlueprintAssignment.cs
  src/Blueprint/Blueprint/help/New-AzBlueprintAssignment.md
Labels: Waiting for CI :shipit:

#8987 Update README.md - Fixing broken links
  documentation/development-docs/examples/README.md
Labels: needs-review

#8982 Version GuestConfiguration
  src/GuestConfiguration/GuestConfiguration/Az.GuestConfiguration.psd1
  src/GuestConfiguration/GuestConfiguration/ChangeLog.md
  src/GuestConfiguration/GuestConfiguration/Properties/AssemblyInfo.cs
Labels: needs-review

#8995 Reverted Azure Firewall as per discussion
  src/Network/Network/AzureFirewall/ApplicationRuleCollection/NewAzureFirewallApplicationRuleCollectionCommand.cs
  src/Network/Network/AzureFirewall/NetworkRuleCollection/NewAzureFirewallNetworkRuleCollectionCommand.cs
  tools/LocalFeed/Microsoft.Azure.Management.Network.20.0.0-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.Network.20.0.0-preview.snupkg
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#8991 Azure Event Grid: Enhance help text for Endpoint per customer feedback
  src/EventGrid/EventGrid/ChangeLog.md
  src/EventGrid/EventGrid/Utilities/EventGridConstants.cs
  src/EventGrid/EventGrid/help/New-AzEventGridSubscription.md
  src/EventGrid/EventGrid/help/Update-AzEventGridSubscription.md
Labels: Waiting for CI :shipit:

#9000 fix New-AzEventGridSubscription.md and Update-AzEventGridSubscription…
  src/EventGrid/EventGrid/ChangeLog.md
  src/EventGrid/EventGrid/help/New-AzEventGridSubscription.md
  src/EventGrid/EventGrid/help/Update-AzEventGridSubscription.md
Labels: Waiting for CI :shipit:

#8999 Update common version
  tools/Common.Netcore.Dependencies.targets
  tools/RepoTasks/RepoTasks.CmdletsForTest/RepoTasks.CmdletsForTest.csproj
  tools/RepoTasks/RepoTasks.CmdletsForTest/packages.config
  tools/RepoTasks/RepoTasks.RemoteWorker/RepoTasks.RemoteWorker.csproj
  tools/RepoTasks/RepoTasks.RemoteWorker/packages.config
Labels: Waiting for CI :shipit:

#8984 Add SsisProperties if NodeCount not null for managed ir
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/IntegrationRuntimes/SetAzureDataFactoryIntegrationRuntimeCommand.cs
Labels: Waiting for CI :shipit:

#9003 Replace Sql dependency on Monitor SDK with common code
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Sql/Sql.Test/ScenarioTests/AuditingTests.cs
  src/Sql/Sql.Test/ScenarioTests/SqlTestsBase.cs
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AuditingTests/TestAuditingOnDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AuditingTests/TestAuditingOnServer.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AuditingTests/TestNewDatabaseDiagnosticsAreCreatedOnNeed.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AuditingTests/TestNewServerDiagnosticsAreCreatedOnNeed.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/Auditing/AuditingHelpMessages.cs
  src/Sql/Sql/Auditing/DefinitionsCommon.cs
  src/Sql/Sql/Auditing/Model/DatabaseDiagnosticAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Model/DatabaseEventHubAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Model/DatabaseLogAnalyticsAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Model/ServerBlobAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Model/ServerDiagnosticAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Model/ServerEventHubAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Model/ServerLogAnalyticsAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Services/AuditingEndpointsCommunicator.cs
  src/Sql/Sql/Auditing/Services/SqlAuditAdapter.cs
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseBackupLongTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseGeoBackupPolicyModel.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseLongTermRetentionBackupModel.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseLongTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlServerBackupLongTermRetentionVaultModel.cs
  src/Sql/Sql/ManagedDatabase Backup/Model/AzureSqlManagedDatabaseBackupShortTermRetentionPolicyModel.cs
  src/Sql/Sql/ManagedDatabase Backup/Services/AzureSqlManagedDatabaseBackupAdapter.cs
  src/Sql/Sql/Sql.csproj
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#8943 Time zone parameter
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstance.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/help/New-AzSqlInstance.md
Labels: needs-review

#8778 [RecoveryServices.Backup] Updated ScheduleRunDays according to timezone
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SchedulePolicyConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/RecoveryServices.Backup.Helpers.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/PolicyTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#9009 [RecoveryServices] Sql table fixes
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureWorkloadProtectableItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.format.ps1xml
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#9014 Typo fix
  src/Websites/Websites/help/New-AzWebApp.md
Labels: Waiting for CI :shipit:

#8996 Blueprint Upcoming Release: Support secure strings and whoIsBlueprint
  src/Blueprint/Blueprint.Test/Blueprint.Test.csproj
  src/Blueprint/Blueprint.Test/ScenarioTests/TestController.cs
  src/Blueprint/Blueprint/Blueprint.csproj
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Cmdlets/BlueprintCmdletBase.cs
  src/Blueprint/Blueprint/Cmdlets/NewAzureRMBlueprintAssignment.cs
  src/Blueprint/Blueprint/Cmdlets/SetAzureRMBlueprintAssignment.cs
  src/Blueprint/Blueprint/Common/BlueprintClient.cs
  src/Blueprint/Blueprint/Common/BlueprintConstants.cs
  src/Blueprint/Blueprint/Common/IBlueprintClient.cs
  src/Blueprint/Blueprint/Models/PSBlueprintAssignment.cs
  src/Blueprint/Blueprint/Models/PSKeyVaultReference.cs
  src/Blueprint/Blueprint/Models/PSSecretReferenceParameterValue.cs
  src/Blueprint/Blueprint/Models/PSSecretValueReference.cs
  src/Blueprint/Blueprint/Models/PSWhoIsBlueprintContract.cs
  src/Blueprint/Blueprint/Properties/Resources.Designer.cs
  src/Blueprint/Blueprint/Properties/Resources.resx
  src/Blueprint/Blueprint/help/Az.Blueprint.md
  src/Blueprint/Blueprint/help/Get-AzBlueprint.md
  src/Blueprint/Blueprint/help/New-AzBlueprintAssignment.md
  src/Blueprint/Blueprint/help/Remove-AzBlueprintAssignment.md
  src/Blueprint/Blueprint/help/Set-AzBlueprintAssignment.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#8890 [Monitor] New Cmdlets for Genv2 (non classic) metric alerts.
  src/Monitor/Monitor.Test/Alerts/NewAzureRmMetricAlertRuleV2CriteriaTests.cs
  src/Monitor/Monitor.Test/Alerts/NewAzureRmMetricAlertRuleV2DimensionSelectionTests.cs
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.ps1
  src/Monitor/Monitor.Test/ScenarioTests/TestsController.cs
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestAddAzureRmMetricAlertRuleV2.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestGetAzureRmMetricAlertRuleV2.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestRemoveAzureRmMetricAlertRuleV2.json
  src/Monitor/Monitor/Alerts/AddAzureRmMetricAlertRuleV2Command.cs
  src/Monitor/Monitor/Alerts/GetAzureRmMetricAlertRuleV2Command.cs
  src/Monitor/Monitor/Alerts/NewAzureRmMetricAlertRuleV2CriteriaCommand.cs
  src/Monitor/Monitor/Alerts/NewAzureRmMetricAlertRuleV2DimensionSelectionCommand.cs
  src/Monitor/Monitor/Alerts/RemoveAzureRmMetricAlertRuleV2Command.cs
  src/Monitor/Monitor/Az.Monitor.psd1
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/Monitor.csproj
  src/Monitor/Monitor/OutputClasses/PSMetricAlertRuleV2.cs
  src/Monitor/Monitor/OutputClasses/PSMetricAlertRuleV2SingleResource.cs
  src/Monitor/Monitor/OutputClasses/PSMetricCriteria.cs
  src/Monitor/Monitor/OutputClasses/PSMetricDimension.cs
  src/Monitor/Monitor/help/Add-AzMetricAlertRuleV2.md
  src/Monitor/Monitor/help/Get-AzMetricAlertRuleV2.md
  src/Monitor/Monitor/help/New-AzMetricAlertRuleV2Criteria.md
  src/Monitor/Monitor/help/New-AzMetricAlertRuleV2DimensionSelection.md
  src/Monitor/Monitor/help/Remove-AzMetricAlertRuleV2.md
  src/Sql/Sql.Test/Sql.Test.csproj
  tools/StaticAnalysis/Exceptions/Az.Monitor/SignatureIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#9018 Allow tags update via Set operations for VirtualNetworkGateway and Vi…
  ChangeLog.md
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.ps1
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests/TestVirtualNetworkGatewayConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestSetVirtualNetworkGatewayCRUD.json
  src/Network/Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/VirtualNetworkGateway/VirtualNetworkGatewayParameterSets.cs
  src/Network/Network/VirtualNetworkGatewayConnection/UpdateAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/help/Set-AzVirtualNetworkGateway.md
  src/Network/Network/help/Set-AzVirtualNetworkGatewayConnection.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#9006 EventHub: Added NetworkRuleSet cmdlets and help
  src/EventGrid/EventGrid.Test/EventGrid.Test.csproj
  src/EventHub/EventHub.Test/EventHub.Test.csproj
  src/EventHub/EventHub.Test/ScenarioTests/NetworkRuleSet.cs
  src/EventHub/EventHub.Test/ScenarioTests/NetworkRuleSetTests.ps1
  src/EventHub/EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.NetworkRuleSetTests/NetworkRuleSetCRUD.json
  src/EventHub/EventHub/Az.EventHub.psd1
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/AzureEventHubsCmdletBase.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/AddAzureEventHubIPRule.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/AddAzureEventHubVirtualNetworkrule.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/GetAzureEventHubNetworkRuleSet.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/RemoveAzureEventHubIPRule.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/RemoveAzureEventHubNetworkRuleSet.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/RemoveAzureEventHubVirtualNetworkrule.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/SetAzureEventHubNetworkrule.cs
  src/EventHub/EventHub/EventHub.csproj
  src/EventHub/EventHub/EventHub.format.ps1xml
  src/EventHub/EventHub/Models/PSNWRuleSetIpRulesAttributes.cs
  src/EventHub/EventHub/Models/PSNWRuleSetVirtualNetworkRulesAttributes.cs
  src/EventHub/EventHub/Models/PSNetworkRuleIPActionAttributes.cs
  src/EventHub/EventHub/Models/PSNetworkRuleSetAttributes.cs
  src/EventHub/EventHub/Models/PSSubnetAttributes.cs
  src/EventHub/EventHub/Resources.resx
  src/EventHub/EventHub/Utilities/EventHubsClient.cs
  src/EventHub/EventHub/help/Add-AzEventHubIPRule.md
  src/EventHub/EventHub/help/Add-AzEventHubVirtualNetworkRule.md
  src/EventHub/EventHub/help/Az.EventHub.md
  src/EventHub/EventHub/help/Get-AzEventHubNetworkRuleSet.md
  src/EventHub/EventHub/help/Remove-AzEventHubIPRule.md
  src/EventHub/EventHub/help/Remove-AzEventHubNetworkRuleSet.md
  src/EventHub/EventHub/help/Remove-AzEventHubVirtualNetworkRule.md
  src/EventHub/EventHub/help/Set-AzEventHubNetworkRuleSet.md
  src/IotHub/IotHub.Test/IotHub.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  tools/StaticAnalysis/Exceptions/Az.EventHub/SignatureIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#9013 ServiceBus: Added New NetworkRuleSet cmdlets
  src/ServiceBus/ServiceBus.Test/ScenarioTests/NetworkRuleSet.cs
  src/ServiceBus/ServiceBus.Test/ScenarioTests/NetworkRuleSetTests.ps1
  src/ServiceBus/ServiceBus.Test/ServiceBus.Test.csproj
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.NetworkRuleSetTests/NetworkRuleSetCRUD.json
  src/ServiceBus/ServiceBus/Az.ServiceBus.psd1
  src/ServiceBus/ServiceBus/Cmdlets/AzureServiceBusCmdletBase.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/AddAzureServiceBusVirtualNetworkrule.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/AddAzureServicebusIPRule.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/GetAzureServiceBusNetworkRuleSet.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/RemoveAzureEventHubVirtualNetworkrule.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/RemoveAzureServiceBusIPRule.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/RemoveAzureServiceBusNetworkRuleSet.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/SetAzureServiceBusNetworkrule.cs
  src/ServiceBus/ServiceBus/Models/PSNWRuleSetIpRulesAttributes.cs
  src/ServiceBus/ServiceBus/Models/PSNWRuleSetVirtualNetworkRulesAttributes.cs
  src/ServiceBus/ServiceBus/Models/PSNetworkRuleIPActionAttributes.cs
  src/ServiceBus/ServiceBus/Models/PSNetworkRuleSetAttributes.cs
  src/ServiceBus/ServiceBus/Models/PSSubnetAttributes.cs
  src/ServiceBus/ServiceBus/ServiceBus.csproj
  src/ServiceBus/ServiceBus/ServiceBus.format.ps1xml
  src/ServiceBus/ServiceBus/Utilities/ServiceBusClient.cs
  src/ServiceBus/ServiceBus/help/Add-AzServiceBusIPRule.md
  src/ServiceBus/ServiceBus/help/Add-AzServiceBusVirtualNetworkRule.md
  src/ServiceBus/ServiceBus/help/Get-AzServiceBusNetworkRuleSet.md
  src/ServiceBus/ServiceBus/help/Remove-AzServiceBusIPRule.md
  src/ServiceBus/ServiceBus/help/Remove-AzServiceBusNetworkRuleSet.md
  src/ServiceBus/ServiceBus/help/Remove-AzServiceBusVirtualNetworkRule.md
  src/ServiceBus/ServiceBus/help/Set-AzServiceBusNetworkRuleSet.md
  tools/StaticAnalysis/Exceptions/Az.ServiceBus/SignatureIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#9042 Update Az.DataLakeStore.md
  src/DataLakeStore/DataLakeStore/help/Az.DataLakeStore.md
Labels: Waiting for CI :shipit:

#9044 Fixed Cortex test
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexExpressRouteCRUD.json
Labels: needs-review

#9050 Remove travis configuration
  .travis.yml
Labels: needs-review

#9041 Fix minor issues in help for Sql cmdlets
  src/Sql/Sql/help/Get-AzSqlDatabase.md
  src/Sql/Sql/help/New-AzSqlDatabase.md
Labels: Waiting for CI :shipit:

#8945 Update the ADLS sdk to use httpclient, integrate with azure framework
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlMockContext.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlMockDelegatingHandler.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/UrlDecodingRecordMatcher.cs
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsAccount.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsAccountTiers.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsEnumerateAndRestoreDeletedItem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystemPermissions.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFirewallRules.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsTrustedIdProvider.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsVirtualNetworkRules.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestNegativeAdlsAccount.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsAccount.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsAccountTiers.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsEnumerateAndRestoreDeletedItem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystemPermissions.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFirewallRules.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsTrustedIdProvider.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsVirtualNetworkRules.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestNegativeAdlsAccount.json
  src/DataLakeStore/DataLakeStore/DataLakeStore.csproj
  src/DataLakeStore/DataLakeStore/DataPlaneModels/AdlsClientFactory.cs
  src/DataLakeStore/DataLakeStore/Properties/AssemblyInfo.cs
Labels: Waiting for CI :shipit:

#9037 [Storage] Upgrade to SRPSDK 11.0
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageAccountKey.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestGetAzureStorageLocationUsage.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNetworkRule.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountBlockBlobStorage.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountKey.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingGetAccountToGetKey.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingNewUpdateAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestPipingSetStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestRemoveAzureStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureRmStorageAccountKeySource.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccountStorageV2.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetCurrentStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageAccountManagementPolicy.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainer.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerLegalHold.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobServiceProperties.json
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/StorageAccountBaseCmdlet.cs
  src/StorageSync/StorageSync.Test/StorageSync.Test.csproj
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#9062 Version Az.ServiceBus for release
  src/ServiceBus/ServiceBus/Az.ServiceBus.psd1
  src/ServiceBus/ServiceBus/ChangeLog.md
  src/ServiceBus/ServiceBus/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.ServiceBus.dll.json
Labels: needs-review

#9015 PolicyInsights: Support querying policy evaluation details
  src/PolicyInsights/PolicyInsights.Test/PolicyInsights.Test.csproj
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/Common.ps1
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/PolicyEventTests.ps1
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/QueryOptionTests.cs
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/QueryOptionTests.ps1
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyEventTests/ManagementGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyEventTests/PolicySetDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyEventTests/ResourceGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyEventTests/ResourceScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyEventTests/SubscriptionLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyEventTests/SubscriptionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/ManagementGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/PolicyDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/PolicySetDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/ResourceGroupLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/ResourceGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/ResourceScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/SubscriptionLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateSummaryTests/SubscriptionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllManagementGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllPolicyDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllPolicySetDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllResourceGroupLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllResourceGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllResourceScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllSubscriptionLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/AllSubscriptionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestManagementGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestPolicyDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestPolicySetDefinitionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestResourceGroupLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestResourceGroupScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestResourceScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestSubscriptionLevelPolicyAssignmentScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.PolicyStateTests/LatestSubscriptionScope.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithApply.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithExpandPolicyEvaluationDetails.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithFilter.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithFrom.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithOrderBy.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithSelect.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithTo.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.QueryOptionTests/QueryResultsWithTop.json
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/PolicyInsights/PolicyInsights/Cmdlets/GetAzureRmPolicyState.cs
  src/PolicyInsights/PolicyInsights/Common/ParameterHelpMessages.cs
  src/PolicyInsights/PolicyInsights/Models/ExpressionEvaluationDetails.cs
  src/PolicyInsights/PolicyInsights/Models/IfNotExistsEvaluationDetails.cs
  src/PolicyInsights/PolicyInsights/Models/PolicyEvaluationDetails.cs
  src/PolicyInsights/PolicyInsights/Models/PolicyState.cs
  src/PolicyInsights/PolicyInsights/PolicyInsights.csproj
  src/PolicyInsights/PolicyInsights/PolicyInsights.format.ps1xml
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyState.md
Labels: Cmdlet Review Complete, needs-review

#9064 Replaced local SDK by officially published
  src/Compute/Compute.Test/Compute.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network/Network.csproj
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  tools/LocalFeed/Microsoft.Azure.Management.Network.20.0.0-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.Management.Network.20.0.0-preview.snupkg
Labels: needs-review

#8853 SQR (Scheduled Query Rule) PS cmdlets and tests implementation
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/Monitor/Monitor.Test/ScenarioTests/ScheduledQueryRulesTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/ScheduledQueryRulesTests.ps1
  src/Monitor/Monitor.Test/ScenarioTests/TestsController.cs
  src/Monitor/Monitor.Test/ScheduledQueryRules/GetScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/ScheduledQueryRules/NewScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/ScheduledQueryRules/RemoveScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/ScheduledQueryRules/SetScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/ScheduledQueryRules/UpdateScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.ScheduledQueryRulesTests/TestNewGetUpdateSetRemoveScheduledQueryRule.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.ScheduledQueryRulesTests/TestPipingRemoveSetUpdateScheduledQueryRule.json
  src/Monitor/Monitor/Az.Monitor.psd1
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleAlertingAction.cs
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleAznsAction.cs
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleLogMetricTrigger.cs
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleResource.cs
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleSchedule.cs
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleSource.cs
  src/Monitor/Monitor/OutputClasses/PSScheduledQueryRuleTriggerCondition.cs
  src/Monitor/Monitor/ScheduledQueryRules/GetScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleAlertingActionCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleAznsActionGroupCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleLogMetricTriggerCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleScheduleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleSourceCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleTriggerConditionCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/RemoveScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/ScheduledQueryRuleUtilities.cs
  src/Monitor/Monitor/ScheduledQueryRules/SetScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/UpdateScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleAlertingAction.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleAznsAction.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleMetricTrigger.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleResource.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleSchedule.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleSource.cs
  src/Monitor/Monitor/TransitionalClasses/ScheduledQueryRuleTriggerCondition.cs
  src/Monitor/Monitor/help/Az.Monitor.md
  src/Monitor/Monitor/help/Get-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleAlertingAction.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleAznsActionGroup.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleLogMetricTrigger.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleSchedule.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleSource.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleTriggerCondition.md
  src/Monitor/Monitor/help/Remove-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/Set-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/Update-AzScheduledQueryRule.md
  tools/StaticAnalysis/Exceptions/Az.Monitor/SignatureIssues.csv
Labels: Cmdlet Review Complete, Waiting for CI :shipit:

#9065 webapp: Marking Get-AzWebAppMetrics, Get-AzWebAppSlotMetrics and Get-AzAppServicPlanMetrics as deprecated
  src/Websites/Websites.Test/ScenarioTests/AppServicePlanTests.cs
  src/Websites/Websites.Test/ScenarioTests/AppServicePlanTests.ps1
  src/Websites/Websites.Test/ScenarioTests/WebAppSlotTests.cs
  src/Websites/Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.cs
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AppServicePlans/GetAzureAppServicePlanMetrics.cs
  src/Websites/Websites/Cmdlets/DeploymentSlots/GetAzureWebAppSlotMetrics.cs
  src/Websites/Websites/Cmdlets/WebApps/GetAzureWebAppMetrics.cs
  src/Websites/Websites/help/Get-AzAppServicePlanMetric.md
  src/Websites/Websites/help/Get-AzWebAppMetric.md
  src/Websites/Websites/help/Get-AzWebAppSlotMetric.md
Labels: needs-review

#9054 WebSites - Add kind property to PSSite
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Models.WebApp/PSSite.cs
Labels: Waiting for CI :shipit:

#9056 Change enum parameters to string
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorCustomRuleObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorFireWallPolicy.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorFrontendEndpointObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorManagedRuleOverrideObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorMatchConditionObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorRoutingRuleObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/UpdateAzureRmFrontDoorFireWallPolicy.cs
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
  src/FrontDoor/FrontDoor/Models/PSAzureManagedRuleOverride.cs
  src/FrontDoor/FrontDoor/Models/PSCustomRule.cs
  src/FrontDoor/FrontDoor/Models/PSFrontendEndpoint.cs
  src/FrontDoor/FrontDoor/Models/PSMatchCondition.cs
  src/FrontDoor/FrontDoor/Models/PSPolicy.cs
  src/FrontDoor/FrontDoor/Models/PSRoutingRule.cs
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorCustomRuleObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorFireWallPolicy.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorFrontendEndpointObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorManagedRuleOverrideObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorMatchConditionObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorRoutingRuleObject.md
  src/FrontDoor/FrontDoor/help/Update-AzFrontDoorFireWallPolicy.md
  tools/StaticAnalysis/Exceptions/Az.FrontDoor/BreakingChangeIssues.csv
Labels: needs-revision

#8832 Show bing disclaimer only for Bing APIs, Improve error message when a…
  src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.cs
  src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.ps1
  src/CognitiveServices/CognitiveServices.Test/SessionRecords/CognitiveServices.Test.ScenarioTests.CognitiveServicesAccountTests/TestNewAccountWithInvalidName.json
  src/CognitiveServices/CognitiveServices.Test/notice.txt
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/Properties/Resources.resx
  src/CognitiveServices/CognitiveServices/notice.txt
Labels: Waiting for CI :shipit:

#9084 Fix various typos in Relay confirmation messages
  src/Relay/Relay/Resources.resx
Labels: Waiting for CI :shipit:

#9089 Update Changelog for Relay Module
  src/Relay/Relay/ChangeLog.md
Labels: Waiting for CI :shipit:, needs-review

#9076 Updating versions and release notes for the 2019-03-01-hybrid profile
  src/StackAdmin/Azs.AzureBridge.Admin/Module/Azs.AzureBridge.Admin/Azs.Azurebridge.Admin.psd1
  src/StackAdmin/Azs.AzureBridge.Admin/Module/Azs.AzureBridge.Admin/ChangeLog.md
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Azs.Backup.Admin.psd1
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/ChangeLog.md
  src/StackAdmin/Azs.Commerce.Admin/Module/Azs.Commerce.Admin/Azs.Commerce.Admin.psd1
  src/StackAdmin/Azs.Commerce.Admin/Module/Azs.Commerce.Admin/ChangeLog.md
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Azs.Compute.Admin.psd1
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/ChangeLog.md
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/ChangeLog.md
  src/StackAdmin/Azs.Gallery.Admin/Module/Azs.Gallery.Admin/Azs.Gallery.Admin.psd1
  src/StackAdmin/Azs.Gallery.Admin/Module/Azs.Gallery.Admin/ChangeLog.md
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/Azs.Infrastructureinsights.Admin.psd1
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/ChangeLog.md
  src/StackAdmin/Azs.KeyVault.Admin/Module/Azs.KeyVault.Admin/Azs.Keyvault.Admin.psd1
  src/StackAdmin/Azs.KeyVault.Admin/Module/Azs.KeyVault.Admin/ChangeLog.md
  src/StackAdmin/Azs.Network.Admin/Module/Azs.Network.Admin/Azs.Network.Admin.psd1
  src/StackAdmin/Azs.Network.Admin/Module/Azs.Network.Admin/ChangeLog.md
  src/StackAdmin/Azs.Storage.Admin/Module/Azs.Storage.Admin/Azs.Storage.Admin.psd1
  src/StackAdmin/Azs.Storage.Admin/Module/Azs.Storage.Admin/ChangeLog.md
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Azs.Subscriptions.Admin.psd1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/ChangeLog.md
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Azs.Subscriptions.psd1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/ChangeLog.md
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Azs.Update.Admin.psd1
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/ChangeLog.md
  src/StackAdmin/AzureRM/AzureRM.psd1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: Azure Stack

#9093 Brooklyn Feature:- Custom routes set on Gateway.
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/VirtualNetworkGatewayIkeV2Test.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSVirtualNetworkGateway.cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
  src/Network/Network/help/Set-AzVirtualNetworkGateway.md
Labels: Waiting for CI :shipit:

#9080 Updated Az.Monitor.md help file to include new cmdlets
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/help/Az.Monitor.md
Labels: needs-review

#8923 3842798: Automatic DNS Nameserver delegation in parent when child zon…
  src/Dns/Dns.Test/ScenarioTests/ZoneTests.cs
  src/Dns/Dns.Test/ScenarioTests/ZoneTests.ps1
  src/Dns/Dns.Test/SessionRecords/Microsoft.Azure.Commands.ScenarioTest.DnsTests.ZoneTests/TestZoneWithDelegation.json
  src/Dns/Dns/ChangeLog.md
  src/Dns/Dns/Properties/Resources.Designer.cs
  src/Dns/Dns/Properties/Resources.resx
  src/Dns/Dns/Zones/NewAzureDnsZone.cs
  src/Dns/Dns/help/New-AzDnsZone.md
Labels: Cmdlet Review Complete, Sprint Candidate, Waiting for CI :shipit:

#9101 [HotFix] Fixes for NatGateways tests
  src/Network/Network.Test/ScenarioTests/NatGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/NatGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NatGatewayTests/TestNatGatewayCRUDAllParameters.json
Labels: Waiting for CI :shipit:

#9108 Fixes for NatGateways tests - sync from release
  src/Network/Network.Test/ScenarioTests/NatGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/NatGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NatGatewayTests/TestNatGatewayCRUDAllParameters.json
Labels: needs-review

#9083 Adding breaking change warning + Existing Bug fixes
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSFabricDetails.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSRecoveryPlanObjects.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Network/UpdateAzureRmRecoveryServicesAsrNetworkMapping.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryPlan/EditAzureRmRecoveryServicesAsrRecoveryPlan.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryPlan/GetAzureRmRecoveryServicesAsrRecoveryPlan.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryServices.SiteRecovery.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/SetAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/UpdateAzureRmRecoveryServicesAsrProtectionDirection.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
Labels: Sprint Candidate, Waiting for CI :shipit:

#9100 Rename WAF cmdlets from *-AzFrontDoor* to *-AzFrontDoorWaf*
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/FrontDoor/FrontDoor.Test/ScenarioTests/WebApplicationFireWallPolicyTests.ps1
  src/FrontDoor/FrontDoor/Az.FrontDoor.psd1
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/GetAzureRmFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafCustomRuleObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafManagedRuleObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafManagedRuleOverrideObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafMatchConditionObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafRuleGroupOverrideObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/RemoveAzureRmFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/Cmdlets/UpdateAzureRmFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/help/Az.FrontDoor.md
  src/FrontDoor/FrontDoor/help/Get-AzFrontDoorWafPolicy.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafCustomRuleObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafManagedRuleObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafManagedRuleOverrideObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafMatchConditionObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafPolicy.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafRuleGroupOverrideObject.md
  src/FrontDoor/FrontDoor/help/Remove-AzFrontDoorWafPolicy.md
  src/FrontDoor/FrontDoor/help/Update-AzFrontDoorWafPolicy.md
  tools/StaticAnalysis/Exceptions/Az.FrontDoor/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.FrontDoor/SignatureIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#9069 [HDInsight] - Add a cmdlet to update gateway credential
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsightTestBase.cs
  src/HDInsight/HDInsight.Test/UnitTests/HttpTests.cs
  src/HDInsight/HDInsight/Az.HDInsight.psd1
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/ClusterConfigurationUtils.cs
  src/HDInsight/HDInsight/HDInsight.csproj
  src/HDInsight/HDInsight/JobCommands/GetAzureHDInsightJobOutputCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GrantAzureHDInsightHttpServicesAccessCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/RevokeAzureHDInsightHttpServicesAccessCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightGatewayCredentialCommand.cs
  src/HDInsight/HDInsight/Models/Management/AzureHdInsightManagementClient.cs
  src/HDInsight/HDInsight/help/Az.HDInsight.md
  src/HDInsight/HDInsight/help/Grant-AzHDInsightHttpServicesAccess.md
  src/HDInsight/HDInsight/help/Revoke-AzHDInsightHttpServicesAccess.md
  src/HDInsight/HDInsight/help/Set-AzHDInsightGatewayCredential.md
  tools/StaticAnalysis/Exceptions/Az.HDInsight/BreakingChangeIssues.csv
Labels: Cmdlet Review Complete, Sprint Candidate, Waiting for CI :shipit:
