Repository Azure/azure-powershell, pull requests merged in 2019-08, with the labels that each got.

#9703 Add optional ResourceGroupName to LTR cmdlet
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2ResourceGroupBased.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestLongTermRetentionV2ResourceGroupBasedBackup.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/AzureSqlDatabaseLongTermRetentionBackupCmdletBase.cs
  src/Sql/Sql/Database Backup/Cmdlet/GetAzureRmSqlDatabaseLongTermRetentionBackup.cs
  src/Sql/Sql/Database Backup/Cmdlet/RemoveAzureRmSqlDatabaseLongTermRetentionBackup.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseLongTermRetentionBackupModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupCommunicator.cs
  src/Sql/Sql/help/Get-AzSqlDatabaseLongTermRetentionBackup.md
  src/Sql/Sql/help/Remove-AzSqlDatabaseLongTermRetentionBackup.md
Labels: needs-review

#9733 Relay: Fix typo in PSHybridConnectionAttributes model name
  src/Relay/Relay/Cmdlets/HybridConnections/GetAzureRelayHybridConnections.cs
  src/Relay/Relay/Cmdlets/HybridConnections/NewAzureRelayHybridConnections.cs
  src/Relay/Relay/Cmdlets/HybridConnections/SetAzureRelayHybridConnections.cs
  src/Relay/Relay/Models/PSHybridConnectionAttributes.cs
  src/Relay/Relay/Utilities/RelayClient.cs
  src/Relay/Relay/help/Get-AzRelayHybridConnection.md
  src/Relay/Relay/help/New-AzRelayHybridConnection.md
  src/Relay/Relay/help/Set-AzRelayHybridConnection.md
  tools/StaticAnalysis/Exceptions/Az.Relay/BreakingChangeIssues.csv
Labels: needs-revision

#9770 Update Security Module version
  src/Security/Security/Az.Security.psd1
  src/Security/Security/Properties/AssemblyInfo.cs
Labels: Waiting for CI :shipit:

#9683 Add Initialize-AzVirtualNetworkSubnetPolicy command
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestInitializeSubnetPolicy.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/VirtualNetwork/Subnet/InitializeAzureVirtualNetworkSubnetPolicyCommand.cs
  src/Network/Network/help/Initialize-AzVirtualNetworkSubnetPolicy.md
Labels: needs-revision

#9750 Failover database and elastic pool new powershell cmdlets
  src/Sql/Sql.LegacySdk/Sql.LegacySdk.csproj
  src/Sql/Sql.Test/ScenarioTests/FailoverTests.cs
  src/Sql/Sql.Test/ScenarioTests/FailoverTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverDatabasePassThru.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverDatabaseWithDatabasePiping.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverDatabaseWithServerPiping.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverElasticPool.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverElasticPoolPassThru.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverTests/TestFailoverElasticPoolWithPoolPiping.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/InvokeAzureSqlDatabaseFailover.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseCommunicator.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/InvokeAzureSqlElasticPoolFailover.cs
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolCommunicator.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/help/Az.Sql.md
  src/Sql/Sql/help/Invoke-AzSqlDatabaseFailover.md
  src/Sql/Sql/help/Invoke-AzSqlElasticPoolFailover.md
Labels: needs-revision

#9756 Fix for not setting apirevisiondescription
  src/ApiManagement/ApiManagement.ServiceManagement.Test/ScenarioTests/ApiManagementTests.ps1
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiRevisionCrudTest.json
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/AuthorizationServerCrudTest.json
  src/ApiManagement/ApiManagement.ServiceManagement/ApiManagementClient.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Commands/GetAzureApiManagementAuthorizationServer.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Commands/NewAzureApiManagementApiRevision.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Commands/NewAzureApiManagementAuthorizationServer.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Commands/SetAzureApiManagementAuthorizationServer.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Models/PsApiManagementOAuth2AuthorizationServer.cs
  src/ApiManagement/ApiManagement/ChangeLog.md
  src/ApiManagement/ApiManagement/help/Get-AzApiManagementAuthorizationServer.md
  src/ApiManagement/ApiManagement/help/New-AzApiManagementAuthorizationServer.md
  src/ApiManagement/ApiManagement/help/Set-AzApiManagementAuthorizationServer.md
Labels: Waiting for CI :shipit:

#9773 adjust validation to accomodate Ipv6 IP prefix
  src/Network/Network/ChangeLog.md
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/PublicIpPrefix/NewAzurePublicIpPrefixCommand.cs
Labels: Waiting for CI :shipit:

#9803 [Blueprints] Get- cmdlet should work on national clouds
  src/Blueprint/Blueprint/Az.Blueprint.psd1
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Cmdlets/BlueprintDefinition/BlueprintDefinitionCmdletBase.cs
  src/Blueprint/Blueprint/Common/BlueprintConstants.cs
  src/Blueprint/Blueprint/Properties/AssemblyInfo.cs
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Blueprint.dll.json
Labels: Waiting for CI :shipit:

#9757 Add Parameters for Set-AzDataFactoryV2IntegrationRuntime
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.IntegrationRuntimeTests/TestSsisAzureIntegrationRuntime.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/IntegrationRuntimes/SetAzureDataFactoryIntegrationRuntimeCommand.cs
  src/DataFactory/DataFactoryV2/Models/PSManagedIntegrationRuntime.cs
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2IntegrationRuntime.md
Labels: needs-revision

#9812 Minor fixes to PR template and CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: needs-review

#9762 Update to R4.5 RP standard (#24)
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirctory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirectory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumePipelines.json
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/ModelExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/NetAppFiles.csproj
  src/NetAppFiles/NetAppFiles/Pool/NewNetAppFilesPool.cs
  src/NetAppFiles/NetAppFiles/Volume/NewNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesVolume.md
  tools/StaticAnalysis/Exceptions/Az.NetAppFiles/BreakingChangeIssues.csv
Labels: needs-revision

#9734 Updated Get-AzVirtualNetworkSubnetConfig to support searching by subnet resource id
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/VirtualNetwork/Subnet/GetAzureVirtualNetworkSubnetConfigCommand.cs
  src/Network/Network/help/Get-AzVirtualNetworkSubnetConfig.md
Labels: Waiting for CI :shipit:

#9777 Updated volumetype param description
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
  src/Compute/Compute/help/Set-AzVmssDiskEncryptionExtension.md
Labels: Waiting for CI :shipit:

#9826 Update New-AzSqlDatabaseFailoverGroup.md
  src/Sql/Sql/help/New-AzSqlDatabaseFailoverGroup.md
Labels: Waiting for CI :shipit:, needs-review

#9808 Add an example of assigning policy at subscription level to help doc
  src/Resources/Resources/help/New-AzPolicyAssignment.md
Labels: needs-revision

#9836 Update description of Location parameter for AzNetworkServiceTag
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkServiceTag/GetAzureNetworkServiceTagCommand.cs
  src/Network/Network/help/Get-AzNetworkServiceTag.md
Labels: needs-review

#9841 Update ChangeLog.md for the 'Resources' service
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#9811 Update parameters and display field for PrivateIP
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/PrivateLinkServiceTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AvailablePrivateEndpointTypeTests/TestAvailablePrivateEndpointTypeCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PrivateLinkServiceTests/TestPrivateLinkServiceCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkBaseCmdlet.cs
  src/Network/Network/Common/NetworkCloudException.cs
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Generated/Models/PSFrontendIPConfiguration.cs
  src/Network/Network/Models/PSNetworkInterface.cs
  src/Network/Network/Models/PSPrivateEndpoint.cs
  src/Network/Network/Models/PSPrivateEndpointConnection.cs
  src/Network/Network/Models/PSPrivateLinkServiceConnection.cs
  src/Network/Network/Models/PSPrivateLinkServiceIpConfiguration.cs
  src/Network/Network/Models/PSPrivateLinkServiceResourceSet.cs
  src/Network/Network/Models/PSSubnet.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PrivateEndpoint/SetAzurePrivateEndpointCommand.cs
  src/Network/Network/PrivateLinkService/PrivateLinkServiceIpConfiguration/NewAzurePrivateLinkServiceIpConfiguration.cs
  src/Network/Network/PrivateLinkService/SetAzurePrivateLinkServiceCommand.cs
  src/Network/Network/help/New-AzPrivateLinkServiceIpConfig.md
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
Labels: Waiting for CI :shipit:

#9781 [Storage] support StandardBlobtier and Rehydrate priority
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
  src/Storage/Storage.Management/help/Start-AzStorageBlobCopy.md
  src/Storage/Storage.Test/Service/MockStorageBlobManagement.cs
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/StartAzureStorageBlobCopy.cs
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Model/Contract/IStorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/StorageBlobManagement.cs
  src/Storage/Storage/Storage.csproj
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
Labels: Waiting for CI :shipit:

#9825 Deprecating Add-AzServiceFabricApplicationCertificate cmdlet
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/ServiceFabric/ServiceFabric/Commands/AddAzureRmServiceFabricApplicationCertificate.cs
Labels: Waiting for CI :shipit:

#9834 Add note about Microsoft internal access to cmdlet design repo
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: needs-review

#9822 ServiceBus: Fix for issue #9786 : cannot create a rule with Listen only rights
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusPaginationTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusQueueTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusServiceTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusSubscriptionTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusTopicTests.ps1
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueueAuth_CURD.json
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpaceAuth_CURD_Tests.json
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopicAuth_CURD.json
  src/ServiceBus/ServiceBus/ChangeLog.md
  src/ServiceBus/ServiceBus/Cmdlets/AuthorizationRule/NewAzureServiceBusAuthorizationRule.cs
  src/ServiceBus/ServiceBus/Cmdlets/AzureServiceBusCmdletBase.cs
Labels: needs-review

#9857 Updated ADF .NET SDK version to 4.1.2
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-review

#9795 Update Invoke-AzVMRunCommand.md
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/Invoke-AzVMRunCommand.md
Labels: Waiting for CI :shipit:

#9817 Update documentation of old Auditing Cmdlets.
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/help/Get-AzSqlDatabaseAuditing.md
  src/Sql/Sql/help/Get-AzSqlServerAuditing.md
  src/Sql/Sql/help/Set-AzSqlDatabaseAuditing.md
  src/Sql/Sql/help/Set-AzSqlServerAuditing.md
Labels: Waiting for CI :shipit:

#9843 Update New-AzOperationalInsightsWindowsEventDataSource.md
  src/OperationalInsights/OperationalInsights/ChangeLog.md
  src/OperationalInsights/OperationalInsights/help/New-AzOperationalInsightsWindowsEventDataSource.md
Labels: Waiting for CI :shipit:

#9852 Update New-AzOperationalInsightsLinuxSyslogDataSource.md
  src/OperationalInsights/OperationalInsights/ChangeLog.md
  src/OperationalInsights/OperationalInsights/help/New-AzOperationalInsightsLinuxSyslogDataSource.md
Labels: Waiting for CI :shipit:

#9860 Remove non-release directives
  src/Dns/resources/Test-AzDummy.ps1
  src/Network/readme.md
  src/Network/resources/Test-AzDummy.ps1
  src/Network/resources/comparison-directives.yaml
Labels: needs-review

#9793 Add clarification around Set-AzWebApp -AppSettings
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/help/Set-AzWebApp.md
  src/Websites/Websites/help/Set-AzWebAppSlot.md
Labels: Waiting for CI :shipit:

#9870 Fix issue with output for Get-AzAks
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/GetAzureRmAks.cs
Labels: Sprint Candidate

#9846 ServiceBus: Added new command 'Test-AzServiceBusNameAvailability'
  src/ServiceBus/ServiceBus.Test/ScenarioTests/NetworkRuleSetTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusDRConfigurationTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusMigrationConfigurationTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusQueueTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusRuleTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusTopicTests.ps1
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusQueueTests/ServiceBusQueue_CURD.json
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusTopicTests/ServiceBusTopic_CURD.json
  src/ServiceBus/ServiceBus/Az.ServiceBus.psd1
  src/ServiceBus/ServiceBus/ChangeLog.md
  src/ServiceBus/ServiceBus/Cmdlets/AzureServiceBusCmdletBase.cs
  src/ServiceBus/ServiceBus/Cmdlets/CheckNameAvailability/TestAzServiceBusCheckNameAvailability.cs
  src/ServiceBus/ServiceBus/Utilities/ServiceBusClient.cs
  src/ServiceBus/ServiceBus/help/Test-AzServiceBusNameAvailability.md
Labels: Sprint Candidate

#9861 Multi Link support in Virtual WAN
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexDownloadConfig.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Cortex/CortexParameterSetNames.cs
  src/Network/Network/Cortex/VpnConnection/NewAzVpnSiteLinkConnectionCommand.cs
  src/Network/Network/Cortex/VpnConnection/NewAzureRmVpnConnectionCommand.cs
  src/Network/Network/Cortex/VpnConnection/UpdateAzureRmVpnConnectionCommand.cs
  src/Network/Network/Cortex/VpnSite/NewAzVpnSiteLinkCommand.cs
  src/Network/Network/Cortex/VpnSite/NewAzureRmVpnSiteCommand.cs
  src/Network/Network/Cortex/VpnSite/UpdateAzureRmVpnSiteCommand.cs
  src/Network/Network/Models/Cortex/PSVpnConnection.cs
  src/Network/Network/Models/Cortex/PSVpnLinkBgpSettings.cs
  src/Network/Network/Models/Cortex/PSVpnLinkProviderProperties.cs
  src/Network/Network/Models/Cortex/PSVpnSite.cs
  src/Network/Network/Models/Cortex/PSVpnSiteLink.cs
  src/Network/Network/Models/Cortex/PSVpnSiteLinkConnection.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/Get-AzVpnConnection.md
  src/Network/Network/help/Get-AzVpnSite.md
  src/Network/Network/help/New-AzVpnConnection.md
  src/Network/Network/help/New-AzVpnSite.md
  src/Network/Network/help/New-AzVpnSiteLink.md
  src/Network/Network/help/New-AzVpnSiteLinkConnection.md
  src/Network/Network/help/Remove-AzVpnConnection.md
  src/Network/Network/help/Remove-AzVpnSite.md
  src/Network/Network/help/Update-AzVpnConnection.md
  src/Network/Network/help/Update-AzVpnSite.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-review

#9887 fix issue that user MSI doens't work in Azure Function
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication.Test/AuthenticationFactoryTests.cs
  src/Accounts/Authentication/Authentication/ManagedServiceAccessTokenBase.cs
  src/Accounts/Authentication/Authentication/ManagedServiceAppServiceAccessToken.cs
Labels: Waiting for CI :shipit:

#9892 fix userId in system managed identity test cases
  src/Accounts/Authentication.Test/AuthenticationFactoryTests.cs
  src/Accounts/Authentication/Authentication/ManagedServiceAccessTokenBase.cs
Labels: Waiting for CI :shipit:

#9929 Handle ErrorResponseException in NetworkBaseCmdlet
  src/Network/Network.Test/ScenarioTests/NetworkCloudExceptionTests.cs
  src/Network/Network.Test/ScenarioTests/NetworkCloudExceptionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkCloudExceptionTests/TestErrorResponseException.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkBaseCmdlet.cs
  src/Network/Network/Common/NetworkCloudException.cs
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
Labels: Waiting for CI :shipit:

#9883 webapp: Updating the content type header for Zip & war deploy to not use multipart to work with kudulite & classic
  src/Accounts/Accounts/ChangeLog.md
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromWar.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromZip.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
Labels: App Services, Waiting for CI :shipit:
