Repository Azure/azure-powershell, pull requests merged in 2019-12, with the labels that each got.

#10631 out of band release for RecoveryServices
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.SiteRecovery.dll.json
Labels: needs-review

#10629 out of band preview release for blueprint
  src/Blueprint/Blueprint/Az.Blueprint.psd1
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Properties/AssemblyInfo.cs
Labels: needs-review

#10632 out of band preview release for reservations
  src/Reservations/Reservations/Az.Reservations.psd1
  src/Reservations/Reservations/ChangeLog.md
  src/Reservations/Reservations/Properties/AssemblyInfo.cs
Labels: needs-review

#10248 [Monitor] Adding new optional argument to Add-AzureRmDiagnosticSettings to support Log Analytics dedicated workflows as destinations
  src/Monitor/Monitor.Test/Diagnostics/SetDiagnosticSettingCommandTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AzureRmDiagnosticSettingTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AzureRmDiagnosticSettingTests.ps1
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AzureRmDiagnosticSettingTests/TestSetAzureRmDiagnosticSettingEventHub.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AzureRmDiagnosticSettingTests/TestSetAzureRmDiagnosticSettingLogAnalytics.json
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/Diagnostics/SetAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/OutputClasses/PSServiceDiagnosticSettings.cs
  src/Monitor/Monitor/help/Set-AzDiagnosticSetting.md
Labels: needs-revision

#10639 Update Stop-AzVirtualNetworkGatewayPacketCapture.md
  src/Network/Network/help/Stop-AzVirtualNetworkGatewayPacketCapture.md
Labels: needs-review

#10641 Fix 10602: Fix bug with New-AzBatchPool collections
  src/Batch/Batch.Test/ScenarioTests/PoolTests.ps1
  src/Batch/Batch.Test/SessionRecords/Microsoft.Azure.Commands.Batch.Test.ScenarioTests.PoolTests/TestPoolCRUD.json
  src/Batch/Batch/ChangeLog.md
  src/Batch/Batch/Models/BatchClient.Pools.cs
  src/Batch/Batch/Utils/Utils.cs
Labels: needs-review

#10633 Fix issue: Client-side telemetry is not getting correct UserAgent in Az 4.0
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
Labels: needs-review

#10637 [Storage] Fix set container ACL clean stored accesspolicy issue and update change log for SRP SDK upgrade
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerAcl.cs
Labels: needs-review

#10623 Fix mismatch between cmdlets and service in index.json
  tools/CreateMappings_rules.json
Labels: needs-review

#10649 Fix null ref in generated cmdlets when context is not set
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/ContextAdapter.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
Labels: needs-review

#10655 [Storage] Update to SRP SDK 14.2.0, and add Quota parameter alias
  src/EventGrid/EventGrid.Test/EventGrid.Test.csproj
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/File/NewAzureStorageShare.cs
  src/Storage/Storage.Management/File/UpdateAzureStorageShare.cs
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/help/Get-AzRmStorageShare.md
  src/Storage/Storage.Management/help/New-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Set-AzStorageShareQuota.md
  src/Storage/Storage.Management/help/Update-AzRmStorageShare.md
  src/Storage/Storage/File/Cmdlet/SetAzureStorageShareQuota.cs
Labels: needs-review

#10523 Add new dns label
  src/Network/Network/help/Set-AzPublicIpAddress.md
Labels: needs-review

#10659 Changes to support "ReplicasPerMaster" and "Instances"
  src/RedisCache/RedisCache.Test/RedisCache.Test.csproj
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.cs
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestFirewallRule.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestGeoReplication.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestImportExportReboot.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCache.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCacheClustering.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePatchSchedules.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePipeline.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestSetNonExistingRedisCacheTest.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZoneRedundancy.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZones.json
  src/RedisCache/RedisCache/Az.RedisCache.psd1
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheAttributes.cs
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
  src/RedisCache/RedisCache/RedisCache.csproj
  src/RedisCache/RedisCache/RedisCache.format.ps1xml
  src/RedisCache/RedisCache/help/Export-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Get-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Import-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/New-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheScheduleEntry.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCache.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheDiagnostic.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Reset-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCacheDiagnostic.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#10674 AzureFirewall with IpGroups (LATEST)
  src/Network/Network.Test/ScenarioTests/AzureFirewallIpGroupTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallIpGroupTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallIpGroupTests/TestAzureFirewallIpGroup.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallIpGroupTests/TestListAzureFirewallIpGroup.json
  src/Network/Network/AzureFirewall/ApplicationRule/NewAzureFirewallApplicationRuleCommand.cs
  src/Network/Network/AzureFirewall/NatRule/NewAzureFirewallNatRuleCommand.cs
  src/Network/Network/AzureFirewall/NetworkRule/NewAzureFirewallNetworkRuleCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/IpGroup/GetIpGroupCommand.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallApplicationRule.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallNatRule.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallNetworkRule.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/help/New-AzFirewallApplicationRule.md
  src/Network/Network/help/New-AzFirewallNatRule.md
  src/Network/Network/help/New-AzFirewallNetworkRule.md
Labels: needs-review

#10679 Update azure-powershell-developer-guide.md
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: needs-review

#10685 Revert "Changes to support "ReplicasPerMaster" and "Instances""
  src/RedisCache/RedisCache.Test/RedisCache.Test.csproj
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.cs
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestFirewallRule.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestGeoReplication.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestImportExportReboot.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCache.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCacheClustering.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePatchSchedules.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePipeline.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestSetNonExistingRedisCacheTest.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZoneRedundancy.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZones.json
  src/RedisCache/RedisCache/Az.RedisCache.psd1
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheAttributes.cs
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
  src/RedisCache/RedisCache/RedisCache.csproj
  src/RedisCache/RedisCache/RedisCache.format.ps1xml
  src/RedisCache/RedisCache/help/Export-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Get-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Import-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/New-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheScheduleEntry.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCache.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheDiagnostic.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Reset-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCacheDiagnostic.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#10682 Added Connected Machine cmdlets
  src/ConnectedMachine/Az.ConnectedMachine.format.ps1xml
  src/ConnectedMachine/custom/readme.md
  src/ConnectedMachine/docs/readme.md
  src/ConnectedMachine/examples/latest-2019-08-02/Get-AzConnectedMachine.md
  src/ConnectedMachine/examples/latest-2019-08-02/Remove-AzConnectedMachine.md
  src/ConnectedMachine/examples/readme.md
  src/ConnectedMachine/how-to.md
  src/ConnectedMachine/license.txt
  src/ConnectedMachine/readme.md
  src/ConnectedMachine/resources/readme.md
  src/ConnectedMachine/test/Get-AzConnectedMachine.Recording.json
  src/ConnectedMachine/test/Get-AzConnectedMachine.Tests.ps1
  src/ConnectedMachine/test/Remove-AzConnectedMachine.Recording.json
  src/ConnectedMachine/test/Remove-AzConnectedMachine.Tests.ps1
  src/ConnectedMachine/test/readme.md
Labels: needs-revision

#10697 Type fix in an example in New-AzEventHub.md
  src/EventHub/EventHub/help/New-AzEventHub.md
Labels: needs-review

#10694 Revert "Revert "Changes to support "ReplicasPerMaster" and "Instances"""
  src/RedisCache/RedisCache.Test/RedisCache.Test.csproj
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.cs
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestFirewallRule.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestGeoReplication.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestImportExportReboot.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCache.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCacheClustering.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePatchSchedules.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePipeline.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestSetNonExistingRedisCacheTest.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZoneRedundancy.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZones.json
  src/RedisCache/RedisCache/Az.RedisCache.psd1
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheAttributes.cs
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
  src/RedisCache/RedisCache/RedisCache.csproj
  src/RedisCache/RedisCache/RedisCache.format.ps1xml
  src/RedisCache/RedisCache/help/Export-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Get-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Import-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/New-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheScheduleEntry.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCache.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheDiagnostic.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Reset-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCacheDiagnostic.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#10707 upgrade version for Az.Subscription to 0.7.2
  src/Subscription/Subscription/Az.Subscription.psd1
  src/Subscription/Subscription/ChangeLog.md
  src/Subscription/Subscription/Properties/AssemblyInfo.cs
Labels: needs-review

#10709 Upgrade reference to azure powershell common
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:, needs-review

#10716 Merge last out of band release for reservations
  src/Reservations/Reservations/Az.Reservations.psd1
  src/Reservations/Reservations/ChangeLog.md
  src/Reservations/Reservations/Properties/AssemblyInfo.cs
Labels: needs-review

#10717 Merge release 2019 11 29 blueprint
  src/Blueprint/Blueprint/Az.Blueprint.psd1
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Properties/AssemblyInfo.cs
Labels: needs-review

#10715 update version and release note for Az.DeviceProvisioningServices
  src/DeviceProvisioningServices/DeviceProvisioningServices/Az.DeviceProvisioningServices.psd1
  src/DeviceProvisioningServices/DeviceProvisioningServices/ChangeLog.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/Properties/AssemblyInfo.cs
Labels: needs-review

#10718 Merge 2019 11 29 recovery services
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
Labels: needs-review

#10712 Fix the bug of Get-AzResource with api-version
  src/Resources/ResourceManager/Components/ApiVersionHelper.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/ResourceManager/Utilities/ResourceTypeUtility.cs
  src/Resources/Resources.Test/UnitTests/Utilities/TestResourceTypeUtility.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#10728 Fix Invoke-AzHDInsightHiveJob.md error
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/help/Invoke-AzHDInsightHiveJob.md
Labels: Waiting for CI :shipit:

#10741 [Compute] Fix Set-AzVMCustomScriptExtension
  VirtualMachineCustomScriptExtensionManagedDisk.json
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineCustomScriptExtensionManagedDisk.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/CustomScript/SetAzureVMCustomScriptExtensionCommand.cs
Labels: needs-revision

#10743 add sub id to client telemetry for az 4.0 preview
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
Labels: needs-review

#10742 update Aks customization for service telemetry
  src/Aks/custom/GetAzAks.cs
  src/Aks/custom/GetAzAks_List.cs
  src/Aks/custom/ImportAzAksCredential.cs
  src/Aks/custom/NewAzAksBase.cs
  src/Aks/custom/RemoveAzAks.cs
  src/Aks/custom/StartAzAksDashboard.cs
Labels: needs-review

#10761 Correct parameter name in example 6
  src/ContainerInstance/ContainerInstance/ChangeLog.md
  src/ContainerInstance/ContainerInstance/help/New-AzContainerGroup.md
Labels: Waiting for CI :shipit:

#10600 Add support for vulnerability assessment operations on system databases in azure cmdlets
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/SqlVulnerabilityAssessmentAtpCmdletBase.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ClearSqlVulnerabilityAssessmentRuleBaselineBase.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ManagedDatabase/ClearSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ManagedDatabase/GetAzureSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ManagedDatabase/SetAzureSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/SetAzureSqlVulnerabilityAssessmentRuleBaselineBase.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentScan/ManagedDatabase/ConvertAzureSqlManagedDatabaseVulnerabilityAssessmentScan.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentScan/ManagedDatabase/GetAzureSqlManagedDatabaseVulnerabilityAssessmentScanRecord.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentScan/ManagedDatabase/StartAzureSqlManagedDatabaseVulnerabilityAssessmentScan.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/Database/ClearSqlDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/Database/GetAzureSqlDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/Database/UpdateAzureSqlDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/ManagedDatabase/ClearSqlManagedDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/ManagedDatabase/GetAzureSqlManagedDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/ManagedDatabase/UpdateAzureSqlManagedDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Services/SqlVulnerabilityAssessmentRuleBaselineAdapter.cs
  src/Sql/Sql/help/Clear-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline.md
  src/Sql/Sql/help/Get-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline.md
  src/Sql/Sql/help/Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline.md
Labels: needs-revision

#10770 Add license header for auto generated code
  src/readme.azure.md
Labels: needs-review

#10734 Display error response detail in New-AzCdnEndpoint cmdlet
  src/Cdn/Cdn/ChangeLog.md
  src/Cdn/Cdn/Endpoint/NewAzureRmCdnEndpoint.cs
Labels: Waiting for CI :shipit:

#10747 Update publish process for psd1 signing
  tools/ExpandModules.ps1
  tools/PackModules.ps1
Labels: needs-review

#10772 Azure Site Recovery: Cmk powershell support for azure to azure provider
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery/DiskReplicationConfiguration/AzureRmAsrAzureToAzureDiskReplicationConfig.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryServices.SiteRecovery.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/AddAzureRmRecoveryServicesAsrReplicationProtectedItemDisk.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrAzureToAzureDiskReplicationConfig.md
Labels: needs-review

#10774 [Storage] Fix Output format of AzureDataLakeGen2Item.Permissions
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Storage.format.ps1xml
Labels: needs-review

#10693 Fixed Broken Link in Get-AzDtlAllowedVMSizesPolicy.md
  src/DevTestLabs/DevTestLabs/help/Get-AzDtlAllowedVMSizesPolicy.md
Labels: Waiting for CI :shipit:

#10775 [Storage] Add warning message for DefaultAction value change
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/UpdateAzureStorageAccountNetworkRuleSet.cs
Labels: needs-revision

#10563 Update version of Microsoft.Azure.Management.Sql to 1.37.0-preview in Sql and Sql.Test solution.
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network/Network.csproj
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AdvancedDataSecurityManagedInstanceTests/AdvancedDataSecurityPolicyTest.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestBasicDataClassificationOnSqlManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseBackupTests/ManagedDatabaseShortTermRetentionPolicy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseBackupTests/ManagedDeletedDatabaseShortTermRetentionPolicy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestCreateManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestGeoRestoreManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestGetManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestRemoveManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestRestoreDeletedManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestRestoreManagedDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentMiTests/VulnerabilityAssessmentManagedDatabaseBaselineTest.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentMiTests/VulnerabilityAssessmentManagedDatabaseScanConvertTest.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentMiTests/VulnerabilityAssessmentManagedDatabaseScanRecordGetListTest.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentMiTests/VulnerabilityAssessmentManagedDatabaseSettingsTest.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentMiTests/VulnerabilityAssessmentManagedDatabaseWithSettingsNotDefinedTest.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentMiTests/VulnerabilityAssessmentManagedInstanceSettingsTest.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/InstanceActiveDirectoryAdministrator/Services/AzureSqlInstanceActiveDirectoryAdministratorCommunicator.cs
  src/Sql/Sql/Sql.csproj
  tools/SecurityTools/CredScanSuppressions.json
Labels: Waiting for CI :shipit:, needs-revision

#10740 Add public IP support for Azure-SSIS Integration Runtime
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.IntegrationRuntimeTests/TestSsisAzureIntegrationRuntime.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
  src/DataFactory/DataFactoryV2/IntegrationRuntimes/SetAzureDataFactoryIntegrationRuntimeCommand.cs
  src/DataFactory/DataFactoryV2/Models/PSManagedIntegrationRuntime.cs
  src/DataFactory/DataFactoryV2/Properties/Resources.Designer.cs
  src/DataFactory/DataFactoryV2/Properties/Resources.resx
  src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2IntegrationRuntime.md
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2IntegrationRuntime.md
  src/DataFactory/DataFactoryV2/help/Start-AzDataFactoryV2IntegrationRuntime.md
Labels: Waiting for CI :shipit:

#10699 updated the New/Set-AzEnvironment cmdlets to contain azure attestation endpoint
  src/Accounts/Accounts.Test/EnvironmentCmdletTests.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Environment/AddAzureRMEnvironment.cs
  src/Accounts/Accounts/Environment/SetAzureRMEnvironment.cs
  src/Accounts/Accounts/help/Add-AzEnvironment.md
  src/Accounts/Accounts/help/Set-AzEnvironment.md
  src/Accounts/Authentication.ResourceManager/Models/PSAzureEnvironment.cs
  src/Accounts/Authentication.Test/TypeConversionTests.cs
Labels: Waiting for CI :shipit:

#10691 Add missing fields of powershell
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.IntegrationRuntimeTests/TestSelfHostedIntegrationRuntime.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Models/PSSelfHostedIntegrationRuntimeStatus.cs
  src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2IntegrationRuntime.md
Labels: needs-revision

#10787 Remove deprecated MachineLearningCompute cmdlets
  src/MachineLearning/MachineLearning/Az.MachineLearning.psd1
  src/MachineLearning/MachineLearning/ChangeLog.md
  src/MachineLearning/MachineLearning/help/Az.MachineLearning.md
  src/MachineLearning/MachineLearning/help/Get-AzMlOpCluster.md
  src/MachineLearning/MachineLearning/help/Get-AzMlOpClusterKey.md
  src/MachineLearning/MachineLearning/help/New-AzMlOpCluster.md
  src/MachineLearning/MachineLearning/help/Remove-AzMlOpCluster.md
  src/MachineLearning/MachineLearning/help/Set-AzMlOpCluster.md
  src/MachineLearning/MachineLearning/help/Test-AzMlOpClusterSystemServicesUpdateAvailability.md
  src/MachineLearning/MachineLearning/help/Update-AzMlOpClusterSystemService.md
  src/MachineLearning/MachineLearningCompute.Test/ScenarioTests/MLCTests.cs
Labels: Sprint Candidate, needs-review

#10791 [Strorage] Revert preview feature which should not in master branch
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestFailoverAzureStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewSetAzStorageAccountFileAADDS.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewSetAzureStorageAccountGZRS.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewSetAzureStorageAccountRAGZRS.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobServiceProperties.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/Blob/UpdateAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSAzureFilesIdentityBasedAuthentication.cs
  src/Storage/Storage.Management/Models/PSBlobServiceProperties.cs
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageAccountKey.cs
  src/Storage/Storage.Management/StorageAccount/InvokeAzureStorageAccountFailover.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccountKey.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2ChildItem.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2ItemContent.md
  src/Storage/Storage.Management/help/Get-AzStorageAccountKey.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobServiceProperty.md
  src/Storage/Storage.Management/help/Invoke-AzStorageAccountFailover.md
  src/Storage/Storage.Management/help/Move-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/New-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/New-AzDataLakeGen2ItemACLObject.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageAccountKey.md
  src/Storage/Storage.Management/help/Remove-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Update-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Update-AzStorageBlobServiceProperty.md
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Common/AzureDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2FileContent.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/MoveAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/NewAzDataLakeGen2ACLObject.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/NewAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RemoveAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/GEN1_GEN2_MAPPING.md
  src/Storage/Storage/Model/ResourceModel/PSPathAccessControl.cs
  src/Storage/Storage/Storage.csproj
  src/Storage/Storage/Storage.format.ps1xml
  src/Storage/Storage/Storage.generated.format.ps1xml
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
  tools/LocalFeed/Microsoft.Azure.Storage.Blob.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/LocalFeed/Microsoft.Azure.Storage.Common.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/LocalFeed/Microsoft.Azure.Storage.File.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/LocalFeed/Microsoft.Azure.Storage.Queue.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: needs-review

#10730 Update Completer for License type to have new value "DR"
  src/SqlVirtualMachine/SqlVirtualMachine.sln
  src/SqlVirtualMachine/SqlVirtualMachine/ChangeLog.md
  src/SqlVirtualMachine/SqlVirtualMachine/Common/ArgumentCompleters/LicenseTypeCompleter.cs
Labels: needs-revision

#10806 [Storage] revert other changes in storage
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/StorageAccountBaseCmdlet.cs
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainer.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageContainer.cs
Labels: Sprint Candidate

#10807 Resolved break changes in DataBoxEdge
  src/DataBoxEdge/DataBoxEdge/Common/Cmdlets/Orders/DataBoxEdgeOrderRemoveCmdlet.cs
  src/DataBoxEdge/DataBoxEdge/Common/Cmdlets/Roles/DataBoxEdgeRoleSetCmdlet.cs
Labels: Sprint Candidate, needs-review

#10808 Suppressed changes in Az.Compute
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Sprint Candidate, needs-review

#10744 Typo?
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Remove-AzTag.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#10810 The cmdlet Get-AzStorageContainer should support the alias Get-AzStor…
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainer.cs
Labels: Waiting for CI :shipit:

#10801 Minor Fixes for Sql InstanceFailoverGroup Cmdlets (#10516)
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Instance Failover Group/Cmdlet/NewAzureSqlInstanceFailoverGroup.cs
  src/Sql/Sql/Instance Failover Group/Cmdlet/SetAzureSqlInstanceFailoverGroup.cs
  src/Sql/Sql/help/Set-AzSqlDatabaseInstanceFailoverGroup.md
Labels: Sprint Candidate
