Repository Azure/azure-powershell, pull requests merged in 2019-11, with the labels that each got.

#10153 Add readReplicaCount AzSqlDatabase property
  src/Sql/Sql.Test/ScenarioTests/ReadScaleCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ReadScaleCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ReadScaleCrudTests/TestDatabaseReadReplicaCount.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ReadScaleCrudTests/TestDatabaseReadScaleCreateUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ReadScaleCrudTests/TestDatabaseReadScaleGet.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/Instance Failover Group/Cmdlet/RemoveAzureSqlInstanceFailoverGroup.cs
  src/Sql/Sql/help/New-AzSqlDatabase.md
  src/Sql/Sql/help/Remove-AzSqlDatabaseInstanceFailoverGroup.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
Labels: needs-review

#10452 [Sql] Fix merging issue in ChangeLog
  src/Sql/Sql/ChangeLog.md
Labels: needs-review

#10424 [Storage] Support datalake (adls) gen2
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2ChildItem.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2ItemContent.md
  src/Storage/Storage.Management/help/Move-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/New-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/New-AzDataLakeGen2ItemACLObject.md
  src/Storage/Storage.Management/help/Remove-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Update-AzDataLakeGen2Item.md
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Common/AzureDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2FileContent.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/MoveAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/NewAzDataLakeGen2ACLObject.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/NewAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RemoveAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2Item.cs
  src/Storage/Storage/Model/ResourceModel/PSPathAccessControl.cs
  src/Storage/Storage/Storage.csproj
  src/Storage/Storage/Storage.format.ps1xml
  src/Storage/Storage/Storage.generated.format.ps1xml
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
  tools/LocalFeed/Microsoft.Azure.Storage.Blob.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/LocalFeed/Microsoft.Azure.Storage.Common.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/LocalFeed/Microsoft.Azure.Storage.File.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/LocalFeed/Microsoft.Azure.Storage.Queue.11.2.0-Release-jenkins-dotnet-nuget-231.nupkg
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: needs-revision

#10459 add missing yamldotnet
  src/Aks/readme.md
Labels: needs-review

#10454 Add component detection task
  .azure-pipelines/windows-powershell.yml
Labels: needs-review

#10442 add pr knowledge share doc
  documentation/internal/pull-request-review-knowledge-share.md
Labels: needs-review

#10448 Add EnabledState parameter to Custom Rule objects and pass it through
  src/FrontDoor/FrontDoor.Test/ScenarioTests/WebApplicationFireWallPolicyTests.ps1
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestPolicyCrud.json
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewAzureRmFrontDoorWafCustomRuleObject.cs
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
  src/FrontDoor/FrontDoor/Models/PSCustomRule.cs
Labels: needs-review

#10402 Fix a small bug.
  src/Sql/Sql/Auditing/Services/SqlAuditAdapter.cs
  src/Sql/Sql/ChangeLog.md
Labels: needs-revision

#10399 Fix Set-AzSqlDatabase no zone resilience set
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
Labels: needs-review

#10450 Delete Microsoft.Azure.PowerShell.Cmdlets.ManagedNetwork.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.ManagedNetwork.dll.json
Labels: needs-review

#10461 Az.3.0.0 migration guide
  documentation/migration-guides/Az.3.0.0-migration-guide.md
Labels: needs-review

#10469 [RecoveryServices] Fix issues in Get-AzRecoveryServicesBackupContainer Cmdlet
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Utils.cs
Labels: needs-review

#10352 Generation: Comments from Chris Lewis regarding new Etag usage in Powershell Update-AzXXX commands
  documentation/RFC/RFC0005-ETags.md
Labels: Az 4.x Preview

#10473 [Storage] Add DatalakeGen2 FileSystem alias to Container cmdlets
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageContainer.cs
Labels: needs-review

#10069 Added -Include parameter with example
  src/ResourceGraph/ResourceGraph/ChangeLog.md
  src/ResourceGraph/ResourceGraph/help/Search-AzGraph.md
Labels: Resource Graph, Waiting for CI :shipit:

#10449 [AzureStack]PowerShell update for Fabriclocation Module
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin.csproj
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/ChangeLog.md
  src/StackAdmin/Azs.Fabric.Admin/Module/packages.config
  src/StackAdmin/Azs.Fabric.Admin/Tests/Azs.Fabric.Admin.Tests.csproj
  src/StackAdmin/Azs.Fabric.Admin/Tests/packages.config
Labels: Azure Stack, needs-revision

#10312 [Azure Stack] Add DRP Admin module
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin.csproj
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Azs.Deployment.Admin.psd1
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Azs.Deployment.Admin.psm1
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/ChangeLog.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsActionPlan.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsActionPlanAttempt.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsActionPlanOperation.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsFileContainer.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsProductDeployment.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsProductPackage.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Get-AzsProductSecret.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Invoke-AzsProductBootstrapAction.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Invoke-AzsProductDeployAction.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Invoke-AzsProductExecuteRunnerAction.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Invoke-AzsProductRemoveAction.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Invoke-AzsProductRotateSecretsAction.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Lock-AzsProductSubscription.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/New-AzsFileContainer.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/New-AzsProductPackage.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Remove-AzsFileContainer.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Remove-AzsProductPackage.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Set-AzsProductSecret.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/Help/Unlock-AzsProductSubscription.md
  src/StackAdmin/Azs.Deployment.Admin/Module/Azs.Deployment.Admin/en-US/Azs.Deployment.Admin-help.xml
  src/StackAdmin/Azs.Deployment.Admin/Module/MSSharedLibKey.snk
  src/StackAdmin/AzureStack/AzureStack.psd1
  src/StackAdmin/Stack.sln
Labels: Waiting for CI :shipit:

#10474 Update documentation of Get-AzDataLakeStoreDeletedItem and Restore-AzDataLakeStoreDeletedItem
  src/DataLakeStore/DataLakeStore/ChangeLog.md
  src/DataLakeStore/DataLakeStore/help/Get-AzDataLakeStoreDeletedItem.md
  src/DataLakeStore/DataLakeStore/help/Restore-AzDataLakeStoreDeletedItem.md
Labels: needs-review

#10445 Update to R5 RP 2019-07-01 API
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/AccountTests.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/Common.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/SnapshotTests.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirectory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumePipelines.json
  src/NetAppFiles/NetAppFiles/Account/UpdateNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/ModelExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesExportPolicyRule.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesSnapshot.cs
  src/NetAppFiles/NetAppFiles/NetAppFiles.csproj
  src/NetAppFiles/NetAppFiles/Volume/NewNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/help/Get-AzNetAppFilesSnapshot.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesSnapshot.md
  tools/StaticAnalysis/Exceptions/Az.NetAppFiles/BreakingChangeIssues.csv
Labels: needs-revision

#10440 Add files needed for ADO security tools pipeline
  tools/SecurityTools/CredScanSuppressions.json
  tools/SecurityTools/PoliCheckFileExtensions.xml
  tools/SecurityTools/RunBinSkim.ps1
Labels: needs-revision

#10488 fix Nullreferenceexception in remove azure ad service principal#10168
  src/Resources/Resources.Test/ScenarioTests/ActiveDirectoryTests.cs
  src/Resources/Resources.Test/ScenarioTests/ActiveDirectoryTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestRemoveServicePrincipalWithNameNotFound.json
  src/Resources/Resources/ActiveDirectory/Cmdlets/RemoveAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#10489 Fix filter data help
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/Start-AzVirtualNetworkGatewayConnectionPacketCapture.md
  src/Network/Network/help/Start-AzVirtualnetworkGatewayPacketCapture.md
Labels: needs-review

#10494 [Datafactory] Use latest sdk 4.4.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-review

#10438 Adding disktype parameter For V2A EnableDr + fixing recoveryplan edit…
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryPlan/GetAzureRmRecoveryServicesAsrRecoveryPlan.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Utilities/Utilities.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Backup-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJob.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJobDetail.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrNetworkMapping.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrPolicy.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultContext.md
  src/RecoveryServices/RecoveryServices/help/Undo-AzRecoveryServicesBackupItemDeletion.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesAsrPolicy.md
  src/RecoveryServices/RecoveryServices/help/Wait-AzRecoveryServicesBackupJob.md
Labels: needs-revision

#10376 Upgrade PrivateDns .net sdk to 1.0.0
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/PrivateDns/PrivateDns/ChangeLog.md
  src/PrivateDns/PrivateDns/PrivateDns.csproj
Labels: needs-revision

#10492 Fix bug in New-AZADServicePrincipal#9478
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#10498 [ManagedNetwork]Fix Leading Slash in test cases
  src/ManagedNetwork/ManagedNetwork.Test/ScenarioTests/ManagedNetworkGroupTests.ps1
  src/ManagedNetwork/ManagedNetwork.Test/ScenarioTests/ManagedNetworkPolicyTests.ps1
  src/ManagedNetwork/ManagedNetwork.Test/ScenarioTests/ManagedNetworkTests.ps1
  src/ManagedNetwork/ManagedNetwork.Test/SessionRecords/Microsoft.Azure.Commands.ManagedNetwork.Test.ScenarioTests.ScenarioTests.ManagedNetworkGroupTests/TestGetSetManagedNetworkGroup.json
  src/ManagedNetwork/ManagedNetwork.Test/SessionRecords/Microsoft.Azure.Commands.ManagedNetwork.Test.ScenarioTests.ScenarioTests.ManagedNetworkPolicyTests/TestGetSetManagedNetworkPolicy.json
  src/ManagedNetwork/ManagedNetwork.Test/SessionRecords/Microsoft.Azure.Commands.ManagedNetwork.Test.ScenarioTests.ScenarioTests.ManagedNetworkTests/TestGetSetManagedNetwork.json
  src/ManagedNetwork/ManagedNetwork/ChangeLog.md
Labels: needs-revision

#10471 Fix for redis issue #9510
  src/RedisCache/RedisCache.Test/ScenarioTests/Utilitytests.cs
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Commands/SetAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/SizeConverter.cs
  src/RedisCache/RedisCache/Properties/Resources.Designer.cs
  src/RedisCache/RedisCache/Properties/Resources.resx
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
Labels: needs-review

#10510 Support MinimumTlsVersion property for Redis Cache cmdlets
  src/RedisCache/RedisCache.Test/RedisCache.Test.csproj
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestFirewallRule.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestGeoReplication.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestImportExportReboot.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCache.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCacheClustering.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePatchSchedules.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePipeline.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestSetNonExistingRedisCacheTest.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZones.json
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Commands/SetAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheAttributes.cs
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
  src/RedisCache/RedisCache/RedisCache.csproj
  src/RedisCache/RedisCache/RedisCache.format.ps1xml
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCache.md
Labels: Waiting for CI :shipit:

#10541 [Compute] November release
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.cs
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.ps1
  src/Compute/Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/StrategiesVirtualMachineTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetProfileTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestGalleryCrossTenant.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestGalleryImageVersionDiskImage.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests/TestSimpleGalleryCrossTenant.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetAutoRepair.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineReapply.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/GalleryImage/GalleryImageCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssDataDiskCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Manual/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/ImageEx.cs
  src/Compute/Compute/VirtualMachine/Action/SetAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/Add-AzVmssDataDisk.md
  src/Compute/Compute/help/New-AzGalleryImageDefinition.md
  src/Compute/Compute/help/New-AzGalleryImageVersion.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Set-AzVM.md
  src/Compute/Compute/help/Update-AzGalleryImageDefinition.md
  src/Compute/Compute/help/Update-AzGalleryImageVersion.md
  src/Compute/Compute/help/Update-AzVmss.md
Labels: needs-review

#10366 Fix enabling CDN custom domain HTTPS for Microsoft, Akamai CDN
  src/Cdn/Cdn.Test/ScenarioTests/CustomDomainTests.cs
  src/Cdn/Cdn.Test/ScenarioTests/CustomDomainTests.ps1
  src/Cdn/Cdn.Test/SessionRecords/Microsoft.Azure.Commands.Cdn.Test.ScenarioTests.ScenarioTest.CustomDomainTests/TestAkamaiCustomDomainHttpsWithRunningEndpoint.json
  src/Cdn/Cdn.Test/SessionRecords/Microsoft.Azure.Commands.Cdn.Test.ScenarioTests.ScenarioTest.CustomDomainTests/TestCustomDomainEnableDisableWithRunningEndpoint.json
  src/Cdn/Cdn.Test/SessionRecords/Microsoft.Azure.Commands.Cdn.Test.ScenarioTests.ScenarioTest.CustomDomainTests/TestMicrosoftCustomDomainHttpsWithRunningEndpoint.json
  src/Cdn/Cdn.Test/SessionRecords/Microsoft.Azure.Commands.Cdn.Test.ScenarioTests.ScenarioTest.CustomDomainTests/TestVerizonCustomDomainHttpsWithRunningEndpoint.json
  src/Cdn/Cdn/ChangeLog.md
  src/Cdn/Cdn/CustomDomain/EnableAzureRmCdnCustomDomainHttps.cs
Labels: needs-review

#10439 Add IsCloudRecoveryReady in existing BackupInfo
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin.csproj
  src/StackAdmin/Azs.Backup.Admin/Module/packages.config
  src/StackAdmin/Azs.Backup.Admin/Tests/Azs.Backup.Admin.Tests.csproj
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestCreateBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestGetBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestListBackups.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestRestoreBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/packages.config
Labels: Waiting for CI :shipit:

#10313 Adding Microsoft.Maintenance RP PS cmdlets
  src/Maintenance/Maintenance.Test/Maintenance.Test.csproj
  src/Maintenance/Maintenance.Test/Properties/AssemblyInfo.cs
  src/Maintenance/Maintenance.Test/ScenarioTests/Common.ps1
  src/Maintenance/Maintenance.Test/ScenarioTests/MaintenanceTests.cs
  src/Maintenance/Maintenance.Test/ScenarioTests/MaintenanceTests.ps1
  src/Maintenance/Maintenance.Test/ScenarioTests/TestController.cs
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestConfigurationAssignment.json
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestMaintenanceConfiguration.json
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestMaintenanceUpdate.json
  src/Maintenance/Maintenance.sln
  src/Maintenance/Maintenance/ApplyUpdate/ApplyUpdateCreateOrUpdateMethod.cs
  src/Maintenance/Maintenance/ApplyUpdate/ApplyUpdateGetMethod.cs
  src/Maintenance/Maintenance/Az.Maintenance.psd1
  src/Maintenance/Maintenance/ChangeLog.md
  src/Maintenance/Maintenance/Common/HashTableExtensions.cs
  src/Maintenance/Maintenance/Common/MaintenanceClient.cs
  src/Maintenance/Maintenance/Common/MaintenanceClientBaseCmdlet.cs
  src/Maintenance/Maintenance/Common/MaintenanceCloudException.cs
  src/Maintenance/Maintenance/ConfigurationAssignment/ConfigurationAssignmentCreateOrUpdateMethod.cs
  src/Maintenance/Maintenance/ConfigurationAssignment/ConfigurationAssignmentDeleteMethod.cs
  src/Maintenance/Maintenance/ConfigurationAssignment/ConfigurationAssignmentGetMethod.cs
  src/Maintenance/Maintenance/Maintenance.csproj
  src/Maintenance/Maintenance/Maintenance.format.ps1xml
  src/Maintenance/Maintenance/MaintenanceAutomationBaseCmdlet.cs
  src/Maintenance/Maintenance/MaintenanceConfiguration/MaintenanceConfigurationCreateOrUpdateMethod.cs
  src/Maintenance/Maintenance/MaintenanceConfiguration/MaintenanceConfigurationDeleteMethod.cs
  src/Maintenance/Maintenance/MaintenanceConfiguration/MaintenanceConfigurationGetMethod.cs
  src/Maintenance/Maintenance/MaintenanceConfiguration/MaintenanceConfigurationUpdateMethod.cs
  src/Maintenance/Maintenance/Models/MaintenanceAutoMapperProfile.cs
  src/Maintenance/Maintenance/Models/PSApplyUpdate.cs
  src/Maintenance/Maintenance/Models/PSArgument.cs
  src/Maintenance/Maintenance/Models/PSConfigurationAssignment.cs
  src/Maintenance/Maintenance/Models/PSMaintenanceConfiguration.cs
  src/Maintenance/Maintenance/Models/PSUpdate.cs
  src/Maintenance/Maintenance/Properties/AssemblyInfo.cs
  src/Maintenance/Maintenance/Properties/Resources.Designer.cs
  src/Maintenance/Maintenance/Properties/Resources.resx
  src/Maintenance/Maintenance/StartupScripts/sample.ps1
  src/Maintenance/Maintenance/Update/UpdateListMethod.cs
  src/Maintenance/Maintenance/help/Az.Maintenance.md
  src/Maintenance/Maintenance/help/Get-AzApplyUpdate.md
  src/Maintenance/Maintenance/help/Get-AzConfigurationAssignment.md
  src/Maintenance/Maintenance/help/Get-AzMaintenanceConfiguration.md
  src/Maintenance/Maintenance/help/Get-AzMaintenanceUpdate.md
  src/Maintenance/Maintenance/help/New-AzApplyUpdate.md
  src/Maintenance/Maintenance/help/New-AzConfigurationAssignment.md
  src/Maintenance/Maintenance/help/New-AzMaintenanceConfiguration.md
  src/Maintenance/Maintenance/help/Remove-AzConfigurationAssignment.md
  src/Maintenance/Maintenance/help/Remove-AzMaintenanceConfiguration.md
  src/Maintenance/Maintenance/help/Update-AzMaintenanceConfiguration.md
  tools/StaticAnalysis/Exceptions/Az.Maintenance/AssemblyVersionConflict.csv
  tools/StaticAnalysis/Exceptions/Az.Maintenance/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Maintenance/ExtraAssemblies.csv
  tools/StaticAnalysis/Exceptions/Az.Maintenance/HelpIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Maintenance/MissingAssemblies.csv
  tools/StaticAnalysis/Exceptions/Az.Maintenance/SignatureIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#10393 Change New-AzAdServicePrincipal to add credentials only to associated…
  src/Resources/Resources.Test/ScenarioTests/ActiveDirectoryTests.cs
  src/Resources/Resources.Test/ScenarioTests/ActiveDirectoryTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestCreateDeleteSpCredentials.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestNewADServicePrincipal.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests/TestNewADServicePrincipalWithReaderRole.json
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Properties/Resources.Designer.cs
  src/Resources/Resources/Properties/Resources.resx
  src/Resources/Resources/Resources.csproj
Labels: Sprint Candidate, Waiting for CI :shipit:

#10552 [Blueprint] Blueprint and artifact folder/file names should be platform agnostic
  src/Blueprint/Blueprint/Cmdlets/BlueprintCmdletBase.cs
  src/Blueprint/Blueprint/Cmdlets/BlueprintDefinition/BlueprintDefinitionCmdletBase.cs
Labels: needs-review

#10576 [Blueprint] Update version number and changelog for a new version
  src/Blueprint/Blueprint/ChangeLog.md
Labels: needs-review

#10582 Small correction on description
  src/AlertsManagement/AlertsManagement/help/Remove-AzActionRule.md
Labels: needs-review

#10571 [RecoveryServices.Backup] Added cmdlets to enable or disable SoftdeleteFeature in a vault
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMSetVaultProperty.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/GetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVaultProperty.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
Labels: needs-review

#10412 Fix the bug of PowerShellGet in tools/RunVersionController.ps1
  tools/RunVersionController.ps1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Attestation.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Blueprint.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.DataBox.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.DataMigration.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.DevSpaces.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.DeviceProvisioningServices.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.GuestConfiguration.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.IotCentral.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Kusto.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.ManagedServiceIdentity.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Management.CognitiveServices.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Management.PowerBIEmbedded.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Management.Search.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Management.Storage.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.ManagementPartner.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Maps.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.MixedReality.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.NetAppFiles.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.PrivateDns.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.ARM.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Reservations.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.ResourceGraph.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Search.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Security.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.SecurityCenter.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Subscription.dll.json
  tools/Tools.Common/SerializedCmdlets/TestCmdletsModule.dll.json
Labels: needs-review

#10553 [Compute] SkipExtensionsOnOverprovisionedVMs for VMSS
  src/Compute/Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/Compute/Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetProfileTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/SimpleNewVmssSkipExtOverprovision.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Update-AzVmss.md
  tools/StaticAnalysis/Exceptions/Az.Compute/SignatureIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#10585 S161 RC2
  ChangeLog.md
  src/Compute/Compute/Az.Compute.psd1
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  tools/Az/Az.psd1
Labels: Waiting for CI :shipit:

#10591 remove conflicting files
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.NetAppFiles.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.PrivateDns.dll.json
Labels: needs-review

#10580 handle null reference in get-azlocation when no subscription under current directory
  src/Resources/ResourceManager/Implementation/Locations/GetAzureLocationCmdlet.cs
  src/Resources/ResourceManager/Properties/Resources.Designer.cs
  src/Resources/ResourceManager/Properties/Resources.resx
Labels: needs-review

#10586 Upgrade test framework (alternative for #10500)
  .azure-pipelines/powershell-core.yml
  .azure-pipelines/windows-powershell.yml
  build.proj
  src/Automation/Automation.Test/Automation.Test.csproj
  src/Az.Test.props
  src/Sql/Sql.Test/Utilities/UnitTestHelper.cs
  src/SqlVirtualMachine/SqlVirtualMachine.Test/Utilities/UnitTestHelper.cs
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
  tools/Common.Netcore.Dependencies.Test.targets
Labels: needs-review

#10542 [Storage] Support Idenity SAS - Target 12/17 PSH release
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestRevokeAzStorageAccountUserDelegationKeys.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/RevokeAzStorageAccountUserDelegationKeys.cs
  src/Storage/Storage.Management/StorageAccount/StorageAccountBaseCmdlet.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/New-AzStorageBlobSASToken.md
  src/Storage/Storage.Management/help/New-AzStorageContainerSASToken.md
  src/Storage/Storage.Management/help/New-AzStorageContext.md
  src/Storage/Storage.Management/help/Revoke-AzStorageAccountUserDelegationKeys.md
  src/Storage/Storage.Test/Service/MockStorageBlobManagement.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageBlobSasToken.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainerSasToken.cs
  src/Storage/Storage/Model/Contract/IStorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/StorageBlobManagement.cs
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: needs-review

#10525 Update to latest sdk version and priovide new api of CalculatePrice and Purchase
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Reservations/Reservations.Test/Reservations.Test.csproj
  src/Reservations/Reservations.Test/ScenarioTests/ReservationOrderTests.ps1
  src/Reservations/Reservations.Test/ScenarioTests/ReservationTests.cs
  src/Reservations/Reservations.Test/ScenarioTests/ReservationTests.ps1
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationOrderTests/TestGetReservationOrder.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationOrderTests/TestListReservationOrders.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestCalculatePrice.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestGetCatalog.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestGetReservation.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestGetReservationOrderId.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestListReservationHistory.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestListReservations.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestMergeReservation.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestPurchase.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestSplitReservation.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestUpdateReservationToShared.json
  src/Reservations/Reservations.Test/SessionRecords/Microsoft.Azure.Commands.Reservations.Test.ScenarioTests.ReservationTests/TestUpdateReservationToSingle.json
  src/Reservations/Reservations/Az.Reservations.psd1
  src/Reservations/Reservations/ChangeLog.md
  src/Reservations/Reservations/Cmdlets/Calculate.cs
  src/Reservations/Reservations/Cmdlets/Purchase.cs
  src/Reservations/Reservations/Custom/PSCalculatePriceResponseProperties.cs
  src/Reservations/Reservations/Custom/PSReservationOrder.cs
  src/Reservations/Reservations/Reservations.csproj
  src/Reservations/Reservations/help/Az.Reservations.md
  src/Reservations/Reservations/help/Get-AzReservation.md
  src/Reservations/Reservations/help/Get-AzReservationCatalog.md
  src/Reservations/Reservations/help/Get-AzReservationHistory.md
  src/Reservations/Reservations/help/Get-AzReservationOrder.md
  src/Reservations/Reservations/help/Get-AzReservationOrderId.md
  src/Reservations/Reservations/help/Get-AzReservationQuote.md
  src/Reservations/Reservations/help/Merge-AzReservation.md
  src/Reservations/Reservations/help/New-AzReservation.md
  src/Reservations/Reservations/help/Split-AzReservation.md
  src/Reservations/Reservations/help/Update-AzReservation.md
Labels: needs-review

#10594 [IotCentral] Remove subdomain check for idempotent
  src/IotCentral/IotCentral/ChangeLog.md
  src/IotCentral/IotCentral/Common/IotCentralUtils.cs
  src/IotCentral/IotCentral/IotCentral/NewAzureRmIotCentralApp.cs
Labels: needs-revision

#10605 [Storage] Add mapping table for adls gen1->gen2 cmdlets
  src/Storage/Storage/DatalakeGen2/GEN1_GEN2_MAPPING.md
Labels: needs-review

#10565 [Az.Resources] Fix template parameter name conflict issue for deployment cmdlets
  src/Resources/ResourceManager/Utilities/TemplateUtility.cs
  src/Resources/Resources.Test/Models.ResourceGroups/GalleryTemplatesClientTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#10597 Update for new API 2019-08-01 (#29)
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/Common.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirectory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumePipelines.json
  src/NetAppFiles/NetAppFiles/Account/NewNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/Account/SetNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/Account/UpdateNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/Az.NetAppFiles.psd1
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/NetAppFiles.csproj
  src/NetAppFiles/NetAppFiles/Pool/NewNetAppFilesPool.cs
  src/NetAppFiles/NetAppFiles/Pool/UpdateNetAppFilesPool.cs
  src/NetAppFiles/NetAppFiles/Volume/NewNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/Volume/UpdateNetAppFilesVolume.cs
Labels: needs-review

#10603 Update Attestation Powershell cmdlets for new .Net SDK version
  src/Attestation/Attestation.Test/Attestation.Test.csproj
  src/Attestation/Attestation.Test/PemFiles/policySigningCerts.pem
  src/Attestation/Attestation.Test/Properties/AssemblyInfo.cs
  src/Attestation/Attestation.Test/ScenarioTests/AttstationTests.cs
  src/Attestation/Attestation.Test/ScenarioTests/AttstationTests.ps1
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestCreateAttestationWithPolicySigningCertificate.json
  src/Attestation/Attestation/Attestation.csproj
  src/Attestation/Attestation/Commands/GetAzureAttestation.cs
  src/Attestation/Attestation/Commands/NewAzureAttestation.cs
  src/Attestation/Attestation/Models/AttestationCmdletBase.cs
  src/Attestation/Attestation/Models/AttestationCreationParameters.cs
  src/Attestation/Attestation/Models/AttestationManagementClient.cs
  src/Attestation/Attestation/help/New-AzAttestation.md
Labels: needs-review

#10610 Correct return type for New-AzStorageAccountKey
  src/Storage/Storage.Management/help/New-AzStorageAccountKey.md
Labels: needs-review

#10609 Upgraded storage creation in Vulnerability Assessment auto enablement…
  src/Sql/Sql/AdvancedThreatProtection/Templates/DeployInstanceVaTemplate.json
  src/Sql/Sql/AdvancedThreatProtection/Templates/DeployServerVaTemplate.json
  src/Sql/Sql/ChangeLog.md
Labels: needs-review

#10608 [DataFactory] Upgrade sdk to version 4.5.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-review

#10612 Added support to specify the Curve for Certificate Policies
  src/KeyVault/KeyVault.Test/Models/PSKeyVaultCertificatePolicyTests.cs
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Constants.cs
  src/KeyVault/KeyVault/Commands/NewAzureKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/Models/PSKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/help/New-AzKeyVaultCertificatePolicy.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultCertificatePolicy.md
Labels: needs-review

#10611 Update New-AzEventHubAuthorizationRuleSASToken.md
  src/EventHub/EventHub/help/New-AzEventHubAuthorizationRuleSASToken.md
Labels: needs-review

#10627 Update azure-powershell-developer-guide.md
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: needs-review
