Repository Azure/azure-powershell, pull requests merged in 2019-09, with the labels that each got.

#9933 added vCore example to create an elastic pool
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/help/New-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:

#9851 Update Test-AzNetworkWatcherIPFlow.md to correct null index error in $Nics example line
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/Test-AzNetworkWatcherIPFlow.md
Labels: Waiting for CI :shipit:

#9816 Bug fix for scope type
  src/AlertsManagement/AlertsManagement/ActionRuleCommands/SetAzureActionRule.cs
  src/Monitor/Monitor/ChangeLog.md
Labels: Waiting for CI :shipit:

#9973 Update example in Get-AzWebAppPublishingProfile documentation
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/help/Get-AzWebAppPublishingProfile.md
Labels: needs-review

#9932 Update Get-AzNetworkWatcherPacketCapture.md
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/Get-AzNetworkWatcherPacketCapture.md
Labels: Waiting for CI :shipit:

#9958 Update Set-AzApiManagementPolicy.md
  src/ApiManagement/ApiManagement/ChangeLog.md
  src/ApiManagement/ApiManagement/help/Set-AzApiManagementPolicy.md
Labels: Waiting for CI :shipit:

#9878 [Blueprint] Make RP registration call request reply
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Cmdlets/BlueprintCmdletBase.cs
Labels: Waiting for CI :shipit:

#9935 SQR Cmdlets improvements
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/SetScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/help/Get-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleAznsActionGroup.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleSource.md
  src/Monitor/Monitor/help/Remove-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/Set-AzScheduledQueryRule.md
  src/Monitor/Monitor/help/Update-AzScheduledQueryRule.md
Labels: Waiting for CI :shipit:

#9896 Get-Metrics gives error
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/help/Get-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:

#9956 Correction to New-ApplicationGateway example 1.
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/New-AzApplicationGateway.md
Labels: Waiting for CI :shipit:

#9984 webapp: Migrating an app to another Appservice plan was removing existing tags from the app resource
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestTagsNotRemovedBySetWebApp.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/Websites/Websites/Cmdlets/WebApps/SetAzureWebApp.cs
  src/Websites/Websites/help/New-AzWebApp.md
  src/Websites/Websites/help/New-AzWebAppSlot.md
Labels: Waiting for CI :shipit:

#9966 [Storage] Fix block blob with properties fail on container enabled ImmutabilityPolicy
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
Labels: needs-review

#9945 Making the Monitor PS SDK to point to the version 0.24.1-preview of the .Net SDK
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/Monitor/Monitor.Test/ScheduledQueryRules/NewScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/ScheduledQueryRules/SetScheduledQueryRuleTests.cs
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestAddAzureRmMetricAlertRuleV2.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestGetAzureRmMetricAlertRuleV2.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestRemoveAzureRmMetricAlertRuleV2.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.ScheduledQueryRulesTests/TestNewGetUpdateSetRemoveScheduledQueryRule.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.ScheduledQueryRulesTests/TestPipingRemoveSetUpdateScheduledQueryRule.json
  src/Monitor/Monitor.sln
  src/Monitor/Monitor/ActionGroups/SetAzureRmActionGroupCommand.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/Monitor.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  tools/StaticAnalysis/Exceptions/Az.Monitor/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Monitor/SignatureIssues.csv
Labels: needs-review

#9996 [Azure resource graph] ignore subscription from context
  src/ResourceGraph/ResourceGraph/ChangeLog.md
  src/ResourceGraph/ResourceGraph/Cmdlets/SearchAzureRmGraph.cs
Labels: Waiting for CI :shipit:

#9988 Version Az.HealthcareApis for release
  src/HealthcareApis/HealthcareApis/Az.HealthcareApis.psd1
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/Properties/AssemblyInfo.cs
Labels: needs-review

#9994 Fixed typo in example for Update-AzServiceFabricReliability doc
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/ServiceFabric/ServiceFabric/help/Update-AzServiceFabricReliability.md
Labels: needs-review

#9961 Update version of Az.HDInsight for preview release
  src/HDInsight/HDInsight/Az.HDInsight.psd1
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/Properties/AssemblyInfo.cs
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.HDInsight.dll.json
Labels: needs-review

#10000 Modify Remove-AzSqlDatabaseAudit and Remove-AzSqlServerAudit
  src/Sql/Sql.Test/ScenarioTests/AuditTests.cs
  src/Sql/Sql.Test/ScenarioTests/AuditTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AuditTests/TestRemoveDatabaseAuditingSettingsMultipleDiagnosticSettings.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.AuditTests/TestRemoveServerAuditingSettingsMultipleDiagnosticSettings.json
  src/Sql/Sql/Auditing/Cmdlet/RemoveAzSqlDatabaseAudit.cs
  src/Sql/Sql/Auditing/Cmdlet/RemoveAzSqlServerAudit.cs
  src/Sql/Sql/Auditing/DefinitionsCommon.cs
  src/Sql/Sql/Auditing/Model/ServerBlobAuditingSettingsModel.cs
  src/Sql/Sql/Auditing/Services/SqlAuditAdapter.cs
  src/Sql/Sql/ChangeLog.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#9968 New-AzRoleAssignment ParameterSet changes to allow parameter Scope as optional
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/help/New-AzRoleAssignment.md
Labels: needs-review

#10031 Make OS Restriction in DSC Node Registration explicit
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/help/Register-AzAutomationDscNode.md
Labels: needs-review

#9844 Add new cmdlet and update existing emdlet
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/DeviceProvisioningServices.Test.csproj
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsLinkedHubTests.cs
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsAccessPolicyTests/IotDpsAccessPolicyLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsLinkedHubTests/IotDpsLinkedHubLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsTests/IotDpsLifeCycle.json
  src/IotHub/IotHub.Test/IotHub.Test.csproj
  src/IotHub/IotHub.Test/ScenarioTests/IotHubTests.ps1
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubRoutingTests/TestAzureIotHubRoutingLifeCycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubTests/TestAzureIotHubLifeCycle.json
  src/IotHub/IotHub/Az.IotHub.psd1
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/Common/IotHubUtils.cs
  src/IotHub/IotHub/IotHub.csproj
  src/IotHub/IotHub/IotHub/AddAzureRmIotHubEventHubConsumerGroup.cs
  src/IotHub/IotHub/IotHub/GetAzureRmEventHubConsumerGroup.cs
  src/IotHub/IotHub/IotHub/ManualFailover/InvokeAzureRmIotHubManualFailover.cs
  src/IotHub/IotHub/IotHub/RemoveAzureRmIotHubEventHubConsumerGroup.cs
  src/IotHub/IotHub/IotHub/SetAzureRmIotHub.cs
  src/IotHub/IotHub/Models/PSIotHubInputProperties.cs
  src/IotHub/IotHub/Models/PSIotHubLocationDescription.cs
  src/IotHub/IotHub/Models/PSIotHubProperties.cs
  src/IotHub/IotHub/Properties/Resources.Designer.cs
  src/IotHub/IotHub/Properties/Resources.resx
  src/IotHub/IotHub/help/Add-AzIotHubEventHubConsumerGroup.md
  src/IotHub/IotHub/help/Az.IotHub.md
  src/IotHub/IotHub/help/Get-AzIotHubEventHubConsumerGroup.md
  src/IotHub/IotHub/help/Invoke-AzIotHubManualFailover.md
  src/IotHub/IotHub/help/Remove-AzIotHubEventHubConsumerGroup.md
  src/IotHub/IotHub/help/Set-AzIotHub.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: Cmdlet Review Complete, Sprint Candidate

#10016 [Datafactory] Adding 3 new commands to ADF V2 for blob event triggers
  src/DataFactory/DataFactoryV2.Test/Resources/blobeventtrigger.json
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/TriggerTests.cs
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/TriggerTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.TriggerTests/TestBlobEventTriggerSubscriptions.json
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.TriggerTests/TestBlobEventTriggerSubscriptionsByInputObject.json
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.TriggerTests/TestBlobEventTriggerSubscriptionsByResourceId.json
  src/DataFactory/DataFactoryV2/Az.DataFactory.psd1
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/DataFactoryContextActionBaseCmdlet.cs
  src/DataFactory/DataFactoryV2/DataFactoryContextSubResourceBaseCmdlet.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.Trigger.cs
  src/DataFactory/DataFactoryV2/Models/PSTriggerSubscriptionStatus.cs
  src/DataFactory/DataFactoryV2/Triggers/AddAzureDataFactoryTriggerSubscriptionCommand.cs
  src/DataFactory/DataFactoryV2/Triggers/GetAzureDataFactoryTriggerSubscriptionStatusCommand.cs
  src/DataFactory/DataFactoryV2/Triggers/RemoveAzureDataFactoryTriggerCommand.cs
  src/DataFactory/DataFactoryV2/Triggers/RemoveAzureDataFactoryTriggerSubscriptionCommand.cs
  src/DataFactory/DataFactoryV2/help/Add-AzDataFactoryV2TriggerSubscription.md
  src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2TriggerSubscriptionStatus.md
  src/DataFactory/DataFactoryV2/help/Remove-AzDataFactoryV2TriggerSubscription.md
Labels: Sprint Candidate

#10006 [Storage] Support preserverPerserve File Attributes
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Get-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Set-AzStorageFileContent.md
  src/Storage/Storage/File/Cmdlet/GetAzureStorageFileContent.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageFileContent.cs
  src/Storage/Storage/File/StorageFileDataManagementCmdletBase.cs
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
Labels: Sprint Candidate, Waiting for CI :shipit:

#10019 Fix Email validation util. Would currently flag mail addresses that s…
  src/Sql/Sql.Test/UnitTests/AzureSqlUtilTests.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Services/Util.cs
Labels: Sprint Candidate, Waiting for CI :shipit:

#9963 Fixed Start-AzAutomationRunbook cmdlet Null reference exception
  src/Automation/Automation.Test/ScenarioTests/AutomationTests.ps1
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.AutomationTests/TestAutomationRunbookWithParameter.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.AutomationTests/TestAutomationRunbookWithParameterAndWait.json
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClient.cs
Labels: Sprint Candidate, Waiting for CI :shipit:

#9999 [HDInsight] Call out breaking changes
  src/HDInsight/HDInsight/ManagementCommands/DisableAzureHDInsightOMSCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/EnableAzureHDInsightOMSCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GetAzureHDInsightOMSCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GrantAzureHDInsightRdpServicesAccessCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/RemoveAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/RevokeAzureHDInsightRdpServicesAccessCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightGatewayCredentialCommand.cs
Labels: Sprint Candidate, Waiting for CI :shipit:

#10046 Update ChangeLog.md for HDInsight
  src/HDInsight/HDInsight/ChangeLog.md
Labels: needs-review

#10050 Updating ADF SDK to 4.1.3
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Sprint Candidate, Waiting for CI :shipit:

#10035 Added more exception handling in Az.HealthcareApis
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/HealthcareApis/GetAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/NewAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/RemoveAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/SetAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/Properties/Resources.Designer.cs
  src/HealthcareApis/HealthcareApis/Properties/Resources.resx
Labels: Sprint Candidate, Waiting for CI :shipit:

#9574 Support single role restore for AzS infra backup
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin.csproj
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Azs.Backup.Admin.psd1
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/ChangeLog.md
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Restore-AzsBackup.ps1
  src/StackAdmin/Azs.Backup.Admin/Module/packages.config
  src/StackAdmin/Azs.Backup.Admin/Tests/Azs.Backup.Admin.Tests.csproj
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestRestoreBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/packages.config
  src/StackAdmin/Azs.Backup.Admin/Tests/src/Backup.Tests.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
  tools/Modules/Run-UnitTests.ps1
Labels: needs-review

#9943 Add tooling documentation for Tools.Common, StaticAnalysis, and CI Filter
  documentation/tooling/ci-filter.md
  documentation/tooling/static-analysis.md
  documentation/tooling/tools-common.md
Labels: Discuss, needs-review

#10045 Initial set of RFCs for Az PowerShell
  documentation/RFC/README.md
  documentation/RFC/RFC0001-Aure-Profiles.md
  documentation/RFC/RFC0002-SubscriptionList-in-Get.md
  documentation/RFC/RFCNNNN-New-RFC-Template.md
Labels: needs-revision

#10012 Add documentation on Resource Manager and Active Directory concepts and cmdlets
  documentation/internal/resource-manager-active-directory.md
Labels: needs-review

#10083 Update Az.Batch for Preview Release
  src/Batch/Batch/Az.Batch.psd1
  src/Batch/Batch/ChangeLog.md
  src/Batch/Batch/Properties/AssemblyInfo.cs
Labels: needs-review

#10061 Added more exception handling in New-AzHealthcareApisService
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/HealthcareApis/NewAzureRmHealthcareApisService.cs
Labels: needs-review

#10093 Generation: Storage Release Notes
  src/Storage/docs/latest-2019-04-30/Set-AzStorageBlobServiceProperty.md
  src/Storage/resources/ReleaseNotes.md
  src/Storage/resources/comparing_modules_management_new.md
Labels: Waiting for CI :shipit:

#10112 Fixing typos in RFC template
  documentation/RFC/RFCNNNN-New-RFC-Template.md
Labels: needs-review

#10117 Update RFC0001 - typo
  documentation/RFC/RFC0001-Aure-Profiles.md
Labels: needs-review

#10092 adding Model Flattening to RFC
  documentation/RFC/Model Flattening and Inline Creation .md
Labels: needs-revision

#10098 Added issue template for Az 4.x
  .github/ISSUE_TEMPLATE/az4-preview-bug-report.md
  documentation/preview/README.md
Labels: needs-revision

#10123 updating the name to include RFC and dashes
  documentation/RFC/RFC0004-Model-Flattening-and-Inline-Creation.md
Labels: needs-review

#10126 Fixed typo in RFC0004
  documentation/RFC/RFC0004-Model-Flattening-and-Inline-Creation.md
Labels: needs-review

#10124 Updated path to RFC0004
  documentation/preview/README.md
Labels: needs-review

#10118 Added Azure Profiles description
  documentation/preview/AzureProfiles.md
Labels: needs-review

#10079 Add deprecation notice on Batch cmdlet
  src/Batch/Batch/BatchAccounts/GetBatchAccountNodeAgentSkuCommand.cs
  src/Batch/Batch/ChangeLog.md
Labels: needs-review

#10024 Monitor Release Notes and other small changes
  src/Monitor/Az.Monitor.psd1
  src/Monitor/custom/latest-2019-04-30/New-AzLogProfile.ps1
  src/Monitor/custom/latest-2019-04-30/Set-AzLogProfile.ps1
  src/Monitor/docs/latest-2019-04-30/Az.Monitor.md
  src/Monitor/docs/latest-2019-04-30/New-AzLogProfile.md
  src/Monitor/docs/latest-2019-04-30/Set-AzLogProfile.md
  src/Monitor/docs/latest-2019-04-30/Update-AzActionGroup.md
  src/Monitor/examples/latest-2019-04-30/Update-AzActionGroup.md
  src/Monitor/readme.md
  src/Monitor/resources/ReleaseNotes.md
  src/Monitor/resources/cm_new.md
Labels: needs-review

#10091 Add features, omissions, and RFCs to preview documentation
  documentation/RFC/RFC0003-AsynchronousOperations.md
  documentation/RFC/RFC0005-ETags.md
  documentation/RFC/RFC0006-Creation-and-Modification-Cmdlets.md
  documentation/preview/Features.md
  documentation/preview/Omissions.md
Labels: Waiting for CI :shipit:

#10054 Added P5 SKU to Set-AzRedisCache help documentation
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/help/Set-AzRedisCache.md
Labels: needs-review

#10114 Fix for Issue 9810 - error in Reset-AzStorageSyncServerCertificate
  src/StorageSync/StorageSync/ChangeLog.md
  src/StorageSync/StorageSync/Properties/StorageSyncResources.resx
Labels: needs-review

#10134 Add TOC in Readme
  documentation/preview/README.md
Labels: needs-review

#10139 fixed code for last section. AddressPrefix for subnet is PropertiesAd…
  documentation/RFC/RFC0004-Model-Flattening-and-Inline-Creation.md
Labels: needs-review

#10131 Make all modules preview and update version to 4
  src/AppService/Az.AppService.psd1
  src/AppService/readme.md
  src/Billing/Az.Billing.psd1
  src/Billing/readme.md
  src/Compute/readme.md
  src/Dns/readme.md
  src/KeyVault/readme.md
  src/Monitor/Az.Monitor.psd1
  src/Monitor/readme.md
  src/Network/readme.md
  src/Resources/readme.md
  src/ServiceBus/readme.md
  src/Storage/readme.md
Labels: needs-review

#10106 Introduce new SKUs and Generations for VirtualNetwork VPN gateways.
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestVirtualNetworkExpressRouteGatewayCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSVirtualNetworkGateway.cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
  src/Network/Network/help/Set-AzVirtualNetworkGateway.md
Labels: needs-review

#10109 Fixed New-AzureAutomationSoftwareUpdateConfiguration cmdlet for Linux reboot setting parameter
  src/Automation/Automation.Test/ScenarioTests/UpdateManagementTests.cs
  src/Automation/Automation.Test/ScenarioTests/UpdateManagementTests.ps1
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/CreateLinuxSucWithRebootSetting.json
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClientSoftwareUpdateConfiguration.cs
Labels: needs-revision

#10125 ADE - Remove QueryEncryptionStatus & honor different publisher, type and name
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestAzureDiskEncryptionExtensionSinglePassEnableAndDisableWithNonDefaultParams.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/AzureDiskEncryption/GetAzureDiskEncryptionStatus.cs
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#10136 regenerated Monitor help
  src/Monitor/Monitor/help/New-AzActionGroupReceiver.md
Labels: needs-review

#10148 [Storage] Support list container/account with nextpagelink
  src/EventGrid/EventGrid.Test/EventGrid.Test.csproj
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/Blob/GetAzureStorageContainer.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/Get-AzRmStorageContainer.md
Labels: needs-review

#10151 [Storage] Upgrade to xscl 11.1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Storage.csproj
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
Labels: Waiting for CI :shipit:
