Repository Azure/azure-powershell, pull requests merged in 2019-01, with the labels that each got.

#8188 Updated, AzureFirewall test to match recent update
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUD.json
Labels: Waiting for CI :shipit:

#8204 [Compute] Upgrade Compute client library to 24.1.0 and enable some tests.
  src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/AEMExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/AvailabilityZoneTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/ChefExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/ChefExtensionTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/ComputeTestCommon.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/DiagnosticsExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/DiagnosticsExtensionTests.ps1
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/DiskRPTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/DscExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/GalleryTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/ImageTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/SqlIaaSExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineBootDiagnosticsTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineExtensionTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineNetworkInterfaceTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineRunCommandTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/ResourceManager/Compute/Commands.Compute/Commands.Compute.Netcore.csproj
  src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetReimageMethod.cs
  src/ResourceManager/Network/Commands.Network.Test/Commands.Network.Test.Netcore.csproj
  src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup.Test/Commands.RecoveryServices.Backup.Test.Netcore.csproj
Labels: needs-review

#8216 Update Stop-AzServiceBusMigration.md
  src/ResourceManager/ServiceBus/Commands.ServiceBus/help/Stop-AzServiceBusMigration.md
Labels: Waiting for CI :shipit:

#8189 Fix, cover ServiceEndpointPolicy Lists
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetServiceEndpointPolicies.json
  src/ResourceManager/Network/Commands.Network/ServiceEndpointPolicy/AzureServiceEndpointPolicyBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/ServiceEndpointPolicy/GetAzureServiceEndpointPolicyCommand.cs
  src/ResourceManager/Network/Commands.Network/help/Get-AzServiceEndpointPolicy.md
Labels: Waiting for CI :shipit:

#8217 Fix Enable/Disable-AzureRmAlias
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/AliasHelper.cs
Labels: Waiting for CI :shipit:

#8219 Update description of Zone parameter in help
  src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVMConfig.md
Labels: Waiting for CI :shipit:

#8218 Update description for zone parameter
  src/ResourceManager/Compute/Commands.Compute/help/New-AzVMConfig.md
Labels: Waiting for CI :shipit:

#8129 Cortex ergw
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/CortexTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/CortexTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCrossConnectionTests.cs
  src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCrossConnectionTests.ps1
  src/ResourceManager/Network/Commands.Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexExpressRouteCRUD.json
  src/ResourceManager/Network/Commands.Network/Az.Network.psd1
  src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs
  src/ResourceManager/Network/Commands.Network/Cortex/CortexParameterSetNames.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/ExpressRouteConnection/ExpressRouteConnectionBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/ExpressRouteConnection/GetAzureRmExpressRouteConnectionCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/ExpressRouteConnection/NewAzureRmExpressRouteConnectionCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/ExpressRouteConnection/RemoveAzureRmExpressRouteConnectionCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/ExpressRouteConnection/SetAzureRmExpressRouteConnectionCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/ExpressRouteGatewayBaseCmdlet.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/GetAzureRmExpressRouteGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/NewAzureRmExpressRouteGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/RemoveAzureRmExpressRouteGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/Cortex/ExpressRouteGateway/SetAzureRmExpressRouteGatewayCommand.cs
  src/ResourceManager/Network/Commands.Network/ExpressRouteCrossConnection/SetAzureRMExpressRouteCrossConnectionCommand.cs
  src/ResourceManager/Network/Commands.Network/Microsoft.Azure.Commands.Network.format.ps1xml
  src/ResourceManager/Network/Commands.Network/Models/Cortex/PSExpressRouteCircuitPeeringId.cs
  src/ResourceManager/Network/Commands.Network/Models/Cortex/PSExpressRouteConnection.cs
  src/ResourceManager/Network/Commands.Network/Models/Cortex/PSExpressRouteGateway.cs
  src/ResourceManager/Network/Commands.Network/Models/Cortex/PSExpressRouteGatewayAutoscaleConfiguration.cs
  src/ResourceManager/Network/Commands.Network/Models/Cortex/PSExpressRouteGatewayPropertiesAutoScaleConfigurationBounds.cs
  src/ResourceManager/Network/Commands.Network/Models/Cortex/PSVirtualHubId.cs
  src/ResourceManager/Network/Commands.Network/Properties/Resources.Designer.cs
  src/ResourceManager/Network/Commands.Network/Properties/Resources.resx
  src/ResourceManager/Network/Commands.Network/help/Add-AzExpressRouteCrossConnectionPeering.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteConnection.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteCrossConnection.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteCrossConnectionARPTable.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteCrossConnectionPeering.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteCrossConnectionRouteTable.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteCrossConnectionRouteTableSummary.md
  src/ResourceManager/Network/Commands.Network/help/Get-AzExpressRouteGateway.md
  src/ResourceManager/Network/Commands.Network/help/New-AzExpressRouteConnection.md
  src/ResourceManager/Network/Commands.Network/help/New-AzExpressRouteCrossConnectionPeering.md
  src/ResourceManager/Network/Commands.Network/help/New-AzExpressRouteGateway.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzExpressRouteConnection.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzExpressRouteCrossConnectionPeering.md
  src/ResourceManager/Network/Commands.Network/help/Remove-AzExpressRouteGateway.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzExpressRouteConnection.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzExpressRouteCrossConnection.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzExpressRouteCrossConnectionPeering.md
  src/ResourceManager/Network/Commands.Network/help/Set-AzExpressRouteGateway.md
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: Cmdlet Review Complete

#8222 Corrected command name in Set-AzSqlElasticPool help
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:, needs-review

#8223 Corrected command name in Set-AzureRmSqlElasticPool help
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlElasticPool.md
Labels: Waiting for CI :shipit:, needs-review

#8187 EventGrid: PowerShell cmdlets for API Version 2019-01-01
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/Commands.EventGrid.Test.Netcore.csproj
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/ScenarioTests/Common.ps1
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/ScenarioTests/EventSubscriptionTests.cs
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/ScenarioTests/EventSubscriptionTests.ps1
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/ScenarioTests/TopicTests.ps1
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToAzureSubscription.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToAzureSubscription2.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToCustomTopics.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToCustomTopics2.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToResourceCRUD.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToResourceGroup.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscriptionToResourceGroup2.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.EventSubscriptionTests/EventGrid_EventSubscription_Deadletter.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.TopicTests/EventGrid_TopicsCreateGetAndDelete.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.TopicTests/EventGrid_TopicsGetKey.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.TopicTests/EventGrid_TopicsNewKey.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.TopicTests/EventGrid_TopicsSet.json
  src/ResourceManager/EventGrid/Commands.EventGrid.Test/SessionRecords/Microsoft.Azure.Commands.EventGrid.Tests.ScenarioTests.TopicTypeTests/EventGrid_TopicTypes.json
  src/ResourceManager/EventGrid/Commands.EventGrid/AzureEventGridCmdletBase.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/ChangeLog.md
  src/ResourceManager/EventGrid/Commands.EventGrid/Commands.EventGrid.Netcore.csproj
  src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/GetAzureEventGridSubscription.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/NewAzureEventGridSubscription.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/RemoveAzureEventGridSubscription.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/UpdateAzureEventGridSubscription.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Models/PSEventSubscription.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Topic/GetAzureEventGridTopic.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Topic/GetAzureEventGridTopicKeys.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Topic/NewAzureEventGridTopic.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Topic/NewAzureEventGridTopicKey.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Topic/RemoveAzureEventGridTopic.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Topic/SetAzureEventGridTopic.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/TopicType/GetAzureRmEventGridTopicType.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Utilities/EventGridClient.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Utilities/EventGridConstants.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/Utilities/EventGridUtils.cs
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Az.EventGrid.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Get-AzEventGridSubscription.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Get-AzEventGridTopic.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Get-AzEventGridTopicKey.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Get-AzEventGridTopicType.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/New-AzEventGridSubscription.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/New-AzEventGridTopic.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/New-AzEventGridTopicKey.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Remove-AzEventGridSubscription.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Remove-AzEventGridTopic.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Set-AzEventGridTopic.md
  src/ResourceManager/EventGrid/Commands.EventGrid/help/Update-AzEventGridSubscription.md
  tools/StaticAnalysis/Exceptions/Az.EventGrid/SignatureIssues.csv
Labels: needs-review

#8221 Azure Advisor cmdlet updates
  src/ResourceManager/Advisor/Commands.Advisor.Test/ScenarioTests/EnableAzAdvisorRecommendation.ps1
  src/ResourceManager/Advisor/Commands.Advisor.Test/ScenarioTests/GetAzAdvisorRecommendation.ps1
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.EnableAzAdvisorRecommendation/EnableAzAdvisorRecommendationByIdParameterSet.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.EnableAzAdvisorRecommendation/EnableAzAdvisorRecommendationByNameParameterSet.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.EnableAzAdvisorRecommendation/EnableAzAdvisorRecommendationPipeline.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorConfiguration/GetConfigurationQuery.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationByCategory.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationByIdParameterSet.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationByNameParameterSet.json
  src/ResourceManager/Advisor/Commands.Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationNoParameter.json
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/DisableAzAdvisorRecommendation.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/EnableAzAdvisorRecommendation.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/GetAzAdvisorConfiguration.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/GetAzAdvisorRecommendation.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/Models/PsAzureAdvisorConfigurationData.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/Models/PsAzureAdvisorResourceRecommendationBase.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/SetAzAdvisorConfiguration.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/Utilities/Client/ConfigurationResource.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/Utilities/Client/RecommendationResource.cs
  src/ResourceManager/Advisor/Commands.Advisor/Cmdlets/Utilities/RecommendationHelper.cs
  src/ResourceManager/Advisor/Commands.Advisor/Microsoft.Azure.Commands.Advisor.format.ps1xml
  src/ResourceManager/Advisor/Commands.Advisor/help/Disable-AzAdvisorRecommendation.md
  src/ResourceManager/Advisor/Commands.Advisor/help/Enable-AzAdvisorRecommendation.md
  src/ResourceManager/Advisor/Commands.Advisor/help/Get-AzAdvisorRecommendation.md
  src/ResourceManager/Advisor/Commands.Advisor/help/Set-AzAdvisorConfiguration.md
  tools/StaticAnalysis/Exceptions/Az.Advisor/BreakingChangeIssues.csv
Labels: needs-revision

#8229 Fix compute doc description
  src/ResourceManager/Compute/Commands.Compute/ChangeLog.md
  src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Action/VirtualMachineActionBaseCmdlet.cs
  src/ResourceManager/Compute/Commands.Compute/help/Restart-AzVM.md
  src/ResourceManager/Compute/Commands.Compute/help/Start-AzVM.md
  src/ResourceManager/Compute/Commands.Compute/help/Stop-AzVM.md
Labels: Waiting for CI :shipit:

#8192 Test Dependency analyzer changes
  src/ResourceManager/Compute/Commands.Compute/Sync/ServicePointHandler.cs
  src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2/Az.DataFactory.psd1
  src/ResourceManager/Profile/Commands.Profile/Accounts.csproj
  src/lib/System.Buffers.dll
  src/lib/System.Net.Http.WinHttpHandler.dll
  src/lib/System.Private.ServiceModel.dll
  src/lib/System.Reflection.DispatchProxy.dll
  src/lib/System.Security.Permissions.dll
  src/lib/System.ServiceModel.Primitives.dll
  tools/StaticAnalysis/DependencyAnalyzer/DependencyAnalyzer.cs
  tools/StaticAnalysis/Exceptions/Az.DataFactoryV2/MissingAssemblies.csv
  tools/StaticAnalysis/Exceptions/Az.Profile/AssemblyVersionConflict.csv
  tools/StaticAnalysis/Exceptions/Az.Profile/SharedAssemblyConflict.csv
Labels: needs-review

#8234 Porting Import context fix from Az module to AzureRM
  src/ResourceManager/Profile/Commands.Profile.Test/ProfileCmdletTests.cs
  src/ResourceManager/Profile/Commands.Profile/ChangeLog.md
  src/ResourceManager/Profile/Commands.Profile/Common/AzureContextModificationCmdlet.cs
  src/ResourceManager/Profile/Commands.Profile/Context/ImportAzureRMContext.cs
  src/ResourceManager/Profile/Commands.Profile/Properties/Resources.Designer.cs
  src/ResourceManager/Profile/Commands.Profile/Properties/Resources.resx
Labels: needs-revision

#8241 Minor spelling correction
  documentation/migration-guides/Az.1.0.0-migration-guide.md
Labels: Waiting for CI :shipit:

#8247 Made sln creation use relative paths instead of full paths
  build.proj
Labels: Sprint Candidate, needs-review

#8254 Fix sign build
  tools/CreateMappings_rules.json
  tools/NewHelpIndex.ps1
Labels: Sprint Candidate, needs-review

#8245 Fix typo in New-AzDeployment
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzDeployment.md
Labels: Waiting for CI :shipit:

#8246 Make MailNickname parameter mandatory for New-AzADUser
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADUserCommand.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzADUser.md
  tools/StaticAnalysis/Exceptions/Az.Resources/BreakingChangeIssues.csv
Labels: Sprint Candidate, Waiting for CI :shipit:

#8239 Add Local scope to Enable-AzureRmAlias
  src/Accounts/Accounts/AzureRmAlias/EnableAzureRmAlias.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Enable-AzureRmAlias.md
Labels: Sprint Candidate, needs-review

#8233 Make name optional in Id parameter set for Compute
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Action/RestartAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Action/SaveAzureVMImageCommand.cs
  src/Compute/Compute/VirtualMachine/Action/SetAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Action/StartAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Action/StopAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/RemoveAzureVMCommand.cs
  src/Compute/Compute/help/Remove-AzVM.md
  src/Compute/Compute/help/Restart-AzVM.md
  src/Compute/Compute/help/Save-AzVMImage.md
  src/Compute/Compute/help/Set-AzVM.md
  src/Compute/Compute/help/Start-AzVM.md
  src/Compute/Compute/help/Stop-AzVM.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Sprint Candidate, needs-review

#8257 Add suppressions file for Policheck
  tools/CheckPoliCheck.ps1
  tools/PolicheckSuppressions.json
Labels: needs-review

#8258 Version Az.Resources for 1.0.1-preview release
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#8268 Fix help xml files
  src/Advisor/Advisor/help/Disable-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Enable-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Get-AzAdvisorConfiguration.md
  src/Advisor/Advisor/help/Get-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Set-AzAdvisorConfiguration.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationMongoDbCollectionSetting.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationMongoDbDatabaseSetting.md
Labels: needs-review

#8267 fixed missing quote in Add-AzVirtualNetworkPeering
  src/Network/Network/help/Add-AzVirtualNetworkPeering.md
Labels: Waiting for CI :shipit:

#8271 Fix test cmdlets
  documentation/testing-docs/using-azure-test-framework.md
  tools/Modules/TestFx-Tasks.psd1
  tools/Modules/TestFx-Tasks.psm1
Labels: needs-review

#8272 Update AzureRmError.ps1 to be resilient over 'directory does not exist' errors when writing files
  src/ResourceManager/Profile/Commands.Profile/StartupScripts/AzureRmError.ps1
  tools/AzureRM.Example.psm1
Labels: needs-review

#8278 Fix typo in Set-AzVirtualNetworkPeering.md
  src/Network/Network/help/Set-AzVirtualNetworkPeering.md
Labels: needs-review

#8284 Update version of Authorization SDK used in Resources
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources/Models.Authorization/AuthorizationClientExtensions.cs
  src/Resources/Resources/Resources.csproj
Labels: needs-review

#8236 Azs.Backup.Admin changes for cert-wrapped encryption
  src/StackAdmin/Azs.Backup.Admin/Help/Get-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/Help/Get-AzsBackupConfiguration.md
  src/StackAdmin/Azs.Backup.Admin/Help/New-AzsEncryptionKeyBase64.md
  src/StackAdmin/Azs.Backup.Admin/Help/Restore-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/Help/Set-AzsBackupConfiguration.md
  src/StackAdmin/Azs.Backup.Admin/Help/Start-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin.csproj
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Azs.Backup.Admin.psd1
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/ChangeLog.md
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Restore-AzsBackup.ps1
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Set-AzsBackupConfiguration.ps1
  src/StackAdmin/Azs.Backup.Admin/Module/packages.config
  src/StackAdmin/Azs.Backup.Admin/Tests/Azs.Backup.Admin.Tests.csproj
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestCreateBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestGetAllBackupLocation.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestGetBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestGetBackupLocation.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestListBackupLocations.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestListBackupOperations.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestListBackups.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestRestoreBackup.json
  src/StackAdmin/Azs.Backup.Admin/Tests/SessionRecords/BackupAdminClient/TestUpdateBackupLocation.json
  src/StackAdmin/Azs.Backup.Admin/Tests/packages.config
  src/StackAdmin/Azs.Backup.Admin/Tests/src/Backup.Tests.ps1
  src/StackAdmin/Azs.Backup.Admin/Tests/src/BackupLocation.Tests.ps1
  src/StackAdmin/Azs.Backup.Admin/Tests/src/Common.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: Azure Stack, Waiting for CI :shipit:

#8160 webapp: Fixes to SSL commandlets
  src/Websites/Websites.Test/ScenarioTests/SSLBindingTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestCreateNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestGetNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestGetWebAppCertificate.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestRemoveNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestWebAppSSLBindingPipeSupport.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/Certificates/NewAzureWebAppSSLBinding.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
Labels: needs-revision

#8302 Update example for Remove-AzNetworkSecurityRuleConfig
  src/Network/Network/help/Remove-AzNetworkSecurityRuleConfig.md
Labels: needs-review

#8301 Fix typo in Update-AzStorageAccountNetworkRuleSet help
  src/Storage/Storage.Management/help/Update-AzStorageAccountNetworkRuleSet.md
Labels: needs-review

#8292 Test for UninstallAzureRm
  src/Accounts/Accounts.Test/MockDataStore.cs
  src/Accounts/Accounts.Test/UninstallAzureRmTests.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/UninstallAzureRm/UninstallAzureRm.cs
Labels: Waiting for CI :shipit:

#8303 Update ADLS change log
  src/DataLakeStore/DataLakeStore/ChangeLog.md
Labels: Waiting for CI :shipit:

#8315 Update documentation for creating app/SP credentials
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzADAppCredential.md
  src/Resources/Resources/help/New-AzADSpCredential.md
Labels: needs-review

#8317 Add information about traits to dev guide
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: Waiting for CI :shipit:

#8307 Update tags for Az.psd1
  tools/Az/Az.psd1
Labels: needs-review

#8319 BugFix: Calling ConvertTo-PlatformImageObject only in the success path
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Add-AzsPlatformImage.ps1
Labels: Waiting for CI :shipit:

#8311 AzAdvisor Get-AzAdvisorRecommendation updates with ResourceId
  src/Advisor/Advisor.Test/ScenarioTests/EnableAzAdvisorRecommendation.ps1
  src/Advisor/Advisor.Test/ScenarioTests/GetAzAdvisorRecommendation.ps1
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.DisableAzAdvisorRecommendation/DisableAzAdvisorRecommendationBadUserInput.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.DisableAzAdvisorRecommendation/DisableAzAdvisorRecommendationByIdParameter.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.DisableAzAdvisorRecommendation/DisableAzAdvisorRecommendationByNameParameter.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.DisableAzAdvisorRecommendation/DisableAzAdvisorRecommendationPipelineScenario.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.EnableAzAdvisorRecommendation/EnableAzAdvisorRecommendationByIdParameterSet.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.EnableAzAdvisorRecommendation/EnableAzAdvisorRecommendationByNameParameterSet.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.EnableAzAdvisorRecommendation/EnableAzAdvisorRecommendationPipeline.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorConfiguration/GetConfigurationQuery.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationByCategory.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationByIdParameterSet.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationByNameParameterSet.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.GetAzAdvisorRecommendation/GetAzAdvisorRecommendationNoParameter.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.SetAzAdvisorConfiguration/SetAzAdvisorConfigurationBadUserInputLowCpu.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.SetAzAdvisorConfiguration/SetAzAdvisorConfigurationByLowCpu.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.SetAzAdvisorConfiguration/SetAzAdvisorConfigurationByLowCpuExclude.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.SetAzAdvisorConfiguration/SetAzAdvisorConfigurationByRg.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.SetAzAdvisorConfiguration/SetAzAdvisorConfigurationByRgExclude.json
  src/Advisor/Advisor.Test/SessionRecords/Microsoft.Azure.Commands.Advisor.Test.ScenarioTests.SetAzAdvisorConfiguration/SetAzAdvisorConfigurationPipelineByLowCpuExclude.json
  src/Advisor/Advisor/Cmdlets/DisableAzAdvisorRecommendation.cs
  src/Advisor/Advisor/Cmdlets/EnableAzAdvisorRecommendation.cs
  src/Advisor/Advisor/Cmdlets/GetAzAdvisorRecommendation.cs
  src/Advisor/Advisor/Cmdlets/Utilities/Client/RecommendationResource.cs
  src/Advisor/Advisor/Cmdlets/Utilities/RecommendationHelper.cs
  src/Advisor/Advisor/help/Disable-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Enable-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Get-AzAdvisorRecommendation.md
Labels: needs-review

#8308 Added NetworkConfigurationDiagnopstic cmdlets and tests
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestNetworkConfigurationDiagnostic.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSEvaluatedNetworkSecurityGroup.cs
  src/Network/Network/Models/PSMatchedRule.cs
  src/Network/Network/Models/PSNetworkConfigurationDiagnosticProfile.cs
  src/Network/Network/Models/PSNetworkConfigurationDiagnosticResponse.cs
  src/Network/Network/Models/PSNetworkConfigurationDiagnosticResult.cs
  src/Network/Network/Models/PSNetworkSecurityGroupResult.cs
  src/Network/Network/Models/PSNetworkSecurityRulesEvaluationResult.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkWatcher/NetworkConfigurationDiagnostic/InvokeNetworkWatcherNetworkConfigurationDiagnosticCommand.cs
  src/Network/Network/NetworkWatcher/NetworkConfigurationDiagnostic/NewAzureNetworkWatcherConfigurationDiagnosticProfileCommand.cs
  src/Network/Network/help/Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic.md
  src/Network/Network/help/New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-review

#8329 Fix typo in AD credential reference documentation
  src/Resources/Resources/help/New-AzADAppCredential.md
  src/Resources/Resources/help/New-AzADSpCredential.md
Labels: Waiting for CI :shipit:

#8333 Fix help generation
  tools/GenerateHelp.ps1
Labels: needs-review

#8337 Fix formatting issue with PSResourceGroupDeployment object
  src/Resources/ResourceManager/SdkExtensions/ResourcesExtensions.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#8310 Add warning message for PS 6 for Uninstall-AzureRm
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/UninstallAzureRm/UninstallAzureRm.cs
  src/Accounts/Accounts/help/Uninstall-AzureRm.md
Labels: needs-review

#8344 Remove incorrect example from Connect-AzAccount.md
  src/Accounts/Accounts/help/Connect-AzAccount.md
Labels: Waiting for CI :shipit:

#8305 Add script to generate Compute images from api spec
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Strategies/ComputeRp/Images.cs
  src/Compute/Compute/Strategies/ComputeRp/Images.json
  src/Compute/Compute/Strategies/ComputeRp/SyncComputeImages.ps1
Labels: needs-review

#8346 Fix a header and some typos
  src/Compute/Compute/help/Update-AzVM.md
Labels: needs-review

#8228 Added support for Python 2 Runbooks
  src/Automation/Automation.Test/ScenarioTests/AutomationTests.cs
  src/Automation/Automation.Test/ScenarioTests/AutomationTests.ps1
  src/Automation/Automation.Test/ScenarioTests/Resources/fastjob.py
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Cmdlet/NewAzureAutomationRunbook.cs
  src/Automation/Automation/Common/AutomationPSClient.cs
  src/Automation/Automation/help/New-AzAutomationRunbook.md
  src/Automation/Automation/help/Start-AzAutomationRunbook.md
Labels: needs-review

#8324 Ado build fix for checkin
  Repo.props
  azure-powershell-linux.yml
  azure-powershell-macOS.yml
  azure-powershell-windows.yml
  build.proj
  build/after.Azure.PowerShell.sln.targets
  build/download-build-steps.yml
  build/install-pwsh-steps.yml
  build/jobs.yml
  documentation/development-docs/azure-powershell-developer-guide.md
  src/Accounts/Accounts/Accounts.csproj
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Automation/Automation.Test/ScenarioTests/CertificateTests.cs
  src/Compute/Compute.Test/ScenarioTests/ResourceSkuTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Kusto/Kusto/Properties/Resources.Designer.cs
  src/Kusto/Kusto/Properties/Resources.resx
  src/Resources/Resources.Test/ScenarioTests/PolicyTests.cs
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage/Storage.csproj
  src/lib/WindowsAzure.Storage/9.3.0/Mono.Posix.NETStandard.dll
  tools/BatchModelGenerator/BatchModelGenerator.csproj
  tools/CheckAssemblies.ps1
  tools/GenerateHelp.ps1
  tools/StaticAnalysis/DependencyAnalyzer/DependencyAnalyzer.cs
  tools/StaticAnalysis/Program.cs
  tools/StaticAnalysis/StaticAnalysis.Netcore.csproj
Labels: needs-review

#8328 Renaming TDE and KeyVaultKey cmdlets from "ManagedInstance" -> "Instance"
  src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.json
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedInstanceKeyVaultKeyTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ManagedInstanceProtectorTests.ps1
  src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/TDECertificateTests.ps1
  src/ResourceManager/Sql/Commands.Sql/Az.Sql.psd1
  src/ResourceManager/Sql/Commands.Sql/ChangeLog.md
  src/ResourceManager/Sql/Commands.Sql/Properties/Resources.resx
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/AddAzureRmSqlManagedInstanceKeyVaultKey.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/AddAzureRmSqlManagedInstanceTransparentDataEncryptionCertificate.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/AzureRmSqlManagedInstanceKeyVaultKeyBase.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/AzureSqlRmManagedInstanceTransparentDataEncryptionProtectorBase.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/GetAzureRmSqlManagedInstanceKeyVaultKey.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/GetAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/RemoveAzureRmSqlManagedInstanceKeyVaultKey.cs
  src/ResourceManager/Sql/Commands.Sql/TransparentDataEncryption/Cmdlet/SetAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
  src/ResourceManager/Sql/Commands.Sql/help/Add-AzSqlInstanceKeyVaultKey.md
  src/ResourceManager/Sql/Commands.Sql/help/Add-AzSqlInstanceTransparentDataEncryptionCertificate.md
  src/ResourceManager/Sql/Commands.Sql/help/Az.Sql.md
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzSqlInstanceKeyVaultKey.md
  src/ResourceManager/Sql/Commands.Sql/help/Get-AzSqlInstanceTransparentDataEncryptionProtector.md
  src/ResourceManager/Sql/Commands.Sql/help/Remove-AzSqlInstanceKeyVaultKey.md
  src/ResourceManager/Sql/Commands.Sql/help/Set-AzSqlInstanceTransparentDataEncryptionProtector.md
Labels: Preview, needs-revision

#8334 Add serialization to IotHubRoutingEndpoint cmdlet
  src/IotHub/IotHub.Test/ScenarioTests/IotHubRoutingTests.ps1
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubRoutingTests/TestAzureIotHubRoutingLifeCycle.json
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/IotHub/Routing/AddAzureRmIotHubRoutingEndpoint.cs
  src/IotHub/IotHub/help/Add-AzIotHubRoutingEndpoint.md
  tools/CredScanSuppressions.json
Labels: needs-revision

#8368 Update recording for conditionally skipped test
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectivityCheck.json
Labels: needs-review

#8320 Add test for Enable/Disable-AzureRmAlias
  src/Accounts/Accounts.Test/AzureRmAliasTests.cs
  src/Accounts/Accounts.Test/AzureRmAliasTests.ps1
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.AzureRmAliasTests/AzureRmAliasCRUD.json
Labels: needs-review

#8372 Add collation parameter to the New-AzSqlInstance command
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstance.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/Constants.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/New-AzSqlInstance.md
Labels: needs-review

#8362 Updating ADF SDK
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Sprint Candidate, Waiting for CI :shipit:

#8321 new property MaxCapacity for ApplicationGatewayAutoscaleConfiguration
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD2.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD3.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDRewriteRuleSet.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDSubItems.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDSubItems2.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableSslOptions.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableWafRuleSets.json
  src/Network/Network/ApplicationGateway/AutoscaleConfiguration/AzureApplicationGatewayAutoscaleConfigurationBase.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSApplicationGatewayAutoscaleConfiguration.cs
  src/Network/Network/help/New-AzApplicationGatewayAutoscaleConfiguration.md
  src/Network/Network/help/Set-AzApplicationGatewayAutoscaleConfiguration.md
Labels: needs-review

#8298 [Storage] Give detail error message when get/set classic Logging/Metric on Premium Storage Account.
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Test/Service/MockStorageBlobManagement.cs
  src/Storage/Storage/Common/Cmdlet/GetAzureStorageServiceLogging.cs
  src/Storage/Storage/Common/Cmdlet/GetAzureStorageServiceMetrics.cs
  src/Storage/Storage/Common/Cmdlet/SetAzureStorageServiceLogging.cs
  src/Storage/Storage/Common/Cmdlet/SetAzureStorageServiceMetrics.cs
  src/Storage/Storage/Model/Contract/IStorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/StorageBlobManagement.cs
Labels: needs-review

#8318 Added Subdomain Parameter to Set-AzureRmIoTCentralApp
  src/IotCentral/IotCentral.Test/ScenarioTests/IotCentralTests.ps1
  src/IotCentral/IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/IotCentral/IotCentral/ChangeLog.md
  src/IotCentral/IotCentral/Common/IotCentralBaseCmdlet.cs
  src/IotCentral/IotCentral/Common/IotCentralUtils.cs
  src/IotCentral/IotCentral/IotCentral/NewAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/IotCentral/SetAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/help/Az.IotCentral.md
  src/IotCentral/IotCentral/help/Get-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/New-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/Remove-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/Set-AzIotCentralApp.md
Labels: Waiting for CI :shipit:

#8366 Few improvements for LicenseType parameter and fix for updating managed instance identity
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/help/New-AzSqlDatabase.md
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
Labels: Waiting for CI :shipit:

#8250 [WebApps] New cmdlet: Publish-AzWebApp
  src/Websites/Websites.Test/ScenarioTests/Common.ps1
  src/Websites/Websites.Test/ScenarioTests/Resources/HelloJava.war
  src/Websites/Websites.Test/ScenarioTests/Resources/nodejs-sample.zip
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.cs
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromWar.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromZip.json
  src/Websites/Websites.Test/Websites.Test.csproj
  src/Websites/Websites/Az.Websites.psd1
  src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
  src/Websites/Websites/help/Az.Websites.md
  src/Websites/Websites/help/Publish-AzWebApp.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#8332 Service Fabric add cert rollback on failure
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/Common.ps1
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/TestServiceFabric.cs
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/TestServiceFabric.ps1
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricApplicationCertificate.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricApplicationCertificateRollback.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricClientCertificate.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricClusterCertificate.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricClusterCertificateCNNotAllowed.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricNode.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricNodeType.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestNewAzureRmServiceFabricCluster.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestNewAzureRmServiceFabricClusterCNCert.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestRemoveAzureRmServiceFabricClientCertificate.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestRemoveAzureRmServiceFabricClusterCertificate.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestRemoveAzureRmServiceFabricClusterCertificateNotAllowed.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestRemoveAzureRmServiceFabricNode.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestRemoveAzureRmServiceFabricNodeType.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestRemoveAzureRmServiceFabricSettings.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestSetAzureRmServiceFabricSettings.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestSetAzureRmServiceFabricUpgradeType.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestUpdateAzureRmServiceFabricDurability.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestUpdateAzureRmServiceFabricReliability.json
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/ServiceFabric/ServiceFabric/Commands/AddAzureRmServiceFabricApplicationCertificate.cs
  src/ServiceFabric/ServiceFabric/Commands/AddAzureRmServiceFabricClusterCertificate.cs
  src/ServiceFabric/ServiceFabric/Commands/AddAzureRmServiceFabricNodeType.cs
  src/ServiceFabric/ServiceFabric/Commands/NewAzureRmServiceFabricCluster.cs
  src/ServiceFabric/ServiceFabric/Commands/RemoveAzureRmServiceFabricNodeType.cs
  src/ServiceFabric/ServiceFabric/Commands/ServiceFabricClusterCertificateCmdlet.cs
  src/ServiceFabric/ServiceFabric/Commands/ServiceFabricClusterCmdlet.cs
  src/ServiceFabric/ServiceFabric/Commands/ServiceFabricCmdletBase.cs
  src/ServiceFabric/ServiceFabric/Commands/UpdateAzureRmServiceFabricDurability.cs
  src/ServiceFabric/ServiceFabric/Common/Constants.cs
  src/ServiceFabric/ServiceFabric/Properties/Resources.Designer.cs
  src/ServiceFabric/ServiceFabric/Properties/Resources.resx
  src/ServiceFabric/ServiceFabric/ServiceFabric.csproj
Labels: Sprint Candidate, Waiting for CI :shipit:

#8380 Update RouteTable docs
  src/Network/Network/help/Set-AzRouteTable.md
Labels: needs-review

#8342 Resolve path provided to -TemplateFile parameter for RG deployment cmdlets
  src/Resources/ResourceManager/Implementation/CmdletBase/ResourceWithParameterCmdletBase.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/TestAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentFromNonexistentTemplateFile.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentFromNonexistentTemplateParameterFile.json
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#8379 [Azure Stack] Update Azs.Fabric.Admin Module to v0.4.0 for deprecations
  src/StackAdmin/Azs.Fabric.Admin/Help/Azs.Fabric.Admin.md
  src/StackAdmin/Azs.Fabric.Admin/Help/Get-AzsInfrastructureVolume.md
  src/StackAdmin/Azs.Fabric.Admin/Help/Get-AzsStoragePool.md
  src/StackAdmin/Azs.Fabric.Admin/Help/Get-AzsStorageSystem.md
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/ChangeLog.md
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsInfrastructureVolume.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsStoragePool.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsStorageSystem.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsVolume.ps1
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetAllStoragePools.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetAllStorageSystems.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetStoragePool.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestGetStorageSystem.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestListStoragePools.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/SessionRecords/FabricAdminClient/TestListStorageSystems.json
  src/StackAdmin/Azs.Fabric.Admin/Tests/src/StoragePool.tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/Tests/src/StorageSystem.tests.ps1
  src/StackAdmin/AzureStack/AzureStack.psd1
Labels: Azure Stack, needs-review

#8378 [Compute] Add ProvisionAfterExtension parameter to Add-AzVmssExtension
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetProfileTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssExtensionCommand.cs
  src/Compute/Compute/help/Add-AzVmssExtension.md
Labels: Waiting for CI :shipit:

#8395 Bump Network SDK version to 19.8.1
  src/Compute/Compute.Test/Compute.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network/Network.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
Labels: needs-review

#8396 Add missing descriptions and examples. Fixes #7011
  src/Network/Network/help/Add-AzApplicationGatewayAuthenticationCertificate.md
  src/Network/Network/help/Add-AzApplicationGatewayIPConfiguration.md
  src/Network/Network/help/Add-AzApplicationGatewayUrlPathMapConfig.md
  src/Network/Network/help/Add-AzLoadBalancerInboundNatPoolConfig.md
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/Get-AzApplicationGatewayAuthenticationCertificate.md
  src/Network/Network/help/Get-AzApplicationGatewayBackendAddressPool.md
  src/Network/Network/help/Get-AzLoadBalancerInboundNatPoolConfig.md
  src/Network/Network/help/New-AzApplicationGatewayAuthenticationCertificate.md
  src/Network/Network/help/New-AzLoadBalancerInboundNatPoolConfig.md
  src/Network/Network/help/Remove-AzApplicationGatewayAuthenticationCertificate.md
  src/Network/Network/help/Remove-AzApplicationGatewayUrlPathMapConfig.md
  src/Network/Network/help/Remove-AzLoadBalancerInboundNatPoolConfig.md
  src/Network/Network/help/Set-AzApplicationGatewayAuthenticationCertificate.md
  src/Network/Network/help/Set-AzApplicationGatewayUrlPathMapConfig.md
  src/Network/Network/help/Set-AzLoadBalancerInboundNatPoolConfig.md
Labels: needs-review

#8383 Update Add-AzLoadBalancerRuleConfig.md to make documentation more clear
  src/Network/Network/help/Add-AzLoadBalancerRuleConfig.md
Labels: needs-review

#8376 [SQL] Port SqlDatabaseBackupShortTermRetentionPolicy preview cmdlets to master
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestShortTermRetentionPolicy.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/AzureSqlDatabaseBackupShortTermRetentionPolicyCmdletBase.cs
  src/Sql/Sql/Database Backup/Cmdlet/GetAzureRmSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Cmdlet/SetAzureRmSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseBackupShortTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupCommunicator.cs
  src/Sql/Sql/help/Get-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  src/Sql/Sql/help/Set-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  tools/StaticAnalysis/Exceptions/Az.Sql/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#8304 Updating versions and release notes for AzureRM 2.4.0 and AzureStack 1.7.0 release
  src/StackAdmin/Azs.AzureBridge.Admin/Module/Azs.AzureBridge.Admin/Azs.Azurebridge.Admin.psd1
  src/StackAdmin/Azs.Backup.Admin/Module/Azs.Backup.Admin/Azs.Backup.Admin.psd1
  src/StackAdmin/Azs.Commerce.Admin/Module/Azs.Commerce.Admin/Azs.Commerce.Admin.psd1
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Azs.Compute.Admin.psd1
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/ChangeLog.md
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Add-AzsVMExtension.ps1
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsPlatformImage.ps1
  src/StackAdmin/Azs.Compute.Admin/Module/Azs.Compute.Admin/Generated.PowerShell.Commands/SwaggerPathCommands/Get-AzsVMExtension.ps1
  src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/Azs.Fabric.Admin.psd1
  src/StackAdmin/Azs.Gallery.Admin/Module/Azs.Gallery.Admin/Azs.Gallery.Admin.psd1
  src/StackAdmin/Azs.InfrastructureInsights.Admin/Module/Azs.InfrastructureInsights.Admin/Azs.Infrastructureinsights.Admin.psd1
  src/StackAdmin/Azs.KeyVault.Admin/Module/Azs.KeyVault.Admin/Azs.Keyvault.Admin.psd1
  src/StackAdmin/Azs.Network.Admin/Module/Azs.Network.Admin/Azs.Network.Admin.psd1
  src/StackAdmin/Azs.Storage.Admin/Module/Azs.Storage.Admin/Azs.Storage.Admin.psd1
  src/StackAdmin/Azs.Subscriptions.Admin/Module/Azs.Subscriptions.Admin/Azs.Subscriptions.Admin.psd1
  src/StackAdmin/Azs.Subscriptions/Module/Azs.Subscriptions/Azs.Subscriptions.psd1
  src/StackAdmin/Azs.Update.Admin/Module/Azs.Update.Admin/Azs.Update.Admin.psd1
  src/StackAdmin/AzureRM/AzureRM.psd1
  src/StackAdmin/AzureStack/AzureStack.psd1
  src/StackAdmin/Dns/Commands.Dns/AzureRM.Dns.psd1
  src/StackAdmin/Network/Commands.Network/AzureRM.Network.psd1
  src/StackAdmin/Resources/Commands.Resources/AzureRM.Resources.psd1
  src/StackAdmin/Storage.Management/Commands.Management.Storage/AzureRM.Storage.psd1
Labels: Azure Stack

#8428 Fix Compute help description
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/Set-AzVMBootDiagnostics.md
Labels: needs-review

#8431 Replace "goal state" in Network help with clearer messages
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/Set-AzApplicationGatewayIPConfiguration.md
  src/Network/Network/help/Set-AzApplicationGatewaySslCertificate.md
  src/Network/Network/help/Set-AzExpressRouteConnection.md
  src/Network/Network/help/Set-AzLoadBalancer.md
  src/Network/Network/help/Set-AzLoadBalancerFrontendIpConfig.md
  src/Network/Network/help/Set-AzLoadBalancerProbeConfig.md
  src/Network/Network/help/Set-AzLoadBalancerRuleConfig.md
  src/Network/Network/help/Set-AzNetworkInterface.md
  src/Network/Network/help/Set-AzNetworkInterfaceIpConfig.md
  src/Network/Network/help/Set-AzNetworkInterfaceTapConfig.md
  src/Network/Network/help/Set-AzNetworkProfile.md
  src/Network/Network/help/Set-AzNetworkSecurityGroup.md
  src/Network/Network/help/Set-AzNetworkSecurityRuleConfig.md
  src/Network/Network/help/Set-AzPublicIpAddress.md
  src/Network/Network/help/Set-AzRouteConfig.md
  src/Network/Network/help/Set-AzRouteTable.md
  src/Network/Network/help/Set-AzVirtualNetwork.md
  src/Network/Network/help/Set-AzVirtualNetworkGateway.md
  src/Network/Network/help/Set-AzVirtualNetworkSubnetConfig.md
  src/Network/Network/help/Set-AzVirtualNetworkTap.md
  src/Network/Network/help/Update-AzVirtualHub.md
  src/Network/Network/help/Update-AzVpnConnection.md
  src/Network/Network/help/Update-AzVpnGateway.md
  src/Network/Network/help/Update-AzVpnSite.md
Labels: needs-review

#8392 Add test coverage for Get-AzureRmSubscription list call
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts/Subscription/GetAzureRMSubscription.cs
Labels: needs-review

#8433 Fix incorrect value for -RegenerationPeriod parameter in example
  src/KeyVault/KeyVault/help/Set-AzKeyVaultManagedStorageSasDefinition.md
Labels: needs-review

#8377 Update ClientRuntime and TestFramework
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.Test.targets
  tools/Common.Netcore.Dependencies.targets
  tools/LocalFeed/Microsoft.Azure.Test.HttpRecorder.1.14.1.nupkg
  tools/LocalFeed/Microsoft.Azure.Test.HttpRecorder.1.14.1.symbols.nupkg
  tools/LocalFeed/Microsoft.Rest.ClientRuntime.Azure.TestFramework.1.8.1.nupkg
  tools/LocalFeed/Microsoft.Rest.ClientRuntime.Azure.TestFramework.1.8.1.symbols.nupkg
  tools/RepoTasks/RepoTasks.CmdletsForTest/RepoTasks.CmdletsForTest.csproj
  tools/RepoTasks/RepoTasks.CmdletsForTest/packages.config
  tools/RepoTasks/RepoTasks.RemoteWorker/RepoTasks.RemoteWorker.csproj
  tools/RepoTasks/RepoTasks.RemoteWorker/packages.config
  tools/StaticAnalysis/StaticAnalysis.csproj
  tools/StaticAnalysis/packages.config
Labels: needs-review

#8438 Fix the example
  src/Compute/Compute/help/Invoke-AzVMReimage.md
Labels: Waiting for CI :shipit:

#8442 Fix the header and some typos
  src/Compute/Compute/help/Get-AzVMRunCommandDocument.md
Labels: needs-review

#8441 Fix the header, example, and some typos
  src/Compute/Compute/help/Invoke-AzVMRunCommand.md
Labels: needs-review

#8404 Fix versioncontroller: https://github.com/Azure/azure-powershell/issues/8397
  build.proj
  tools/RunVersionController.ps1
  tools/UpdateAz.ps1
Labels: Waiting for CI :shipit:

#8393 Fix Set-AzResourceGroup
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/ResourceManager/SdkExtensions/ResourcesExtensions.cs
  src/Resources/ResourceManager/SdkModels/ResourceGroups/PSResourceGroup.cs
  src/Resources/Resources.Test/ResourceGroups/SetAzureResourceGroupCommandTests.cs
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests/TestUpdatesExistingResourceGroup.json
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#8449 Correct example cmdlet in README.md from AzureRm to Az
  README.md
Labels: Waiting for CI :shipit:

#8448 Update HttpRecorder to 1.13.3
  tools/Common.Netcore.Dependencies.Test.targets
  tools/Common.Netcore.Dependencies.targets
  tools/LocalFeed/Microsoft.Azure.Test.Framework.3.0.0.nupkg
  tools/RepoTasks/RepoTasks.CmdletsForTest/RepoTasks.CmdletsForTest.csproj
  tools/RepoTasks/RepoTasks.CmdletsForTest/packages.config
  tools/RepoTasks/RepoTasks.RemoteWorker/RepoTasks.RemoteWorker.csproj
  tools/RepoTasks/RepoTasks.RemoteWorker/packages.config
  tools/StaticAnalysis/StaticAnalysis.csproj
  tools/StaticAnalysis/packages.config
Labels: Waiting for CI :shipit:
