Repository Azure/azure-powershell, pull requests merged in 2020-08, with the labels that each got.

#12462 Introducing Az.Security AdaptiveNetworkHardening cmdlets
  src/Security/Security.Test/ScenarioTests/SecurityAdaptiveNetworkHardeningTests.cs
  src/Security/Security.Test/ScenarioTests/SecurityAdaptiveNetworkHardeningTests.ps1
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityAdaptiveNetworkHardeningTests/GetSingleAdaptiveNetworkHardeningResource.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityAdaptiveNetworkHardeningTests/ListByExtendedResource.json
  src/Security/Security/Az.Security.psd1
  src/Security/Security/ChangeLog.md
  src/Security/Security/Cmdlets/AdaptiveNetworkHardening/AddAdaptiveNetworkHardening.cs
  src/Security/Security/Cmdlets/AdaptiveNetworkHardening/GetAdaptiveNetworkHardening.cs
  src/Security/Security/Common/ParameterHelpMessages.cs
  src/Security/Security/Models/AdaptiveNetworkHardenings/PSSecurityAdaptiveNetworkHardening.cs
  src/Security/Security/Models/AdaptiveNetworkHardenings/PSSecurityAdaptiveNetworkHardeningConverters.cs
  src/Security/Security/Models/AdaptiveNetworkHardenings/PSSecurityAdaptiveNetworkHardeningEffectiveNetworkSecurityGroups.cs
  src/Security/Security/Models/AdaptiveNetworkHardenings/PSSecurityAdaptiveNetworkHardeningProperties.cs
  src/Security/Security/Models/AdaptiveNetworkHardenings/PSSecurityAdaptiveNetworkHardeningRule.cs
  src/Security/Security/help/Add-AzSecurityAdaptiveNetworkHardening.md
  src/Security/Security/help/Get-AzSecurityAdaptiveNetworkHardening.md
Labels: needs-revision

#12497 [Storage] Fix some test cases - preview
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
Labels: Waiting for CI :shipit:, needs-review

#12536 Update Get-AzCosmosDBMongoDBCollection.md
  src/CosmosDB/CosmosDB/help/Get-AzCosmosDBMongoDBCollection.md
Labels: Waiting for CI :shipit:, needs-review

#12556 Always publish pipeline artifacts, even if cancelled
  .azure-pipelines/util/publish-artifacts-steps.yml
Labels: needs-review

#12461 Generate Az.Accounts.psm1 and add it as RootModule to Az.Accounts.psd…
  src/Accounts/Accounts/Directory.Build.targets
  tools/AddModulePsm1Dependency.ps1
  tools/PublishModules.ps1
  tools/PublishModules.psm1
  tools/UpdateModules.ps1
  tools/UpdateModules.psm1
Labels: needs-review

#12554 [Compute] HostGroup: add InstanceView parameter to Get-AzHostGroup
  src/Compute/Compute.Test/ScenarioTests/DedicatedHostTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DedicatedHostTests/TestDedicatedHost.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DedicatedHostTests/TestDedicatedHostVirtualMachine.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/DedicatedHostGroup/DedicatedHostGroupGetMethod.cs
  src/Compute/Compute/Generated/Models/PSHostGroupInstanceView.cs
  src/Compute/Compute/help/Get-AzHostGroup.md
Labels: needs-review

#12545 Az.DataFactory: Add missing properties to PSPipelineRun class
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Models/PSPipelineRun.cs
Labels: needs-review

#12514 Encryption at host param
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetNewEncryptionAtHost.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestEncryptionAtHostVM.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestEncryptionAtHostVMDefaultParameterSet.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Manual/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Manual/PSVirtualMachineScaleSetVMProfile.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Models/PSVirtualMachine.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Update-AzVM.md
  src/Compute/Compute/help/Update-AzVmss.md
Labels: needs-revision

#12557 Fix the issue of type and description
  tools/GenerateInMemoryCreator.ps1
Labels: needs-review

#12299 Upgrade assembly versions
  .azure-pipelines/daily-build.yml
  .azure-pipelines/powershell-core.yml
  .azure-pipelines/util/test-steps.yml
  tools/Common.Netcore.Dependencies.Test.targets
  tools/VersionController/VersionController.Netcore.csproj
  tools/VersionController/packages.config
Labels: needs-review

#12531 Fix some MySQL issues
  src/MariaDb/examples/Get-AzMariaDbReplica.md
  src/MySql/custom/New-AzMySqlServer.ps1
  src/MySql/custom/Update-AzMySqlServer.ps1
  src/MySql/docs/Get-AzMySqlReplica.md
  src/MySql/docs/Get-AzMySqlServer.md
  src/MySql/docs/New-AzMySqlReplica.md
  src/MySql/docs/New-AzMySqlServer.md
  src/MySql/docs/Restore-AzMySqlServer.md
  src/MySql/docs/Update-AzMySqlServer.md
  src/MySql/examples/Get-AzMySqlReplica.md
  src/MySql/examples/Get-AzMySqlServer.md
  src/MySql/examples/New-AzMySqlReplica.md
  src/MySql/examples/New-AzMySqlServer.md
  src/MySql/examples/Restore-AzMySqlServer.md
  src/MySql/examples/Update-AzMySqlServer.md
  src/MySql/readme.md
Labels: Generator, needs-review

#12568 Update test cases and skip sleep during test
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Resources/Resources.Test/ScenarioTests/InvokeResourceActionTests.ps1
  src/Resources/Resources.Test/ScenarioTests/ResourceTests.ps1
Labels: needs-review

#12584 Fix an issue causing Az.psm1 not to generate
  tools/UpdateModules.ps1
  tools/UpdateModules.psm1
Labels: needs-review

#12569 Add PSAzureSubscriptionPolicy for PSAzureSubScription.
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.SubscriptionCmdletTests/AllParameterSetsSucceed.json
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.ps1
  src/Accounts/Accounts.Test/UnitTest/PSAzureSubscriptionTest.cs
  src/Accounts/Accounts/Accounts.format.ps1xml
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication.ResourceManager/Models/PSAzureSubscription.cs
  src/Accounts/Authentication.ResourceManager/Models/PSAzureSubscriptionPolicy.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#12575 Enable MHSM Management via *-AzKeyVault
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/GetAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/KeyVaultManagementCmdletBase.cs
  src/KeyVault/KeyVault/Models/ModelExtensions.cs
  src/KeyVault/KeyVault/Models/PSKeyVault.cs
  src/KeyVault/KeyVault/Models/PSManagedHsm.cs
  src/KeyVault/KeyVault/Models/VaultCreationParameters.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/help/Get-AzKeyVault.md
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVault.md
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
  tools/LocalFeed/microsoft.azure.management.keyvault.3.0.1.nupkg
Labels: needs-review

#12537 [Storage] Support blob query acceleration
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobQueryResult.md
  src/Storage/Storage.Management/help/New-AzStorageBlobQueryConfig.md
  src/Storage/Storage.Test/Service/MockStorageBlobManagement.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzStorageBlobQueryResult.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzStorageBlobQueryConfig .cs
  src/Storage/Storage/Common/BlobQueryTextConfiguration.cs
  src/Storage/Storage/Model/Contract/IStorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/StorageBlobManagement.cs
  src/Storage/Storage/Storage.csproj
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: Cmdlet Review Complete, Waiting for CI :shipit:

#12585 Fix issue in example of HanaOnAzure
  src/HanaOnAzure/docs/New-AzSapMonitor.md
  src/HanaOnAzure/examples/New-AzSapMonitor.md
Labels: needs-review

#12603 [Storage] Support Track2 blob container Access Policy
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Common/AccessPolicyHelper.cs
  src/Storage/Storage/File/Cmdlet/GetAzureStorageShareStoredAccessPolicy.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageShareStoredAccessPolicy.cs
  src/Storage/Storage/Queue/Cmdlet/GetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Queue/Cmdlet/SetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/GetAzureStorageTableStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/SetAzureStorageTableStoredAccessPolicy.cs
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: needs-review

#12607 Added breaking change attribute to GetAzureResourceGroupDeploymentOperationCmdlet
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentOperationCmdlet.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#12617 [Storage] Fixed [#12592]: Fix download blob fail when related sub directory not exist.
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobContent.cs
Labels: needs-review

#12618 Show "NotPolice" legal terms for Face.
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/CognitiveServices/CognitiveServices/CognitiveServices.csproj
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/Properties/Resources.Designer.cs
  src/CognitiveServices/CognitiveServices/Properties/Resources.resx
Labels: needs-review

#12624 Use release binaries for bumping version
  tools/RunVersionController.ps1
  tools/VersionController/Models/VersionFileHelper.cs
  tools/VersionController/Program.cs
Labels: needs-review

#12572 Az.IoTCentral - Allow updating application pricing information using Set-AzIotCentralApp command
  src/IotCentral/IotCentral.Test/IotCentral.Test.csproj
  src/IotCentral/IotCentral.Test/ScenarioTests/IotCentralTests.ps1
  src/IotCentral/IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/IotCentral/IotCentral/ChangeLog.md
  src/IotCentral/IotCentral/IotCentral.csproj
  src/IotCentral/IotCentral/IotCentral/SetAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/help/Get-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/New-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/Remove-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/Set-AzIotCentralApp.md
Labels: needs-revision

#12589 Aladdin generated examples for CosmosDB
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBAccountKey.md
  src/CosmosDB/CosmosDB/help/Update-AzCosmosDBSqlContainerThroughput.md
  src/CosmosDB/CosmosDB/help/Update-AzCosmosDBSqlDatabase.md
Labels: Waiting for CI :shipit:

#12570 Update role assignment cmdlet
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Resources/Resources.Test/ScenarioTests/RoleAssignmentTests.cs
  src/Resources/Resources.Test/ScenarioTests/RoleAssignmentTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaWithV2Conditions.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaWithV2ConditionsOnly.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/UpdateRa.json
  src/Resources/Resources/ActiveDirectory/Models/ParameterSet.cs
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Models.Authorization/AuthorizationClient.cs
  src/Resources/Resources/Models.Authorization/FilterRoleAssignmentsOptions.cs
  src/Resources/Resources/Properties/Resources.Designer.cs
  src/Resources/Resources/Properties/Resources.resx
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/SetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/help/Az.Resources.md
  src/Resources/Resources/help/New-AzADServicePrincipal.md
  src/Resources/Resources/help/New-AzRoleAssignment.md
  src/Resources/Resources/help/Remove-AzDeploymentScript.md
  src/Resources/Resources/help/Remove-AzTag.md
  src/Resources/Resources/help/Remove-AzTenantDeployment.md
  src/Resources/Resources/help/Set-AzRoleAssignment.md
  src/Resources/Resources/help/Test-AzManagementGroupDeployment.md
  src/Resources/Resources/help/Update-AzTag.md
Labels: needs-revision

#12609 Wrong variable in the 'Example 2'
  src/Databricks/help/New-AzDatabricksWorkspace.md
Labels: Waiting for CI :shipit:

#12601 Fix Issue New-AzStorageSyncCloudEndpoint across subscriptions failing…
  src/StorageSync/StorageSync/CloudEndpoint/NewCloudEndpointCommand.cs
  src/StorageSync/StorageSync/Common/StorageSyncClientWrapper.cs
  src/StorageSync/StorageSync/Interfaces/IStorageSyncClientWrapper.cs
Labels: needs-revision

#12631 Record scenario test for Managed Hsm
  src/Compute/Compute.Test/Compute.Test.csproj
  src/EventHub/EventHub.Test/EventHub.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
  src/KeyVault/KeyVault.Test/ScenarioTests/ManagedHsmManagementTests.cs
  src/KeyVault/KeyVault.Test/ScenarioTests/ManagedHsmManagementTests.ps1
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestDeleteVault.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestGetVault.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestListVaults.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.ManagedHsmManagementTests/TestManagedHsmCRUD.json
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/Models/PSManagedHsm.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVault.md
  src/Sql/Sql.Test/Sql.Test.csproj
  tools/LocalFeed/Microsoft.Azure.Management.KeyVault.3.1.0-preview.1.nupkg
  tools/LocalFeed/microsoft.azure.management.keyvault.3.0.1.nupkg
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review

#12629 Add note to KeyVault docs Set-AzKeyVaultAccessPolicy.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultAccessPolicy.md
Labels: Waiting for CI :shipit:

#12622 Fixed the Address/Ip Typo
  src/Synapse/Synapse/help/New-AzSynapseFirewallRule.md
Labels: Waiting for CI :shipit:

#12632 [Storage] Fix some help issue
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Add-AzRmStorageContainerLegalHold.md
  src/Storage/Storage.Management/help/Add-AzStorageAccountNetworkRule.md
  src/Storage/Storage.Management/help/Close-AzStorageFileHandle.md
  src/Storage/Storage.Management/help/Disable-AzStorageDeleteRetentionPolicy.md
  src/Storage/Storage.Management/help/Disable-AzStorageStaticWebsite.md
  src/Storage/Storage.Management/help/Enable-AzStorageDeleteRetentionPolicy.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Get-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Get-AzStorageAccount.md
  src/Storage/Storage.Management/help/Get-AzStorageAccountNameAvailability.md
  src/Storage/Storage.Management/help/Get-AzStorageAccountNetworkRuleSet.md
  src/Storage/Storage.Management/help/Get-AzStorageBlob.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobServiceProperty.md
  src/Storage/Storage.Management/help/Get-AzStorageFile.md
  src/Storage/Storage.Management/help/Get-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Get-AzStorageFileCopyState.md
  src/Storage/Storage.Management/help/Get-AzStorageFileHandle.md
  src/Storage/Storage.Management/help/Get-AzStorageQueue.md
  src/Storage/Storage.Management/help/Get-AzStorageQueueStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Get-AzStorageServiceLoggingProperty.md
  src/Storage/Storage.Management/help/Get-AzStorageServiceMetricsProperty.md
  src/Storage/Storage.Management/help/Get-AzStorageServiceProperty.md
  src/Storage/Storage.Management/help/Get-AzStorageTable.md
  src/Storage/Storage.Management/help/Get-AzStorageTableStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Get-AzStorageUsage.md
  src/Storage/Storage.Management/help/Lock-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/New-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/New-AzStorageDirectory.md
  src/Storage/Storage.Management/help/New-AzStorageFileSASToken.md
  src/Storage/Storage.Management/help/New-AzStorageQueue.md
  src/Storage/Storage.Management/help/New-AzStorageQueueStoredAccessPolicy.md
  src/Storage/Storage.Management/help/New-AzStorageTable.md
  src/Storage/Storage.Management/help/New-AzStorageTableStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainerLegalHold.md
  src/Storage/Storage.Management/help/Remove-AzStorageAccount.md
  src/Storage/Storage.Management/help/Remove-AzStorageAccountNetworkRule.md
  src/Storage/Storage.Management/help/Remove-AzStorageBlob.md
  src/Storage/Storage.Management/help/Remove-AzStorageDirectory.md
  src/Storage/Storage.Management/help/Remove-AzStorageFile.md
  src/Storage/Storage.Management/help/Remove-AzStorageQueue.md
  src/Storage/Storage.Management/help/Remove-AzStorageQueueStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Remove-AzStorageShare.md
  src/Storage/Storage.Management/help/Remove-AzStorageTable.md
  src/Storage/Storage.Management/help/Remove-AzStorageTableStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Set-AzCurrentStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Set-AzStorageQueueStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageServiceLoggingProperty.md
  src/Storage/Storage.Management/help/Set-AzStorageServiceMetricsProperty.md
  src/Storage/Storage.Management/help/Set-AzStorageShareQuota.md
  src/Storage/Storage.Management/help/Set-AzStorageTableStoredAccessPolicy.md
  src/Storage/Storage.Management/help/Start-AzStorageBlobCopy.md
  src/Storage/Storage.Management/help/Start-AzStorageFileCopy.md
  src/Storage/Storage.Management/help/Stop-AzStorageFileCopy.md
  src/Storage/Storage.Management/help/Update-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/Update-AzStorageAccountNetworkRuleSet.md
  src/Storage/Storage.Management/help/Update-AzStorageServiceProperty.md
Labels: needs-review

#12638 Add AllowAll to New-AzMySqlFirewallRule
  src/MySql/custom/New-AzMySqlFirewallRule.ps1
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/New-AzMySqlFirewallRule.md
  src/MySql/examples/New-AzMySqlFirewallRule.md
  src/MySql/test/Az.MySql-TestResults.xml
  src/MySql/test/New-AzMySqlFirewallRule.Recording.json
  src/MySql/test/New-AzMySqlFirewallRule.Tests.ps1
Labels: needs-review

#12454 authenticate token each time client is sending request
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Authentication/Authentication/ExternalAccessToken.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
Labels: Waiting for CI :shipit:

#12614 Bug fix- when getting metric alert from pipeline, the actions are del…
  src/Monitor/Monitor.Test/Alerts/AddAzureRmMetricAlertRuleV2Tests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.ps1
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestAddAzureRmMetricAlertRuleV2WithActionGroupId.json
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestDisableAzureRmMetricAlertRuleV2WithActionGroups.json
  src/Monitor/Monitor/Alerts/AddAzureRmMetricAlertRuleV2Command.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/help/Add-AzMetricAlertRuleV2.md
Labels: needs-revision

#12650 Support installer on .NET Framework 4.x
  setup/InstallerChecks.CA.dll
  setup/InstallerChecks/InstallerChecks/CustomAction.config
  setup/InstallerChecks/InstallerChecks/InstallerChecks.csproj
Labels: needs-review

#12620 preload newtonsoft.json 12.0.3
  src/lib/NetFxPreloadAssemblies/Newtonsoft.Json.12.0.3.dll
Labels: needs-review, needs-revision

#12652 Adding CPlat SDK PowerShell team as Code owners
  .github/CODEOWNERS
Labels: needs-review

#12639 [Storage] Force overwrite Query result file
  src/Storage/Storage.Management/help/Get-AzStorageBlobQueryResult.md
  src/Storage/Storage/Blob/Cmdlet/GetAzStorageBlobQueryResult.cs
Labels: needs-review

#12656 Updated Az.Resources .NET SDK reference to 3.10.0-preview
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/PolicyAliasTests.cs
  src/Resources/Resources.Test/ScenarioTests/ProviderListBuilder.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Tags/Tags.csproj
Labels: needs-review

#12661 Correct ImageBuilder MonitoringSolutions cmdlet and doc mapping
  tools/CreateMappings_rules.json
Labels: Waiting for CI :shipit:

#12662 Remove log4net lib
  tools/StaticAnalysis/Properties/AssemblyInfo.cs
  tools/Tools.Common/Loggers/AnalysisLogger.cs
  tools/Tools.Common/Properties/AssemblyInfo.cs
  tools/Tools.Common/Tools.Common.Netcore.csproj
Labels: needs-review

#12658 New cmdlet Invoke-AzVmPatchAssessment
  src/Compute/Compute.Test/ScenarioTests/ComputeTestCommon.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachinePatchTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachinePatchTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachinePatchTests/TestInvokeAzVmPatchAssessment.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Generated/VirtualMachine/InvokeAzureVMPatchAssessmentCommand.cs
  src/Compute/Compute/Manual/PSVirtualMachinePatchAssessmentResult.cs
  src/Compute/Compute/help/Az.Compute.md
  src/Compute/Compute/help/Invoke-AzVmPatchAssessment.md
Labels: needs-revision

#12651 [Storage] support set/update/remove acl recursive on DatalakeGen2 item
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Remove-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage.Management/help/Set-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage.Management/help/Update-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage/Blob/Cmdlet/GetAzStorageBlobTag.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobByTag.cs
  src/Storage/Storage/Common/AzureDataLakeGen2Item.cs
  src/Storage/Storage/Common/AzureStorageBlob.cs
  src/Storage/Storage/Common/BlobQueryTextConfiguration.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/DataLakeGen2ACLRecursiveBaseCmdlet.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RemoveAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/SetAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2Item.cs
  src/Storage/Storage/Model/ResourceModel/PSACLRecursiveChangeResult.cs
  src/Storage/Storage/Model/ResourceModel/PSPathAccessControl.cs
  src/Storage/Storage/Storage.csproj
  tools/LocalFeed/azure.storage.blobs.12.5.0-dev.20200811.1.nupkg
  tools/LocalFeed/azure.storage.common.12.5.0-dev.20200811.1.nupkg
  tools/LocalFeed/azure.storage.files.datalake.12.3.0-dev.20200811.1.nupkg
Labels: needs-review

#12668 [Storage] Support ORS - GA
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobORS.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/Blob/UpdateAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSObjectReplicationPolicy.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/GetAzStorageObjectReplicationPolicy.cs
  src/Storage/Storage.Management/StorageAccount/NewAzStorageObjectReplicationPolicyRule.cs
  src/Storage/Storage.Management/StorageAccount/RemoveAzStorageObjectReplicationPolicy.cs
  src/Storage/Storage.Management/StorageAccount/SetAzStorageObjectReplicationPolicy.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzStorageObjectReplicationPolicy.md
  src/Storage/Storage.Management/help/New-AzStorageObjectReplicationPolicyRule.md
  src/Storage/Storage.Management/help/Remove-AzStorageObjectReplicationPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageObjectReplicationPolicy.md
  src/Storage/Storage.Management/help/Update-AzStorageBlobServiceProperty.md
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: needs-review

#12670 [Synapse] - Support ShouldProcess for 3 cmdlets
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkJob/SubmitAzureSynapseSparkJob.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkSession/StartAzureSynapseSparkSession.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkStatement/InvokeAzureSynapseSparkStatement.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Invoke-AzSynapseSparkStatement.md
  src/Synapse/Synapse/help/Start-AzSynapseSparkSession.md
  src/Synapse/Synapse/help/Submit-AzSynapseSparkJob.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/SignatureIssues.csv
Labels: Waiting for CI :shipit:, needs-review

#12671 [HDInsight]Support creating cluster with encryption at host.
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HDInsight/HDInsight.Test/ScenarioTests/HDInsightClusterTests.cs
  src/HDInsight/HDInsight.Test/ScenarioTests/HDInsightClusterTests.ps1
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCreateClusterWithEncryptionAtHost.json
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/HDInsight.csproj
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterConfigCommand.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightConfig.cs
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
  src/HDInsight/HDInsight/help/New-AzHDInsightClusterConfig.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#12647 [Synapse] Add integration runtime management cmdlets
  src/Synapse/Synapse.Test/ScenarioTests/IntegrationRuntimeTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestAzureIntegrationRuntime.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestIntegrationRuntimePiping.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestSelfHostedIntegrationRuntime.json
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/GetAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/GetAzureSynapseIntegrationRuntimeKey.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/GetAzureSynapseIntegrationRuntimeMetric.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/GetAzureSynapseIntegrationRuntimeNode.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/InvokeAzureSynapseIntegrationRuntimeUpgrade.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/NewAzureSynapseIntegrationRuntimeKey.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/RemoveAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/RemoveAzureSynapseIntegrationRuntimeNode.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/SetAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/SyncAzureSynapseIntegrationRuntimeCredential.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/UpdateAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/UpdateAzureSynapseIntegrationRuntimeNode.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Common/ResourceTypes.cs
  src/Synapse/Synapse/Common/Utils.cs
  src/Synapse/Synapse/Models/CreatePSIntegrationRuntimeParameters.cs
  src/Synapse/Synapse/Models/PSIntegrationRuntime.cs
  src/Synapse/Synapse/Models/PSIntegrationRuntimeKeys.cs
  src/Synapse/Synapse/Models/PSIntegrationRuntimeMetrics.cs
  src/Synapse/Synapse/Models/PSLinkedIntegrationRuntime.cs
  src/Synapse/Synapse/Models/PSLinkedIntegrationRuntimeStatus.cs
  src/Synapse/Synapse/Models/PSManagedIntegrationRuntime.cs
  src/Synapse/Synapse/Models/PSManagedIntegrationRuntimeNode.cs
  src/Synapse/Synapse/Models/PSManagedIntegrationRuntimeStatus.cs
  src/Synapse/Synapse/Models/PSSelfHostedIntegrationRuntime.cs
  src/Synapse/Synapse/Models/PSSelfHostedIntegrationRuntimeNode.cs
  src/Synapse/Synapse/Models/PSSelfHostedIntegrationRuntimeStatus.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Models/SynapseEntityFilterOptions.cs
  src/Synapse/Synapse/Models/SynapseManagementCmdletBase.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Get-AzSynapseIntegrationRuntime.md
  src/Synapse/Synapse/help/Get-AzSynapseIntegrationRuntimeKey.md
  src/Synapse/Synapse/help/Get-AzSynapseIntegrationRuntimeMetric.md
  src/Synapse/Synapse/help/Get-AzSynapseIntegrationRuntimeNode.md
  src/Synapse/Synapse/help/Invoke-AzSynapseIntegrationRuntimeUpgrade.md
  src/Synapse/Synapse/help/New-AzSynapseIntegrationRuntimeKey.md
  src/Synapse/Synapse/help/Remove-AzSynapseIntegrationRuntime.md
  src/Synapse/Synapse/help/Remove-AzSynapseIntegrationRuntimeNode.md
  src/Synapse/Synapse/help/Set-AzSynapseIntegrationRuntime.md
  src/Synapse/Synapse/help/Sync-AzSynapseIntegrationRuntimeCredential.md
  src/Synapse/Synapse/help/Update-AzSynapseIntegrationRuntime.md
  src/Synapse/Synapse/help/Update-AzSynapseIntegrationRuntimeNode.md
Labels: needs-review, needs-revision

#12676 [KeyVault]Provide Warning Messages for SecretVaultText
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/GetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/RestoreAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/UndoAzureKeyVaultSecretRemoval.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVaultSecret.cs
Labels: needs-review

#12672 Provide Warning Messages For Azure KeyVault Soft Delete
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultCertificate.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultKey.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
Labels: Waiting for CI :shipit:, needs-review

#12678 Fix secure string conversion
  src/HanaOnAzure/custom/New-AzSapMonitorProviderInstance.ps1
Labels: needs-review

#12667 Adding schedule fields to NewAzMaintenance Configuration cmdlet and new Public Configuration GET cmdlet
  src/Maintenance/Maintenance.Test/Maintenance.Test.csproj
  src/Maintenance/Maintenance.Test/ScenarioTests/MaintenanceTests.cs
  src/Maintenance/Maintenance.Test/ScenarioTests/MaintenanceTests.ps1
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestMaintenanceConfiguration.json
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestPublicMaintenanceConfiguration.json
  src/Maintenance/Maintenance/Az.Maintenance.psd1
  src/Maintenance/Maintenance/ChangeLog.md
  src/Maintenance/Maintenance/Maintenance.csproj
  src/Maintenance/Maintenance/MaintenanceAutomationBaseCmdlet.cs
  src/Maintenance/Maintenance/MaintenanceConfiguration/MaintenanceConfigurationCreateOrUpdateMethod.cs
  src/Maintenance/Maintenance/Models/PSMaintenanceConfiguration.cs
  src/Maintenance/Maintenance/PublicMaintenanceConfiguration/PublicMaintenanceConfigurationGetMethod.cs
  src/Maintenance/Maintenance/help/Az.Maintenance.md
  src/Maintenance/Maintenance/help/Get-AzMaintenancePublicConfiguration.md
  src/Maintenance/Maintenance/help/New-AzMaintenanceConfiguration.md
Labels: Waiting for CI :shipit:

#12677 Added runOn parameter to Set-AzAutomationWebhook
  src/Automation/Automation.Test/UnitTests/SetAzureAutomationWebhookTest.cs
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Cmdlet/SetAzureAutomationWebhook.cs
  src/Automation/Automation/Common/AutomationPSClientWebhook.cs
  src/Automation/Automation/Common/IAutomationPSClient.cs
  src/Automation/Automation/help/Set-AzAutomationWebhook.md
Labels: needs-revision

#12682 Add ClientIpAddress to New/Update-AzMySqlFirewallRule
  src/MySql/custom/New-AzMySqlFirewallRule.ps1
  src/MySql/custom/Update-AzMySqlFirewallRule.ps1
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/New-AzMySqlFirewallRule.md
  src/MySql/docs/Update-AzMySqlFirewallRule.md
  src/MySql/examples/New-AzMySqlFirewallRule.md
  src/MySql/examples/Update-AzMySqlFirewallRule.md
  src/MySql/test/Az.MySql-TestResults.xml
  src/MySql/test/New-AzMySqlFirewallRule.Recording.json
  src/MySql/test/New-AzMySqlFirewallRule.Tests.ps1
  src/MySql/test/Update-AzMySqlFirewallRule.Recording.json
  src/MySql/test/Update-AzMySqlFirewallRule.Tests.ps1
Labels: needs-review

#12683 Add breaking changes warnings in preparation for October 27th milestone PR
  src/ManagedServices/ManagedServices/Commands/GetAzureRmManagedServicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/GetAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Commands/NewAzureRmManagedServicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/NewAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Commands/RemoveAzureRmManagedServcicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/RemoveAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Extensions/ManagedServicesUtility.cs
Labels: needs-revision

#12685 [HanaOnAzure] Fix issue in powershell <7
  src/HanaOnAzure/Az.HanaOnAzure.psd1
  src/HanaOnAzure/ChangeLog.md
  src/HanaOnAzure/custom/New-AzSapMonitorProviderInstance.ps1
  src/HanaOnAzure/examples/New-AzSapMonitor.md
  src/HanaOnAzure/exports/New-AzSapMonitor.ps1
  src/HanaOnAzure/exports/ProxyCmdletDefinitions.ps1
  src/HanaOnAzure/generated/api/Models/Api20161001/Vault.PowerShell.cs
  src/HanaOnAzure/generated/api/Models/Api20161001/VaultCreateOrUpdateParameters.PowerShell.cs
  src/HanaOnAzure/generated/api/Models/Api20161001/VaultPatchParameters.PowerShell.cs
  src/HanaOnAzure/help/New-AzSapMonitor.md
Labels: needs-review

#12686 Polish changelog for release-2020-08-25
  src/Automation/Automation/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/HDInsight/HDInsight/ChangeLog.md
  src/KeyVault/KeyVault/ChangeLog.md
  src/Maintenance/Maintenance/ChangeLog.md
  src/ManagedServices/ManagedServices/ChangeLog.md
  src/Monitor/Monitor/ChangeLog.md
  src/Resources/Resources/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
Labels: Waiting for CI :shipit:

#12689 Added ClientIpAddress Modes to firewall rule cmdlets
  src/MySql/Az.MySql.psd1
  src/MySql/ChangeLog.md
  src/MySql/custom/New-AzMySqlFirewallRule.ps1
  src/MySql/custom/Update-AzMySqlFirewallRule.ps1
  src/MySql/examples/New-AzMySqlFirewallRule.md
  src/MySql/examples/Update-AzMySqlFirewallRule.md
  src/MySql/exports/New-AzMySqlFirewallRule.ps1
  src/MySql/exports/ProxyCmdletDefinitions.ps1
  src/MySql/exports/Update-AzMySqlFirewallRule.ps1
  src/MySql/help/New-AzMySqlFirewallRule.md
  src/MySql/help/Update-AzMySqlFirewallRule.md
  src/MySql/internal/New-AzMySqlFirewallRule.ps1
  src/MySql/internal/ProxyCmdletDefinitions.ps1
  src/MySql/internal/Update-AzMySqlFirewallRule.ps1
  src/MySql/test/Az.MySql-TestResults.xml
  src/MySql/test/New-AzMySqlFirewallRule.Recording.json
  src/MySql/test/New-AzMySqlFirewallRule.Tests.ps1
  src/MySql/test/Update-AzMySqlFirewallRule.Recording.json
  src/MySql/test/Update-AzMySqlFirewallRule.Tests.ps1
Labels: Sprint Candidate, needs-review

#12687 Fix broken link
  src/HanaOnAzure/docs/New-AzSapMonitorProviderInstance.md
Labels: needs-review

#12688 Load and merge all public cloud environments
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#12703 Add breaking change attribute for subscriptionId parameter in Get-AzR…
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentOperationCmdlet.cs
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#12701 Fix typo in New-AzConfigurationAssignment.md
  src/Maintenance/Maintenance/ChangeLog.md
  src/Maintenance/Maintenance/help/New-AzConfigurationAssignment.md
Labels: needs-revision

#12664 Support build/publish one module via TargetModule property
  build.proj
  src/StackHCI/Properties/AssemblyInfo.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/FilesChangedTask.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/FilterTask.cs
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/SetGenerator.cs
  tools/CreateFilterMappings.ps1
  tools/PublishModules.psm1
Labels: needs-review

#12731 Update Set-AzKeyVaultCertificatePolicy.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultCertificatePolicy.md
Labels: Doc - Reference, needs-review

#12733 [DataFactory] Upgrade sdk version to 4.11.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-review

#12727 [Storage] Support Track2 blob container Access Policy
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Common/AccessPolicyHelper.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
  src/Storage/Storage/File/Cmdlet/GetAzureStorageShareStoredAccessPolicy.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageShareStoredAccessPolicy.cs
  src/Storage/Storage/Queue/Cmdlet/GetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Queue/Cmdlet/SetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/GetAzureStorageTableStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/SetAzureStorageTableStoredAccessPolicy.cs
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: needs-review

#12732 [KeyVault] Enhance error handling
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Models/KeyVaultManagementCmdletBase.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
Labels: needs-review

#12723 Add Az.Accounts as required module for psd1 if not exist.
  tools/Gen2Master/MoveFromGeneration2Master.ps1
Labels: needs-review

#12750 Fixed build version
  src/Batch/Batch.Test/Batch.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/HPCCache/HPCCache.Test/HPCCache.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network/Network.csproj
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-review

#12759 Improving default testing of New-AzDiskEncryptionSetConfig EncryptionType param
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskEncryptionSetConfigEncryptionType.json
Labels: needs-review

#12753 Show "NotPolice" legal terms for some of Cognitive Services APIs.
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/CognitiveServices/CognitiveServices/CognitiveServices.csproj
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/Properties/Resources.Designer.cs
  src/CognitiveServices/CognitiveServices/Properties/Resources.resx
Labels: needs-review

#12761 Update Remove-AzManagementGroup.md
  src/Resources/Resources/help/Remove-AzManagementGroup.md
Labels: needs-review

#12769 Ignore Network each time network API upgrade
  src/SignalR/SignalR.Test/TestController.cs
Labels: needs-review

#12770 Release Az.Storage-preview 2.5.2
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/AssemblyInfo.cs
  src/Accounts/Authentication/Properties/AssemblyInfo.cs
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
  src/Storage/Storage/Properties/AssemblyInfo.cs
Labels: needs-review

#12449 Enable internet security feature for VirtualWan P2SVpnGateway client connections and expose Reset operations for VirtualWan P2SVpnGateway & VpnGateway resources.
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestP2SCortexCRUD.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/P2SVpnGateway/NewAzureRmP2sVpnGatewayCommand.cs
  src/Network/Network/Cortex/P2SVpnGateway/ResetAzureP2SVpnGatewayCommand.cs
  src/Network/Network/Cortex/P2SVpnGateway/UpdateAzureRmP2SVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/ResetAzureVpnGatewayCommand.cs
  src/Network/Network/Models/Cortex/PSP2SConnectionConfiguration.cs
  src/Network/Network/help/New-AzP2sVpnGateway.md
  src/Network/Network/help/Reset-AzP2sVpnGateway.md
  src/Network/Network/help/Reset-AzVpnGateway.md
  src/Network/Network/help/Update-AzP2sVpnGateway.md
  src/SignalR/SignalR.Test/ScenarioTests/AzureRmSignalRTests.cs
Labels: needs-review

#12588 Vmss dedicated host
  src/Compute/Compute.Test/ScenarioTests/DedicatedHostTests.ps1
  src/Compute/Compute.Test/ScenarioTests/StrategiesVmssTests.cs
  src/Compute/Compute.Test/ScenarioTests/StrategiesVmssTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DedicatedHostTests/TestDedicatedHost.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DedicatedHostTests/TestDedicatedHostVirtualMachine.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests/TestSimpleNewVmssHostGroup.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetAssignedHost.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestHostGroupPropertySetOnVirtualMachine.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineGetStatusWithAssignedHost.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/DedicatedHostGroup/DedicatedHostGroupCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/DedicatedHostGroup/DedicatedHostGroupGetMethod.cs
  src/Compute/Compute/Generated/Models/PSHostGroup.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineInstanceView.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSetVMInstanceView.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Models/PSVirtualMachine.cs
  src/Compute/Compute/Models/PSVirtualMachineInstanceView.cs
  src/Compute/Compute/Strategies/ComputeRp/DedicatedHostStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/SubResourceStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzHostGroup.md
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVmss.md
Labels: needs-review

#12774 Fix Typo in 'remove-cmdlet-example.md'
  documentation/development-docs/examples/remove-cmdlet-example.md
Labels: needs-review

#12785 [KeyVault] Doc update about SAN certificate
  src/KeyVault/KeyVault/Commands/NewAzureKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/help/New-AzKeyVaultCertificatePolicy.md
Labels: needs-review

#12795 Patch for release 2020 08 25
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestEncryptionAtHostVMNull.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for CI :shipit:

#12789 Add isolated trust model example to the documentation for the Reset_AzAttestationPolicy cmdlet
  src/Attestation/Attestation/help/Reset-AzAttestationPolicy.md
Labels: Waiting for CI :shipit:

#12780 [Resources] Bug fixes for deployment and deployment What-If cmdlets
  src/Resources/ResourceManager/Comparers/ChangeTypeComparer.cs
  src/Resources/ResourceManager/Formatters/PSResourceManagerErrorFormatter.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/ResourceManager/SdkModels/Deployments/PSDeploymentWhatIfCmdletParameters.cs
  src/Resources/Resources.Test/Formatters/WhatIfOperationResultFormatterTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#12798 Ignore PrivateDns module each time it upgrades
  src/SignalR/SignalR.Test/TestController.cs
Labels: needs-review

#12790 Cleanup VMSS OrchestrationMode test and help message
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
Labels: needs-revision

#12704 [Network] Add Cmdlets for BYOIP Feature
  src/Network/Network.Test/NrpTeamAlias.cs
  src/Network/Network.Test/ScenarioTests/CustomIpPrefixTests.cs
  src/Network/Network.Test/ScenarioTests/CustomIpPrefixTests.ps1
  src/Network/Network/Az.Network.psd1
  src/Network/Network/BYOIP/CustomIpPrefix/CustomIpPrefixBaseCmdlet.cs
  src/Network/Network/BYOIP/CustomIpPrefix/GetAzureCustomIpPrefixCommand.cs
  src/Network/Network/BYOIP/CustomIpPrefix/NewAzureCustomIpPrefixCommand.cs
  src/Network/Network/BYOIP/CustomIpPrefix/RemoveAzureCustomIpPrefixCommand.cs
  src/Network/Network/BYOIP/CustomIpPrefix/UpdateAzureCustomIpPrefixCommand.cs
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/BYOIP/PSCustomIpPrefix.cs
  src/Network/Network/Models/PSPublicIpPrefix.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/PublicIpPrefix/NewAzurePublicIpPrefixCommand.cs
  src/Network/Network/help/Get-AzCustomIpPrefix.md
  src/Network/Network/help/New-AzCustomIpPrefix.md
  src/Network/Network/help/Remove-AzCustomIpPrefix.md
  src/Network/Network/help/Update-AzCustomIpPrefix.md
Labels: needs-revision

#12693 [Compute] Vm health field in vm instance view
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/VirtualMachineGetStatusWithHealhtExtension.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/Models/PSVirtualMachineInstanceView.cs
  src/Compute/Compute/Models/PSVirtualMachineInstanceView.cs
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: Waiting for CI :shipit:

#12805 [Resources] Fix array parameter serialization issue
  src/Resources/ResourceManager/Json/PSJsonSerializer.cs
  src/Resources/Resources.Test/Json/PSJsonSerializerTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#12806 Update New-AzResourceLock.md examples (#12225)
  src/Resources/Resources/help/New-AzResourceLock.md
Labels: needs-review

#12809 New packet capture Cmdlet for Network Module: VpnConnection and VpnGateway Resource
  src/Network/Network.Test/ScenarioTests/CortexTests.cs
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestVpnConnectionPacketCapture.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestVpnGatewayPacketCapture.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VpnConnection/StartAzVpnConnectionPacketCaptureCommand.cs
  src/Network/Network/Cortex/VpnConnection/StopAzVpnConnectionPacketCaptureCommand.cs
  src/Network/Network/Cortex/VpnGateway/StartAzVpnGatewayPacketCaptureCommand.cs
  src/Network/Network/Cortex/VpnGateway/StopAzVpnGatewayPacketCaptureCommand.cs
  src/Network/Network/Models/Cortex/PSVpnConnectionPacketCaptureResult.cs
  src/Network/Network/Models/Cortex/PSVpnGatewayPacketCaptureResult.cs
  src/Network/Network/help/Start-AzVpnConnectionPacketCapture.md
  src/Network/Network/help/Start-AzVpnGatewayPacketCapture.md
  src/Network/Network/help/Stop-AzVpnConnectionPacketCapture.md
  src/Network/Network/help/Stop-AzVpnGatewayPacketCapture.md
Labels: Waiting for CI :shipit:
