Repository Azure/azure-powershell, pull requests merged in 2020-09, with the labels that each got.

#12812 Any Source to Local IP range
  src/Network/Network/help/New-AzFirewallNetworkRule.md
Labels: Waiting for CI :shipit:

#12635 add test case for new type of Express Custom Setup: AzPowerShellSetup
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1
Labels: needs-author-feedback, needs-revision

#12817 Internal/az.installer
  tools/Az.Tools.Installer/Az.Tools.Installer.psd1
  tools/Az.Tools.Installer/Az.Tools.Installer.psm1
  tools/Az.Tools.Installer/exports/Get-AzModuleWithUpdate.ps1
  tools/Az.Tools.Installer/exports/Install-AzModule.ps1
  tools/Az.Tools.Installer/internal/utils.psm1
Labels: needs-review

#12783 [RecoveryServices.Backup] Adding data source move feature - Copy-AzRecoveryServicesVault cmdlet
  src/RecoveryServices/RecoveryServices.Backup.Helpers/RecoveryServices.Backup.Helpers.csproj
  src/RecoveryServices/RecoveryServices.Backup.Helpers/TrackingHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Enums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Models/RecoveryServices.Backup.Models.csproj
  src/RecoveryServices/RecoveryServices.Backup.Providers/RecoveryServices.Backup.Providers.csproj
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/ContainerAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/OperationStatusAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/RecoveryServices.Backup.ServiceClientAdapter.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/Common.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureBackupDataMove.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/CopyAzureRmRecoveryServicesVault.cs
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.csproj
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
  src/RecoveryServices/RecoveryServices/help/Az.RecoveryServices.md
  src/RecoveryServices/RecoveryServices/help/Copy-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJob.md
Labels: needs-review

#12794 appgw: validate cert only if certificateFile is specified in set ssl cert command
  src/KeyVault/KeyVault/Models/KeyVaultDataServiceClient.cs
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/ScenarioTests/NetworkTestRunner.cs
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestKeyVaultIntegrationTest.json
  src/Network/Network.sln
  src/Network/Network/ApplicationGateway/SslCertificate/SetAzureApplicationGatewaySslCertificateCommand.cs
  src/Network/Network/ChangeLog.md
  tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs
  tools/TestFx/ITestRunnerFactory.cs
  tools/TestFx/TestManager.cs
Labels: Waiting for CI :shipit:

#12740 Format BreakingChange Output Messages
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#12829 Add null check in ConditionVersion of Set-AzRoleAssignmenr
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/RoleAssignments/SetAzureRoleAssignmentCommand.cs
Labels: needs-review

#12437 Added operation parameters and operation steps in MI operations PS cmdlet
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstanceOperation/Model/AzureSqlManagedInstanceOperationModel.cs
  src/Sql/Sql/ManagedInstanceOperation/Services/AzureSqlManagedInstanceOperationAdapter.cs
  src/Sql/Sql/help/Get-AzSqlInstanceOperation.md
Labels: needs-revision

#12777 Adding patchStatus property to VM Instance View
  src/Compute/Compute.Test/ScenarioTests/VirtualMachinePatchTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachinePatchTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachinePatchTests/TestPatchStatusGetAzVMinstanceview.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Models/PSVirtualMachineInstanceView.cs
  src/Compute/Compute/Models/PSVirtualMachineInstanceView.cs
Labels: needs-revision

#12825 Corrected parameter field 'Name' to 'StorageSyncServiceName' in the example
  src/StorageSync/StorageSync/help/Reset-AzStorageSyncServerCertificate.md
Labels: Waiting for CI :shipit:

#12821 Update spelling of Proeprty to Property
  src/Accounts/Authentication.ResourceManager/Common/PSObjectExtensions.cs
  src/Accounts/Authentication.Test/PSSerializationTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/Blob/DisableAzureStorageBlobRestorePolicy.cs
  src/Storage/Storage.Management/Blob/EnableAzureStorageBlobRestorePolicy.cs
  src/Storage/Storage.Management/Blob/GetAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/Blob/UpdateAzureStorageBlobServiceProperties.cs
Labels: Waiting for CI :shipit:

#12816 [RecoveryServices.backup] changing number of VMs from 100 to 1000
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#12842 Fix https://github.com/Azure/azure-powershell/issues/12707
  src/Blockchain/custom/New-AzBlockchainMember.ps1
  src/Blockchain/custom/New-AzBlockchainTransactionNode.ps1
  src/Blockchain/custom/Update-AzBlockchainMember.ps1
  src/Blockchain/custom/Update-AzBlockchainTransactionNode.ps1
Labels: needs-review

#12797 [KeyVault] Refactor tests
  src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
  src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultTestFixture.cs
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestModifyAccessPolicyNegativeCases.json
Labels: needs-review

#12459 Add parameter EnableRbcAuthorization for 'New-AzKeyVault' and 'Update-AzKeyVault'
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestCreateNewVault.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestUpdateVault.json
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultAccessPolicy.cs
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/VirtualNetworkRuleSet/KeyVaultNetworkRuleSetBase.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/PSKeyVault.cs
  src/KeyVault/KeyVault/Models/VaultCreationParameters.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
Labels: Waiting for CI :shipit:

#12673 Disk Access changes
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.cs
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskAccessObject.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskConfigDiskAccessNetworkAccess.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskEncryptionSetConfigEncryptionType.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestSnapshotConfigDiskAccessNetworkPolicy.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Disk/GetAzDiskAccessCommand.cs
  src/Compute/Compute/Disk/NewAzDiskAccessCommand.cs
  src/Compute/Compute/Disk/RemoveDiskAccessCommand.cs
  src/Compute/Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/Generated/DiskEncryptionSet/Config/NewAzureRmDiskEncryptionSetConfigCommand.cs
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Generated/Models/PSDisk.cs
  src/Compute/Compute/Generated/Models/PSDiskEncryptionSet.cs
  src/Compute/Compute/Generated/Models/PSDiskUpdate.cs
  src/Compute/Compute/Generated/Models/PSSnapshot.cs
  src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotConfigCommand.cs
  src/Compute/Compute/Models/PSDiskAccess.cs
  src/Compute/Compute/Models/PSDiskAccessList.cs
  src/Compute/Compute/help/Az.Compute.md
  src/Compute/Compute/help/Get-AzDiskAccess.md
  src/Compute/Compute/help/New-AzDiskAccess.md
  src/Compute/Compute/help/New-AzDiskConfig.md
  src/Compute/Compute/help/New-AzDiskEncryptionSetConfig.md
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
  src/Compute/Compute/help/New-AzSnapshotConfig.md
  src/Compute/Compute/help/Remove-AzDiskAccess.md
Labels: needs-review

#12854 {HDInsight} Skip network api version check
  src/HDInsight/HDInsight.Test/ScenarioTests/TestController.cs
Labels: needs-review

#12845 RecoveryServices OOB release
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices.Backup.Logger/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices.Backup/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Properties/AssemblyInfo.cs
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.Backup.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.SiteRecovery.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.RecoveryServices.dll.json
Labels: needs-review

#12832 Cmdlet Update-AzModule
  tools/Az.Tools.Installer/Az.Tools.Installer.psd1
  tools/Az.Tools.Installer/Az.Tools.Installer.psm1
  tools/Az.Tools.Installer/exports/Get-AzModuleUpdateList.ps1
  tools/Az.Tools.Installer/exports/Get-AzModuleWithUpdate.ps1
  tools/Az.Tools.Installer/exports/Update-AzModule.ps1
  tools/Az.Tools.Installer/internal/Add-RepositoryArgumentCompleter.ps1
  tools/Az.Tools.Installer/internal/Add-RepositoryDefaultValue.ps1
Labels: needs-review

#12767 [KeyVault] Update to official SDK
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/PSManagedHsm.cs
  tools/LocalFeed/Microsoft.Azure.Management.KeyVault.3.1.0-preview.1.nupkg
Labels: needs-review

#12784 Update Add-AzApplicationGatewayCustomError.md
  src/Network/Network/help/Add-AzApplicationGatewayCustomError.md
Labels: Doc - Reference

#12818 Fix dictionary deserialization issue
  src/AppConfiguration/.gitignore
  src/AppConfiguration/custom/ResourceIdentityUserAssignedIdentities.json.cs
  src/AppConfiguration/test/New-AzAppConfigurationStore.Tests.ps1
  src/Portal/.gitignore
  src/Portal/Az.Portal.psd1
  src/Portal/custom/Serialization/DashboardLensParts.cs
  src/Portal/custom/Serialization/DashboardPropertiesLenses.cs
  src/Portal/docs/Get-AzPortalDashboard.md
  src/Portal/docs/New-AzPortalDashboard.md
  src/Portal/docs/Remove-AzPortalDashboard.md
  src/Portal/docs/Update-AzPortalDashboard.md
Labels: needs-review

#12849 Adding Warning message for 3 regions when Geo backup storage redundancy is choosen on MI creation
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/help/New-AzSqlInstance.md
Labels: needs-revision

#12351 Updated Set-AzVirtualNetworkSubnetConfig to allow NSG and Route Table to be removed from subnet
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetNetworkSecurityGroupCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetRouteTableCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/VirtualNetwork/Subnet/SetAzureVirtualNetworkSubnetConfigCommand.cs
Labels: Waiting for CI :shipit:

#12882 [Storage] Upgrade DMlib to fix issue #12220
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/NewAzDataLakeGen2Item.cs
  src/Storage/Storage/Storage.csproj
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
Labels: needs-review

#12883 [Aks] update api version to 2020-06-01
  src/Aks/Aks.Test/Aks.Test.csproj
  src/Aks/Aks.Test/ScenarioTests/GetAksVersionTests.ps1
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.ps1
  src/Aks/Aks.Test/ScenarioTests/NodePoolTests.ps1
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.GetAksVersionTests/TestAksVersion.json
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestAzureKubernetes.json
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestSimpleAzureKubernetes.json
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.NodePoolTests/TestAksNodePool.json
  src/Aks/Aks/Aks.csproj
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/NewKubeBase.cs
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  src/Aks/Aks/Commands/StartAzureRmAksDashboard.cs
  src/Aks/Aks/Models/PSContainerServiceAgentPoolProfile.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
  src/Aks/Aks/help/New-AzAksCluster.md
  src/Aks/Aks/help/Set-AzAksCluster.md
Labels: needs-review

#12892 Add breaking change flag for OrchestrationMode feature. Required prior to 9/10
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
Labels: needs-review

#12895 update help for AAS Skus
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Set-AzAnalysisServicesServer.md
Labels: Waiting for CI :shipit:

#12869 Adding support for Premium V3 tier
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AppServicePlans/NewAzureAppServicePlan.cs
  src/Websites/Websites/Cmdlets/AppServicePlans/SetAzureAppServicePlan.cs
  src/Websites/Websites/Utilities/CmdletHelpers.cs
Labels: needs-revision

#12833 update Azure Web App runtime stack to DOTNETCORE
  src/Websites/Websites/help/Set-AzWebApp.md
Labels: Doc - Reference

#12828 Get-AzResourceGroup - New example, and cleanup
  src/Resources/Resources/help/Get-AzResourceGroup.md
Labels: Doc - Reference

#12893 Add warning when creating PowerShell 6.2 function apps; Remove ability to create v2 Functions in regions that do not support it.
  src/Functions/custom/HelperFunctions.ps1
  src/Functions/custom/New-AzFunctionApp.ps1
  src/Functions/test/New-AzFunctionApp.Tests.ps1
Labels: Waiting for CI :shipit:

#12800 [SQL] Add Managed Database Log Replay service cmdlets
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseLogReplayScenarioTest.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseLogReplayScenarioTest.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseLogReplayScenarioTest/TestCancelManagedDatabaseLogReplayService.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseLogReplayScenarioTest/TestCompleteManagedDatabaseLogReplayService.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseLogReplayScenarioTest/TestManagedDatabaseLogReplayService.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseLogReplayScenarioTest/TestPipingCompleteCancelManagedDatabaseLogReplayService.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseLogReplayScenarioTest/TestPipingManagedDatabaseLogReplayService.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedDatabase/Cmdlet/AzureSqlManagedDatabaseLogReplayCmdletBase.cs
  src/Sql/Sql/ManagedDatabase/Cmdlet/CompleteAzureSqlInstanceDatabaseLogReplay.cs
  src/Sql/Sql/ManagedDatabase/Cmdlet/GetAzureSqlInstanceDatabaseLogReplay.cs
  src/Sql/Sql/ManagedDatabase/Cmdlet/StartAzureSqlInstanceDatabaseLogReplay.cs
  src/Sql/Sql/ManagedDatabase/Cmdlet/StopAzureSqlInstanceDatabaseLogReplay.cs
  src/Sql/Sql/ManagedDatabase/Model/AzureSqlManagedDatabaseModel.cs
  src/Sql/Sql/ManagedDatabase/Model/AzureSqlManagedDatabaseRestoreDetailsResultModel.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseAdapter.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseCommunicator.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/help/Az.Sql.md
  src/Sql/Sql/help/Complete-AzSqlInstanceDatabaseLogReplay.md
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseLogReplay.md
  src/Sql/Sql/help/Start-AzSqlInstanceDatabaseLogReplay.md
  src/Sql/Sql/help/Stop-AzSqlInstanceDatabaseLogReplay.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-revision

#12880 [Aks] Preview for windows VHD
  src/Aks/Aks/Commands/NewAzureRmAksNodePool.cs
Labels: needs-review

#12637 [Aks]Add new switch GenerateSshKey to generate SSH keys if necessary
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
  src/Aks/Aks/help/Az.Aks.md
  src/Aks/Aks/help/New-AzAksCluster.md
Labels: needs-revision

#12901 Fix Network ChangeLog merging error
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:, needs-review

#12898 [Storage] Added breaking change warning message for upcoming cmdlet output change
  src/Network/Network.sln
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/AddAzureStorageAccountManagementPolicyAction.cs
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageAccountManagementPolicy.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccountManagementPolicyRule.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccountManagementPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerStoredAccessPolicy.cs
Labels: needs-review

#12807 Update Remove-AzNetworkInterfaceIpConfig.md
  src/Network/Network/help/Remove-AzNetworkInterfaceIpConfig.md
Labels: Doc - Reference

#12921 Fixing Set-AzSqlInstance cmdlet to not send GRS backup storage redundancy by default
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
Labels: needs-revision

#12911 Added Alpine 3.10 Dockerfile
  docker/Dockerfile-alpine-3.10
Labels: needs-review

#12465 [Network] Add New-AzExpressRoutePortLOA cmdlet
  src/Network/Network.Test/ScenarioTests/ExpressRoutePortTests.cs
  src/Network/Network.Test/ScenarioTests/ExpressRoutePortTests.ps1
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/ExpressRoutePort/LOA/NewAzureRmExpressRoutePortLOACommand.cs
  src/Network/Network/help/New-AzExpressRoutePortLOA.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-review

#12905 [Aks]Add client side parameter validation logic.
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Commands/NewKubeBase.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
  src/Aks/Aks/Utils/ValidateSecureString.cs
  src/Aks/Aks/help/New-AzAksCluster.md
Labels: needs-review

#12931 update sdk version
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Storage.csproj
Labels: Waiting for CI :shipit:, needs-review

#12938 Polish changelog for upcoming release
  src/Accounts/Accounts/ChangeLog.md
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/Maintenance/Maintenance/ChangeLog.md
  src/Network/Network/ChangeLog.md
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/Sql/Sql/ChangeLog.md
Labels: Waiting for CI :shipit:

#12940 Polish changelog for upcoming release
  src/Compute/Compute/ChangeLog.md
Labels: needs-review

#12926 Added new Cluster cmdlets and fix for issue 10722
  src/EventHub/EventHub.Test/EventHub.Test.csproj
  src/EventHub/EventHub.Test/ScenarioTests/ClusterTest.cs
  src/EventHub/EventHub.Test/ScenarioTests/ClusterTest.ps1
  src/EventHub/EventHub.Test/ScenarioTests/NamespaceTests.ps1
  src/EventHub/EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.ClusterTest/ClusterTestCURD.json
  src/EventHub/EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.NamespaceTests/NamespaceAuthorizationRulesCRUD.json
  src/EventHub/EventHub/Az.EventHub.psd1
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/AuthorizationRule/SetAzureEventhubAuthorizationRules.cs
  src/EventHub/EventHub/Cmdlets/AzureEventHubsCmdletBase.cs
  src/EventHub/EventHub/Cmdlets/Clusters/GetAzureEventHubAvailableClusters.cs
  src/EventHub/EventHub/Cmdlets/Clusters/GetAzureEventHubCluster.cs
  src/EventHub/EventHub/Cmdlets/Clusters/NewAzureEventHubCluster.cs
  src/EventHub/EventHub/Cmdlets/Clusters/RemoveAzureEventHubCluster.cs
  src/EventHub/EventHub/Cmdlets/Clusters/SetAzureEventHubCluster.cs
  src/EventHub/EventHub/EventHub.csproj
  src/EventHub/EventHub/Models/PSEventHubsAvailableCluster.cs
  src/EventHub/EventHub/Models/PSEventHubsClusterAttributes.cs
  src/EventHub/EventHub/Models/PSEventHubsClusterSkuAttributes.cs
  src/EventHub/EventHub/Resources.resx
  src/EventHub/EventHub/Utilities/EventHubsClient.cs
  src/EventHub/EventHub/help/Az.EventHub.md
  src/EventHub/EventHub/help/Get-AzEventHubCluster.md
  src/EventHub/EventHub/help/Get-AzEventHubClustersAvailableRegion.md
  src/EventHub/EventHub/help/New-AzEventHubCluster.md
  src/EventHub/EventHub/help/Remove-AzEventHubCluster.md
  src/EventHub/EventHub/help/Set-AzEventHubCluster.md
Labels: Sprint Candidate, needs-review

#12942 Include input object and resource id parameters in Server and Instanc…
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/InstanceActiveDirectoryOnlyAuthentication/Cmdlet/AzureSqlInstanceActiveDirectoryOnlyAuthenticationCmdletBase.cs
  src/Sql/Sql/InstanceActiveDirectoryOnlyAuthentication/Cmdlet/DisableAzureSqlInstanceActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/InstanceActiveDirectoryOnlyAuthentication/Cmdlet/EnableAzureSqlInstanceActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/InstanceActiveDirectoryOnlyAuthentication/Cmdlet/GetAzureSqlInstanceActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/ServerActiveDirectoryOnlyAuthentication/Cmdlet/AzureSqlServerActiveDirectoryOnlyAuthenticationCmdletBase.cs
  src/Sql/Sql/ServerActiveDirectoryOnlyAuthentication/Cmdlet/DisableAzureSqlServerActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/ServerActiveDirectoryOnlyAuthentication/Cmdlet/EnableAzureSqlServerActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/ServerActiveDirectoryOnlyAuthentication/Cmdlet/GetAzureSqlServerActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/help/Disable-AzSqlInstanceActiveDirectoryOnlyAuthentication.md
  src/Sql/Sql/help/Disable-AzSqlServerActiveDirectoryOnlyAuthentication.md
  src/Sql/Sql/help/Enable-AzSqlInstanceActiveDirectoryOnlyAuthentication.md
  src/Sql/Sql/help/Enable-AzSqlServerActiveDirectoryOnlyAuthentication.md
  src/Sql/Sql/help/Get-AzSqlInstanceActiveDirectoryOnlyAuthentication.md
  src/Sql/Sql/help/Get-AzSqlServerActiveDirectoryOnlyAuthentication.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#12951 Pin the swagger version for mysql, postgres and mariadb
  src/MariaDb/readme.md
  src/MySql/readme.md
  src/PostgreSql/readme.md
Labels: needs-review

#12920 [Aks] Add addon support
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.cs
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.ps1
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestAzureKubernetesAddons.json
  src/Aks/Aks/Az.Aks.psd1
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/Constants.cs
  src/Aks/Aks/Commands/DisableAzureRmAddons.cs
  src/Aks/Aks/Commands/EnableAzureRmAddons.cs
  src/Aks/Aks/Commands/NewKubeBase.cs
  src/Aks/Aks/Commands/UpdateAddonsBase.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
  src/Aks/Aks/Utils/AddonUtils.cs
  src/Aks/Aks/help/Az.Aks.md
  src/Aks/Aks/help/Disable-AzAksAddon.md
  src/Aks/Aks/help/Enable-AzAksAddon.md
  src/Aks/Aks/help/New-AzAksCluster.md
Labels: needs-review

#12946 Update psd1 for Kusto GA
  src/Kusto/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: needs-review

#12947 Change output format of virtual router
  src/Network/Network/Generated/Models/PSVirtualRouter.cs
  src/Network/Network/Network.format.ps1xml
Labels: Waiting for CI :shipit:, needs-review

#12963 [SignalR] Clarify the usage of Update-AzSignalRNetworkAcl in document
  src/SignalR/SignalR/help/Update-AzSignalRNetworkAcl.md
Labels: needs-review

#12910 Update connectedmachine to 2020-08-02
  src/ConnectedMachine/Az.ConnectedMachine.format.ps1xml
  src/ConnectedMachine/custom/Connect-AzConnectedMachine.ps1
  src/ConnectedMachine/custom/MachineExtensionProperties.json.cs
  src/ConnectedMachine/custom/MachineExtensionPropertiesProtectedSettings.cs
  src/ConnectedMachine/custom/MachineExtensionPropertiesSettings.cs
  src/ConnectedMachine/custom/MachineExtensionUpdatePropertiesProtectedSettings.cs
  src/ConnectedMachine/custom/MachineExtensionUpdatePropertiesSettings.cs
  src/ConnectedMachine/docs/Get-AzConnectedMachine.md
  src/ConnectedMachine/docs/Get-AzConnectedMachineExtension.md
  src/ConnectedMachine/docs/New-AzConnectedMachineExtension.md
  src/ConnectedMachine/docs/Set-AzConnectedMachineExtension.md
  src/ConnectedMachine/docs/Update-AzConnectedMachineExtension.md
  src/ConnectedMachine/readme.md
  src/ConnectedMachine/test/Get-AzConnectedMachine.Recording.json
  src/ConnectedMachine/test/Get-AzConnectedMachineExtension.Recording.json
  src/ConnectedMachine/test/New-AzConnectedMachineExtension.Recording.json
  src/ConnectedMachine/test/New-AzConnectedMachineExtension.Tests.ps1
  src/ConnectedMachine/test/Remove-AzConnectedMachine.Recording.json
  src/ConnectedMachine/test/Remove-AzConnectedMachineExtension.Recording.json
  src/ConnectedMachine/test/Set-AzConnectedMachineExtension.Recording.json
  src/ConnectedMachine/test/Set-AzConnectedMachineExtension.Tests.ps1
  src/ConnectedMachine/test/Update-AzConnectedMachineExtension.Recording.json
  src/ConnectedMachine/test/env.json
Labels: needs-review

#12943 Updated Connection monitor endpoint cmdlet
  src/Network/Network/Az.Network.psd1
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSConnectionMonitorEndPoint.cs
  src/Network/Network/Models/PSConnectionMonitorEndpointScope.cs
  src/Network/Network/Models/PSConnectionMonitorEndpointScopeItem.cs
  src/Network/Network/Models/PSConnectionMonitorTcpConfiguration.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkWatcher/ConnectionMonitor/ConnectionMonitorBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndPointObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndpointScopeItemObject.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorProtocolConfigurationObjectCommand.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointScopeItemObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#12945 Change psd1 for upcoming preview release
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  tools/Az/Az.psd1
Labels: needs-review

#12974 Improve the build of Az.Tools.Predictor
  .azure-pipelines/sign-tool-predictor.yml
  tools/Az.Tools.Installer/build.proj
  tools/Az.Tools.Predictor/build.proj
Labels: customer-reported, needs-review

#12982 Fix newtonsoft.json loading
  tools/StaticAnalysis/Exceptions/Az.DeviceProvisioningServices/SharedAssemblyConflict.csv
  tools/StaticAnalysis/Exceptions/Az.IotHub/SharedAssemblyConflict.csv
  tools/StaticAnalysis/Program.cs
  tools/StaticAnalysis/StaticAnalysis.Netcore.csproj
Labels: needs-review

#12980 Update release version in Az.Network.psd1
  src/Network/Network/Az.Network.psd1
Labels: needs-review

#12981 bump version for Az.storage-preview 2.6.1
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/AssemblyInfo.cs
  src/Accounts/Authentication/Properties/AssemblyInfo.cs
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
  src/Storage/Storage/Properties/AssemblyInfo.cs
Labels: needs-review

#12985 IgnoreCase = false for BackupStorageRedundancy
  src/Sql/Sql.Test/ScenarioTests/DatabaseActivationTests.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
Labels: needs-review

#12984 Predict parameter values in the suggestion
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.sln
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorConstants.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterValuePredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine.Polyfiller.dll
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine2.dll
  tools/Az.Tools.Predictor/MockPSConsole/MockPSConsole.csproj
  tools/Az.Tools.Predictor/MockPSConsole/Program.cs
Labels: customer-reported, needs-review

#12996 Populated failover types at Update-ASRRecoveryPlan cmdlet flow
  src/Compute/Compute/ChangeLog.md
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSRecoveryPlanObjects.cs
Labels: needs-review

#13001 Fixed bug in New-AzConnectionMonitorEndpoint cmdlet. Updated help file
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndPointObjectCommand.cs
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointObject.md
Labels: needs-review

#12999 Corrected some typos in messages.
  src/DataFactory/DataFactories/Properties/Resources.resx
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Properties/Resources.resx
  src/OperationalInsights/OperationalInsights/Properties/Resources.resx
  src/StreamAnalytics/StreamAnalytics/Properties/Resources.resx
Labels: customer-reported, needs-review

#13009 Provide the detailed date of removing property SecretValueText
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/GetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/RestoreAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/UndoAzureKeyVaultSecretRemoval.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVaultSecret.cs
Labels: needs-review

#12995 Add -Scope AllUsers on Install-Module during docker build
  docker/Dockerfile-alpine-3.10
  docker/Dockerfile-centos-7
  docker/Dockerfile-debian-9
  docker/Dockerfile-ubuntu-18.04
Labels: needs-review

#12971 Fixed complaint on Managed instance's system database for vulnerability assessment
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ManagedDatabase/ClearSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ManagedDatabase/GetAzureSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentRuleBaseline/ManagedDatabase/SetAzureSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentScan/ManagedDatabase/ConvertAzureSqlManagedDatabaseVulnerabilityAssessmentScan.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentScan/ManagedDatabase/GetAzureSqlManagedDatabaseVulnerabilityAssessmentScanRecord.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentScan/ManagedDatabase/StartAzureSqlManagedDatabaseVulnerabilityAssessmentScan.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/ManagedDatabase/ClearSqlManagedDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/ManagedDatabase/GetAzureSqlManagedDatabaseVulnerabilityAssessmentSettings.cs
  src/Sql/Sql/VulnerabilityAssessment/Cmdlet/VulnerabilityAssessmentSettings/ManagedDatabase/UpdateAzureSqlManagedDatabaseVulnerabilityAssessmentSettings.cs
Labels: customer-reported, needs-review

#13007 Fixed help message for Remove-AzExpressRouteCircuitConnectionConfig parameter AddressPrefixType
  src/Network/Network/help/Remove-AzExpressRouteCircuitConnectionConfig.md
Labels: needs-review

#12528 {IotHub} Update device sdk
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/DeviceProvisioningServices.Test.csproj
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsAccessPolicyTests/IotDpsAccessPolicyLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsEnrollmentGroupTests/IotDpsEnrollmentGroupLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsEnrollmentTests/IotDpsEnrollmentLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsLinkedHubTests/IotDpsLinkedHubLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsRegistrationTests/IotDpsRegistrationLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsTests/IotDpsLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.sln
  src/DeviceProvisioningServices/DeviceProvisioningServices/ChangeLog.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/DeviceProvisioningServices.csproj
  src/IotHub/IotHub.Test/IotHub.Test.csproj
  src/IotHub/IotHub.Test/ScenarioTests/IotHubDPDeviceTests.ps1
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPConfigurationTests/TestAzureIotHubConfigurationLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPDeviceTests/TestAzureIotHubDeviceLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPModuleTests/TestAzureIotHubModuleLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPTracingTests/TestAzureIotHubTracing.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubRoutingTests/TestAzureIotHubRoutingLifeCycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubTests/TestAzureIotHubLifeCycle.json
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/IotHub.csproj
Labels: needs-revision

#13019 Vmware virtustream
  src/VMWare/.gitattributes
  src/VMWare/.gitignore
  src/VMWare/Az.VMWare.psd1
  src/VMWare/custom/New-AzVMWarePrivateCloud.ps1
  src/VMWare/custom/readme.md
  src/VMWare/docs/Az.VMWare.md
  src/VMWare/docs/Get-AzVMWareAuthorization.md
  src/VMWare/docs/Get-AzVMWareCluster.md
  src/VMWare/docs/Get-AzVMWarePrivateCloud.md
  src/VMWare/docs/Get-AzVMWarePrivateCloudAdminCredentials.md
  src/VMWare/docs/New-AzVMWareAuthorization.md
  src/VMWare/docs/New-AzVMWareCluster.md
  src/VMWare/docs/New-AzVMWarePrivateCloud.md
  src/VMWare/docs/Remove-AzVMWareAuthorization.md
  src/VMWare/docs/Remove-AzVMWareCluster.md
  src/VMWare/docs/Remove-AzVMWarePrivateCloud.md
  src/VMWare/docs/Test-AzVMWareLocationQuotaAvailability.md
  src/VMWare/docs/Test-AzVMWareLocationTrialAvailability.md
  src/VMWare/docs/Update-AzVMWareCluster.md
  src/VMWare/docs/Update-AzVMWarePrivateCloud.md
  src/VMWare/docs/readme.md
  src/VMWare/examples/Get-AzVMWareAuthorization.md
  src/VMWare/examples/Get-AzVMWareCluster.md
  src/VMWare/examples/Get-AzVMWarePrivateCloud.md
  src/VMWare/examples/Get-AzVMWarePrivateCloudAdminCredentials.md
  src/VMWare/examples/New-AzVMWareAuthorization.md
  src/VMWare/examples/New-AzVMWareCluster.md
  src/VMWare/examples/New-AzVMWarePrivateCloud.md
  src/VMWare/examples/Remove-AzVMWareAuthorization.md
  src/VMWare/examples/Remove-AzVMWareCluster.md
  src/VMWare/examples/Remove-AzVMWarePrivateCloud.md
  src/VMWare/examples/Test-AzVMWareLocationQuotaAvailability.md
  src/VMWare/examples/Test-AzVMWareLocationTrialAvailability.md
  src/VMWare/examples/Update-AzVMWareCluster.md
  src/VMWare/examples/Update-AzVMWarePrivateCloud.md
  src/VMWare/how-to.md
  src/VMWare/license.txt
  src/VMWare/readme.md
  src/VMWare/resources/readme.md
  src/VMWare/test/New-AzVMWareAuthorization.Recording.json
  src/VMWare/test/New-AzVMWareAuthorization.Tests.ps1
  src/VMWare/test/New-AzVMWareCluster.Recording.json
  src/VMWare/test/New-AzVMWareCluster.Tests.ps1
  src/VMWare/test/New-AzVMWarePrivateCloud.Recording.json
  src/VMWare/test/New-AzVMWarePrivateCloud.Tests.ps1
  src/VMWare/test/Test-AzVMWareLocationQuotaAvailability.Recording.json
  src/VMWare/test/Test-AzVMWareLocationQuotaAvailability.Tests.ps1
  src/VMWare/test/Test-AzVMWareLocationTrialAvailability.Recording.json
  src/VMWare/test/Test-AzVMWareLocationTrialAvailability.Tests.ps1
  src/VMWare/test/env.json
  src/VMWare/test/loadEnv.ps1
  src/VMWare/test/readme.md
  src/VMWare/test/utils.ps1
Labels: needs-review

#12994 [Databricks] Add feature vnet peering.
  src/Databricks/Az.Databricks.psd1
  src/Databricks/custom/Update-AzDatabricksVNetPeering.ps1
  src/Databricks/docs/Az.Databricks.md
  src/Databricks/docs/Get-AzDatabricksVNetPeering.md
  src/Databricks/docs/New-AzDatabricksVNetPeering.md
  src/Databricks/docs/Remove-AzDatabricksVNetPeering.md
  src/Databricks/docs/Update-AzDatabricksVNetPeering.md
  src/Databricks/examples/Get-AzDatabricksVNetPeering.md
  src/Databricks/examples/New-AzDatabricksVNetPeering.md
  src/Databricks/examples/Remove-AzDatabricksVNetPeering.md
  src/Databricks/examples/Update-AzDatabricksVNetPeering.md
  src/Databricks/readme.md
  src/Databricks/test/Get-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Get-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/test/Get-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/New-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/New-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/test/New-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Remove-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Remove-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/test/Remove-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Remove-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/Update-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Update-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/test/Update-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/deployment-templates/key-vault/parameters.json
  src/Databricks/test/deployment-templates/security-network-group/parameters.json
  src/Databricks/test/deployment-templates/virtual-network/parameters.json
  src/Databricks/test/env.json
  src/Databricks/test/utils.ps1
Labels: Databricks, needs-revision

#13018 combine track 1&2 sdk
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/Commands/AddAzureKeyVaultKey.cs
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/Models/DataServiceCredential.cs
  src/KeyVault/KeyVault/Models/IKeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/KeyVaultCmdletBase.cs
  src/KeyVault/KeyVault/Models/KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/PSKeyVaultKey.cs
  src/KeyVault/KeyVault/Models/VaultUriHelper.cs
  src/KeyVault/KeyVault/Track2Models/Track2HsmClient.cs
  src/KeyVault/KeyVault/Track2Models/Track2KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Track2Models/Track2ModelConvertionExtensions.cs
  src/KeyVault/KeyVault/Track2Models/Track2TokenCredential.cs
  src/KeyVault/KeyVault/Track2Models/Track2VaultClient.cs
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  src/lib/PreloadAssemblyInfo.json
  tools/Common.Netcore.Dependencies.targets
  tools/LocalFeed/Microsoft.Azure.PowerShell.Authentication.Abstractions.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Authentication.Abstractions.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Aks.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Aks.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Authorization.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Authorization.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Compute.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Compute.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Graph.Rbac.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Graph.Rbac.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.KeyVault.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.KeyVault.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Monitor.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Monitor.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Network.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Network.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.PolicyInsights.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.PolicyInsights.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.ResourceManager.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.ResourceManager.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Storage.Management.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Storage.Management.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Websites.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Clients.Websites.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Common.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Common.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Storage.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Storage.1.5.8-preview.symbols.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Strategies.1.5.8-preview.nupkg
  tools/LocalFeed/Microsoft.Azure.PowerShell.Strategies.1.5.8-preview.symbols.nupkg
  tools/StaticAnalysis/Exceptions/Az.KeyVault/MissingAssemblies.csv
Labels: needs-review

#13017 [RecoveryServices.Backup] Adding workload container name validation
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#12870 Add ApiProperties support for Cognitive Services
  src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.cs
  src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.ps1
  src/CognitiveServices/CognitiveServices.Test/SessionRecords/CognitiveServices.Test.ScenarioTests.CognitiveServicesAccountTests/TestApiProperties.json
  src/CognitiveServices/CognitiveServices/Az.CognitiveServices.psd1
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccountApiProperty.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/SetAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/UpdateAzureCognitiveServicesAccountNetworkRuleSet.cs
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccount.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccountApiProperty.md
  src/CognitiveServices/CognitiveServices/help/Set-AzCognitiveServicesAccount.md
  tools/StaticAnalysis/Exceptions/Az.CognitiveServices/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#13027 Updated breaking changes warnings in preparation for S177 Milestone PR
  src/ManagedServices/ManagedServices/ChangeLog.md
  src/ManagedServices/ManagedServices/Commands/NewAzureRmManagedServicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/NewAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Extensions/ManagedServicesUtility.cs
Labels: needs-review

#13014 [Network] Add new property in VPNSite resource
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VpnSite/NewAzureRmVpnSiteCommand.cs
  src/Network/Network/Cortex/VpnSite/O365Policy/NewAzureRmO365PolicyPropertyCommand.cs
  src/Network/Network/Cortex/VpnSite/UpdateAzureRmVpnSiteCommand.cs
  src/Network/Network/Models/Cortex/PSO365BreakOutCategoryPolicies.cs
  src/Network/Network/Models/Cortex/PSO365PolicyProperties.cs
  src/Network/Network/Models/Cortex/PSVpnSite.cs
  src/Network/Network/help/New-AzO365PolicyProperty.md
  src/Network/Network/help/New-AzVpnSite.md
  src/Network/Network/help/Update-AzVpnSite.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-review

#13020 Remove case sensitivity for backup storage redundancy parameter for MI
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
Labels: needs-review

#13032 Update ChangeLog.md
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#13003 Fix SQL cmdlet New-AzSqlDatabaseExport to use network isolation parameters
  src/Sql/Sql.Test/ScenarioTests/Common.ps1
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/ScenarioTests/ImportExportTests.cs
  src/Sql/Sql.Test/ScenarioTests/ImportExportTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestRestoreDeletedDatabaseBackup.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ImportExportTests/TestExportDatabase_NetworkIsolation.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ImportExportTests/TestImportNewDatabase_NetworkIsolation.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ImportExport/Service/ImportExportDatabaseAdapter.cs
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#13021 feat(): add skipMetricValidation to powershell
  src/Monitor/Monitor.Test/Alerts/NewAzureRmMetricAlertRuleV2CriteriaTests.cs
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.ps1
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestAddAzureRmMetricAlertRuleV2WithSkipMetricValidation.json
  src/Monitor/Monitor/Alerts/AddAzureRmMetricAlertRuleV2Command.cs
  src/Monitor/Monitor/Alerts/NewAzureRmMetricAlertRuleV2CriteriaCommand.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/Monitor.csproj
  src/Monitor/Monitor/OutputClasses/PSDynamicMetricCriteria.cs
  src/Monitor/Monitor/OutputClasses/PSMetricCriteria.cs
  src/Monitor/Monitor/help/New-AzMetricAlertRuleV2Criteria.md
  src/Sql/Sql.Test/Sql.Test.csproj
Labels: needs-review

#13028 Az.KeyVault New-AzKeyVaultCertificatePolicy documentation - Clarification NOTE - escaping special characters in SubjectName parameter
  src/KeyVault/KeyVault/help/New-AzKeyVaultCertificatePolicy.md
Labels: customer-reported, needs-review

#13034 [Storage] Fix some help issue
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Restore-AzStorageBlobRange.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
Labels: needs-review

#13043 Onboard Dedicated HSM RP
  src/DedicatedHsm/.gitattributes
  src/DedicatedHsm/.gitignore
  src/DedicatedHsm/Az.DedicatedHsm.psd1
  src/DedicatedHsm/custom/readme.md
  src/DedicatedHsm/docs/Az.DedicatedHsm.md
  src/DedicatedHsm/docs/Get-AzDedicatedHsm.md
  src/DedicatedHsm/docs/New-AzDedicatedHsm.md
  src/DedicatedHsm/docs/Remove-AzDedicatedHsm.md
  src/DedicatedHsm/docs/Update-AzDedicatedHsm.md
  src/DedicatedHsm/docs/readme.md
  src/DedicatedHsm/examples/Get-AzDedicatedHsm.md
  src/DedicatedHsm/examples/New-AzDedicatedHsm.md
  src/DedicatedHsm/examples/Remove-AzDedicatedHsm.md
  src/DedicatedHsm/examples/Update-AzDedicatedHsm.md
  src/DedicatedHsm/how-to.md
  src/DedicatedHsm/license.txt
  src/DedicatedHsm/readme.md
  src/DedicatedHsm/resources/readme.md
  src/DedicatedHsm/test/Get-AzDedicatedHsm.Recording.json
  src/DedicatedHsm/test/Get-AzDedicatedHsm.Tests.ps1
  src/DedicatedHsm/test/New-AzDedicatedHsm.Recording.json
  src/DedicatedHsm/test/New-AzDedicatedHsm.Tests.ps1
  src/DedicatedHsm/test/Remove-AzDedicatedHsm.Recording.json
  src/DedicatedHsm/test/Remove-AzDedicatedHsm.Tests.ps1
  src/DedicatedHsm/test/Update-AzDedicatedHsm.Recording.json
  src/DedicatedHsm/test/Update-AzDedicatedHsm.Tests.ps1
  src/DedicatedHsm/test/deployment-templates/public-ipaddress/parameters.json
  src/DedicatedHsm/test/deployment-templates/public-ipaddress/template.json
  src/DedicatedHsm/test/deployment-templates/security-network-group/parameters.json
  src/DedicatedHsm/test/deployment-templates/security-network-group/template.json
  src/DedicatedHsm/test/deployment-templates/virtual-network-gateway/parameters.json
  src/DedicatedHsm/test/deployment-templates/virtual-network-gateway/template.json
  src/DedicatedHsm/test/deployment-templates/virtual-network/parameters.json
  src/DedicatedHsm/test/deployment-templates/virtual-network/template.json
  src/DedicatedHsm/test/env.json
  src/DedicatedHsm/test/loadEnv.ps1
  src/DedicatedHsm/test/readme.md
  src/DedicatedHsm/test/test-dedicated-hsm.ps1
  src/DedicatedHsm/test/utils.ps1
Labels: needs-review

#13048 [Databricks] Add vnet peering feature
  src/Databricks/custom/Update-AzDatabricksVNetPeering.ps1
  src/Databricks/docs/Update-AzDatabricksVNetPeering.md
  src/Databricks/test/utils.ps1
Labels: Databricks, needs-review

#13025 improve telemetry
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorConstants.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ITelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/PredictionSource.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
Labels: needs-review

#13060 Fix MySql issues
  src/MySql/custom/New-AzMySqlServer.ps1
  src/MySql/custom/Update-AzMySqlServer.ps1
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/Get-AzMySqlConnectionString.md
  src/MySql/docs/New-AzMySqlFirewallRule.md
  src/MySql/docs/New-AzMySqlReplica.md
  src/MySql/docs/Restore-AzMySqlServer.md
  src/MySql/examples/New-AzMySqlFirewallRule.md
  src/MySql/readme.md
  src/MySql/test/Az.MySql-TestResults.xml
  src/MySql/utils/Unprotect-SecureString.ps1
Labels: needs-review

#12979 [Tools] Add step of copying generate-info.json when move from generate branch to master
  tools/Gen2Master/MoveFromGeneration2Master.ps1
  tools/GenerateHelp.ps1
  tools/GeneratedModuleList.txt
Labels: needs-review

#13039 Get-AzVMImage cmdlet OData support for Top, OrderBy, Expand
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineImageListTopOrderExpand.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Images/GetAzureVMImageCommand.cs
  src/Compute/Compute/help/Get-AzVMImage.md
  src/Network/Network.Test/Network.Test.csproj
Labels: needs-review

#13008 Add a pipeline for release candidate test
  .azure-pipelines/release-test.yml
  tools/Test/SmokeTest/CleanAzModules.ps1
  tools/Test/SmokeTest/Common.ps1
  tools/Test/SmokeTest/ConnectAzAccount.ps1
  tools/Test/SmokeTest/InstallAnIndividualModule.ps1
  tools/Test/SmokeTest/InstallAnIndividualModuleOnTopOfAz.ps1
  tools/Test/SmokeTest/InstallAzModules.ps1
  tools/Test/SmokeTest/InstallAzOnTopOfAnIndividualModule.ps1
  tools/Test/SmokeTest/PrepareRequiredPowershell.ps1
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
  tools/Test/SmokeTest/ScriptsCaller.ps1
  tools/Test/SmokeTest/UpdateAnIndividualModule.ps1
  tools/Test/SmokeTest/UpdateAzModules.ps1
Labels: needs-review

#13059 {HDInsight} Added warning message for planning to deprecate the parameters of old private link
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
Labels: needs-review

#13068 Update Set-AzLoadBalancerInboundNatPoolConfig.md
  src/Network/Network/help/Set-AzLoadBalancerInboundNatPoolConfig.md
Labels: needs-review

#13070 Update Set-AzLoadBalancerFrontendIpConfig.md
  src/Network/Network/help/Set-AzLoadBalancerFrontendIpConfig.md
Labels: needs-review

#13033 Microsoft.cache RP regsitering shouldn't block creating/updating redi…
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
Labels: needs-review

#13051 Add BackupStorageRedundancy parameter to Restore DB, Create DB Copy, Create GeoSecondary cmdlets
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudStretchTests/TestStretchDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCancelOperation.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRename.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancyNotSpecified.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestUpdateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdateWithLicenseType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateDatabaseCopy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateDatabaseCopyWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateNamedSecondaryDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateNamedSecondaryDatabaseNegative.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateSecondaryDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateSecondaryDatabaseWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestFailoverSecondaryDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestRemoveSecondaryDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ImportExportTests/TestExportDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ReadScaleCrudTests/TestDatabaseReadReplicaCount.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ReadScaleCrudTests/TestDatabaseReadScaleCreateUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ReadScaleCrudTests/TestDatabaseReadScaleGet.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/RestoreAzureRMSqlDatabase.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Database/Cmdlet/AzureSqlDatabaseCmdletBase.cs
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseCopy.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Model/AzureReplicationLinkModel.cs
  src/Sql/Sql/Replication/Model/AzureSqlDatabaseCopyModel.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabaseCopy.md
  src/Sql/Sql/help/New-AzSqlDatabaseSecondary.md
  src/Sql/Sql/help/Restore-AzSqlDatabase.md
Labels: needs-review

#13073 Add Managed HSM support for SQL
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/TdeKeyHelper.cs
Labels: Waiting for CI :shipit:, customer-reported, needs-review

#13081 Aladdin generated examples for StreamAnalytics
  src/StreamAnalytics/StreamAnalytics/help/Get-AzStreamAnalyticsInput.md
  src/StreamAnalytics/StreamAnalytics/help/Get-AzStreamAnalyticsOutput.md
  src/StreamAnalytics/StreamAnalytics/help/New-AzStreamAnalyticsInput.md
  src/StreamAnalytics/StreamAnalytics/help/New-AzStreamAnalyticsOutput.md
  src/StreamAnalytics/StreamAnalytics/help/New-AzStreamAnalyticsTransformation.md
  src/StreamAnalytics/StreamAnalytics/help/Start-AzStreamAnalyticsJob.md
  src/StreamAnalytics/StreamAnalytics/help/Stop-AzStreamAnalyticsJob.md
  src/StreamAnalytics/StreamAnalytics/help/Test-AzStreamAnalyticsInput.md
  src/StreamAnalytics/StreamAnalytics/help/Test-AzStreamAnalyticsOutput.md
Labels: needs-review

#13079 {HDInsight} Add deprecation information for storage related parameters
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
Labels: needs-review

#13031 [Storage] update RM Blob service properties cmdlet: only set changed properties to server
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobRestore.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobServiceProperties.json
  src/Storage/Storage.Management/Blob/DisableAzureStorageBlobDeleteRetentionPolicy.cs
  src/Storage/Storage.Management/Blob/DisableAzureStorageBlobRestorePolicy.cs
  src/Storage/Storage.Management/Blob/EnableAzureStorageBlobDeleteRetentionPolicy.cs
  src/Storage/Storage.Management/Blob/EnableAzureStorageBlobRestorePolicy.cs
  src/Storage/Storage.Management/Blob/UpdateAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/ChangeLog.md
Labels: needs-review

#13087 Fix MariaDb document issues
  src/MariaDb/custom/Get-AzMariaDBConnectionString.ps1
  src/MariaDb/custom/New-AzMariaDBServer.ps1
  src/MariaDb/custom/New-AzMariaDbReplica.ps1
  src/MariaDb/custom/Restart-AzMariaDbServer.ps1
  src/MariaDb/custom/Restore-AzMariaDBServer.ps1
  src/MariaDb/docs/Az.MariaDb.md
  src/MariaDb/docs/Get-AzMariaDbConnectionString.md
  src/MariaDb/docs/New-AzMariaDbReplica.md
  src/MariaDb/docs/Restart-AzMariaDbServer.md
  src/MariaDb/docs/Restore-AzMariaDbServer.md
Labels: needs-review

#13088 Change MariaDb to MariaDB in cmdlet descriptions
  src/MariaDb/custom/Get-AzMariaDBConnectionString.ps1
  src/MariaDb/custom/New-AzMariaDBServer.ps1
  src/MariaDb/custom/New-AzMariaDbReplica.ps1
  src/MariaDb/custom/Restore-AzMariaDBServer.ps1
  src/MariaDb/custom/Update-AzMariaDBServer.ps1
  src/MariaDb/docs/Az.MariaDb.md
  src/MariaDb/docs/Get-AzMariaDbConnectionString.md
  src/MariaDb/docs/New-AzMariaDbReplica.md
  src/MariaDb/docs/New-AzMariaDbServer.md
  src/MariaDb/docs/Restore-AzMariaDbServer.md
  src/MariaDb/docs/Update-AzMariaDbConfiguration.md
  src/MariaDb/docs/Update-AzMariaDbFirewallRule.md
  src/MariaDb/docs/Update-AzMariaDbServer.md
  src/MariaDb/docs/Update-AzMariaDbVirtualNetworkRule.md
  src/MariaDb/examples/Update-AzMariaDbConfiguration.md
  src/MariaDb/examples/Update-AzMariaDbFirewallRule.md
  src/MariaDb/examples/Update-AzMariaDbServer.md
  src/MariaDb/examples/Update-AzMariaDbVirtualNetworkRule.md
Labels: needs-review

#13077 Improve PostgreSql
  src/PostgreSql/custom/New-AzPostgreSqlFirewallRule.ps1
  src/PostgreSql/custom/New-AzPostgreSqlReplica.ps1
  src/PostgreSql/custom/New-AzPostgreSqlServer.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlConfiguration.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlFirewallRule.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlServer.ps1
  src/PostgreSql/custom/readme.md
  src/PostgreSql/docs/Az.PostgreSql.md
  src/PostgreSql/docs/Get-AzPostgreSqlConfiguration.md
  src/PostgreSql/docs/New-AzPostgreSqlFirewallRule.md
  src/PostgreSql/docs/New-AzPostgreSqlReplica.md
  src/PostgreSql/docs/Remove-AzPostgreSqlServer.md
  src/PostgreSql/docs/Update-AzPostgreSqlConfiguration.md
  src/PostgreSql/docs/Update-AzPostgreSqlFirewallRule.md
  src/PostgreSql/docs/Update-AzPostgreSqlServer.md
  src/PostgreSql/docs/readme.md
  src/PostgreSql/examples/Get-AzPostgreSqlConfiguration.md
  src/PostgreSql/examples/New-AzPostgreSqlFirewallRule.md
  src/PostgreSql/examples/New-AzPostgreSqlReplica.md
  src/PostgreSql/examples/Remove-AzPostgreSqlServer.md
  src/PostgreSql/examples/Update-AzPostgreSqlFirewallRule.md
  src/PostgreSql/readme.md
  src/PostgreSql/test/Get-AzPostgreSqlConfiguration.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlConnectionString.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlReplica.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlFirewallRule.Tests.ps1
  src/PostgreSql/test/New-AzPostgreSqlReplica.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Restart-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Restore-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlConfiguration.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFirewallRule.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/env.json
  src/PostgreSql/test/readme.md
  src/PostgreSql/utils/Unprotect-SecureString.ps1
Labels: needs-review

#13075 fix DateTime parse issue
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#13074 Fix dedicated HSM onboarding issues
  documentation/azure-powershell-modules.md
  src/DedicatedHsm/MSSharedLibKey.snk
  tools/CreateMappings_rules.json
Labels: needs-review

#13091 Initial Version of Az.Tools.Installer
  .azure-pipelines/sign-tools.yml
  tools/Az.Tools.Installer/Az.Tools.Installer.psd1
  tools/Az.Tools.Installer/Az.Tools.Installer.psm1
  tools/Az.Tools.Installer/assembly/Microsoft.ApplicationInsights.2.12.0/Microsoft.ApplicationInsights.dll
  tools/Az.Tools.Installer/build.proj
  tools/Az.Tools.Installer/exports/Install-AzModule.ps1
  tools/Az.Tools.Installer/exports/Uninstall-AzModule.ps1
  tools/Az.Tools.Installer/exports/Update-AzModule.ps1
  tools/Az.Tools.Installer/internal/Add-RepositoryArgumentCompleter.ps1
  tools/Az.Tools.Installer/internal/Add-RepositoryDefaultValue.ps1
  tools/Az.Tools.Installer/internal/Classes.ps1
  tools/Az.Tools.Installer/internal/Get-AzModuleUpdateList.ps1
  tools/Az.Tools.Installer/internal/Send-PageViewTelemetry.ps1
  tools/PublishToolsModule.ps1
Labels: needs-review

#13005 Fix the bug that warning message cannot be suppressed
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/MonitorCmdletBase.cs
Labels: Waiting for CI :shipit:

#13093 Update the version of AppConfiguration
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:, needs-review

#12912 Add managed hsm uri in regex matching
  src/Sql/Sql/ChangeLog.md
Labels: SQL, Service Attention, Waiting for CI :shipit:

#12991 Fix typo in New-AzDataShareDataSet example
  src/DataShare/DataShare/help/New-AzDataShareDataSet.md
Labels: needs-review

#13069 Update Set-AzLoadBalancerRuleConfig.md
  src/Network/Network/help/Set-AzLoadBalancerRuleConfig.md
Labels: Waiting for CI :shipit:

#13108 Polish chagnelog for upcoming release
  src/Accounts/Accounts/ChangeLog.md
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/Databricks/ChangeLog.md
  src/EventHub/EventHub/ChangeLog.md
  src/IotHub/IotHub/ChangeLog.md
  src/MariaDb/ChangeLog.md
  src/Monitor/Monitor/ChangeLog.md
  src/RedisCache/RedisCache/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
  tools/VersionController/MinimalVersion.csv
Labels: needs-review
