Repository Azure/azure-powershell, pull requests merged in 2020-07, with the labels that each got.

#12291 invoke-azrest
  src/Accounts/Accounts.Test/ErrorResolutionTests.cs
  src/Accounts/Accounts.Test/InvokeAzRestTests.cs
  src/Accounts/Accounts.Test/InvokeAzRestTests.ps1
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.InvokeAzRestTests/TestInvokeAzRest.json
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/PSAzureOperationResponse.cs
  src/Accounts/Accounts/Models/PSHttpResponse.cs
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
  src/Accounts/Accounts/help/Az.Accounts.md
  src/Accounts/Accounts/help/Invoke-AzRestMethod.md
Labels: needs-review

#12293 fix static analysis error for Azure.Core
  tools/StaticAnalysis/BreakingChangeAnalyzer/BreakingChangeAnalyzer.cs
  tools/StaticAnalysis/DependencyAnalyzer/DependencyAnalyzer.cs
  tools/StaticAnalysis/HelpAnalyzer/HelpAnalyzer.cs
  tools/StaticAnalysis/SharedAssemblyLoader.cs
  tools/StaticAnalysis/SignatureVerifier/SignatureVerifier.cs
Labels: needs-review

#12283 String with escape chars cannot be converted into json object
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/PowershellJsonConverter.cs
Labels: needs-review

#12202 [Synapse] Make Synapse PowerShell consume track 2 Spark SDK
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkJob/GetAzureSynapseSparkJob.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkJob/StopAzureSynapseSparkJob.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkJob/SubmitAzureSynapseSparkJob.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkJob/WaitAzureSynapseSparkJob.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkSession/GetAzureSynapseSparkSession.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkSession/ResetAzureSynapseSparkSessionTimeout.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkSession/StartAzureSynapseSparkSession.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkSession/StopAzureSynapseSparkSession.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkStatement/GetAzureSynapseSparkStatement.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkStatement/InvokeAzureSynapseSparkStatement.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkStatement/StopAzureSynapseSparkStatement.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Firewall/GetAzureSynapseFirewallRule.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Firewall/NewAzureSynapseFirewallRule.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Firewall/RemoveAzureSynapseFirewallRule.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Firewall/UpdateAzureSynapseFirewallRule.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/GetAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/NewAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/RemoveAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/TestAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/UpdateAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/GetAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/NewAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/RemoveAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/TestAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/UpdateAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/GetAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/NewAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/RemoveAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/TestAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/UpdateAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Common/AzureSessionCredential.cs
  src/Synapse/Synapse/Models/PSLivyBatchStateInformation.cs
  src/Synapse/Synapse/Models/PSLivyRequestBase.cs
  src/Synapse/Synapse/Models/PSLivySessionStateInformation.cs
  src/Synapse/Synapse/Models/PSLivyStateInformation.cs
  src/Synapse/Synapse/Models/PSLivyStatementOutput.cs
  src/Synapse/Synapse/Models/PSSchedulerInformation.cs
  src/Synapse/Synapse/Models/PSSparkServicePluginInformation.cs
  src/Synapse/Synapse/Models/PSSynapseExtendedSparkStatement.cs
  src/Synapse/Synapse/Models/PSSynapseSparkJob.cs
  src/Synapse/Synapse/Models/PSSynapseSparkJobInformationBase.cs
  src/Synapse/Synapse/Models/PSSynapseSparkSession.cs
  src/Synapse/Synapse/Models/PSSynapseSparkStatement.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsSparkClient.cs
  src/Synapse/Synapse/Models/SynapseCmdletBase.cs
  src/Synapse/Synapse/Models/SynapseManagementCmdletBase.cs
  src/Synapse/Synapse/Models/SynapseSparkCmdletBase.cs
  src/Synapse/Synapse/Synapse.csproj
Labels: needs-review

#12271 Modifying the HelpText for AzRecoveryServiceBackup cmdlets
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/RegisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesBackupAutoProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/EnableAzureRmRecoveryServicesBackupAutoProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRMRecoveryServicesBackupProtectableItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/InitializeAzureRmRecoveryServicesBackupProtectableItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/UndoAzureRmRecoveryServicesBackupItemDeletion.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJob.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupRetentionPolicyObject.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupSchedulePolicyObject.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Backup-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupAutoProtection.md
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupAutoProtection.md
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJob.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJobDetail.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectableItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRPMountScript.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryLogChain.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRetentionPolicyObject.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupSchedulePolicyObject.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupStatus.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupWorkloadRecoveryConfig.md
  src/RecoveryServices/RecoveryServices/help/Initialize-AzRecoveryServicesBackupProtectableItem.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Register-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Remove-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProperty.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
  src/RecoveryServices/RecoveryServices/help/Stop-AzRecoveryServicesBackupJob.md
  src/RecoveryServices/RecoveryServices/help/Undo-AzRecoveryServicesBackupItemDeletion.md
  src/RecoveryServices/RecoveryServices/help/Unregister-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Unregister-AzRecoveryServicesBackupManagementServer.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: needs-review

#12302 Update private link
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: needs-review

#12305 Update Network owners
  .github/CODEOWNERS
Labels: needs-review

#12273 Create Unregister-AzResourceProvider Cmdlet
  src/Resources/ResourceManager/Implementation/Features/UnregisterAzureProviderFeatureCmdlet.cs
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/SdkClient/ProviderFeatureClient.cs
  src/Resources/Resources.Test/Features/UnregisterProviderFeatureCmdletTests.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/ProviderFeatureTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ProviderFeatureTests/TestAzureProviderFeature.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagCreateOrUpdateWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagCreateOrUpdateWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagDeleteWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagDeleteWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagGetWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagGetWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagUpdateWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagUpdateWithResourceIdParamsForSubscription.json
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Unregister-AzProviderFeature.md
Labels: needs-review

#12301 Remove Sha256Checksum parameter of example of New-AzImageBuilderCustomizerObject.
  src/ImageBuilder/Az.ImageBuilder.psm1
  src/ImageBuilder/ChangeLog.md
  src/ImageBuilder/check-dependencies.ps1
  src/ImageBuilder/examples/New-AzImageBuilderCustomizerObject.md
  src/ImageBuilder/exports/New-AzImageBuilderCustomizerObject.ps1
  src/ImageBuilder/exports/ProxyCmdletDefinitions.ps1
  src/ImageBuilder/generate-info.json
  src/ImageBuilder/generated/runtime/BuildTime/Cmdlets/ExportPsd1.cs
  src/ImageBuilder/help/Az.ImageBuilder.md
  src/ImageBuilder/help/New-AzImageBuilderCustomizerObject.md
  src/ImageBuilder/readme.md
Labels: Azure PS Team, Doc - Reference, ImageBuilder, needs-review

#12233 Introducing Az.Security AllowedConnection cmdlets
  src/Security/Security.Test/ScenarioTests/AllowedConnectionTests.cs
  src/Security/Security.Test/ScenarioTests/AllowedConnectionTests.ps1
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.AllowedConnectionTests/GetResourceGroupLevelResource.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.AllowedConnectionTests/GetResourceId.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.AllowedConnectionTests/GetSubscriptionScope.json
  src/Security/Security/Az.Security.psd1
  src/Security/Security/ChangeLog.md
  src/Security/Security/Cmdlets/AllowedConnection/GetAllowedConnection.cs
  src/Security/Security/Models/AllowedConnection/PSSecurityAllowedConnection.cs
  src/Security/Security/Models/AllowedConnection/PSSecurityConnectableResources.cs
  src/Security/Security/Models/AllowedConnection/PSSecurityConnectableResourcesConverters.cs
  src/Security/Security/Models/AllowedConnection/PSSecurityConnectedResource.cs
  src/Security/Security/help/Get-AzAllowedConnection.md
Labels: needs-review

#12300 adding warning when using new-azvmss and not using "latest" image version
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetImageVersion.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
Labels: needs-review

#12290 Az.DataFactory update to include Global Parameters
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.cs
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.DataFactoryTests/TestUpdateFactoryGlobalParameters.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/DataFactories/SetAzureDataFactoryCommand.cs
  src/DataFactory/DataFactoryV2/Models/CreatePSDataFactoryParameters.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.DataFactories.cs
  src/DataFactory/DataFactoryV2/Models/PSDataFactory.cs
  src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2.md
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2.md
Labels: needs-review

#12308 Adding support for fetching MAB agent jobs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/ServiceClientHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/MabModels/MabJob.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJob.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJob.md
Labels: needs-review

#12309 [Synapse] Add access control cmdlets
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/GetAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/GetAzureSynapseRoleDefinition.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/NewAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/RemoveAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/PSRoleAssignmentDetails.cs
  src/Synapse/Synapse/Models/PSSynapseRole.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsRoleClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Models/SynapseRoleCmdletBase.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/Synapse.csproj
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Get-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Get-AzSynapseRoleDefinition.md
  src/Synapse/Synapse/help/New-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Remove-AzSynapseRoleAssignment.md
Labels: needs-review

#12319 Fix bug: Get-AzAks doesn't get all clusters
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/GetAzureRmAks.cs
  src/Aks/Aks/Commands/GetAzureRmAksNodePool.cs
  src/Aks/Aks/Commands/KubeCmdletBase.cs
Labels: needs-review

#12297 Az.MonitoringSolutions
  src/MonitoringSolutions/.gitattributes
  src/MonitoringSolutions/.gitignore
  src/MonitoringSolutions/custom/New-AzMonitorLogAnalyticsSolution.ps1
  src/MonitoringSolutions/custom/readme.md
  src/MonitoringSolutions/docs/Az.MonitoringSolutions.md
  src/MonitoringSolutions/docs/Get-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/docs/New-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/docs/Remove-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/docs/Update-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/docs/readme.md
  src/MonitoringSolutions/examples/Get-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/examples/New-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/examples/Remove-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/examples/Update-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/how-to.md
  src/MonitoringSolutions/license.txt
  src/MonitoringSolutions/readme.md
  src/MonitoringSolutions/resources/readme.md
  src/MonitoringSolutions/test/Get-AzMonitorLogAnalyticsSolution.Recording.json
  src/MonitoringSolutions/test/Get-AzMonitorLogAnalyticsSolution.Tests.ps1
  src/MonitoringSolutions/test/New-AzMonitorLogAnalyticsSolution.Recording.json
  src/MonitoringSolutions/test/New-AzMonitorLogAnalyticsSolution.Tests.ps1
  src/MonitoringSolutions/test/Remove-AzMonitorLogAnalyticsSolution.Recording.json
  src/MonitoringSolutions/test/Remove-AzMonitorLogAnalyticsSolution.Tests.ps1
  src/MonitoringSolutions/test/Update-AzMonitorLogAnalyticsSolution.Recording.json
  src/MonitoringSolutions/test/Update-AzMonitorLogAnalyticsSolution.Tests.ps1
  src/MonitoringSolutions/test/deployment-templates/operational-insightsworkspace/parameters.json
  src/MonitoringSolutions/test/deployment-templates/operational-insightsworkspace/template.json
  src/MonitoringSolutions/test/env.json
  src/MonitoringSolutions/test/loadEnv.ps1
  src/MonitoringSolutions/test/readme.md
  src/MonitoringSolutions/test/utils.ps1
Labels: needs-review

#12321 Update Add-AzApplicationGatewayBackendAddressPool.md
  src/Network/Network/help/Add-AzApplicationGatewayBackendAddressPool.md
Labels: needs-review

#12317 Add default provider support to Az.Attestation module
  src/Attestation/Attestation.Test/Attestation.Test.csproj
  src/Attestation/Attestation.Test/SamplePolicyFiles/SgxAllowDebugMode.txt
  src/Attestation/Attestation.Test/SamplePolicyFiles/SgxDisableDebugMode.txt
  src/Attestation/Attestation.Test/SamplePolicyFiles/SgxRequireSqlServer.txt
  src/Attestation/Attestation.Test/SamplePolicyFiles/SgxRequireSqlServerBogusMrSigner.txt
  src/Attestation/Attestation.Test/SamplePolicySignerFiles/cert1.pem
  src/Attestation/Attestation.Test/SamplePolicySignerFiles/cert2.signed.txt
  src/Attestation/Attestation.Test/SamplePolicySignerFiles/cert3.signed.txt
  src/Attestation/Attestation.Test/SamplePolicySignerFiles/cert4.signed.txt
  src/Attestation/Attestation.Test/SamplePolicySignerFiles/cert5.signed.txt
  src/Attestation/Attestation.Test/ScenarioTests/AttestationPolicySignerTests.ps1
  src/Attestation/Attestation.Test/ScenarioTests/AttstationPolicySignerTests.cs
  src/Attestation/Attestation.Test/ScenarioTests/AttstationPolicyTests.cs
  src/Attestation/Attestation.Test/ScenarioTests/AttstationPolicyTests.ps1
  src/Attestation/Attestation.Test/ScenarioTests/AttstationTests.cs
  src/Attestation/Attestation.Test/ScenarioTests/AttstationTests.ps1
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttestationPolicySignerTests/TestAddAttestationPolicySigner.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttestationPolicySignerTests/TestGetAttestationPolicySigners.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttestationPolicySignerTests/TestGetDefaultProviderPolicySigners.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttestationPolicySignerTests/TestRemoveAttestationPolicySigner.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationPolicyTests/TestGetAttestationPolicy.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationPolicyTests/TestGetDefaultProviderPolicy.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationPolicyTests/TestResetAttestationPolicy.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestCreateAttestation.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestCreateAttestationWithPolicySigningCertificate.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestCreateAttestationWithTags.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestDeleteAttestationByName.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestGetAttestation.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestGetDefaultProviderByLocation.json
  src/Attestation/Attestation.Test/SessionRecords/Microsoft.Azure.Commands.Attestation.Test.ScenarioTests.AttstationTests/TestGetDefaultProviders.json
  src/Attestation/Attestation/Attestation.csproj
  src/Attestation/Attestation/ChangeLog.md
  src/Attestation/Attestation/Commands/AddAzAttestationPolicySigner.cs
  src/Attestation/Attestation/Commands/GetAzureAttestation.cs
  src/Attestation/Attestation/Commands/GetAzureAttestationPolicy.cs
  src/Attestation/Attestation/Commands/GetAzureAttestationPolicySigners.cs
  src/Attestation/Attestation/Commands/RemoveAzAttestationPolicySigner.cs
  src/Attestation/Attestation/Models/AttestationDataServiceClient.cs
  src/Attestation/Attestation/Models/AttestationDataServiceCmdletBase.cs
  src/Attestation/Attestation/Models/AttestationManagementClient.cs
  src/Attestation/Attestation/Models/PSAttestation.cs
  src/Attestation/Attestation/Models/PSPolicySigners.cs
  src/Attestation/Attestation/help/Add-AzAttestationPolicySigner.md
  src/Attestation/Attestation/help/Get-AzAttestation.md
  src/Attestation/Attestation/help/Get-AzAttestationPolicy.md
  src/Attestation/Attestation/help/Get-AzAttestationPolicySigners.md
  src/Attestation/Attestation/help/Remove-AzAttestationPolicySigner.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#12310 {HDInsight} Support creating cluster with ADLSGen1/2 storage in national clouds
  src/HDInsight/HDInsight.Test/ScenarioTests/Common.ps1
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestClusterRelatedCommands.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCmkClusterRelatedCommands.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightHostTests/TestHostRelatedCommands.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightSetGatewayCredentialTest/TestSetGatewayCredential.json
  src/HDInsight/HDInsight.Test/UnitTests/NewClusterTests.cs
  src/HDInsight/HDInsight.Test/UnitTests/PremiumClusterTests.cs
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/Models/Management/AzureHdInsightManagementClient.cs
Labels: needs-review

#12311 Authentication.csproj should not be referenced by module project
  src/AnalysisServices/AnalysisServices.Dataplane/AnalysisServices.Dataplane.csproj
  src/AnalysisServices/AnalysisServices.Dataplane/Models/AsAzureDataplaneCmdletBase.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Properties/Resources.Designer.cs
  src/AnalysisServices/AnalysisServices.Dataplane/Properties/Resources.resx
  src/AnalysisServices/AnalysisServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Common/PSRecoveryServicesClient.cs
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
Labels: needs-review

#12318 Add test cases and examples for kubernetes configuration.
  src/KubernetesConfiguration/docs/Az.KubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/readme.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/test/Az.KubernetesConfiguration-TestResults.xml
  src/KubernetesConfiguration/test/Get-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/Get-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/New-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/New-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/env.json
  src/KubernetesConfiguration/test/loadEnv.ps1
  src/KubernetesConfiguration/test/readme.md
  src/KubernetesConfiguration/test/utils.ps1
Labels: Kubernetes Configuration, needs-review

#12277 Custom providers
  src/CustomProviders/.gitattributes
  src/CustomProviders/.gitignore
  src/CustomProviders/Az.CustomProviders.psd1
  src/CustomProviders/custom/readme.md
  src/CustomProviders/docs/Az.CustomProviders.md
  src/CustomProviders/docs/Get-AzCustomProvider.md
  src/CustomProviders/docs/Get-AzCustomProviderAssociation.md
  src/CustomProviders/docs/New-AzCustomProvider.md
  src/CustomProviders/docs/New-AzCustomProviderAssociation.md
  src/CustomProviders/docs/Remove-AzCustomProvider.md
  src/CustomProviders/docs/Remove-AzCustomProviderAssociation.md
  src/CustomProviders/docs/Update-AzCustomProvider.md
  src/CustomProviders/docs/readme.md
  src/CustomProviders/examples/Get-AzCustomProvider.md
  src/CustomProviders/examples/Get-AzCustomProviderAssociation.md
  src/CustomProviders/examples/New-AzCustomProvider.md
  src/CustomProviders/examples/New-AzCustomProviderAssociation.md
  src/CustomProviders/examples/Remove-AzCustomProvider.md
  src/CustomProviders/examples/Remove-AzCustomProviderAssociation.md
  src/CustomProviders/examples/Update-AzCustomProvider.md
  src/CustomProviders/how-to.md
  src/CustomProviders/license.txt
  src/CustomProviders/readme.md
  src/CustomProviders/resources/readme.md
  src/CustomProviders/test/Az.CustomProviderCrud.Recording.json
  src/CustomProviders/test/AzCustomProviderCrud.Tests.ps1
  src/CustomProviders/test/Get-AzCustomProvider.Tests.ps1
  src/CustomProviders/test/Get-AzCustomProviderAssociation.Tests.ps1
  src/CustomProviders/test/New-AzCustomProvider.Tests.ps1
  src/CustomProviders/test/New-AzCustomProviderAssociation.Tests.ps1
  src/CustomProviders/test/Remove-AzCustomProvider.Tests.ps1
  src/CustomProviders/test/Remove-AzCustomProviderAssociation.Tests.ps1
  src/CustomProviders/test/Set-AzCustomProviderAssociation.Tests.ps1
  src/CustomProviders/test/Update-AzCustomProvider.Tests.ps1
  src/CustomProviders/test/env.json
  src/CustomProviders/test/loadEnv.ps1
  src/CustomProviders/test/localEnv.json
  src/CustomProviders/test/readme.md
  src/CustomProviders/test/utils.ps1
Labels: needs-review

#12325 Add test cases and examples of CostManagement.
  src/CostManagement/docs/Az.Cost.md
  src/CostManagement/docs/Get-AzCostManagementExport.md
  src/CostManagement/docs/Get-AzCostManagementExportExecutionHistory.md
  src/CostManagement/docs/Invoke-AzCostManagementExecuteExport.md
  src/CostManagement/docs/Invoke-AzCostManagementUsageQuery.md
  src/CostManagement/docs/New-AzCostManagementExport.md
  src/CostManagement/docs/New-AzCostManagementQueryColumnObject.md
  src/CostManagement/docs/New-AzCostManagementQueryComparisonExpressionObject.md
  src/CostManagement/docs/New-AzCostManagementQueryFilterObject.md
  src/CostManagement/docs/Remove-AzCostManagementExport.md
  src/CostManagement/docs/Update-AzCostManagementExport.md
  src/CostManagement/docs/readme.md
  src/CostManagement/examples/Get-AzCostManagementExport.md
  src/CostManagement/examples/Get-AzCostManagementExportExecutionHistory.md
  src/CostManagement/examples/Invoke-AzCostManagementExecuteExport.md
  src/CostManagement/examples/Invoke-AzCostManagementUsageQuery.md
  src/CostManagement/examples/New-AzCostManagementExport.md
  src/CostManagement/examples/New-AzCostManagementQueryColumnObject.md
  src/CostManagement/examples/New-AzCostManagementQueryComparisonExpressionObject.md
  src/CostManagement/examples/New-AzCostManagementQueryFilterObject.md
  src/CostManagement/examples/Remove-AzCostManagementExport.md
  src/CostManagement/examples/Update-AzCostManagementExport.md
  src/CostManagement/readme.md
  src/CostManagement/test/Az.Cost-TestResults.xml
  src/CostManagement/test/Get-AzCostManagementExport.Recording.json
  src/CostManagement/test/Get-AzCostManagementExport.Tests.ps1
  src/CostManagement/test/Get-AzCostManagementExportExecutionHistory.Recording.json
  src/CostManagement/test/Get-AzCostManagementExportExecutionHistory.Tests.ps1
  src/CostManagement/test/Invoke-AzCostManagementExecuteExport.Recording.json
  src/CostManagement/test/Invoke-AzCostManagementExecuteExport.Tests.ps1
  src/CostManagement/test/Invoke-AzCostManagementUsageQuery.Tests.ps1
  src/CostManagement/test/New-AzCostManagementExport.Recording.json
  src/CostManagement/test/New-AzCostManagementExport.Tests.ps1
  src/CostManagement/test/New-AzCostManagementQueryColumnObject.Tests.ps1
  src/CostManagement/test/New-AzCostManagementQueryComparisonExpressionObject.Tests.ps1
  src/CostManagement/test/New-AzCostManagementQueryFilterObject.Tests.ps1
  src/CostManagement/test/Remove-AzCostManagementExport.Recording.json
  src/CostManagement/test/Remove-AzCostManagementExport.Tests.ps1
  src/CostManagement/test/Update-AzCostManagementExport.Tests.ps1
  src/CostManagement/test/deployment-templates/storage-account/parameters.json
  src/CostManagement/test/deployment-templates/storage-account/template.json
  src/CostManagement/test/env.json
  src/CostManagement/test/loadEnv.ps1
  src/CostManagement/test/readme.md
  src/CostManagement/test/test-script.ps1
  src/CostManagement/test/utils.ps1
Labels: Cost Management

#12323 [Storage] Support Blobversion with Track2 SDK
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobIsVersioningEnabled.json
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/Blob/UpdateAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSBlobServiceProperties.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/help/Get-AzStorageBlob.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobContent.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobServiceProperty.md
  src/Storage/Storage.Management/help/New-AzStorageBlobSASToken.md
  src/Storage/Storage.Management/help/Remove-AzStorageBlob.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
  src/Storage/Storage.Management/help/Start-AzStorageBlobCopy.md
  src/Storage/Storage.Management/help/Update-AzStorageBlobServiceProperty.md
  src/Storage/Storage.Test/Service/MockStorageBlobManagement.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobCopyState.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageBlobSasToken.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/StartAzureStorageBlobCopy.cs
  src/Storage/Storage/Blob/Cmdlet/StopAzureStorageBlobCopy.cs
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Blob/StorageDataMovementCmdletBase.cs
  src/Storage/Storage/Common/AzureStorageBlob.cs
  src/Storage/Storage/Common/AzureStorageContainer.cs
  src/Storage/Storage/Common/InvalidCloudBlob.cs
  src/Storage/Storage/Common/StorageExtensions.cs
  src/Storage/Storage/Common/UserAgent.cs
  src/Storage/Storage/Common/Util.cs
  src/Storage/Storage/Model/Contract/IStorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/StorageBlobManagement.cs
  src/Storage/Storage/Resources.Designer.cs
  src/Storage/Storage/Resources.resx
  src/Storage/Storage/Storage.csproj
  src/Storage/Storage/Storage.generated.format.ps1xml
Labels: needs-review

#12330 First release of Az.HanaOnAzure
  src/HanaOnAzure/.gitignore
  src/HanaOnAzure/Az.Hana.psd1
  src/HanaOnAzure/Az.HanaOnAzure.psd1
  src/HanaOnAzure/custom/New-AzSapMonitorProviderInstance.ps1
  src/HanaOnAzure/custom/readme.md
  src/HanaOnAzure/docs/Az.HanaOnAzure.md
  src/HanaOnAzure/docs/Get-AzSapMonitor.md
  src/HanaOnAzure/docs/Get-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/docs/New-AzSapMonitor.md
  src/HanaOnAzure/docs/New-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/docs/Remove-AzSapMonitor.md
  src/HanaOnAzure/docs/Remove-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/docs/Update-AzSapMonitor.md
  src/HanaOnAzure/docs/readme.md
  src/HanaOnAzure/examples/Get-AzSapMonitor.md
  src/HanaOnAzure/examples/Get-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/examples/New-AzSapMonitor.md
  src/HanaOnAzure/examples/New-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/examples/Remove-AzSapMonitor.md
  src/HanaOnAzure/examples/Remove-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/examples/Update-AzSapMonitor.md
  src/HanaOnAzure/examples/latest-2019-04-30/Get-AzHanaInstance.md
  src/HanaOnAzure/examples/latest-2019-04-30/New-AzHanaInstance.md
  src/HanaOnAzure/examples/latest-2019-04-30/Remove-AzHanaInstance.md
  src/HanaOnAzure/examples/latest-2019-04-30/Restart-AzHanaInstance.md
  src/HanaOnAzure/examples/latest-2019-04-30/Start-AzHanaInstance.md
  src/HanaOnAzure/examples/latest-2019-04-30/Stop-AzHanaInstance.md
  src/HanaOnAzure/examples/latest-2019-04-30/Update-AzHanaInstance.md
  src/HanaOnAzure/examples/readme.md
  src/HanaOnAzure/how-to.md
  src/HanaOnAzure/readme.md
  src/HanaOnAzure/test/Get-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/Get-AzSapMonitor.Tests.ps1
  src/HanaOnAzure/test/Get-AzSapMonitorProviderInstance.Recording.json
  src/HanaOnAzure/test/Get-AzSapMonitorProviderInstance.Tests.ps1
  src/HanaOnAzure/test/New-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/New-AzSapMonitor.Tests.ps1
  src/HanaOnAzure/test/New-AzSapMonitorProviderInstance.Recording.json
  src/HanaOnAzure/test/New-AzSapMonitorProviderInstance.Tests.ps1
  src/HanaOnAzure/test/Remove-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/Remove-AzSapMonitor.Tests.ps1
  src/HanaOnAzure/test/Remove-AzSapMonitorProviderInstance.Recording.json
  src/HanaOnAzure/test/Remove-AzSapMonitorProviderInstance.Tests.ps1
  src/HanaOnAzure/test/Update-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/Update-AzSapMonitor.Tests.ps1
  src/HanaOnAzure/test/env.json
  src/HanaOnAzure/test/loadEnv.ps1
  src/HanaOnAzure/test/readme.md
  src/HanaOnAzure/test/utils.ps1
  src/helpers/KeyVault/readme.noprofile.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#12254 [ConnectedKubernetes] Init for ConnectedKubernetes
  src/ConnectedKubernetes/Az.ConnectedKubernetes.psd1
  src/ConnectedKubernetes/custom/Az.ConnectedKubernetes.custom.psm1
  src/ConnectedKubernetes/custom/New-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/custom/Remove-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/custom/Update-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/custom/readme.md
  src/ConnectedKubernetes/docs/Az.ConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Get-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Remove-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Update-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/readme.md
  src/ConnectedKubernetes/examples/Get-AzConnectedKubernetes.md
  src/ConnectedKubernetes/examples/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/examples/Remove-AzConnectedKubernetes.md
  src/ConnectedKubernetes/examples/Update-AzConnectedKubernetes.md
  src/ConnectedKubernetes/readme.md
  src/ConnectedKubernetes/test/Get-AzConnectedKubernetes.Recording.json
  src/ConnectedKubernetes/test/Get-AzConnectedKubernetes.Tests.ps1
  src/ConnectedKubernetes/test/New-AzConnectedKubernetes.Recording.json
  src/ConnectedKubernetes/test/New-AzConnectedKubernetes.Tests.ps1
  src/ConnectedKubernetes/test/Remove-AzConnectedKubernetes.Recording.json
  src/ConnectedKubernetes/test/Remove-AzConnectedKubernetes.Tests.ps1
  src/ConnectedKubernetes/test/Update-AzConnectedKubernetes.Recording.json
  src/ConnectedKubernetes/test/Update-AzConnectedKubernetes.Tests.ps1
  src/ConnectedKubernetes/test/env.json
  src/ConnectedKubernetes/test/loadEnv.ps1
  src/ConnectedKubernetes/test/readme.md
  src/ConnectedKubernetes/test/utils.ps1
Labels: Generator, needs-review

#12337 [KubernetesConfiguration] Init for KubernetesConfiguration
  src/KubernetesConfiguration/custom/New-AzKubernetesConfiguration.ps1
  src/KubernetesConfiguration/custom/Remove-AzKubernetesConfiguration.ps1
  src/KubernetesConfiguration/custom/readme.md
  src/KubernetesConfiguration/docs/Az.KubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/readme.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/readme.md
  src/KubernetesConfiguration/test/Get-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/Get-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/New-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/New-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/env.json
  src/KubernetesConfiguration/test/loadEnv.ps1
  src/KubernetesConfiguration/test/readme.md
  src/KubernetesConfiguration/test/utils.ps1
Labels: Generator, needs-review

#12356 Fix version compare scripts in psm1
  tools/UpdateModules.ps1
Labels: needs-review

#12339 Public Preview of Az.AzureStackHCI module
  src/StackHCI/StackHCI/Az.StackHCI.psd1
  src/StackHCI/StackHCI/Az.StackHCI.psm1
  src/StackHCI/StackHCI/ChangeLog.md
  src/StackHCI/StackHCI/Help/Register-AzStackHCI.md
  src/StackHCI/StackHCI/Help/Unregister-AzStackHCI.md
Labels: needs-revision

#12340 Fix typo in Get-AzKeyVaultCertificate.md documentation
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificate.md
Labels: needs-revision

#12268 Lower case server name in upsert server operation
  src/Sql/Sql.Test/ScenarioTests/VulnerabilityAssessmentTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests/VulnerabilityAssessmentServerSettingsTest.json
  src/Sql/Sql.Test/UnitTests/AzureSqlUtilTests.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/Services/Util.cs
Labels: needs-review

#12358 Update Frontdoor module to use latest SDK - RP API v2020-05-01
  src/FrontDoor/FrontDoor.Test/FrontDoor.Test.csproj
  src/FrontDoor/FrontDoor.Test/ScenarioTests/FrontDoorTests.cs
  src/FrontDoor/FrontDoor.Test/ScenarioTests/FrontDoorTests.ps1
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrud.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrudDefaults.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrudPrivateLink.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrudRedirect.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorCrudWithPiping.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestManagedRuleSetDefinitions.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestPolicyCrud.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestPolicyCrudWithPiping.json
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewFrontDoorBackendObject.cs
  src/FrontDoor/FrontDoor/FrontDoor.csproj
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
  src/FrontDoor/FrontDoor/Models/PSBackend.cs
  src/FrontDoor/FrontDoor/help/Get-AzFrontDoorRulesEngine.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorBackendObject.md
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorRulesEngine.md
  src/FrontDoor/FrontDoor/help/Remove-AzFrontDoorRulesEngine.md
Labels: needs-revision

#12363 Add one example on Add-AzEnvironment
  src/Accounts/Accounts/help/Add-AzEnvironment.md
Labels: needs-review

#12368 Fix broken links related to developer guide
  documentation/development-docs/azure-powershell-developer-guide.md
  documentation/development-docs/design-guidelines/cmdlet-best-practices.md
  documentation/development-docs/design-guidelines/should-process-confirm-impact.md
  documentation/development-docs/generate-format.ps1xml-file.md
  documentation/development-docs/help-generation.md
Labels: needs-review

#12362 [Network] Zone-redundant Public IP address
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/LoadBalancer/FrontendIPConfiguration/NewAzureRmLoadBalancerFrontendIpConfigCommand.cs
  src/Network/Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
  src/Network/Network/PublicIpPrefix/NewAzurePublicIpPrefixCommand.cs
Labels: needs-review

#12288 update docs
  src/DesktopVirtualization/custom/New-AzWvdHostPool_FullSenerioCreate.ps1
  src/DesktopVirtualization/custom/New-AzWvdRegistrationInfo.ps1
  src/DesktopVirtualization/custom/Remove-AzWvdRegistrationInfo.ps1
  src/DesktopVirtualization/docs/Az.DesktopVirtualization.md
  src/DesktopVirtualization/docs/New-AzWvdApplication.md
  src/DesktopVirtualization/docs/New-AzWvdApplicationGroup.md
  src/DesktopVirtualization/docs/New-AzWvdHostPool.md
  src/DesktopVirtualization/docs/New-AzWvdWorkspace.md
  src/DesktopVirtualization/docs/Update-AzWvdApplication.md
  src/DesktopVirtualization/docs/Update-AzWvdApplicationGroup.md
  src/DesktopVirtualization/docs/Update-AzWvdDesktop.md
  src/DesktopVirtualization/docs/Update-AzWvdHostPool.md
  src/DesktopVirtualization/docs/Update-AzWvdWorkspace.md
  src/DesktopVirtualization/readme.md
  src/DesktopVirtualization/test/Az.DesktopVirtualization-TestResults.xml
  src/DesktopVirtualization/test/Get-AzWvdApplicationGroup.Recording.json
  src/DesktopVirtualization/test/Get-AzWvdApplicationGroup.Tests.ps1
  src/DesktopVirtualization/test/Get-AzWvdHostPool.Recording.json
  src/DesktopVirtualization/test/Get-AzWvdHostPool.Tests.ps1
  src/DesktopVirtualization/test/Get-AzWvdRegistrationInfo.Recording.json
  src/DesktopVirtualization/test/Get-AzWvdRegistrationInfo.Tests.ps1
  src/DesktopVirtualization/test/New-AzWvdApplicationGroup.Recording.json
  src/DesktopVirtualization/test/New-AzWvdApplicationGroup.Tests.ps1
  src/DesktopVirtualization/test/New-AzWvdHostPool.Recording.json
  src/DesktopVirtualization/test/New-AzWvdHostPool.Tests.ps1
  src/DesktopVirtualization/test/New-AzWvdRegistrationInfo.Recording.json
  src/DesktopVirtualization/test/New-AzWvdRegistrationInfo.Tests.ps1
  src/DesktopVirtualization/test/Register-AzWvdApplicationGroup.Recording.json
  src/DesktopVirtualization/test/Register-AzWvdApplicationGroup.Tests.ps1
  src/DesktopVirtualization/test/Remove-AzWvdApplicationGroup.Recording.json
  src/DesktopVirtualization/test/Remove-AzWvdApplicationGroup.Tests.ps1
  src/DesktopVirtualization/test/Remove-AzWvdHostPool.Recording.json
  src/DesktopVirtualization/test/Remove-AzWvdHostPool.Tests.ps1
  src/DesktopVirtualization/test/Remove-AzWvdRegistrationInfo.Recording.json
  src/DesktopVirtualization/test/Remove-AzWvdRegistrationInfo.Tests.ps1
  src/DesktopVirtualization/test/Unregister-AzWvdApplicationGroup.Recording.json
  src/DesktopVirtualization/test/Unregister-AzWvdApplicationGroup.Tests.ps1
  src/DesktopVirtualization/test/Update-AzWvdApplicationGroup.Recording.json
  src/DesktopVirtualization/test/Update-AzWvdApplicationGroup.Tests.ps1
  src/DesktopVirtualization/test/Update-AzWvdHostPool.Recording.json
  src/DesktopVirtualization/test/Update-AzWvdHostPool.Tests.ps1
  src/DesktopVirtualization/test/env.json
  src/DesktopVirtualization/test/utils.ps1
Labels: needs-review

#12428 Aladdin generated examples for Resources
  src/Resources/Resources/help/Add-AzADGroupMember.md
  src/Resources/Resources/help/Get-AzADAppCredential.md
  src/Resources/Resources/help/Get-AzADGroup.md
  src/Resources/Resources/help/Get-AzADGroupMember.md
  src/Resources/Resources/help/Get-AzADServicePrincipal.md
  src/Resources/Resources/help/Get-AzADUser.md
  src/Resources/Resources/help/Get-AzDeploymentOperation.md
  src/Resources/Resources/help/Get-AzProviderOperation.md
  src/Resources/Resources/help/Get-AzResourceGroupDeploymentOperation.md
  src/Resources/Resources/help/Get-AzResourceGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/New-AzADApplication.md
  src/Resources/Resources/help/New-AzADGroup.md
  src/Resources/Resources/help/New-AzADSpCredential.md
  src/Resources/Resources/help/New-AzADUser.md
  src/Resources/Resources/help/New-AzResourceGroupDeployment.md
  src/Resources/Resources/help/New-AzRoleDefinition.md
  src/Resources/Resources/help/Remove-AzADAppCredential.md
  src/Resources/Resources/help/Remove-AzADApplication.md
  src/Resources/Resources/help/Remove-AzADGroup.md
  src/Resources/Resources/help/Remove-AzADGroupMember.md
  src/Resources/Resources/help/Remove-AzADSpCredential.md
  src/Resources/Resources/help/Remove-AzADUser.md
  src/Resources/Resources/help/Remove-AzManagementGroup.md
  src/Resources/Resources/help/Remove-AzManagementGroupSubscription.md
  src/Resources/Resources/help/Remove-AzResourceLock.md
  src/Resources/Resources/help/Save-AzResourceGroupDeploymentTemplate.md
  src/Resources/Resources/help/Set-AzManagedApplicationDefinition.md
  src/Resources/Resources/help/Set-AzRoleDefinition.md
  src/Resources/Resources/help/Update-AzADServicePrincipal.md
  src/Resources/Resources/help/Update-AzADUser.md
Labels: needs-review

#12430 Add the new switch parameter AllowActiveFTP to Firewall Command
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDWithAllowActiveFTP.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/Set-AzFirewall.md
Labels: needs-review

#12421 Fix wrong database name on existing database error for New-AzSqlDatabaseSecondary
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateNamedSecondaryDatabaseNegative.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
Labels: needs-review, needs-revision

#12397 Add parameter "MaxContextPopulation" for `Connect-AzAccount`
  src/Accounts/Accounts.Test/ConnectAzAccountScenarioTests.cs
  src/Accounts/Accounts.Test/ConnectAzAccountScenarioTests.ps1
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ConnectAzAccountScenarioTests/TestMaxContextPopulationGetAll.json
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ConnectAzAccountScenarioTests/TestMaxContextPopulationWithDefaultValue.json
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ConnectAzAccountScenarioTests/TestMaxContextPopulationWithSpecifiedValue.json
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/help/Connect-AzAccount.md
Labels: needs-review

#12443 [Storage] Support Track2 blob SAS and code revise
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageBlobSasToken.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainerSasToken.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/StartAzureStorageBlobCopy.cs
  src/Storage/Storage/Blob/Cmdlet/StopAzureStorageBlobCopy.cs
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Common/Cmdlet/NewAzureStorageAccountSasToken.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
Labels: needs-review

#12433 [RecoveryServices.Backup]Trigger AFS container/item discovery only when needed
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#12439 Support private offers in subscription level
  src/Marketplace/Marketplace.Test/Marketplace.Test.csproj
  src/Marketplace/Marketplace.Test/ScenarioTests/PrivateStoreTests.cs
  src/Marketplace/Marketplace.Test/ScenarioTests/PrivateStoreTests.ps1
  src/Marketplace/Marketplace.Test/SessionRecords/Microsoft.Azure.Commands.Marketplace.Test.ScenarioTests.PrivateStoreTests/TestGetPrivateStorePrivateOffer.json
  src/Marketplace/Marketplace.Test/SessionRecords/Microsoft.Azure.Commands.Marketplace.Test.ScenarioTests.PrivateStoreTests/TestUpdatePrivateStorePrivateOffer.json
  src/Marketplace/Marketplace/Az.Marketplace.psd1
  src/Marketplace/Marketplace/ChangeLog.md
  src/Marketplace/Marketplace/Cmdlets/GetAzMarketplacePrivateStoreOffer.cs
  src/Marketplace/Marketplace/Cmdlets/SetAzMarketplacePrivateStoreOffer.cs
  src/Marketplace/Marketplace/Marketplace.csproj
  src/Marketplace/Marketplace/help/Get-AzMarketplacePrivateStoreOffer.md
  src/Marketplace/Marketplace/help/Set-AzMarketplacePrivateStoreOffer.md
Labels: needs-review

#12436 Add test case to test the issue #11692
  src/Resources/Resources.Test/ScenarioTests/ResourceTests.cs
  src/Resources/Resources.Test/ScenarioTests/ResourceTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestGetComplexResourceByDifferentFiltersTest.json
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#12123 Generate Az.Databricks for CMK feature
  src/Databricks/.gitattributes
  src/Databricks/.gitignore
  src/Databricks/Az.Databricks.psd1
  src/Databricks/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/custom/readme.md
  src/Databricks/docs/Az.Databricks.md
  src/Databricks/docs/Get-AzDatabricksWorkspace.md
  src/Databricks/docs/New-AzDatabricksWorkspace.md
  src/Databricks/docs/Remove-AzDatabricksWorkspace.md
  src/Databricks/docs/Update-AzDatabricksWorkspace.md
  src/Databricks/examples/New-AzDatabricksWorkspace.md
  src/Databricks/examples/Remove-AzDatabricksWorkspace.md
  src/Databricks/examples/Update-AzDatabricksWorkspace.md
  src/Databricks/how-to.md
  src/Databricks/license.txt
  src/Databricks/readme.md
  src/Databricks/resources/readme.md
  src/Databricks/test/Get-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Get-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/New-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Remove-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/deployment-templates/key-vault/parameters.json
  src/Databricks/test/deployment-templates/key-vault/template.json
  src/Databricks/test/deployment-templates/virtual-network/parameters.json
  src/Databricks/test/env.json
  src/Databricks/test/readme.md
  src/Databricks/test/utils.ps1
Labels: Az 4.x Preview, needs-review

#12470 [Storage] Support share usage
  src/Storage/Storage.Management.Test/ScenarioTests/StorageFileTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageFileTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageFileTests/TestStorageFileShareGetUsage.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/File/GetAzureStorageShare.cs
  src/Storage/Storage.Management/Models/PSShare.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/help/Get-AzRmStorageShare.md
  src/Storage/Storage.Management/help/New-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Update-AzRmStorageShare.md
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: needs-review

#12479 EncryptionAtHost and SecurityProfile changes for New-AzVM, New-AzVMConfig and Update-AzVM
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskEncryptionSet.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestEncryptionAtHostVM.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestEncryptionAtHostVMDefaultParameterSet.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Models/PSVirtualMachine.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/Update-AzVM.md
Labels: needs-review

#12476 Correct reference doc for Add-AzEnvironment
  src/Accounts/Accounts/help/Add-AzEnvironment.md
Labels: needs-review

#12477 [Aks]Add some alias
  src/Aks/Aks/Az.Aks.psd1
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/Aks/Aks/Commands/GetAzureRmAks.cs
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Commands/NewKubeBase.cs
  src/Aks/Aks/Commands/RemoveAzureRmAks.cs
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  src/Aks/Aks/help/Az.Aks.md
  src/Aks/Aks/help/Get-AzAksCluster.md
  src/Aks/Aks/help/New-AzAksCluster.md
  src/Aks/Aks/help/Remove-AzAksCluster.md
  src/Aks/Aks/help/Set-AzAksCluster.md
Labels: needs-review

#12480 Fix the path issue on linux
  tools/StaticAnalysis/BreakingChangeAnalyzer/BreakingChangeAnalyzer.cs
Labels: needs-review

#12416 Call Tools.Common.dll in ps scripts to check whether a module is belong to AzureStack
  build.proj
  tools/CheckAssemblies.ps1
  tools/CreateAliasMapping.ps1
  tools/CreateFilterMappings.ps1
  tools/CreateMappings.ps1
  tools/GenerateHelp.ps1
  tools/NewHelpIndex.ps1
  tools/PreloadToolDll.ps1
  tools/RunVersionController.ps1
  tools/Tools.Common/AllowList.csv
  tools/Tools.Common/Tools.Common.Netcore.csproj
  tools/Tools.Common/Utilities/ModuleFilter.cs
Labels: needs-review

#12471 Improve telemetry data and environment discover metadata
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#12499 [Storage] bump up version for OOB
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
  src/Storage/Storage/Properties/AssemblyInfo.cs
Labels: needs-review

#12505 Update changelog for upcoming release
  src/Accounts/Accounts/ChangeLog.md
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/HDInsight/HDInsight/ChangeLog.md
  src/OperationalInsights/OperationalInsights/ChangeLog.md
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
Labels: Waiting for CI :shipit:

#12324 functionality : PeerAddressType for Private Peering and ignore case logic
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/Utils.cs
  src/Network/Network/ExpressRouteCircuit/Peering/AddAzureExpressRouteCircuitPeeringConfigCommand.cs
  src/Network/Network/ExpressRouteCircuit/Peering/AzureExpressRouteCircuitPeeringConfigBase.cs
  src/Network/Network/ExpressRouteCircuit/Peering/Connection/AddAzureExpressRouteCircuitConnectionConfigCommand.cs
  src/Network/Network/ExpressRouteCircuit/Peering/Connection/RemoveAzureExpressRouteCircuitConnectionConfigCommand.cs
  src/Network/Network/ExpressRouteCircuit/Peering/Connection/SetAzureExpressRouteCircuitConnectionConfigCommand.cs
  src/Network/Network/ExpressRouteCircuit/Peering/NewAzureExpressRouteCircuitPeeringConfigCommand.cs
  src/Network/Network/ExpressRouteCircuit/Peering/RemoveAzureExpressRouteCircuitPeeringConfigCommand.cs
  src/Network/Network/ExpressRouteCircuit/Peering/SetAzureExpressRouteCircuitPeeringConfigCommand.cs
Labels: needs-revision

#12495 Fix filtering by tenantId issue in Get-AzTenant
  src/Accounts/Accounts.Test/TenantCmdletMockTests.cs
  src/Accounts/Accounts/Accounts.generated.format.ps1xml
  src/Accounts/Accounts/Models/ModelExtensions.cs
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/help/Get-AzTenant.md
  src/Accounts/Authentication.ResourceManager/Models/PSAzureTenant.cs
Labels: Waiting for CI :shipit:

#12429 Add patch mode to Set-AzVMOperatingSystem
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskEncryptionSet.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestSetAzVMOperatingSystem.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestSetAzVMOperatingSystemError.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMOperatingSystemCommand.cs
  src/Compute/Compute/help/Set-AzVMOperatingSystem.md
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-review

#12518 [Frontdoor][Bug] Nullable DynamicCompression fix
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
Labels: Sprint Candidate, Waiting for CI :shipit:

#12517 Databricks: double encryption
  src/Databricks/Az.Databricks.psd1
  src/Databricks/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/docs/New-AzDatabricksWorkspace.md
  src/Databricks/readme.md
  src/Databricks/test/Get-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Get-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/New-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/New-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/Remove-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/deployment-templates/key-vault/parameters.json
  src/Databricks/test/deployment-templates/virtual-network/parameters.json
  src/Databricks/test/env.json
  src/Databricks/test/utils.ps1
Labels: Sprint Candidate, needs-review

#12473 Improve mysql user experience
  src/MySql/custom/New-AzMySqlFirewallRule.ps1
  src/MySql/custom/New-AzMySqlReplica.ps1
  src/MySql/custom/Update-AzMySqlConfiguration.ps1
  src/MySql/custom/Update-AzMySqlFirewallRule.ps1
  src/MySql/custom/Update-AzMySqlServer.ps1
  src/MySql/custom/readme.md
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/Get-AzMySqlConfiguration.md
  src/MySql/docs/Get-AzMySqlConnectionString.md
  src/MySql/docs/Get-AzMySqlFirewallRule.md
  src/MySql/docs/Get-AzMySqlServer.md
  src/MySql/docs/Get-AzMySqlVirtualNetworkRule.md
  src/MySql/docs/New-AzMySqlFirewallRule.md
  src/MySql/docs/New-AzMySqlReplica.md
  src/MySql/docs/Remove-AzMySqlFirewallRule.md
  src/MySql/docs/Remove-AzMySqlServer.md
  src/MySql/docs/Remove-AzMySqlVirtualNetworkRule.md
  src/MySql/docs/Restart-AzMySqlServer.md
  src/MySql/docs/Restore-AzMySqlServer.md
  src/MySql/docs/Update-AzMySqlConfiguration.md
  src/MySql/docs/Update-AzMySqlFirewallRule.md
  src/MySql/docs/Update-AzMySqlServer.md
  src/MySql/docs/Update-AzMySqlVirtualNetworkRule.md
  src/MySql/docs/readme.md
  src/MySql/examples/New-AzMySqlFirewallRule.md
  src/MySql/examples/New-AzMySqlReplica.md
  src/MySql/examples/Update-AzMySqlFirewallRule.md
  src/MySql/readme.md
  src/MySql/test/Az.MySql-TestResults.xml
  src/MySql/test/Get-AzMySqlConfiguration.Recording.json
  src/MySql/test/Get-AzMySqlConnectionString.Recording.json
  src/MySql/test/Get-AzMySqlFirewallRule.Recording.json
  src/MySql/test/Get-AzMySqlReplica.Recording.json
  src/MySql/test/Get-AzMySqlReplica.Tests.ps1
  src/MySql/test/Get-AzMySqlServer.Recording.json
  src/MySql/test/Get-AzMySqlVirtualNetworkRule.Recording.json
  src/MySql/test/New-AzMySqlFirewallRule.Recording.json
  src/MySql/test/New-AzMySqlFirewallRule.Tests.ps1
  src/MySql/test/New-AzMySqlReplica.Recording.json
  src/MySql/test/New-AzMySqlReplica.Tests.ps1
  src/MySql/test/New-AzMySqlServer.Recording.json
  src/MySql/test/New-AzMySqlServerReplica.Recording.json
  src/MySql/test/New-AzMySqlVirtualNetworkRule.Recording.json
  src/MySql/test/Remove-AzMySqlFirewallRule.Recording.json
  src/MySql/test/Remove-AzMySqlServer.Recording.json
  src/MySql/test/Remove-AzMySqlVirtualNetworkRule.Recording.json
  src/MySql/test/Restart-AzMySqlServer.Recording.json
  src/MySql/test/Restore-AzMySqlServer.Recording.json
  src/MySql/test/Restore-AzMySqlServer.Tests.ps1
  src/MySql/test/Update-AzMySqlConfiguration.Recording.json
  src/MySql/test/Update-AzMySqlFirewallRule.Recording.json
  src/MySql/test/Update-AzMySqlFirewallRule.Tests.ps1
  src/MySql/test/Update-AzMySqlServer.Recording.json
  src/MySql/test/Update-AzMySqlVirtualNetworkRule.Recording.json
  src/MySql/test/env.json
  src/MySql/test/readme.md
  src/MySql/test/utils.ps1
Labels: Generator, needs-review

#12520 Timeseriesinsights api upgrade
  src/TimeSeriesInsights/custom/New-AzTimeSeriesInsightsEnvironment.ps1
  src/TimeSeriesInsights/custom/New-AzTimeSeriesInsightsEventSource.ps1
  src/TimeSeriesInsights/custom/readme.md
  src/TimeSeriesInsights/docs/Az.TimeSeriesInsights.md
  src/TimeSeriesInsights/docs/Get-AzTimeSeriesInsightsAccessPolicy.md
  src/TimeSeriesInsights/docs/Get-AzTimeSeriesInsightsEnvironment.md
  src/TimeSeriesInsights/docs/Get-AzTimeSeriesInsightsEventSource.md
  src/TimeSeriesInsights/docs/Get-AzTimeSeriesInsightsReferenceDataSet.md
  src/TimeSeriesInsights/docs/New-AzTimeSeriesInsightsAccessPolicy.md
  src/TimeSeriesInsights/docs/New-AzTimeSeriesInsightsEnvironment.md
  src/TimeSeriesInsights/docs/New-AzTimeSeriesInsightsEventSource.md
  src/TimeSeriesInsights/docs/New-AzTimeSeriesInsightsReferenceDataSet.md
  src/TimeSeriesInsights/docs/Update-AzTimeSeriesInsightsAccessPolicy.md
  src/TimeSeriesInsights/docs/Update-AzTimeSeriesInsightsEnvironment.md
  src/TimeSeriesInsights/docs/Update-AzTimeSeriesInsightsEventSource.md
  src/TimeSeriesInsights/docs/Update-AzTimeSeriesInsightsReferenceDataSet.md
  src/TimeSeriesInsights/examples/Get-AzTimeSeriesInsightsEnvironment.md
  src/TimeSeriesInsights/examples/New-AzTimeSeriesInsightsEnvironment.md
  src/TimeSeriesInsights/examples/Update-AzTimeSeriesInsightsEnvironment.md
  src/TimeSeriesInsights/readme.md
  src/TimeSeriesInsights/test/Get-AzTimeSeriesInsightsAccessPolicy.Recording.json
  src/TimeSeriesInsights/test/Get-AzTimeSeriesInsightsEnvironment.Recording.json
  src/TimeSeriesInsights/test/Get-AzTimeSeriesInsightsEventSource.Recording.json
  src/TimeSeriesInsights/test/Get-AzTimeSeriesInsightsReferenceDataSet.Recording.json
  src/TimeSeriesInsights/test/New-AzTimeSeriesInsightsAccessPolicy.Recording.json
  src/TimeSeriesInsights/test/New-AzTimeSeriesInsightsAccessPolicy.Tests.ps1
  src/TimeSeriesInsights/test/New-AzTimeSeriesInsightsEnvironment.Recording.json
  src/TimeSeriesInsights/test/New-AzTimeSeriesInsightsEnvironment.Tests.ps1
  src/TimeSeriesInsights/test/New-AzTimeSeriesInsightsEventSource.Recording.json
  src/TimeSeriesInsights/test/New-AzTimeSeriesInsightsReferenceDataSet.Recording.json
  src/TimeSeriesInsights/test/Remove-AzTimeSeriesInsightsAccessPolicy.Recording.json
  src/TimeSeriesInsights/test/Remove-AzTimeSeriesInsightsEnvironment.Recording.json
  src/TimeSeriesInsights/test/Remove-AzTimeSeriesInsightsEventSource.Recording.json
  src/TimeSeriesInsights/test/Remove-AzTimeSeriesInsightsReferenceDataSet.Recording.json
  src/TimeSeriesInsights/test/Remove-AzTimeSeriesInsightsReferenceDataSet.Tests.ps1
  src/TimeSeriesInsights/test/Update-AzTimeSeriesInsightsAccessPolicy.Recording.json
  src/TimeSeriesInsights/test/Update-AzTimeSeriesInsightsEnvironment.Recording.json
  src/TimeSeriesInsights/test/Update-AzTimeSeriesInsightsEnvironment.Tests.ps1
  src/TimeSeriesInsights/test/Update-AzTimeSeriesInsightsEventSource.Recording.json
  src/TimeSeriesInsights/test/Update-AzTimeSeriesInsightsReferenceDataSet.Recording.json
  src/TimeSeriesInsights/test/env.json
  src/TimeSeriesInsights/test/helper.ps1
  src/TimeSeriesInsights/test/utils.ps1
Labels: needs-review

#12519 Add back the column width of PSAzureContext
  src/Accounts/Accounts/Accounts.generated.format.ps1xml
Labels: Sprint Candidate, Waiting for CI :shipit:

#12504 add what brackets around parameters mean in PowerShell Documentation
  documentation/development-docs/design-guidelines/parameter-best-practices.md
Labels: Doc - Internal, Waiting for CI :shipit:

#12516 Add new attributes to role assignment objects and related cmdlets
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/Common.ps1
  src/Resources/Resources.Test/ScenarioTests/RoleAssignmentTests.cs
  src/Resources/Resources.Test/ScenarioTests/RoleAssignmentTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaWithV1Conditions.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaWithV2ConditionVersionOnly.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaWithV2Conditions.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests/RaWithV2ConditionsOnly.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Models.Authorization/AuthorizationClient.cs
  src/Resources/Resources/Models.Authorization/AuthorizationClientExtensions.cs
  src/Resources/Resources/Models.Authorization/FilterRoleAssignmentsOptions.cs
  src/Resources/Resources/Models.Authorization/PSRoleAssignment.cs
  src/Resources/Resources/Resources.csproj
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
  src/Resources/Resources/help/New-AzRoleAssignment.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#12521 Revert "Add brackets"
  build.proj
  src/AppConfiguration/Az.AppConfiguration.psd1
  src/AppConfiguration/generated/runtime/BuildTime/Cmdlets/ExportPsd1.cs
  src/AppConfiguration/readme.md
  src/AppConfiguration/run-module.ps1
Labels: Sprint Candidate, Waiting for CI :shipit:

#12533 Minor version bump if module version is less than 1.0.0
  tools/VersionController/Models/VersionBumper.cs
Labels: Sprint Candidate, needs-revision
