Repository Azure/azure-powershell, pull requests merged in 2020-11, with the labels that each got.

#13351 Update labels of issue templates
  .github/ISSUE_TEMPLATE/az-module-bug-report.md
  .github/ISSUE_TEMPLATE/azurerm-module-bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/internal-issue.md
Labels: Waiting for CI :shipit:

#13355 Fix syntax error in Windows PowerShell
  tools/Az.Tools.Installer/Az.Tools.Installer.psd1
  tools/Az.Tools.Installer/exports/Update-AzModule.ps1
  tools/Az.Tools.Installer/internal/Get-AzModuleUpdateList.ps1
Labels: needs-review

#13380 bump up storage verison -> 3.0.1-preview
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
  src/Storage/Storage/Properties/AssemblyInfo.cs
Labels: needs-review

#13363 Aladdin generated examples for Batch
  src/Batch/Batch/help/New-AzBatchAccount.md
  src/Batch/Batch/help/Set-AzBatchApplication.md
Labels: Waiting for CI :shipit:, customer-reported

#13369 Fix api version in release notes for ACR
  ChangeLog.md
  src/ContainerRegistry/ContainerRegistry/ChangeLog.md
Labels: Waiting for CI :shipit:

#13349 Update for -HostNames parameter values
  src/Network/Network/help/Add-AzApplicationGatewayHttpListener.md
Labels: Waiting for CI :shipit:, customer-reported

#13390 Add AppConfiguration to Az
  src/AppConfiguration/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: Waiting for CI :shipit:

#13327 Update how we send request and collect telemetry
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
Labels: needs-review

#13362 Workaround for the token cache issue in Az.Accounts 2.1.0
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
Labels: Waiting for CI :shipit:, customer-reported

#13388 Youri/digital twins generation
  src/DigitalTwins/test/New-AzDigitalTwinsEndpoint.Tests.ps1
Labels: needs-review

#13395 New parameter (MaintenanceConfigurationId) added to the New-AzSqlInstance and Set-AzSqlInstance cmdlets.
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstanceWithMaintenanceConfigurationId.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
Labels: Waiting for CI :shipit:

#13263 modifying Backup Time header to display UTC
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.format.ps1xml
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#13409 Added officially published SDK
  src/Batch/Batch.Test/Batch.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HPCCache/HPCCache.Test/HPCCache.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network/Network.csproj
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SignalR/SignalR.Test/SignalR.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-review

#13381 0.1.0 release of Az.DigitalTwins
  documentation/azure-powershell-modules.md
  src/DigitalTwins/Az.DigitalTwins.psd1
  src/DigitalTwins/Changelog.md
  src/DigitalTwins/test/New-AzDigitalTwinsEndpoint.Tests.ps1
Labels: needs-review

#13389 [RecoveryServices.Backup] Modifying breaking change warning in Get-AzRecoveryServicesBackupJobDetails Cmdlet
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJobDetails.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#13356 [DataFactory]improve documentation for cmdlet New-AzDataFactoryV2LinkedServiceEncryptedCredential
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/LinkedServices/NewAzureDataFactoryLinkedServiceEncryptedCredentialCommand.cs
  src/DataFactory/DataFactoryV2/help/New-AzDataFactoryV2LinkedServiceEncryptedCredential.md
Labels: Doc - Reference, needs-review

#13408 [Azure PowerShell] New service principal warning
  src/Resources/Resources/help/New-AzADServicePrincipal.md
Labels: Doc - Reference, needs-review

#13414 [Doc]Fix the issue of change log for Az.Sql
  src/Sql/Sql/ChangeLog.md
Labels: Waiting for CI :shipit:

#13402 [RecoveryServices.Backup] Updating sample script help text for Set-AzRecoveryServicesBackupProtectionPolicy
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Copy-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
Labels: needs-review

#13396 connect-azaccount supports ctrl-C
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Authentication/DelegatingAuthenticator.cs
  src/Accounts/Authenticators/DeviceCodeAuthenticator.cs
  src/Accounts/Authenticators/InteractiveUserAuthenticator.cs
Labels: Waiting for CI :shipit:

#13404 Update Restore-AzSqlInstanceDatabase.md
  src/Sql/Sql/help/Restore-AzSqlInstanceDatabase.md
Labels: Waiting for CI :shipit:

#13410 Bug fixes and performance improvement
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSettings.json
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterSet.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
Labels: needs-review

#13415 StackHCI 0.3.1 OOB release
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/ChangeLog.md
  src/StackHCI/Properties/AssemblyInfo.cs
Labels: needs-review

#13354 Improve the telemetry and http request
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzContext.cs
Labels: needs-revision

#13411 [DeviceProvisioningService] Allow tags in IoT DPS create cmdlet
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsTests.ps1
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsTests/IotDpsLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices/ChangeLog.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/Cmdlet/IotDps/NewAzureRmIotDeviceProvisioningService.cs
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/New-AzIoTDeviceProvisioningService.md
Labels: needs-review

#13270 [Pipeline] Require specified build from 'azure-powershell - sign' to download
  .azure-pipelines/release-test.yml
  tools/Test/SmokeTest/ConnectAzAccount.ps1
  tools/Test/SmokeTest/InstallAnIndividualModuleOnTopOfAz.ps1
  tools/Test/SmokeTest/InstallAzOnTopOfAnIndividualModule.ps1
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
  tools/Test/SmokeTest/UpdateAnIndividualModule.ps1
  tools/Test/SmokeTest/UpdateAzModules.ps1
Labels: needs-review

#13407 New-AzVm and New-AzVmConfig licenseType description edits
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
Labels: Waiting for CI :shipit:

#13436 fixing Az.Resource version
  src/Resources/Resources/Az.Resources.psd1
  tools/Az/Az.psd1
Labels: needs-review

#13328 Update module infomation
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
Labels: needs-revision

#13417 Corrected the PublicSubnetName argument
  src/Databricks/help/New-AzDatabricksWorkspace.md
Labels: Waiting for CI :shipit:, customer-reported

#13440 [Pipeline] Remove subscriptionId from smoke test
  .azure-pipelines/release-test.yml
Labels: needs-review

#13424 Update package script to support RequiredModules
  tools/Az.Tools.Predictor/build.proj
  tools/PublishToolsModule.ps1
Labels: needs-review

#13452 fixing Az.Network version
  tools/Az/Az.psd1
Labels: needs-review

#13420 Add variety to Az.Predictor result list
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
Labels: customer-reported, needs-review

#13455 Update-AzVirtualRouter to allow branch to branch traffic
  src/Network/Network.Test/ScenarioTests/VirtualRouterTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualRouterTests/TestVirtualRouterCRUDMinimalParameters.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/Models/PSVirtualRouter.cs
  src/Network/Network/Models/Cortex/PSVirtualHub.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/VirtualRouter/UpdateAzureRMVirtualRouterCommand.cs
  src/Network/Network/VirtualRouterPeer/UpdateAzureRMVirtualRouterPeerCommand.cs
  src/Network/Network/help/Update-AzVirtualRouter.md
Labels: needs-review

#13453 Fixed broken urls
  src/Compute/Compute/help/Add-AzVMSecret.md
  src/Compute/Compute/help/Add-AzVmssSecret.md
  src/EventGrid/EventGrid/help/New-AzEventGridSubscription.md
Labels: needs-review

#13428 Make arguments `-MinScaleUnits` and `-MaxScaleUnits` optional in `Set-AzExpressRouteGateway`
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/ExpressRouteGateway/SetAzureRmExpressRouteGatewayCommand.cs
  src/Network/Network/help/Set-AzExpressRouteGateway.md
Labels: Waiting for CI :shipit:

#13447 Update RecordType in examples 3 and 4
  src/PrivateDns/PrivateDns/help/New-AzPrivateDnsRecordConfig.md
Labels: Waiting for CI :shipit:

#13433 Fix PartnerServerName check in GetAzureSqlDatabaseReplicationLink.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Replication/Cmdlet/GetAzureSqlDatabaseReplicationLink.cs
Labels: Waiting for CI :shipit:

#13233 Get-AzVMBootDiagnostics api change to use RetrieveBootDiagnosticsData()
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineBootDiagnostics.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMBootDiagnosticsDataCommand.cs
Labels: Waiting for CI :shipit:

#13393 Allow Get-AzLogicAppRunHistory to return more than 30 entries
  src/LogicApp/LogicApp/ChangeLog.md
  src/LogicApp/LogicApp/Cmdlets/LogicApp/GetAzureLogicAppRunHistoryCommand.cs
  src/LogicApp/LogicApp/Utilities/LogicAppClientRunOperations.cs
  src/LogicApp/LogicApp/help/Get-AzLogicAppRunHistory.md
Labels: customer-reported, needs-review

#13458 [Aks]Fix the issue of service principal.
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.cs
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.ps1
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestNewAzureKubernetesByServicePrincipal.json
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/NewKubeBase.cs
Labels: needs-review

#13460 Fixed Cluster commands for EventHub cluster without tags and updated help text for AzEventHubGeoDRConfiguration
  src/EventHub/EventHub.Test/ScenarioTests/ClusterTest.ps1
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/DRConfig/NewAzureEventHubGeoDRConfiguration.cs
  src/EventHub/EventHub/Models/PSEventHubDRConfigurationAttributes.cs
  src/EventHub/EventHub/Models/PSEventHubsClusterAttributes.cs
  src/EventHub/EventHub/help/New-AzEventHubGeoDRConfiguration.md
Labels: needs-review

#13446 Remove previous Az.Accounts version in Install-AzModule
  tools/Az.Tools.Installer/Az.Tools.Installer.psd1
  tools/Az.Tools.Installer/exports/Install-AzModule.ps1
Labels: needs-review

#13462 Add Get-AzVirtualRouterPeerAdvertisedRoute and Get-AzVirtualRouterPeerLearnedRoute with warning messageVr peer
  src/Network/Network/ChangeLog.md
  src/Network/Network/VirtualRouterPeer/GetAzVirtualRouterPeerAdvertisedRouteCommand.cs
  src/Network/Network/VirtualRouterPeer/GetAzVirtualRouterPeerLearnedRouteCommand.cs
Labels: needs-review

#13445 [Synapse] - Supports -Force parameter for Remove-* cmdlets
  src/Synapse/Synapse.Test/ScenarioTests/FirewallTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SparkPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlDatabaseTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolV3Tests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/WorkspaceTests.ps1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/DataFlows/RemoveAzureSynapseDataFlow.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/Datasets/RemoveAzureSynapseDataset.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/LinkedServices/RemoveAzureSynapseLinkedService.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/Notebooks/RemoveAzureSynapseNotebook.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/Pipelines/RemoveAzureSynapsePipeline.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/Triggers/RemoveAzureSynapseTrigger.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/Triggers/RemoveAzureSynapseTriggerSubscription.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Firewall/RemoveAzureSynapseFirewallRule.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/RemoveAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlDatabase/RemoveAzureSynapseSqlDatabase.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/RemoveAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/RemoveAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Remove-AzSynapseDataFlow.md
  src/Synapse/Synapse/help/Remove-AzSynapseDataset.md
  src/Synapse/Synapse/help/Remove-AzSynapseFirewallRule.md
  src/Synapse/Synapse/help/Remove-AzSynapseLinkedService.md
  src/Synapse/Synapse/help/Remove-AzSynapseNotebook.md
  src/Synapse/Synapse/help/Remove-AzSynapsePipeline.md
  src/Synapse/Synapse/help/Remove-AzSynapseSparkPool.md
  src/Synapse/Synapse/help/Remove-AzSynapseSqlDatabase.md
  src/Synapse/Synapse/help/Remove-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Remove-AzSynapseTrigger.md
  src/Synapse/Synapse/help/Remove-AzSynapseTriggerSubscription.md
  src/Synapse/Synapse/help/Remove-AzSynapseWorkspace.md
Labels: needs-review

#13465 Polish changelog for upcoming release
  src/DataLakeStore/DataLakeStore/ChangeLog.md
  src/EventHub/EventHub/ChangeLog.md
  src/IotHub/IotHub/ChangeLog.md
  src/LogicApp/LogicApp/ChangeLog.md
  tools/Az/Az.psd1
Labels: needs-review

#12939 Updating load balancer and ip address commands with new global load balancing properties
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.cs
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.ps1
  src/Network/Network.Test/ScenarioTests/LoadBalancerTests.cs
  src/Network/Network.Test/ScenarioTests/LoadBalancerTests.ps1
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.ps1
  src/Network/Network.Test/ScenarioTests/PublicIpPrefixTests.cs
  src/Network/Network.Test/ScenarioTests/PublicIpPrefixTests.ps1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkBaseCmdlet.cs
  src/Network/Network/Generated/LoadBalancer/BackendAddressPool/GetAzureRmLoadBalancerBackendAddressPoolConfigCommand.cs
  src/Network/Network/Generated/LoadBalancer/FrontendIPConfiguration/AddAzureRmLoadBalancerFrontendIpConfigCommand.cs
  src/Network/Network/Generated/LoadBalancer/FrontendIPConfiguration/NewAzureRmLoadBalancerFrontendIpConfigCommand.cs
  src/Network/Network/Generated/LoadBalancer/FrontendIPConfiguration/SetAzureRmLoadBalancerFrontendIpConfigCommand.cs
  src/Network/Network/Generated/LoadBalancer/NewAzureRMLoadBalancerCommand.cs
  src/Network/Network/Generated/Models/PSLoadBalancerSku.cs
  src/Network/Network/Generated/Models/PSPublicIpAddressSku.cs
  src/Network/Network/LoadBalancer/NewAzLoadBalancerBackendAddressConfig.cs
  src/Network/Network/Models/PSLoadBalancerBackendAddress.cs
  src/Network/Network/Models/PSPublicIpPrefixSku.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
  src/Network/Network/PublicIpPrefix/NewAzurePublicIpPrefixCommand.cs
  src/Network/Network/help/Add-AzLoadBalancerFrontendIpConfig.md
  src/Network/Network/help/Get-AzLoadBalancer.md
  src/Network/Network/help/Get-AzPublicIpAddress.md
  src/Network/Network/help/Get-AzPublicIpPrefix.md
  src/Network/Network/help/New-AzLoadBalancer.md
  src/Network/Network/help/New-AzLoadBalancerBackendAddressConfig.md
  src/Network/Network/help/New-AzLoadBalancerFrontendIpConfig.md
  src/Network/Network/help/New-AzPublicIpAddress.md
  src/Network/Network/help/New-AzPublicIpPrefix.md
  src/Network/Network/help/Set-AzLoadBalancerFrontendIpConfig.md
Labels: Cmdlet Review Complete

#13456 Fix add/set/get-azenvironment
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Environment/AddAzureRMEnvironment.cs
  src/Accounts/Accounts/Environment/SetAzureRMEnvironment.cs
  src/Accounts/Accounts/help/Add-AzEnvironment.md
  src/Accounts/Accounts/help/Set-AzEnvironment.md
  src/Accounts/Authentication.ResourceManager/ContextModelExtensions.cs
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#13413 [HDInsight] Add three parameters to support relay outbound and private link and custom Ambari DB
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HDInsight/HDInsight.Test/ScenarioTests/HDInsightClusterTests.cs
  src/HDInsight/HDInsight.Test/ScenarioTests/HDInsightClusterTests.ps1
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCreateClusterWithCustomAmbariDatabase.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCreateClusterWithPrivateLink.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCreateClusterWithRelayOutoundAndPrivateLink.json
  src/HDInsight/HDInsight.sln
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/ClusterCreateHelper.cs
  src/HDInsight/HDInsight/Constants.cs
  src/HDInsight/HDInsight/HDInsight.csproj
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightMetastoreCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/RestartAzureHDInsightHost.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightCluster.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightConfig.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightMetastoreType.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightNetworkProperties.cs
  src/HDInsight/HDInsight/help/Add-AzHDInsightMetastore.md
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
  src/HDInsight/HDInsight/help/Restart-AzHDInsightHost.md
  tools/SecurityTools/CredScanSuppressions.json
  tools/StaticAnalysis/Exceptions/Az.HDInsight/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#13399 Updated issue template with sensitive information warning
  .github/ISSUE_TEMPLATE/az-module-bug-report.md
  .github/ISSUE_TEMPLATE/azurerm-module-bug-report.md
Labels: Waiting for CI :shipit:

#13401 remove unused ADAL libs
  src/lib/NetCorePreloadAssemblies/Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll
  src/lib/NetCorePreloadAssemblies/Microsoft.IdentityModel.Clients.ActiveDirectory.dll
  src/lib/NetFxPreloadAssemblies/Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll
  src/lib/NetFxPreloadAssemblies/Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Labels: needs-review

#13438 Require to put a link of design review in PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs-review

#13403 Onboard Migrate to Private Link Common Cmdlets
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#13454 Az.StackHCI Cmdlet registration changes for GA
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
  src/StackHCI/help/Az.StackHCI.md
  src/StackHCI/help/Register-AzStackHCI.md
  src/StackHCI/help/Test-AzStackHCIConnection.md
  src/StackHCI/help/Unregister-AzStackHCI.md
Labels: Cmdlet Review Complete, Waiting for CI :shipit:

#13471 Format changelog of cosmos DB from last release
  src/CosmosDB/CosmosDB/ChangeLog.md
Labels: Waiting for CI :shipit:

#13466 Erich/fix write object error
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/Authenticators/DeviceCodeAuthenticator.cs
  src/Accounts/Authenticators/MsalAccessToken.cs
Labels: Waiting for CI :shipit:

#13416 Fix error happens if there's no write permission to user profile path
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Common/AzureContextModificationCmdlet.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Authentication/AzureSessionInitializer.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#13385 Adding firewall prerequisite information
  src/Sql/Sql/help/New-AzSqlDatabaseExport.md
Labels: Doc - Reference, Waiting for CI :shipit:, customer-reported

#13475 Add 3rd party MIT license...
  LICENSE.txt
Labels: Waiting for CI :shipit:, needs-review

#13427 {VirtualWan} Mark older routeTable cmdlets as deprecating
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubRouteCommand.cs
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubRouteTableCommand.cs
  src/Network/Network/Cortex/VirtualHub/SetAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/UpdateAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHubRouteTable/AddAzureRmVirtualHubRouteCommand.cs
  src/Network/Network/Cortex/VirtualHubRouteTable/AddAzureRmVirtualHubRouteTableCommand.cs
  src/Network/Network/Cortex/VirtualHubRouteTable/GetAzureRmVirtualHubRouteTableCommand.cs
  src/Network/Network/Cortex/VirtualHubRouteTable/RemoveAzureRmVirtualHubRouteTableCommand.cs
Labels: Waiting for CI :shipit:

#13398 add cmdlet Get-AzAccessToken
  src/Accounts/Accounts/Accounts.format.ps1xml
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/PSAccessToken.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
  src/Accounts/Accounts/help/Az.Accounts.md
  src/Accounts/Accounts/help/Get-AzAccessToken.md
  src/Accounts/Authenticators/MsalAccessToken.cs
Labels: Waiting for CI :shipit:

#13482 Fix device code authentication with tenantId
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Authenticators/DeviceCodeAuthenticator.cs
Labels: Waiting for CI :shipit:

#13485 Update Update-AzAppConfigurationStore.md
  src/AppConfiguration/help/Update-AzAppConfigurationStore.md
Labels: Waiting for CI :shipit:, customer-reported

#13488 Add byDict parameter set for New-AzSapMonitorProviderInstance and re-record tests
  src/HanaOnAzure/custom/New-AzSapMonitorProviderInstance.ps1
  src/HanaOnAzure/docs/New-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/examples/New-AzSapMonitorProviderInstance.md
  src/HanaOnAzure/readme.md
  src/HanaOnAzure/test/Get-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/Get-AzSapMonitorProviderInstance.Recording.json
  src/HanaOnAzure/test/New-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/New-AzSapMonitorProviderInstance.Recording.json
  src/HanaOnAzure/test/New-AzSapMonitorProviderInstance.Tests.ps1
  src/HanaOnAzure/test/Remove-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/Remove-AzSapMonitorProviderInstance.Recording.json
  src/HanaOnAzure/test/Update-AzSapMonitor.Recording.json
  src/HanaOnAzure/test/env.json
  src/HanaOnAzure/test/utils.ps1
Labels: needs-review

#13490 Update New-AzCosmosDBAccount.md
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBAccount.md
Labels: Waiting for CI :shipit:, customer-reported

#13501 Add Smoke Test on Powershell 7.1.0 (Latest Version)
  .azure-pipelines/release-test.yml
  .azure-pipelines/util/smoke-test-steps.yml
  tools/Test/SmokeTest/PrepareRequiredPowershell.ps1
Labels: needs-review

#13508 Correct spelling of TagPatchOperation
  src/Resources/Resources/help/Update-AzTag.md
Labels: Waiting for CI :shipit:, customer-reported

#13468 Adding Azure Communication Service Powershell Cmdlets
  src/Communication/.gitattributes
  src/Communication/.gitignore
  src/Communication/Az.Communication.psd1
  src/Communication/custom/readme.md
  src/Communication/docs/Az.Communication.md
  src/Communication/docs/Get-AzCommunicationService.md
  src/Communication/docs/Get-AzCommunicationServiceKey.md
  src/Communication/docs/New-AzCommunicationService.md
  src/Communication/docs/New-AzCommunicationServiceKey.md
  src/Communication/docs/Remove-AzCommunicationService.md
  src/Communication/docs/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/docs/Update-AzCommunicationService.md
  src/Communication/docs/readme.md
  src/Communication/examples/Get-AzCommunicationService.md
  src/Communication/examples/Get-AzCommunicationServiceKey.md
  src/Communication/examples/New-AzCommunicationService.md
  src/Communication/examples/New-AzCommunicationServiceKey.md
  src/Communication/examples/Remove-AzCommunicationService.md
  src/Communication/examples/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/examples/Update-AzCommunicationService.md
  src/Communication/how-to.md
  src/Communication/license.txt
  src/Communication/readme.md
  src/Communication/resources/readme.md
  src/Communication/test/Get-AzCommunicationService.Recording.json
  src/Communication/test/Get-AzCommunicationService.Tests.ps1
  src/Communication/test/Get-AzCommunicationServiceKey.Recording.json
  src/Communication/test/Get-AzCommunicationServiceKey.Tests.ps1
  src/Communication/test/New-AzCommunicationService.Recording.json
  src/Communication/test/New-AzCommunicationService.Tests.ps1
  src/Communication/test/New-AzCommunicationServiceKey.Recording.json
  src/Communication/test/New-AzCommunicationServiceKey.Tests.ps1
  src/Communication/test/Remove-AzCommunicationService.Tests.ps1
  src/Communication/test/Set-AzCommunicationServiceNotificationHub.Recording.json
  src/Communication/test/Set-AzCommunicationServiceNotificationHub.Tests.ps1
  src/Communication/test/Update-AzCommunicationService.Recording.json
  src/Communication/test/Update-AzCommunicationService.Tests.ps1
  src/Communication/test/env.json
  src/Communication/test/loadEnv.ps1
  src/Communication/test/readme.md
  src/Communication/test/utils.ps1
Labels: needs-review

#13511 Add private link support for Redis Enterprise
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: needs-revision

#13502 Release Az.Storage-Preview-v.3.0.2
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/AssemblyInfo.cs
  src/Accounts/Authentication/Properties/AssemblyInfo.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseActivationTests.cs
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
  src/Storage/Storage/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
Labels: needs-review

#13513 Get-AzLogicAppRunHistory Help Tidy
  src/LogicApp/LogicApp/help/Get-AzLogicAppRunHistory.md
Labels: Doc - Reference, customer-reported

#13491 Fix the invalid character
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
Labels: Waiting for CI :shipit:, customer-reported

#13512 Added telemetry info
  README.md
Labels: needs-review

#13519 Provide Private Link support for HealthcareApis RP
  src/HealthcareApis/HealthcareApis.Test/HealthcareApis.Test.csproj
  src/HealthcareApis/HealthcareApis.Test/ScenarioTests/HealthcareApisServiceController.cs
  src/HealthcareApis/HealthcareApis.Test/ScenarioTests/HealthcareApisServiceTests.cs
  src/HealthcareApis/HealthcareApis.Test/ScenarioTests/HealthcareApisServiceTests.ps1
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestAzRmHealthcareApisService.json
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestPrivateEndpointConnection.json
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestPublicNetworkAccessControl.json
  src/HealthcareApis/HealthcareApis.sln
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/HealthcareApis.csproj
  src/HealthcareApis/HealthcareApis/HealthcareApis/NewAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/SetAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/help/New-AzHealthcareApisService.md
  src/HealthcareApis/HealthcareApis/help/Set-AzHealthcareApisService.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#13525 Add Commands for other Modules
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: Waiting for CI :shipit:

#13523 [RecoveryServices.Backup] Making help text changes to Restore-AzRecoveryServicesBackupItem cmdlet
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
Labels: needs-review

#13528 Update New-AzFrontDoorWafManagedRuleObject.md to remove unsupported "EnabledState" parameter in New-AzFrontDoorWafManagedRuleOverrideObject
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafManagedRuleObject.md
Labels: needs-review

#13546 Merge internal/Az.Tools.Predictor
  .azure-pipelines/sign-tool-predictor.yml
  tools/Az.Tools.Installer/build.proj
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Az.Tools.Predictor.Test.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Data/CommandsModel.zip
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Data/PredictionsModel.zip
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Data/SuggestionsModel.zip
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/ModelFixture.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.sln
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorConstants.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSettings.json
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ITelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterSet.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterValuePredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Prediction.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/PredictionSource.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Profile/AzurePSDataCollectionProfile.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Settings.cs
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine.Polyfiller.dll
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine2.dll
  tools/Az.Tools.Predictor/MockPSConsole/MockPSConsole.csproj
  tools/Az.Tools.Predictor/MockPSConsole/Program.cs
  tools/Az.Tools.Predictor/NuGet.Config
  tools/Az.Tools.Predictor/build.proj
  tools/PublishToolsModule.ps1
Labels: needs-review

#13538 Release Az.Storage-Preview-v.3.0.2
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/AssemblyInfo.cs
  src/Accounts/Authentication/Properties/AssemblyInfo.cs
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
  src/Storage/Storage/Properties/AssemblyInfo.cs
Labels: needs-review

#13439 [Pipeline] dailyBuild: bump version and sign
  .azure-pipelines/daily-build.yml
  tools/RunVersionController.ps1
Labels: needs-review

#13480 Add Variety to Az.Predictor
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSettings.json
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Settings.cs
Labels: Waiting for CI :shipit:, customer-reported

#13547 Disable test related to fileproperties
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystemPermissions.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystemPermissions.json
Labels: Waiting for CI :shipit:

#13495 [Storage] Support upload 4TB Azure file
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/DataLakeStore/DataLakeStore/DataLakeStore.csproj
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Common/AzureStorageFile.cs
  src/Storage/Storage/Common/Util.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageFileContent.cs
  src/Storage/Storage/File/StorageFileDataManagementCmdletBase.cs
  src/Storage/Storage/Storage.csproj
  src/Storage/Storage/Storage.format.ps1xml
  src/Storage/Storage/Storage.generated.format.ps1xml
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/Common.Netcore.Dependencies.targets
  tools/StaticAnalysis/Exceptions/Az.Batch/MissingAssemblies.csv
  tools/StaticAnalysis/Exceptions/Az.Resources/MissingAssemblies.csv
Labels: Waiting for CI :shipit:

#13518 Healthcare APIs Powershell BYOK Updates
  src/HealthcareApis/HealthcareApis.Test/ScenarioTests/Common.ps1
  src/HealthcareApis/HealthcareApis.Test/ScenarioTests/HealthcareApisServiceTests.ps1
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestAzRmHealthcareApisService.json
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/HealthcareApis/NewAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/RemoveAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/SetAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisFhirServiceCosmosDbConfig.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisServiceConfig.cs
  src/HealthcareApis/HealthcareApis/help/Get-AzHealthcareApisService.md
  src/HealthcareApis/HealthcareApis/help/New-AzHealthcareApisService.md
  src/HealthcareApis/HealthcareApis/help/Remove-AzHealthcareApisService.md
  src/HealthcareApis/HealthcareApis/help/Set-AzHealthcareApisService.md
Labels: Waiting for CI :shipit:

#13532 {IotHub} Added new examples for hashtable type parameter
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Add-AzIoTDeviceProvisioningServiceEnrollment.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Add-AzIoTDeviceProvisioningServiceEnrollmentGroup.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Set-AzIoTDeviceProvisioningServiceEnrollment.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Set-AzIoTDeviceProvisioningServiceEnrollmentGroup.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Update-AzIoTDeviceProvisioningService.md
  src/IotHub/IotHub/help/Add-AzIotHubConfiguration.md
  src/IotHub/IotHub/help/Add-AzIotHubDeployment.md
  src/IotHub/IotHub/help/Set-AzIotHubConfiguration.md
  src/IotHub/IotHub/help/Set-AzIotHubDeployment.md
  src/IotHub/IotHub/help/Test-AzIotHubRoute.md
  src/IotHub/IotHub/help/Update-AzIotHub.md
  src/IotHub/IotHub/help/Update-AzIotHubDeviceTwin.md
Labels: Waiting for CI :shipit:

#13550 Policy definition fix
  src/Resources/ResourceManager/Components/Constants.cs
  src/Resources/Resources/ChangeLog.md
  tools/Az/Az.psd1
Labels: needs-revision

#13437 Get-AzVm filter by Name prior to checking for throttling
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineGetVMNameAcrossResourceGroups.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
Labels: needs-review

#13559 [Az.Resources] change version commparator from double to version
  src/Resources/Resources.sln
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/SetAzureRoleAssignmentCommand.cs
Labels: needs-review

#13540 {AppService} Prevent duplicate rules from being created.
  src/Websites/Websites.Test/ScenarioTests/AccessRestrictionTests.cs
  src/Websites/Websites.Test/ScenarioTests/AccessRestrictionTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.AccessRestrictionTests/TestAddWebAppAccessRestrictionDuplicate.json
  src/Websites/Websites.sln
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AccessRestriction/AddAzureWebAppAccessRestrictionRule.cs
Labels: needs-revision

#13562 [ResourceGraph.Autorest]Remove ETag property.
  src/ResourceGraph/ResourceGraph.Autorest/custom/New-AzResourceGraphQuery.ps1
  src/ResourceGraph/ResourceGraph.Autorest/custom/Update-AzResourceGraphQuery.ps1
  src/ResourceGraph/ResourceGraph.Autorest/docs/Get-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/New-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/Update-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/Get-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/New-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/Update-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/readme.md
Labels: Resource Graph, needs-review

#13555 [Az.Migrate] Upgrading a default user logic in New-AzMigrateServerReplication cmdlet
  src/Migrate/custom/New-AzMigrateServerReplication.ps1
  src/Migrate/readme.md
Labels: Waiting for CI :shipit:

#13506 Secret Management Extension for AKV
  src/KeyVault/KeyVault/Az.KeyVault.Extension/Az.KeyVault.Extension.psd1
  src/KeyVault/KeyVault/Az.KeyVault.Extension/Az.KeyVault.Extension.psm1
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/SecretManagementExtension/SecretManagementExtension.psm1
  tools/CleanupBuild.ps1
  tools/NewHelpIndex.ps1
  tools/NewOutputTypeIndex.ps1
  tools/PublishModules.psm1
  tools/UpdateModules.psm1
Labels: Waiting for CI :shipit:

#13542 Vimundad appgwt: Adding Rule Priority for Application Gateway RequestRoutingRule
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUD3.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDRewriteRuleSet.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDRewriteRuleSetUrlConfiguration.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDRewriteRuleSetWithConditions.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDSubItems2.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayWithFirewallPolicy.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayWithListenerHostNames.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableServerVariableAndHeader.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableSslOptions.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestAvailableWafRuleSets.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestTopLevelWafResourceWithApplicationGateway.json
  src/Network/Network/ApplicationGateway/RequestRoutingRule/AzureApplicationGatewayRequestRoutingRuleBase.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSApplicationGatewayRequestRoutingRule.cs
  src/Network/Network/help/Add-AzApplicationGatewayRequestRoutingRule.md
  src/Network/Network/help/Add-AzApplicationGatewaySslCertificate.md
  src/Network/Network/help/New-AzApplicationGatewayRequestRoutingRule.md
  src/Network/Network/help/New-AzApplicationGatewaySslCertificate.md
  src/Network/Network/help/Set-AzApplicationGatewayRequestRoutingRule.md
  src/Network/Network/help/Set-AzApplicationGatewaySslCertificate.md
Labels: needs-review

#13565 [Synapse] Update spark version to 1.0.0-beta.1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Synapse.csproj
Labels: needs-review

#13479 New Start-AzVmssRollingExtensionUpgrade cmdlet
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetExtRollingUpgrade.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Manual/VirtualMachineScaleSetRollingUpgrade/VirtualMachineScaleSetRollingExtensionStartUpgrade.cs
  src/Compute/Compute/help/Start-AzVmssRollingExtensionUpgrade.md
Labels: needs-review

#13576 [NetAppFiles] Anf 7405 update for api version 2020 07 01
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/SnapshotTests.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirectory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.ActiveDirectoryTests/TestActiveDirectoryCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.ActiveDirectoryTests/TestActiveDirectoryPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupPolicyTests/TestBackupPolicyCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupPolicyTests/TestBackupPolicyPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestBackupCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestBackupPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotPolicyTests/TestSnapshotPolicyCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotPolicyTests/TestSnapshotPolicyPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestCreateVolumeFromSnapshot.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestRestoreVolumeFromSnapshot.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VaultTests/TestVaultCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestSetVolumePool.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumePipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeReplication.json
  src/NetAppFiles/NetAppFiles.sln
  src/NetAppFiles/NetAppFiles/Az.NetAppFiles.psd1
  src/NetAppFiles/NetAppFiles/BackupPolicy/NewNetAppFilesBackupPolicy.cs
  src/NetAppFiles/NetAppFiles/BackupPolicy/UpdateNetAppFilesBackupPolicy.cs
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/BackupExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesActiveDirectory.cs
  src/NetAppFiles/NetAppFiles/NetAppFiles.csproj
  src/NetAppFiles/NetAppFiles/help/Az.NetAppFiles.md
  src/NetAppFiles/NetAppFiles/help/Set-AzNetAppFilesVolumePool.md
Labels: Waiting for CI :shipit:

#13568 Az.StackHCI v0.4.1 OOB release
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/ChangeLog.md
  src/StackHCI/Properties/AssemblyInfo.cs
Labels: Waiting for CI :shipit:

#13564 [WindowsIoTServices] Init.
  src/WindowsIotServices/.gitattributes
  src/WindowsIotServices/.gitignore
  src/WindowsIotServices/Az.WindowsIotServices.psd1
  src/WindowsIotServices/custom/readme.md
  src/WindowsIotServices/docs/Az.WindowsIotServices.md
  src/WindowsIotServices/docs/Get-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/docs/New-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/docs/Remove-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/docs/Update-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/docs/readme.md
  src/WindowsIotServices/examples/Get-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/examples/New-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/examples/Remove-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/examples/Update-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/how-to.md
  src/WindowsIotServices/license.txt
  src/WindowsIotServices/readme.md
  src/WindowsIotServices/resources/readme.md
  src/WindowsIotServices/test/Get-AzWindowsIotServicesDevice.Recording.json
  src/WindowsIotServices/test/Get-AzWindowsIotServicesDevice.Tests.ps1
  src/WindowsIotServices/test/New-AzWindowsIotServicesDevice.Recording.json
  src/WindowsIotServices/test/New-AzWindowsIotServicesDevice.Tests.ps1
  src/WindowsIotServices/test/Remove-AzWindowsIotServicesDevice.Recording.json
  src/WindowsIotServices/test/Remove-AzWindowsIotServicesDevice.Tests.ps1
  src/WindowsIotServices/test/Update-AzWindowsIotServicesDevice.Recording.json
  src/WindowsIotServices/test/Update-AzWindowsIotServicesDevice.Tests.ps1
  src/WindowsIotServices/test/env.json
  src/WindowsIotServices/test/loadEnv.ps1
  src/WindowsIotServices/test/readme.md
  src/WindowsIotServices/test/utils.ps1
  src/WindowsIotServices/utils/Unprotect-SecureString.ps1
Labels: Waiting for CI :shipit:

#13457 New-AzApiManagementProduct: Change SubscriptionsLimit parameter default value to None
  src/ApiManagement/ApiManagement.ServiceManagement/Commands/NewAzureApiManagementProduct.cs
  src/ApiManagement/ApiManagement/ChangeLog.md
Labels: Waiting for CI :shipit:, customer-reported

#13524 Supported "all" as an option when setting key vault access policies
  src/KeyVault/KeyVault.Test/ScenarioTests/AccessPolicyTests.cs
  src/KeyVault/KeyVault.Test/ScenarioTests/AccessPolicyTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.AccessPolicyTests/TestSetAllAccessPolicies.json
  src/KeyVault/KeyVault.sln
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs
  src/KeyVault/KeyVault/help/Get-AzKeyVault.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificateIssuer.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultSecret.md
  src/KeyVault/KeyVault/help/Get-AzManagedHsm.md
  src/KeyVault/KeyVault/help/Get-AzManagedHsmKey.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultAccessPolicy.md
Labels: needs-review

#13589 Fix typo for WorkspaceResourceId parameter in example
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorOutputObject.md
Labels: customer-reported

#13412 Remove-AzSynapseSqlPoolRestorePoint
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPool.json
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/RemoveAzureSynapseSqlPoolRestorePoint.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Common/ResourceTypes.cs
  src/Synapse/Synapse/Models/SqlPool Backup/PSRestorePoint.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Remove-AzSynapseSqlPoolRestorePoint.md
Labels: needs-review

#13473 [Tool]Fix the issue of generating generate-info.json
  tools/Gen2Master/MoveFromGeneration2Master.ps1
Labels: needs-review

#13601 {IotHub} Fix sas-token decoding issue
  src/IotHub/IotHub.sln
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/IotHub/DataPlane/NewAzIotHubSasToken.cs
Labels: Waiting for CI :shipit:

#13483 [Resources] Fix issue preventing deployment of Template Specs located outside of the current subscription context
  src/Resources/ResourceManager/Implementation/CmdletBase/ResourceWithParameterCmdletBase.cs
  src/Resources/Resources.Test/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCommandTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#13608 fix parameter for get-azcontainerregistryusage and exception for connect-azcontainerregistry
  src/ContainerRegistry/ContainerRegistry/ChangeLog.md
  src/ContainerRegistry/ContainerRegistry/Commands/GetAzureContainerRegistryUsage.cs
  src/ContainerRegistry/ContainerRegistry/Models/ContainerRegistryDataPlaneClient.cs
  src/ContainerRegistry/ContainerRegistry/help/Get-AzContainerRegistryUsage.md
Labels: Waiting for CI :shipit:
