Repository Azure/azure-powershell, pull requests merged in 2020-01, with the labels that each got.

#10823 upadte Az.psd1 for all Azs modules
  tools/Az/Az.psd1
Labels: Waiting for CI :shipit:

#10813 Fixed Static Analysis issue
  tools/StaticAnalysis/BreakingChangeAnalyzer/BreakingChangeAnalyzer.cs
  tools/VersionController/Models/VersionMetadataHelper.cs
Labels: Bug

#10822 Add PartnerDatabaseName to New-AzSqlDatabaseSecondary cmdlet
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateNamedSecondaryDatabase.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Model/AzureReplicationLinkModel.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
  src/Sql/Sql/Sql.types.ps1xml
  src/Sql/Sql/help/New-AzSqlDatabaseSecondary.md
Labels: needs-revision

#10753 Update New-AzReservation.md
  src/Reservations/Reservations/ChangeLog.md
  src/Reservations/Reservations/help/New-AzReservation.md
Labels: Waiting for CI :shipit:

#10786 [stackadmin branch] Azs.Backup.Admin module generation
  src/StackAdmin/Azs.Backup.Admin/.gitignore
  src/StackAdmin/Azs.Backup.Admin/custom/Get-AzsBackup.ps1
  src/StackAdmin/Azs.Backup.Admin/custom/Restore-AzsBackup.ps1
  src/StackAdmin/Azs.Backup.Admin/custom/Set-AzsBackupConfiguration.ps1
  src/StackAdmin/Azs.Backup.Admin/custom/Start-AzsBackup.ps1
  src/StackAdmin/Azs.Backup.Admin/docs/Azs.Backup.Admin.md
  src/StackAdmin/Azs.Backup.Admin/docs/Get-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/docs/Get-AzsBackupConfiguration.md
  src/StackAdmin/Azs.Backup.Admin/docs/Restore-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/docs/Set-AzsBackupConfiguration.md
  src/StackAdmin/Azs.Backup.Admin/docs/Start-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/examples/Get-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/examples/Get-AzsBackupConfiguration.md
  src/StackAdmin/Azs.Backup.Admin/examples/Restore-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/examples/Set-AzsBackupConfiguration.md
  src/StackAdmin/Azs.Backup.Admin/examples/Start-AzsBackup.md
  src/StackAdmin/Azs.Backup.Admin/readme.md
  src/StackAdmin/Azs.Backup.Admin/test/Common.ps1
  src/StackAdmin/Azs.Backup.Admin/test/Get-AzsBackup.Recording.json
  src/StackAdmin/Azs.Backup.Admin/test/Get-AzsBackup.Tests.ps1
  src/StackAdmin/Azs.Backup.Admin/test/Get-AzsBackupConfiguration.Recording.json
  src/StackAdmin/Azs.Backup.Admin/test/Get-AzsBackupConfiguration.Tests.ps1
  src/StackAdmin/Azs.Backup.Admin/test/Restore-AzsBackup.Recording.json
  src/StackAdmin/Azs.Backup.Admin/test/Restore-AzsBackup.Tests.ps1
  src/StackAdmin/Azs.Backup.Admin/test/Set-AzsBackupConfiguration.Recording.json
  src/StackAdmin/Azs.Backup.Admin/test/Set-AzsBackupConfiguration.Tests.ps1
  src/StackAdmin/Azs.Backup.Admin/test/Start-AzsBackup.Recording.json
  src/StackAdmin/Azs.Backup.Admin/test/Start-AzsBackup.Tests.ps1
Labels: needs-review

#10683 Retrieve policy aliases at tenant level
  src/Blueprint/Blueprint.Test/Blueprint.Test.csproj
  src/Resources/ResourceManager/Implementation/Policy/GetAzurePolicyAliasCmdlet.cs
  src/Resources/ResourceManager/Implementation/Policy/NewAzurePolicyDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/PolicyHelpStrings.cs
  src/Resources/ResourceManager/Implementation/Policy/SetAzurePolicyDefinition.cs
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/ResourceManager/SdkExtensions/ResourcesExtensions.cs
  src/Resources/ResourceManager/SdkModels/Deployments/TemplateValidationInfo.cs
  src/Resources/Resources.Test/Models.ResourceGroups/ResourceClientTests.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/SamplePolicyDefinitionObject.json
  src/Resources/Resources.Test/ScenarioTests/PolicyAliasTests.cs
  src/Resources/Resources.Test/ScenarioTests/PolicyTests.cs
  src/Resources/Resources.Test/ScenarioTests/PolicyTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUD.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUDAtManagementGroup.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionCRUDAtSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionMode.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionWithFullObject.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyDefinitionWithParameters.json
  src/Resources/Resources/ChangeLog.md
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
  tools/Common.Netcore.Dependencies.Test.targets
Labels: needs-review

#10857 Update Set-AzNetworkWatcherConfigFlowLog.md
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/Set-AzNetworkWatcherConfigFlowLog.md
Labels: needs-revision

#10866 [Compute] Disk encryption update
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskEncryptionSet.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/Generated/DiskEncryptionSet/DiskEncryptionSetUpdateMethod.cs
  src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotUpdateConfigCommand.cs
  src/Compute/Compute/help/Az.Compute.md
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
  src/Compute/Compute/help/New-AzSnapshotUpdateConfig.md
  src/Compute/Compute/help/Update-AzDiskEncryptionSet.md
Labels: Waiting for CI :shipit:

#10874 Az.storage preview.3
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Properties/AssemblyInfo.cs
Labels: Waiting for CI :shipit:

#10889 Provide examples for creating ADServicePrincipal with Credential and …
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzADServicePrincipal.md
Labels: needs-review

#10867 webapp: Adding support for MinTls, AlwaysOn, FtpsState properties for an app & slot
  src/Websites/Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetAzureStorageWebAppHyperVSlot.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetWebAppSlot.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetAzureStorageWebAppHyperV.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetWebApp.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestTagsNotRemovedBySetWebApp.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/Websites/Websites/Cmdlets/WebApps/SetAzureWebApp.cs
  src/Websites/Websites/Utilities/CmdletHelpers.cs
  src/Websites/Websites/help/Set-AzWebApp.md
  src/Websites/Websites/help/Set-AzWebAppSlot.md
Labels: needs-review

#10901 Fix Changelog.md errors
  src/Cdn/Cdn/ChangeLog.md
  src/DataBoxEdge/DataBoxEdge/ChangeLog.md
  src/Network/Network/ChangeLog.md
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#10755 update latest VMAccessAgent version to 2.4 instead of 2.0
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/Set-AzVMAccessExtension.md
Labels: Waiting for CI :shipit:

#10676 Changed a parameter name from VaultName to Name
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVault.cs
  src/KeyVault/KeyVault/help/Add-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Add-AzKeyVaultCertificateContact.md
  src/KeyVault/KeyVault/help/Add-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Add-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Add-AzKeyVaultNetworkRule.md
  src/KeyVault/KeyVault/help/Backup-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Backup-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Backup-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Backup-AzKeyVaultSecret.md
  src/KeyVault/KeyVault/help/Import-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/New-AzKeyVaultCertificateAdministratorDetail.md
  src/KeyVault/KeyVault/help/New-AzKeyVaultCertificateOrganizationDetail.md
  src/KeyVault/KeyVault/help/New-AzKeyVaultCertificatePolicy.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVault.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultAccessPolicy.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultCertificateContact.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultCertificateIssuer.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultCertificateOperation.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultManagedStorageSasDefinition.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultNetworkRule.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultSecret.md
  src/KeyVault/KeyVault/help/Restore-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Restore-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Restore-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Restore-AzKeyVaultSecret.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultAccessPolicy.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultCertificateIssuer.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultCertificatePolicy.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultManagedStorageSasDefinition.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultSecret.md
  src/KeyVault/KeyVault/help/Stop-AzKeyVaultCertificateOperation.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultCertificateRemoval.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultKeyRemoval.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultManagedStorageAccountRemoval.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultManagedStorageSasDefinitionRemoval.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultRemoval.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultSecretRemoval.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultManagedStorageAccountKey.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultNetworkRuleSet.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultSecret.md
Labels: needs-review

#10837 ASR changes for Remove-ReplicationProtectedItemDisk
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/A2A/A2ATestsHelper.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/A2A/AsrA2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/A2A/AsrA2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/A2A/AsrA2ATestsBase.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrA2ATests/A2ARemoveReplicationProtectedItemDisk.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/Common/PSAsrReplicationProtectedItemsClient.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/RemoveAzureRmRecoveryServicesAsrReplicationProtectedItemDisk.cs
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Remove-AzRecoveryServicesAsrReplicationProtectedItemDisk.md
Labels: needs-review

#10916 Update New-AzHDInsightCluster.md
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
Labels: needs-review

#10897 Fix for getting ApiSchema associated with an API of Type OpenApi
  src/ApiManagement/ApiManagement.ServiceManagement.Test/ScenarioTests/ApiManagementTests.ps1
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiCrudTest.json
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportOpenApiTest.json
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportSwaggerTest.json
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportWadlTest.json
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiImportExportWsdlTest.json
  src/ApiManagement/ApiManagement.ServiceManagement.Test/SessionRecords/Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Test.ScenarioTests.ApiManagementTests/ApiVersionSetImportCrudTest.json
  src/ApiManagement/ApiManagement.ServiceManagement/Helpers/Utils.cs
  src/ApiManagement/ApiManagement/ChangeLog.md
  src/ApiManagement/ApiManagement/help/New-AzApiManagementProduct.md
  src/ApiManagement/ApiManagement/help/Set-AzApiManagementApi.md
  src/ApiManagement/ApiManagement/help/Set-AzApiManagementProduct.md
Labels: needs-review

#10896 Fix Typo Microsot #9660
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VpnSite/NewAzureRmVpnSiteCommand.cs
Labels: needs-review

#10910 [IotCentral] Add new sku to IotCentral
  src/IotCentral/IotCentral.Test/IotCentral.Test.csproj
  src/IotCentral/IotCentral.Test/ScenarioTests/IotCentralTests.ps1
  src/IotCentral/IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/IotCentral/IotCentral/ChangeLog.md
  src/IotCentral/IotCentral/IotCentral.csproj
  src/IotCentral/IotCentral/Models/PSIotCentralAppSku.cs
  src/IotCentral/IotCentral/Models/PSIotCentralAppSkuInfo.cs
Labels: needs-review

#10927 [ADF] Upgrade SDK to version 4.7
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-review

#10355 Disable context auto saving when AzureRmContext.json not available
  src/Accounts/Accounts.Test/AutoSaveSettingOnLoadingTests.cs
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/AutoSave/DisableAzureRmContextAutosave.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Common/AzureContextModificationCmdlet.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#10934 [Compute] Limit the number of VM status to 100
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineGetStatus.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Properties/Resources.Designer.cs
  src/Compute/Compute/Properties/Resources.resx
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
Labels: needs-revision

#10939 Remove Get-AzAppConfigurationStoreKeyValue from AppConfiguration and fix a minor issue in blockchain
  src/AppConfiguration/readme.md
  src/BlockChain/readme.md
Labels: Waiting for CI :shipit:

#10919 Updates to get maintenance update api
  src/Maintenance/Maintenance.Test/ScenarioTests/MaintenanceTests.ps1
  src/Maintenance/Maintenance/ChangeLog.md
  src/Maintenance/Maintenance/Update/UpdateListMethod.cs
  src/Maintenance/Maintenance/help/Get-AzMaintenanceUpdate.md
Labels: Waiting for CI :shipit:

#10942 add mappings for cosmos db
  tools/CreateMappings_rules.json
Labels: needs-review

#10894 Adding Cmdlet New-AzApplicationGatewayRewriteRuleUrlConfiguration to support url rewrite capability for V2 application gateways
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDRewriteRuleSetUrlConfiguration.json
  src/Network/Network/ApplicationGateway/RewriteRuleActionSet/AzureApplicationGatewayRewriteRuleActionSetBase.cs
  src/Network/Network/ApplicationGateway/RewriteRuleUrlConfiguration/AzureApplicationGatewayRewriteRuleUrlConfigurationBase.cs
  src/Network/Network/ApplicationGateway/RewriteRuleUrlConfiguration/NewAzureApplicationGatewayRewriteRuleUrlConfigurationCommand.cs
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSApplicationGatewayRewriteRuleActionSet.cs
  src/Network/Network/Models/PSApplicationGatewayUrlConfiguration.cs
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/New-AzApplicationGatewayRewriteRuleActionSet.md
  src/Network/Network/help/New-AzApplicationGatewayRewriteRuleUrlConfiguration.md
Labels: Waiting for CI :shipit:

#10878 Sobaner/wildcardlistener
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayWithListenerHostNames.json
  src/Network/Network/ApplicationGateway/HttpListener/AzureApplicationGatewayHttpListenerBase.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSApplicationGatewayHttpListener.cs
  src/Network/Network/help/Add-AzApplicationGatewayHttpListener.md
  src/Network/Network/help/New-AzApplicationGatewayHttpListener.md
  src/Network/Network/help/Set-AzApplicationGatewayHttpListener.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#10933 Add support for forced tunneling/management subnet and management IP configuration
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDwithManagementIpConfig.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/Network.csproj
  src/Network/Network/help/Get-AzFirewall.md
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/Set-AzFirewall.md
Labels: Waiting for CI :shipit:

#10902 fix broken links
  documentation/development-docs/design-guidelines/parameter-best-practices.md
Labels: Doc - Internal, needs-review

#10893 Added support to optionally include sub-folders when deploying blueprints with artifacts
  src/Blueprint/Blueprint/ChangeLog.md
  src/Blueprint/Blueprint/Cmdlets/BlueprintDefinition/BlueprintDefinitionCmdletBase.cs
  src/Blueprint/Blueprint/Cmdlets/BlueprintDefinition/ImportAzureRMBlueprint.cs
  src/Blueprint/Blueprint/Common/BlueprintConstants.cs
  src/Blueprint/Blueprint/help/Import-AzBlueprintWithArtifact.md
Labels: Waiting for CI :shipit:

#10895 Cross Subscription Restore For Managed Instance.
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseCrudScenarioTests.ps1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedDatabase/Cmdlet/RestoreAzureSqlManagedDatabase.cs
  src/Sql/Sql/help/Restore-AzSqlInstanceDatabase.md
Labels: needs-review

#10973 Fix Broken Example Code
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/Grant-AzSnapshotAccess.md
  src/Compute/Compute/help/Revoke-AzSnapshotAccess.md
Labels: Waiting for CI :shipit:

#10948 powershell cmdlets for connection monitor V2
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/Network/Network/Az.Network.psd1
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSConnectionMonitor.cs
  src/Network/Network/Models/PSConnectionMonitorEndPoint.cs
  src/Network/Network/Models/PSConnectionMonitorEndpointFilter.cs
  src/Network/Network/Models/PSConnectionMonitorEndpointFilterItem.cs
  src/Network/Network/Models/PSConnectionMonitorHttpConfiguration.cs
  src/Network/Network/Models/PSConnectionMonitorIcmpConfiguration.cs
  src/Network/Network/Models/PSConnectionMonitorOutput.cs
  src/Network/Network/Models/PSConnectionMonitorProtocolConfiguration.cs
  src/Network/Network/Models/PSConnectionMonitorResult.cs
  src/Network/Network/Models/PSConnectionMonitorSuccessThreshold.cs
  src/Network/Network/Models/PSConnectionMonitorTcpConfiguration.cs
  src/Network/Network/Models/PSConnectionMonitorTestConfiguration.cs
  src/Network/Network/Models/PSConnectionMonitorTestGroup.cs
  src/Network/Network/Models/PSConnectionMonitorWorkspaceSettings.cs
  src/Network/Network/Models/PSHTTPHeader.cs
  src/Network/Network/Models/PSNetworkWatcherConnectionMonitorObject.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkWatcher/ConnectionMonitor/ConnectionMonitorBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/GetAzureNetworkWatcherConnectionMonitorCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/GetAzureNetworkWatcherConnectionMonitorReportCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndPointObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndpointFilterItemObject.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorObject.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorOutputObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorProtocolConfigurationObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorTestConfigurationObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorTestGroupObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/RemoveAzureNetworkWatcherConnectionMonitorCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/SetAzureNetworkWatcherConnectionMonitorCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/StartAzureNetworkWatcherConnectionMonitorCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/StopAzureNetworkWatcherConnectionMonitorCommand.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/Get-AzNetworkWatcherConnectionMonitor.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitor.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorOutputObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorTestConfigurationObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorTestGroupObject.md
  src/Network/Network/help/Set-AzNetworkWatcherConnectionMonitor.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#10977 [AzureStack] Azs.Subscriptions.Admin: Test and Custom scripts
  src/StackAdmin/Azs.Subscriptions.Admin/custom/New-AzsAcquiredPlan.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/custom/New-AzsOffer.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/custom/New-AzsPlan.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/custom/Set-AzsOffer.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/custom/Set-AzsPlan.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/custom/Set-AzsUserSubscription.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/readme.md
  src/StackAdmin/Azs.Subscriptions.Admin/test/AcquiredPlan.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/AdminManagedOffer.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/Common.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/DelegatedProvider.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/DelegatedProviderManagedOffer.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/DirectoryTenant.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/Location.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/OfferDelegation.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/Plan.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/SubscriptionQuota.Tests.ps1
  src/StackAdmin/Azs.Subscriptions.Admin/test/UserSubscription.Tests.ps1
  src/StackAdmin/readme.azurestack.md
Labels: needs-review

#10978 readme.md transformations and ported unit tests for AzureBridge module
  src/StackAdmin/Azs.AzureBridge.Admin/readme.md
  src/StackAdmin/Azs.AzureBridge.Admin/test/Common.ps1
  src/StackAdmin/Azs.AzureBridge.Admin/test/Get-AzsAzureBridgeActivation.Tests.ps1
  src/StackAdmin/Azs.AzureBridge.Admin/test/Get-AzsAzureBridgeDownloadedProduct.Tests.ps1
  src/StackAdmin/Azs.AzureBridge.Admin/test/Get-AzsAzureBridgeProduct.Tests.ps1
  src/StackAdmin/Azs.AzureBridge.Admin/test/Invoke-AzsAzureBridgeProductDownload.Tests.ps1
  src/StackAdmin/Azs.AzureBridge.Admin/test/Override.ps1
  src/StackAdmin/Azs.AzureBridge.Admin/test/Remove-AzsAzureBridgeDownloadedProduct.Tests.ps1
Labels: needs-review

#10971 Powershell Fix for AFS GA
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileShareItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.format.ps1xml
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupItem.md
Labels: needs-revision
