Repository Azure/azure-powershell, pull requests merged in 2020-03, with the labels that each got.

#11193 Added new cmdlets for flowLog resource
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/Network/Network/Az.Network.psd1
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSFlowLogResource.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkWatcher/FlowLog/FlowLogBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/FlowLog/GetAzNetworkWatcherFlowLogCommand.cs
  src/Network/Network/NetworkWatcher/FlowLog/NewAzNetworkWatcherFlowLogCommand.cs
  src/Network/Network/NetworkWatcher/FlowLog/RemoveAzNetworkWatcherFlowLogCommand.cs
  src/Network/Network/NetworkWatcher/FlowLog/SetAzNetworkWatcherFlowLogCommand.cs
  src/Network/Network/NetworkWatcher/SetAzureNetworkWatcherConfigFlowLogCommand.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/Get-AzNetworkWatcherFlowLog.md
  src/Network/Network/help/New-AzNetworkWatcherFlowLog.md
  src/Network/Network/help/Remove-AzNetworkWatcherFlowLog.md
  src/Network/Network/help/Set-AzNetworkWatcherFlowLog.md
Labels: needs-revision

#11182 Min scale units fix - new min value is 1
  src/Network/Network/Cortex/ExpressRouteGateway/NewAzureRmExpressRouteGatewayCommand.cs
Labels: needs-revision

#11204 Add PublicNetworkAccess to New-AzSqlServer and Set-AzSqlServer
  src/Network/Network/Network.csproj
  src/Sql/Sql.Test/ScenarioTests/AdvancedDataSecurityTests.cs
  src/Sql/Sql.Test/ScenarioTests/AdvisorTests.cs
  src/Sql/Sql.Test/ScenarioTests/AuditTests.cs
  src/Sql/Sql.Test/ScenarioTests/DataClassificationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DataMaskingTests.cs
  src/Sql/Sql.Test/ScenarioTests/DataSyncTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseActivationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupStretchTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudStretchTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobAgentCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobCredentialCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobExecutionCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobStepCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobTargetCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticJobTargetGroupCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/FailoverGroupTests.cs
  src/Sql/Sql.Test/ScenarioTests/FailoverTests.cs
  src/Sql/Sql.Test/ScenarioTests/ImportExportTests.cs
  src/Sql/Sql.Test/ScenarioTests/ReadScaleCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServerCommunicationLinkCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServerCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServerCrudTests.ps1
  src/Sql/Sql.Test/ScenarioTests/ServerDnsAliasTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServerKeyVaultKeyTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServiceObjectiveTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServiceTierAdvisorTests.cs
  src/Sql/Sql.Test/ScenarioTests/TDECertificateTests.cs
  src/Sql/Sql.Test/ScenarioTests/ThreatDetectionTests.cs
  src/Sql/Sql.Test/ScenarioTests/TransparentDataEncryptionCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/VirtualNetworkRuleTest.cs
  src/Sql/Sql.Test/ScenarioTests/VulnerabilityAssessmentTests.cs
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerCreateAndGetWithPublicNetworkAccess.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerCreateWithIdentity.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerGet.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerRemove.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithIdentity.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithPublicNetworkAccess.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithoutIdentity.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/Server/Model/AzureSqlServerModel.cs
  src/Sql/Sql/Server/Services/AzureSqlServerAdapter.cs
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/New-AzSqlServer.md
  src/Sql/Sql/help/Set-AzSqlServer.md
Labels: needs-review

#11229 Add Minimal Tls Version Optional Parameter for SQLDB/MI
  src/Network/Network/Network.csproj
  src/Sql/Sql.Test/ScenarioTests/AdvancedDataSecurityManagedInstanceTests.cs
  src/Sql/Sql.Test/ScenarioTests/DataClassificationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DataSyncTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseCrudScenarioTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/ScenarioTests/ServerCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServerCrudTests.ps1
  src/Sql/Sql.Test/ScenarioTests/VulnerabilityAssessmentMiTests.cs
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateUpdateManagedInstanceWithMinimalTlsVersion.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/CreateandUpdateServerWithMinimalTlsVersion.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/Server/Model/AzureSqlServerModel.cs
  src/Sql/Sql/Server/Services/AzureSqlServerAdapter.cs
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlServer.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlServer.md
Labels: Sprint Candidate

#11250 Merge changes from feature/tagApi-2019-10-01 to Az.Resources-preview
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Resources/ResourceManager/Implementation/ResourceGroups/GetAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/ResourceManager.format.ps1xml
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/ResourceManager/SdkModels/Resources/PSResource.cs
  src/Resources/Resources.Test/Models.ResourceGroups/ResourceClientTests.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/ResourceGroupTests.ps1
  src/Resources/Resources.Test/ScenarioTests/TagTests.cs
  src/Resources/Resources.Test/ScenarioTests/TagTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests/TestFindResourceGroup.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagCreateOrUpdateWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagCreateOrUpdateWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagDeleteWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagDeleteWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagGetWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagGetWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagUpdateWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagUpdateWithResourceIdParamsForSubscription.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Az.Resources.md
  src/Resources/Resources/help/Get-AzResource.md
  src/Resources/Resources/help/Get-AzTag.md
  src/Resources/Resources/help/New-AzTag.md
  src/Resources/Resources/help/Remove-AzTag.md
  src/Resources/Resources/help/Update-AzTag.md
  src/Resources/Tags/Client/TagBaseCmdlet.cs
  src/Resources/Tags/Client/TagsClient.cs
  src/Resources/Tags/Model/PSTagResource.cs
  src/Resources/Tags/Model/PSTagsObject.cs
  src/Resources/Tags/Model/TagPatchOperation.cs
  src/Resources/Tags/Model/TagsExtensions.cs
  src/Resources/Tags/Properties/Resources.Designer.cs
  src/Resources/Tags/Properties/Resources.resx
  src/Resources/Tags/Tag/GetAzureTagCommand.cs
  src/Resources/Tags/Tag/NewAzureTagCommand.cs
  src/Resources/Tags/Tag/RemoveAzureTagCommand.cs
  src/Resources/Tags/Tag/UpdateAzureTagCommand.cs
  src/Resources/Tags/Tags.csproj
  src/Resources/Tags/Tags.format.ps1xml
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetWebAppSlot.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetWebApp.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
  tools/Common.Netcore.Dependencies.Test.targets
Labels: needs-review

#11255 Use MsalCacheHelper to do cache IO
  src/Accounts/Authentication/Authentication.csproj
  src/Accounts/Authentication/Authentication/Clients/AuthenticationClientFactory.cs
  src/Accounts/Authentication/Authentication/Clients/SharedTokenCacheClientFactory.cs
  src/lib/Microsoft.Identity.Client.Extensions.Msal/NetCore/Microsoft.Identity.Client.Extensions.Msal.dll
  src/lib/Microsoft.Identity.Client.Extensions.Msal/NetFx/Microsoft.Identity.Client.Extensions.Msal.dll
Labels: needs-review

#11249 Get-AzGalleryImageVersion fix example args
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/Get-AzGalleryImageVersion.md
Labels: Waiting for CI :shipit:

#10931 Update New-AzScheduledQueryRuleLogMetricTrigger.md
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/help/New-AzScheduledQueryRuleLogMetricTrigger.md
Labels: Monitor, Waiting for CI :shipit:

#10827 [WIP] Fix Microsoft.Azure.PowerShell.Cmdlets.ManagedServices.dll.json
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.ManagedServices.dll.json
Labels: needs-review

#11252 Fix typo
  src/Network/Network/help/Az.Network.md
Labels: Waiting for CI :shipit:

#11269 Fix changelog merge issue
  src/IotHub/IotHub/ChangeLog.md
Labels: needs-review

#10303 Nullreferenceexception in az accounts#10292
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Default/ClearAzureRmDefault.cs
  src/Accounts/Accounts/Default/GetAzureRmDefault.cs
  src/Accounts/Accounts/Default/SetAzureRMDefault.cs
  src/Accounts/Accounts/Models/RMProfileClient.cs
Labels: needs-review

#11232 [Az.Functions] Preview bug fixes
  src/Functions/Az.Functions.psd1
  src/Functions/custom/Api20180201/Site.cs
  src/Functions/custom/Functions.format.ps1xml
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
  src/Functions/custom/FunctionsStack/WindowsFunctionsStacks.json
  src/Functions/custom/HelperFunctions.ps1
  src/Functions/custom/New-AzFunctionApp.ps1
  src/Functions/custom/New-AzFunctionAppPlan.ps1
  src/Functions/custom/Remove-AzFunctionApp.ps1
  src/Functions/custom/Remove-AzFunctionAppPlan.ps1
  src/Functions/custom/Restart-AzFunctionApp.ps1
  src/Functions/custom/Start-AzFunctionApp.ps1
  src/Functions/custom/Stop-AzFunctionApp.ps1
  src/Functions/custom/api/Support/FunctionsVersionType.cs
  src/Functions/custom/api/Support/RuntimeType.cs
  src/Functions/docs/hybrid-2019-03-01/Az.Functions.md
  src/Functions/docs/hybrid-2019-03-01/New-AzFunctionApp.md
  src/Functions/docs/latest-2019-04-30/Az.Functions.md
  src/Functions/docs/latest-2019-04-30/Get-AzFunctionApp.md
  src/Functions/docs/latest-2019-04-30/Get-AzFunctionAppAvailableLocation.md
  src/Functions/docs/latest-2019-04-30/Get-AzFunctionAppPlan.md
  src/Functions/docs/latest-2019-04-30/New-AzFunctionApp.md
  src/Functions/docs/latest-2019-04-30/New-AzFunctionAppPlan.md
  src/Functions/docs/latest-2019-04-30/Remove-AzFunctionApp.md
  src/Functions/docs/latest-2019-04-30/Remove-AzFunctionAppPlan.md
  src/Functions/docs/latest-2019-04-30/Restart-AzFunctionApp.md
  src/Functions/docs/latest-2019-04-30/Start-AzFunctionApp.md
  src/Functions/docs/latest-2019-04-30/Stop-AzFunctionApp.md
  src/Functions/test/Functions.Scenario.Tests.ps1
Labels: Az 4.x Preview, needs-revision

#11237 Pass auth headers for virtualHubVnetConnection support across different tenants
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/HubVnetConnection/NewAzureRmHubVirtualNetworkConnectionCommand.cs
  src/Network/Network/Cortex/HubVnetConnection/UpdateAzureRmHubVirtualNetworkConnectionCommand.cs
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/UpdateAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/VirtualHubBaseCmdlet.cs
Labels: Waiting for CI :shipit:

#11295 Add note about the version of PowerShell
  docker/README.md
Labels: Waiting for CI :shipit:

#11253 Display ResourceManager correlationIds in error output
  src/Resources/ResourceManager/Implementation/CmdletBase/ResourceManagerCmdletBase.cs
  src/Resources/ResourceManager/Implementation/Deployments/GetAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/GetAzureManagementGroupDeploymentOperationCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/GetAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/GetAzureSubscriptionDeploymentOperationCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/GetAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/GetAzureTenantDeploymentOperationCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/RemoveAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/RemoveAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/RemoveAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/StopAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/StopAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/StopAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Locations/GetAzureLocationCmdlet.cs
  src/Resources/ResourceManager/Implementation/Policy/GetAzurePolicyAliasCmdlet.cs
  src/Resources/ResourceManager/Implementation/Providers/GetAzureProviderCmdlet.cs
  src/Resources/ResourceManager/Implementation/Providers/RegisterAzureProviderCmdlet.cs
  src/Resources/ResourceManager/Implementation/Providers/UnregisterAzureProviderCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/RemoveAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/StopAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/TestAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroups/GetAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroups/NewAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroups/RemoveAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroups/SetAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/RestClients/ResourceManagerRestClientBase.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerCloudException.cs
  src/Resources/Resources.Test/ScenarioTests/ResourceGroupTests.ps1
  src/Resources/Resources.Test/ScenarioTests/ResourceLockTests.ps1
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#11283 [Maps] Update Privacy Notice text displayed when creating a Map account
  src/Maps/Maps/ChangeLog.md
  src/Maps/Maps/Properties/Resources.Designer.cs
  src/Maps/Maps/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#11279 Restore-AzSqlInstanceDatabase - fix "an" -> "a"
  src/Sql/Sql/help/Restore-AzSqlInstanceDatabase.md
Labels: Waiting for CI :shipit:

#11304 Create DisableAzureSqlServerActiveDirectoryOnlyAuthentication.cs
  src/Sql/Sql/ServerActiveDirectoryAdministrator/Cmdlet/DisableAzureSqlServerActiveDirectoryOnlyAuthentication.cs
Labels: Waiting for CI :shipit:

#11303 disable one test case that is unstable on linux
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.cs
Labels: needs-review

#11307 pick up updates to PublishModules.ps1 on master
  tools/PublishModules.ps1
Labels: needs-review

#11302 update macos to 10.14
  .azure-pipelines/powershell-core.yml
Labels: needs-review

#11294 Improve PolicyInsights error messages
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/RemediationTests.cs
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/RemediationTests.ps1
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.RemediationTests/ErrorHandling.json
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/PolicyInsights/PolicyInsights/Cmdlets/GetAzPolicyMetadata.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/GetAzureRmPolicyEvent.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/GetAzureRmPolicyState.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/GetAzureRmPolicyStateSummary.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Remediation/GetAzureRmPolicyRemediation.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Remediation/RemoveAzureRmPolicyRemediation.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Remediation/StartAzureRmPolicyRemediation.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Remediation/StopAzureRmPolicyRemediation.cs
  src/PolicyInsights/PolicyInsights/Common/ParameterHelpMessages.cs
  src/PolicyInsights/PolicyInsights/Common/PolicyInsightsCmdletBase.cs
  src/PolicyInsights/PolicyInsights/help/Start-AzPolicyRemediation.md
Labels: needs-review

#11306 Updating changelog.md and correcting parameter IsAzureADOnlyAuthentication
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ServerActiveDirectoryAdministrator/Cmdlet/SetAzureSqlServerActiveDirectoryAdministrator.cs
  src/Sql/Sql/help/Set-AzSqlServerActiveDirectoryAdministrator.md
Labels: needs-revision

#11318 Update C# SDK to throw Cloud Exception, Update default SKU to be ST2
  src/IotCentral/IotCentral.Test/IotCentral.Test.csproj
  src/IotCentral/IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/IotCentral/IotCentral/ChangeLog.md
  src/IotCentral/IotCentral/IotCentral.csproj
  src/IotCentral/IotCentral/IotCentral/NewAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/help/New-AzIotCentralApp.md
Labels: needs-review

#11268 Resources/GetAzureResourceCmdlet.cs fix #11267 get-azresource to use actual apiVersion of resource with parameter set -ResourceGroupName -Name -ExpandProperties -ResourceType
  src/Resources/ResourceManager/Implementation/Resource/GetAzureResourceCmdlet.cs
  src/Resources/Resources.Test/ScenarioTests/ResourceTests.cs
  src/Resources/Resources.Test/ScenarioTests/ResourceTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceTests/TestGetResourceByNameAndType.json
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#11313 ASR: ADE Reprotect and Update bug fixes
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/SetAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/UpdateAzureRmRecoveryServicesAsrProtectionDirection.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#11323 Escape single quote
  src/Resources/Resources/ActiveDirectory/Cmdlets/GetAzureADUserCommand.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#11341 Fix doc
  src/Network/Network/help/Get-AzAvailablePrivateEndpointType.md
Labels: Waiting for CI :shipit:

#11334 Update Get-AzResourceLock.md to add an extra example
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Get-AzResourceLock.md
Labels: Waiting for CI :shipit:

#11292 SAP AEM: add support for new VM Extension for SAP
  src/Compute/Compute.Test/ScenarioTests/AEMExtensionTests.cs
  src/Compute/Compute.Test/ScenarioTests/AEMExtensionTests.ps1
  src/Compute/Compute.Test/ScenarioTests/ComputeTestRunner.cs
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestExtensionDowngrade.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestExtensionReinstall.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestExtensionUpgrade.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestNewExtensionDiskAdd.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestOldExtensionReinstall.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestWithSystemAssignedIdentity.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestWithUserAssignedIdentity.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests/TestWithoutIdentity.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/AEM/AEMExtensionConstants.cs
  src/Compute/Compute/Extension/AEM/AEMHelper.cs
  src/Compute/Compute/Extension/AEM/ArrayExtensions.cs
  src/Compute/Compute/Extension/AEM/GetAzureRmVMAEMExtension.cs
  src/Compute/Compute/Extension/AEM/RemoveAzureRmVMAEMExtension.cs
  src/Compute/Compute/Extension/AEM/SetAzureRmVMAEMExtension.cs
  src/Compute/Compute/Extension/AEM/TestAzureRmVMAEMExtension.cs
  src/Compute/Compute/help/Set-AzVMAEMExtension.md
Labels: needs-revision

#11266 Deployment Scripts cmdlets
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentScriptCmdletBase.cs
  src/Resources/ResourceManager/Implementation/DeploymentScripts/GetAzDeploymentScript.cs
  src/Resources/ResourceManager/Implementation/DeploymentScripts/GetAzDeploymentScriptLog.cs
  src/Resources/ResourceManager/Implementation/DeploymentScripts/RemoveAzDeploymentScript.cs
  src/Resources/ResourceManager/Implementation/DeploymentScripts/SaveAzDeploymentScriptLog.cs
  src/Resources/ResourceManager/Properties/Resources.Designer.cs
  src/Resources/ResourceManager/Properties/Resources.resx
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/ResourceManager.format.ps1xml
  src/Resources/ResourceManager/SdkClient/DeploymentScriptsSdkClient.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsAzureCliScript.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsAzurePowerShellScript.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsAzureResourceBase.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsAzureScriptBase.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsDeploymentScript.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsDeploymentScriptLog.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsDeploymentScriptLogPath.cs
  src/Resources/Resources.Test/DeploymentScriptsTests/SaveAzDeploymentScriptLogCommandTests.cs
  src/Resources/Resources.Test/Mocks/MockDataStore.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentScriptsTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentScriptsTests.ps1
  src/Resources/Resources.Test/ScenarioTests/ResourcesController.cs
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptGetAllDeploymentScriptPropertiesCli.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptGetForCli.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptGetForPowerShell.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptLogGetForCli.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptLogGetForPowerShell.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptPipeDeploymentScriptObjectToGetLogs.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptRemoveDeploymentScriptCli.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptRemoveDeploymentScriptPowerShell.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptRemovePipedDeploymentScriptObject.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptTryRemoveNonExistingDeploymentScript.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentScriptsTests/TestDeploymentScriptTrySaveNonExistingFilePathForLogFile.json
  src/Resources/Resources.Test/TemplateScriptDeployment.json
  src/Resources/Resources.Test/TemplateScriptDeploymentCli.json
  src/Resources/Resources.Test/TemplateScriptDeploymentParameters.json
  src/Resources/Resources.Test/TemplateScriptDeploymentParametersCli.json
  src/Resources/Resources.Test/TemplateScriptDeploymentParametersCliBadScript.json
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Get-AzDeploymentScript.md
  src/Resources/Resources/help/Get-AzDeploymentScriptLog.md
  src/Resources/Resources/help/Remove-AzDeploymentScript.md
  src/Resources/Resources/help/Save-AzDeploymentScriptLog.md
Labels: needs-revision

#11363 Fix the bug of RunVerioncontroller.ps1
  tools/RunVersionController.ps1
Labels: needs-review

#11360 [ASR] [V2A] Adding properties for VMware DR monitoring
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSFabricDetails.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryServices.SiteRecovery.csproj
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-revision

#11349 [Az.Attestation] Improved error messages and updated examples in documentation
  src/Attestation/Attestation/ChangeLog.md
  src/Attestation/Attestation/Commands/GetAzureAttestationPolicy.cs
  src/Attestation/Attestation/Commands/ResetAzureAttestationPolicy.cs
  src/Attestation/Attestation/Commands/SetAzureAttestationPolicy.cs
  src/Attestation/Attestation/Models/AttestationDataServiceClient.cs
  src/Attestation/Attestation/Models/ServerError.cs
  src/Attestation/Attestation/help/Add-AzAttestationPolicySigner.md
  src/Attestation/Attestation/help/Get-AzAttestation.md
  src/Attestation/Attestation/help/Get-AzAttestationPolicy.md
  src/Attestation/Attestation/help/Get-AzAttestationPolicySigners.md
  src/Attestation/Attestation/help/New-AzAttestation.md
  src/Attestation/Attestation/help/Remove-AzAttestation.md
  src/Attestation/Attestation/help/Remove-AzAttestationPolicySigner.md
  src/Attestation/Attestation/help/Reset-AzAttestationPolicy.md
  src/Attestation/Attestation/help/Set-AzAttestationPolicy.md
Labels: needs-review

#11350 [Compute] Fix AutomaticRepairsPolicy issue
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetProfileTests.ps1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-review

#11364 Save sensitivity rank when classifying columns
  src/Network/Network/Network.csproj
  src/Sql/Sql.Test/ScenarioTests/DataClassificationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestDataClassificationOnSqlDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestEnableDisableRecommendationsOnSqlDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestErrorIsThrownWhenInvalidClassificationIsSet.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/DataClassification/InformationProtectionPolicy.cs
  src/Sql/Sql/DataClassification/Model/SensitivityLabelModel.cs
  src/Sql/Sql/DataClassification/Services/DataClassificationAdapter.cs
  src/Sql/Sql/DataClassification/Services/DataClassificationEndpointsCommunicator.cs
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/Get-AzSqlDatabaseSensitivityClassification.md
  src/Sql/Sql/help/Get-AzSqlDatabaseSensitivityRecommendation.md
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseSensitivityClassification.md
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseSensitivityRecommendation.md
Labels: needs-review

#11366 DataFactory: Add optional parameters to Invoke-AzDataFactoryV2Pipeline to support rerun
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/RunTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.RunTests/TestRunV2.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.Pipelines.cs
  src/DataFactory/DataFactoryV2/Runs/InvokeAzureDataFactoryPipelineCommand.cs
Labels: Waiting for CI :shipit:

#11359 Added support for retry policy update for failed items
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/PolicyTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadPolicy.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
Labels: needs-review

#11344 [HDInsight] Support customers specify min TLS version when creating cluster
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HDInsight/HDInsight.Test/ScenarioTests/Common.ps1
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestClusterRelatedCommands.json
  src/HDInsight/HDInsight.Test/UnitTests/NewClusterTests.cs
  src/HDInsight/HDInsight.Test/UnitTests/PremiumClusterTests.cs
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/HDInsight.csproj
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterConfigCommand.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightCluster.cs
  src/HDInsight/HDInsight/Models/Management/AzureHDInsightConfig.cs
  src/HDInsight/HDInsight/Models/Management/AzureHdInsightManagementClient.cs
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
  src/HDInsight/HDInsight/help/New-AzHDInsightClusterConfig.md
Labels: needs-revision

#11355 Added option of Byte encoding for New-AzDataLakeStoreItem, Add-AzDAtaLakeStoreItemContent, Get-AzDAtaLakeStoreItemContent
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.cs
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystem.json
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests/TestAdlsFileSystem.json
  src/DataLakeStore/DataLakeStore/ChangeLog.md
  src/DataLakeStore/DataLakeStore/DataPlaneCommands/AddAzureRmDataLakeStoreItemContent.cs
  src/DataLakeStore/DataLakeStore/DataPlaneCommands/GetAzureRmDataLakeStoreItemContent.cs
  src/DataLakeStore/DataLakeStore/DataPlaneCommands/NewAzureRmDataLakeStoreItem.cs
  src/DataLakeStore/DataLakeStore/DataPlaneModels/ByteEncoding.cs
  src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemCmdletBase.cs
  src/DataLakeStore/DataLakeStore/DataPlaneModels/EncodingUtils.cs
Labels: needs-review

#11389 [Compute] March release
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestGallery.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Gallery/GalleryDeleteMethod.cs
  src/Compute/Compute/Generated/GalleryImage/GalleryImageDeleteMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionDeleteMethod.cs
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Generated/Models/PSDisk.cs
  src/Compute/Compute/Generated/Models/PSDiskUpdate.cs
  src/Compute/Compute/Generated/Models/PSHostGroup.cs
  src/Compute/Compute/Generated/Models/PSHostList.cs
  src/Compute/Compute/Generated/Models/PSResourceSku.cs
  src/Compute/Compute/Generated/Models/PSRunCommandDocument.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSetVM.cs
  src/Compute/Compute/Generated/ProximityPlacementGroup/ProximityPlacementGroupDeleteMethod.cs
  src/Compute/Compute/Generated/VirtualMachine/VirtualMachineReimageMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetDeallocateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetDeleteInstancesMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetReimageMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetRestartMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetStartMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateInstancesMethod.cs
  src/Compute/Compute/help/New-AzDiskConfig.md
  src/Compute/Compute/help/New-AzGalleryImageVersion.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: needs-review

#11348 Update New-AzNetworkInterface.md
  src/Network/Network/help/New-AzNetworkInterface.md
Labels: Doc - Reference, Waiting for CI :shipit:

#11373 [RecoveryServices.Backup]Added support for restoring multiple files/folders in AzureFileShare
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: Sprint Candidate, Waiting for CI :shipit:

#11394 [RecoveryServices.Backup] Added User ResourceGroup Feature in IAASVM policy
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/PolicyTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
Labels: Sprint Candidate

#11271 [AppService]: #7682- Added new cmdlets for managing Routing Rules
  src/Websites/Websites.Test/ScenarioTests/RoutingRuleTests.cs
  src/Websites/Websites.Test/ScenarioTests/RoutingRuleTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.RoutingRuleTests/TestAddWebAppTrafficRoutingRule.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.RoutingRuleTests/TestGetWebAppTrafficRoutingRule.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.RoutingRuleTests/TestRemoveWebAppTrafficRoutingRule.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.RoutingRuleTests/TestUpdateWebAppTrafficRoutingRule.json
  src/Websites/Websites.Test/Websites.Test.csproj
  src/Websites/Websites/Az.Websites.psd1
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/TrafficRouting/AddAzureWebAppTrafficRoutingRule.cs
  src/Websites/Websites/Cmdlets/TrafficRouting/GetAzureWebAppTrafficRoutingRule.cs
  src/Websites/Websites/Cmdlets/TrafficRouting/RemoveAzureWebAppTrafficRoutingRule.cs
  src/Websites/Websites/Cmdlets/TrafficRouting/UpdateAzureWebAppTrafficRoutingRule.cs
  src/Websites/Websites/Properties/Resources.Designer.cs
  src/Websites/Websites/Properties/Resources.resx
  src/Websites/Websites/Utilities/CmdletHelpers.cs
  src/Websites/Websites/Websites.csproj
  src/Websites/Websites/help/Add-AzWebAppTrafficRouting.md
  src/Websites/Websites/help/Get-AzWebAppTrafficRouting.md
  src/Websites/Websites/help/Remove-AzWebAppTrafficRouting.md
  src/Websites/Websites/help/Update-AzWebAppTrafficRouting.md
Labels: Cmdlet Review Complete, Sprint Candidate, Waiting for CI :shipit:

#11404 Add breaking change description for Export-AzDataLakeStoreItem and Import-AzDataLakeStoreItem
  src/DataLakeStore/DataLakeStore/ChangeLog.md
  src/DataLakeStore/DataLakeStore/DataPlaneCommands/ExportAzureRmDataLakeStoreItem.cs
  src/DataLakeStore/DataLakeStore/DataPlaneCommands/ImportAzureRmDataLakeStoreItem.cs
Labels: Sprint Candidate, Waiting for CI :shipit:

#11408 [KeyVault] add breaking change attributes
  src/Compute/Compute.sln
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/help/Add-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Get-AzKeyVault.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificateIssuer.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultManagedStorageAccount.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultSecret.md
Labels: Sprint Candidate, needs-review

#11405 Comment out the exportchildproperties test in aliastest of testfilesystem, and unskip the adlstest.testfilesystem
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.ps1
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.cs
  src/DataLakeStore/DataLakeStore.Test/SessionRecords/Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests/TestAdlsFileSystem.json
Labels: needs-review

#11392 Update Set-AzApiManagementGroup.md because of missing required parameter in example
  src/ApiManagement/ApiManagement/ChangeLog.md
  src/ApiManagement/ApiManagement/help/Set-AzApiManagementGroup.md
Labels: Waiting for CI :shipit:
