Repository Azure/azure-powershell, pull requests merged in 2020-10, with the labels that each got.

#13098 return multiple suggestion
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/PredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSettings.json
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ITelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterSet.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Prediction.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Settings.cs
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine2.dll
  tools/Az.Tools.Predictor/MockPSConsole/Program.cs
Labels: needs-review

#12871 VM OrchestrationMode: PlatformFaultDomainCount in New-AzVmss and VmssId in New-AzVm
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetOrchestrationVM.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVmss.md
Labels: Breaking Change Release, Waiting for CI :shipit:

#13113 Remove dependencies
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorConstants.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Predictor.cs
  tools/Az.Tools.Predictor/build.proj
Labels: needs-review

#13160 Update AzDisk cmdlet documents to use parameter names instead of alias and correct parameter value
  src/Compute/Compute/help/New-AzDisk.md
  src/Compute/Compute/help/New-AzDiskConfig.md
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
  src/Compute/Compute/help/Set-AzDiskDiskEncryptionKey.md
  src/Compute/Compute/help/Set-AzDiskKeyEncryptionKey.md
  src/Compute/Compute/help/Set-AzDiskUpdateDiskEncryptionKey.md
  src/Compute/Compute/help/Set-AzDiskUpdateKeyEncryptionKey.md
  src/Compute/Compute/help/Update-AzDisk.md
Labels: needs-review

#13116 [DataFactory] Upgrade sdk version to 4.12.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Waiting for CI :shipit:

#13099 Update Invoke-AzStorageSyncChangeDetection.md
  src/StorageSync/StorageSync/help/Invoke-AzStorageSyncChangeDetection.md
Labels: needs-review

#13161 resolved problems with urls in help files
  src/Accounts/Accounts/help/Add-AzEnvironment.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultAccessPolicy.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultAccessPolicy.md
  src/Resources/Resources/help/Get-AzResource.md
  src/Resources/Resources/help/Move-AzResource.md
  src/Resources/Resources/help/New-AzResource.md
  src/Resources/Resources/help/Remove-AzResource.md
  src/Resources/Resources/help/Set-AzResource.md
Labels: Waiting for CI :shipit:

#13102 Fix a output of HostedSubnet under virtual router
  src/Network/Network/Generated/Models/PSHubIpConfiguration.cs
  src/Network/Network/Generated/Models/PSVirtualRouter.cs
  src/Network/Network/Network.format.ps1xml
Labels: needs-review

#13148 update url in backup storage redundancy warnings
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
Labels: needs-review

#13106 [Storage] Support share Accesstier
  src/Storage/Storage.Management.Test/ScenarioTests/StorageFileTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageFileTests/TestStorageFileShare.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/File/NewAzureStorageShare.cs
  src/Storage/Storage.Management/File/UpdateAzureStorageShare.cs
  src/Storage/Storage.Management/help/New-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Update-AzRmStorageShare.md
Labels: needs-review

#13137 add links to referenced cmdlets
  src/Monitor/Monitor/help/Add-AzMetricAlertRuleV2.md
Labels: Waiting for CI :shipit:, customer-reported

#13132 Az Migrate Module Bug Fixes
  src/Migrate/custom/Get-AzMigrateDiscoveredServer.ps1
  src/Migrate/custom/Get-AzMigrateServer.ps1
  src/Migrate/custom/Get-AzMigrateServerReplication.ps1
  src/Migrate/custom/New-AzMigrateNicMapping.ps1
  src/Migrate/custom/New-AzMigrateProject.ps1
  src/Migrate/custom/New-AzMigrateServerReplication.ps1
  src/Migrate/custom/Set-AzMigrateServerReplication.ps1
  src/Migrate/docs/Az.Migrate.md
  src/Migrate/docs/Get-AzMigrateDiscoveredServer.md
  src/Migrate/docs/Get-AzMigrateMachine.md
  src/Migrate/docs/Get-AzMigrateProject.md
  src/Migrate/docs/Get-AzMigrateRunAsAccount.md
  src/Migrate/docs/Get-AzMigrateServer.md
  src/Migrate/docs/Get-AzMigrateServerReplication.md
  src/Migrate/docs/Get-AzMigrateSite.md
  src/Migrate/docs/Get-AzMigrateSolution.md
  src/Migrate/docs/New-AzMigrateNicMapping.md
  src/Migrate/docs/New-AzMigrateProject.md
  src/Migrate/docs/New-AzMigrateServerReplication.md
  src/Migrate/docs/Register-AzMigrateProjectTool.md
  src/Migrate/docs/Remove-AzMigrateProject.md
  src/Migrate/docs/Set-AzMigrateServerReplication.md
  src/Migrate/examples/Get-AzMigrateDiscoveredServer.md
  src/Migrate/examples/Get-AzMigrateMachine.md
  src/Migrate/examples/Get-AzMigrateProject.md
  src/Migrate/examples/Get-AzMigrateRunAsAccount.md
  src/Migrate/examples/Get-AzMigrateServer.md
  src/Migrate/examples/Get-AzMigrateSite.md
  src/Migrate/examples/Get-AzMigrateSolution.md
  src/Migrate/examples/New-AzMigrateNicMapping.md
  src/Migrate/examples/New-AzMigrateProject.md
  src/Migrate/examples/New-AzMigrateServerReplication.md
  src/Migrate/examples/Register-AzMigrateProjectTool.md
  src/Migrate/examples/Remove-AzMigrateProject.md
  src/Migrate/readme.md
  src/Migrate/test/Get-AzMigrateDiscoveredServer.Tests.ps1
  src/Migrate/test/Get-AzMigrateMachine.Recording.json
  src/Migrate/test/Get-AzMigrateMachine.Tests.ps1
  src/Migrate/test/Get-AzMigrateServerReplication.Tests.ps1
  src/Migrate/test/New-AzMigrateNicMapping.Tests.ps1
  src/Migrate/test/New-AzMigrateProject.Recording.json
  src/Migrate/test/New-AzMigrateProject.Tests.ps1
  src/Migrate/test/New-AzMigrateServerReplication.Tests.ps1
  src/Migrate/test/utils.ps1
Labels: needs-review

#13153 [Resources] Remove preview note from template deployment What-If results
  src/Resources/ResourceManager/Formatters/WhatIfOperationResultFormatter.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentCreateCmdlet.cs
  src/Resources/ResourceManager/Properties/Resources.Designer.cs
  src/Resources/ResourceManager/Properties/Resources.resx
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#13150 Update Set-AzApplicationGateway.md
  src/Network/Network/help/Set-AzApplicationGateway.md
Labels: Doc - Reference, Waiting for CI :shipit:, customer-reported

#13128 Update SDK for Cognitive Services PowerShell
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/CognitiveServices/CognitiveServices/CognitiveServices.csproj
Labels: needs-review

#13182 [SpringCloud ] Updated API version
  src/SpringCloud/custom/New-AzSpringCloudAppDeployment.ps1
  src/SpringCloud/custom/Update-AzSpringCloudAppDeployment.ps1
  src/SpringCloud/docs/Deploy-AzSpringCloudApp.md
  src/SpringCloud/docs/Get-AzSpringCloud.md
  src/SpringCloud/docs/Get-AzSpringCloudApp.md
  src/SpringCloud/docs/Get-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/New-AzSpringCloud.md
  src/SpringCloud/docs/New-AzSpringCloudApp.md
  src/SpringCloud/docs/New-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/Remove-AzSpringCloudApp.md
  src/SpringCloud/docs/Remove-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/Update-AzSpringCloud.md
  src/SpringCloud/docs/Update-AzSpringCloudApp.md
  src/SpringCloud/docs/Update-AzSpringCloudAppDeployment.md
  src/SpringCloud/readme.md
  src/SpringCloud/test/Az.SpringCloud-TestResults.xml
  src/SpringCloud/test/Get-AzSpringCloud.Recording.json
  src/SpringCloud/test/Get-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/Get-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/New-AzSpringCloud.Recording.json
  src/SpringCloud/test/New-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/New-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/New-AzSpringCloudAppDeployment.Tests.ps1
  src/SpringCloud/test/Remove-AzSpringCloud.Recording.json
  src/SpringCloud/test/Remove-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/Remove-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Restart-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Start-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Stop-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Update-AzSpringCloud.Recording.json
  src/SpringCloud/test/Update-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/Update-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/env.json
  src/SpringCloud/test/utils.ps1
Labels: SpringCloud

#13119 [Storage] Support new permission in container access policy
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerAcl.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Common/AccessPolicyHelper.cs
  src/Storage/Storage/Common/AzureStorageContainer.cs
  src/Storage/Storage/Common/BlobQueryTextConfiguration.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
  src/Storage/Storage/Storage.csproj
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: needs-review

#13184 [SpringCloud ] Updated API version
  src/SpringCloud/custom/Deploy-AzSpringCloudApp.ps1
  src/SpringCloud/custom/Get-AzSpringCloud.ps1
  src/SpringCloud/custom/New-AzSpringCloud.ps1
  src/SpringCloud/custom/New-AzSpringCloudApp.ps1
  src/SpringCloud/custom/New-AzSpringCloudAppDeployment.ps1
  src/SpringCloud/custom/Update-AzSpringCloud.ps1
  src/SpringCloud/custom/Update-AzSpringCloudApp.ps1
  src/SpringCloud/custom/Update-AzSpringCloudAppDeployment.ps1
  src/SpringCloud/docs/Deploy-AzSpringCloudApp.md
  src/SpringCloud/docs/Get-AzSpringCloud.md
  src/SpringCloud/docs/Get-AzSpringCloudApp.md
  src/SpringCloud/docs/Get-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/New-AzSpringCloud.md
  src/SpringCloud/docs/New-AzSpringCloudApp.md
  src/SpringCloud/docs/New-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/Remove-AzSpringCloudApp.md
  src/SpringCloud/docs/Remove-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/Update-AzSpringCloud.md
  src/SpringCloud/docs/Update-AzSpringCloudApp.md
  src/SpringCloud/docs/Update-AzSpringCloudAppDeployment.md
  src/SpringCloud/readme.md
  src/SpringCloud/resources/appplatform.json
  src/SpringCloud/resources/readme.md
  src/SpringCloud/test/Az.SpringCloud-TestResults.xml
  src/SpringCloud/test/Get-AzSpringCloud.Recording.json
  src/SpringCloud/test/Get-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/Get-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/New-AzSpringCloud.Recording.json
  src/SpringCloud/test/New-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/New-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/New-AzSpringCloudAppDeployment.Tests.ps1
  src/SpringCloud/test/Remove-AzSpringCloud.Recording.json
  src/SpringCloud/test/Remove-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/Remove-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Restart-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Start-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Stop-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/Update-AzSpringCloud.Recording.json
  src/SpringCloud/test/Update-AzSpringCloudApp.Recording.json
  src/SpringCloud/test/Update-AzSpringCloudAppDeployment.Recording.json
  src/SpringCloud/test/env.json
  src/SpringCloud/test/utils.ps1
Labels: SpringCloud, needs-review

#13172 Fixes #1587 - Added connection string example
  src/Websites/Websites/help/Set-AzWebApp.md
Labels: needs-review

#13195 fixing breaking test for get-Azresource
  src/Peering/Peering.Test/ScenarioTests/RegisteredAsn.ps1
  src/Peering/Peering.Test/ScenarioTests/RegisteredPrefix.ps1
  src/Peering/Peering.Test/SessionRecords/Microsoft.Azure.Commands.Peering.Test.ScenarioTests.RegisteredAsn/TestCreateRegisteredAsn.json
  src/Peering/Peering.Test/SessionRecords/Microsoft.Azure.Commands.Peering.Test.ScenarioTests.RegisteredAsn/TestGetRegisteredAsn.json
  src/Peering/Peering.Test/SessionRecords/Microsoft.Azure.Commands.Peering.Test.ScenarioTests.RegisteredPrefix/TestCreateRegisteredPrefix.json
  src/Peering/Peering.Test/SessionRecords/Microsoft.Azure.Commands.Peering.Test.ScenarioTests.RegisteredPrefix/TestGetRegisteredPrefix.json
  src/Peering/Peering/ChangeLog.md
Labels: needs-review

#13176 corrected the variable name from $vnet to $subnet (under heading Retrieving all subnet delegations)
  src/Network/Network/help/Get-AzDelegation.md
Labels: customer-reported, needs-review

#13196 Add Get-AzVirtualRouterPeerAdvertisedRoute and Get-AzVirtualRouterPee…
  src/Network/Network.Test/ScenarioTests/VirtualRouterTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualRouterTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualRouterTests/TestVirtualRouterPeerRoutes.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Generated/Models/PSPeerRoute.cs
  src/Network/Network/VirtualRouterPeer/GetAzVirtualRouterPeerAdvertisedRouteCommand.cs
  src/Network/Network/VirtualRouterPeer/GetAzVirtualRouterPeerLearnedRouteCommand.cs
  src/Network/Network/help/Get-AzVirtualRouterPeerAdvertisedRoute.md
  src/Network/Network/help/Get-AzVirtualRouterPeerLearnedRoute.md
Labels: Waiting for CI :shipit:, needs-review

#13189 Add links to PowerShell cmdlets referenced in the document
  src/Monitor/Monitor/help/Add-AzAutoscaleSetting.md
Labels: customer-reported, needs-review

#13190 Add links to PowerShell cmdlets referenced in the document
  src/Monitor/Monitor/help/New-AzActivityLogAlertCondition.md
Labels: customer-reported, needs-review

#13199 Deprecate Sku and add SkuName and SkuTier parameters for Firewall command
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallVirtualHubMultiPublicIPCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallWithDNSProxy.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/New-AzFirewall.md
Labels: needs-review

#13169 [Backup] fixing workload restore for limited roles
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/GetAzureRmRecoveryServicesBackupWorkloadRecoveryConfig.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#12856 Remove SecretValueText to avoid displaying secretvalue in plain text
  src/KeyVault/KeyVault.Test/Scripts/VaultCertificateTests.ps1
  src/KeyVault/KeyVault.Test/Scripts/VaultManagedStorageAccountTests.ps1
  src/KeyVault/KeyVault.Test/Scripts/VaultSecretTests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/GetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/RestoreAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/UndoAzureKeyVaultSecretRemoval.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Models/PSDeletedKeyVaultSecret.cs
  src/KeyVault/KeyVault/Models/PSKeyVaultSecret.cs
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificate.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultSecret.md
  tools/DeleteModules.ps1
  tools/InstallationTests/AutoTestLogin.ps1
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: Breaking Change Release, Do Not Merge :no_entry_sign:

#13185 Fix a output of HostedSubnet under virtual router (#13102)
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/Models/PSHubIpConfiguration.cs
  src/Network/Network/Generated/Models/PSVirtualRouter.cs
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#13197 [Databricks] Fixed bug that withouth -EncryptionKeyVersion will keep last key version.
  src/Databricks/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/test/Get-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Get-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/New-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/New-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Remove-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Remove-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/deployment-templates/key-vault/parameters.json
  src/Databricks/test/deployment-templates/security-network-group/parameters.json
  src/Databricks/test/deployment-templates/virtual-network/parameters.json
  src/Databricks/test/env.json
  src/Databricks/test/utils.ps1
Labels: Databricks, needs-review

#13214 [Databricks]Update databricks workspace withouth -EncryptionKeyVersion that the key version will be empty.(#13173)
  src/Databricks/Az.Databricks.psd1
  src/Databricks/ChangeLog.md
  src/Databricks/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/test/Az.Databricks-TestResults.xml
  src/Databricks/test/Get-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Get-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/New-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/New-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Remove-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Remove-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/test/deployment-templates/key-vault/parameters.json
  src/Databricks/test/deployment-templates/security-network-group/parameters.json
  src/Databricks/test/deployment-templates/virtual-network/parameters.json
  src/Databricks/test/env.json
  src/Databricks/test/utils.ps1
Labels: Databricks, needs-review

#13218 New-AzDiskUpdateConfig added parameters Tier, diskIOPSReadOnly, and diskMBpsReadOnly
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskConfigTierSectorSizeReadOnly.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/Generated/Models/PSDiskUpdate.cs
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
Labels: needs-review

#13201 [Storage] Fixed a sample script issue of set management policy with json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSDataPolicy.cs
  src/Storage/Storage.Management/help/Set-AzStorageAccountManagementPolicy.md
Labels: needs-review

#13187 Detach managed hsm from key vault command
  src/KeyVault/KeyVault.Test/ScenarioTests/ManagedHsmManagementTests.ps1
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/Commands/GetAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/GetAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/NewAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/UndoAzureKeyVaultRemoval.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureManagedHsm.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/KeyVaultManagementCmdletBase.cs
  src/KeyVault/KeyVault/Models/PSManagedHsm.cs
  src/KeyVault/KeyVault/Models/VaultCreationOrUpdateParameters.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/help/Get-AzKeyVault.md
  src/KeyVault/KeyVault/help/Get-AzManagedHsm.md
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/New-AzManagedHsm.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVault.md
  src/KeyVault/KeyVault/help/Remove-AzManagedHsm.md
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
  src/KeyVault/KeyVault/help/Update-AzManagedHsm.md
Labels: needs-review

#13222 [Resources] Fixed an issue where deployment cmdlets does not preserve case of parameters
  src/Resources/ResourceManager/Json/PSJsonSerializer.cs
  src/Resources/Resources.Test/Json/PSJsonSerializerTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#13139 Added an example to New-AzVirtualHubVnetConnection and New-AzVHubRoute
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/New-AzVHubRoute.md
  src/Network/Network/help/New-AzVirtualHubVnetConnection.md
Labels: Doc - Reference, Waiting for CI :shipit:

#13188 [Storage] support set/update/remove acl recursive on DatalakeGen2 item
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Remove-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage.Management/help/Set-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage.Management/help/Update-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage/Common/AzureDataLakeGen2Item.cs
  src/Storage/Storage/Common/AzureStorageBlob.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/DataLakeGen2ACLRecursiveBaseCmdlet.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RemoveAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/SetAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2Item.cs
  src/Storage/Storage/Model/ResourceModel/PSACLRecursiveChangeResult.cs
  src/Storage/Storage/Model/ResourceModel/PSPathAccessControl.cs
Labels: needs-review

#13142 fix parsing bug
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
Labels: Waiting for CI :shipit:

#12562 Edit Get & Set ShortTermRetentionPolicy For Adding New Parameter: DiffBackupIntervalInHours
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestShortTermRetentionPolicy.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/GetAzureSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Cmdlet/SetAzureSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseBackupShortTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/Get-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  src/Sql/Sql/help/Set-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  tools/StaticAnalysis/Exceptions/Az.Sql/BreakingChangeIssues.csv
Labels: Breaking Change Release, Waiting for CI :shipit:

#13220 Update PSAzureActiveDirectoryApp so that TenantId can be updated
  src/DataMigration/DataMigration/Models/PSAzureActiveDirectoryApp.cs
Labels: needs-review

#13118 [Storage] Add breaking change type
  src/Storage/Storage.Management/Blob/DisableAzureStorageBlobRestorePolicy.cs
  src/Storage/Storage.Management/Blob/EnableAzureStorageBlobRestorePolicy.cs
  src/Storage/Storage.Management/Blob/GetAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/Blob/UpdateAzureStorageBlobServiceProperties.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSBlobServiceProperties.cs
  src/Storage/Storage.Management/Models/PSDataPolicy.cs
  src/Storage/Storage.Management/StorageAccount/AddAzureStorageAccountManagementPolicyAction.cs
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageAccountManagementPolicy.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccountManagementPolicyRule.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccountManagementPolicy.cs
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Breaking Change Release, Waiting for CI :shipit:

#13205 Add links to PowerShell cmdlets referenced in the document
  src/Monitor/Monitor/help/Update-AzScheduledQueryRule.md
Labels: customer-reported, needs-review

#13217 Fix a simple typo of New-AzOffice365PolicyProperty.md
  src/Network/Network/help/New-AzOffice365PolicyProperty.md
Labels: customer-reported, needs-review

#13203 Add links to PowerShell cmdlets referenced in the document
  src/Monitor/Monitor/help/New-AzMetricAlertRuleV2Criteria.md
Labels: customer-reported, needs-review

#13204 Add links to PowerShell cmdlets referenced in the document
  src/Monitor/Monitor/help/New-AzMetricAlertRuleV2DimensionSelection.md
Labels: customer-reported, needs-review

#13219 Clarified sync/async behavior
  src/Sql/Sql/help/Switch-AzSqlDatabaseFailoverGroup.md
Labels: needs-review

#13212 new cmdlet Get-AzDiskEncryptionSetAssociatedResource
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.cs
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestGetDiskEncryptionSetAssociatedResource.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/GetAzDiskEncryptionSetAssociatedResourceCommand.cs
  src/Compute/Compute/help/Get-AzDiskEncryptionSetAssociatedResource.md
Labels: needs-review

#12105 Managed services cmdlet changes
  src/ManagedServices/ManagedServices.Test/ScenarioTests/ManagedServicesTests.ps1
  src/ManagedServices/ManagedServices.Test/ScenarioTests/TestController.cs
  src/ManagedServices/ManagedServices.Test/SessionRecords/Microsoft.Azure.PowerShell.Cmdlets.ManagedServices.Test.ScenarioTests.ManagedServicesTests/ManagedServices_CRUD.json
  src/ManagedServices/ManagedServices/ChangeLog.md
  src/ManagedServices/ManagedServices/Commands/GetAzureRmManagedServicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/GetAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Commands/NewAzureRmManagedServicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/NewAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Commands/RemoveAzureRmManagedServcicesAssignment.cs
  src/ManagedServices/ManagedServices/Commands/RemoveAzureRmManagedServicesDefinition.cs
  src/ManagedServices/ManagedServices/Extensions/ManagedServicesExtensions.cs
  src/ManagedServices/ManagedServices/Extensions/ManagedServicesUtility.cs
  src/ManagedServices/ManagedServices/Microsoft.Azure.PowerShell.Cmdlets.ManagedServices.generated.format.ps1xml
  src/ManagedServices/ManagedServices/Models/ManagedServicesClientWrapper.cs
  src/ManagedServices/ManagedServices/Models/ManagedServicesCmdletBase.cs
  src/ManagedServices/ManagedServices/Models/PSRegistrationAssignment.cs
  src/ManagedServices/ManagedServices/Models/PSRegistrationAssignmentProperties.cs
  src/ManagedServices/ManagedServices/Models/PSRegistrationAssignmentPropertiesRegistrationDefinition.cs
  src/ManagedServices/ManagedServices/Models/PSRegistrationAssignmentPropertiesRegistrationDefinitionProperties.cs
  src/ManagedServices/ManagedServices/Models/PSRegistrationDefinition.cs
  src/ManagedServices/ManagedServices/Models/PSRegistrationDefinitionProperties.cs
  src/ManagedServices/ManagedServices/help/Az.ManagedServices.md
  src/ManagedServices/ManagedServices/help/Get-AzManagedServicesAssignment.md
  src/ManagedServices/ManagedServices/help/Get-AzManagedServicesDefinition.md
  src/ManagedServices/ManagedServices/help/New-AzManagedServicesAssignment.md
  src/ManagedServices/ManagedServices/help/New-AzManagedServicesDefinition.md
  src/ManagedServices/ManagedServices/help/Remove-AzManagedServicesAssignment.md
  src/ManagedServices/ManagedServices/help/Remove-AzManagedServicesDefinition.md
  tools/StaticAnalysis/Exceptions/Az.ManagedServices/BreakingChangeIssues.csv
Labels: Breaking Change Release, needs-revision

#13232 New-AzDiskUpdateConfig new parameter MaxSharesCount
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskConfigTierSectorSizeReadOnly.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
Labels: needs-review

#13224 Deprecate DisableSoftDelete in New-AzKeyVault & EnableSoftDelete in Update-AzKeyVault
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestUpdateVault.json
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultCertificate.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultKey.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review

#13235 DiskRP PS support for DiskRP version 2020-06-30.
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.cs
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskConfigTierSectorSizeReadOnly.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestGetDiskEncryptionSetAssociatedResource.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/Generated/Disk/GetAzDiskEncryptionSetAssociatedResourceCommand.cs
  src/Compute/Compute/Generated/Models/PSDisk.cs
  src/Compute/Compute/Generated/Models/PSDiskUpdate.cs
  src/Compute/Compute/help/Get-AzDiskEncryptionSetAssociatedResource.md
  src/Compute/Compute/help/New-AzDiskConfig.md
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-review

#13236 Fix Az.Tools.Installer issues
  tools/Az.Tools.Installer/exports/Install-AzModule.ps1
  tools/Az.Tools.Installer/internal/Get-AzModuleUpdateList.ps1
Labels: needs-review

#13223 databricks 1.0.1 oob release
  src/Databricks/Az.Databricks.psd1
  src/Databricks/ChangeLog.md
  src/Databricks/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
Labels: needs-review

#13234 Add the missing file.
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Profile/AzurePSDataCollectionProfile.cs
Labels: needs-review

#13250 Revert "Edit Get & Set ShortTermRetentionPolicy For Adding New Parameter: DiffBackupIntervalInHours"
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestShortTermRetentionPolicy.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/GetAzureRmSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Cmdlet/SetAzureRmSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseBackupShortTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/Get-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  src/Sql/Sql/help/Set-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  tools/StaticAnalysis/Exceptions/Az.Sql/BreakingChangeIssues.csv
Labels: needs-review

#13251 Fix for issue 13097
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ImportExport/Service/ImportExportDatabaseAdapter.cs
  src/Sql/Sql/ImportExport/Service/ImportExportDatabaseCommunicator.cs
Labels: needs-review

#13215 [RecoveryServices.Backup] Breaking changes in Restore Backup item cmdlet
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Models/RecoveryServices.Backup.Models.csproj
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: Breaking Change Release, needs-review

#13254 Remove Get-AzProfile and Select-AzProfile
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/GetAzProfile.cs
  src/Accounts/Accounts/CommonModule/SelectAzProfile.cs
  src/Accounts/Accounts/help/Get-AzProfile.md
  src/Accounts/Accounts/help/Select-AzProfile.md
  tools/StaticAnalysis/Exceptions/Az.Accounts/BreakingChangeIssues.csv
Labels: Breaking Change Release, needs-review

#13255 [Az.Functions] Implement Functions' Stacks API which describes what runtimes and runtime versions are available for function app creation + bug fixes
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
  src/Functions/custom/FunctionsStack/WindowsFunctionsStacks.json
  src/Functions/custom/Get-AzFunctionApp.ps1
  src/Functions/custom/HelperFunctions.ps1
  src/Functions/custom/New-AzFunctionApp.ps1
  src/Functions/docs/Get-AzFunctionApp.md
  src/Functions/test/Get-AzFunctionApp.Recording.json
  src/Functions/test/Get-AzFunctionAppAvailableLocation.Recording.json
  src/Functions/test/Get-AzFunctionAppPlan.Recording.json
  src/Functions/test/Get-Update-Remove-AzFunctionAppSetting.Recording.json
  src/Functions/test/New-AzFunctionApp.Recording.json
  src/Functions/test/New-AzFunctionApp.Tests.ps1
  src/Functions/test/New-AzFunctionAppPlan.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.ps1
  src/Functions/test/New-Update-Remove-AzFunctionAppPlan.Recording.json
  src/Functions/test/Restart-Start-Stop-AzFunctionApp.Recording.json
  src/Functions/test/env.json
  src/Functions/test/utils.ps1
Labels: needs-review

#13239 [Datafactory] fix cmdlet New-AzDataFactoryV2LinkedServiceEncryptedCredential
  src/DataFactory/DataFactories.Test/DataFactories.Test.csproj
  src/DataFactory/DataFactories/DataFactories.csproj
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-revision

#13242 Limit KeyType to be required only when create managed HSM key
  src/KeyVault/KeyVault.Test/PesterTests/ManagedHsmDatePlaneTests.Tests.ps1
  src/KeyVault/KeyVault.Test/PesterTests/ManagedHsmDatePlaneTests.ps1
  src/KeyVault/KeyVault.Test/Resources/testImportKey.pfx
  src/KeyVault/KeyVault.Test/ScenarioTests/PesterTests/ManagedHsmDatePlaneTests.Tests.ps1
  src/KeyVault/KeyVault.Test/ScenarioTests/PesterTests/ManagedHsmDatePlaneTests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/AddAzureManagedHsmKey.cs
  src/KeyVault/KeyVault/help/Add-AzManagedHsmKey.md
Labels: needs-review

#13249 Get the App Roles assigned correctly in case of Stack HCI registration using WAC token.
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
  src/StackHCI/Properties/AssemblyInfo.cs
Labels: customer-reported, needs-review

#13226 Security domain
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/KeyVault/KeyVault.Test/UnitTests/SecurityDomainTests.cs
  src/KeyVault/KeyVault.sln
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/Helpers/UtilityExtensions.cs
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/Models/DataServiceCredential.cs
  src/KeyVault/KeyVault/Properties/AssemblyInfo.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/BackupSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/RestoreSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/SecurityDomainCmdlet.cs
  src/KeyVault/KeyVault/SecurityDomain/Common/Constants.cs
  src/KeyVault/KeyVault/SecurityDomain/Common/IOStreamExtensions.cs
  src/KeyVault/KeyVault/SecurityDomain/Common/Utils.cs
  src/KeyVault/KeyVault/SecurityDomain/Crypto/mod_math.cs
  src/KeyVault/KeyVault/SecurityDomain/Crypto/shared_secret.cs
  src/KeyVault/KeyVault/SecurityDomain/Crypto/test/test.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/CertKey.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/CertKeys.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/DownloadRequest.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/ISecurityDomainClient.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/JWE.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/JWK.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/KDF.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/KeyPath.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomainClient.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomainRestoreData.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomainTransferKey.cs
  src/KeyVault/KeyVault/Track2Models/Track2VaultClient.cs
  src/KeyVault/KeyVault/help/Az.KeyVault.md
  src/KeyVault/KeyVault/help/Backup-AzManagedHsmSecurityDomain.md
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/Restore-AzManagedHsmSecurityDomain.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.KeyVault/SignatureIssues.csv
Labels: needs-review

#13252 [Aks]Promised breaking changes
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.ps1
  src/Aks/Aks.Test/ScenarioTests/NodePoolTests.ps1
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/Aks/Aks/Commands/GetAzureRmAks.cs
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Commands/NewKubeBase.cs
  src/Aks/Aks/Commands/RemoveAzureRmAks.cs
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  src/Aks/Aks/help/New-AzAksCluster.md
  src/Aks/Aks/help/Set-AzAksCluster.md
  tools/StaticAnalysis/Exceptions/Az.Aks/BreakingChangeIssues.csv
Labels: needs-review

#13140 update changelog
  src/DesktopVirtualization/ChangeLog.md
Labels: More Info :label:, needs-review

#13258 Polish changelog for upcoming release
  src/Accounts/Accounts/ChangeLog.md
  src/KeyVault/KeyVault/ChangeLog.md
  src/ManagedServices/ManagedServices/ChangeLog.md
  src/Network/Network/ChangeLog.md
  src/Resources/Resources/ChangeLog.md
  tools/Az/Az.psd1
Labels: Waiting for CI :shipit:

#13092 Update azure-powershell-developer-guide.md
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: Doc - Internal, needs-review

#12866 Update synopsis for Get-AzReservationQuote
  src/Reservations/Reservations/help/Az.Reservations.md
  src/Reservations/Reservations/help/Get-AzReservationQuote.md
Labels: Doc - Reference, Waiting for CI :shipit:

#13282 Fix postgresql psd1 file
  src/PostgreSql/Az.PostgreSql.psd1
Labels: needs-review

#13114 [DataFactory] Add 2 New commands to ADF V2
  src/DataFactory/DataFactoryV2.Test/Resources/pipelineWait.json
  src/DataFactory/DataFactoryV2.Test/Resources/tumblingTriggerWithPipeline.json
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/TriggerTests.cs
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/TriggerTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.TriggerTests/TestInvokeAndStopTriggerRun.json
  src/DataFactory/DataFactoryV2/Az.DataFactory.psd1
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.Trigger.cs
  src/DataFactory/DataFactoryV2/Runs/InvokeAzureDataFactoryTriggerRunCommand.cs
  src/DataFactory/DataFactoryV2/Runs/StopAzureDataFactoryTriggerRunCommand.cs
  src/DataFactory/DataFactoryV2/help/Invoke-AzDataFactoryV2TriggerRun.md
  src/DataFactory/DataFactoryV2/help/Stop-AzDataFactoryV2TriggerRun.md
Labels: Cmdlet Review Complete, Waiting for CI :shipit:, needs-revision

#13273 fix typo in changelog and false required assemblies in az.containerregistry.psd1
  src/ContainerRegistry/ContainerRegistry/Az.ContainerRegistry.psd1
  src/ContainerRegistry/ContainerRegistry/ChangeLog.md
Labels: needs-review

#13279 [SpringCloud]Updated Changelog.md
  src/SpringCloud/Changelog.md
Labels: SpringCloud, needs-review

#13280 Replace Get-AzAksCluster with Get-AzAks
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: needs-review

#13289 Revert upgraded version of Az.Functions.
  src/Functions/Az.Functions.psd1
  src/Functions/ChangeLog.md
  tools/VersionController/MinimalVersion.csv
Labels: needs-review

#13208 Make "Connectionlink" argument mandatory in start-azVpnConnectionPacketCapture and Stop-AzVpnConnectionPacketCapture
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VpnConnection/StartAzVpnConnectionPacketCaptureCommand.cs
  src/Network/Network/Cortex/VpnConnection/StopAzVpnConnectionPacketCaptureCommand.cs
  src/Network/Network/help/Start-AzVpnConnectionPacketCapture.md
  src/Network/Network/help/Stop-AzVpnConnectionPacketCapture.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-revision

#13159 Corrected docs for Get-AzSecurityPricing & Set-AzSecurityPricing
  src/Security/Security/help/Az.Security.md
  src/Security/Security/help/Get-AzSecurityPricing.md
  src/Security/Security/help/Set-AzSecurityPricing.md
Labels: Doc - Reference, needs-review

#12948 Add suggestion for parameter of PrivateEndPoint cmdlet
  src/Network/Network/PrivateLinkService/PrivateEndpointConnection/GetAzurePrivateEndpointConnection.cs
  src/Network/Network/PrivateLinkService/PrivateEndpointConnection/PrivateEndpointConnectionBaseCmdlet.cs
  src/Network/Network/PrivateLinkService/PrivateLinkResource/GetAzurePrivateLinkResourceCommand.cs
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
  src/Network/Network/help/Get-AzPrivateEndpointConnection.md
  src/Network/Network/help/Get-AzPrivateLinkResource.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: Breaking Change Release, Do Not Merge :no_entry_sign:, needs-review

#13292 fix issue: fails to migrate ADAL token for MSA account
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Authentication/Authentication/TokenCache/AdalTokenMigrator.cs
  src/Accounts/Authentication/AzureSessionInitializer.cs
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
Labels: needs-review

#13303 Update changelog
  src/Functions/ChangeLog.md
Labels: needs-review

#13302 fix null reference and method case insensitive for `Invoke-AzRestMethod`
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
Labels: Waiting for CI :shipit:

#13308 Updated Connection monitor endpoint cmdlet
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSConnectionMonitorEndPoint.cs
  src/Network/Network/Models/PSConnectionMonitorEndpointScope.cs
  src/Network/Network/Models/PSConnectionMonitorEndpointScopeItem.cs
  src/Network/Network/Models/PSConnectionMonitorTcpConfiguration.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkWatcher/ConnectionMonitor/ConnectionMonitorBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndPointObjectCommand.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndpointScopeItemObject.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorProtocolConfigurationObjectCommand.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointScopeItemObject.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#13309 [AKs] Add the alias of AksCluster back.
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/GetAzureRmAks.cs
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Commands/RemoveAzureRmAks.cs
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  tools/StaticAnalysis/Exceptions/Az.Aks/BreakingChangeIssues.csv
Labels: needs-review

#13297 Aladdin generated examples for ServiceFabric
  src/ServiceFabric/ServiceFabric/help/Remove-AzServiceFabricNode.md
  src/ServiceFabric/ServiceFabric/help/Update-AzServiceFabricReliability.md
Labels: Waiting for CI :shipit:, customer-reported

#13296 Aladdin generated examples for DataLakeAnalytics
  src/DataLakeAnalytics/DataLakeAnalytics/help/Add-AzDataLakeAnalyticsDataSource.md
  src/DataLakeAnalytics/DataLakeAnalytics/help/Set-AzDataLakeAnalyticsAccount.md
Labels: Waiting for CI :shipit:, customer-reported

#13295 Aladdin generated examples for NotificationHubs
  src/NotificationHubs/NotificationHubs/help/Get-AzNotificationHub.md
  src/NotificationHubs/NotificationHubs/help/Set-AzNotificationHub.md
Labels: Waiting for CI :shipit:, customer-reported

#13307 Fix Error in Get-AzAutomationDscNode Example 1
  src/Automation/Automation/help/Get-AzAutomationDscNodeReport.md
Labels: Waiting for CI :shipit:

#13304 added supported TrafficAnalyticsInterval values in documentation for Set-AzNetworkWatcherConfigFlowLog
  src/Network/Network/help/Set-AzNetworkWatcherConfigFlowLog.md
Labels: Doc - Reference, Waiting for CI :shipit:, customer-reported

#13310 Update ADLS plane sdk
  src/DataLakeStore/DataLakeStore/ChangeLog.md
  src/DataLakeStore/DataLakeStore/DataLakeStore.csproj
Labels: Waiting for CI :shipit:

#13316 Add DigitalTwins Generated Code and Tests
  src/DigitalTwins/.gitattributes
  src/DigitalTwins/.gitignore
  src/DigitalTwins/Az.DigitalTwins.psd1
  src/DigitalTwins/custom/New-AzDigitalTwinsCheckNameRequestObject.ps1
  src/DigitalTwins/custom/New-AzDigitalTwinsDigitalTwinsIdentityObject.ps1
  src/DigitalTwins/custom/New-AzDigitalTwinsEndpoint.ps1
  src/DigitalTwins/custom/Test-AzDigitalTwinsInstanceNameAvailability.ps1
  src/DigitalTwins/custom/readme.md
  src/DigitalTwins/docs/Az.DigitalTwins.md
  src/DigitalTwins/docs/Get-AzDigitalTwinsEndpoint.md
  src/DigitalTwins/docs/Get-AzDigitalTwinsInstance.md
  src/DigitalTwins/docs/New-AzDigitalTwinsCheckNameRequestObject.md
  src/DigitalTwins/docs/New-AzDigitalTwinsDigitalTwinsIdentityObject.md
  src/DigitalTwins/docs/New-AzDigitalTwinsEndpoint.md
  src/DigitalTwins/docs/New-AzDigitalTwinsInstance.md
  src/DigitalTwins/docs/Remove-AzDigitalTwinsEndpoint.md
  src/DigitalTwins/docs/Remove-AzDigitalTwinsInstance.md
  src/DigitalTwins/docs/Test-AzDigitalTwinsInstanceNameAvailability.md
  src/DigitalTwins/docs/Update-AzDigitalTwinsInstance.md
  src/DigitalTwins/docs/readme.md
  src/DigitalTwins/examples/Get-AzDigitalTwinsEndpoint.md
  src/DigitalTwins/examples/Get-AzDigitalTwinsInstance.md
  src/DigitalTwins/examples/New-AzDigitalTwinsCheckNameRequestObject.md
  src/DigitalTwins/examples/New-AzDigitalTwinsDigitalTwinsIdentityObject.md
  src/DigitalTwins/examples/New-AzDigitalTwinsEndpoint.md
  src/DigitalTwins/examples/New-AzDigitalTwinsInstance.md
  src/DigitalTwins/examples/Remove-AzDigitalTwinsEndpoint.md
  src/DigitalTwins/examples/Remove-AzDigitalTwinsInstance.md
  src/DigitalTwins/examples/Test-AzDigitalTwinsInstanceNameAvailability.md
  src/DigitalTwins/examples/Update-AzDigitalTwinsInstance.md
  src/DigitalTwins/how-to.md
  src/DigitalTwins/license.txt
  src/DigitalTwins/readme.md
  src/DigitalTwins/resources/readme.md
  src/DigitalTwins/test/Get-AzDigitalTwinsEndpoint.Recording.json
  src/DigitalTwins/test/Get-AzDigitalTwinsEndpoint.Tests.ps1
  src/DigitalTwins/test/Get-AzDigitalTwinsInstance.Recording.json
  src/DigitalTwins/test/Get-AzDigitalTwinsInstance.Tests.ps1
  src/DigitalTwins/test/New-AzDigitalTwinsCheckNameRequestObject.Tests.ps1
  src/DigitalTwins/test/New-AzDigitalTwinsDigitalTwinsIdentityObject.Tests.ps1
  src/DigitalTwins/test/New-AzDigitalTwinsEndpoint.Recording.json
  src/DigitalTwins/test/New-AzDigitalTwinsEndpoint.Tests.ps1
  src/DigitalTwins/test/New-AzDigitalTwinsInstance.Recording.json
  src/DigitalTwins/test/New-AzDigitalTwinsInstance.Tests.ps1
  src/DigitalTwins/test/Remove-AzDigitalTwinsEndpoint.Recording.json
  src/DigitalTwins/test/Remove-AzDigitalTwinsEndpoint.Tests.ps1
  src/DigitalTwins/test/Remove-AzDigitalTwinsInstance.Recording.json
  src/DigitalTwins/test/Remove-AzDigitalTwinsInstance.Tests.ps1
  src/DigitalTwins/test/Test-AzDigitalTwinsInstanceNameAvailability.Recording.json
  src/DigitalTwins/test/Test-AzDigitalTwinsInstanceNameAvailability.Tests.ps1
  src/DigitalTwins/test/Update-AzDigitalTwinsInstance.Recording.json
  src/DigitalTwins/test/Update-AzDigitalTwinsInstance.Tests.ps1
  src/DigitalTwins/test/deployment-templates/eventgrid/parameters.json
  src/DigitalTwins/test/deployment-templates/eventgrid/template.json
  src/DigitalTwins/test/env.json
  src/DigitalTwins/test/loadEnv.ps1
  src/DigitalTwins/test/readme.md
  src/DigitalTwins/test/utils.ps1
  src/DigitalTwins/utils/Unprotect-SecureString.ps1
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-review

#13299 [Resources] Fix an issue where What-If shows two resource group scopes with different casing
  src/Resources/ResourceManager/Formatters/WhatIfOperationResultFormatter.cs
  src/Resources/Resources.Test/Formatters/WhatIfOperationResultFormatterTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#13326 Fix duplicate text
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterSet.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Settings.cs
Labels: needs-review

#13333 [ResourceGraph] Add new ResourceGraph.Autorest module.
  src/ResourceGraph/ResourceGraph.Autorest/.gitattributes
  src/ResourceGraph/ResourceGraph.Autorest/.gitignore
  src/ResourceGraph/ResourceGraph.Autorest/Az.ResourceGraph.psd1
  src/ResourceGraph/ResourceGraph.Autorest/custom/New-AzResourceGraphQuery.ps1
  src/ResourceGraph/ResourceGraph.Autorest/custom/Update-AzResourceGraphQuery.ps1
  src/ResourceGraph/ResourceGraph.Autorest/custom/readme.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/Az.ResourceGraph.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/Get-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/New-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/Remove-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/Update-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/docs/readme.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/Get-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/New-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/Remove-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/examples/Update-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph.Autorest/how-to.md
  src/ResourceGraph/ResourceGraph.Autorest/license.txt
  src/ResourceGraph/ResourceGraph.Autorest/readme.md
  src/ResourceGraph/ResourceGraph.Autorest/resources/readme.md
  src/ResourceGraph/ResourceGraph.Autorest/test/Get-AzResourceGraphQuery.Recording.json
  src/ResourceGraph/ResourceGraph.Autorest/test/Get-AzResourceGraphQuery.Tests.ps1
  src/ResourceGraph/ResourceGraph.Autorest/test/New-AzResourceGraphQuery.Recording.json
  src/ResourceGraph/ResourceGraph.Autorest/test/New-AzResourceGraphQuery.Tests.ps1
  src/ResourceGraph/ResourceGraph.Autorest/test/Query.kql
  src/ResourceGraph/ResourceGraph.Autorest/test/Remove-AzResourceGraphQuery.Recording.json
  src/ResourceGraph/ResourceGraph.Autorest/test/Remove-AzResourceGraphQuery.Tests.ps1
  src/ResourceGraph/ResourceGraph.Autorest/test/Update-AzResourceGraphQuery.Recording.json
  src/ResourceGraph/ResourceGraph.Autorest/test/Update-AzResourceGraphQuery.Tests.ps1
  src/ResourceGraph/ResourceGraph.Autorest/test/env.json
  src/ResourceGraph/ResourceGraph.Autorest/test/loadEnv.ps1
  src/ResourceGraph/ResourceGraph.Autorest/test/readme.md
  src/ResourceGraph/ResourceGraph.Autorest/test/utils.ps1
  src/ResourceGraph/ResourceGraph.Autorest/utils/Unprotect-SecureString.ps1
Labels: Resource Graph, needs-review

#13331 [Doc] Add migraion guide for az 5.0.
  documentation/migration-guides/Az.5.0.0-migration-guide.md
Labels: needs-review

#13336 Grammar and formatting updates
  documentation/migration-guides/Az.5.0.0-migration-guide.md
Labels: needs-review

#13329 Upload helper scripts to find ADE extension version
  src/Compute/Compute/Extension/AzureDiskEncryption/Scripts/Find_1passAdeVersion_VM.ps1
  src/Compute/Compute/Extension/AzureDiskEncryption/Scripts/Find_1passAdeVersion_VMSS.ps1
Labels: needs-review

#13317 Fix keyvault access token issue
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication.Test/AuthenticationFactoryTests.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
Labels: Waiting for CI :shipit:

#13341 Update Invoke-AzStorageSyncChangeDetection.md
  src/StorageSync/StorageSync/help/Invoke-AzStorageSyncChangeDetection.md
Labels: needs-review

#13314 [Storage] Fix BlobType description in help of Set-AzStorageBlobContent
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
Labels: Waiting for CI :shipit:

#13334 Tools to generate migration guide.
  tools/BreakingChanges/GenerateMigrationExcel.ps1
  tools/BreakingChanges/GenerateMigrationGuide.ps1
Labels: needs-review

#13343 Add culture info to version parsing
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
Labels: needs-review

#13323 [KeyVault] Enable key vault tag update
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestUpdateVault.json
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
Labels: needs-review

#13352 [IotHub] Allow tags in IoT Hub create cmdlet
  src/IotHub/IotHub.Test/ScenarioTests/IotHubTests.ps1
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubTests/TestAzureIotHubLifeCycle.json
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/IotHub/NewAzureRmIotHub.cs
  src/IotHub/IotHub/help/New-AzIotHub.md
Labels: needs-review

#13347 Update logic for generate-info.json
  tools/Gen2Master/MoveFromGeneration2Master.ps1
Labels: needs-review
