Repository Azure/azure-powershell, pull requests merged in 2020-02, with the labels that each got.

#10855 Added test cases for DiskEncryptionSet input for V2A and H2A
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/CMKInput/B2A.VaultCredentials
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2A/AsrV2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2A/AsrV2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2A/CMKInput/V2A.VaultCredentials
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/TestUpdateRPIWithDES.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ATests/V2ACreateRPIWithDES.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ATests/V2ACreateRPIWithDESEnabledDiskInput.json
Labels: needs-revision

#10900 PBI 6059593: Update AFS evaluation cmdlet character rules to latest
  src/StorageSync/StorageSync/ChangeLog.md
  src/StorageSync/StorageSync/Config.json
Labels: needs-review

#11019 fix typo
  ChangeLog.md
Labels: needs-review

#10892 Nemanjas/mi change hw generation
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstancePoolCrudTests/TestDeleteManagedInstanceInInstancePool.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstancePoolCrudTests/TestUpdateManagedInstanceInInstancePool.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestSetManagedInstance.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/help/Set-AzSqlInstance.md
Labels: needs-revision

#11013 Firewall Policy support on vnet firewall
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/help/New-AzFirewall.md
Labels: needs-review

#11024 Set null if parameter AvailableToOtherTenants is not set
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADApplicationCommand.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-revision

#11049 Fix Test-AzureVmWorkloadRestoreAsFiles in RecoveryService
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ItemTests.ps1
Labels: needs-review

#11001 Azs.Fabric.Admin module generation, metadata changes, customization and test
  src/StackAdmin/Azs.Fabric.Admin/custom/Get-AzsEdgeGateway.ps1
  src/StackAdmin/Azs.Fabric.Admin/custom/Get-AzsEdgeGatewayPool.ps1
  src/StackAdmin/Azs.Fabric.Admin/custom/Get-AzsInfrastructureRole.ps1
  src/StackAdmin/Azs.Fabric.Admin/docs/Get-AzsStoragePool.md
  src/StackAdmin/Azs.Fabric.Admin/docs/Get-AzsStorageSystem.md
  src/StackAdmin/Azs.Fabric.Admin/examples/Get-AzsDrive.md
  src/StackAdmin/Azs.Fabric.Admin/examples/Get-AzsInfrastructureShare.md
  src/StackAdmin/Azs.Fabric.Admin/examples/Get-AzsStorageSubSystem.md
  src/StackAdmin/Azs.Fabric.Admin/examples/Get-AzsVolume.md
  src/StackAdmin/Azs.Fabric.Admin/readme.md
  src/StackAdmin/Azs.Fabric.Admin/test/Common.ps1
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsEdgeGateway.Recording.json
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsEdgeGateway.Tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsEdgeGatewayPool.Recording.json
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsEdgeGatewayPool.Tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsIPPool.Recording.json
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsIPPool.Tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsInfrastructureLocation.Recording.json
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsInfrastructureLocation.Tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsInfrastructureRole.Recording.json
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsInfrastructureRole.Tests.ps1
  src/StackAdmin/Azs.Fabric.Admin/test/Get-AzsInfrastructureRoleInstance.Tests.ps1
Labels: needs-revision

#10959 Az.CognitiveServices - Update SDK to 7.0, Improve error message
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.cs
  src/CognitiveServices/CognitiveServices.Test/ScenarioTests/CognitiveServicesAccountTests.ps1
  src/CognitiveServices/CognitiveServices.Test/SessionRecords/CognitiveServices.Test.ScenarioTests.CognitiveServicesAccountTests/TestAsyncAccountOperations.json
  src/CognitiveServices/CognitiveServices/ChangeLog.md
  src/CognitiveServices/CognitiveServices/CognitiveServices.csproj
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/AddAzureCognitiveServicesAccountNetworkRule.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/CognitiveServicesAccountBaseCmdlet.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/GetAzureCognitiveServicesAccountNetworkRuleSet.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/RemoveAzureCognitiveServicesAccountNetworkRule.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/SetAzureCognitiveServicesAccount.cs
  src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/UpdateAzureCognitiveServicesAccountNetworkRuleSet.cs
  src/CognitiveServices/CognitiveServices/Models/PSCognitiveServicesAccount.cs
Labels: Waiting for CI :shipit:

#10828 Create docker image
  .github/ISSUE_TEMPLATE/az-module-bug-report.md
  Dockerfile
  build.proj
  docker/Dockerfile-centos-7
  docker/Dockerfile-debian-9
  docker/Dockerfile-ubuntu-18.04
  docker/README.md
  docker/config/AzureRmContextSettings.json
  tools/Docker/BuildImages.ps1
  tools/Docker/CleanArtifacts.ps1
  tools/Docker/GetArtifacts.ps1
  tools/RunVersionController.ps1
Labels: needs-review

#11121 Add system.buffers dependency to az.datalakestore
  src/DataLakeStore/DataLakeStore/Az.DataLakeStore.psd1
  src/DataLakeStore/DataLakeStore/ChangeLog.md
  src/DataLakeStore/DataLakeStore/DataLakeStore.csproj
Labels: needs-review

#11092 fix save and import context issue
  src/Accounts/Accounts/AutoSave/DisableAzureRmContextAutosave.cs
  src/Accounts/Accounts/Context/ImportAzureRMContext.cs
  src/Accounts/Authentication.ResourceManager/AzureRmProfile.cs
  src/Accounts/Authentication.ResourceManager/AzureRmProfileConverter.cs
  src/Accounts/Authentication/Authentication/Clients/AuthenticationClientFactory.cs
  src/Accounts/Authentication/Authentication/Clients/InMemoryTokenCacheClientFactory.cs
  src/Accounts/Authentication/Authentication/Clients/SharedTokenCacheClientFactory.cs
Labels: needs-review

#11138 Editions in the ChangeLog of CosmosDB
  src/CosmosDB/CosmosDB/ChangeLog.md
Labels: Waiting for CI :shipit:

#11152 solve the problem of build stack edge
  tools/CreateMappings_rules.json
  tools/GenerateHelp.ps1
Labels: Waiting for CI :shipit:

#11154 Fix no refresh token found issue during SSO
  src/Accounts/Authentication.ResourceManager/AzureRmProfile.cs
  src/Accounts/Authentication.ResourceManager/Properties/Resources.Designer.cs
  src/Accounts/Authentication.ResourceManager/Properties/Resources.resx
Labels: needs-review

#11155 Shows tags table in output for Get-AzResource
  src/Resources/ResourceManager/ResourceManager.format.ps1xml
  src/Resources/ResourceManager/SdkModels/Resources/PSResource.cs
  src/Resources/Resources/help/Get-AzResource.md
Labels: needs-revision

#11042 Adding support to set custom hostnames for WebAppSlots#10980
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetWebAppSlot.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestSetWebApp.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
Labels: needs-review

#11128 Update the resource group tag filter to use server side odata query
  src/Resources/ResourceManager/Implementation/ResourceGroups/GetAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/Resources.Test/Models.ResourceGroups/ResourceClientTests.cs
  src/Resources/Resources.Test/ScenarioTests/ResourceGroupTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests/TestFindResourceGroup.json
  src/Resources/Resources/ChangeLog.md
Labels: needs-revision

#11053 Add Survey Url to Send-Feedback & Resolve-Error
  src/Accounts/Accounts.Test/ErrorResolutionScenarioTests.cs
  src/Accounts/Accounts.Test/ErrorResolutionScenarioTests.ps1
  src/Accounts/Accounts.Test/ErrorResolutionTests.cs
  src/Accounts/Accounts.Test/SendFeedbackTests.cs
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.ErrorResolutionScenarioTests/WriteInformationInResolveError.json
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Common/AzureProfileConstants.cs
  src/Accounts/Accounts/Errors/ResolveError.cs
  src/Accounts/Accounts/Feedback/SendFeedback.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Authentication.ResourceManager/Models/PSAzureFeedback.cs
Labels: needs-review

#11184 Add typed objects for piping scenarios [breaking]
  src/Resources/ResourceManager/Entities/Policy/PolicyDefinitionProperties.cs
  src/Resources/ResourceManager/Entities/Policy/PolicySetDefinitionProperties.cs
  src/Resources/ResourceManager/Entities/Policy/PolicyType.cs
  src/Resources/ResourceManager/Extensions/JsonExtensions.cs
  src/Resources/ResourceManager/Implementation/Policy/GetAzurePolicyAssignment.cs
  src/Resources/ResourceManager/Implementation/Policy/GetAzurePolicyDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/GetAzurePolicySetDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/NewAzurePolicyAssignment.cs
  src/Resources/ResourceManager/Implementation/Policy/NewAzurePolicyDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/NewAzurePolicySetDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/PolicyCmdletBase.cs
  src/Resources/ResourceManager/Implementation/Policy/PolicyHelpStrings.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyAssignment.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyAssignmentEnforcementMode.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyAssignmentProperties.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyDefinitionProperties.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicySetDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicySetDefinitionProperties.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyType.cs
  src/Resources/ResourceManager/Implementation/Policy/RemoveAzurePolicyAssignment.cs
  src/Resources/ResourceManager/Implementation/Policy/RemoveAzurePolicyDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/RemoveAzurePolicySetDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/SetAzurePolicyAssignment.cs
  src/Resources/ResourceManager/Implementation/Policy/SetAzurePolicyDefinition.cs
  src/Resources/ResourceManager/Implementation/Policy/SetAzurePolicySetDefinition.cs
  src/Resources/Resources.Test/ScenarioTests/PolicyTests.cs
  src/Resources/Resources.Test/ScenarioTests/PolicyTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.PolicyTests/TestPolicyObjectPiping.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzPolicyAssignment.md
  src/Resources/Resources/help/Remove-AzPolicyAssignment.md
  src/Resources/Resources/help/Remove-AzPolicyDefinition.md
  src/Resources/Resources/help/Remove-AzPolicySetDefinition.md
  src/Resources/Resources/help/Set-AzPolicyAssignment.md
  src/Resources/Resources/help/Set-AzPolicyDefinition.md
  src/Resources/Resources/help/Set-AzPolicySetDefinition.md
  tools/StaticAnalysis/Exceptions/Az.Resources/BreakingChangeIssues.csv
Labels: needs-review

#11137 Cmdlet changes for 2019-10-01 Tags API for resources and subscriptions
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/TagTests.cs
  src/Resources/Resources.Test/ScenarioTests/TagTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagCreateOrUpdateWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagCreateOrUpdateWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagDeleteWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagDeleteWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagGetWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagGetWithResourceIdParamsForSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagUpdateWithResourceIdParamsForResource.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TagTests/TagUpdateWithResourceIdParamsForSubscription.json
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Az.Resources.md
  src/Resources/Resources/help/Get-AzTag.md
  src/Resources/Resources/help/New-AzTag.md
  src/Resources/Resources/help/Remove-AzTag.md
  src/Resources/Resources/help/Update-AzTag.md
  src/Resources/Tags/Client/TagBaseCmdlet.cs
  src/Resources/Tags/Client/TagsClient.cs
  src/Resources/Tags/Model/PSTagResource.cs
  src/Resources/Tags/Model/PSTagsObject.cs
  src/Resources/Tags/Model/TagPatchOperation.cs
  src/Resources/Tags/Model/TagsExtensions.cs
  src/Resources/Tags/Properties/Resources.Designer.cs
  src/Resources/Tags/Properties/Resources.resx
  src/Resources/Tags/Tag/GetAzureTagCommand.cs
  src/Resources/Tags/Tag/NewAzureTagCommand.cs
  src/Resources/Tags/Tag/RemoveAzureTagCommand.cs
  src/Resources/Tags/Tag/UpdateAzureTagCommand.cs
  src/Resources/Tags/Tags.csproj
  src/Resources/Tags/Tags.format.ps1xml
  tools/Common.Netcore.Dependencies.Test.targets
Labels: needs-review

#11195 [Storage] Support allowProtectedAppendWrites in ImmutabilityPolicy
  src/EventGrid/EventGrid.Test/EventGrid.Test.csproj
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/Blob/SetAzureStorageContainerImmutabilityPolicy.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSContainer.cs
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Management/help/Set-AzRmStorageContainerImmutabilityPolicy.md
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: needs-review
