Repository Azure/azure-powershell, pull requests merged in 2021-08, with the labels that each got.

#15552 [Resources] Use JsonExtensions to serialize and deserialize template and parameter objects
  src/Resources/ResourceManager/Json/PSJsonSerializer.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/ResourceManager/Utilities/TemplateUtility.cs
  src/Resources/Resources.Test/Json/PSJsonSerializerTests.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentFromTemplateAndParameterFileContainingDatetimeOutput.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentFromTemplateFileContainingDatetimeOutput.json
  src/Resources/Resources.Test/simpleTemplateWithDatetimeOutput.json
  src/Resources/Resources.Test/simpleTemplateWithDatetimeOutputParameters.json
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#15592 Update Network changelog for September release
  src/Network/Network/ChangeLog.md
Labels: needs-review

#15578 Add -AsJob to Remove-AzSqlInstande and -SubnetId to Set-AzSqlInstance
  src/Sql/Sql.Test/ScenarioTests/Common.ps1
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateUpdateManagedInstanceWithMinimalTlsVersion.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestRemoveManagedInstance.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestSetManagedInstance.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/RemoveAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/help/Remove-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
Labels: needs-review

#15545 [Storage] Support VLW
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageBlobInventory.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainer.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerEncryptionScope.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerLegalHold.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerSoftDelete.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerVLW.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobORS.json
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/Blob/InvokeAzureStorageContainerObjectLevelWormMigration.cs
  src/Storage/Storage.Management/Blob/NewAzureStorageContainer.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSContainer.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Invoke-AzRmStorageContainerImmutableStorageWithVersioningMigration.md
  src/Storage/Storage.Management/help/New-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/New-AzStorageContainer.md
  src/Storage/Storage.Management/help/Remove-AzStorageBlobImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobLegalHold.md
  src/Storage/Storage/Blob/Cmdlet/RemoveAzStorageBlobImmutabilityPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzStorageBlobImmutabilityPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzStorageBlobLegalHold.cs
  src/Storage/Storage/Storage.csproj
Labels: Waiting for CI :shipit:

#15599 Update New-AzWebAppCertificate.md
  src/Websites/Websites/help/New-AzWebAppCertificate.md
Labels: customer-reported

#15604 Update Test-AzKustoClusterNameAvailability.md
  src/Kusto/help/Test-AzKustoClusterNameAvailability.md
Labels: customer-reported

#15584 Revert some previous change for readme.md in ADDomainServices
  src/ADDomainServices/readme.md
Labels: needs-revision

#15519 [RecoveryServices.Backup] Added MSI based Restore
  src/RecoveryServices/RecoveryServices.Backup.Helpers/RecoveryServices.Backup.Helpers.csproj
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Models/RecoveryServices.Backup.Models.csproj
  src/RecoveryServices/RecoveryServices.Backup.Models/VaultModels/VaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/RecoveryServices.Backup.Providers.csproj
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/RecoveryServices.Backup.ServiceClientAdapter.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/GetAzureVmWorkloadContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVMGetContainers.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRSVaultMSI.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureUnmanagedVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMCrossRegionRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMDiskExclusion.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetItems.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMRPMountScript.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMRestoreWithMSI.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMSetVaultContext.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureFSGetJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMCancelJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobsTimeFilter.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMWaitJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadPolicy.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/GetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.Test/RecoveryServices.Test.csproj
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
  src/RecoveryServices/RecoveryServices/help/Az.RecoveryServices.md
  src/RecoveryServices/RecoveryServices/help/Copy-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: needs-review

#15624 Add some SingularNouns for Statis Analysis
  tools/Tools.Common/Models/CmdletMetadata.cs
Labels: needs-review

#15583 [ChangeAnalysis] Release version 0.1.0
  src/ChangeAnalysis/.gitattributes
  src/ChangeAnalysis/.gitignore
  src/ChangeAnalysis/Az.ChangeAnalysis.psd1
  src/ChangeAnalysis/custom/readme.md
  src/ChangeAnalysis/docs/Az.ChangeAnalysis.md
  src/ChangeAnalysis/docs/Get-AzChangeAnalysis.md
  src/ChangeAnalysis/docs/readme.md
  src/ChangeAnalysis/examples/Get-AzChangeAnalysis.md
  src/ChangeAnalysis/how-to.md
  src/ChangeAnalysis/license.txt
  src/ChangeAnalysis/readme.md
  src/ChangeAnalysis/resources/readme.md
  src/ChangeAnalysis/test/Get-AzChangeAnalysis.Recording.json
  src/ChangeAnalysis/test/Get-AzChangeAnalysis.Tests.ps1
  src/ChangeAnalysis/test/deployment-templates/key-vault/parameters.json
  src/ChangeAnalysis/test/deployment-templates/key-vault/template.json
  src/ChangeAnalysis/test/env.json
  src/ChangeAnalysis/test/loadEnv.ps1
  src/ChangeAnalysis/test/readme.md
  src/ChangeAnalysis/test/utils.ps1
  src/ChangeAnalysis/utils/Unprotect-SecureString.ps1
  tools/StaticAnalysis/Exceptions/Az.ChangeAnalysis/SignatureIssues.csv
Labels: needs-review

#15646 Update New-AzDataMigrationService.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationService.md
Labels: customer-reported

#15582 [Storage] Fix Bug 10483492: Remove-AzDataLakeGen2Item fails with readonly sas
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Common/AzureDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/MoveAzDataLakeGen2Item.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RemoveAzDataLakeGen2Item.cs
Labels: needs-review

#15666 Create mutex names that are safe for Linux (fixes #15653)
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Sync/Upload/BlobCreatorBase.cs
Labels: customer-reported

#15667 [SQL] Updating SDK Package Version
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.LedgerDigestUploadTests/TestGetDefaultLedgerDigestUpload.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.LedgerDigestUploadTests/TestSetLedgerDigestUploadByDatabaseObject.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.LedgerDigestUploadTests/TestSetLedgerDigestUploadByName.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.LedgerDigestUploadTests/TestSetLedgerDigestUploadByResourceId.json
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Sql.csproj
Labels: SQL

#15719 Fix typo in cmdlet example
  src/ApiManagement/ApiManagement/help/Remove-AzApiManagementApiSchema.md
Labels: customer-reported

#15710 [Doc] How to: Enable Overriding Subscription ID in Your Module
  documentation/development-docs/enable-subscription-id-overriding.md
Labels: Doc - Internal, needs-review

#15737 Support creating ec keys in key vault
  src/KeyVault/KeyVault.Test/PesterTests/Key.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/AddAzureKeyVaultKey.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/PSDeletedKeyVaultKey.cs
  src/KeyVault/KeyVault/Models/PSKeyVaultKey.cs
  src/KeyVault/KeyVault/Track2Models/Track2VaultClient.cs
  src/KeyVault/KeyVault/help/Add-AzKeyVaultKey.md
Labels: needs-review

#15772 Adding support for pagination in Sql Get Databases
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Services/AzureSqlDatabaseCommunicator.cs
Labels: customer-reported

#15773 Polish changelog for upcoming release
  src/SecurityInsights/SecurityInsights/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
Labels: needs-review

#15777 [Az.RecoveryServices.Backup] Bug Fixes
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/GetAzureRmRecoveryServicesBackupWorkloadRecoveryConfig.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Register-AzRecoveryServicesBackupContainer.md
Labels: needs-review

#15779 Fix spelling of accountname
  src/Media/Media/help/Sync-AzMediaServiceStorageKey.md
Labels: customer-reported

#15780 Fix Spelling, examples
  src/DataShare/DataShare/help/New-AzDataShareDataSetMapping.md
Labels: customer-reported

#15788 Docs: Parameter is ignored when listing secrets
  src/KeyVault/KeyVault/help/Get-AzKeyVaultSecret.md
Labels: customer-reported
