Repository Azure/azure-powershell, pull requests merged in 2021-11, with the labels that each got.

#16295 Update Update-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage.Management/help/Update-AzDataLakeGen2AclRecursive.md
Labels: customer-reported

#16296 Update Get-AzEventGridDomain.md
  src/EventGrid/EventGrid/help/Get-AzEventGridDomain.md
Labels: customer-reported

#16293 Update Get-AzStorageBlob.md
  src/Storage/Storage.Management/help/Get-AzStorageBlob.md
Labels: customer-reported, needs-author-feedback

#16270 Replace the parameter FolderName of Sql script cmdlet
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/SqlScript/SetAzureSynapseSqlScript.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/help/Set-AzSynapseSqlScript.md
Labels: needs-revision

#16246 Update Get-AzVirtualWanVpnConfiguration.md
  src/Network/Network/help/Get-AzVirtualWanVpnConfiguration.md
Labels: Doc - Reference, needs-review, customer-reported

#15615 Update Remove-AzBatchJob.md
  src/Batch/Batch/help/Remove-AzBatchJob.md
Labels: customer-reported, needs-author-feedback

#16290 update-azvm will update application Profile
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
Labels: needs-review

#16235 Compute Generation PR
  src/Compute/Compute.Autorest/Az.Compute.psd1
  src/Compute/Compute.Autorest/README.md
  src/Compute/Compute.Autorest/custom/README.md
  src/Compute/Compute.Autorest/docs/Az.Compute.md
  src/Compute/Compute.Autorest/docs/Get-AzVMRunCommand.md
  src/Compute/Compute.Autorest/docs/Get-AzVmssVMRunCommand.md
  src/Compute/Compute.Autorest/docs/README.md
  src/Compute/Compute.Autorest/docs/Remove-AzVMRunCommand.md
  src/Compute/Compute.Autorest/docs/Remove-AzVmssVMRunCommand.md
  src/Compute/Compute.Autorest/docs/Set-AzVMRunCommand.md
  src/Compute/Compute.Autorest/docs/Set-AzVmssVMRunCommand.md
  src/Compute/Compute.Autorest/examples/Get-AzVMRunCommand.md
  src/Compute/Compute.Autorest/examples/Get-AzVmssVMRunCommand.md
  src/Compute/Compute.Autorest/examples/Remove-AzVMRunCommand.md
  src/Compute/Compute.Autorest/examples/Remove-AzVmssVMRunCommand.md
  src/Compute/Compute.Autorest/examples/Set-AzVMRunCommand.md
  src/Compute/Compute.Autorest/examples/Set-AzVmssVMRunCommand.md
  src/Compute/Compute.Autorest/test/Get-AzVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Get-AzVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Get-AzVmssVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Get-AzVmssVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/README.md
  src/Compute/Compute.Autorest/test/Remove-AzVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Remove-AzVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Remove-AzVmssVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Remove-AzVmssVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Set-AzVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Set-AzVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Set-AzVmssVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Set-AzVmssVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/loadEnv.ps1
  src/Compute/Compute.Autorest/test/utils.ps1
Labels: needs-revision

#16114 Update Az.Storage.md
  src/Storage/Storage.Management/help/Az.Storage.md
Labels: Waiting for CI :shipit:

#16297 Add Get-Date note to New-AzStorageAccountSASToken's ExpiryTime
  src/Storage/Storage.Management/help/New-AzStorageAccountSASToken.md
Labels: needs-revision, needs-author-feedback

#16248 [Advisor] Fixed the issue that `Az.Advisor.psd1` was not signed
  src/Advisor/Advisor/ChangeLog.md
Labels: Waiting for CI :shipit:

#16323 Update New-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
Labels: needs-review

#16314 Remove the modules in the skip list of generation branch
  tools/PrepareAutorestModule.ps1
Labels: needs-review

#16335 Update MediaServices private link registration
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#16329 Update Get-AzP2sVpnGatewayDetailedConnectionHealth.md to Clarify SaS URL requirements
  src/Network/Network/help/Get-AzP2sVpnGatewayDetailedConnectionHealth.md
Labels: Waiting for CI :shipit:

#16304 [DataFactory]Updated ADF .Net SDK version to 4.27.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-review

#16164 Update issue template using Github form schema
  .github/ISSUE_TEMPLATE/1-AZ-BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/2-FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/3-AZ-QUESTION.yml
  .github/ISSUE_TEMPLATE/4-AZ-DOC-BUG.yml
  .github/ISSUE_TEMPLATE/5-AZURERM-BUG.yml
  .github/ISSUE_TEMPLATE/INTERNAL-ISSUE.yml
  .github/ISSUE_TEMPLATE/az-module-bug-report.md
  .github/ISSUE_TEMPLATE/azurerm-module-bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/internal-issue.md
Labels: needs-review

#15867 (AzureCXP) Add a note about handling Production slots during Swap operations
  src/Websites/Websites/help/Switch-AzWebAppSlot.md
Labels: Waiting for CI :shipit:

#16301 [Aks] Added ResourceGroupName in PSKubernetesCluster
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Models/PSKubernetesCluster.cs
Labels: Waiting for CI :shipit:

#16300 [Aks] Align the logic of Set-AzAks to cli
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.cs
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.ps1
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestUpgradeKubernetesVersion.json
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
  src/Aks/Aks/help/Set-AzAksCluster.md
Labels: Waiting for CI :shipit:

#16337 Support Login Hint
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Connect-AzAccount.md
  src/Accounts/Accounts/help/Open-AzSurveyLink.md
  src/Accounts/Authentication/Authentication.csproj
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  src/Accounts/Authenticators/Authenticators.csproj
  src/Accounts/Authenticators/InteractiveUserAuthenticator.cs
  src/lib/NetCorePreloadAssemblies/Azure.Identity.dll
  src/lib/NetFxPreloadAssemblies/Azure.Identity.dll
Labels: needs-review

#16366 Update New-AzAutomationSourceControl.md
  src/Automation/Automation/help/New-AzAutomationSourceControl.md
Labels: Waiting for CI :shipit:, customer-reported

#16347 [Policy] Adding examples for retrieving component-level policy compliance states
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyState.md
Labels: Waiting for CI :shipit:

#15723 [CosmosDB] Changing the warning message for AnalyticalStorageSchemaType
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewOrUpdateAzCosmosDBAccount.cs
Labels: Waiting for CI :shipit:, customer-reported

#16159 [Resources] Add `Publish-AzBicepModule` for publishing Bicep files
  src/Resources/ResourceManager/Implementation/Bicep/PublishAzureBicepModuleCmdlet.cs
  src/Resources/ResourceManager/Utilities/BicepUtility.cs
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Az.Resources.md
  src/Resources/Resources/help/Publish-AzBicepModule.md
Labels: needs-revision, Cmdlet Review Complete

#16247 Update IdentifierUris of ADApp and DisplayName of ADServicePrincipal
  src/Resources/ResourceManager/Properties/AssemblyInfo.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADApplicationCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADApplicationCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADServicePrincipalCommand.cs
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Properties/AssemblyInfo.cs
  src/Resources/Resources/help/New-AzADApplication.md
  src/Resources/Resources/help/New-AzADServicePrincipal.md
  tools/Az/Az.psd1
Labels: Azure Stack

#16156 [Synapse] Spark Configuration cmdlets
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/SparkConfiguration/ExportAzureSynapseSparkConfiguration.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/SparkConfiguration/GetAzureSynapseSparkConfiguration.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/SparkConfiguration/NewAzureSynapseSparkConfiguration.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/SparkConfiguration/RemoveAzureSynapseSparkConfiguration.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/SparkConfiguration/PSSparkConfiguration.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/SparkConfiguration/PSSparkConfigurationResource.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/SynapseAnalyticsArtifactsClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Export-AzSynapseSparkConfiguration.md
  src/Synapse/Synapse/help/Get-AzSynapseSparkConfiguration.md
  src/Synapse/Synapse/help/New-AzSynapseSparkConfiguration.md
  src/Synapse/Synapse/help/Remove-AzSynapseSparkConfiguration.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#16305 [Storage] Support VLW and account level worm GA
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestAzureStorageAccountWorm.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountEnableNfsV3.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageBlobInventory.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainer.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerEncryptionScope.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerLegalHold.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerSoftDelete.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerVLW.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobORS.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/Blob/InvokeAzureStorageContainerObjectLevelWormMigration.cs
  src/Storage/Storage.Management/Blob/NewAzureStorageContainer.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSContainer.cs
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Disable-AzStorageContainerDeleteRetentionPolicy.md
  src/Storage/Storage.Management/help/Enable-AzStorageContainerDeleteRetentionPolicy.md
  src/Storage/Storage.Management/help/Invoke-AzRmStorageContainerImmutableStorageWithVersioningMigration.md
  src/Storage/Storage.Management/help/New-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageContainer.md
  src/Storage/Storage.Management/help/Remove-AzStorageBlobImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobLegalHold.md
  src/Storage/Storage/Blob/Cmdlet/RemoveAzStorageBlobImmutabilityPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzStorageBlobImmutabilityPolicy.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzStorageBlobLegalHold.cs
Labels: needs-review

#16360 Attestation/WSS Release
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
  src/StackHCI/help/Add-AzStackHCIVMAttestation.md
  src/StackHCI/help/Az.StackHCI.md
  src/StackHCI/help/Disable-AzStackHCIAttestation.md
  src/StackHCI/help/Enable-AzStackHCIAttestation.md
  src/StackHCI/help/Get-AzStackHCIVMAttestation.md
  src/StackHCI/help/Remove-AzStackHCIVMAttestation.md
  src/StackHCI/help/Set-AzStackHCI.md
Labels: Waiting for CI :shipit:

#14905 [Communication] Update to swagger version 2020-08-20
  src/Communication/Az.Communication.psd1
  src/Communication/custom/readme.md
  src/Communication/docs/Az.Communication.md
  src/Communication/docs/Get-AzCommunicationService.md
  src/Communication/docs/Get-AzCommunicationServiceKey.md
  src/Communication/docs/New-AzCommunicationService.md
  src/Communication/docs/New-AzCommunicationServiceKey.md
  src/Communication/docs/Remove-AzCommunicationService.md
  src/Communication/docs/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/docs/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/docs/Update-AzCommunicationService.md
  src/Communication/examples/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/readme.md
  src/Communication/test/Get-AzCommunicationService.Recording.json
  src/Communication/test/Get-AzCommunicationServiceKey.Recording.json
  src/Communication/test/New-AzCommunicationService.Recording.json
  src/Communication/test/New-AzCommunicationServiceKey.Recording.json
  src/Communication/test/Set-AzCommunicationServiceNotificationHub.Recording.json
  src/Communication/test/Test-AzCommunicationServiceNameAvailability.Recording.json
  src/Communication/test/Test-AzCommunicationServiceNameAvailability.Tests.ps1
  src/Communication/test/Update-AzCommunicationService.Recording.json
  src/Communication/test/env.json
  src/Communication/test/loadEnv.ps1
  src/Communication/test/utils.ps1
  src/Communication/utils/Unprotect-SecureString.ps1
Labels: needs-revision

#16133 NAT Port Range for VPN
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestVirtualNetworkGatewayNatRuleCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VpnGatewayNatRule/NewAzureRmVpnGatewayNatRuleCommand.cs
  src/Network/Network/Cortex/VpnGatewayNatRule/UpdateAzureRmVpnGatewayNatRuleCommand.cs
  src/Network/Network/Models/PSVpnNatRuleMapping.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/VirtualNetworkGateway/VirtualNetworkGatewayNatRule/NewAzureVirtualNetworkGatewayNatRule.cs
  src/Network/Network/VirtualNetworkGateway/VirtualNetworkGatewayNatRule/UpdateAzureVirtualNetworkGatewayNatRule.cs
  src/Network/Network/help/New-AzVirtualNetworkGatewayNatRule.md
  src/Network/Network/help/New-AzVpnGatewayNatRule.md
  src/Network/Network/help/Update-AzVirtualNetworkGatewayNatRule.md
  src/Network/Network/help/Update-AzVpnGatewayNatRule.md
Labels: Waiting for CI :shipit:

#16388 Added default parameter set for command Get-AzAlertRule
  src/Monitor/Monitor.sln
  src/Monitor/Monitor/Alerts/GetAzureRmAlertRuleCommand.cs
  src/Monitor/Monitor/ChangeLog.md
Labels: Waiting for CI :shipit:

#16387 [Kusto] Lock commit ID of swagger
  src/Kusto/readme.md
Labels: needs-review

#16398 StackHCI - Change output type on new cmdlets
  src/StackHCI/Az.StackHCI.psm1
Labels: Waiting for CI :shipit:

#16321 Az.Tools.Installer v2
  .azure-pipelines/sign-tools.yml
  tools/Az.Tools.Installer/.gitignore
  tools/Az.Tools.Installer/Az.Tools.Installer.psd1
  tools/Az.Tools.Installer/Az.Tools.Installer.psm1
  tools/Az.Tools.Installer/GenerateHelp.ps1
  tools/Az.Tools.Installer/build.proj
  tools/Az.Tools.Installer/exports/Install-AzModule.ps1
  tools/Az.Tools.Installer/exports/Uninstall-AzModule.ps1
  tools/Az.Tools.Installer/exports/Update-AzModule.ps1
  tools/Az.Tools.Installer/help/Install-AzModule.md
  tools/Az.Tools.Installer/help/Uninstall-AzModule.md
  tools/Az.Tools.Installer/help/Update-AzModule.md
  tools/Az.Tools.Installer/internal/Add-RepositoryArgumentCompleter.ps1
  tools/Az.Tools.Installer/internal/Add-RepositoryDefaultValue.ps1
  tools/Az.Tools.Installer/internal/Classes.ps1
  tools/Az.Tools.Installer/internal/Get-AzModuleUpdateList.ps1
  tools/Az.Tools.Installer/internal/Install-AzModuleInternal.ps1
  tools/Az.Tools.Installer/internal/Install-AzModule_ByPath.ps1
  tools/Az.Tools.Installer/internal/Install-AzModule_Default.ps1
  tools/Az.Tools.Installer/internal/Install-SingleModuleFromPackage.ps1
  tools/Az.Tools.Installer/internal/Send-PageViewTelemetry.ps1
  tools/Az.Tools.Installer/test-module.ps1
  tools/Az.Tools.Installer/test/Az.Tools.Installer.Tests.Helper.ps1
  tools/Az.Tools.Installer/test/Install-AzModule.Tests.ps1
  tools/Az.Tools.Installer/test/README.md
  tools/Az.Tools.Installer/test/Uninstall-AzModule.Tests.ps1
  tools/Az.Tools.Installer/test/Update-AzModule.Tests.ps1
Labels: needs-review

#15994 Add-AzVhd Convenience Layer
  src/Compute/Compute.AlcWrapper/PSPageBlobClient.cs
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Models/PSSyncOutputEvents.cs
  src/Compute/Compute/StorageServices/AddAzureVhdCommand.cs
  src/Compute/Compute/StorageServices/StorageUtilities.cs
  src/Compute/Compute/StorageServices/VirtualHardDiskSettingData.cs
  src/Compute/Compute/StorageServices/WmiUtilities.cs
  src/Compute/Compute/Sync/Program.cs
  src/Compute/Compute/Sync/Upload/DiskSynchronizer.cs
  src/Compute/Compute/Sync/Upload/DiskUploadCreator.cs
  src/Compute/Compute/Sync/Upload/UploadContextDisk.cs
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
  src/Compute/Compute/help/Add-AzVhd.md
  tools/PostBuildModuleAlc.ps1
  tools/StaticAnalysis/Exceptions/Az.Compute/SignatureIssues.csv
Labels: needs-review

#16412 Remove unused directives after autorest.powershell is upgraded
  src/ConnectedKubernetes/readme.md
  src/ImageBuilder/readme.md
Labels: Waiting for CI :shipit:

#16389 Add module info to useragent
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
  src/Accounts/Accounts/CommonModule/UserAgent.cs
  src/Accounts/Authentication/Factories/ClientFactory.cs
  tools/Common.Netcore.Dependencies.targets
  tools/ScenarioTest.ResourceManager/Mocks/MockClientFactory.cs
  tools/TestFx/TestClientFactory.cs
Labels: needs-review

#16402 Schedule name shouldn't contains special character
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Cmdlet/NewAzureAutomationSchedule.cs
  src/Automation/Automation/Properties/Resources.Designer.cs
  src/Automation/Automation/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#16350 [Az.ContainerInstance] Connect websocket for Invoke-AzContainerInstanceCommand
  src/ContainerInstance/Az.ContainerInstance.psd1
  src/ContainerInstance/custom/Invoke-AzContainerInstanceCommand.ps1
  src/ContainerInstance/custom/InvokeAzContainerInstanceCommand_ExecuteExpanded.cs
  src/ContainerInstance/custom/New-AzContainerGroup.ps1
  src/ContainerInstance/docs/Add-AzContainerInstanceOutput.md
  src/ContainerInstance/docs/Az.ContainerInstance.md
  src/ContainerInstance/docs/Get-AzContainerGroup.md
  src/ContainerInstance/docs/Invoke-AzContainerInstanceCommand.md
  src/ContainerInstance/docs/New-AzContainerGroup.md
  src/ContainerInstance/docs/New-AzContainerInstanceHttpHeaderObject.md
  src/ContainerInstance/docs/Restart-AzContainerGroup.md
  src/ContainerInstance/examples/Add-AzContainerInstanceOutput.md
  src/ContainerInstance/examples/Get-AzContainerGroup.md
  src/ContainerInstance/examples/Invoke-AzContainerInstanceCommand.md
  src/ContainerInstance/examples/New-AzContainerGroup.md
  src/ContainerInstance/examples/New-AzContainerInstanceHttpHeaderObject.md
  src/ContainerInstance/examples/Remove-AzContainerGroup.md
  src/ContainerInstance/examples/Restart-AzContainerGroup.md
  src/ContainerInstance/examples/new-AzContainerInstanceHttpHeaderObject.md
  src/ContainerInstance/readme.md
  src/ContainerInstance/test/Add-AzContainerInstanceOutput.Recording.json
  src/ContainerInstance/test/Get-AzContainerGroup.Recording.json
  src/ContainerInstance/test/Get-AzContainerInstanceCachedImage.Recording.json
  src/ContainerInstance/test/Get-AzContainerInstanceCapability.Recording.json
  src/ContainerInstance/test/Get-AzContainerInstanceLog.Recording.json
  src/ContainerInstance/test/Get-AzContainerInstanceUsage.Recording.json
  src/ContainerInstance/test/Invoke-AzContainerInstanceCommand.Recording.json
  src/ContainerInstance/test/New-AzContainerGroup.Recording.json
  src/ContainerInstance/test/Remove-AzContainerGroup.Recording.json
  src/ContainerInstance/test/Restart-AzContainerGroup.Recording.json
  src/ContainerInstance/test/Restart-AzContainerGroup.Tests.ps1
  src/ContainerInstance/test/Start-AzContainerGroup.Recording.json
  src/ContainerInstance/test/Stop-AzContainerGroup.Recording.json
  src/ContainerInstance/test/Update-AzContainerGroup.Recording.json
  src/ContainerInstance/test/env.json
  tools/StaticAnalysis/Exceptions/Az.ContainerInstance/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#16228 Fixes to azure disk encryption cmdlets
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetExtensionTests.ps1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.format.ps1xml
  src/Compute/Compute/Extension/AzureDiskEncryption/SetAzureDiskEncryptionExtension.cs
  src/Compute/Compute/Extension/VmssDiskEncryption/DisableAzureVmssDiskEncryption.cs
  src/Compute/Compute/Extension/VmssDiskEncryption/GetAzureVmssVMDiskEncryptionStatus.cs
  src/Compute/Compute/Extension/VmssDiskEncryption/SetAzureVmssDiskEncryptionExtension.cs
  src/Compute/Compute/Models/PSVmssVMDiskEncryptionStatusContext.cs
  src/Compute/Compute/help/Set-AzVmssDiskEncryptionExtension.md
Labels: Waiting for CI :shipit:

#16374 [Storage] remove Name from Get-AzRmStorageShare ShareResourceIdParameterSet
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/File/GetAzureStorageShare.cs
  src/Storage/Storage.Management/help/Get-AzRmStorageShare.md
  src/Storage/Storage.Management/help/New-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Update-AzRmStorageShare.md
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:, Breaking Change Release

#16351 [Aks] Migrate to msgraph
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.ps1
  src/Aks/Aks.Test/ScenarioTests/TestController.cs
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestAzureKubernetes.json
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestNewAzureKubernetesByServicePrincipal.json
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestSimpleAzureKubernetes.json
  src/Aks/Aks.Test/SessionRecords/Commands.Aks.Test.ScenarioTests.KubernetesTests/TestUpgradeKubernetesVersion.json
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/Constants.cs
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/Aks/Aks/Commands/KubeCmdletBase.cs
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#16299 Update ADO image
  .azure-pipelines/powershell-core.yml
  .azure-pipelines/release-test.yml
  .azure-pipelines/windows-powershell.yml
Labels: Engineering, Waiting for CI :shipit:

#16187 Added UserData parameter to Vm, Vmss, VmssVm cmdlets
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetUserdata.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMUserData.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMUserDataBase64Encoded.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Common/ValidateBase64EncodedString.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSetVM.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMGetMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMUpdateMethod.cs
  src/Compute/Compute/Manual/PSVirtualMachineScaleSetVMProfile.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Models/PSVirtualMachine.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/Get-AzVM.md
  src/Compute/Compute/help/Get-AzVmss.md
  src/Compute/Compute/help/Get-AzVmssVM.md
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Update-AzVM.md
  src/Compute/Compute/help/Update-AzVmss.md
  src/Compute/Compute/help/Update-AzVmssVM.md
Labels: needs-revision

#16432 [OperationalInsights] Modified output result the Invoke-AzOperationalInsightsQuery.
  src/OperationalInsights/OperationalInsights.Test/OperationalInsights.Test.csproj
  src/OperationalInsights/OperationalInsights/ChangeLog.md
  src/OperationalInsights/OperationalInsights/Models/PSQueryResponse.cs
  src/OperationalInsights/OperationalInsights/OperationalInsights.csproj
  src/OperationalInsights/OperationalInsights/OperationalInsights.format.ps1xml
Labels: Waiting for CI :shipit:

#16425 [Redis] updating redis api version in PrivatelinkServiceProvider configuration
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#16440 Added a message to Set-AzKeyVaultAccessPolicy about using the 'All' option for Permissions
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultAccessPolicy.md
Labels: Waiting for CI :shipit:

#16434 Remove unsupported force parameter in Remove-AzAutomationHybridWorkerGroup reference doc
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/help/Remove-AzAutomationHybridWorkerGroup.md
Labels: Waiting for CI :shipit:

#16470 Typo "Azure CosmosDB"→"Azure Cosmos DB"
  src/CosmosDB/CosmosDB/help/Az.CosmosDB.md
Labels: Waiting for CI :shipit:, customer-reported

#16461 Add API version notice on Budget modules
  src/Billing/Billing/help/Get-AzConsumptionBudget.md
  src/Billing/Billing/help/New-AzConsumptionBudget.md
  src/Billing/Billing/help/Remove-AzConsumptionBudget.md
  src/Billing/Billing/help/Set-AzConsumptionBudget.md
Labels: Waiting for CI :shipit:

#16271 [Storage] Fixed create container SAS token fail from an access policy without expireTime, and set expireTime
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerStoredAccessPolicy.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
  src/Storage/Storage/Common/StorageExtensions.cs
  src/Storage/Storage/Common/Util.cs
Labels: needs-review

#16455 Az.Accounts 2.6.2 release
  src/Accounts/Accounts/Az.Accounts.psd1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/AssemblyInfo.cs
  src/Accounts/Authentication/Properties/AssemblyInfo.cs
  src/Accounts/Authenticators/Properties/AssemblyInfo.cs
  tools/Tools.Common/SerializedCmdlets/Az.Accounts.json
Labels: Waiting for CI :shipit:

#16438 Updated IoT Central .NET package to 4.0.0 (RP version 2021-06-01) with support for Managed Identities
  src/IotCentral/IotCentral.Test/IotCentral.Test.csproj
  src/IotCentral/IotCentral.Test/ScenarioTests/IotCentralController.cs
  src/IotCentral/IotCentral.Test/ScenarioTests/IotCentralTests.ps1
  src/IotCentral/IotCentral.Test/SessionRecords/Microsoft.Azure.Commands.IotCentral.Test.ScenarioTests.IotCentralTests/TestIotCentralAppLifecycleManagement.json
  src/IotCentral/IotCentral/Az.IotCentral.psd1
  src/IotCentral/IotCentral/ChangeLog.md
  src/IotCentral/IotCentral/Common/IotCentralUtils.cs
  src/IotCentral/IotCentral/IotCentral.csproj
  src/IotCentral/IotCentral/IotCentral.generated.format.ps1xml
  src/IotCentral/IotCentral/IotCentral/GetAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/IotCentral/NewAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/IotCentral/SetAzureRmIotCentralApp.cs
  src/IotCentral/IotCentral/Models/PSIotCentralApp.cs
  src/IotCentral/IotCentral/Models/PSIotCentralAppSku.cs
  src/IotCentral/IotCentral/Models/PSIotCentralAppSkuInfo.cs
  src/IotCentral/IotCentral/help/Get-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/New-AzIotCentralApp.md
  src/IotCentral/IotCentral/help/Set-AzIotCentralApp.md
Labels: Waiting for CI :shipit:

#16181 Check in basic managed Cassandra cmdlets
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/CosmosDB/CosmosDB.Test/ScenarioTests/ManagedCassandraOperationsTests.cs
  src/CosmosDB/CosmosDB.Test/ScenarioTests/ManagedCassandraOperationsTests.ps1
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.ManagedCassandraOperationsTests/TestManagedCassandraClusterCreateUpdateGetCmdlets.json
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.ManagedCassandraOperationsTests/TestManagedCassandraDatacenterCreateUpdateGetCmdlets.json
  src/CosmosDB/CosmosDB.sln
  src/CosmosDB/CosmosDB/Az.CosmosDB.psd1
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/Helpers/Constants.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/GetAzManagedCassandraCluster.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/GetAzManagedCassandraDatacenter.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/NewAzManagedCassandraCluster.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/NewAzManagedCassandraDatacenter.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/NewOrUpdateAzManagedCassandraCluster.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/NewOrUpdateAzManagedCassandraDatacenter.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/RemoveAzManagedCassandraCluster.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/RemoveAzManagedCassandraDatacenter.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/UpdateAzManagedCassandraCluster.cs
  src/CosmosDB/CosmosDB/ManagedCassandra/UpdateAzManagedCassandraDatacenter.cs
  src/CosmosDB/CosmosDB/Models/ManagedCassandra/PSCertificate.cs
  src/CosmosDB/CosmosDB/Models/ManagedCassandra/PSClusterResource.cs
  src/CosmosDB/CosmosDB/Models/ManagedCassandra/PSClusterResourceProperties.cs
  src/CosmosDB/CosmosDB/Models/ManagedCassandra/PSDataCenterResource.cs
  src/CosmosDB/CosmosDB/Models/ManagedCassandra/PSDataCenterResourceProperties.cs
  src/CosmosDB/CosmosDB/Models/ManagedCassandra/PSSeedNode.cs
  src/CosmosDB/CosmosDB/help/Az.CosmosDB.md
  src/CosmosDB/CosmosDB/help/Get-AzManagedCassandraCluster.md
  src/CosmosDB/CosmosDB/help/Get-AzManagedCassandraDataCenter.md
  src/CosmosDB/CosmosDB/help/New-AzManagedCassandraCluster.md
  src/CosmosDB/CosmosDB/help/New-AzManagedCassandraDataCenter.md
  src/CosmosDB/CosmosDB/help/Remove-AzManagedCassandraCluster.md
  src/CosmosDB/CosmosDB/help/Remove-AzManagedCassandraDataCenter.md
  src/CosmosDB/CosmosDB/help/Update-AzManagedCassandraCluster.md
  src/CosmosDB/CosmosDB/help/Update-AzManagedCassandraDataCenter.md
Labels: Waiting for CI :shipit:

#16279 [WebPubSub] Fix
  src/SignalR/SignalR.Autorest/Az.SignalR.psd1
  src/SignalR/SignalR.Autorest/README.md
  src/SignalR/SignalR.Autorest/custom/scripts/Get-AzWebPubSubKey_ListViaIdentity.ps1
  src/SignalR/SignalR.Autorest/docs/Get-AzWebPubSubKey.md
  src/SignalR/SignalR.Autorest/docs/New-AzWebPubSub.md
  src/SignalR/SignalR.Autorest/docs/New-AzWebPubSubHub.md
  src/SignalR/SignalR.Autorest/docs/New-AzWebPubSubKey.md
  src/SignalR/SignalR.Autorest/examples/Get-AzWebPubSubKey.md
  src/SignalR/SignalR.Autorest/examples/New-AzWebPubSubHub.md
  src/SignalR/SignalR.Autorest/examples/New-AzWebPubSubKey.md
Labels: Waiting for CI :shipit:

#16390 Add GenerateCmdletDesignMarkdown.ps1 script
  tools/GenerateCmdletDesignMarkdown.ps1
Labels: Waiting for CI :shipit:

#16377 Removing PSAzureFirewallPolicyThreatIntelWhitelist validations
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewallPolicy/PSAzureFirewallPolicyThreatIntelWhitelist.cs
Labels: needs-review

#16473 Add about_az.help.txt into en-US culture folder
  build.proj
  src/Accounts/Accounts/help/About/about_az.help.txt
  src/Accounts/Accounts/help/About/about_az.md
  src/Az.props
  tools/CleanupBuild.ps1
  tools/Docs/CopyAboutTopics.ps1
  tools/Docs/GenerateAboutTopicTxt.ps1
  tools/HelpGeneration/HelpGeneration.psm1
Labels: Engineering, Doc - Reference, needs-review

#16454 Reduce access request for role assignment
  src/Resources/Resources.Test/ScenarioTests/DenyAssignmentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DenyAssignmentTests.ps1
  src/Resources/Resources.Test/ScenarioTests/RoleAssignmentTests.ps1
  src/Resources/Resources/ActiveDirectory/Models/ActiveDirectoryClient.cs
  src/Resources/Resources/ActiveDirectory/Models/OdataHelper.cs
  src/Resources/Resources/ActiveDirectory/Models/PSErrorHelperObject.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/DenyAssignments/GetAzureDenyAssignmentCommand.cs
  src/Resources/Resources/Models.Authorization/AuthorizationClient.cs
  src/Resources/Resources/Models.Authorization/AuthorizationClientExtensions.cs
  src/Resources/Resources/Models.Authorization/FilterDenyAssignmentsOptions.cs
  src/Resources/Resources/Models.Authorization/FilterRoleAssignmentsOptions.cs
  src/Resources/Resources/Models.Authorization/PSRoleAssignment.cs
  src/Resources/Resources/RoleAssignments/GetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/SetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/help/Get-AzDenyAssignment.md
Labels: needs-review

#16384 [Application Insights] release 2018-05-01-preview version.
  src/ApplicationInsights/ApplicationInsights.Autorest/.gitattributes
  src/ApplicationInsights/ApplicationInsights.Autorest/.gitignore
  src/ApplicationInsights/ApplicationInsights.Autorest/Az.ApplicationInsights.psd1
  src/ApplicationInsights/ApplicationInsights.Autorest/README.md
  src/ApplicationInsights/ApplicationInsights.Autorest/custom/New-AzApplicationInsightsWebTest.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/custom/New-AzApplicationInsightsWebTestHeaderFieldObject.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/custom/README.md
  src/ApplicationInsights/ApplicationInsights.Autorest/custom/autogen-model-cmdlets/New-AzApplicationInsightsWebTestGeolocationObject.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/Az.ApplicationInsights.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/Get-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/New-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/New-AzApplicationInsightsWebTestGeolocationObject.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/New-AzApplicationInsightsWebTestHeaderFieldObject.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/README.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/Remove-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/docs/Update-AzApplicationInsightsWebTestTag.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/Get-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/New-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/New-AzApplicationInsightsWebTestGeolocationObject.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/New-AzApplicationInsightsWebTestHeaderFieldObject.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/Remove-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/Update-AzApplicationInsightsWebTestTag.md
  src/ApplicationInsights/ApplicationInsights.Autorest/how-to.md
  src/ApplicationInsights/ApplicationInsights.Autorest/license.txt
  src/ApplicationInsights/ApplicationInsights.Autorest/resources/README.md
  src/ApplicationInsights/ApplicationInsights.Autorest/test/Get-AzApplicationInsightsWebTest.Recording.json
  src/ApplicationInsights/ApplicationInsights.Autorest/test/Get-AzApplicationInsightsWebTest.Tests.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/New-AzApplicationInsightsWebTest.Recording.json
  src/ApplicationInsights/ApplicationInsights.Autorest/test/New-AzApplicationInsightsWebTest.Tests.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/New-AzApplicationInsightsWebTestGeolocationObject.Tests.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/New-AzApplicationInsightsWebTestHeaderFieldObject.Tests.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/README.md
  src/ApplicationInsights/ApplicationInsights.Autorest/test/Remove-AzApplicationInsightsWebTest.Tests.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/Update-AzApplicationInsightsWebTestTag.Recording.json
  src/ApplicationInsights/ApplicationInsights.Autorest/test/Update-AzApplicationInsightsWebTestTag.Tests.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/env.json
  src/ApplicationInsights/ApplicationInsights.Autorest/test/loadEnv.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/test/utils.ps1
  src/ApplicationInsights/ApplicationInsights.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-revision

#16396 Add AcceleratedNetwork and PublicNetworkAccess parameters to Disk and Snapshot cmdlets
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.cs
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskAcceleratedNetworkAndPublicNetworkAccess.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/Generated/Models/PSDisk.cs
  src/Compute/Compute/Generated/Models/PSDiskUpdate.cs
  src/Compute/Compute/Generated/Models/PSSnapshot.cs
  src/Compute/Compute/Generated/Models/PSSnapshotUpdate.cs
  src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotConfigCommand.cs
  src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotUpdateConfigCommand.cs
  src/Compute/Compute/help/New-AzDiskConfig.md
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
  src/Compute/Compute/help/New-AzSnapshotConfig.md
  src/Compute/Compute/help/New-AzSnapshotUpdateConfig.md
Labels: needs-review

#16496 Add MSGraph message for Az.Resources
  src/Resources/Resources/DenyAssignments/GetAzureDenyAssignmentCommand.cs
  src/Resources/Resources/Helper/MSGraphMessageHelper.cs
  src/Resources/Resources/RoleAssignments/GetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/SetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/help/Get-AzDenyAssignment.md
  src/Resources/Resources/help/Get-AzRoleAssignment.md
  src/Resources/Resources/help/New-AzRoleAssignment.md
  src/Resources/Resources/help/Remove-AzRoleAssignment.md
  src/Resources/Resources/help/Set-AzRoleAssignment.md
Labels: Waiting for CI :shipit:

#16489 removing word "advanced"
  src/Sql/Sql/help/Set-AzSqlServerAudit.md
Labels: Waiting for CI :shipit:, needs-review, customer-reported

#16493 [Az.CloudService] Make Az.CloudService GA
  src/CloudService/Changelog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: needs-revision

#16449 Remove secrets in PSAzurerRmAccount from display
  src/Accounts/Accounts.Test/ContextCmdletTests.cs
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.SubscriptionCmdletTests/GetSubscriptionsAfterContextRenameAndSet.json
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.cs
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.ps1
  src/Accounts/Accounts/Accounts.format.ps1xml
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication.ResourceManager/AzureRmProfile.cs
  src/Accounts/Authentication.ResourceManager/Models/PSAzureRmAccount.cs
Labels: Waiting for CI :shipit:

#16502 Add description for scripts under tools/Docs
  tools/Docs/CopyAboutTopics.ps1
  tools/Docs/GenerateAboutTopicTxt.ps1
  tools/Docs/GenerateDotNetCsv.ps1
  tools/Docs/README.md
Labels: Waiting for CI :shipit:

#16494 [Az.Functions] Bug fixes for the breaking change release
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
  src/Functions/custom/FunctionsStack/WindowsFunctionsStacks.json
  src/Functions/custom/HelperFunctions.ps1
  src/Functions/custom/New-AzFunctionApp.ps1
  src/Functions/custom/Remove-AzFunctionApp.ps1
  src/Functions/custom/Update-AzFunctionApp.ps1
  src/Functions/custom/Update-AzFunctionAppPlan.ps1
  src/Functions/docs/Update-AzFunctionApp.md
  src/Functions/docs/Update-AzFunctionAppPlan.md
  src/Functions/examples/Update-AzFunctionApp.md
  src/Functions/examples/Update-AzFunctionAppPlan.md
  src/Functions/test/Get-AzFunctionApp.Recording.json
  src/Functions/test/Get-AzFunctionApp.Tests.ps1
  src/Functions/test/Get-AzFunctionAppAvailableLocation.Recording.json
  src/Functions/test/Get-AzFunctionAppPlan.Recording.json
  src/Functions/test/Get-Update-Remove-AzFunctionAppSetting.Recording.json
  src/Functions/test/New-AzFunctionApp.Recording.json
  src/Functions/test/New-AzFunctionApp.Tests.ps1
  src/Functions/test/New-AzFunctionAppPlan.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.ps1
  src/Functions/test/New-Update-Remove-AzFunctionAppPlan.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionAppPlan.Tests.ps1
  src/Functions/test/Remove-AzFunctionApp.Recording.json
  src/Functions/test/Remove-AzFunctionApp.Tests.ps1
  src/Functions/test/Restart-Start-Stop-AzFunctionApp.Recording.json
  src/Functions/test/env.json
  src/Functions/test/utils.ps1
Labels: needs-review, Breaking Change Release

#16501 [ManagedServices] Release 2020-02-01-preview
  src/ManagedServices/.gitattributes
  src/ManagedServices/.gitignore
  src/ManagedServices/Az.ManagedServices.psd1
  src/ManagedServices/README.md
  src/ManagedServices/custom/Get-AzManagedServicesMarketplaceDefinition.ps1
  src/ManagedServices/custom/New-AzManagedServicesEligibleAuthorizationObject.ps1
  src/ManagedServices/custom/README.md
  src/ManagedServices/docs/Az.ManagedServices.md
  src/ManagedServices/docs/Get-AzManagedServicesAssignment.md
  src/ManagedServices/docs/Get-AzManagedServicesDefinition.md
  src/ManagedServices/docs/Get-AzManagedServicesMarketplaceDefinition.md
  src/ManagedServices/docs/New-AzManagedServicesAssignment.md
  src/ManagedServices/docs/New-AzManagedServicesAuthorizationObject.md
  src/ManagedServices/docs/New-AzManagedServicesDefinition.md
  src/ManagedServices/docs/New-AzManagedServicesEligibleApproverObject.md
  src/ManagedServices/docs/New-AzManagedServicesEligibleAuthorizationObject.md
  src/ManagedServices/docs/README.md
  src/ManagedServices/docs/Remove-AzManagedServicesAssignment.md
  src/ManagedServices/docs/Remove-AzManagedServicesDefinition.md
  src/ManagedServices/examples/Get-AzManagedServicesAssignment.md
  src/ManagedServices/examples/Get-AzManagedServicesDefinition.md
  src/ManagedServices/examples/Get-AzManagedServicesMarketplaceDefinition.md
  src/ManagedServices/examples/New-AzManagedServicesAssignment.md
  src/ManagedServices/examples/New-AzManagedServicesAuthorizationObject.md
  src/ManagedServices/examples/New-AzManagedServicesDefinition.md
  src/ManagedServices/examples/New-AzManagedServicesEligibleApproverObject.md
  src/ManagedServices/examples/New-AzManagedServicesEligibleAuthorizationObject.md
  src/ManagedServices/examples/Remove-AzManagedServicesAssignment.md
  src/ManagedServices/examples/Remove-AzManagedServicesDefinition.md
  src/ManagedServices/how-to.md
  src/ManagedServices/license.txt
  src/ManagedServices/resources/README.md
  src/ManagedServices/test/Get-AzManagedServicesAssignment.Tests.ps1
  src/ManagedServices/test/Get-AzManagedServicesDefinition.Tests.ps1
  src/ManagedServices/test/Get-AzManagedServicesMarketplaceDefinition.Tests.ps1
  src/ManagedServices/test/New-AzManagedServicesAssignment.Tests.ps1
  src/ManagedServices/test/New-AzManagedServicesAuthorizationObject.Tests.ps1
  src/ManagedServices/test/New-AzManagedServicesDefinition.Tests.ps1
  src/ManagedServices/test/New-AzManagedServicesEligibleApproverObject.Tests.ps1
  src/ManagedServices/test/New-AzManagedServicesEligibleAuthorizationObject.Tests.ps1
  src/ManagedServices/test/README.md
  src/ManagedServices/test/Remove-AzManagedServicesAssignment.Tests.ps1
  src/ManagedServices/test/Remove-AzManagedServicesDefinition.Tests.ps1
  src/ManagedServices/test/loadEnv.ps1
  src/ManagedServices/test/utils.ps1
  src/ManagedServices/utils/Unprotect-SecureString.ps1
  tools/StaticAnalysis/Exceptions/Az.ManagedServices/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.ManagedServices/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#16520 Remove Blockchain from azure-powershell-modules.md
  documentation/azure-powershell-modules.md
Labels: needs-review

#16481 [Aks] Added cmdlet Invoke-AzAksRunCommand
  src/Aks/Aks/Az.Aks.psd1
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/Constants.cs
  src/Aks/Aks/Commands/RunAzureRmAksCommand.cs
  src/Aks/Aks/Models/Mapper.cs
  src/Aks/Aks/Models/PSRunCommandResult.cs
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
  src/Aks/Aks/help/Az.Aks.md
  src/Aks/Aks/help/Invoke-AzAksRunCommand.md
Labels: needs-review

#16517 Example improvement in Databox and EdgeOrder
  src/DataBox/docs/Az.DataBox.md
  src/DataBox/docs/Get-AzDataBoxJob.md
  src/DataBox/docs/Get-AzDataBoxJobCredential.md
  src/DataBox/docs/New-AzDataBoxContactDetailsObject.md
  src/DataBox/docs/New-AzDataBoxDiskJobDetailsObject.md
  src/DataBox/docs/New-AzDataBoxHeavyJobDetailsObject.md
  src/DataBox/docs/New-AzDataBoxJob.md
  src/DataBox/docs/New-AzDataBoxJobDetailsObject.md
  src/DataBox/docs/New-AzDataBoxKeyEncryptionKeyObject.md
  src/DataBox/docs/New-AzDataBoxManagedDiskDetailsObject.md
  src/DataBox/docs/New-AzDataBoxShippingAddressObject.md
  src/DataBox/docs/New-AzDataBoxStorageAccountDetailsObject.md
  src/DataBox/docs/New-AzDataBoxTransferConfigurationObject.md
  src/DataBox/docs/README.md
  src/DataBox/docs/Remove-AzDataBoxJob.md
  src/DataBox/docs/Stop-AzDataBoxJob.md
  src/DataBox/docs/Update-AzDataBoxJob.md
  src/DataBox/examples/New-AzDataBoxJob.md
  src/DataBox/examples/Update-AzDataBoxJob.md
  src/EdgeOrder/docs/New-AzEdgeOrderAddress.md
  src/EdgeOrder/docs/New-AzEdgeOrderItem.md
  src/EdgeOrder/docs/New-AzEdgeOrderPreferencesObject.md
  src/EdgeOrder/docs/Update-AzEdgeOrderAddress.md
  src/EdgeOrder/docs/Update-AzEdgeOrderItem.md
  src/EdgeOrder/examples/New-AzEdgeOrderAddress.md
  src/EdgeOrder/examples/New-AzEdgeOrderItem.md
  src/EdgeOrder/examples/New-AzEdgeOrderPreferencesObject.md
  src/EdgeOrder/examples/Update-AzEdgeOrderAddress.md
  src/EdgeOrder/examples/Update-AzEdgeOrderItem.md
Labels: Waiting for CI :shipit:

#16525 [API Management] Fixed variable reference - Export-AzApiManagementApi
  src/ApiManagement/ApiManagement/help/Export-AzApiManagementApi.md
Labels: Doc - Reference, Waiting for CI :shipit:, customer-reported

#16480 Support multiple regex rules within the same module
  tools/CreateMappings.ps1
  tools/CreateMappings_rules.json
  tools/README.md
Labels: needs-review

#16528 [KeyVault] Rename RBAC properties
  src/KeyVault/KeyVault.Test/PesterTests/ManagedHsmDataPlaneTests.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/RBAC/GetAzureManagedHsmRoleDefinition.cs
  src/KeyVault/KeyVault/Commands/RBAC/NewAzureKeyVaultRoleDefinition.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/PSKeyVaultPermission.cs
  src/KeyVault/KeyVault/Models/RbacExtensions.cs
  src/KeyVault/KeyVault/help/Get-AzKeyVaultRoleDefinition.md
  src/KeyVault/KeyVault/help/New-AzKeyVaultRoleDefinition.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review

#16500 Download Az.Compute from PSGallery
  .azure-pipelines/util/smoke-test-steps.yml
Labels: needs-review

#16460 Cleanup Base64 encoding validation
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Common/ValidateBase64EncodedString.cs
Labels: needs-review

#16495 [Azure Backup] [Breaking Change Release] Replaced BackupManagementType MARS with MAB, added SAPHana workload support for few cmdlets
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/ServiceClientHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureWorkloadSAPHanaDatabaseProtectedItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Enums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Utils.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/PsBackupProviderManager.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/JobAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/Common.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/Common.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/Mab/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/UnregisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJob.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Az.RecoveryServices.md
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupAutoProtection.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupStatus.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupWorkloadRecoveryConfig.md
  src/RecoveryServices/RecoveryServices/help/Unregister-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesVault.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:, Breaking Change Release

#16530 [Aks] Move code to main branch
  src/Aks/Aks.Autorest/Az.Aks.nuspec
  src/Aks/Aks.Autorest/Az.Aks.psd1
  src/Aks/Aks.Autorest/create-model-cmdlets.ps1
  src/Aks/Aks.Autorest/docs/Az.Aks.md
  src/Aks/Aks.Autorest/docs/Get-AzAksNodePoolUpgradeProfile.md
  src/Aks/Aks.Autorest/docs/Get-AzAksUpgradeProfile.md
  src/Aks/Aks.Autorest/docs/Get-AzAksVersion.md
  src/Aks/Aks.Autorest/docs/README.md
  src/Aks/Aks.Autorest/docs/Start-AzAksCluster.md
  src/Aks/Aks.Autorest/docs/Stop-AzAksCluster.md
  src/Aks/Aks.Autorest/generate-info.json
  src/Aks/Aks.Autorest/generated/runtime/BuildTime/Models/PsHelpMarkdownOutputs.cs
  src/Aks/Aks.Autorest/generated/runtime/Customizations/IJsonSerializable.cs
  src/Aks/Aks.Autorest/generated/runtime/UndeclaredResponseException.cs
  src/Aks/Aks.Autorest/license.txt
  src/Aks/Aks.Autorest/resources/README.md
  src/Aks/Aks/Az.Aks.psd1
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/help/Get-AzAksUpgradeProfile.md
  src/Aks/Aks/help/Start-AzAksCluster.md
  src/Aks/Aks/help/Stop-AzAksCluster.md
  tools/StaticAnalysis/Exceptions/Az.Aks/BreakingChangeIssues.csv
Labels: needs-revision

#16535 [ManagedServices] modified version.
  src/ManagedServices/Az.ManagedServices.psd1
  src/ManagedServices/README.md
  src/ManagedServices/test/loadEnv.ps1
Labels: Waiting for CI :shipit:

#16536 [Az.Resources] Create feature registration cmdlets
  src/Resources/ResourceManager/Implementation/Features/GetAzureProviderPreviewFeatureCmdlet.cs
  src/Resources/ResourceManager/Implementation/Features/RegisterAzureProviderPreviewFeatureCmdlet.cs
  src/Resources/ResourceManager/Implementation/Features/UnregisterAzureProviderPreviewFeatureCmdlet.cs
  src/Resources/ResourceManager/Properties/Resources.Designer.cs
  src/Resources/ResourceManager/Properties/Resources.resx
  src/Resources/ResourceManager/SdkClient/ProviderFeatureClient.cs
  src/Resources/ResourceManager/SdkExtensions/ResourcesExtensions.cs
  src/Resources/ResourceManager/SdkModels/Features/PSSubscriptionFeatureRegistration.cs
  src/Resources/Resources.Test/Features/GetAzureProviderPreviewFeatureCmdletTests.cs
  src/Resources/Resources.Test/Features/RegisterAzureProviderPreviewFeatureCmdletTests.cs
  src/Resources/Resources.Test/Features/UnregisterAzureProviderPreviewFeatureCmdletTests.cs
  src/Resources/Resources.Test/ScenarioTests/ProviderFeatureTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ProviderFeatureTests/TestAzureProviderFeature.json
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Az.Resources.md
  src/Resources/Resources/help/Get-AzProviderPreviewFeature.md
  src/Resources/Resources/help/Register-AzProviderPreviewFeature.md
  src/Resources/Resources/help/Unregister-AzProviderPreviewFeature.md
Labels: Waiting for CI :shipit:

#16499 [Synapse]update private endpoint model to sync up with sdk change
  src/Synapse/Synapse/Models/DataPlaneModels/ManagedPrivateEndpoints/PSManagedPrivateEndpointProperties.cs
Labels: Waiting for CI :shipit:

#16471 update new/restore-azsyanpsesqlpool to support Tag and StorageAccountType parameter
  src/Synapse/Synapse.Test/ScenarioTests/Common.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolBackupTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestRestoreFromDroppedSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPool.json
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/RestoreAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/NewAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/ManagementModels/SqlPool/PSSynapseSqlPool.cs
  src/Synapse/Synapse/help/New-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Restore-AzSynapseSqlPool.md
Labels: needs-review

#16534 Add URI parameter to Invoke-AzRestMethod
  src/Accounts/Accounts.Test/InvokeAzRestTests.ps1
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
  src/Accounts/Accounts/help/Invoke-AzRestMethod.md
  src/Accounts/Authentication/Constants.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/Authenticators/Constants.cs
  src/Storage/Storage.Test/File/Cmdlet/NewAzureStorageShareTest.cs
Labels: Waiting for CI :shipit:

#16533 Update New-AzStorageAccountSASToken.md
  src/Storage/Storage.Management/help/New-AzStorageAccountSASToken.md
Labels: Waiting for CI :shipit:

#16478 Reword budget command notes after review
  src/Billing/Billing/help/Get-AzConsumptionBudget.md
  src/Billing/Billing/help/New-AzConsumptionBudget.md
  src/Billing/Billing/help/Remove-AzConsumptionBudget.md
  src/Billing/Billing/help/Set-AzConsumptionBudget.md
Labels: Doc - Reference, Waiting for CI :shipit:

#16491 [Bug Fix] Application Gateway Trusted Client Certificate cmds fails to load entire cert chain from file.
  src/Network/Network.Test/ScenarioTests/Data/TrustedClientCertificate.cer
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDWithMutualAuthentication.json
  src/Network/Network/ApplicationGateway/TrustedClientCertificate/AzureApplicationGatewayTrustedClientCertificateBase.cs
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:

#16540 Misc updates during release
  src/Aks/Aks/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/HDInsight/HDInsight/ChangeLog.md
  src/Network/Network/ChangeLog.md
  src/OperationalInsights/OperationalInsights/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: needs-review
