Repository Azure/azure-powershell, pull requests merged in 2021-12, with the labels that each got.

#16469 [Synapse] Add support for KQL script
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/KqlScripts/ExportAzureSynapseKqlScript.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/KqlScripts/GetAzureSynapseKqlScript.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/KqlScripts/RemoveAzureSynapseKqlScript.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/Artifact/KqlScripts/SetAzureSynapseKqlScript.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/KqlScripts/PSKqlScript.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/KqlScripts/PSKqlScriptContent.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/KqlScripts/PSKqlScriptContentCurrentConnection.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/KqlScripts/PSKqlScriptContentMetadata.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/KqlScripts/PSKqlScriptResource.cs
  src/Synapse/Synapse/Models/DataPlaneModels/Artifact/SynapseAnalyticsArtifactsClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/Synapse.csproj
  src/Synapse/Synapse/help/Export-AzSynapseKqlScript.md
  src/Synapse/Synapse/help/Get-AzSynapseKqlScript.md
  src/Synapse/Synapse/help/New-AzSynapseKqlScript.md
  src/Synapse/Synapse/help/Remove-AzSynapseKqlScript.md
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/Common.Netcore.Dependencies.targets
  tools/StaticAnalysis/Exceptions/Az.Synapse/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#16439 Moving SQL Server and SQL Instance AAD from ActiveDirectoryClient to MicrosoftGraphClient
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Helpers/MSGraphMessageHelper.cs
  src/Sql/Sql/InstanceActiveDirectoryAdministrator/Cmdlet/AzureSqlInstanceActiveDirectoryAdministratorCmdletBase.cs
  src/Sql/Sql/InstanceActiveDirectoryAdministrator/Services/AzureSqlInstanceActiveDirectoryAdministratorAdapter.cs
  src/Sql/Sql/ServerActiveDirectoryAdministrator/Cmdlet/AzureSqlServerActiveDirectoryAdministratorCmdletBase.cs
  src/Sql/Sql/ServerActiveDirectoryAdministrator/Cmdlet/GetAzureSqlServerActiveDirectoryAdministrator.cs
  src/Sql/Sql/ServerActiveDirectoryAdministrator/Services/AzureSqlServerActiveDirectoryAdministratorAdapter.cs
Labels: Waiting for CI :shipit:

#16541 Fix a typo in Update Az-Tags doc where "Repalces" was specified instead of "Replaces"
  src/Resources/Resources/help/Update-AzTag.md
Labels: Waiting for CI :shipit:, customer-reported

#16554 Fixed New-AzVm to not create a PublicIpAddress when it is not provided as a parameter
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMNoPublicIPAddress.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Strategies/Network/NetworkInterfaceStrategy.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Compute - VM, Waiting for CI :shipit:

#16557 Move ContainerInstance to release-2021-12-07
  src/ContainerInstance/Az.ContainerInstance.psd1
  src/ContainerInstance/Changelog.md
  src/ContainerInstance/ContainerInstance.sln
  src/ContainerInstance/README.md
  src/ContainerInstance/generate-info.json
  src/ContainerInstance/generated/api/ContainerInstance.cs
  src/ContainerInstance/generated/cmdlets/StartAzContainerGroup_Start.cs
  src/ContainerInstance/generated/cmdlets/StartAzContainerGroup_StartViaIdentity.cs
Labels: needs-review

#16559 [Az.Resources]Update Get-AzADServicePrincipal.ps1
  src/Resources/MSGraph.Autorest/custom/Get-AzADServicePrincipal.ps1
Labels: Waiting for CI :shipit:

#16546 [Storage] Fixed get container access policy fail when permission in null [#15644]
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/New-AzStorageAccountSASToken.md
  src/Storage/Storage/Common/AccessPolicyHelper.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
Labels: Waiting for CI :shipit:

#16547 Add ZoneRedundant parameter to New-AzSqlDatabaseCopy, New-AzSqlDatabaseSecondary and Restore-AzSqlDatabase
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestCreateRestoreRegularAndZoneRedundantDatabaseWithSourceNotZoneRedundant.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseBackupTests/TestCreateRestoreRegularAndZoneRedundantDatabaseWithSourceZoneRedundant.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateCopyRegularAndZoneRedundantDatabaseWithSourceNotZoneRedundant.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateCopyRegularAndZoneRedundantDatabaseWithSourceZoneRedundant.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateSecondaryRegularAndZoneRedundantDatabaseWithSourceNotZoneRedundant.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateSecondaryRegularAndZoneRedundantDatabaseWithSourceZoneRedundant.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/RestoreAzureRMSqlDatabase.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseCopy.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Model/AzureReplicationLinkModel.cs
  src/Sql/Sql/Replication/Model/AzureSqlDatabaseCopyModel.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabaseCopy.md
  src/Sql/Sql/help/New-AzSqlDatabaseSecondary.md
  src/Sql/Sql/help/Restore-AzSqlDatabase.md
Labels: Waiting for CI :shipit:

#16526 `New-AzAutomationSchedule` provide ability to define the start time with offsets
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClient.cs
  src/Automation/Automation/help/New-AzAutomationSchedule.md
Labels: Waiting for CI :shipit:

#16579 [Kubernetes Configuration] Update custom folder
  src/KubernetesConfiguration/custom/Get-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/custom/New-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/custom/Remove-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/custom/Update-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/docs/Get-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/New-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesExtension.md
  tools/PrepareAutorestModule.ps1
Labels: needs-review

#16585 Typo fix
  src/ServiceBus/ServiceBus/help/Test-AzServiceBusName.md
Labels: Waiting for CI :shipit:, customer-reported

#16591 Add "Thanks to community" section to 7.0 changelog
  .ci-config.json
  ChangeLog.md
Labels: Waiting for CI :shipit:

#16424 Added more example
  src/Compute/Compute/help/Add-AzVmssExtension.md
Labels: needs-review, Service Attention, customer-reported

#16596 Refresh module list
  documentation/azure-powershell-modules.md
Labels: needs-review

#16600 Added example for password credentials
  src/Resources/Resources/help/New-AzADAppCredential.md
Labels: Waiting for CI :shipit:, customer-reported

#16616 [Az.Accounts] Fix the doubled Api Version in Uri of the request issued by Invoke-AzRestMethod
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
Labels: needs-review, customer-reported

#16623 Fixed wrong mapping in help index
  tools/CreateMappings.ps1
Labels: needs-review

#16621 add 'Feature' parameter to New-AzGalleryImageDefinition
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/GalleryImage/GalleryImageCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/Models/PSGalleryImage.cs
  src/Compute/Compute/help/New-AzGalleryImageDefinition.md
Labels: needs-review

#16605 [Az.Resources] Formatted the output format of DeploymentVariable
  src/Resources/ResourceManager/SdkExtensions/ResourcesExtensions.cs
  src/Resources/ResourceManager/SdkModels/Deployments/DeploymentVariable.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-revision

#16598 [Az.KeyVault] Support rotating key in key vault
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Key/InvokeAzureKeyVaultOperation.cs
  src/KeyVault/KeyVault/Commands/Key/KeyRotationPolicy/GetAzKeyVaultKeyRotationPolicy.cs
  src/KeyVault/KeyVault/Commands/Key/KeyRotationPolicy/InvokeAzKeyVaultKeyRotation.cs
  src/KeyVault/KeyVault/Commands/Key/KeyRotationPolicy/UpdateAzKeyVaultKeyRotationPolicy.cs
  src/KeyVault/KeyVault/Commands/Key/KeyVaultKeyCmdletBase.cs
  src/KeyVault/KeyVault/Commands/KeyVaultOnlyKeyCmdletBase.cs
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/Models/IKeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/PSKeyRotationLifetimeAction.cs
  src/KeyVault/KeyVault/Models/PSKeyRotationPolicy.cs
  src/KeyVault/KeyVault/Track2Models/Track2HsmClient.cs
  src/KeyVault/KeyVault/Track2Models/Track2KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Track2Models/Track2ModelConvertionExtensions.cs
  src/KeyVault/KeyVault/Track2Models/Track2VaultClient.cs
  src/KeyVault/KeyVault/help/Get-AzKeyVaultKeyRotationPolicy.md
  src/KeyVault/KeyVault/help/Invoke-AzKeyVaultKeyRotation.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultKeyRotationPolicy.md
Labels: Waiting for CI :shipit:

#16624 Add piping support for -Query in Search-AzGraph
  src/ResourceGraph/ResourceGraph/ChangeLog.md
  src/ResourceGraph/ResourceGraph/Cmdlets/SearchAzureRmGraph.cs
  src/ResourceGraph/ResourceGraph/help/Get-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph/help/New-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph/help/Remove-AzResourceGraphQuery.md
  src/ResourceGraph/ResourceGraph/help/Search-AzGraph.md
  src/ResourceGraph/ResourceGraph/help/Update-AzResourceGraphQuery.md
Labels: Waiting for CI :shipit:

#16634 The Example 2 code is modified. Since there is no parameter available as `-AddCertBinding`
  src/Websites/Websites/help/New-AzWebAppCertificate.md
Labels: Waiting for CI :shipit:, customer-reported

#16633 Added OrdinalIgnoreCase for string comparison of resourceIdentifier type for flowlog cmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkWatcher/FlowLog/FlowLogBaseCmdlet.cs
Labels: needs-review

#16583 Update Set-AzApplicationGatewayFirewallPolicy.md
  src/Network/Network.sln
  src/Network/Network/help/Set-AzApplicationGatewayFirewallPolicy.md
Labels: customer-reported

#16505 Updated Set-AzAutomationModule to use PUT call while updating modules with specific versions
  ChangeLog.md
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.ModuleTests/SetModule.json
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClient.cs
Labels: Waiting for CI :shipit:, customer-reported

#16661 Prepare for Az.MySql and Az.PostgreSql GA
  src/MySql/Az.MySql.psd1
  src/MySql/ChangeLog.md
  src/MySql/Properties/AssemblyInfo.cs
  src/PostgreSql/Az.PostgreSql.psd1
  src/PostgreSql/ChangeLog.md
  src/PostgreSql/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: needs-review

#16669 Powershell cmdlet updates for Resource Mover api-version 2021-08-01
  src/ResourceMover/README.md
  src/ResourceMover/custom/README.md
  src/ResourceMover/docs/Add-AzResourceMoverMoveResource.md
  src/ResourceMover/docs/Get-AzResourceMoverMoveCollection.md
  src/ResourceMover/docs/Get-AzResourceMoverMoveResource.md
  src/ResourceMover/docs/Get-AzResourceMoverUnresolvedDependency.md
  src/ResourceMover/docs/Invoke-AzResourceMoverBulkRemove.md
  src/ResourceMover/docs/Invoke-AzResourceMoverCommit.md
  src/ResourceMover/docs/Invoke-AzResourceMoverDiscard.md
  src/ResourceMover/docs/Invoke-AzResourceMoverInitiateMove.md
  src/ResourceMover/docs/Invoke-AzResourceMoverPrepare.md
  src/ResourceMover/docs/New-AzResourceMoverMoveCollection.md
  src/ResourceMover/docs/README.md
  src/ResourceMover/docs/Remove-AzResourceMoverMoveCollection.md
  src/ResourceMover/docs/Remove-AzResourceMoverMoveResource.md
  src/ResourceMover/docs/Resolve-AzResourceMoverMoveCollectionDependency.md
  src/ResourceMover/examples/Add-AzResourceMoverMoveResource.md
  src/ResourceMover/examples/Get-AzResourceMoverMoveResource.md
  src/ResourceMover/how-to.md
  src/ResourceMover/resources/README.md
  src/ResourceMover/test/Add-AzResourceMoverMoveResource.Recording.json
  src/ResourceMover/test/Add-AzResourceMoverMoveResource.Tests.ps1
  src/ResourceMover/test/Get-AzResourceMoverMoveCollection.Recording.json
  src/ResourceMover/test/Get-AzResourceMoverMoveCollection.Tests.ps1
  src/ResourceMover/test/Get-AzResourceMoverMoveResource.Recording.json
  src/ResourceMover/test/Get-AzResourceMoverRequiredForResources.Recording.json
  src/ResourceMover/test/Get-AzResourceMoverUnresolvedDependency.Recording.json
  src/ResourceMover/test/Invoke-AzResourceMoverBulkRemove.Recording.json
  src/ResourceMover/test/Invoke-AzResourceMoverCommit.Recording.json
  src/ResourceMover/test/Invoke-AzResourceMoverDiscard.Recording.json
  src/ResourceMover/test/Invoke-AzResourceMoverInitiateMove.Recording.json
  src/ResourceMover/test/Invoke-AzResourceMoverPrepare.Recording.json
  src/ResourceMover/test/New-AzResourceMoverMoveCollection.Recording.json
  src/ResourceMover/test/New-AzResourceMoverMoveCollection.Tests.ps1
  src/ResourceMover/test/README.md
  src/ResourceMover/test/Remove-AzResourceMoverMoveCollection.Recording.json
  src/ResourceMover/test/Remove-AzResourceMoverMoveResource.Recording.json
  src/ResourceMover/test/Resolve-AzResourceMoverMoveCollectionDependency.Recording.json
  src/ResourceMover/test/env.json
  src/ResourceMover/test/localEnv.json
Labels: customer-reported, needs-author-feedback

#16437 new example 4/workaround
  src/Network/Network/help/Set-AzNetworkSecurityRuleConfig.md
Labels: Waiting for CI :shipit:, customer-reported

#16637 [CosmosDB] Exposing backup policy migration state
  src/CosmosDB/CosmosDB.Test/ScenarioTests/RestoreTests.cs
  src/CosmosDB/CosmosDB.Test/ScenarioTests/RestoreTests.ps1
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.RestoreTests/TestUpdateCosmosDBAccountBackupPolicyCmdLet.json
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSBackupPolicy.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSBackupPolicyMigrationState.cs
Labels: Waiting for CI :shipit:

#16658 Fixed typo in error message of InvalidWorkspaceResourceId
  src/Network/Network/ChangeLog.md
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#16670 Updated the example command with NodeType param
  src/ServiceFabric/ServiceFabric/help/Remove-AzServiceFabricNodeType.md
Labels: Waiting for CI :shipit:

#16622 [Az.Functions] Remove preview from the PowerShell 7.0 stack on Linux
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
Labels: Waiting for CI :shipit:, Functions

#16675 Deserialized the `Value` in `DeploymentVariable` as object array if its type is Array
  src/Resources/ResourceManager/SdkExtensions/ResourcesExtensions.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#16678 [Aks] Update doc
  src/Aks/Aks/help/New-AzAksCluster.md
Labels: needs-revision

#16650 add a default value for [-AutoPauseDelayInMinute] parameter of command [New-AzSynapseSparkpool] and [Update-AzSynapseSparkpool]
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/NewAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/UpdateAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/help/New-AzSynapseSparkPool.md
  src/Synapse/Synapse/help/Update-AzSynapseSparkPool.md
Labels: Waiting for CI :shipit:

#16674 Update Get-AzDataProtectionOperation.md
  src/DataProtection/help/Get-AzDataProtectionOperation.md
Labels: Waiting for CI :shipit:

#16643 Added new parameters ApplicationSecurityGroup, IpConfiguration, CustomNetworkInterfaceName for Get-AzPrivateEndpoint and New-AzPrivateEndpoint
  src/Network/Network.Test/ScenarioTests/PrivateEndpointTests.cs
  src/Network/Network.Test/ScenarioTests/PrivateEndpointTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PrivateEndpointTests/TestPrivateEndpointApplicationSecurityGroup.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PrivateEndpointTests/TestPrivateEndpointCustomNetworkInterfaceName.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PrivateEndpointTests/TestPrivateEndpointIpConfiguration.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSPrivateEndpoint.cs
  src/Network/Network/Models/PSPrivateEndpointIPConfiguration.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PrivateEndpoint/NewAzurePrivateEndpointCommand.cs
  src/Network/Network/PrivateEndpoint/PrivateEndpointIPConfiguration/NewAzurePrivateEndpointIPConfigurationCommand.cs
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/Get-AzPrivateEndpoint.md
  src/Network/Network/help/New-AzPrivateEndpoint.md
  src/Network/Network/help/New-AzPrivateEndpointIpConfiguration.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-review

#16686 Update Get-AzDataProtectionOperation.md in generation
  src/DataProtection/docs/Get-AzDataProtectionOperation.md
  src/DataProtection/examples/Get-AzDataProtectionOperation.md
Labels: needs-revision

#16613 Support oauth storage context in storage table cmdlets
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Test/Service/MockStorageTableManagement.cs
  src/Storage/Storage.Test/Service/MockStorageTableV2Management.cs
  src/Storage/Storage.Test/Table/GetAzureStorageTableStoredAccessPolicyTest.cs
  src/Storage/Storage.Test/Table/GetAzureStorageTableTest.cs
  src/Storage/Storage.Test/Table/NewAzureStorageTableStoredAccessPolicyTest.cs
  src/Storage/Storage.Test/Table/NewAzureStorageTableTest.cs
  src/Storage/Storage.Test/Table/RemoveAzureStorageTableStoredAccessPolicyTest.cs
  src/Storage/Storage.Test/Table/RemoveAzureStorageTableTest.cs
  src/Storage/Storage.Test/Table/SetAzureStorageTableStoredAccessPolicyTest.cs
  src/Storage/Storage.Test/Table/StorageTableStorageTestBase.cs
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Common/AzureStorageTable.cs
  src/Storage/Storage/Common/Cmdlet/GetAzureStorageCORSRule.cs
  src/Storage/Storage/Common/Cmdlet/GetAzureStorageServiceLogging.cs
  src/Storage/Storage/Common/Cmdlet/GetAzureStorageServiceMetrics.cs
  src/Storage/Storage/Common/Cmdlet/GetAzureStorageServiceProperties.cs
  src/Storage/Storage/Common/Cmdlet/RemoveAzureStorageCORSRule.cs
  src/Storage/Storage/Common/Cmdlet/SetAzureStorageCORSRule.cs
  src/Storage/Storage/Common/Cmdlet/SetAzureStorageServiceLogging.cs
  src/Storage/Storage/Common/Cmdlet/SetAzureStorageServiceMetrics.cs
  src/Storage/Storage/Common/Cmdlet/SetAzureStorageServiceProperties.cs
  src/Storage/Storage/Model/Contract/IStorageTableManagement.cs
  src/Storage/Storage/Model/Contract/StorageTableManagement.cs
  src/Storage/Storage/Model/Contract/StorageTableV2Management.cs
  src/Storage/Storage/Model/ResourceModel/PSCorsRule.cs
  src/Storage/Storage/Model/ResourceModel/PSSeriviceProperties.cs
  src/Storage/Storage/Storage.csproj
  src/Storage/Storage/Table/Cmdlet/GetAzureStorageTableStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/GetStorageAzureTable.cs
  src/Storage/Storage/Table/Cmdlet/NewAzureStorageTableSasToken.cs
  src/Storage/Storage/Table/Cmdlet/NewAzureStorageTableStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/NewStorageAzureTable.cs
  src/Storage/Storage/Table/Cmdlet/RemoveAzureStorageTableStoredAccessPolicy.cs
  src/Storage/Storage/Table/Cmdlet/RemoveStorageAzureTable.cs
  src/Storage/Storage/Table/Cmdlet/SetAzureStorageTableStoredAccessPolicy.cs
  src/Storage/Storage/Table/StorageCloudTableCmdletBase.cs
Labels: Waiting for CI :shipit:

#16693 Add change log for Az.Functions and Az.ResourceMover
  src/Functions/ChangeLog.md
  src/ResourceMover/Changelog.md
Labels: Waiting for CI :shipit:

#16687 Fix update SignalR bugs and add tests
  src/SignalR/SignalR.Test/ScenarioTests/AzureRmSignalRTests.cs
  src/SignalR/SignalR.Test/ScenarioTests/AzureRmSignalRTests.ps1
  src/SignalR/SignalR.Test/ScenarioTests/Common.ps1
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalR.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRSetUpstream.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRUpdate.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRUpdateNetworkAcl.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRWithDefaultArgs.json
  src/SignalR/SignalR/ChangeLog.md
  src/SignalR/SignalR/Cmdlets/UpdateAzureRmSignalR.cs
Labels: Waiting for CI :shipit:

#16632 [DataFactory]Updated ADF .Net SDK version to 5.0.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Waiting for CI :shipit:

#15826 Formatting improvement
  src/Websites/Websites/help/Set-AzWebApp.md
Labels: needs-author-feedback

#16555 Add DiffDiskPlacement parameter to Set-AzVMOSDisk and Set-AzVmssStorageProfile and
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetDiffDiskPlacement.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineDiffDiskPlacement.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMOSDiskCommand.cs
  src/Compute/Compute/help/Set-AzVMOSDisk.md
  src/Compute/Compute/help/Set-AzVmssStorageProfile.md
Labels: Compute - VM, Compute - VMSS

#16683 [Redis] Adding Managed Identity support
  src/RedisCache/RedisCache.Test/RedisCache.Test.csproj
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.cs
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestDiagnosticOperations.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestFirewallRule.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestGeoReplication.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestImportExportReboot.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestManagedIdentity.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCache.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCacheClustering.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePatchSchedules.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePipeline.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestSetNonExistingRedisCacheTest.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZones.json
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Commands/SetAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheAttributes.cs
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
  src/RedisCache/RedisCache/Models/Utility.cs
  src/RedisCache/RedisCache/RedisCache.csproj
  src/RedisCache/RedisCache/RedisCache.format.ps1xml
  src/RedisCache/RedisCache/help/Az.RedisCache.md
  src/RedisCache/RedisCache/help/Export-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCache.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/Get-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Get-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Import-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/New-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheScheduleEntry.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCache.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheDiagnostic.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheFirewallRule.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheLink.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCachePatchSchedule.md
  src/RedisCache/RedisCache/help/Reset-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCacheDiagnostic.md
Labels: Waiting for CI :shipit:

#16702 Add -Force to Move-Item to skip the error of file exist.
  tools/PrepareAutorestModule.ps1
Labels: Waiting for CI :shipit:

#16709 Prepare for synapse GA
  src/Synapse/Synapse/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: needs-review

#16710 Polish change log
  src/Automation/Automation/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/KeyVault/KeyVault/ChangeLog.md
  src/Network/Network/ChangeLog.md
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#16590 Use case-insensitive comparison for ResourceId (Set/New-NetworkWatcherFlowLog)
  src/Network/Network/ChangeLog.md
Labels: needs-revision, Waiting for CI :shipit:

#16699 Principal typo (was princial)
  src/Resources/Resources/help/New-AzADServicePrincipal.md
Labels: Waiting for CI :shipit:, customer-reported

#16696 [Blueprint] Fix cmdlet used in Set-AzBlueprintArtifact doc examples
  src/Blueprint/Blueprint.sln
  src/Blueprint/Blueprint/help/Set-AzBlueprintArtifact.md
Labels: Waiting for CI :shipit:

#16713 Migrate Azure AD features in Az.Synapse to MSGraph API
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Models/DataPlaneModels/AccessControl/SynapseAnalyticsRoleClient.cs
  src/Synapse/Synapse/Models/ManagementModels/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/help/Get-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/New-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Remove-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Set-AzSynapseSqlActiveDirectoryAdministrator.md
Labels: Waiting for CI :shipit:

#16706 Updated help message and help markdown for parameter Tenant of cmdlet Set-AzContext
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Context/SetAzureRMContext.cs
  src/Accounts/Accounts/help/Set-AzContext.md
Labels: Waiting for CI :shipit:

#16728 Fix UserData metadata so piping occurs correctly
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Common/ValidateBase64EncodedString.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMGetMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMUpdateMethod.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/Get-AzVM.md
  src/Compute/Compute/help/Get-AzVmss.md
  src/Compute/Compute/help/Get-AzVmssVM.md
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Update-AzVM.md
  src/Compute/Compute/help/Update-AzVmss.md
  src/Compute/Compute/help/Update-AzVmssVM.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:, Breaking Change Release
