Repository Azure/azure-powershell, pull requests merged in 2021-09, with the labels that each got.

#15796 Update enable-subscription-id-overriding.md with limitations
  documentation/development-docs/enable-subscription-id-overriding.md
Labels: Doc - Internal, needs-review

#15804 Update New-AzOperationalInsightsWorkspace.md
  src/OperationalInsights/OperationalInsights/help/New-AzOperationalInsightsWorkspace.md
Labels: customer-reported

#15808 Recode Example2
  src/Resources/Resources/help/New-AzADAppCredential.md
Labels: customer-reported

#15846 Update Set-AzNetworkInterfaceIpConfig.md
  src/Network/Network/help/Set-AzNetworkInterfaceIpConfig.md
Labels: customer-reported

#15835 Fixed trigger schedule client
  src/DataProtection/custom/Cmdlets/Policy/New-AzDataProtectionPolicyTriggerScheduleClientObject.ps1
Labels: needs-review

#15852 [FrontDoor] New-AzFrontDoorRulesEngineActionObject: Allow rule engine action creation without RouteConfigurationOverride and fix DynamicCompression parameter being ignored issue
  src/FrontDoor/FrontDoor.Test/ScenarioTests/FrontDoorTests.cs
  src/FrontDoor/FrontDoor.Test/ScenarioTests/FrontDoorTests.ps1
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.FrontDoorTests/TestFrontDoorRulesEngineCrud.json
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewFrontDoorRulesEngineActionObject.cs
  src/FrontDoor/FrontDoor/Common/AzureFrontDoorCmdletBase.cs
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
  src/FrontDoor/FrontDoor/Models/PSRouteConfiguration.cs
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorRulesEngineActionObject.md
  tools/StaticAnalysis/Exceptions/Az.FrontDoor/SignatureIssues.csv
Labels: needs-revision

#15858 Onboarding ARM to the Private Link Common Cmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: needs-revision

#15837 [Synapse] Add synapse Integration Runtime commands
  src/Synapse/Synapse.Test/ScenarioTests/IntegrationRuntimeTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestAzureSSISIntegrationRuntime.json
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/StartAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/StopAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseManagementCmdletBase.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Start-AzSynapseIntegrationRuntime.md
  src/Synapse/Synapse/help/Stop-AzSynapseIntegrationRuntime.md
Labels: needs-revision

#15823 [Synapse] Update version of reference package to use stable api version
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolV3Tests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestAuditOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestAuditOnWorkspace.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditDisableSqlPoolAudit.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditDisableWorkspaceAudit.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditFailWithBadSqlPoolIndentity.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditFailWithBadWorkspaceIndentity.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditOnWorkspace.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditSqlPoolRetentionKeepProperties.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditSqlPoolStorageKeyRotation.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditSqlPoolUpdatePolicyKeepPreviousStorage.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditSqlPoolUpdatePolicyWithStorage.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditWorkspaceRetentionKeepProperties.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditWorkspaceStorageKeyRotation.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditWorkspaceUpdatePolicyKeepPreviousStorage.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestBlobAuditWorkspaceUpdatePolicyWithStorage.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestExtendedAuditOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestExtendedAuditOnWorkspace.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestNewSqlPoolAuditDiagnosticsAreCreatedOnNeed.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestNewWorkspaceAuditDiagnosticsAreCreatedOnNeed.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestRemoveAuditOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestRemoveAuditOnWorkspace.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestRemoveSqlPoolAuditingSettingsMultipleDiagnosticSettings.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.AuditTests/TestRemoveWorkspaceAuditingSettingsMultipleDiagnosticSettings.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.DataClassificationTests/TestDataClassificationOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.DataClassificationTests/TestEnableDisableRecommendationsOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.FirewallTests/TestSynapseFirewall.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestAzureIntegrationRuntime.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestAzureSSISIntegrationRuntime.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestIntegrationRuntimePiping.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestSelfHostedIntegrationRuntime.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SparkPoolTests/TestSynapseSparkPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlDatabaseTests/TestSynapseSqlDatabase.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestDroppedSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestRestoreFromRestorePoint.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestSqlPoolRestorePoint.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPoolSecurity.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolV3Tests/TestSynapseSqlPoolV3.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentBaseline.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentScanConvertTest.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentScanRecordGetListTest.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseManagedIdentitySqlControlSetting.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseWorkspace.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseWorkspaceSecurity.json
  src/Synapse/Synapse.Test/Synapse.Test.csproj
  src/Synapse/Synapse.sln
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkSession/StartAzureSynapseSparkSession.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/SparkStatement/InvokeAzureSynapseSparkStatement.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsSparkClient.cs
  src/Synapse/Synapse/Synapse.csproj
Labels: needs-review

#15886 Reworded sentence to make it clear that a specific key version must b…
  src/KeyVault/KeyVault/help/Get-AzKeyVaultKey.md
Labels: customer-reported

#15892 Azure Site Recovery - Minor bug fixes
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2ARCM/AsrV2ARcmTests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2ARCM/AsrV2ARcmTests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ARCMTests/TestV2ARCM540Reprotect.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/RemoveAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/UpdateAzureRmRecoveryServicesAsrProtectionDirection.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review, bug, customer-reported

#15897 Fixed changelog
  src/Batch/Batch.Test/Batch.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/ContainerRegistry/ContainerRegistry.Test/ContainerRegistry.Test.csproj
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HPCCache/HPCCache.Test/HPCCache.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/ScenarioTests/BastionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallVirtualHubAllocateDeallocated.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallVirtualHubCRUDWithZones.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionIpObjectParam.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionVnetObjectParam.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionVnetsIpObjectsParams.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/BYOIP/CustomIpPrefix/NewAzureCustomIpPrefixCommand.cs
  src/Network/Network/BYOIP/CustomIpPrefix/UpdateAzureCustomIpPrefixCommand.cs
  src/Network/Network/Bastion/BastionBaseCmdlet.cs
  src/Network/Network/Bastion/NewAzBastionCommand.cs
  src/Network/Network/Bastion/SetAzBastionCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/Models/BYOIP/PSCustomIpPrefix.cs
  src/Network/Network/Models/Bastion/PSBastion.cs
  src/Network/Network/Models/Bastion/PSBastionSku.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
  src/Network/Network/help/Get-AzCustomIpPrefix.md
  src/Network/Network/help/New-AzBastion.md
  src/Network/Network/help/New-AzCustomIpPrefix.md
  src/Network/Network/help/New-AzPublicIpAddress.md
  src/Network/Network/help/Set-AzBastion.md
  src/Network/Network/help/Set-AzFirewall.md
  src/Network/Network/help/Update-AzCustomIpPrefix.md
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SignalR/SignalR.Test/SignalR.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-revision

#15918 Fix multi-regional examples
  src/Compute/Compute/help/New-AzGalleryImageVersion.md
Labels: customer-reported

#15921 Remove duplicated .props file reference in csproj
  src/Synapse/Synapse.Autorest/Az.Synapse.csproj
Labels: Waiting for CI :shipit:

#15260 Add new parameter to enable/disable BGP route translation for NAT VirtualWan VpnGateway
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestP2SCortexCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/P2SVpnGateway/NewAzureRmP2sVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/NewAzureRmVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/UpdateAzureRmVpnGatewayCommand.cs
  src/Network/Network/Models/Cortex/PSVpnGateway.cs
  src/Network/Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzP2sVpnGateway.md
  src/Network/Network/help/New-AzVpnGateway.md
  src/Network/Network/help/Update-AzP2sVpnGateway.md
  src/Network/Network/help/Update-AzVpnGateway.md
Labels: needs-author-feedback, Waiting for Cmdlet Review Completion

#15928 Fix daily smoke test
  src/Accounts/Accounts/ChangeLog.md
Labels: needs-review

#15878 [DataFlow] add additional cmd parameter for quick reuse of cluster fo…
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/IntegrationRuntimes/SetAzureDataFactoryIntegrationRuntimeCommand.cs
  src/DataFactory/DataFactoryV2/Models/PSManagedIntegrationRuntime.cs
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2IntegrationRuntime.md
Labels: needs-revision

#15935 Fix wrong encoding in *-AzVirtualHubRoute*.md
  src/Network/Network/help/Add-AzVirtualHubRoute.md
  src/Network/Network/help/Add-AzVirtualHubRouteTable.md
  src/Network/Network/help/Get-AzVirtualHubRouteTable.md
  src/Network/Network/help/Remove-AzVirtualHubRouteTable.md
Labels: Doc - Reference, needs-review

#15934 Sign AuthenticationAssemblyLoadContext.dll in daily build
  .azure-pipelines/daily-build.yml
Labels: Waiting for CI :shipit:

#15933 Add Az.Attestation module to Az
  src/Attestation/Attestation/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: needs-review

#15941 Use last PowerState instance in Statuses for power status
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
Labels: customer-reported

#15945 [Storage] Support new SRP features on new API version 2021-06-01
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountEnableNfsV3.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestSetAzureStorageAccount.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageBlobInventory.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerImmutabilityPolicy.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerLegalHold.json
  src/Storage/Storage.Management/Blob/AddAzureStorageContainerLegalHold.cs
  src/Storage/Storage.Management/Blob/NewAzureStorageContainer.cs
  src/Storage/Storage.Management/Blob/SetAzureStorageContainerImmutabilityPolicy.cs
  src/Storage/Storage.Management/Blob/UpdateAzureStorageContainer.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSBlobInventoryPolicy.cs
  src/Storage/Storage.Management/Models/PSContainer.cs
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageBlobInventoryPolicyRule.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/Add-AzRmStorageContainerLegalHold.md
  src/Storage/Storage.Management/help/New-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageBlobInventoryPolicyRule.md
  src/Storage/Storage.Management/help/Set-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Update-AzRmStorageContainer.md
  src/StorageSync/StorageSync.Test/StorageSync.Test.csproj
Labels: needs-review

#15957 Azure Site Recovery - Minor bug fixes in Update policy
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review, bug, customer-reported

#15962 [Accounts] Add debug message to ALC
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/StartupScripts/InitializeAssemblyResolver.ps1
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContext.cs
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  tools/PostBuildModuleAlc.ps1
Labels: needs-review
