Repository Azure/azure-powershell, pull requests merged in 2021-03, with the labels that each got.

#14350 Upgrade build script using 7.2.0
  .azure-pipelines/sign-tool-predictor.yml
Labels: Az.Tools.Predictor

#14300 IoT Hub SDK upgrade and test updates
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/DeviceProvisioningServices.Test.csproj
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsAccessPolicyTests/IotDpsAccessPolicyLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsEnrollmentGroupTests/IotDpsEnrollmentGroupLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsEnrollmentTests/IotDpsEnrollmentLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsLinkedHubTests/IotDpsLinkedHubLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsRegistrationTests/IotDpsRegistrationLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsTests/IotDpsLifeCycle.json
  src/IotHub/IotHub.Test/IotHub.Test.csproj
  src/IotHub/IotHub.Test/ScenarioTests/IotHubController.cs
  src/IotHub/IotHub.Test/ScenarioTests/IotHubDPModuleTests.ps1
  src/IotHub/IotHub.Test/ScenarioTests/IotHubRoutingTests.ps1
  src/IotHub/IotHub.Test/ScenarioTests/IotHubTests.ps1
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPConfigurationTests/TestAzureIotHubConfigurationLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPDeviceTests/TestAzureIotHubDeviceLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPModuleTests/TestAzureIotHubModuleLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPTracingTests/TestAzureIotHubTracing.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubRoutingTests/TestAzureIotHubRoutingLifeCycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubTests/TestAzureIotHubLifeCycle.json
  src/IotHub/IotHub.sln
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/IotHub.csproj
  src/IotHub/IotHub/IotHub/AddAzureRmIotHubCertificate.cs
  src/IotHub/IotHub/IotHub/DataPlane/Device/GetAzIotHubDeviceConnectionString.cs
  src/IotHub/IotHub/IotHub/DataPlane/Module/GetAzIotHubModuleConnectionString.cs
  src/IotHub/IotHub/IotHub/DataPlane/NewAzIotHubSasToken.cs
  src/IotHub/IotHub/IotHub/ManualFailover/InvokeAzureRmIotHubManualFailover.cs
  src/IotHub/IotHub/IotHub/SetAzureRmIotHubVerifiedCertificate.cs
  src/IotHub/IotHub/IotHub/UpdateAzureRmIotHub.cs
  src/IotHub/IotHub/Models/PSCapabilities.cs
Labels: needs-revision

#14386 Correct psd1 file and remove space charactor from tag
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
Labels: Az.Tools.Predictor

#14353 [AzureStack] Remove EnforcementMode from Policy
  .azure-pipelines/util/build-steps.yml
  .azure-pipelines/util/publish-artifacts-steps.yml
  .azure-pipelines/util/test-steps.yml
  NuGet.Config
  src/Resources/ResourceManager/Entities/Policy/PolicyAssignmentProperties.cs
  src/Resources/ResourceManager/Implementation/Policy/NewAzurePolicyAssignment.cs
  src/Resources/ResourceManager/Implementation/Policy/PsPolicyAssignmentProperties.cs
  src/Resources/ResourceManager/Implementation/Policy/SetAzurePolicyAssignment.cs
  tools/CheckIgnoredFile.ps1
  tools/NetCoreCsProjSync/NuGet.Config
  tools/NetCorePsd1Sync/NuGet.Config
Labels: needs-revision

#14255 [ImageBuilder] Add feature for ImageBuilder
  src/ImageBuilder/custom/New-AzImageBuilderCustomizerObject.ps1
  src/ImageBuilder/custom/New-AzImagerBuilderTemplate.ps1
  src/ImageBuilder/docs/Az.ImageBuilder.md
  src/ImageBuilder/docs/New-AzImageBuilderCustomizerObject.md
  src/ImageBuilder/docs/New-AzImageBuilderTemplate.md
  src/ImageBuilder/readme.md
  src/ImageBuilder/test/New-AzImageBuilderTemplate.Tests.ps1
  src/ImageBuilder/test/NewSourceObjectFromJsonObject.Tests.ps1
  src/ImageBuilder/test/deployment-templates/Linux-image/linux.json
Labels: Generator

#14373 Fix PVS-Studio issues related to 'Recoveryservices'
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSFabricDetails.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/StartAzureRmRecoveryServicesAsrTestFailoverJob.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/StartAzureRmRecoveryServicesAsrUnPlannedFailover.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/UpdateAzureRmRecoveryServicesAsrProtectionDirection.cs
Labels: Recovery Services Site-Recovery

#14422 [Az.RedisEnterpriseCache] Update Get-AzRedisEnterpriseCache to allow to ListBySubscriptionId
  src/RedisEnterpriseCache/custom/Get-AzRedisEnterpriseCache.ps1
  src/RedisEnterpriseCache/docs/Get-AzRedisEnterpriseCache.md
  src/RedisEnterpriseCache/examples/Get-AzRedisEnterpriseCache.md
  src/RedisEnterpriseCache/test/Get-AzRedisEnterpriseCache.Recording.json
  src/RedisEnterpriseCache/test/Get-AzRedisEnterpriseCache.Tests.ps1
  src/RedisEnterpriseCache/test/Get-AzRedisEnterpriseCacheDatabase.Recording.json
  src/RedisEnterpriseCache/test/Get-AzRedisEnterpriseCacheKey.Recording.json
  src/RedisEnterpriseCache/test/New-AzRedisEnterpriseCache.Recording.json
  src/RedisEnterpriseCache/test/New-AzRedisEnterpriseCache.Tests.ps1
  src/RedisEnterpriseCache/test/New-AzRedisEnterpriseCacheDatabase.Recording.json
  src/RedisEnterpriseCache/test/New-AzRedisEnterpriseCacheKey.Recording.json
  src/RedisEnterpriseCache/test/Remove-AzRedisEnterpriseCache.Recording.json
  src/RedisEnterpriseCache/test/Remove-AzRedisEnterpriseCacheDatabase.Recording.json
  src/RedisEnterpriseCache/test/env.json
Labels: needs-review

#14417 Remove resource group from get-azloadbalancer this results in a regio…
  src/Network/Network/help/Set-AzLoadBalancer.md
Labels: customer-reported

#14447 [CloudService]Fix the issues of CloudService tests
  src/CloudService/test/Get-AzCloudServiceRoleInstanceRemoteDesktopFile.Recording.json
  src/CloudService/test/Get-AzCloudServiceRoleInstanceRemoteDesktopFile.Tests.ps1
  src/CloudService/test/env.json
Labels: Generator

#14432 Update Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline.md
  src/Sql/Sql/help/Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline.md
Labels: customer-reported

#14452 [CloudService] Update SecurityTools config
  tools/SecurityTools/CredScanSuppressions.json
  tools/SecurityTools/PoliCheckFileExtensions.xml
Labels: Generator

#14480 [BotService] Fix the issue that not package resource folder
  src/BotService/readme.md
Labels: Generator

#14368 Fix PVS-Studio issues related to 'DataFactory'
  src/DataFactory/DataFactories/Models/DataFactoryClient.Encrypt.cs
Labels: Data Factory

#14163 [Az.RecoveryServices.Backup] Adding Cross Zonal Restore for Zone-pinned VMs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/RecoveryServices.Backup.Helpers.csproj
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Enums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Models/RecoveryServices.Backup.Models.csproj
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/RecoveryServices.Backup.Providers.csproj
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/OperationStatusAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/RecoveryServices.Backup.ServiceClientAdapter.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/JobTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/GetAzureVmWorkloadContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVMGetContainers.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRSVaultMSI.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureUnmanagedVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMCrossRegionRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMDiskExclusion.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetItems.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMRPMountScript.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMSetVaultContext.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureFSGetJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMCancelJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobsTimeFilter.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMWaitJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ProtectionCheckTests/TestAzureFSProtectionCheck.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.Test/RecoveryServices.Test.csproj
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: needs-review

#14321 Adding Server Trust Group cmdlets
  src/Sql/Sql.Test/ScenarioTests/ServerTrustGroupTests.cs
  src/Sql/Sql.Test/ScenarioTests/ServerTrustGroupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerTrustGroupTests/TestServerTrustGroup.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/ServerTrustGroup/Cmdlet/AzureSqlServerTrustGroupCmdletBase.cs
  src/Sql/Sql/ServerTrustGroup/Cmdlet/GetAzureSqlServerTrustGroup.cs
  src/Sql/Sql/ServerTrustGroup/Cmdlet/NewAzureSqlServerTrustGroup.cs
  src/Sql/Sql/ServerTrustGroup/Cmdlet/RemoveAzureSqlServerTrustGroup.cs
  src/Sql/Sql/ServerTrustGroup/Model/AzureSqlServerTrustGroupModel.cs
  src/Sql/Sql/ServerTrustGroup/Services/AzureSqlServerTrustGroupAdapter.cs
  src/Sql/Sql/ServerTrustGroup/Services/AzureSqlServerTrustGroupCommunicator.cs
  src/Sql/Sql/help/Az.Sql.md
  src/Sql/Sql/help/Get-AzSqlServerTrustGroup.md
  src/Sql/Sql/help/New-AzSqlServerTrustGroup.md
  src/Sql/Sql/help/Remove-AzSqlServerTrustGroup.md
Labels: needs-revision

#14513 [BotService] Move template files to custom folder
  src/BotService/custom/Initialize-AzBotServicePrepareDeploy.ps1
  src/BotService/custom/New-AzBotService.ps1
  src/BotService/custom/typescript.web.config
  src/BotService/custom/web.config
  src/BotService/custom/webappv4.template.json
Labels: Generator

#14443 [KeyVault] support async API design of security domain
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/BackupSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/RestoreSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/SecurityDomainCmdlet.cs
  src/KeyVault/KeyVault/SecurityDomain/Common/AsyncHelper.cs
  src/KeyVault/KeyVault/SecurityDomain/Common/Utils.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/ISecurityDomainClient.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomainClient.cs
Labels: needs-review

#14515 Unkown parameter
  src/Sql/Sql/help/Restore-AzSqlDatabase.md
Labels: customer-reported

#14496 [BotService] Update BotService
  src/BotService/Az.BotService.psd1
  src/BotService/Changelog.md
  src/BotService/custom/Export-AzBotServiceApp.ps1
  src/BotService/custom/Initialize-AzBotServicePrepareDeploy.ps1
  src/BotService/custom/New-AzBotService.ps1
  src/BotService/custom/Publish-AzBotServiceApp.ps1
  src/BotService/custom/typescript.web.config
  src/BotService/custom/web.config
  src/BotService/custom/webappv4.template.json
  src/BotService/exports/Export-AzBotServiceApp.ps1
  src/BotService/exports/Get-AzBotService.ps1
  src/BotService/exports/Initialize-AzBotServicePrepareDeploy.ps1
  src/BotService/exports/New-AzBotService.ps1
  src/BotService/exports/ProxyCmdletDefinitions.ps1
  src/BotService/exports/Publish-AzBotServiceApp.ps1
  src/BotService/exports/Remove-AzBotService.ps1
  src/BotService/exports/Update-AzBotService.ps1
  src/BotService/generate-info.json
  src/BotService/generated/runtime/BuildTime/Cmdlets/ExportPsd1.cs
  src/BotService/generated/runtime/BuildTime/Models/PsHelpMarkdownOutputs.cs
  src/BotService/generated/runtime/BuildTime/Models/PsProxyTypes.cs
  src/BotService/generated/runtime/PipelineMocking.cs
  src/BotService/internal/Get-AzBotCheckNameAvailability.ps1
  src/BotService/internal/Get-AzOperation.ps1
  src/BotService/internal/New-AzBotService.ps1
  src/BotService/internal/ProxyCmdletDefinitions.ps1
  src/BotService/readme.md
Labels: Generator

#14488 [Acr] Added support for Acr LoginServers
  .ci-config.json
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestAzRmHealthcareApisService.json
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestPrivateEndpointConnection.json
  src/HealthcareApis/HealthcareApis.Test/SessionRecords/Microsoft.Azure.Commands.HealthcareApisService.Test.ScenarioTests.HealthcareApisServiceTests/TestPublicNetworkAccessControl.json
  src/HealthcareApis/HealthcareApis/Az.HealthcareApis.psd1
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/HealthcareApis/AddAzureRmHealthcareapisAcrLoginServer.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/NewAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/RemoveAzureRmHealthcareapisAcrLoginServer.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/ResetAzureRmHealthcareapisAcrLoginServer.cs
  src/HealthcareApis/HealthcareApis/HealthcareApis/SetAzureRmHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisFhirServiceAcrConfig.cs
  src/HealthcareApis/HealthcareApis/Models/PSHealthcareApisService.cs
  src/HealthcareApis/HealthcareApis/help/Add-AzHealthcareApisAcrLoginServer.md
  src/HealthcareApis/HealthcareApis/help/Az.HealthcareApis.md
  src/HealthcareApis/HealthcareApis/help/New-AzHealthcareApisService.md
  src/HealthcareApis/HealthcareApis/help/Remove-AzHealthcareApisAcrLoginServer.md
  src/HealthcareApis/HealthcareApis/help/Reset-AzHealthcareApisAcrLoginServer.md
  src/HealthcareApis/HealthcareApis/help/Set-AzHealthcareApisService.md
  src/Websites/Websites.Test/ScenarioTests/AppServiceEnvironmentTests.cs
  tools/LocalFeed/Microsoft.Azure.Management.HealthcareApis.3.0.1.nupkg
  tools/StaticAnalysis/Exceptions/Az.Sql/SignatureIssues.csv
  tools/StaticAnalysis/IssueChecker/IssueChecker.cs
  tools/StaticAnalysis/ReportRecordFactory.cs
Labels: needs-revision

#14535 Fix invalid SAS token from New-AzServiceBusAuthorizationRuleSASToken and New-AzEventHubAuthorizationRuleSASToken
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/AuthorizationRule/NewAzureEventhubAuthorizationRuleSASToken.cs
  src/ServiceBus/ServiceBus/ChangeLog.md
  src/ServiceBus/ServiceBus/Cmdlets/AuthorizationRule/NewAzureServiceBusAuthorizationRuleSASToken.cs
Labels: customer-reported

#14138 Azure Firewall - Data PIP removal for FT firewal
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallNoDataPip.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/help/New-AzFirewall.md
Labels: Waiting for CI :shipit:

#14531 Update Cloud Shell image in README.md
  README.md
Labels: Waiting for CI :shipit:

#14479 [Compute] Adding Set-AzVmUefi, Set-AzVmssUefi, Set-AzVmSecurityType, Set-AzVmssSecurityType to support Trusted Launch
  ChangeLog.md
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineProfileTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetProfileTests.ps1
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssSecurityTypeCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssUefiCommand.cs
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMSecurityType.cs
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMUefi.cs
  src/Compute/Compute/help/Set-AzVMSecurityType.md
  src/Compute/Compute/help/Set-AzVMUefi.md
  src/Compute/Compute/help/Set-AzVmssSecurityType.md
  src/Compute/Compute/help/Set-AzVmssUefi.md
  tools/StaticAnalysis/Exceptions/Az.Compute/SignatureIssues.csv
Labels: needs-revision

#14328 Fixed what-if functionality with -QueryString parameter
  NuGet.Config
  README.md
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentCreateCmdlet.cs
  src/Resources/ResourceManager/SdkModels/Deployments/PSDeploymentWhatIfCmdletParameters.cs
  src/Resources/Resources.Test/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCommandTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.ps1
  src/Resources/Resources.Test/ScenarioTests/ResourceTestRunner.cs
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentWithQueryString.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestWhatIfWithQueryString.json
  src/Resources/Resources.Test/sampleLinkedTemplateChild.json
  src/Resources/Resources.Test/sampleLinkedTemplateParent.json
  src/Resources/Resources/ChangeLog.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: needs-revision

#14573 Revert the version change in Az.Resources.psd1
  src/Resources/Resources/Az.Resources.psd1
Labels: Do Not Merge :no_entry_sign:

#14575 Fix typo
  src/Aks/Aks/help/Az.Aks.md
Labels: Waiting for CI :shipit:, customer-reported

#14601 [Synapse] - New-AzSynapseFirewallRule correct IP ranges for -AllowAllAzureIp and -AllowAllIp
  src/Synapse/Synapse.Test/ScenarioTests/FirewallTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.FirewallTests/TestSynapseFirewall.json
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/Firewall/NewAzureSynapseFirewallRule.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/help/New-AzSynapseFirewallRule.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/BreakingChangeIssues.csv
Labels: needs-revision

#14584 support subscription diagnosticsetting
  src/Monitor/Monitor.Test/Diagnostics/SetDiagnosticSettingCommandTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AzureRmDiagnosticSettingTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AzureRmDiagnosticSettingTests.ps1
  src/Monitor/Monitor/Az.Monitor.psd1
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/Diagnostics/DiagnosticSettingCommandBase.cs
  src/Monitor/Monitor/Diagnostics/GetAzureRMSubscriptionDiagnosticSettingCategoryCommand.cs
  src/Monitor/Monitor/Diagnostics/GetAzureRmDiagnosticSettingCategoryCommand.cs
  src/Monitor/Monitor/Diagnostics/GetAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/NewAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/RemoveAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/SetAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/OutputClasses/PSDiagnosticSettingCategory.cs
  src/Monitor/Monitor/OutputClasses/PSSubscriptionDiagnosticSettingCategory.cs
  src/Monitor/Monitor/Utilities.cs
  src/Monitor/Monitor/help/Az.Monitor.md
  src/Monitor/Monitor/help/Get-AzDiagnosticSetting.md
  src/Monitor/Monitor/help/Get-AzSubscriptionDiagnosticSettingCategory.md
  src/Monitor/Monitor/help/New-AzDiagnosticSetting.md
  src/Monitor/Monitor/help/Remove-AzDiagnosticSetting.md
  src/Monitor/Monitor/help/Set-AzDiagnosticSetting.md
Labels: needs-review

#14603 Update Invoke-AzSqlInstanceFailover.md
  src/Sql/Sql/help/Invoke-AzSqlInstanceFailover.md
Labels: Service Attention, Waiting for CI :shipit:, customer-reported

#14613 Onboard DigitalTwins to Private Link Common Cmdlets
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#14412 Remove duplicated utility class Base64UrlEncoder
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
  src/Accounts/Accounts/Utilities/Base64UrlHelpers.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/Base64UrlEncoder.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/CertKeys.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/JWE.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/JWK.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomainClient.cs
Labels: Waiting for CI :shipit:

#14577 Adding Private Range (No SNAT) Support to Firewall Policies
  src/Network/Network.Test/ScenarioTests/AzureFirewallPolicyTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallPolicyTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallPolicyTests/TestAzureFirewallPolicyPrivateRangeCRUD.json
  src/Network/Network/AzureFirewallPolicy/NewAzureFirewallPolicyCommand.cs
  src/Network/Network/AzureFirewallPolicy/SetAzureFirewallPolicyCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewallPolicy/PSAzureFirewallPolicy.cs
  src/Network/Network/Models/AzureFirewallPolicy/PSAzureFirewallPolicySNAT.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/New-AzFirewallPolicy.md
  src/Network/Network/help/Set-AzFirewallPolicy.md
Labels: needs-revision

#14635 feat: support "automitigate" parameter
  src/Monitor/Monitor.Test/Alerts/AddAzureRmMetricAlertRuleV2Tests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/AlertsTests.ps1
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.AlertsTests/TestAddAzureRmMetricAlertRuleV2WithAutoMitigate.json
  src/Monitor/Monitor/Alerts/AddAzureRmMetricAlertRuleV2Command.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/help/Add-AzMetricAlertRuleV2.md
Labels: Waiting for CI :shipit:
