Repository Azure/azure-powershell, pull requests merged in 2021-05, with the labels that each got.

#14852 Updated example 3 to use correct parameter
  src/Accounts/Accounts/help/Get-AzAccessToken.md
Labels: customer-reported

#14858 Update New-AzVirutalNetworkGatewayConnection Ex 1
  src/Network/Network/help/New-AzIpsecTrafficSelectorPolicy.md
Labels: customer-reported

#14839 Updated templateSpecs cmdlets to use new SDK
  src/DeploymentManager/DeploymentManager.Test/DeploymentManager.Test.csproj
  src/Resources/ResourceManager/Components/TemplateSpecPackagingEngine.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/ResourceWithParameterCmdletBase.cs
  src/Resources/ResourceManager/Implementation/TemplateSpecs/NewAzTemplateSpec.cs
  src/Resources/ResourceManager/Implementation/TemplateSpecs/SetAzTemplateSpec.cs
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/SdkClient/TemplateSpecsSdkClient.cs
  src/Resources/ResourceManager/SdkModels/TemplateSpecs/PSTemplateSpecArtifact.cs
  src/Resources/ResourceManager/SdkModels/TemplateSpecs/PSTemplateSpecVersion.cs
  src/Resources/Resources.Test/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCommandTests.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/TemplateSpecTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentTemplateSpec.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewFailedSubscriptionDeploymentTemplateSpec.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewMGDeploymentTemplateSpec.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewSubscriptionDeploymentTemplateSpec.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewTenantDeploymentTemplateSpec.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/NewTemplateSpec_Tags_AppliesInheritedTagsIfNoTagsSuppliedAndSpecExists.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/NewTemplateSpec_Tags_AppliesTagsToBothTemplateSpecAndVersionIfNotExist.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/NewTemplateSpec_Tags_AppliesTagsToOnlyVersionIfTemplateSpecExists.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/NewTemplateSpec_Tags_RemovesTagsFromExistingVersionIfTagsExplicityEmpty.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/SetTemplateSpec_Tags_AppliesInheritedTagsIfNewVersionAndNoTagsProvidedAndSpecExists.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/SetTemplateSpec_Tags_AppliesTagsOnlyToVersionIfVersionSpecified.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/SetTemplateSpec_Tags_AppliesTagsToBothTemplateSpecAndVersionIfNotExist.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/SetTemplateSpec_Tags_AppliesTagsToTemplateSpecIfNoVersionSpecified.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/SetTemplateSpec_Tags_RemovesTagsIfTagsExplicitlyEmpty.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/TestTemplateSpecCreate.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/TestTemplateSpecGet.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/TestTemplateSpecRemoval.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.TemplateSpecTests/TestTemplateSpecSet.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Resources.csproj
  src/Resources/Resources/Resources.format.ps1xml
  src/Resources/Resources/help/New-AzTemplateSpec.md
  src/Resources/Resources/help/Set-AzTemplateSpec.md
  tools/StaticAnalysis/Exceptions/Az.Resources/BreakingChangeIssues.csv
Labels: Breaking Change Release

#14891 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseSensitivityClassification.md
Labels: customer-reported

#14892 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseSensitivityRecommendation.md
Labels: customer-reported

#14883 Typo "Azure SQL database"→"Azure SQL Database"
  src/Sql/Sql/help/Set-AzSqlDatabaseAudit.md
Labels: customer-reported

#14902 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Enable-AzSqlInstanceDatabaseSensitivityRecommendation.md
Labels: Waiting for CI :shipit:, customer-reported

#14899 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Set-AzSqlInstanceDatabaseSensitivityClassification.md
Labels: Waiting for CI :shipit:, customer-reported

#14901 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Remove-AzSqlInstanceDatabaseSensitivityClassification.md
Labels: customer-reported

#14900 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Disable-AzSqlInstanceDatabaseSensitivityRecommendation.md
Labels: customer-reported

#14898 Typo "Azure SQL managed instance"→"Azure SQL Managed Instance"
  src/Sql/Sql/help/Az.Sql.md
Labels: customer-reported

#14897 Azure Networking: Updated saDataSizeKilobytes validation for vpn gateway connection
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests/TestVirtualNetworkGatewayConnectionWithZeroSaData.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/VirtualNetworkGatewayVpnCustomIpsecPolicySetWithZeroSADataSizeTest.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/VirtualNetworkGatewayConnection/NewAzureRmIpsecPolicyCommand.cs
Labels: needs-revision

#14913 Publishing release version of Maintenance cmdlets for GA.
  src/Maintenance/Maintenance.Test/Maintenance.Test.csproj
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestMaintenanceConfiguration.json
  src/Maintenance/Maintenance.Test/SessionRecords/Microsoft.Azure.Commands.Maintenance.Test.ScenarioTests.MaintenanceTests/TestPublicMaintenanceConfiguration.json
  src/Maintenance/Maintenance/ChangeLog.md
  src/Maintenance/Maintenance/Maintenance.csproj
Labels: Waiting for CI :shipit:

#14952 Update IdentifierUris of ADApp and DisplayName of ADServicePrincipal
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADApplicationCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADApplicationCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzADApplication.md
  src/Resources/Resources/help/New-AzADServicePrincipal.md
Labels: needs-review

#14966 [Storage] Support Blob inventory
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageBlobInventory.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSBlobInventoryPolicy.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageBlobInventoryPolicy.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageBlobInventoryPolicyRule.cs
  src/Storage/Storage.Management/StorageAccount/RemoveAzureStorageBlobInventoryPolicy.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageBlobInventoryPolicy.cs
  src/Storage/Storage.Management/StorageAccount/StorageAccountBaseCmdlet.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobInventoryPolicy.md
  src/Storage/Storage.Management/help/New-AzStorageBlobInventoryPolicyRule.md
  src/Storage/Storage.Management/help/Remove-AzStorageBlobInventoryPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobInventoryPolicy.md
  tools/LocalFeed/Microsoft.Azure.Management.Storage.22.0.0.nupkg
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#14950 Set retry times by environment variable
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Extensions/ServiceClientExtension.cs
  src/Accounts/Authentication/Factories/ClientFactory.cs
  src/DataBox/DataBox/DataBox.csproj
  src/Websites/Websites.Helper/Websites.Helper.csproj
  tools/Common.Netcore.Dependencies.targets
  tools/RepoTasks/RepoTasks.CmdletsForTest/RepoTasks.CmdletsForTest.csproj
  tools/RepoTasks/RepoTasks.CmdletsForTest/packages.config
  tools/RepoTasks/RepoTasks.RemoteWorker/RepoTasks.RemoteWorker.csproj
  tools/RepoTasks/RepoTasks.RemoteWorker/packages.config
Labels: needs-review

#14979 Provide key size for RSA key
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Helpers/JwkHelper.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/PSDeletedKeyVaultKey.cs
  src/KeyVault/KeyVault/Models/PSKeyVaultKey.cs
Labels: Waiting for CI :shipit:

#14982 [Storage] Support DefaultSharePermission and CrossTenantReplication
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewSetAzStorageAccountFileAADDS.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobORS.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSAzureFilesIdentityBasedAuthentication.cs
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzStorageObjectReplicationPolicy.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/StorageAccountBaseCmdlet.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageObjectReplicationPolicy.md
  tools/LocalFeed/Microsoft.Azure.Management.Storage.22.0.0.nupkg
Labels: need-review

#15014 Subject name issuer
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Accounts/help/Connect-AzAccount.md
  src/Accounts/Authentication/Authentication/Parameters/AuthenticationParameters.cs
  src/Accounts/Authentication/Authentication/Parameters/ServicePrincipalParameters.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/Authenticators/ServicePrincipalAuthenticator.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#15004 [Pipeline]Add back Linux environment.
  .azure-pipelines/powershell-core.yml
  .azure-pipelines/util/analyze-steps.yml
  .azure-pipelines/util/build-steps.yml
  src/DesktopVirtualization/test/New-AzWvdScalingPlan.Tests.ps1
Labels: Waiting for CI :shipit:

#14996 Update New-AzVMwarePrivateCloud.md
  src/VMware/help/New-AzVMwarePrivateCloud.md
Labels: Waiting for CI :shipit:, customer-reported

#15021 Made changes in the registration to onboard nodes to Azure Arc
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
  src/StackHCI/help/Register-AzStackHCI.md
  src/StackHCI/help/Unregister-AzStackHCI.md
  tools/StaticAnalysis/Exceptions/Az.StackHCI/BreakingChangeIssues.csv
  tools/Tools.Common/SerializedCmdlets/Az.StackHCI.json
Labels: Waiting for CI :shipit:

#15012 Add warning message if user using PowerShell 6 or PowerShell 7 < 7.0.6
  tools/UpdateModules.psm1
Labels: Waiting for CI :shipit:

#15034 Create AzPreview module
  tools/AzPreview/AzPreview.psd1
  tools/AzPreview/AzPreview.psd1.template
  tools/PublishModules.psm1
  tools/RunVersionController.ps1
  tools/UpdateModules.psm1
Labels: Waiting for CI :shipit:

#15011 Fixes: #14884: `Set-AzWebAppSlot` to set FtpsState, #14998:`Set-AzWeb…
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AppServicePlans/SetAzureAppServicePlan.cs
  src/Websites/Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
Labels: Waiting for CI :shipit:

#14599 [Az.RecoveryServices.Backup] fixed sql CRR and security issue with SQL restore
  src/RecoveryServices/RecoveryServices.Backup.Helpers/RecoveryServices.Backup.Helpers.csproj
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureWorkloadRecoveryConfig.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Models/RecoveryServices.Backup.Models.csproj
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/RecoveryServices.Backup.Providers.csproj
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/RestoreDiskAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/RecoveryServices.Backup.ServiceClientAdapter.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ProtectionCheckTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/JobTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/GetAzureVmWorkloadContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVMGetContainers.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRSVaultMSI.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureUnmanagedVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMCrossRegionRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMDiskExclusion.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetItems.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMRPMountScript.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMSetVaultContext.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureFSGetJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMCancelJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobsTimeFilter.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMWaitJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadPolicy.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/RecoveryPoint/GetAzureRmRecoveryServicesBackupRecoveryLogChain.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/GetAzureRmRecoveryServicesBackupWorkloadRecoveryConfig.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.Test/RecoveryServices.Test.csproj
  src/RecoveryServices/RecoveryServices.sln
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
  src/RecoveryServices/RecoveryServices/Vault/GetAzureRmRecoveryServicesVaults.cs
  src/RecoveryServices/RecoveryServices/Vault/SetAzureRmRecoveryServicesVaultContext.cs
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryLogChain.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupWorkloadRecoveryConfig.md
Labels: needs-review

#15040 Update New-AzPublicIpAddress.md
  src/Network/Network/help/New-AzPublicIpAddress.md
Labels: Waiting for CI :shipit:, customer-reported

#15037 [App Service] Access restriction deterministic remove
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AccessRestriction/RemoveAzureWebAppAccessRestrictionRule.cs
Labels: Waiting for CI :shipit:

#15049 Update Split-AzReservation.md
  src/Reservations/Reservations/help/Split-AzReservation.md
Labels: Waiting for CI :shipit:, customer-reported

#15052 Small fix for AzPreview
  .gitignore
  tools/Az/Az.psd1
  tools/AzPreview.psd1.template
  tools/AzPreview/AzPreview.psd1
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#15045 Fix link typo in warning message
  tools/UpdateModules.psm1
Labels: Waiting for CI :shipit:

#15054 Update Get-AzExpressRouteCircuitRouteTable.md Example 1 correction
  src/Network/Network/help/Get-AzExpressRouteCircuitRouteTable.md
Labels: Waiting for CI :shipit:, customer-reported

#15062 Removing unused TimeGrain variable from example
  src/Monitor/Monitor/help/New-AzDiagnosticSetting.md
Labels: Waiting for CI :shipit:, customer-reported

#15071 Application Gateway AutoScale Example
  src/Network/Network/help/New-AzApplicationGatewayAutoscaleConfiguration.md
Labels: Waiting for CI :shipit:, customer-reported

#15073 Remove the reference to container instance project in network solution
  src/Network/Network.sln
Labels: Waiting for CI :shipit:

#15079 Add HighAvailabilityReplicaCount to New-AzSqlDatabaseSecondary
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/TestCreateNamedSecondaryDatabase.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Model/AzureReplicationLinkModel.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabaseSecondary.md
Labels: Waiting for CI :shipit:

#15085 Update SignalR module
  src/SignalR/SignalR.Test/ScenarioTests/AzureRmSignalRTests.cs
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalR.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRSetUpstream.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRUpdateNetworkAcl.json
  src/SignalR/SignalR.Test/SessionRecords/Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests/TestAzureRmSignalRWithDefaultArgs.json
  src/SignalR/SignalR.Test/SignalR.Test.csproj
  src/SignalR/SignalR.sln
  src/SignalR/SignalR/ChangeLog.md
  src/SignalR/SignalR/Cmdlets/GetAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/GetAzureRmSignalRKey.cs
  src/SignalR/SignalR/Cmdlets/NewAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/NewAzureRmSignalRKey.cs
  src/SignalR/SignalR/Cmdlets/RemoveAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/RestartAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/SetAzureRmSignalRUpstream.cs
  src/SignalR/SignalR/Cmdlets/TestAzureRmSignalRName.cs
  src/SignalR/SignalR/Cmdlets/UpdateAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/UpdateAzureRmSignalRNetworkAcl.cs
  src/SignalR/SignalR/Models/PSSignalRResource.cs
  src/SignalR/SignalR/SignalR.csproj
  src/SignalR/SignalR/Strategies/SignalRRp/SignalRStrategy.cs
  src/SignalR/SignalR/Utilities/Constants.cs
  src/SignalR/SignalR/help/Az.SignalR.md
  src/SignalR/SignalR/help/Update-AzSignalRNetworkAcl.md
Labels: Waiting for CI :shipit:

#15094 [DiskPool] Add unit tests
  src/DiskPool/examples/Get-AzDiskPool.md
  src/DiskPool/examples/Get-AzDiskPoolIscsiTarget.md
  src/DiskPool/examples/New-AzDiskPool.md
  src/DiskPool/examples/New-AzDiskPoolIscsiTarget.md
  src/DiskPool/examples/Remove-AzDiskPool.md
  src/DiskPool/examples/Remove-AzDiskPoolIscsiTarget.md
  src/DiskPool/examples/Start-AzDiskPool.md
  src/DiskPool/examples/Stop-AzDiskPool.md
  src/DiskPool/examples/Update-AzDiskPool.md
  src/DiskPool/examples/Update-AzDiskPoolIscsiTarget.md
  src/DiskPool/test/Get-AzDiskPool.Recording.json
  src/DiskPool/test/Get-AzDiskPool.Tests.ps1
  src/DiskPool/test/Get-AzDiskPoolIscsiTarget.Recording.json
  src/DiskPool/test/Get-AzDiskPoolIscsiTarget.Tests.ps1
  src/DiskPool/test/New-AzDiskPool.Recording.json
  src/DiskPool/test/New-AzDiskPool.Tests.ps1
  src/DiskPool/test/New-AzDiskPoolAclObject.Tests.ps1
  src/DiskPool/test/New-AzDiskPoolIscsiLunObject.Tests.ps1
  src/DiskPool/test/New-AzDiskPoolIscsiTarget.Recording.json
  src/DiskPool/test/New-AzDiskPoolIscsiTarget.Tests.ps1
  src/DiskPool/test/Remove-AzDiskPool.Recording.json
  src/DiskPool/test/Remove-AzDiskPool.Tests.ps1
  src/DiskPool/test/Remove-AzDiskPoolIscsiTarget.Recording.json
  src/DiskPool/test/Remove-AzDiskPoolIscsiTarget.Tests.ps1
  src/DiskPool/test/Start-AzDiskPool.Recording.json
  src/DiskPool/test/Start-AzDiskPool.Tests.ps1
  src/DiskPool/test/Stop-AzDiskPool.Recording.json
  src/DiskPool/test/Stop-AzDiskPool.Tests.ps1
  src/DiskPool/test/Update-AzDiskPool.Recording.json
  src/DiskPool/test/Update-AzDiskPool.Tests.ps1
  src/DiskPool/test/Update-AzDiskPoolIscsiTarget.Recording.json
  src/DiskPool/test/Update-AzDiskPoolIscsiTarget.Tests.ps1
  src/DiskPool/test/deployment-templates/disk-pool/parameters.json
  src/DiskPool/test/deployment-templates/disk-pool/template.json
  src/DiskPool/test/deployment-templates/disk/parameters.json
  src/DiskPool/test/deployment-templates/disk/template.json
  src/DiskPool/test/deployment-templates/iscsi-target/parameters.json
  src/DiskPool/test/deployment-templates/iscsi-target/template.json
  src/DiskPool/test/deployment-templates/virtual-network/parameters.json
  src/DiskPool/test/deployment-templates/virtual-network/template.json
  src/DiskPool/test/env.json
  src/DiskPool/test/utils.ps1
Labels: needs-review

#13732 [Az.EventHub] Get-AzEventHub accepts pipeline input from Get-AzEventHubNamespace.
  src/EventHub/EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.EventHubsTests/EventHubsAuthorizationRulesCRUD.json
  src/EventHub/EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.EventHubsTests/EventHubsCRUD.json
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/EventHub/GetAzureEventHubs.cs
  src/EventHub/EventHub/help/Get-AzEventHub.md
  src/EventHub/EventHub/help/Get-AzEventHubNamespace.md
  tools/StaticAnalysis/Exceptions/Az.EventHub/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15103 Update Set-AzNotificationHubsNamespace.md to include required "SkuTier" in examples
  src/NotificationHubs/NotificationHubs/help/Set-AzNotificationHubsNamespace.md
Labels: Waiting for CI :shipit:

#15112 Update misspelled word in Set-AzNetworkInterface.md
  src/Network/Network/help/Set-AzNetworkInterface.md
Labels: customer-reported

#15126 Update Az.DiskPool docs
  src/DiskPool/docs/Az.DiskPool.md
  src/DiskPool/docs/Get-AzDiskPool.md
  src/DiskPool/docs/Get-AzDiskPoolIscsiTarget.md
  src/DiskPool/docs/New-AzDiskPool.md
  src/DiskPool/docs/New-AzDiskPoolAclObject.md
  src/DiskPool/docs/New-AzDiskPoolIscsiLunObject.md
  src/DiskPool/docs/New-AzDiskPoolIscsiTarget.md
  src/DiskPool/docs/Remove-AzDiskPool.md
  src/DiskPool/docs/Remove-AzDiskPoolIscsiTarget.md
  src/DiskPool/docs/Start-AzDiskPool.md
  src/DiskPool/docs/Stop-AzDiskPool.md
  src/DiskPool/docs/Update-AzDiskPool.md
  src/DiskPool/docs/Update-AzDiskPoolIscsiTarget.md
Labels: Waiting for CI :shipit:

#15111 AzPreview use latest Az.Accounts version
  tools/AzPreview/AzPreview.psd1
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#15104 [NetAppFiles] Update to api-version 2021-02-01 updates
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirectory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.ActiveDirectoryTests/TestActiveDirectoryCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.ActiveDirectoryTests/TestActiveDirectoryPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupPolicyTests/TestBackupPolicyCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupPolicyTests/TestBackupPolicyPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestBackupCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestBackupPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestVolumeBackupStatusCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotPolicyTests/TestSnapshotPolicyCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotPolicyTests/TestSnapshotPolicyPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestCreateVolumeFromSnapshot.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestRestoreVolumeFromSnapshot.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VaultTests/TestVaultCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestSetVolumePool.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumePipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeReplication.json
  src/NetAppFiles/NetAppFiles/Backups/GetNetAppFilesBackup.cs
  src/NetAppFiles/NetAppFiles/Backups/NewNetAppFilesBackup.cs
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/BackupExtensions.cs
  src/NetAppFiles/NetAppFiles/Helpers/ModelExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesBackup.cs
  src/NetAppFiles/NetAppFiles/NetAppFiles.csproj
  src/NetAppFiles/NetAppFiles/Volume/GetNetAppFilesVolumeBackupStatus.cs
  src/NetAppFiles/NetAppFiles/Volume/UpdateNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/help/Az.NetAppFiles.md
  src/NetAppFiles/NetAppFiles/help/Get-AzNetAppFilesVolumeBackupStatus.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesBackup.md
  src/NetAppFiles/NetAppFiles/help/Remove-AzNetAppFilesBackup.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesVolume.md
Labels: Waiting for CI :shipit:

#15127 [Storage] Fix preview test failure
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage/Storage.csproj
Labels: Waiting for CI :shipit:

#15105 Enable short policy names for mi mw
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstanceWithMaintenanceConfigurationId.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
Labels: SQL - Managed Instance, Waiting for CI :shipit:

#15082 Update Test Deployments to allow the user to specify a deployment name
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Test-AzManagementGroupDeployment.md
  src/Resources/Resources/help/Test-AzTenantDeployment.md
Labels: Waiting for CI :shipit:

#15130 [Storage] Support NFS and SmbMultichannel
  src/Storage/Storage.Management.Test/ScenarioTests/StorageFileTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageFileTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageFileTests/TestAzureStorageShareNFS.json
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageFileTests/TestFileServiceProperties.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/File/NewAzureStorageShare.cs
  src/Storage/Storage.Management/File/UpdateAzAzStorageFileServiceProperty.cs
  src/Storage/Storage.Management/File/UpdateAzureStorageShare.cs
  src/Storage/Storage.Management/Models/PSFileServiceProperties.cs
  src/Storage/Storage.Management/Models/PSShare.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/help/Get-AzRmStorageShare.md
  src/Storage/Storage.Management/help/New-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Update-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Update-AzStorageFileServiceProperty.md
Labels: need-review

#15136 [Resource] Fixed issue that property IdentifierUri is cleaned by Update-AzAdApplication
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADApplicationCommand.cs
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#15153 Fix the random failure in CI pipeline
  src/Accounts/Accounts.Test/AutosaveTests.cs
Labels: Waiting for CI :shipit:
