Repository Azure/azure-powershell, pull requests merged in 2021-02, with the labels that each got.

#14052 Add codeowner for policyInsights
  .github/CODEOWNERS
Labels: Waiting for CI :shipit:

#14071 add legal term to new-azvmwareprivatecloud
  src/VMware/custom/LegalTerm.txt
  src/VMware/custom/New-AzVMwarePrivateCloud.ps1
Labels: Waiting for CI :shipit:

#13980 [MySql] Added connection test cmdlet
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/custom/Test-AzMySqlFlexibleServerConnect.ps1
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/Test-AzMySqlFlexibleServerConnect.md
  src/MySql/examples/Test-AzMySqlFlexibleServerConnect.md
  src/MySql/test/Test-AzMySqlFlexibleServerConnect.Recording.json
  src/MySql/test/Test-AzMySqlFlexibleServerConnect.Tests.ps1
Labels: needs-revision

#14039 Enable Get-AzVM piping to Get-AzVMExtension cmdlet
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineGetVMExtensionPiping.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/GetAzureVMExtensionCommand.cs
  src/Compute/Compute/help/Get-AzVMExtension.md
Labels: Waiting for CI :shipit:

#14058 [Storage] Upgrade XSCL and Azure.Core 1.8.1
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Storage.csproj
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#13981 [PostgreSql] Added connection test cmdlet
  src/MySql/Az.MySql.psd1
  src/PostgreSql/Az.PostgreSql.psd1
  src/PostgreSql/custom/New-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/Test-AzPostgreSqlFlexibleServerConnect.ps1
  src/PostgreSql/docs/Az.PostgreSql.md
  src/PostgreSql/docs/Test-AzPostgreSqlFlexibleServerConnect.md
  src/PostgreSql/examples/Test-AzPostgreSqlFlexibleServerConnect.md
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerConnect.Recording.json
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Recording.json
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Tests.ps1
  src/PostgreSql/utils/adjectives.txt
  src/PostgreSql/utils/nouns.txt
Labels: needs-revision

#14082 Set-AzDataLakeGen2AclRecursive.md - Fix typo (directiry -> directory)
  src/Storage/Storage.Management/help/Set-AzDataLakeGen2AclRecursive.md
Labels: customer-reported

#14049 Using the latest version of autorest to generate code for 'Databricks'
  src/Databricks/Az.Databricks.psd1
  src/Databricks/Az.Databricks.psm1
  src/Databricks/ChangeLog.md
  src/Databricks/check-dependencies.ps1
  src/Databricks/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/exports/New-AzDatabricksWorkspace.ps1
  src/Databricks/exports/ProxyCmdletDefinitions.ps1
  src/Databricks/generate-info.json
  src/Databricks/generated/api/Models/Api20180401/ErrorResponse.cs
  src/Databricks/generated/api/Models/Api20180401/Operation.cs
  src/Databricks/generated/api/Models/Api20180401/VirtualNetworkPeering.cs
  src/Databricks/generated/api/Models/Api20180401/VirtualNetworkPeeringPropertiesFormat.cs
  src/Databricks/generated/api/Models/Api20180401/Workspace.PowerShell.cs
  src/Databricks/generated/api/Models/Api20180401/Workspace.cs
  src/Databricks/generated/api/Models/Api20180401/WorkspaceCustomParameters.cs
  src/Databricks/generated/api/Models/Api20180401/WorkspaceEncryptionParameter.cs
  src/Databricks/generated/api/Models/Api20180401/WorkspaceProperties.cs
  src/Databricks/generated/cmdlets/NewAzDatabricksWorkspace_CreateExpanded.cs
  src/Databricks/help/New-AzDatabricksWorkspace.md
  src/Databricks/internal/New-AzDatabricksWorkspace.ps1
  src/Databricks/internal/ProxyCmdletDefinitions.ps1
  src/Databricks/readme.md
Labels: Waiting for CI :shipit:

#14080 polish changelog for az.accounts
  src/Accounts/Accounts/ChangeLog.md
Labels: Waiting for CI :shipit:

#14094 Add cmdlet Test-AzMySqlFlexibleServerConnect
  src/MySql/custom/Test-AzMySqlFlexibleServerConnect.ps1
Labels: Waiting for CI :shipit:

#14095 Add cmdlet Test-AzPostgreSqlFlexibleServerConnect
  src/PostgreSql/custom/Test-AzPostgreSqlFlexibleServerConnect.ps1
Labels: Waiting for CI :shipit:

#14090 Update Az.Accounts help
  src/Accounts/Accounts/help/Az.Accounts.md
  src/Accounts/Accounts/help/Clear-AzContext.md
  src/Accounts/Accounts/help/Clear-AzDefault.md
  src/Accounts/Accounts/help/Disable-AzContextAutosave.md
  src/Accounts/Accounts/help/Disable-AzDataCollection.md
  src/Accounts/Accounts/help/Disable-AzureRmAlias.md
  src/Accounts/Accounts/help/Disconnect-AzAccount.md
  src/Accounts/Accounts/help/Enable-AzContextAutosave.md
  src/Accounts/Accounts/help/Enable-AzDataCollection.md
  src/Accounts/Accounts/help/Enable-AzureRmAlias.md
  src/Accounts/Accounts/help/Get-AzContext.md
  src/Accounts/Accounts/help/Get-AzContextAutosaveSetting.md
  src/Accounts/Accounts/help/Get-AzDefault.md
  src/Accounts/Accounts/help/Get-AzEnvironment.md
  src/Accounts/Accounts/help/Get-AzSubscription.md
  src/Accounts/Accounts/help/Get-AzTenant.md
  src/Accounts/Accounts/help/Import-AzContext.md
  src/Accounts/Accounts/help/Invoke-AzRestMethod.md
  src/Accounts/Accounts/help/Register-AzModule.md
  src/Accounts/Accounts/help/Remove-AzContext.md
  src/Accounts/Accounts/help/Remove-AzEnvironment.md
  src/Accounts/Accounts/help/Rename-AzContext.md
  src/Accounts/Accounts/help/Save-AzContext.md
  src/Accounts/Accounts/help/Select-AzContext.md
  src/Accounts/Accounts/help/Send-Feedback.md
  src/Accounts/Accounts/help/Set-AzContext.md
  src/Accounts/Accounts/help/Set-AzDefault.md
  src/Accounts/Accounts/help/Uninstall-AzureRm.md
Labels: Waiting for CI :shipit:

#14091 Add cmdlet Test-AzMySqlFlexibleServerConnect
  src/MySql/Az.MySql.psd1
  src/MySql/ChangeLog.md
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/custom/New-AzMySqlServer.ps1
  src/MySql/custom/Test-AzMySqlFlexibleServerConnect.ps1
  src/MySql/custom/Update-AzMySqlFlexibleServer.ps1
  src/MySql/custom/Update-AzMySqlServer.ps1
  src/MySql/examples/Test-AzMySqlFlexibleServerConnect.md
  src/MySql/exports/ProxyCmdletDefinitions.ps1
  src/MySql/exports/Test-AzMySqlFlexibleServerConnect.ps1
  src/MySql/generate-info.json
  src/MySql/help/Az.MySql.md
  src/MySql/help/Test-AzMySqlFlexibleServerConnect.md
  src/MySql/test/Test-AzMySqlFlexibleServerConnect.Recording.json
  src/MySql/test/Test-AzMySqlFlexibleServerConnect.Tests.ps1
Labels: Waiting for CI :shipit:

#14096 Add cmdlet Test-AzPostgreSqlFlexibleServerConnect
  src/PostgreSql/Az.PostgreSql.psd1
  src/PostgreSql/ChangeLog.md
  src/PostgreSql/custom/New-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/New-AzPostgreSqlServer.ps1
  src/PostgreSql/custom/Test-AzPostgreSqlFlexibleServerConnect.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlServer.ps1
  src/PostgreSql/examples/Test-AzPostgreSqlFlexibleServerConnect.md
  src/PostgreSql/exports/ProxyCmdletDefinitions.ps1
  src/PostgreSql/exports/Test-AzPostgreSqlFlexibleServerConnect.ps1
  src/PostgreSql/generate-info.json
  src/PostgreSql/help/Az.PostgreSql.md
  src/PostgreSql/help/Test-AzPostgreSqlFlexibleServerConnect.md
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Recording.json
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Tests.ps1
Labels: Waiting for CI :shipit:

#13690 add cmdlets Get/Start/convert-SynapseVulnerabilityAssessmentScan
  src/Synapse/Synapse.Test/ScenarioTests/VulnerabilityAssessmentTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/VulnerabilityAssessmentTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentScanConvertTest.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentScanRecordGetListTest.json
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/ConvertAzureSynapseSqlPoolVulnerabilityAssessmentScan.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/GetAzureSynapseSqlPoolVulnerabilityAssessmentScanRecord.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/StartAzureSynapseSqlPoolVulnerabilityAssessmentScan.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/PSVulnerabilityAssessmentScanErrorModel.cs
  src/Synapse/Synapse/Models/PSVulnerabilityAssessmentScanExportModel.cs
  src/Synapse/Synapse/Models/PSVulnerabilityAssessmentScanRecordModel.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Convert-AzSynapseSqlPoolVulnerabilityAssessmentScan.md
  src/Synapse/Synapse/help/Get-AzSynapseSqlPoolVulnerabilityAssessmentScanRecord.md
  src/Synapse/Synapse/help/Start-AzSynapseSqlPoolVulnerabilityAssessmentScan.md
  tools/SecurityTools/CredScanSuppressions.json
Labels: Waiting for CI :shipit:

#13621 Get-AzSynapseSqlPoolGeoBackup and Get-AzSynapseDroppedSqlPool.
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolBackupTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolBackupTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestDroppedSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestSqlPoolGeoBackup.json
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/GetAzureSynapseDroppedSqlPoolBackup.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/GetAzureSynapseSqlPoolGeoBackup.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/PSRecoverableSqlPool.cs
  src/Synapse/Synapse/Models/PSRestorableDroppedSqlPool.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Get-AzSynapseDroppedSqlPool.md
  src/Synapse/Synapse/help/Get-AzSynapseSqlPoolGeoBackup.md
Labels: Waiting for CI :shipit:

#14087 Type fix: changed SshKeyVaule to SshKeyValue
  src/Aks/Aks/Properties/Resources.Designer.cs
  src/Aks/Aks/Properties/Resources.resx
Labels: Waiting for CI :shipit:, customer-reported

#14088 Examples used New-AzAks which is legacy cmdlet and the alias for New-…
  src/Aks/Aks/help/New-AzAksCluster.md
Labels: Waiting for CI :shipit:, customer-reported

#14112 Fixed a typo in the cmdlet
  src/Monitor/Monitor/help/Get-AzActivityLog.md
Labels: customer-reported

#14132 Added support for -QueryString parameters to cmdlets hitting /validate API and Fixed issues with dynamic parameters
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/TestCreateRPIWithManagedDisk.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentCreateCmdlet.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/ResourceWithParameterCmdletBase.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/TestDeploymentCmdletBase.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/TestAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/TestAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Test-AzDeployment.md
  src/Resources/Resources/help/Test-AzManagementGroupDeployment.md
  src/Resources/Resources/help/Test-AzResourceGroupDeployment.md
  src/Resources/Resources/help/Test-AzTenantDeployment.md
Labels: Do Not Merge :no_entry_sign:

#14155 Small spelling, formatting changes
  src/ResourceGraph/ResourceGraph/help/Get-AzResourceGraphQuery.md
Labels: customer-reported

#14123 [MySQL] Fix discrepancy between swagger and resource id
  src/MySql/readme.md
  src/MySql/test/Get-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServer.Tests.ps1
  src/MySql/test/Get-AzMySqlFlexibleServerConfiguration.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServerConfiguration.Tests.ps1
  src/MySql/test/Get-AzMySqlFlexibleServerConnectionString.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServerDatabase.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServerDatabase.Tests.ps1
  src/MySql/test/Get-AzMySqlFlexibleServerFirewallRule.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServerFirewallRule.Tests.ps1
  src/MySql/test/Get-AzMySqlFlexibleServerLocationBasedCapability.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServerReplica.Recording.json
  src/MySql/test/Get-AzMySqlFlexibleServerReplica.Tests.ps1
  src/MySql/test/New-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/New-AzMySqlFlexibleServerDatabase.Recording.json
  src/MySql/test/New-AzMySqlFlexibleServerFirewallRule.Recording.json
  src/MySql/test/New-AzMySqlFlexibleServerReplica.Recording.json
  src/MySql/test/Remove-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Remove-AzMySqlFlexibleServer.Tests.ps1
  src/MySql/test/Remove-AzMySqlFlexibleServerDatabase.Recording.json
  src/MySql/test/Remove-AzMySqlFlexibleServerDatabase.Tests.ps1
  src/MySql/test/Remove-AzMySqlFlexibleServerFirewallRule.Recording.json
  src/MySql/test/Remove-AzMySqlFlexibleServerFirewallRule.Tests.ps1
  src/MySql/test/Restart-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Restart-AzMySqlFlexibleServer.Tests.ps1
  src/MySql/test/Restore-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Start-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Start-AzMySqlFlexibleServer.Tests.ps1
  src/MySql/test/Stop-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Stop-AzMySqlFlexibleServer.Tests.ps1
  src/MySql/test/Test-AzMySqlFlexibleServerConnect.Recording.json
  src/MySql/test/Test-AzMySqlFlexibleServerConnect.Tests.ps1
  src/MySql/test/Update-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Update-AzMySqlFlexibleServerConfiguration.Recording.json
  src/MySql/test/Update-AzMySqlFlexibleServerConfiguration.Tests.ps1
  src/MySql/test/Update-AzMySqlFlexibleServerDatabase.Recording.json
  src/MySql/test/Update-AzMySqlFlexibleServerDatabase.Tests.ps1
  src/MySql/test/Update-AzMySqlFlexibleServerFirewallRule.Recording.json
  src/MySql/test/Update-AzMySqlFlexibleServerFirewallRule.Tests.ps1
Labels: needs-revision

#14124 [PostgreSql] Fix discrepancy between swagger and resource id
  src/PostgreSql/readme.md
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerConfiguration.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerConfiguration.Tests.ps1
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerConnect.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerConnectionString.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerFirewallRule.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerFirewallRule.Tests.ps1
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerLocationBasedCapability.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlFlexibleServerFirewallRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Remove-AzPostgreSqlFlexibleServerFirewallRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFlexibleServerFirewallRule.Tests.ps1
  src/PostgreSql/test/Restart-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Restart-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Restore-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Start-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Start-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Stop-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Stop-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServerConfiguration.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServerConfiguration.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServerFirewallRule.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServerFirewallRule.Tests.ps1
Labels: Waiting for CI :shipit:

#14176 Update Set-AzNetworkSecurityRuleConfig.md
  src/Network/Network/help/Set-AzNetworkSecurityRuleConfig.md
Labels: customer-reported

#14177 Acr fix
  src/ContainerRegistry/ContainerRegistry/Az.ContainerRegistry.psd1
  src/ContainerRegistry/ContainerRegistry/ChangeLog.md
  src/ContainerRegistry/ContainerRegistry/Commands/ConnectAzureContainerRegistry.cs
  src/ContainerRegistry/ContainerRegistry/Models/ContainerRegistryDataPlaneClient.cs
  src/ContainerRegistry/ContainerRegistry/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
Labels: Do Not Merge :no_entry_sign:

#14185 Added an additional cmdline to the example which applies the changes …
  src/Network/Network/help/Add-AzLoadBalancerInboundNatRuleConfig.md
Labels: customer-reported

#14189 Az.ContainerRegistry 2.2.1 OOB release (#14177)
  src/ContainerRegistry/ContainerRegistry/Az.ContainerRegistry.psd1
  src/ContainerRegistry/ContainerRegistry/ChangeLog.md
  src/ContainerRegistry/ContainerRegistry/Commands/ConnectAzureContainerRegistry.cs
  src/ContainerRegistry/ContainerRegistry/Models/ContainerRegistryDataPlaneClient.cs
  src/ContainerRegistry/ContainerRegistry/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
Labels: Do Not Merge :no_entry_sign:

#14116 [MySql] Add maintenance window to update flexible server cmdlet
  src/MySql/custom/Update-AzMySqlFlexibleServer.ps1
  src/MySql/docs/Update-AzMySqlFlexibleServer.md
  src/MySql/test/Update-AzMySqlFlexibleServer.Recording.json
  src/MySql/test/Update-AzMySqlFlexibleServer.Tests.ps1
Labels: needs-revision

#14115 [PostgreSql] Add maintenance window to update flexible server cmdlet
  src/PostgreSql/custom/Update-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/docs/New-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/docs/Update-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/docs/Update-AzPostgreSqlFlexibleServerConfiguration.md
  src/PostgreSql/examples/New-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/examples/Update-AzPostgreSqlFlexibleServerConfiguration.md
  src/PostgreSql/readme.md
  src/PostgreSql/test/Get-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/New-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/Remove-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Remove-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/deployment-templates/virtual-network/template.json
  src/PostgreSql/test/env.json
  src/PostgreSql/test/utils.ps1
Labels: needs-revision

#13965 Add prompt for usage and survey
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/InterceptSurvey.ps1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/PromptSurvey.ps1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Settings.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/AzPredictorTelemetryClient.cs
Labels: needs-review

#13681 [AzRecoveryServices.Backup] Adding null check for target storage account
  src/RecoveryServices/RecoveryServices.Backup.Helpers/TrackingHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/WaitAzureRmRecoveryServicesBackupJob.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#14231 Update Add-AzLoadBalancerInboundNatPoolConfig.md
  src/Network/Network/help/Add-AzLoadBalancerInboundNatPoolConfig.md
Labels: customer-reported

#14157 Add clear element to Nuget.config
  NuGet.Config
  tools/Az.Tools.Predictor/NuGet.Config
  tools/NetCoreCsProjSync/NuGet.Config
  tools/NetCorePsd1Sync/NuGet.Config
Labels: Waiting for CI :shipit:

#14216 Add sql mi maintenance configuration examples
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
Labels: customer-reported

#14241 Update sign pipeline of Az.Tools.Predictor
  .azure-pipelines/sign-tool-predictor.yml
Labels: Az.Tools.Predictor, needs-review

#14264 Update website helper to follow assembly setting
  src/Websites/Websites.Helper/Properties/AssemblyInfo.cs
  src/Websites/Websites.Helper/Websites.Helper.csproj
Labels: Waiting for CI :shipit:

#14242 [KeyVault] Update Az 5.0 migration guide
  documentation/migration-guides/Az.5.0.0-migration-guide.md
Labels: Doc - Reference, needs-review

#14235 Update to latest CosmosDB client libraray and allow ServerVersion to …
  src/CosmosDB/CosmosDB.Test/ScenarioTests/AccountTests.ps1
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountRelatedCmdlets.json
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewOrUpdateAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/Helpers/Constants.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSApiProperties.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSBackupPolicy.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSDatabaseAccountGetResults.cs
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBAccount.md
  src/CosmosDB/CosmosDB/help/Update-AzCosmosDBAccount.md
Labels: customer-reported

#14221 [BotService] Fix the issue that didn't pack resources files of bot service.
  build.proj
  src/BotService/Changelog.md
  src/BotService/readme.md
  src/BotService/resources/typescript.web.config
  src/BotService/resources/web.config
  src/BotService/resources/webappv4.template.json
Labels: Do Not Merge :no_entry_sign:

#14104 [DO NOT MERGE] Support deploying Azure resources described with the Bicep language
  src/Resources/ResourceManager/Implementation/CmdletBase/ResourceWithParameterCmdletBase.cs
  src/Resources/ResourceManager/Properties/Resources.Designer.cs
  src/Resources/ResourceManager/Properties/Resources.resx
  src/Resources/ResourceManager/Utilities/BicepUtility.cs
  src/Resources/Resources.Test/Resources.Test.csproj
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentFromBicepFile.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestTestDeploymentFromBicepFile.json
  src/Resources/Resources.Test/UnitTests/Utilities/TestBicepUtility.cs
  src/Resources/Resources.Test/sampleDeploymentBicepFile.bicep
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Get-AzDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzManagementGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzResourceGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzTenantDeploymentWhatIfResult.md
  src/Resources/Resources/help/New-AzDeployment.md
  src/Resources/Resources/help/New-AzManagementGroupDeployment.md
  src/Resources/Resources/help/New-AzResourceGroupDeployment.md
  src/Resources/Resources/help/New-AzTenantDeployment.md
  src/Resources/Resources/help/Test-AzDeployment.md
  src/Resources/Resources/help/Test-AzManagementGroupDeployment.md
  src/Resources/Resources/help/Test-AzResourceGroupDeployment.md
  src/Resources/Resources/help/Test-AzTenantDeployment.md
Labels: Do Not Merge :no_entry_sign:

#14284 [Confluent] Release api version 2020-03-01.
  src/Confluent/.gitattributes
  src/Confluent/.gitignore
  src/Confluent/Az.Confluent.psd1
  src/Confluent/custom/readme.md
  src/Confluent/docs/Az.Confluent.md
  src/Confluent/docs/Get-AzConfluentMarketplaceAgreement.md
  src/Confluent/docs/Get-AzConfluentOrganization.md
  src/Confluent/docs/New-AzConfluentMarketplaceAgreement.md
  src/Confluent/docs/New-AzConfluentOrganization.md
  src/Confluent/docs/Remove-AzConfluentOrganization.md
  src/Confluent/docs/Update-AzConfluentOrganization.md
  src/Confluent/docs/readme.md
  src/Confluent/examples/Get-AzConfluentMarketplaceAgreement.md
  src/Confluent/examples/Get-AzConfluentOrganization.md
  src/Confluent/examples/New-AzConfluentMarketplaceAgreement.md
  src/Confluent/examples/New-AzConfluentOrganization.md
  src/Confluent/examples/Remove-AzConfluentOrganization.md
  src/Confluent/examples/Update-AzConfluentOrganization.md
  src/Confluent/how-to.md
  src/Confluent/license.txt
  src/Confluent/readme.md
  src/Confluent/resources/readme.md
  src/Confluent/test/Get-AzConfluentMarketplaceAgreement.Recording.json
  src/Confluent/test/Get-AzConfluentMarketplaceAgreement.Tests.ps1
  src/Confluent/test/Get-AzConfluentOrganization.Recording.json
  src/Confluent/test/Get-AzConfluentOrganization.Tests.ps1
  src/Confluent/test/New-AzConfluentMarketplaceAgreement.Recording.json
  src/Confluent/test/New-AzConfluentMarketplaceAgreement.Tests.ps1
  src/Confluent/test/New-AzConfluentOrganization.Recording.json
  src/Confluent/test/New-AzConfluentOrganization.Tests.ps1
  src/Confluent/test/Remove-AzConfluentOrganization.Recording.json
  src/Confluent/test/Remove-AzConfluentOrganization.Tests.ps1
  src/Confluent/test/Update-AzConfluentOrganization.Recording.json
  src/Confluent/test/Update-AzConfluentOrganization.Tests.ps1
  src/Confluent/test/env.json
  src/Confluent/test/loadEnv.ps1
  src/Confluent/test/readme.md
  src/Confluent/test/utils.ps1
  src/Confluent/utils/Unprotect-SecureString.ps1
Labels: Waiting for CI :shipit:

#13894 fix #13763- webapp:Increased timout to 300000 MS for Publish-AzWebApp cmdlet
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromWar.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromZip.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
  src/Websites/Websites/help/Publish-AzWebApp.md
  src/Websites/Websites/help/Remove-AzWebAppCertificate.md
Labels: Waiting for CI :shipit:

#14302 [KubernertesConfiguration] Update Api version for Kubernetes Configuration
  src/KubernetesConfiguration/custom/New-AzKubernetesConfiguration.ps1
  src/KubernetesConfiguration/custom/readme.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/readme.md
  src/KubernetesConfiguration/how-to.md
  src/KubernetesConfiguration/readme.md
  src/KubernetesConfiguration/test/Get-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/New-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/env.json
  src/KubernetesConfiguration/utils/Unprotect-SecureString.ps1
Labels: Generator

#14307 [Storage] Fix a issue cause SDK breaking change
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
Labels: Waiting for CI :shipit:

#14314 [Automation]Fix the issue of automation in string
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/PowershellJsonConverter.cs
Labels: Automation

#14331 Updated Az Predictor cmdlet help
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Commands/DisableAzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Commands/EnableAzPredictor.cs
Labels: Az.Tools.Predictor

#14334 Create XML-based help
  .azure-pipelines/sign-tool-predictor.yml
  tools/Az.Tools.Predictor/GenerateHelp.ps1
  tools/Az.Tools.Predictor/build.proj
Labels: Az.Tools.Predictor

#14330 [CloudService]Fix the typo in New-AzCloudService.md
  src/CloudService/docs/New-AzCloudService.md
  src/CloudService/examples/New-AzCloudService.md
Labels: Generator

#14335 Fixed 3 typos in Set-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesAsrReplicationProtectedItem.md
Labels: customer-reported
