Repository Azure/azure-powershell, pull requests merged in 2021-06, with the labels that each got.

#15144 Update Az.SecurityInsights help files
  src/SecurityInsights/SecurityInsights/help/Get-AzSentinelAlertRule.md
  src/SecurityInsights/SecurityInsights/help/Get-AzSentinelAlertRuleTemplate.md
Labels: Waiting for CI :shipit:

#15146 typo in examples resourcegroup parameter
  src/Compute/Compute/help/Set-AzVMOSDisk.md
Labels: Waiting for CI :shipit:, customer-reported

#15151 Code changes for provisioning Server & ManagedInstance with AD Only Authentication & External Administrator Properties
  src/Sql/Sql.Test/UnitTests/AzureSqlDatabaseServerAttributeTests.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/GetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceCommunicator.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/Server/Cmdlet/GetAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Model/AzureSqlServerModel.cs
  src/Sql/Sql/Server/Services/AzureSqlServerAdapter.cs
  src/Sql/Sql/Server/Services/AzureSqlServerCommunicator.cs
  src/Sql/Sql/help/Get-AzSqlInstance.md
  src/Sql/Sql/help/Get-AzSqlServer.md
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlServer.md
Labels: Waiting for CI :shipit:

#15160 Release notes of Az.DiskPool v0.1.0
  src/DiskPool/Az.DiskPool.psd1
Labels: needs-review

#15120 cmdlets for new compute resource: SSH Public Key
  src/Compute/Compute.Test/ScenarioTests/sshKeyTests.cs
  src/Compute/Compute.Test/ScenarioTests/sshKeyTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.sshKeyTests/TestSshKey.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Common/ComputeClientBaseCmdlet.cs
  src/Compute/Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Models/PSSshPublicKeyResource.cs
  src/Compute/Compute/Models/PSSshPublicKeyResourceList.cs
  src/Compute/Compute/Usage/GetAzureSshKey.cs
  src/Compute/Compute/Usage/NewAzureSshKey.cs
  src/Compute/Compute/Usage/RemoveAzureSshKey.cs
  src/Compute/Compute/Usage/UpdateAzureSshKey.cs
  src/Compute/Compute/help/Az.Compute.md
  src/Compute/Compute/help/Get-AzSshKey.md
  src/Compute/Compute/help/New-AzSshKey.md
  src/Compute/Compute/help/Remove-AzSshKey.md
  src/Compute/Compute/help/Update-AzSshKey.md
Labels: needs-revision

#15185 Adding Cross Tenant DS move
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/CopyAzureRmRecoveryServicesVault.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/InitializeAzureRMRecoveryServicesDSMove.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/TestAzureRMRecoveryServicesDSMove.cs
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Az.RecoveryServices.md
  src/RecoveryServices/RecoveryServices/help/Copy-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Initialize-AzRecoveryServicesDSMove.md
  src/RecoveryServices/RecoveryServices/help/Test-AzRecoveryServicesDSMove.md
Labels: Waiting for CI :shipit:

#15187 Add SecretManagement tag to module
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/ChangeLog.md
Labels: Waiting for CI :shipit:

#15188 hotfix for the issue on windows powershell
  src/DiskPool/Az.DiskPool.psd1
  src/DiskPool/custom/New-AzDiskPool.ps1
  src/DiskPool/custom/Update-AzDiskPool.ps1
  src/DiskPool/docs/Az.DiskPool.md
  src/DiskPool/docs/Stop-AzDiskPool.md
  src/DiskPool/readme.md
  src/DiskPool/test/Stop-AzDiskPool.Tests.ps1
Labels: Waiting for CI :shipit:

#15122 Adding CMK changes for PS cmdlets
  src/Sql/Sql.LegacySdk/Generated/Models/EncryptionProtectorProperties.cs
  src/Sql/Sql.Test/ScenarioTests/TransparentDataEncryptionCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/TransparentDataEncryptionCrudTests.ps1
  src/Sql/Sql/Auditing/Services/AuditingEndpointsCommunicator.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/ResourceIdentityHelper.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/Server/Model/AzureSqlServerModel.cs
  src/Sql/Sql/Server/Services/AzureSqlServerAdapter.cs
  src/Sql/Sql/TransparentDataEncryption/Cmdlet/SetAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
  src/Sql/Sql/TransparentDataEncryption/Cmdlet/SetAzureSqlServerTransparentDataEncryptionProtector.cs
  src/Sql/Sql/TransparentDataEncryption/Model/AzureRmSqlManagedInstanceTransparentDataEncryptionProtectorModel.cs
  src/Sql/Sql/TransparentDataEncryption/Model/AzureSqlServerTransparentDataEncryptionProtectorModel.cs
  src/Sql/Sql/TransparentDataEncryption/Services/AzureSqlDatabaseTransparentDataEncryptionAdapter.cs
  src/Sql/Sql/TransparentDataEncryption/Services/AzureSqlDatabaseTransparentDataEncryptionArmAdapter.cs
  src/Sql/Sql/TransparentDataEncryption/Services/AzureSqlDatabaseTransparentDataEncryptionCommunicator.cs
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlServer.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlInstanceTransparentDataEncryptionProtector.md
  src/Sql/Sql/help/Set-AzSqlServer.md
  src/Sql/Sql/help/Set-AzSqlServerTransparentDataEncryptionProtector.md
Labels: Waiting for CI :shipit:

#14738 Provide certificate file login method
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Connect-AzAccount.md
  src/Accounts/Authentication.Test/AuthenticatorsTest/ServicePrincipalAuthenticatorTests.cs
  src/Accounts/Authentication/Authentication/Parameters/ServicePrincipalParameters.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/Authenticators/Factories/AzureCredentialFactory.cs
  src/Accounts/Authenticators/ServicePrincipalAuthenticator.cs
Labels: needs-review

#15190 [Storage] Removed StorageFileDataSmbShareOwner from value set of DefaultSharePermission
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewSetAzStorageAccountFileAADDS.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15172 Update Compute module to use latest .Net SDK version 47.0.0
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/Security/Security.Test/Security.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-team-attention

#15166 [ApplicationInsights] Fixed ApplicationInsightsLinkedStorageAccount CRUD command that complain missing resourcegroupName when using InputObject
  src/ApplicationInsights/ApplicationInsights.Test/ScenarioTests/LinkedStorageAccountTests.ps1
  src/ApplicationInsights/ApplicationInsights.Test/SessionRecords/Microsoft.Azure.Commands.ApplicationInsights.Test.ScenarioTests.LinkedStorageAccountTests/TestLinkedStorageAccountCRUD.json
  src/ApplicationInsights/ApplicationInsights/ApplicationInsights/GetApplicationInsightsLinkedStorageAccount.cs
  src/ApplicationInsights/ApplicationInsights/ApplicationInsights/NewApplicationInsightsLinkedStorageAccount.cs
  src/ApplicationInsights/ApplicationInsights/ApplicationInsights/RemoveApplicationInsightsLinkedStorageAccount.cs
  src/ApplicationInsights/ApplicationInsights/ApplicationInsights/UpdateApplicationInsightsLinkedStorageAccount.cs
  src/ApplicationInsights/ApplicationInsights/ChangeLog.md
Labels: needs-revision

#15196 Add edge zone parameter to virtual network cmdlet
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkEdgeZone.json
  src/Network/Network/Models/PSExtendedLocation.cs
  src/Network/Network/Models/PSVirtualNetwork.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/VirtualNetwork/NewAzureVirtualNetworkCommand.cs
Labels: Waiting for CI :shipit:

#15225 Remove Write-Host leaking file share credentials
  src/ContainerInstance/Changelog.md
  src/ContainerInstance/custom/New-AzContainerGroupVolumeObject.ps1
Labels: customer-reported

#15184 Add edge zone parameter to create network interface cmdlet
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTests.cs
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkInterfaceTests/TestNetworkInterfaceInEdgeZone.json
  src/Network/Network/Models/PSNetworkInterface.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkInterface/NewAzureNetworkInterfaceCommand.cs
  src/Network/Network/help/New-AzNetworkInterface.md
Labels: Waiting for CI :shipit:

#15234 Fix a bug in container instance
  src/ContainerInstance/Az.ContainerInstance.psd1
  src/ContainerInstance/custom/New-AzContainerGroup.ps1
  src/ContainerInstance/custom/New-AzContainerGroupImageRegistryCredentialObject.ps1
  src/ContainerInstance/custom/New-AzContainerGroupPortObject.ps1
  src/ContainerInstance/custom/New-AzContainerGroupVolumeObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceEnvironmentVariableObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceInitDefinitionObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstancePortObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceVolumeMountObject.ps1
  src/ContainerInstance/docs/Az.ContainerInstance.md
  src/ContainerInstance/docs/New-AzContainerGroup.md
  src/ContainerInstance/docs/New-AzContainerGroupImageRegistryCredentialObject.md
  src/ContainerInstance/docs/New-AzContainerGroupPortObject.md
  src/ContainerInstance/docs/New-AzContainerGroupVolumeObject.md
  src/ContainerInstance/docs/New-AzContainerInstanceEnvironmentVariableObject.md
  src/ContainerInstance/docs/New-AzContainerInstanceInitDefinitionObject.md
  src/ContainerInstance/docs/New-AzContainerInstanceObject.md
  src/ContainerInstance/docs/New-AzContainerInstancePortObject.md
  src/ContainerInstance/docs/New-AzContainerInstanceVolumeMountObject.md
  src/ContainerInstance/readme.md
Labels: Waiting for CI :shipit:

#15195 Gateway Load Balancer Cross tenant issue fix
  src/Network/Network/Generated/LoadBalancer/NewAzureRMLoadBalancerCommand.cs
  src/Network/Network/Generated/LoadBalancer/SetAzureRMLoadBalancerCommand.cs
  src/Network/Network/NetworkInterface/NewAzureNetworkInterfaceCommand.cs
  src/Network/Network/NetworkInterface/SetAzureNetworkInterfaceCommand.cs
Labels: Waiting for CI :shipit:

#15231 Update Get-AzSynapseTriggerRun.md example so they do not throw errors
  src/Synapse/Synapse/help/Get-AzSynapseTriggerRun.md
Labels: customer-reported

#15241 [Az.RecoveryServices.Backup] Fixed Disable SQL AG Auto Protection Scenario
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesBackupAutoProtection.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#15240 Add edge zone parameter to public ip prefix cmdlet
  src/Network/Network.Test/ScenarioTests/PublicIpPrefixTests.cs
  src/Network/Network.Test/ScenarioTests/PublicIpPrefixTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpPrefixTests/TestPublicIpPrefixInEdgeZone.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSPublicIpPrefix.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PublicIpPrefix/NewAzurePublicIpPrefixCommand.cs
  src/Network/Network/help/New-AzPublicIpPrefix.md
Labels: Waiting for CI :shipit:

#15230 Enable viewing of Public IP address extended location
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpAddressTests/TestPublicIpAddressInEdgeZone.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSPublicIpAddress.cs
  src/Network/Network/Network.format.ps1xml
Labels: Waiting for CI :shipit:

#15159 [Az.RecoveryServices.Backup] [preview] Adding support for cross tenant DS move
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/CopyAzureRmRecoveryServicesVault.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/InitializeAzureRMRecoveryServicesDSMove.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/TestAzureRMRecoveryServicesDSMove.cs
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Az.RecoveryServices.md
  src/RecoveryServices/RecoveryServices/help/Copy-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Initialize-AzRecoveryServicesDSMove.md
  src/RecoveryServices/RecoveryServices/help/Test-AzRecoveryServicesDSMove.md
Labels: Cmdlet Review Required :warning:, needs-review

#15232 Update Get-AzSynapsePipelineRun.md by adding more examples covering more scenarios
  src/Synapse/Synapse/help/Get-AzSynapsePipelineRun.md
Labels: Waiting for CI :shipit:, customer-reported

#15209 [Storage] Support secure SMB and NFSV3
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageFileTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewAzureStorageAccountEnableNfsV3.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/File/UpdateAzAzStorageFileServiceProperty.cs
  src/Storage/Storage.Management/Models/PSFileServiceProperties.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/help/Get-AzStorageFileServiceProperty.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Update-AzStorageFileServiceProperty.md
Labels: Waiting for CI :shipit:, needs-review

#15280 Update change log to include virtual network change
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:

#15277 Updating set command in example
  src/Network/Network/help/Remove-AzApplicationGatewayBackendAddressPool.md
  src/Network/Network/help/Remove-AzApplicationGatewayBackendHttpSetting.md
  src/Network/Network/help/Remove-AzApplicationGatewayClientAuthConfiguration.md
  src/Network/Network/help/Remove-AzApplicationGatewayConnectionDraining.md
  src/Network/Network/help/Remove-AzApplicationGatewayCustomError.md
  src/Network/Network/help/Remove-AzApplicationGatewayFrontendIPConfig.md
  src/Network/Network/help/Remove-AzApplicationGatewayFrontendPort.md
  src/Network/Network/help/Remove-AzApplicationGatewayHttpListener.md
  src/Network/Network/help/Remove-AzApplicationGatewayIPConfiguration.md
  src/Network/Network/help/Remove-AzApplicationGatewayPrivateLinkConfiguration.md
  src/Network/Network/help/Remove-AzApplicationGatewayRedirectConfiguration.md
  src/Network/Network/help/Remove-AzApplicationGatewayRequestRoutingRule.md
  src/Network/Network/help/Remove-AzApplicationGatewayRewriteRuleSet.md
  src/Network/Network/help/Remove-AzApplicationGatewaySslCertificate.md
  src/Network/Network/help/Remove-AzApplicationGatewaySslPolicy.md
  src/Network/Network/help/Remove-AzApplicationGatewaySslProfile.md
  src/Network/Network/help/Remove-AzApplicationGatewayTrustedClientCertificate.md
  src/Network/Network/help/Set-AzApplicationGatewayIPConfiguration.md
Labels: needs-review

#15291 Import-AzWebAppKeyVaultCertificate - Fix web app parameter name in examples
  src/Websites/Websites/help/Import-AzWebAppKeyVaultCertificate.md
Labels: customer-reported

#15284 [Storage] Support container softdelete
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobContainerSoftDelete.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/Blob/DisableAzureStorageContainerDeleteRetentionPolicy.cs
  src/Storage/Storage.Management/Blob/EnableAzureStorageContainerDeleteRetentionPolicy.cs
  src/Storage/Storage.Management/Blob/GetAzureStorageContainer.cs
  src/Storage/Storage.Management/Blob/StorageBlobBaseCmdlet.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSBlobServiceProperties.cs
  src/Storage/Storage.Management/Models/PSContainer.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Disable-AzStorageContainerDeleteRetentionPolicy.md
  src/Storage/Storage.Management/help/Enable-AzStorageContainerDeleteRetentionPolicy.md
  src/Storage/Storage.Management/help/Get-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/Get-AzStorageContainer.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageEncryptionScope.md
  src/Storage/Storage.Management/help/Restore-AzStorageContainer.md
  src/Storage/Storage.Management/help/Update-AzStorageBlobServiceProperty.md
  src/Storage/Storage.Management/help/Update-AzStorageEncryptionScope.md
  src/Storage/Storage.Management/help/Update-AzStorageFileServiceProperty.md
  src/Storage/Storage.Test/Blob/Cmdlet/GetAzureStorageContainerTest.cs
  src/Storage/Storage.Test/Service/MockStorageBlobManagement.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/RemoveAzureStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/RestoreAzStorageContainer.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageContainerAcl.cs
  src/Storage/Storage/Common/AzureStorageContainer.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2FileContent.cs
  src/Storage/Storage/Storage.generated.format.ps1xml
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#15303 Add Datadog links in hub page
  documentation/azure-powershell-modules.md
Labels: Waiting for CI :shipit:

#15285 Print default log of auto gen module to verbose stream
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/AzModule.cs
Labels: Waiting for CI :shipit:

#15101 [Tools]Throw exception if a solution reference a not exist csproj.
  tools/CreateFilterMappings.ps1
Labels: needs-review

#15247 [SQL] Fix AutoRotationEnabled param
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/TransparentDataEncryption/Cmdlet/SetAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
  tools/StaticAnalysis/Exceptions/Az.Sql/BreakingChangeIssues.csv
Labels: Breaking Change Release, Waiting for CI :shipit:

#15298 Update Update-AzSqlDatabaseAdvancedThreatProtectionSetting to an updated version and allow storage account as an optional parameter
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ThreatDetectionTests/DisablingThreatDetection.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ThreatDetectionTests/ThreatDetectionDatabaseUpdatePolicy.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ThreatDetection/Services/SqlThreatDetectionAdapter.cs
  src/Sql/Sql/ThreatDetection/Services/ThreatDetectionEndpointsCommunicator.cs
  src/Sql/Sql/help/Update-AzSqlDatabaseAdvancedThreatProtectionSetting.md
Labels: needs-revision

#15299 Set-AzVMOperatingSystem AssessmentMode parameter
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineAssessmentMode.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMOperatingSystemCommand.cs
  src/Compute/Compute/help/Set-AzVMOperatingSystem.md
Labels: Waiting for CI :shipit:

#15098 fix typo in regulatory compliance
  src/Security/Security.Test/ScenarioTests/SecurityRegulatoryComplinceTests.ps1
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetAssessmentResourceId.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetAssessmentSubscriptionLevelResource.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetAssessmentSubscriptionScope.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetControlResourceId.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetControlSubscriptionLevelResource.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetControlSubscriptionScope.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetStandardResourceId.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetStandardSubscriptionLevelResource.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecurityRegulatoryComplinceTests/GetStandardSubscriptionScope.json
  src/Security/Security/Az.Security.psd1
  src/Security/Security/ChangeLog.md
  src/Security/Security/Cmdlets/RegulatoryCompliance/GetRegulatoryComplianceAssessment.cs
  src/Security/Security/help/Az.Security.md
  src/Security/Security/help/Get-AzRegulatoryComplianceAssessment.md
  tools/Az.Tools.Predictor/Az.Tools.Predictor/command_param_to_resource_map.json
  tools/AzPreview/AzPreview.psm1
Labels: Security, Waiting for CI :shipit:

#15330 HOTFIX Update Add-AzVmssNetworkInterfaceConfiguration
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssNetworkInterfaceConfigurationCommand.cs
Labels: Waiting for CI :shipit:

#15326 [Tools] Copy only changed file to tmp folder for security check
  .gitignore
  build.proj
  tools/PrepareForSecurityCheck.ps1
  tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.dll.json
Labels: Waiting for CI :shipit:

#15328 Update docs and examples for sql vulnerability assessment cmdlets
  src/Security/Security/help/Add-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  src/Security/Security/help/Get-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  src/Security/Security/help/Get-AzSecuritySqlVulnerabilityAssessmentScanRecord.md
  src/Security/Security/help/Get-AzSecuritySqlVulnerabilityAssessmentScanResult.md
  src/Security/Security/help/Remove-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  src/Security/Security/help/Set-AzSecuritySqlVulnerabilityAssessmentBaseline.md
Labels: Waiting for CI :shipit:

#15264 [DataFactory] Add Encryption settings to Data Factory
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.cs
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.DataFactoryTests/TestCreateDataFactoryV2WithCMK.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/DataFactories/SetAzureDataFactoryCommand.cs
  src/DataFactory/DataFactoryV2/DataFactories/UpdateAzureDataFactoryCommand.cs
  src/DataFactory/DataFactoryV2/Models/CreatePSDataFactoryParameters.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.DataFactories.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryParametersBase.cs
  src/DataFactory/DataFactoryV2/Models/PSDataFactory.cs
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2.md
  src/DataFactory/DataFactoryV2/help/Update-AzDataFactoryV2.md
Labels: Waiting for CI :shipit:

#15306 fix Update-AzVmss, Update-AzVm
  src/Compute/Compute.Test/ScenarioTests/DiagnosticsExtensionTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiagnosticsExtensionTests/TestVmssDiagnosticsExtension.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetAutoRollback.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetIdentity.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetNewEncryptionAtHost.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetPriority.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetReimageUpdate.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetUpdate.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetWriteAcceleratorUpdate.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
Labels: needs-revision

#15339 Enable Available Zones when creating hub Firewalls
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallVirtualHubCRUDWithZones.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:

#15349 Vmss OrchestrationMode
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetOrchestrationVM.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
Labels: Waiting for CI :shipit:

#15352 Fixed bug for `Set-AzActionRule` when RecurrenceType is "Once" and no "ReccurentValue" provided [#14476]
  src/AlertsManagement/AlertsManagement.sln
  src/AlertsManagement/AlertsManagement/ActionRuleCommands/SetAzureActionRule.cs
  src/AlertsManagement/AlertsManagement/ChangeLog.md
Labels: Waiting for CI :shipit:

#15350 [S189] Fix for Partial PUT that causes Update Server operations to fail for policies with 'DENY' effect
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/CreateandUpdateServerWithMinimalTlsVersion.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithIdentity.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithPublicNetworkAccess.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithRestrictOutboundNetworkAccess.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithoutIdentity.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
Labels: Waiting for CI :shipit:

#15353 Fixed bug for `Add-AzAutoscaleSetting` not able to pipe result from `Get-AzAutoScaleSetting` [#13861]
  src/Monitor/Monitor/Autoscale/AddAzureRmAutoscaleSettingCommand.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/help/Add-AzAutoscaleSetting.md
  tools/StaticAnalysis/Exceptions/Az.Monitor/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15325 [Urgent for Public Preview] Modify BackupShortTermRetentionPolicy Powershell Command
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseBackupTests.ps1
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/GetAzureSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Cmdlet/SetAzureSqlDatabaseBackupShortTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseBackupShortTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/help/Get-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  src/Sql/Sql/help/Set-AzSqlDatabaseBackupShortTermRetentionPolicy.md
  tools/StaticAnalysis/Exceptions/Az.Sql/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15362 Adding support for setting analytical storage schema type on account create/update for CosmosDB
  src/CosmosDB/CosmosDB.Test/ScenarioTests/AccountTests.cs
  src/CosmosDB/CosmosDB.Test/ScenarioTests/AccountTests.ps1
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.AccountTests/TestAnalyticalStorageSchemaTypeNewAccount.json
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.AccountTests/TestAnalyticalStorageSchemaTypeUpdateAccount.json
  src/CosmosDB/CosmosDB.sln
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewOrUpdateAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/Helpers/Constants.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSAnalyticalStorageConfiguration.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSDatabaseAccountGetResults.cs
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBAccount.md
  src/CosmosDB/CosmosDB/help/Update-AzCosmosDBAccount.md
Labels: customer-reported

#15359 Adding note for alternate commands
  src/OperationalInsights/OperationalInsights/help/Get-AzOperationalInsightsIntelligencePack.md
Labels: customer-reported

#15297 [Compute] DiskRP 2020_12_01 New and Changed Cmdlets
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.cs
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestAutomaticKeyRotation.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskPurchasePlan.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskSkuPremiumZRSStandardSSDZRS.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskSupportsHibernation.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureDiskPurchasePlanConfig.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskUpdateConfigCommand.cs
  src/Compute/Compute/Generated/Disk/Config/SetAzDiskSecurityProfile.cs
  src/Compute/Compute/Generated/DiskEncryptionSet/Config/NewAzureRmDiskEncryptionSetConfigCommand.cs
  src/Compute/Compute/Generated/DiskEncryptionSet/DiskEncryptionSetUpdateMethod.cs
  src/Compute/Compute/Generated/Models/PSDisk.cs
  src/Compute/Compute/Generated/Models/PSDiskEncryptionSet.cs
  src/Compute/Compute/Generated/Models/PSDiskUpdate.cs
  src/Compute/Compute/Generated/Models/PSSnapshot.cs
  src/Compute/Compute/Generated/Models/PSSnapshotUpdate.cs
  src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotConfigCommand.cs
  src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotUpdateConfigCommand.cs
  src/Compute/Compute/Models/PSPurchasePlan.cs
  src/Compute/Compute/help/New-AzDiskConfig.md
  src/Compute/Compute/help/New-AzDiskEncryptionSetConfig.md
  src/Compute/Compute/help/New-AzDiskPurchasePlanConfig.md
  src/Compute/Compute/help/New-AzDiskUpdateConfig.md
  src/Compute/Compute/help/New-AzSnapshotConfig.md
  src/Compute/Compute/help/New-AzSnapshotUpdateConfig.md
  src/Compute/Compute/help/Set-AzDiskSecurityProfile.md
  src/Compute/Compute/help/Update-AzDiskEncryptionSet.md
Labels: Compute, Compute - Managed Disks, Waiting for CI :shipit:

#15367 bugfix for get-azmetric
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/OutputClasses/PSMetric.cs
Labels: Waiting for CI :shipit:

#15341 Add public ip address as a parameter in New-AzRouteServer
  src/Network/Network.Test/ScenarioTests/RouteServerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteServerTests/TestRouteServerCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteServerTests/TestRouteServerPeerCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteServerTests/TestRouteServerPeerRoutes.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/Models/PSHubIpConfiguration.cs
  src/Network/Network/Generated/Models/PSRouteServer.cs
  src/Network/Network/RouteServer/NewAzureRMRouteServerCommand.cs
  src/Network/Network/help/New-AzRouteServer.md
Labels: needs-revision

#15360 Adding note for alternate commands
  src/OperationalInsights/OperationalInsights/help/Set-AzOperationalInsightsIntelligencePack.md
Labels: customer-reported

#15338 [SQL] Bug fix for UMI
  src/Sql/Sql/Auditing/Services/AuditingEndpointsCommunicator.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/ResourceIdentityHelper.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlServer.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlServer.md
Labels: Waiting for CI :shipit:

#15373 [DataFactroy] Updated ADF .Net SDK version to 4.20.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: needs-revision
