Repository Azure/azure-powershell, pull requests merged in 2021-04, with the labels that each got.

#14565 [Automation] Fixed time zone issue while creating an update deployment schedule
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClientSoftwareUpdateConfiguration.cs
Labels: Do Not Merge :no_entry_sign:, needs-revision

#14661 Fixed a bug for Get-AzKeyVaultSecret -AsPlainText
  src/KeyVault/KeyVault.Test/PesterTests/Secret.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/GetAzureKeyVaultSecret.cs
Labels: Waiting for CI :shipit:

#14650 [StreamAnalytics]Add breaking change message for the cmdlet.
  src/StreamAnalytics/StreamAnalytics/ChangeLog.md
  src/StreamAnalytics/StreamAnalytics/Function/GetAzureStreamAnalyticsFunctionCommand.cs
  src/StreamAnalytics/StreamAnalytics/Function/GetAzureStreamAnalyticsFunctionDefaultDefinitionCommand.cs
  src/StreamAnalytics/StreamAnalytics/Function/NewAzureStreamAnalyticsFunctionCommand.cs
  src/StreamAnalytics/StreamAnalytics/Function/RemoveAzureStreamAnalyticsFunctionCommand.cs
  src/StreamAnalytics/StreamAnalytics/Function/TestAzureStreamAnalyticsFunctionCommand.cs
  src/StreamAnalytics/StreamAnalytics/Input/GetAzureStreamAnalyticsInputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Input/NewAzureStreamAnalyticsInputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Input/RemoveAzureStreamAnalyticsInputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Input/TestAzureStreamAnalyticsInputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Job/GetAzureStreamAnalyticsJobCommand.cs
  src/StreamAnalytics/StreamAnalytics/Job/NewAzureStreamAnalyticsJobCommand.cs
  src/StreamAnalytics/StreamAnalytics/Job/RemoveAzureStreamAnalyticsJobCommand.cs
  src/StreamAnalytics/StreamAnalytics/Job/StartAzureStreamAnalyticsJobCommand.cs
  src/StreamAnalytics/StreamAnalytics/Job/StopAzureStreamAnalyticsJobCommand.cs
  src/StreamAnalytics/StreamAnalytics/Output/GetAzureStreamAnalyticsOutputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Output/NewAzureStreamAnalyticsOutputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Output/RemoveAzureStreamAnalyticsOutputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Output/TestAzureStreamAnalyticsOutputCommand.cs
  src/StreamAnalytics/StreamAnalytics/Subscription/GetAzureStreamAnalyticsQuotasCommand.cs
  src/StreamAnalytics/StreamAnalytics/Transformation/GetAzureStreamAnalyticsTransformationCommand.cs
  src/StreamAnalytics/StreamAnalytics/Transformation/NewAzureStreamAnalyticsTransformationCommand.cs
Labels: Do Not Merge :no_entry_sign:, Service Attention, Stream Analytics

#14660 [Resource]Add parameters breaking change warnings for IdentifierUri and DisplayName.
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADApplicationCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADApplicationCommand.cs
  src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADServicePrincipalCommand.cs
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#14607 Add vulnerability assessment cmdlets for IAAS in Az.Security
  src/Security/Security.Test/ScenarioTests/SqlVulnerabilityAssessmentTests.cs
  src/Security/Security.Test/ScenarioTests/SqlVulnerabilityAssessmentTests.ps1
  src/Security/Security.Test/ScenarioTests/TestController.cs
  src/Security/Security.Test/Security.Test.csproj
  src/Security/Security.Test/SqlVulnerabilityAssessmentTestResources/SetUpVM.ps1
  src/Security/Security/Az.Security.psd1
  src/Security/Security/ChangeLog.md
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/AddSecuritySqlVulnerabilityAssessmentBaseline.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/Common/SqlVulnerabilityAssessmentBaseWithBaseline.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/Common/SqlVulnerabilityAssessmentCmdlet.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/Common/VulnerabilityAssessmentConstants.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/GetSecuritySqlVulnerabilityAssessmentBaseline.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/GetSecuritySqlVulnerabilityAssessmentScanRecord.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/GetSecuritySqlVulnerabilityAssessmentScanResult.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/RemoveSecuritySqlVulnerabilityAssessmentBaseline.cs
  src/Security/Security/Cmdlets/SqlVulnerabilityAssessment/SetSecuritySqlVulnerabilityAssessmentBaseline.cs
  src/Security/Security/Common/ParameterHelpMessages.cs
  src/Security/Security/Common/ParameterSetNames.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentBaseline.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentBaselineAdjustedResult.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentBaselineResults.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentConverters.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentQueryCheck.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentRemediation.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentRule.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentRuleBaselineResults.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentScanRecord.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityAssessmentScanResult.cs
  src/Security/Security/Models/SqlVulnerabilityAssessment/PSSqlVulnerabilityBenchmarkReference.cs
  src/Security/Security/help/Add-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  src/Security/Security/help/Get-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  src/Security/Security/help/Get-AzSecuritySqlVulnerabilityAssessmentScanRecord.md
  src/Security/Security/help/Get-AzSecuritySqlVulnerabilityAssessmentScanResult.md
  src/Security/Security/help/Remove-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  src/Security/Security/help/Set-AzSecuritySqlVulnerabilityAssessmentBaseline.md
  tools/ScenarioTest.ResourceManager/Assert.ps1
Labels: Waiting for CI :shipit:

#14679 [CloudService]Remove link in custom files
  src/CloudService/custom/Get-AzCloudServiceNetworkInterface.ps1
  src/CloudService/custom/Get-AzCloudServicePublicIPAddress.ps1
  src/CloudService/custom/New-AzCloudServiceDiagnosticsExtension.ps1
  src/CloudService/custom/New-AzCloudServiceExtensionObject.ps1
  src/CloudService/custom/New-AzCloudServiceLoadBalancerConfigurationObject.ps1
  src/CloudService/custom/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.ps1
  src/CloudService/custom/New-AzCloudServiceRemoteDesktopExtensionObject.ps1
  src/CloudService/custom/New-AzCloudServiceRoleProfilePropertiesObject.ps1
  src/CloudService/custom/New-AzCloudServiceVaultSecretGroupObject.ps1
  src/CloudService/docs/Get-AzCloudServiceNetworkInterfaces.md
  src/CloudService/docs/Get-AzCloudServicePublicIPAddress.md
  src/CloudService/docs/New-AzCloudServiceDiagnosticsExtension.md
  src/CloudService/docs/New-AzCloudServiceExtensionObject.md
  src/CloudService/docs/New-AzCloudServiceLoadBalancerConfigurationObject.md
  src/CloudService/docs/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.md
  src/CloudService/docs/New-AzCloudServiceRemoteDesktopExtensionObject.md
  src/CloudService/docs/New-AzCloudServiceRoleProfilePropertiesObject.md
  src/CloudService/docs/New-AzCloudServiceVaultSecretGroupObject.md
Labels: Generator

#14281 Fallback to first available context as DefaultContext if current default context key is 'Default'
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication.ResourceManager/AzureRmProfile.cs
  src/Accounts/Authentication.ResourceManager/Constants.cs
Labels: Waiting for CI :shipit:

#14673 [SQL] Add breaking change warning
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/GetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/RemoveAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Replication/Cmdlet/GetAzureSqlDatabaseReplicationLink.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseCopy.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Cmdlet/RemoveAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Cmdlet/SetAzureSqlDatabaseSecondary.cs
Labels: needs-revision

#14689 Add more logs in Az.Accounts before calling into Azure.Identity
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Authentication.Test/Mocks/MockMsalAccessTokenAcquirer.cs
  src/Accounts/Authenticators/AccessTokenAuthenticator.cs
  src/Accounts/Authenticators/DeviceCodeAuthenticator.cs
  src/Accounts/Authenticators/InteractiveUserAuthenticator.cs
  src/Accounts/Authenticators/ManagedServiceIdentityAuthenticator.cs
  src/Accounts/Authenticators/MsalAccessToken.cs
  src/Accounts/Authenticators/MsalAccessTokenAcquirer.cs
  src/Accounts/Authenticators/ServicePrincipalAuthenticator.cs
  src/Accounts/Authenticators/SilentAuthenticator.cs
  src/Accounts/Authenticators/UsernamePasswordAuthenticator.cs
Labels: Waiting for CI :shipit:

#14622 Change default Size value in New-AzVM to Standard_D2S_v3
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestNewAzVMDefaultingSize.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
Labels: needs-revision

#14172 Updated support for synapse role assignment and Added support for role scope
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/GetAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/GetAzureSynapseRoleScope.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/NewAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/RemoveAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Common/Utils.cs
  src/Synapse/Synapse/Models/PSRoleAssignmentDetails.cs
  src/Synapse/Synapse/Models/PSSynapseRole.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsRoleClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/Synapse.csproj
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Get-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Get-AzSynapseRoleScope.md
  src/Synapse/Synapse/help/New-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Remove-AzSynapseRoleAssignment.md
Labels: Do Not Merge :no_entry_sign:

#14716 Example 2 to use New-AzPolicyExemption
  src/Resources/Resources/help/New-AzPolicyExemption.md
Labels: customer-reported

#14719 Update Location explanation
  src/Migrate/help/New-AzMigrateProject.md
Labels: customer-reported

#14704 Update Get-AzEnvironment.md
  src/Accounts/Accounts/help/Get-AzEnvironment.md
Labels: customer-reported

#14749 [BotService]Remove transform in readme.md
  src/BotService/readme.md
Labels: Generator

#14743 Example with wrong parameter (typo)
  src/Compute/Compute/help/Update-AzGalleryImageVersion.md
Labels: customer-reported

#14737 Adjusted casing of cmdlet name in examples to match definition
  src/Sql/Sql/help/Get-AzSqlServerDnsAlias.md
Labels: customer-reported

#14773 fixing typo
  src/Network/Network/help/Get-AzVirtualNetwork.md
Labels: customer-reported

#14770 Fixed typos in Restore-AzApiManagement
  src/ApiManagement/ApiManagement/help/Restore-AzApiManagement.md
Labels: customer-reported

#14672 [DataFactory] Add User Assigned Identity to DataFactory
  src/DataFactory/DataFactory.sln
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.cs
  src/DataFactory/DataFactoryV2.Test/ScenarioTests/DataFactoryTests.ps1
  src/DataFactory/DataFactoryV2.Test/SessionRecords/Microsoft.Azure.Commands.DataFactoryV2.Test.DataFactoryTests/TestCreateDataFactoryV2WithUserAssignedIdentity.json
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/Constants.cs
  src/DataFactory/DataFactoryV2/DataFactories/SetAzureDataFactoryCommand.cs
  src/DataFactory/DataFactoryV2/Models/CreatePSDataFactoryParameters.cs
  src/DataFactory/DataFactoryV2/Models/DataFactoryClient.DataFactories.cs
  src/DataFactory/DataFactoryV2/help/Set-AzDataFactoryV2.md
Labels: Waiting for CI :shipit:

#14779 fixing a typo
  src/AlertsManagement/AlertsManagement/help/Get-AzAlert.md
Labels: customer-reported

#14803 User identity changes
  src/Automation/Automation.Test/ScenarioTests/HybridWorkerGroupTests.ps1
  src/Automation/Automation.Test/ScenarioTests/ModuleTests.ps1
  src/Automation/Automation.Test/ScenarioTests/UpdateManagementTests.ps1
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.HybridWorkerGroupTests/E2EHybridWorkerGroup.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.ModuleTests/SetModule.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.UpdateDynamicGroupPrePostTests/TestCreateAndGetSoftwareUpdateConfigurationWithPrePost.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllMachineRuns.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.UpdateManagementTests/GetAllSUCs.json
  src/Automation/Automation.Test/UnitTests/NewAzureAutomationAccountTest.cs
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Cmdlet/NewAzureAutomationAccount.cs
  src/Automation/Automation/Cmdlet/SetAzureAutomationAccount.cs
  src/Automation/Automation/Common/AutomationPSClient.cs
  src/Automation/Automation/Common/IAutomationPSClient.cs
  src/Automation/Automation/Model/AutomationAccount.cs
  src/Automation/Automation/help/New-AzAutomationAccount.md
  src/Automation/Automation/help/Set-AzAutomationAccount.md
Labels: customer-reported

#14731 [Storage] Support User Assigned Identity
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestAzureStorageAccountUserAssignedIdentity.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/StorageAccountBaseCmdlet.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
Labels: need-review

#14767 Remove principaltype in Synapse Role-based access control
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/AccessControl/NewAzureSynapseRoleAssignment.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Common/Utils.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsRoleClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/help/New-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Remove-AzSynapseRoleAssignment.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/BreakingChangeIssues.csv
Labels: ready to review

#14813 Update Get-AzNetworkWatcherNextHop.md for $VM object properties
  src/Network/Network/help/Get-AzNetworkWatcherNextHop.md
Labels: customer-reported

#14785 Added support for getting a single private link resource
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkResource/GetAzurePrivateLinkResourceCommand.cs
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/GenericProvider.cs
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
  src/Network/Network/help/Get-AzPrivateLinkResource.md
Labels: Waiting for CI :shipit:

#14850 Azure stack fix
  NuGet.Config
  src/Accounts/Accounts/Accounts.csproj
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetCorePreloadAssemblies/Microsoft.Bcl.AsyncInterfaces.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Microsoft.Bcl.AsyncInterfaces.dll
  tools/CheckAssemblies.ps1
  tools/PreloadToolDll.ps1
Labels: needs-review

#14801 [AzureStack] Fix Az.Storage module dll issue
  src/Storage/Storage.Management/Az.Storage.psd1
Labels: need-review
