Repository Azure/azure-powershell, pull requests merged in 2021-07, with the labels that each got.

#15364 AzFunctions: Add additional app settings for Consumption apps, allow empty app settings, and add suffix to connection strings in app settings
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
  src/Functions/custom/HelperFunctions.ps1
  src/Functions/custom/New-AzFunctionApp.ps1
  src/Functions/test/Get-AzFunctionApp.Recording.json
  src/Functions/test/Get-AzFunctionApp.Tests.ps1
  src/Functions/test/Get-AzFunctionAppAvailableLocation.Recording.json
  src/Functions/test/Get-AzFunctionAppPlan.Recording.json
  src/Functions/test/Get-Update-Remove-AzFunctionAppSetting.Recording.json
  src/Functions/test/New-AzFunctionApp.Recording.json
  src/Functions/test/New-AzFunctionApp.Tests.ps1
  src/Functions/test/New-AzFunctionAppPlan.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionAppPlan.Recording.json
  src/Functions/test/Restart-Start-Stop-AzFunctionApp.Recording.json
  src/Functions/test/env.json
  src/Functions/test/helper.ps1
  src/Functions/test/utils.ps1
Labels: Waiting for CI :shipit:

#15333 Adding new parameters for CustomIpPrefix
  src/Network/Network/BYOIP/CustomIpPrefix/NewAzureCustomIpPrefixCommand.cs
  src/Network/Network/BYOIP/CustomIpPrefix/UpdateAzureCustomIpPrefixCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/BYOIP/PSCustomIpPrefix.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/Get-AzCustomIpPrefix.md
  src/Network/Network/help/New-AzCustomIpPrefix.md
  src/Network/Network/help/Update-AzCustomIpPrefix.md
Labels: ready to review

#15351 Update subscription client to 2021-01-01
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts.Test/AzureRMProfileTestsForMultitenant.cs
  src/Accounts/Accounts.Test/Mocks/MockSubscriptionClientFactory.cs
  src/Accounts/Accounts.Test/Mocks/MockSubscriptionClientFactoryVersion2019.cs
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.SubscriptionCmdletTests/GetSubscriptionsWithTags.json
  src/Accounts/Accounts.Test/SubscriptionClientSwitchTest.cs
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.cs
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.ps1
  src/Accounts/Accounts.Test/TenantCmdletMockTests.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/SubscriptionClientProxy.cs
  src/Accounts/Accounts/Models/Version2016_06_01/SubscriptionClientWrapper.cs
  src/Accounts/Accounts/Models/Version2021_01_01/SubscriptionClientWrapper.cs
  src/Accounts/Authentication.ResourceManager/Models/PSAzureSubscription.cs
  src/Accounts/Authentication.ResourceManager/Models/PSAzureTenant.cs
  src/Accounts/Authentication.Test/Cmdlets/ConnectAccount.cs
  src/Resources/Resources.Test/ScenarioTests/ResourcesController.cs
  src/StorageSync/StorageSync.Test/TestController.cs
Labels: Do Not Merge :no_entry_sign:, needs-review

#15376 Add a new line in doc to fix text attached to previous bullet item
  src/Compute/Compute/help/New-AzVMConfig.md
Labels: customer-reported

#15377 Add parameter ManagedResourceGroupName for command New-AzSynapseWorkspace
  src/Synapse/Synapse.Test/ScenarioTests/WorkspaceTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseWorkspace.json
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/NewAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/help/New-AzSynapseWorkspace.md
Labels: needs-revision

#15374 [Storage] Fix a regression in copy blob from blob object pipeline
  src/Storage/Storage/Blob/Cmdlet/StartAzureStorageBlobCopy.cs
Labels: Waiting for CI :shipit:

#15388 Update Remove-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Remove-AzDataLakeGen2Item.md
Labels: customer-reported

#15391 Update - Update Example (external VNET)
  src/ApiManagement/ApiManagement/help/Set-AzApiManagement.md
Labels: customer-reported

#15348 Add new parameter for New-AzPublicIpPrefix
  src/Network/Network/ChangeLog.md
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
  src/Network/Network/help/New-AzPublicIpAddress.md
Labels: Waiting for CI :shipit:

#15381 Cplat cloudservice2
  src/CloudService/custom/New-AzCloudService.ps1
  src/CloudService/custom/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.ps1
  src/CloudService/docs/New-AzCloudService.md
  src/CloudService/docs/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.md
  src/CloudService/examples/New-AzCloudService.md
  src/CloudService/examples/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.md
  src/CloudService/test/test-artifacts/ServiceDefinition.txt
  src/CloudService/test/utils.ps1
Labels: needs-revision

#15397 Added support for creating and setting Template Spec in Bicep file
  src/Resources/ResourceManager/Implementation/TemplateSpecs/NewAzTemplateSpec.cs
  src/Resources/ResourceManager/Implementation/TemplateSpecs/SetAzTemplateSpec.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzTemplateSpec.md
  src/Resources/Resources/help/Set-AzTemplateSpec.md
Labels: Waiting for CI :shipit:

#15406 [Storage] Support last access time
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageBlobTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageBlobTests/TestStorageBlobLastAccessTimeTracking.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/Blob/DisableAzureStorageBlobLastAccessTimeTracking.cs
  src/Storage/Storage.Management/Blob/EnableAzureStorageBlobLastAccessTimeTracking.cs
  src/Storage/Storage.Management/Blob/StorageBlobBaseCmdlet.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSBlobServiceProperties.cs
  src/Storage/Storage.Management/Models/PSDataPolicy.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/AddAzureStorageAccountManagementPolicyAction.cs
  src/Storage/Storage.Management/help/Add-AzStorageAccountManagementPolicyAction.md
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Disable-AzStorageBlobLastAccessTimeTracking.md
  src/Storage/Storage.Management/help/Enable-AzStorageBlobLastAccessTimeTracking.md
  src/Storage/Storage.Management/help/Get-AzStorageFileServiceProperty.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccountManagementPolicy.md
  src/Storage/Storage.Management/help/Update-AzStorageFileServiceProperty.md
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
Labels: needs-review

#15421 Add error termination rule for smoke test
  tools/Test/SmokeTest/ScriptsCaller.ps1
Labels: needs-review

#15403 [Synapse] - Enhance existing cmdlets to support the next generation of SQL pool (so called Gen3 or v3)
  src/Synapse/Synapse.Test/ScenarioTests/DataClassificationTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/FirewallTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SparkPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlDatabaseTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/SqlDatabaseTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolV3Tests.cs
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolV3Tests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/WorkspaceTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.DataClassificationTests/TestDataClassificationOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.DataClassificationTests/TestEnableDisableRecommendationsOnSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.FirewallTests/TestSynapseFirewall.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestAzureIntegrationRuntime.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestIntegrationRuntimePiping.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.IntegrationRuntimeTests/TestSelfHostedIntegrationRuntime.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SparkPoolTests/TestSynapseSparkPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlDatabaseTests/TestSynapseSqlDatabase.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestDroppedSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestRestoreFromRestorePoint.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestSqlPoolRestorePoint.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPoolSecurity.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolV3Tests/TestSynapseSqlPoolV3.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentBaseline.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentScanConvertTest.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.VulnerabilityAssessmentTests/TestVulnerabilityAssessmentScanRecordGetListTest.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseManagedIdentitySqlControlSetting.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseWorkspace.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseWorkspaceSecurity.json
  src/Synapse/Synapse.Test/Synapse.Test.csproj
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/IntegrationRuntimes/SetAzureSynapseIntegrationRuntime.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlDatabase/NewAzureSynapseSqlDatabase.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlDatabase/UpdateAzureSynapseSqlDatabase.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/RestoreAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/GetAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/NewAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/ResumeAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/SuspendAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/UpdateAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/NewAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Common/Utils.cs
  src/Synapse/Synapse/Models/PSSqlDatabaseStorageRedundancyType.cs
  src/Synapse/Synapse/Models/PSSynapseSku.cs
  src/Synapse/Synapse/Models/PSSynapseSqlDatabase.cs
  src/Synapse/Synapse/Models/PSSynapseSqlPool.cs
  src/Synapse/Synapse/Models/PSSynapseSqlPoolV3.cs
  src/Synapse/Synapse/Models/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Synapse.csproj
  src/Synapse/Synapse/help/Get-AzSynapseSparkJobDefinition.md
  src/Synapse/Synapse/help/New-AzSynapseSqlDatabase.md
  src/Synapse/Synapse/help/New-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/New-AzSynapseWorkspace.md
  src/Synapse/Synapse/help/Resume-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Suspend-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Update-AzSynapseSqlPool.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/BreakingChangeIssues.csv
Labels: needs-revision

#15407 VM Defaulting Size warning improved
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: needs-revision

#15428 Fixed some typos for added clarity
  src/Security/Security/help/Get-AzRegulatoryComplianceStandard.md
Labels: Doc - Reference, Waiting for CI :shipit:, customer-reported

#15433 Generate Az.CloudService
  src/CloudService/Az.CloudService.psd1
  src/CloudService/Az.CloudService.psm1
  src/CloudService/Changelog.md
  src/CloudService/CloudService.sln
  src/CloudService/build-module.ps1
  src/CloudService/check-dependencies.ps1
  src/CloudService/create-model-cmdlets.ps1
  src/CloudService/custom/New-AzCloudService.ps1
  src/CloudService/custom/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.ps1
  src/CloudService/examples/New-AzCloudService.md
  src/CloudService/examples/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.md
  src/CloudService/exports/Invoke-AzCloudServiceRebuild.ps1
  src/CloudService/exports/Invoke-AzCloudServiceReimage.ps1
  src/CloudService/exports/New-AzCloudService.ps1
  src/CloudService/exports/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.ps1
  src/CloudService/exports/ProxyCmdletDefinitions.ps1
  src/CloudService/exports/Remove-AzCloudServiceRoleInstance.ps1
  src/CloudService/exports/Restart-AzCloudService.ps1
  src/CloudService/generate-info.json
  src/CloudService/generated/api/Models/Api20210301/CloudService.PowerShell.cs
  src/CloudService/generated/api/Models/Api20210301/Extension.PowerShell.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceInstanceView_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceOSFamily_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceOSFamily_GetViaIdentity.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceOSFamily_List.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceOSVersion_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceOSVersion_GetViaIdentity.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceOSVersion_List.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceRoleInstanceRemoteDesktopFile_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceRoleInstanceView_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceRoleInstance_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceRoleInstance_GetViaIdentity.cs
  src/CloudService/generated/cmdlets/GetAzCloudServiceRoleInstance_List.cs
  src/CloudService/generated/cmdlets/GetAzCloudService_Get.cs
  src/CloudService/generated/cmdlets/GetAzCloudService_GetViaIdentity.cs
  src/CloudService/generated/cmdlets/GetAzCloudService_List.cs
  src/CloudService/generated/cmdlets/GetAzCloudService_List1.cs
  src/CloudService/generated/runtime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
  src/CloudService/generated/runtime/BuildTime/MarkdownRenderer.cs
  src/CloudService/generated/runtime/BuildTime/Models/PsProxyOutputs.cs
  src/CloudService/generated/runtime/BuildTime/Models/PsProxyTypes.cs
  src/CloudService/generated/runtime/Extensions.cs
  src/CloudService/help/New-AzCloudService.md
  src/CloudService/help/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.md
  src/CloudService/run-module.ps1
  src/CloudService/test-module.ps1
  src/CloudService/test/test-artifacts/ServiceDefinition.txt
  src/CloudService/test/utils.ps1
Labels: Waiting for CI :shipit:

#15434 Fix smoke test error action stop
  tools/Test/SmokeTest/ScriptsCaller.ps1
Labels: Waiting for CI :shipit:

#15436 [DataFactory]Fix the command `Get-AzDataFactoryV2LinkedService` doc issue
  src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2LinkedService.md
Labels: Doc - Reference, needs-revision

#15442 BUG fix: Remove managed disk properties for Update VM properties for A2A if not given by user
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/SetAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Recovery Services Site-Recovery, Waiting for CI :shipit:

#15451 Add AzPreview to azure-powershell-modules.md
  documentation/azure-powershell-modules.md
Labels: Doc - Reference, needs-review

#15438 [Storage] List all datalakegen2 items by default
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2ChildItem.md
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
Labels: needs-review

#15450 Unblock Service Tag limited permission scenario
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AccessRestriction/AddAzureWebAppAccessRestrictionRule.cs
Labels: needs-review

#15420 Disable context auto saving when token persistence check fails
  src/Accounts/Accounts.Test/OnImportTests.cs
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
Labels: needs-revision

#15459 [SQL] Fix identity logic for Set-AzSqlServer
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/ResourceIdentityHelper.cs
Labels: needs-review

#15106 #10783 - Fix for Get-AzResource returning PSResource with null SubscriptionId
  src/Resources/ResourceManager/SdkModels/Resources/PSResource.cs
  src/Resources/Resources.Test/Resource/GetAzureResourceCommandTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: ARM, Service Attention, customer-reported, needs-revision

#15368 [Az.RecoveryServices.Backup] Adding Archive for V1 vaults
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileSharePolicy.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureVmWorkloadPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureWorkloadRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/OperationStatusAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/RecoveryPointsAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVMGetContainers.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureUnmanagedVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMDiskExclusion.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetItems.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMRPMountScript.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMSetVaultContext.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureFSGetJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMCancelJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobsTimeFilter.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMWaitJob.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/RecoveryPoint/GetAzureRmRecoveryServicesBackupRecommendedArchivableRPGroup.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/RecoveryPoint/GetAzureRmRecoveryServicesBackupRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/RecoveryPoint/MoveAzureRmRecoveryServicesBackupRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Test/RecoveryServices.Test.csproj
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Move-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: needs-review

#15453 [Synapse] - revert sqlv3 public preview change
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolV3Tests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlDatabaseTests/TestSynapseSqlDatabase.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolV3Tests/TestSynapseSqlPoolV3.json
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SqlDatabase/NewAzureSynapseSqlDatabase.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlDatabase/UpdateAzureSynapseSqlDatabase.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/GetAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/NewAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/ResumeAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/SuspendAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool/UpdateAzureSynapseSqlPool.cs
  src/Synapse/Synapse/help/New-AzSynapseSqlDatabase.md
  src/Synapse/Synapse/help/New-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Resume-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Suspend-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Update-AzSynapseSqlDatabase.md
  src/Synapse/Synapse/help/Update-AzSynapseSqlPool.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/BreakingChangeIssues.csv
Labels: needs-review

#15455 Update Get-AzPolicyState.md
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyState.md
Labels: customer-reported

#15437 Upgrade Azure.Core to 1.16.0
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#15466 [Service Fabric] Fix service fabric cmdlet piping issue by updating model constructors
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/Common.ps1
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/ServiceFabricApplicationTests.ps1
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/ServiceFabricManagedClustersApplicationTests.ps1
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.ServiceFabricApplicationTests/TestApp.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.ServiceFabricManagedClustersApplicationTests/TestManagedApp.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.ServiceFabricManagedClustersApplicationTests/TestManagedAppType.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.ServiceFabricManagedClustersApplicationTests/TestManagedAppTypeVersion.json
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.ServiceFabricManagedClustersApplicationTests/TestManagedService.json
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/ServiceFabric/ServiceFabric/Models/ManagedClusters/PSManagedApplication.cs
  src/ServiceFabric/ServiceFabric/Models/ManagedClusters/PSManagedCluster.cs
  src/ServiceFabric/ServiceFabric/Models/ManagedClusters/PSManagedService.cs
  src/ServiceFabric/ServiceFabric/Models/PSApplication.cs
  src/ServiceFabric/ServiceFabric/Models/PSCluster.cs
Labels: needs-review

#15465 [Storage] fix issue 15460
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Common/AzureStorageBlob.cs
  src/Storage/Storage/Common/AzureStorageContainer.cs
  src/Storage/Storage/Common/AzureStorageFile.cs
  src/Storage/Storage/Common/AzureStorageFileDirectory.cs
  src/Storage/Storage/Common/AzureStorageFileShare.cs
  src/Storage/Storage/Common/AzureStorageQueue.cs
  src/Storage/Storage/Common/Util.cs
  src/Storage/Storage/Storage.csproj
Labels: needs-review

#15468 Remove AzPreview.psm1
  tools/AzPreview/AzPreview.psm1
Labels: Waiting for CI :shipit:

#15446 Fix access error when subscripiton has no Tags property
  src/Accounts/Accounts.Test/UnitTest/PSAzureSubscriptionTest.cs
  src/Accounts/Authentication.ResourceManager/Models/PSAzureSubscription.cs
  tools/Common.Netcore.Dependencies.targets
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: Waiting for CI :shipit:

#15476 Example 1: "blob" --> "container"
  src/Storage/Storage.Management/help/Get-AzStorageContainer.md
Labels: customer-reported

#15467 Add Key Vault virtual machine extension examples and suggestions
  src/Compute/Compute/help/Add-AzVMSecret.md
  src/Compute/Compute/help/Add-AzVmssSecret.md
Labels: Doc - Reference, Waiting for CI :shipit:

#14567 CAE
  src/Accounts/Accounts.Test/SilentReAuthByTenantCmdletTest.cs
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/ContextAdapter.cs
  src/Accounts/Accounts/Models/Version2016_06_01/SubscriptionClientWrapper.cs
  src/Accounts/Accounts/Models/Version2021_01_01/SubscriptionClientWrapper.cs
  src/Accounts/Accounts/Tenant/GetAzureRMTenant.cs
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
  src/Accounts/Authentication.Test/AuthenticatorsTest/SilentAuthenticatorTests.cs
  src/Accounts/Authentication/Authentication/AuthenticationFailedExceptionExtention.cs
  src/Accounts/Authentication/Authentication/IClaimsChallengeProcessor.cs
  src/Accounts/Authentication/Authentication/RenewingTokenCredential.cs
  src/Accounts/Authentication/Authentication/TokenCache/PowerShellTokenCacheProvider.cs
  src/Accounts/Authentication/ClaimsChallengeHandler.cs
  src/Accounts/Authentication/Factories/ClientFactory.cs
  src/Accounts/Authentication/Utilities/ClaimsChallengeUtilities.cs
  src/Accounts/Authenticators/Factories/AzureCredentialFactory.cs
  src/Accounts/Authenticators/MsalAccessToken.cs
  src/Accounts/Authenticators/SilentAuthenticator.cs
  tools/ScenarioTest.ResourceManager/Mocks/MockTokenAuthenticationFactory.cs
Labels: needs-review

#15493 Fix parameter name in examples
  src/Network/Network/help/Sync-AzVirtualNetworkPeering.md
Labels: customer-reported

#15473 Refine generatehelp.ps1
  tools/GenerateHelp.ps1
  tools/NewHelpIndex.ps1
Labels: needs-review

#15487 [Tools]Add pipeline to sync tools folder
  .azure-pipelines/sync-tools-folder.yml
Labels: needs-review

#15488 Add missed generated module
  tools/GeneratedModuleList.txt
Labels: Waiting for CI :shipit:

#15498 Remove unused imports and classes
  src/HealthcareApis/HealthcareApis/Common/ActiveDirectoryClientWrapper.cs
  src/HealthcareApis/HealthcareApis/Common/HealthcareApisBaseCmdlet.cs
  src/HealthcareApis/HealthcareApis/Common/HealthcareApisManagementClientWrapper.cs
  src/Network/Network/NetworkVirtualAppliance/GetNetworkVirtualApplianceCommand.cs
  src/Support/Support/ProblemClassifications/GetAzSupportProblemClassification.cs
  src/Support/Support/Services/GetAzSupportService.cs
  src/Websites/Websites/Utilities/CmdletHelpers.cs
Labels: needs-review

#15464 Add AzPreview link to main readme
  README.md
Labels: needs-review

#15492 fix breaking changes introduced by #15353
  src/Monitor/Monitor/Autoscale/AddAzureRmAutoscaleSettingCommand.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/help/Add-AzAutoscaleSetting.md
  tools/StaticAnalysis/Exceptions/Az.Monitor/BreakingChangeIssues.csv
Labels: needs-revision

#15480 AppService: Removed TestSetAzureStorageWebAppHyperVSlot test.
  src/Websites/Websites.Test/ScenarioTests/WebAppSlotTests.cs
  src/Websites/Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestSetAzureStorageWebAppHyperVSlot.json
Labels: More Info :label:, needs-review

#15497 Add script to install module
  tools/Installer/InstallModule.ps1
Labels: Waiting for CI :shipit:

#15496 Added Subnet' property to new-AzLoadBalancerBackendAddressConfig cmdlet. Fixed piping in Set/Remove loadBalancerBackendPool cmdlets
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendAddressConfig.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolCreate.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolDelete.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/LoadBalancer/NewAzLoadBalancerBackendAddressConfig.cs
  src/Network/Network/LoadBalancer/RemoveAzureLoadBalancerBackendPool.cs
  src/Network/Network/LoadBalancer/SetAzureLoadBalancerBackendPool.cs
  src/Network/Network/Models/PSLoadBalancerBackendAddress.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/help/New-AzLoadBalancerBackendAddressConfig.md
  src/Network/Network/help/Remove-AzLoadBalancerBackendAddressPool.md
  src/Network/Network/help/Set-AzLoadBalancerBackendAddressPool.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#15419 Set-AzVMOperatingSystem: EnableAutoUpdate no longer overwrites existing value
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineEnableAutoUpdate.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMOperatingSystemCommand.cs
Labels: needs-review

#15512 Update New-AzNetworkSecurityGroup.md
  src/Network/Network/help/New-AzNetworkSecurityGroup.md
Labels: customer-reported

#15518 Update GA module versions and regenerate
  src/AppConfiguration/.gitignore
  src/AppConfiguration/Az.AppConfiguration.psd1
  src/AppConfiguration/custom/readme.md
  src/AppConfiguration/readme.md
  src/AppConfiguration/utils/Unprotect-SecureString.ps1
  src/Databricks/.gitignore
  src/Databricks/Az.Databricks.psd1
  src/Databricks/readme.md
  src/Kusto/Az.Kusto.psd1
  src/Kusto/custom/readme.md
  src/Kusto/docs/readme.md
  src/Kusto/how-to.md
  src/Kusto/readme.md
  src/Kusto/tools/Resources/docs/readme.md
  src/Kusto/tools/Resources/how-to.md
  src/ResourceMover/.gitignore
  src/ResourceMover/Az.ResourceMover.psd1
  src/ResourceMover/custom/readme.md
  src/ResourceMover/docs/Get-AzResourceMoverRequiredForResources.md
  src/ResourceMover/docs/Invoke-AzResourceMoverBulkRemove.md
  src/ResourceMover/docs/readme.md
  src/ResourceMover/readme.md
  src/ResourceMover/resources/readme.md
  src/ResourceMover/test/readme.md
Labels: Waiting for CI :shipit:

#15511 update Az.Compute to use latest Compute SDK
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssSecurityProfileCommand.cs
  src/Compute/Compute/VirtualMachine/Config/SetAzureVMSecurityProfile.cs
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/Security/Security.Test/Security.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: needs-revision

#15503 Added subnet property to new-AzLoadBalancerBackendAddressConfig cmdlet. Fixed piping in Set/Remove-AzLoadBalancerBackendAddressPool
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendAddressConfig.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolCreate.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolDelete.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/LoadBalancer/NewAzLoadBalancerBackendAddressConfig.cs
  src/Network/Network/LoadBalancer/RemoveAzureLoadBalancerBackendPool.cs
  src/Network/Network/LoadBalancer/SetAzureLoadBalancerBackendPool.cs
  src/Network/Network/Models/PSLoadBalancerBackendAddress.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/help/New-AzLoadBalancerBackendAddressConfig.md
  src/Network/Network/help/Remove-AzLoadBalancerBackendAddressPool.md
  src/Network/Network/help/Set-AzLoadBalancerBackendAddressPool.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#15510 [Resources] Add -ProceedIfNoChange parameter to the New-Az*Deployment cmdlets
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentCreateCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureManagementGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureSubscriptionDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/Deployments/NewAzureTenantDeploymentCmdlet.cs
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Get-AzDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzManagementGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzResourceGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzTenantDeploymentWhatIfResult.md
  src/Resources/Resources/help/New-AzDeployment.md
  src/Resources/Resources/help/New-AzManagementGroupDeployment.md
  src/Resources/Resources/help/New-AzResourceGroupDeployment.md
  src/Resources/Resources/help/New-AzTenantDeployment.md
Labels: needs-review

#15527 Skip the breakingchange check for modules whoes version is less than 1.0.0
  tools/StaticAnalysis/BreakingChangeAnalyzer/BreakingChangeAnalyzer.cs
Labels: Waiting for CI :shipit:

#15523 Cplat capacity reservation feature
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestCapacityReservation.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/CapacityReservation/GetAzCapacityReservationCommand.cs
  src/Compute/Compute/Generated/CapacityReservation/GetAzCapacityReservationGroupCommand.cs
  src/Compute/Compute/Generated/CapacityReservation/NewAzCapacityReservationCommand.cs
  src/Compute/Compute/Generated/CapacityReservation/NewAzCapacityReservationGroupCommand.cs
  src/Compute/Compute/Generated/CapacityReservation/RemoveAzCapacityReservationCommand.cs
  src/Compute/Compute/Generated/CapacityReservation/RemoveAzCapacityReservationGroupCommand.cs
  src/Compute/Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Generated/Models/PSCapacityReservation.cs
  src/Compute/Compute/Generated/Models/PSCapacityReservationGroup.cs
  src/Compute/Compute/Generated/Models/PSCapacityReservationGroupList.cs
  src/Compute/Compute/Generated/Models/PSCapacityReservationList.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Manual/PSVirtualMachineScaleSetVMProfile.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Models/PSVirtualMachine.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/Get-AzCapacityReservation.md
  src/Compute/Compute/help/Get-AzCapacityReservationGroup.md
  src/Compute/Compute/help/New-AzCapacityReservation.md
  src/Compute/Compute/help/New-AzCapacityReservationGroup.md
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Remove-AzCapacityReservation.md
  src/Compute/Compute/help/Remove-AzCapacityReservationGroup.md
  src/Compute/Compute/help/Update-AzVM.md
  src/Compute/Compute/help/Update-AzVmss.md
Labels: needs-review

#15529 Remove Aks and DnsResolver from skip module
  tools/PrepareAutorestModule.ps1
Labels: Waiting for CI :shipit:

#15536 [MySQL] Quick Fix for MySQL flexible server provisioning failure and doc fix (issue submitted)
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/docs/Update-AzMySqlFlexibleServerConfiguration.md
  src/MySql/examples/Update-AzMySqlFlexibleServerConfiguration.md
Labels: Waiting for CI :shipit:

#15537 Add DnsResolver exceptions
  tools/StaticAnalysis/BreakingChangeAnalyzer/BreakingChangeAnalyzer.cs
  tools/StaticAnalysis/Exceptions/DnsResolver/SignatureIssues.csv
Labels: needs-review

#15443 Upload csv for generating powershell assembly reference docs
  tools/Docs/GenerateDotNetCsv.ps1
  tools/Docs/az-ps-latest.csv
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#15547 Add deprecated message for azure blockchain
  src/Blockchain/custom/New-AzBlockchainMember.ps1
  src/Blockchain/readme.md
Labels: Waiting for CI :shipit:

#15542 Rename DnsResolver exceptions folder
  tools/StaticAnalysis/Exceptions/Az.ADDomainServices/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/Az.DnsResolver/SignatureIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Migrate/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#15553 [DataFactory]Updated ADF .Net SDK version to 4.21.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Waiting for CI :shipit:

#15550 Show Arc error on 20H2 only if Arc intent is specified
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
Labels: Waiting for CI :shipit:

#15507 [PostgreSQL] Migrate PostgreSQL module to PostgreSQL flexible server GA API
  src/PostgreSql/custom/FlexibleServer.cs
  src/PostgreSql/custom/Get-AzPostgreSqlFlexibleServerConnectionString.ps1
  src/PostgreSql/custom/Get-AzPostgreSqlFlexibleServerLocationBasedCapability.ps1
  src/PostgreSql/custom/New-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/New-AzPostgreSqlFlexibleServerFirewallRule.ps1
  src/PostgreSql/custom/Restore-AzPostgreSqlFlexibleServer_PointInTimeRestore.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlFlexibleServerConfiguration.ps1
  src/PostgreSql/docs/New-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/examples/New-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/readme.md
  src/PostgreSql/test/AzPostgreSqlFlexibleServer.Recording.json
  src/PostgreSql/test/AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/test/AzPostgreSqlFlexibleServerConfiguration.Recording.json
  src/PostgreSql/test/AzPostgreSqlFlexibleServerConfiguration.Tests.ps1
  src/PostgreSql/test/AzPostgreSqlFlexibleServerCreateWithFirewallRule.Recording.json
  src/PostgreSql/test/AzPostgreSqlFlexibleServerCreateWithFirewallRule.Tests.ps1
  src/PostgreSql/test/AzPostgreSqlFlexibleServerCreateWithVnet.Recording.json
  src/PostgreSql/test/AzPostgreSqlFlexibleServerCreateWithVnet.Tests.ps1
  src/PostgreSql/test/AzPostgreSqlFlexibleServerFirewallRule.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlConfiguration.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlConfiguration.Tests.ps1
  src/PostgreSql/test/Get-AzPostgreSqlConnectionString.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFirewallRule.Tests.ps1
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerConnectionString.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlFlexibleServerLocationBasedCapability.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlReplica.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlServer.Tests.ps1
  src/PostgreSql/test/Get-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Get-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/New-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlReplica.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/New-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlFirewallRule.Tests.ps1
  src/PostgreSql/test/Remove-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlServer.Tests.ps1
  src/PostgreSql/test/Remove-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Remove-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/Restart-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Restart-AzPostgreSqlServer.Tests.ps1
  src/PostgreSql/test/Restore-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Recording.json
  src/PostgreSql/test/Test-AzPostgreSqlFlexibleServerConnect.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlConfiguration.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlConfiguration.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlFirewallRule.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlFirewallRule.Tests.ps1
  src/PostgreSql/test/Update-AzPostgreSqlServer.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlVirtualNetworkRule.Recording.json
  src/PostgreSql/test/Update-AzPostgreSqlVirtualNetworkRule.Tests.ps1
  src/PostgreSql/test/env.json
  src/PostgreSql/test/localEnv.json
  src/PostgreSql/test/utils.ps1
  tools/StaticAnalysis/Exceptions/Az.PostgreSql/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15539 [Storage] Support Parquet in Quick query
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobQueryResult.md
  src/Storage/Storage.Management/help/New-AzStorageBlobQueryConfig.md
  src/Storage/Storage/Blob/Cmdlet/NewAzStorageBlobQueryConfig .cs
  src/Storage/Storage/Common/BlobQueryTextConfiguration.cs
  src/Storage/Storage/Storage.csproj
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15549 [Redis] New Param added to choose redis version
  src/RedisCache/RedisCache.Test/RedisCache.Test.csproj
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestFirewallRule.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestGeoReplication.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestImportExportReboot.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCache.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCacheClustering.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePatchSchedules.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestRedisCachePipeline.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestSetNonExistingRedisCacheTest.json
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestZones.json
  src/RedisCache/RedisCache/ChangeLog.md
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Commands/SetAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheClient.cs
  src/RedisCache/RedisCache/RedisCache.csproj
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/Set-AzRedisCache.md
Labels: Waiting for CI :shipit:

#15546 Add PowerShell version into telemetry
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/AzModule.cs
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#15568 Revert "[Storage] Support Parquet in Quick query"
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Get-AzStorageBlobQueryResult.md
  src/Storage/Storage.Management/help/New-AzStorageBlobQueryConfig.md
  src/Storage/Storage/Blob/Cmdlet/NewAzStorageBlobQueryConfig .cs
  src/Storage/Storage/Common/BlobQueryTextConfiguration.cs
  src/Storage/Storage/Storage.csproj
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#15570 Customize testgallery as the source of dotnet reference docs
  tools/Docs/GenerateDotNetCsv.ps1
  tools/Docs/az-ps-latest.csv
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#15534 Grammatical fix
  src/Network/Network/help/Add-AzNetworkSecurityRuleConfig.md
Labels: Doc - Reference, customer-reported, needs-review

#15535 Grammar correction
  src/Network/Network/help/Set-AzNetworkSecurityRuleConfig.md
Labels: Doc - Reference, customer-reported, needs-review

#15533 Update docs to indicate [Get/Disable/Enable]-AzHDInsightMonitoring cmdlets are 'Classic'
  src/HDInsight/HDInsight/help/Az.HDInsight.md
  src/HDInsight/HDInsight/help/Disable-AzHDInsightMonitoring.md
  src/HDInsight/HDInsight/help/Enable-AzHDInsightMonitoring.md
  src/HDInsight/HDInsight/help/Get-AzHDInsightMonitoring.md
Labels: Doc - Reference, HDInsight, customer-reported, needs-review

#15573 [Az.Migrate] Tagging bug fix
  src/Migrate/Az.Migrate.psd1
  src/Migrate/Migrate.sln
  src/Migrate/custom/Set-AzMigrateServerReplication.ps1
  src/Migrate/generate-info.json
  tools/GeneratedModuleList.txt
Labels: Waiting for CI :shipit:

#15577 Daily build and smoke test improvements
  .azure-pipelines/daily-build.yml
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: needs-review

#15562 Add new cmdlets for Synapse managed private endpoint
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/DataPlaneCommands/ManagedPrivateEndpoints/GetAzureSynapseManagedPrivateEndpoint.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/ManagedPrivateEndpoints/NewAzureSynapseManagedPrivateEndpoint.cs
  src/Synapse/Synapse/Commands/DataPlaneCommands/ManagedPrivateEndpoints/RemoveAzureSynapseManagedPrivateEndpoint.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/PSManagedPrivateEndpointConnectionState.cs
  src/Synapse/Synapse/Models/PSManagedPrivateEndpointProperties.cs
  src/Synapse/Synapse/Models/PSManagedPrivateEndpointResource.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Models/SynapseManagedPrivateEndpointsClient.cs
  src/Synapse/Synapse/Models/SynapseManagedPrivateEndpointsCmdletBase.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/Synapse.csproj
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Get-AzSynapseManagedPrivateEndpoint.md
  src/Synapse/Synapse/help/New-AzSynapseManagedPrivateEndpoint.md
  src/Synapse/Synapse/help/Remove-AzSynapseManagedPrivateEndpoint.md
Labels: needs-review
