Repository Azure/azure-powershell, pull requests merged in 2021-01, with the labels that each got.

#13856 Preview Release of module 'Az.ADDomainServices'
  src/ADDomainService/.gitattributes
  src/ADDomainService/.gitignore
  src/ADDomainService/Az.ADDomainServices.psd1
  src/ADDomainService/custom/New-AzADDomainService.ps1
  src/ADDomainService/custom/New-AzADDomainServiceDomainSecuritySettingObject.ps1
  src/ADDomainService/custom/New-AzADDomainServiceLdapsSettingObject.ps1
  src/ADDomainService/custom/New-AzADDomainServiceNotificationSettingObject.ps1
  src/ADDomainService/custom/New-AzADDomainServiceReplicaSetObject.ps1
  src/ADDomainService/custom/New-AzADDomainServiceResourceForestSettingObject.ps1
  src/ADDomainService/custom/Update-AzADDomainService.ps1
  src/ADDomainService/custom/readme.md
  src/ADDomainService/docs/Az.ADDomainServices.md
  src/ADDomainService/docs/Get-AzADDomainService.md
  src/ADDomainService/docs/New-AzADDomainService.md
  src/ADDomainService/docs/New-AzADDomainServiceDomainSecuritySettingObject.md
  src/ADDomainService/docs/New-AzADDomainServiceLdapsSettingObject.md
  src/ADDomainService/docs/New-AzADDomainServiceNotificationSettingObject.md
  src/ADDomainService/docs/New-AzADDomainServiceReplicaSetObject.md
  src/ADDomainService/docs/New-AzADDomainServiceResourceForestSettingObject.md
  src/ADDomainService/docs/Remove-AzADDomainService.md
  src/ADDomainService/docs/Update-AzADDomainService.md
  src/ADDomainService/docs/readme.md
  src/ADDomainService/examples/Get-AzADDomainService.md
  src/ADDomainService/examples/New-AzADDomainService.md
  src/ADDomainService/examples/New-AzADDomainServiceDomainSecuritySettingObject.md
  src/ADDomainService/examples/New-AzADDomainServiceLdapsSettingObject.md
  src/ADDomainService/examples/New-AzADDomainServiceNotificationSettingObject.md
  src/ADDomainService/examples/New-AzADDomainServiceReplicaSetObject.md
  src/ADDomainService/examples/New-AzADDomainServiceResourceForestSettingObject.md
  src/ADDomainService/examples/Remove-AzADDomainService.md
  src/ADDomainService/examples/Update-AzADDomainService.md
  src/ADDomainService/how-to.md
  src/ADDomainService/license.txt
  src/ADDomainService/readme.md
  src/ADDomainService/resources/readme.md
  src/ADDomainService/test/Get-AzADDomainService.Recording.json
  src/ADDomainService/test/Get-AzADDomainService.Tests.ps1
  src/ADDomainService/test/New-AzADDomainService.Recording.json
  src/ADDomainService/test/New-AzADDomainService.Tests.ps1
  src/ADDomainService/test/New-AzADDomainServiceDomainSecuritySettingObject.Tests.ps1
  src/ADDomainService/test/New-AzADDomainServiceLdapsSettingObject.Tests.ps1
  src/ADDomainService/test/New-AzADDomainServiceNotificationSettingObject.Tests.ps1
  src/ADDomainService/test/New-AzADDomainServiceReplicaSetObject.Tests.ps1
  src/ADDomainService/test/New-AzADDomainServiceResourceForestSettingObject.Tests.ps1
  src/ADDomainService/test/Remove-AzADDomainService.Recording.json
  src/ADDomainService/test/Remove-AzADDomainService.Tests.ps1
  src/ADDomainService/test/Update-AzADDomainService.Recording.json
  src/ADDomainService/test/Update-AzADDomainService.Tests.ps1
  src/ADDomainService/test/deployment-templates/networkSecurityGroup/parameters.json
  src/ADDomainService/test/deployment-templates/networkSecurityGroup/template.json
  src/ADDomainService/test/deployment-templates/virtual-network/parameters.json
  src/ADDomainService/test/deployment-templates/virtual-network/template.json
  src/ADDomainService/test/env.json
  src/ADDomainService/test/loadEnv.ps1
  src/ADDomainService/test/readme.md
  src/ADDomainService/test/utils.ps1
  src/ADDomainService/utils/Unprotect-SecureString.ps1
Labels: needs-revision

#13867 Updated changelog and added missing feature
  ChangeLog.md
  src/Compute/Compute/ChangeLog.md
Labels: needs-review

#13871 Update New-AzStorageTableStoredAccessPolicy.md
  src/Storage/Storage.Management/help/New-AzStorageTableStoredAccessPolicy.md
Labels: Waiting for CI :shipit:, customer-reported

#13877 Update Set-AzSecurityWorkspaceSetting.md : fixing deviation between a command output and its description
  src/Security/Security/help/Set-AzSecurityWorkspaceSetting.md
Labels: Waiting for CI :shipit:, customer-reported

#13441 #10518-webapp: Support the new appservice Managed certificates
  src/Websites/Websites.Test/ScenarioTests/CertificatesTests.cs
  src/Websites/Websites.Test/ScenarioTests/CertificatesTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.CertificatesTests/TestNewAzWebAppCertificate.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.CertificatesTests/TestNewAzWebAppCertificateForSlot.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.CertificatesTests/TestNewAzWebAppCertificateWithSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.CertificatesTests/TestRemoveAzWebAppCertificate.json
  src/Websites/Websites/Az.Websites.psd1
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/Certificates/NewAzureWebAppCertificate.cs
  src/Websites/Websites/Cmdlets/Certificates/NewAzureWebAppSSLBinding.cs
  src/Websites/Websites/Cmdlets/Certificates/RemoveAzureWebAppCertificate.cs
  src/Websites/Websites/Cmdlets/Certificates/RemoveAzureWebAppSSLBinding.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
  src/Websites/Websites/help/New-AzWebAppCertificate.md
  src/Websites/Websites/help/Remove-AzWebAppCertificate.md
Labels: App Services, Waiting for CI :shipit:

#13875 [CosmosDB] GA of Az.CosmosDB module
  src/CosmosDB/CosmosDB.Test/ScenarioTests/AccountTests.ps1
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountRelatedCmdlets.json
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.AccountTests/TestAddRegionOperation.json
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewAzCosmosDBAccount.cs
Labels: needs-revision

#13866 Fix bug causing Docker Password to be removed from appsettings in Set-AzWebApp(Slot)
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/SetAzureWebAppSlot.cs
  src/Websites/Websites/Cmdlets/WebApps/SetAzureWebApp.cs
Labels: App Services, Waiting for CI :shipit:, customer-reported

#13862 P2s multi auth Vwan
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VpnServerConfiguration/NewAzureRmVpnServerConfigurationCommand.cs
  src/Network/Network/Cortex/VpnServerConfiguration/UpdateAzureRmVpnServerConfigurationCommand.cs
  src/Network/Network/Cortex/VpnServerConfiguration/VpnServerConfigurationBaseCmdlet.cs
  src/Network/Network/help/New-AzVpnServerConfiguration.md
  src/Network/Network/help/Update-AzVpnServerConfiguration.md
Labels: needs-review

#13873 [Storage] Fix ContinuationToken never null in list blob include version
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
Labels: needs-review

#13889 Fix mysql issues
  src/MySql/Az.MySql.psd1
  src/MySql/custom/Get-AzMySqlFlexibleServerConnectionString.ps1
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/custom/adjectives.txt
  src/MySql/custom/nouns.txt
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/Get-AzMySqlConnectionString.md
  src/MySql/docs/Get-AzMySqlFlexibleServerConnectionString.md
  src/MySql/docs/New-AzMySqlFlexibleServer.md
  src/MySql/docs/New-AzMySqlFlexibleServerReplica.md
  src/MySql/docs/New-AzMySqlReplica.md
  src/MySql/docs/Restore-AzMySqlFlexibleServer.md
  src/MySql/docs/Restore-AzMySqlServer.md
  src/MySql/readme.md
Labels: Generator, Waiting for CI :shipit:

#13595 [MONITOR] Data Collection Rules 2019-11-01-preview - New Cmdlets
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/Monitor/Monitor.Test/ScenarioTests/DataCollectionRulesTests.cs
  src/Monitor/Monitor.Test/ScenarioTests/DataCollectionRulesTests.ps1
  src/Monitor/Monitor.Test/SessionRecords/Microsoft.Azure.Commands.Insights.Test.ScenarioTests.DataCollectionRulesTests/AddGetListSetRemoveDataCollectionRulesAndAssociations.json
  src/Monitor/Monitor/Az.Monitor.psd1
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/DataCollectionRules/GetAzureRmDataCollectionRuleAssociationCommand.cs
  src/Monitor/Monitor/DataCollectionRules/GetAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/NewAzureRmDataCollectionRuleAssociationCommand.cs
  src/Monitor/Monitor/DataCollectionRules/NewAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/RemoveAzureRmDataCollectionRuleAssociationCommand.cs
  src/Monitor/Monitor/DataCollectionRules/RemoveAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/SetAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/UpdateAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/Monitor.csproj
  src/Monitor/Monitor/OutputClasses/PSDataCollectionRuleResource.cs
  src/Monitor/Monitor/Utilities.cs
  src/Monitor/Monitor/help/Get-AzDataCollectionRule.md
  src/Monitor/Monitor/help/Get-AzDataCollectionRuleAssociation.md
  src/Monitor/Monitor/help/New-AzDataCollectionRule.md
  src/Monitor/Monitor/help/New-AzDataCollectionRuleAssociation.md
  src/Monitor/Monitor/help/Remove-AzDataCollectionRule.md
  src/Monitor/Monitor/help/Remove-AzDataCollectionRuleAssociation.md
  src/Monitor/Monitor/help/Set-AzDataCollectionRule.md
  src/Monitor/Monitor/help/Update-AzDataCollectionRule.md
  src/Sql/Sql.Test/Sql.Test.csproj
Labels: needs-revision

#13891 Fix the description for Get-AzMySqlConnectionString
  src/MySql/Az.MySql.psd1
  src/MySql/custom/Get-AzMySqlConnectionString.ps1
  src/MySql/docs/Az.MySql.md
  src/MySql/docs/Get-AzMySqlConnectionString.md
Labels: Waiting for CI :shipit:

#13884 [Az.RecoveryServices.Backup] Adding Cross Region Restore feature
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/ItemAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/JobAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/OperationStatusAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/RecoveryPointsAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/RestoreDiskAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/RecoveryServices.Backup.ServiceClientAdapter.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJob.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Jobs/GetAzureRmRecoveryServicesBackupJobDetails.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/RecoveryPoint/GetAzureRmRecoveryServicesBackupRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Backup/RSBackupVaultCmdletBase.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Common/PSRecoveryServicesVaultClient.cs
  src/RecoveryServices/RecoveryServices/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
  src/RecoveryServices/RecoveryServices/Vault/GetAzureRmRecoveryServicesBackupProperty.cs
  src/RecoveryServices/RecoveryServices/Vault/SetAzureRmRecoveryServicesBackupProperties.cs
  src/RecoveryServices/RecoveryServices/help/Copy-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJob.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJobDetail.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProperty.md
Labels: needs-review

#13888 [Synapse] - refine restore sqlpool
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolBackupTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolBackupTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SynapseTestBase.cs
  src/Synapse/Synapse.Test/ScenarioTests/VulnerabilityAssessmentTests.cs
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestRestoreFromRestorePoint.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolBackupTests/TestSqlPoolRestorePoint.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPoolSecurity.json
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/RemoveAzureSynapseSqlPoolRestorePoint.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SqlPool Backup/RestoreAzureSynapseSqlPool.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/help/Remove-AzSynapseSqlPoolRestorePoint.md
  src/Synapse/Synapse/help/Restore-AzSynapseSqlPool.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#13907 Az.CosmosDB GA
  src/CosmosDB/CosmosDB/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: P0, Waiting for CI :shipit:

#13900 Rename some help files
  src/Aks/Aks/help/Disable-AzAksAddOn.md
  src/Aks/Aks/help/Enable-AzAksAddOn.md
  src/Compute/Compute/help/Invoke-AzVMPatchAssessment.md
  src/Network/Network/help/Disconnect-AzP2SVpnGatewayVpnConnection.md
  src/Network/Network/help/Get-AzExpressRouteCrossConnectionArpTable.md
  src/OperationalInsights/OperationalInsights/help/Get-AzOperationalInsightsLinkTarget.md
  src/OperationalInsights/OperationalInsights/help/Get-AzOperationalInsightsSavedSearchResult.md
  src/OperationalInsights/OperationalInsights/help/Get-AzOperationalInsightsSearchResult.md
  src/Security/Security/help/Disable-AzSecurityAdvancedThreatProtection.md
  src/Sql/Sql/help/Disable-AzSqlServerAdvancedThreatProtection.md
  src/Sql/Sql/help/Enable-AzSqlServerAdvancedThreatProtection.md
  src/Storage/Storage.Management/help/Set-AzDataLakeGen2ItemAclObject.md
Labels: needs-review

#13895 [CosmosDB] Bugfix: Added missing property in Sql Container Resource
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/Helpers/Constants.cs
  src/CosmosDB/CosmosDB/Models/Sql/PSSqlContainerGetPropertiesResource.cs
  src/CosmosDB/CosmosDB/SQL/NewAzCosmosDBSqlContainer.cs
  src/CosmosDB/CosmosDB/SQL/UpdateAzCosmosDBSqlContainer.cs
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBCassandraTableThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBGremlinDatabaseThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBGremlinGraphThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBMongoDBCollectionThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBMongoDBDatabaseThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBSqlContainerThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBSqlDatabaseThroughputMigration.md
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBTableThroughputMigration.md
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBAccount.md
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBSqlContainer.md
  src/CosmosDB/CosmosDB/help/Update-AzCosmosDBSqlContainer.md
Labels: Waiting for CI :shipit:

#13912 Drop securestirng decryption for DB releated modules since it has been supported by the generator
  src/MariaDb/custom/New-AzMariaDBServer.ps1
  src/MariaDb/custom/Update-AzMariaDBServer.ps1
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/custom/New-AzMySqlServer.ps1
  src/MySql/custom/Update-AzMySqlFlexibleServer.ps1
  src/MySql/custom/Update-AzMySqlServer.ps1
  src/PostgreSql/custom/New-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/New-AzPostgreSqlServer.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlFlexibleServer.ps1
  src/PostgreSql/custom/Update-AzPostgreSqlServer.ps1
Labels: Waiting for CI :shipit:

#13859 Generate code and tests for HealthBot
  src/HealthBot/.gitattributes
  src/HealthBot/.gitignore
  src/HealthBot/Az.Healthbot.psd1
  src/HealthBot/custom/readme.md
  src/HealthBot/docs/Az.Healthbot.md
  src/HealthBot/docs/Get-AzHealthBot.md
  src/HealthBot/docs/New-AzHealthBot.md
  src/HealthBot/docs/Remove-AzHealthBot.md
  src/HealthBot/docs/Update-AzHealthBot.md
  src/HealthBot/docs/readme.md
  src/HealthBot/examples/Get-AzHealthBot.md
  src/HealthBot/examples/New-AzHealthBot.md
  src/HealthBot/examples/Remove-AzHealthBot.md
  src/HealthBot/examples/Update-AzHealthBot.md
  src/HealthBot/how-to.md
  src/HealthBot/license.txt
  src/HealthBot/readme.md
  src/HealthBot/resources/readme.md
  src/HealthBot/test/Get-AzHealthBot.Recording.json
  src/HealthBot/test/Get-AzHealthBot.Tests.ps1
  src/HealthBot/test/New-AzHealthBot.Recording.json
  src/HealthBot/test/New-AzHealthBot.Tests.ps1
  src/HealthBot/test/Remove-AzHealthBot.Recording.json
  src/HealthBot/test/Remove-AzHealthBot.Tests.ps1
  src/HealthBot/test/Update-AzHealthBot.Recording.json
  src/HealthBot/test/Update-AzHealthBot.Tests.ps1
  src/HealthBot/test/env.json
  src/HealthBot/test/loadEnv.ps1
  src/HealthBot/test/readme.md
  src/HealthBot/test/utils.ps1
  src/HealthBot/utils/Unprotect-SecureString.ps1
Labels: needs-review

#13903 [SQL] [LogReplay] Make Start-AzSqlInstanceDatabaseLogReplay synchronous command
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedDatabase/Cmdlet/StartAzureSqlInstanceDatabaseLogReplay.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseAdapter.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseCommunicator.cs
  src/Sql/Sql/help/Start-AzSqlInstanceDatabaseLogReplay.md
Labels: Waiting for CI :shipit:

#13918 Polish changelog for upcoming release
  src/LogicApp/LogicApp/ChangeLog.md
  src/Websites/Websites/ChangeLog.md
Labels: Waiting for CI :shipit:

#13931 Remove invalid powershell core myget feed on genration branch
  Nuget.config
  tools/NetCoreCsProjSync/NuGet.Config
  tools/NetCorePsd1Sync/NuGet.Config
Labels: Waiting for CI :shipit:

#13736 Adding Routing preference for VpnGateway and P2SVpnGateway
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/P2SVpnGateway/NewAzureRmP2sVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/NewAzureRmVpnGatewayCommand.cs
  src/Network/Network/Models/Cortex/PSP2SVpnGateway.cs
  src/Network/Network/Models/Cortex/PSVpnGateway.cs
  src/Network/Network/help/New-AzP2sVpnGateway.md
  src/Network/Network/help/New-AzVpnGateway.md
Labels: Waiting for CI :shipit:

#13922 Update common lib and client telemetry
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/CommonModule/AzModule.cs
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
  src/Accounts/Accounts/Subscription/GetAzureRMSubscription.cs
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#13882 Add GenerateExternalContributors
  tools/GenerateExternalContributors.ps1
Labels: Waiting for CI :shipit:

#13940 Adding Routing preference for VpnGateway and P2SVpnGateway
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/P2SVpnGateway/NewAzureRmP2sVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/NewAzureRmVpnGatewayCommand.cs
  src/Network/Network/Models/Cortex/PSP2SVpnGateway.cs
  src/Network/Network/Models/Cortex/PSVpnGateway.cs
  src/Network/Network/help/New-AzP2sVpnGateway.md
  src/Network/Network/help/New-AzVpnGateway.md
Labels: Waiting for CI :shipit:

#13939 Missing updates to Az.ADDomainServices
  tools/CreateMappings_rules.json
  tools/GeneratedModuleList.txt
Labels: Waiting for CI :shipit:

#13917 Regenerate code for "BotService"
  src/BotService/custom/readme.md
  src/BotService/readme.md
Labels: Waiting for CI :shipit:

#13853 Support to Get IKE Security Associations on Virtual Network Gateway Connections
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests/TestVirtualNetworkGatewayConnectionGetIkeSa.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSVirtualNetworkGatewayConnectionIkeSa.cs
  src/Network/Network/VirtualNetworkGatewayConnection/GetAzVirtualNetworkGatewayConnectionIkeSaCommand.cs
  src/Network/Network/help/Get-AzVirtualNetworkGatewayConnectionIkeSa.md
Labels: Waiting for CI :shipit:

#13943 VPN NAT for Virtual WAN feature changes
  src/Network/Network.Test/ScenarioTests/CortexTests.cs
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexCRUD.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Cortex/CortexParameterSetNames.cs
  src/Network/Network/Cortex/VpnConnection/NewAzVpnSiteLinkConnectionCommand.cs
  src/Network/Network/Cortex/VpnGateway/NewAzureRmVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/UpdateAzureRmVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGatewayNatRule/GetAzureRmVpnGatewayNatRuleCommand.cs
  src/Network/Network/Cortex/VpnGatewayNatRule/NewAzureRmVpnGatewayNatRuleCommand.cs
  src/Network/Network/Cortex/VpnGatewayNatRule/RemoveAzureRmVpnGatewayNatRuleCommand.cs
  src/Network/Network/Cortex/VpnGatewayNatRule/UpdateAzureRmVpnGatewayNatRuleCommand.cs
  src/Network/Network/Cortex/VpnGatewayNatRule/VpnGatewayNatRuleBaseCmdlet.cs
  src/Network/Network/Models/Cortex/PSVpnGateway.cs
  src/Network/Network/Models/Cortex/PSVpnSiteLinkConnection.cs
  src/Network/Network/Models/PSVpnGatewayNatRule.cs
  src/Network/Network/Models/PSVpnNatRuleMapping.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/help/Get-AzVpnGatewayNatRule.md
  src/Network/Network/help/New-AzVpnGateway.md
  src/Network/Network/help/New-AzVpnGatewayNatRule.md
  src/Network/Network/help/New-AzVpnSiteLinkConnection.md
  src/Network/Network/help/Remove-AzVpnGatewayNatRule.md
  src/Network/Network/help/Update-AzVpnGateway.md
  src/Network/Network/help/Update-AzVpnGatewayNatRule.md
Labels: needs-review

#13947 Azure backup documentation update
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/EnableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupContainer.md
Labels: needs-revision

#13926 Adding support for maintenance configuration for SQL DB
  src/Sql/Sql.Test/ScenarioTests/Common.ps1
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestElasticPoolCreateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestElasticPoolGetWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestElasticPoolUpdateWithMaintenanceConfigurationId.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/MaintenanceConfigurationHelper.cs
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/NewAzureSqlElasticPool.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/SetAzureSqlElasticPool.cs
  src/Sql/Sql/Elastic Pools/Model/AzureSqlElasticPoolModel.cs
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabase.md
  src/Sql/Sql/help/New-AzSqlElasticPool.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
  src/Sql/Sql/help/Set-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:

#13951 Deprecate ContainerService API cmdlets
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/ContainerService/Config/AddAzureRmContainerServiceAgentPoolProfileCommand.cs
  src/Compute/Compute/Generated/ContainerService/Config/NewAzureRmContainerServiceConfigCommand.cs
  src/Compute/Compute/Generated/ContainerService/Config/RemoveAzureRmContainerServiceAgentPoolProfileCommand.cs
  src/Compute/Compute/Generated/ContainerService/ContainerServiceCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/ContainerService/ContainerServiceDeleteMethod.cs
  src/Compute/Compute/Generated/ContainerService/ContainerServiceGetMethod.cs
Labels: needs-revision

#13921 correction to example 1 in Set-AzEventHub.md
  src/EventHub/EventHub/help/Set-AzEventHub.md
Labels: Doc - Reference, customer-reported, needs-author-feedback, needs-revision

#13916 Regenerate code for "CostManagement"
  src/CostManagement/custom/New-AzCostManagementQueryComparisonExpressionObject.ps1
  src/CostManagement/custom/readme.md
  src/CostManagement/docs/Invoke-AzCostManagementQuery.md
  src/CostManagement/docs/New-AzCostManagementExport.md
  src/CostManagement/docs/New-AzCostManagementQueryComparisonExpressionObject.md
  src/CostManagement/docs/New-AzCostManagementQueryFilterObject.md
  src/CostManagement/examples/Invoke-AzCostManagementQuery.md
  src/CostManagement/examples/New-AzCostManagementQueryComparisonExpressionObject.md
  src/CostManagement/examples/New-AzCostManagementQueryFilterObject.md
  src/CostManagement/readme.md
  src/CostManagement/test/Invoke-AzCostManagementQuery.Tests.ps1
  src/CostManagement/test/New-AzCostManagementQueryComparisonExpressionObject.Tests.ps1
  src/CostManagement/test/New-AzCostManagementQueryFilterObject.Tests.ps1
  src/CostManagement/utils/Unprotect-SecureString.ps1
Labels: needs-review

#13952 Remove FilterExpression from Get-AzVMImage documentation
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMImageCmdletOutputFormat.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.format.ps1xml
  src/Compute/Compute/help/Get-AzVMImage.md
Labels: Waiting for CI :shipit:

#13956 Cplat enable automatic upgrade
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineExtensionTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineExtensionTests/TestVirtualMachineExtensionEnableAutomaticUpgrade.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/SetAzureVMExtensionBaseCmdlet.cs
  src/Compute/Compute/Extension/SetAzureVMExtensionCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssExtensionCommand.cs
  src/Compute/Compute/Manual/PSVirtualMachineScaleSetExtension.cs
  src/Compute/Compute/Models/PSVirtualMachineExtension.cs
  src/Compute/Compute/help/Add-AzVmssExtension.md
  src/Compute/Compute/help/Set-AzVMExtension.md
  src/Compute/Compute/help/Set-AzVmss.md
Labels: Waiting for CI :shipit:

#13953 Update code for Botservice
  src/BotService/Az.BotService.psd1
  src/BotService/Az.BotService.psm1
  src/BotService/Changelog.md
  src/BotService/Properties/AssemblyInfo.cs
  src/BotService/build-module.ps1
  src/BotService/check-dependencies.ps1
  src/BotService/custom/readme.md
  src/BotService/generate-info.json
  src/BotService/generated/api/BotService.cs
  src/BotService/generated/api/Models/Api20180712/Bot.cs
  src/BotService/generated/api/Models/Api20180712/BotChannel.cs
  src/BotService/generated/api/Models/Api20180712/ConnectionSetting.cs
  src/BotService/generated/api/Models/Api20180712/DirectLineChannel.cs
  src/BotService/generated/api/Models/Api20180712/EmailChannel.cs
  src/BotService/generated/api/Models/Api20180712/EnterpriseChannel.cs
  src/BotService/generated/api/Models/Api20180712/Error.cs
  src/BotService/generated/api/Models/Api20180712/FacebookChannel.cs
  src/BotService/generated/api/Models/Api20180712/KikChannel.cs
  src/BotService/generated/api/Models/Api20180712/MSTeamsChannel.cs
  src/BotService/generated/api/Models/Api20180712/OperationEntity.cs
  src/BotService/generated/api/Models/Api20180712/Resource.cs
  src/BotService/generated/api/Models/Api20180712/ServiceProvider.cs
  src/BotService/generated/api/Models/Api20180712/SkypeChannel.cs
  src/BotService/generated/api/Models/Api20180712/SlackChannel.cs
  src/BotService/generated/api/Models/Api20180712/SmsChannel.cs
  src/BotService/generated/api/Models/Api20180712/TelegramChannel.cs
  src/BotService/generated/api/Models/Api20180712/WebChatChannel.cs
  src/BotService/generated/api/Support/ChannelName.cs
  src/BotService/generated/api/Support/EnterpriseChannelNodeState.cs
  src/BotService/generated/api/Support/EnterpriseChannelState.cs
  src/BotService/generated/api/Support/Kind.cs
  src/BotService/generated/api/Support/SkuName.cs
  src/BotService/generated/api/Support/SkuTier.cs
  src/BotService/generated/cmdlets/NewAzBotService_CreateExpanded.cs
  src/BotService/generated/cmdlets/UpdateAzBotService_UpdateExpanded.cs
  src/BotService/generated/cmdlets/UpdateAzBotService_UpdateViaIdentityExpanded.cs
  src/BotService/generated/runtime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
  src/BotService/generated/runtime/UndeclaredResponseException.cs
  src/BotService/readme.md
Labels: needs-revision

#13883 Modified SmokeTest/RmCoreSmokeTests.ps1.
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: needs-review

#13968 Formatting IKE SA for List and Table views
  src/Network/Network/ChangeLog.md
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Network.generated.format.ps1xml
Labels: needs-review

#13972 Update Get-AzApplicationGatewayAuthenticationCertificate.md
  src/Network/Network/help/Get-AzApplicationGatewayAuthenticationCertificate.md
Labels: Waiting for CI :shipit:, customer-reported

#13910 Fixing static analysis issues, breaking changes are expected and AzureStack does not ship MSI
  NuGet.Config
  src/Storage/Storage.Management/Az.Storage.psd1
  tools/NetCoreCsProjSync/NuGet.Config
  tools/NetCorePsd1Sync/NuGet.Config
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Storage/MissingAssemblies.csv
Labels: needs-review

#13961 [Storage] Support rounting preferences
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestNewSetAStorageAccount_RoutingPreference.json
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSRoutingPreference.cs
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
Labels: needs-revision

#13962 [RecoveryServices.Backup] Added Zone Redundancy for Recovery Service Vaults
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMCrossRegionRestore.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices/Vault/SetAzureRmRecoveryServicesBackupProperties.cs
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProperty.md
Labels: needs-review

#13901 Corrected example command
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectableItem.md
Labels: Doc - Reference, Waiting for CI :shipit:, customer-reported

#13967 [AppService] Register App Service Resources for Private Link Powershells
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#14006 [Az.RecoveryServices.Backup] modifying policy validation limits as per backup service
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Utils.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#13760 Add test matrix for Az.Accounts
  documentation/testing-docs/test-matrix-for-az-accounts.md
Labels: Doc - Internal, needs-review

#13988 Documentation improvement to Az.StackHCI
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/help/Az.StackHCI.md
  src/StackHCI/help/Register-AzStackHCI.md
  src/StackHCI/test-module.ps1
Labels: needs-review

#14007 Support for Proximity placement group and Availability zone for Vmware to Azure and HyperV to Azure scenarios
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/B2AInput/B2A.VaultCredentials
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2A/AsrV2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2A/AsrV2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/V2A/V2AInput/V2AInput.VaultCredentials
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/TestCreateRPIWithAvZone.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/TestCreateRPIWithPPG.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/TestUpdateRPIWithAvZone.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/TestUpdateRPIWithPPG.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ATests/V2ACreateRPIWithAvZone.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ATests/V2ACreateRPIWithPPG.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ATests/V2AUpdateRPIWithAvZone.json
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrV2ATests/V2AUpdateRPIWithPPG.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSFabricDetails.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/RecoveryServices.SiteRecovery.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/SetAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesAsrReplicationProtectedItem.md
Labels: needs-revision

#14009 Fixed broken link to contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: customer-reported

#14008 add EnableNoPublicIPValue parameter to New-AzDatabricksworkspace
  src/Databricks/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/custom/readme.md
  src/Databricks/docs/New-AzDatabricksWorkspace.md
  src/Databricks/readme.md
Labels: needs-revision

#14002 [keyvault] support importing EC key by byok file
  src/KeyVault/KeyVault.Test/PesterTests/Key.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/AddAzureKeyVaultKey.cs
  src/KeyVault/KeyVault/Helpers/JwkHelper.cs
  src/KeyVault/KeyVault/Models/ByokWebKeyConverter.cs
  src/KeyVault/KeyVault/Models/IWebKeyConverter.cs
  src/KeyVault/KeyVault/Models/PfxWebKeyConverter.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/help/Add-AzKeyVaultKey.md
  src/KeyVault/KeyVault/help/Get-AzKeyVaultKey.md
Labels: needs-review

#14015 Log Analytics new parameters Group By ApplicationId and UserAgent
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/LogAnalyticTests.cs
  src/Compute/Compute.Test/ScenarioTests/LogAnalyticTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.LogAnalyticTests/TestExportLogAnalyticGroupByParameters.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/LogAnalytic/LogAnalyticExportRequestRateByIntervalMethod.cs
  src/Compute/Compute/Generated/LogAnalytic/LogAnalyticExportThrottledRequestsMethod.cs
  src/Compute/Compute/help/Export-AzLogAnalyticRequestRateByInterval.md
  src/Compute/Compute/help/Export-AzLogAnalyticThrottledRequest.md
Labels: needs-revision

#14051 Fix top value when top is not provided
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/PolicyInsights/PolicyInsights/Cmdlets/GetAzureRmPolicyState.cs
Labels: Waiting for CI :shipit:

#14044 Update WAF Sdk to support RequestBodyCheck and JSON exclussions
  src/FrontDoor/FrontDoor.Test/FrontDoor.Test.csproj
  src/FrontDoor/FrontDoor.Test/ScenarioTests/WebApplicationFireWallPolicyTests.ps1
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestManagedRuleSetDefinitions.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestPolicyCrud.json
  src/FrontDoor/FrontDoor.Test/SessionRecords/Microsoft.Azure.Commands.FrontDoor.Test.ScenarioTests.ScenarioTest.WebApplicationFireWallPolicyTests/TestPolicyCrudWithPiping.json
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewFrontDoorWafManagedRuleExclusionObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewFrontDoorWafManagedRuleObject.cs
  src/FrontDoor/FrontDoor/Cmdlets/NewFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/Cmdlets/UpdateFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/FrontDoor.csproj
  src/FrontDoor/FrontDoor/Helpers/ModelExtensions.cs
  src/FrontDoor/FrontDoor/Models/PSPolicy.cs
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafPolicy.md
  src/FrontDoor/FrontDoor/help/Update-AzFrontDoorWafPolicy.md
Labels: Waiting for CI :shipit:

#13928 Add ExpressRoutePort MACsec SCI state
  src/Network/Network.Test/ScenarioTests/CreateKeyVaultParameters.json
  src/Network/Network.Test/ScenarioTests/CreateKeyVaultTemplate.json
  src/Network/Network.Test/ScenarioTests/ExpressRoutePortsMacSecTest.cs
  src/Network/Network.Test/ScenarioTests/ExpressRoutePortsMacSecTest.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ExpressRoutePortsMacSecTest/TestExpressRoutePortMacSecConfigCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/Models/PSExpressRouteLinkMacSecConfig.cs
  src/Network/Network/help/Set-AzExpressRoutePort.md
Labels: needs-revision
