Repository Azure/azure-powershell, pull requests merged in 2022-10, with the labels that each got.

#19727 Fix typo in Example 1
  src/Network/Network/help/New-AzContainerNicConfigIpConfig.md
Labels: customer-reported

#19583 Improve cmdlet descriptions and parameter descriptions for VM/VMSS creation.
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Set-AzVmssOsProfile.md
  tools/StaticAnalysis/Exceptions/Az.Compute/ExampleIssues.csv
Labels: needs-revision

#19740 [do not squash] Fix the issue of security tools pipeline (#19732)
  .azure-pipelines/security-tools.yml
  .azure-pipelines/util/download-build-steps.yml
Labels: Do Not Squash :no_entry_sign:

#19737 {AzureStorage} fixes Azure/azure-powershell#19734
  src/Storage/Storage.Management/help/New-AzStorageContainerSASToken.md
Labels: Doc - Conceptual

#19747 [Az.Ssh] Bug fixes before release
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  src/Ssh/Ssh.Helpers/Ssh.Helpers.csproj
  src/Ssh/Ssh/Az.Ssh.psd1
  src/Ssh/Ssh/Common/SshBaseCmdlet.cs
  src/Ssh/Ssh/Properties/AssemblyInfo.cs
  src/lib/NetCorePreloadAssemblies/Microsoft.IdentityModel.Abstractions.dll
Labels: needs-review

#19741 [RecoveryServices.Backup] Added fix for enable protection and updated help for register container cmdlets
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/EnableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Register-AzRecoveryServicesBackupContainer.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: needs-review

#19742 Added Standby option to SecondaryType parameter to New-AzSqlDatabaseSecondary
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/help/New-AzSqlDatabaseSecondary.md
Labels: needs-review

#19180 Powershell change for VNG multipool
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestVirtualNetworkGatewayPolicyGroupCRUD.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Generated/Models/PSVpnClientConfiguration.cs
  src/Network/Network/Models/PSClientConnectionConfiguration.cs
  src/Network/Network/Models/PSVirtualNetworkGateway.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayPolicyGroup.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayPolicyGroupMember.cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayPolicyGroupCommand .cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayPolicyGroupMemberCommand.cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVpnClientConnectionConfigurationCommand.cs
  src/Network/Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
  src/Network/Network/help/New-AzVirtualNetworkGatewayPolicyGroup.md
  src/Network/Network/help/New-AzVirtualNetworkGatewayPolicyGroupmember.md
  src/Network/Network/help/New-AzVpnClientConnectionConfiguration.md
  src/Network/Network/help/Set-AzVirtualNetworkGateway.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#19763 bump version of Az.CosmosDB
  .azure-pipelines/security-tools.yml
  src/CosmosDB/CosmosDB/Az.CosmosDB.psd1
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/AzPreview/AzPreview.psd1
Labels: needs-review

#19802 Update New-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/help/New-AzApplicationInsightsContinuousExport.md
Labels: customer-reported

#19762 Retreive subscription by id from server if subscription id is provided
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts.Test/AzureRMProfileTestsForMultitenant.cs
  src/Accounts/Accounts.Test/Mocks/MockSubscriptionClientFactory.cs
  src/Accounts/Accounts.Test/Mocks/MockSubscriptionClientFactoryVersion2016.cs
  src/Accounts/Accounts.Test/Mocks/MockSubscriptionClientFactoryVersion2019.cs
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.SubscriptionCmdletTests/AllParameterSetsSucceed.json
  src/Accounts/Accounts.Test/SessionRecords/Microsoft.Azure.Commands.Profile.Test.SubscriptionCmdletTests/PipingWithRmContextWorks.json
  src/Accounts/Accounts.Test/SubscriptionClientSwitchTest.cs
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/Subscription/GetAzureRMSubscription.cs
Labels: needs-review

#19819 [Az.DataProtection] Added storage redundancy ZoneRedundant for backup vault creation
  src/DataProtection/README.md
  src/DataProtection/custom/Cmdlets/Platform/Vault/Get-AzDataProtectionBackupVault_list.ps1
  src/DataProtection/custom/Enums/Enums.cs
  src/DataProtection/docs/Az.DataProtection.md
  src/DataProtection/docs/Get-AzDataProtectionBackupVault.md
Labels: needs-review

#19818 [Storage] Support blob type conversion in sync blob copy
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Copy-AzStorageBlob.md
  src/Storage/Storage/Blob/Cmdlet/CopyAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/StorageDataMovementCmdletBase.cs
Labels: Waiting for CI :shipit:

#19858 Update New-AzGalleryApplicationVersion.md
  src/Compute/Compute/help/New-AzGalleryApplicationVersion.md
Labels: customer-reported

#19898 Remove Update-AzEventGridPartnerDestination from psd1
  src/EventGrid/EventGrid/Az.EventGrid.psd1
Labels: Waiting for CI :shipit:

#19825 Added Get-AzFirewallLearnedPrefix cmdlet and Route Server Id parameter to firewall
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDRouteServerId.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestGetAzureFirewallLearnedIpPrefixes.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/AzureFirewall/AutoLearnedPrefix/GetAzureFirewallLearnedIpPrefixCommand.cs
  src/Network/Network/AzureFirewall/AzureFirewallBaseCmdlet.cs
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallIpPrefix.cs
  src/Network/Network/help/Get-AzFirewallLearnedIpPrefix.md
Labels: Waiting for CI :shipit:

#19899 Remove $vmName from non A2A scenarios as its not applicable
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrReplicationProtectedItem.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: needs-review, Breaking Change Release

#19908 [Az,RecoveryServices.Backup] Added support for cross zonal restore for ZRS vaults for non-ZonePinned VM
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: needs-review

#19912 Fix typos
  src/CosmosDB/CosmosDB/help/Invoke-AzCosmosDBSqlContainerThroughputMigration.md
Labels: customer-reported

#19870 Add logic of collect the error and warning in build step
  build.proj
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/CIFilterTask.cs
  tools/ExecuteCIStep.ps1
Labels: needs-review

#19925 Make StorageContainerSasToken parameter optional
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedDatabase/Cmdlet/StartAzureSqlInstanceDatabaseLogReplay.cs
  src/Sql/Sql/help/Start-AzSqlInstanceDatabaseLogReplay.md
Labels: Waiting for CI :shipit:

#19862 add param to Set-AzVmssStorageProfile
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs
  src/Compute/Compute/help/Set-AzVM.md
  src/Compute/Compute/help/Set-AzVmssStorageProfile.md
Labels: needs-revision

#19931 [KeyVault] Update MDs
  src/KeyVault/KeyVault/Commands/ManagedHsm/UndoAzKeyVaultManagedHsmRemoval.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/help/Az.KeyVault.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultManagedHsmRemoval.md
Labels: Waiting for CI :shipit:

#19696 Add features to Network
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSExtendedLocation.cs
  src/Network/Network/Models/PSVirtualNetworkGateway.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
Labels: customer-reported

#19922 Added Az.Accounts version in telemetry of autorest-based module
  src/Accounts/Accounts/CommonModule/TelemetryProvider.cs
  tools/Common.Netcore.Dependencies.targets
Labels: Do Not Merge :no_entry_sign:

#19946 [Compute] Add missing changelog
  src/Compute/Compute/ChangeLog.md
Labels: Waiting for CI :shipit:
