Repository Azure/azure-powershell, pull requests merged in 2022-08, with the labels that each got.

#19095 Allowed DnsName in New-AzKeyVaultCertificatePolicy to accept an empty list
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Certificate/Policy/NewAzureKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/Models/PSKeyVaultCertificatePolicy.cs
Labels: Waiting for CI :shipit:

#19109 Strong name sign third party assemblies in daily build
  .azure-pipelines/daily-build.yml
Labels: Waiting for CI :shipit:

#18578 15 june ps update
  src/Automation/Automation/help/Get-AzAutomationDscNodeConfiguration.md
Labels: Waiting for CI :shipit:

#19106 Bug fix - Set-AzFirewallPolicy command removes existing resource tags
  src/Network/Network/AzureFirewallPolicy/SetAzureFirewallPolicyCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewallPolicy/PSAzureFirewallPolicy.cs
Labels: Waiting for CI :shipit:

#19076 update Update-AzVm error message
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: needs-revision

#19026 [API Management] Add parameter option "GraphQL" to ImportApi cmdlet
  src/ApiManagement/ApiManagement.ServiceManagement/ApiManagementClient.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Commands/ImportAzureApiManagementApi.cs
  src/ApiManagement/ApiManagement.ServiceManagement/Models/PsApiManagementApiFormat.cs
  src/ApiManagement/ApiManagement/ChangeLog.md
  src/ApiManagement/ApiManagement/help/Import-AzApiManagementApi.md
Labels: Waiting for CI :shipit:

#19118 Add Az.Dashboard Az.Orbital to module list
  documentation/azure-powershell-modules.md
Labels: needs-review

#19111 [CI Example Analyzer] Show line for ExampleIssues
  documentation/Debugging-StaticAnalysis-Errors.md
  tools/StaticAnalysis/ExampleAnalyzer/AnalyzeRules/CommandName.psm1
  tools/StaticAnalysis/ExampleAnalyzer/AnalyzeRules/ParameterNameAndValue.psm1
  tools/StaticAnalysis/ExampleAnalyzer/ExampleIssue.cs
  tools/StaticAnalysis/ExampleAnalyzer/Measure-MarkdownOrScript.ps1
  tools/StaticAnalysis/ExampleAnalyzer/utils.ps1
  tools/StaticAnalysis/Exceptions/Az.Accounts/ExampleIssues.csv
Labels: needs-review

#19123 [Batch] Fixes OutputFiles for JobSchedule ManagerTasks
  src/Batch/Batch/ChangeLog.md
  src/Batch/Batch/Utils/Utils.cs
Labels: Waiting for CI :shipit:

#19134 Az.SpringCloud v0.3.0 release
  src/Accounts/Accounts/Utilities/CommandMappings.json
  src/SpringCloud/Az.SpringCloud.psd1
  src/SpringCloud/Changelog.md
  src/SpringCloud/Properties/AssemblyInfo.cs
  tools/AzPreview/AzPreview.psd1
  tools/Docs/az-ps-latest.csv
  tools/Tools.Common/AllowList.csv
  tools/Tools.Common/SerializedCmdlets/Az.SpringCloud.json
Labels: needs-review

#18997 Upadte NewtonSoft.Json to 13.0.1
  src/DeviceProvisioningServices/DeviceProvisioningServices/DeviceProvisioningServices.csproj
  src/IotHub/IotHub/IotHub.csproj
  src/Resources/ResourceManager/Extensions/JsonExtensions.cs
  src/Sql/Sql.LegacySdk/Sql.LegacySdk.csproj
  src/Websites/Websites.Helper/Websites.Helper.csproj
  src/lib/NetFxPreloadAssemblies/Newtonsoft.Json.dll
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/packages.config
  tools/Common.Netcore.Dependencies.Test.targets
  tools/Common.Netcore.Dependencies.targets
  tools/NetCoreCsProjSync/NetCoreCsProjSync/NetCoreCsProjSync.csproj
  tools/NetCorePsd1Sync/NetCorePsd1Sync/NetCorePsd1Sync.csproj
Labels: needs-review

#19151 Add changelog for PR : 17608
  src/EventGrid/EventGrid/ChangeLog.md
Labels: Waiting for CI :shipit:

#19153 Fixed a typo in Get-AzWebAppAccessRestrictionConfig.md
  src/Websites/Websites/help/Get-AzWebAppAccessRestrictionConfig.md
Labels: Waiting for CI :shipit:

#19083 Update Remove-AzApplicationGatewaySslCertificate.md
  src/Network/Network/help/Remove-AzApplicationGatewaySslCertificate.md
Labels: Waiting for CI :shipit:

#19158 Bug10404 Fixed the typo while checking string for null or blank in Get-AzAutomationDscNode
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/AutomationPSClientDSC.cs
Labels: Automation, Waiting for CI :shipit:

#19152 Bump version of Az.ConnectedKubernetes for OOB relaese
  src/ConnectedKubernetes/Az.ConnectedKubernetes.psd1
  src/ConnectedKubernetes/ChangeLog.md
  src/ConnectedKubernetes/Properties/AssemblyInfo.cs
  tools/AzPreview/AzPreview.psd1
  tools/Docs/az-ps-latest.csv
  tools/Tools.Common/SerializedCmdlets/Az.ConnectedKubernetes.json
Labels: needs-review

#19163 Update Remove-AzApplicationGatewaySslCertificate.md
  src/Network/Network/help/Remove-AzApplicationGatewaySslCertificate.md
Labels: Waiting for CI :shipit:

#19168 Revert "Upadte NewtonSoft.Json to 13.0.1"
  src/DeviceProvisioningServices/DeviceProvisioningServices/DeviceProvisioningServices.csproj
  src/IotHub/IotHub/IotHub.csproj
  src/Resources/ResourceManager/Extensions/JsonExtensions.cs
  src/Sql/Sql.LegacySdk/Sql.LegacySdk.csproj
  src/Websites/Websites.Helper/Websites.Helper.csproj
  src/lib/NetFxPreloadAssemblies/Newtonsoft.Json.dll
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/packages.config
  tools/Common.Netcore.Dependencies.Test.targets
  tools/Common.Netcore.Dependencies.targets
  tools/NetCoreCsProjSync/NetCoreCsProjSync/NetCoreCsProjSync.csproj
  tools/NetCorePsd1Sync/NetCorePsd1Sync/NetCorePsd1Sync.csproj
Labels: Waiting for CI :shipit:

#18474 improved printed output for Get-AzComputeResourceSku
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.Automation.generated.format.ps1xml
  src/Compute/Compute/Generated/Models/PSResourceSku.cs
Labels: needs-review

#19202 Fix syntax error in New-AzApplicationGatewayProbeConfig.md
  src/Network/Network/help/New-AzApplicationGatewayProbeConfig.md
Labels: Waiting for CI :shipit:

#19174 Added parameter ContentType in Import-AzKeyVaultCertificate to support importing pem via certificate string
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Certificate/ImportAzureKeyVaultCertificate.cs
  src/KeyVault/KeyVault/Track2Models/Track2KeyVaultDataServiceClient.cs
Labels: needs-revision

#19178 Fixed required parameters missing for *-AzPrivateEndpointConnection.
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateEndpointConnection/ApproveAzurePrivateEndpointConnection.cs
  src/Network/Network/PrivateLinkService/PrivateEndpointConnection/DenyAzurePrivateEndpointConnection.cs
  src/Network/Network/PrivateLinkService/PrivateEndpointConnection/RemoveAzurePrivateEndpointConnection.cs
  src/Network/Network/PrivateLinkService/PrivateEndpointConnection/SetAzurePrivateEndpointConnection.cs
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
  src/Network/Network/help/Approve-AzPrivateEndpointConnection.md
  src/Network/Network/help/Deny-AzPrivateEndpointConnection.md
  src/Network/Network/help/Get-AzPrivateEndpointConnection.md
  src/Network/Network/help/Remove-AzPrivateEndpointConnection.md
  src/Network/Network/help/Set-AzPrivateEndpointConnection.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#19102 Added Delete Option for Set-AzVmssStorageProfile and Add-AzVmssDataD…
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssDataDiskCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs
  src/Compute/Compute/help/Add-AzVmssDataDisk.md
  src/Compute/Compute/help/Set-AzVmssStorageProfile.md
Labels: Waiting for CI :shipit:

#19201 Fixing MockPSConsole to correctly call Predictor
  tools/Az.Tools.Predictor/MockPSConsole/Program.cs
Labels: Waiting for CI :shipit:, Az.Tools.Predictor

#19155 Bug fix: "Get-AzAutomationJob fails for some jobIds"
  src/Automation/Automation/ChangeLog.md
  src/Automation/Automation/Common/PowershellJsonConverter.cs
Labels: Waiting for CI :shipit:

#19205 Change whitelist to allowlist.
  tools/Tools.Common/Utilities/ModuleFilter.cs
Labels: needs-review

#19179 Update Add-AzNetworkSecurityRuleConfig.md
  src/Network/Network/help/Add-AzNetworkSecurityRuleConfig.md
Labels: Waiting for CI :shipit:

#19214 Added parameter NodeResourceGroup for New-AzAksCluster
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/help/Get-AzAksNodePoolUpgradeProfile.md
  src/Aks/Aks/help/New-AzAksCluster.md
  src/Aks/Aks/help/Start-AzAksCluster.md
  src/Aks/Aks/help/Stop-AzAksCluster.md
Labels: needs-review

#19229 clean up Az.Network.psd1
  src/Network/Network/Az.Network.psd1
Labels: Waiting for CI :shipit:

#19231 [CI Example Analyzer] Modify some comments
  tools/StaticAnalysis/ExampleAnalyzer/Measure-MarkdownOrScript.ps1
  tools/StaticAnalysis/ExampleAnalyzer/utils.ps1
Labels: Waiting for CI :shipit:

#19085 Update the logic of generating the document for upcoming breaking change
  tools/BreakingChanges/GetUpcomingBreakingChange.ps1
Labels: needs-review

#19117 {AzureCXP} fixes Azure/azure-powershell#18913
  src/DesktopVirtualization/Az.DesktopVirtualization.psd1
  src/DesktopVirtualization/README.md
  src/DesktopVirtualization/custom/README.md
  src/DesktopVirtualization/docs/Disconnect-AzWvdUserSession.md
  src/DesktopVirtualization/docs/Expand-AzWvdMsixImage.md
  src/DesktopVirtualization/docs/Get-AzWvdApplication.md
  src/DesktopVirtualization/docs/Get-AzWvdApplicationGroup.md
  src/DesktopVirtualization/docs/Get-AzWvdDesktop.md
  src/DesktopVirtualization/docs/Get-AzWvdHostPool.md
  src/DesktopVirtualization/docs/Get-AzWvdHostPoolRegistrationToken.md
  src/DesktopVirtualization/docs/Get-AzWvdMsixPackage.md
  src/DesktopVirtualization/docs/Get-AzWvdScalingPlan.md
  src/DesktopVirtualization/docs/Get-AzWvdSessionHost.md
  src/DesktopVirtualization/docs/Get-AzWvdUserSession.md
  src/DesktopVirtualization/docs/Get-AzWvdWorkspace.md
  src/DesktopVirtualization/docs/New-AzWvdMsixPackage.md
  src/DesktopVirtualization/docs/New-AzWvdScalingPlan.md
  src/DesktopVirtualization/docs/README.md
  src/DesktopVirtualization/docs/Remove-AzWvdApplication.md
  src/DesktopVirtualization/docs/Remove-AzWvdApplicationGroup.md
  src/DesktopVirtualization/docs/Remove-AzWvdHostPool.md
  src/DesktopVirtualization/docs/Remove-AzWvdMsixPackage.md
  src/DesktopVirtualization/docs/Remove-AzWvdScalingPlan.md
  src/DesktopVirtualization/docs/Remove-AzWvdSessionHost.md
  src/DesktopVirtualization/docs/Remove-AzWvdUserSession.md
  src/DesktopVirtualization/docs/Remove-AzWvdWorkspace.md
  src/DesktopVirtualization/docs/Send-AzWvdUserSessionMessage.md
  src/DesktopVirtualization/docs/Update-AzWvdApplication.md
  src/DesktopVirtualization/docs/Update-AzWvdApplicationGroup.md
  src/DesktopVirtualization/docs/Update-AzWvdDesktop.md
  src/DesktopVirtualization/docs/Update-AzWvdHostPool.md
  src/DesktopVirtualization/docs/Update-AzWvdMsixPackage.md
  src/DesktopVirtualization/docs/Update-AzWvdScalingPlan.md
  src/DesktopVirtualization/docs/Update-AzWvdSessionHost.md
  src/DesktopVirtualization/docs/Update-AzWvdWorkspace.md
  src/DesktopVirtualization/how-to.md
  src/DesktopVirtualization/test/loadEnv.ps1
  src/DesktopVirtualization/utils/Unprotect-SecureString.ps1
Labels: needs-revision

#19222 clarify scope of new-azdeployment
  src/Resources/Resources/help/New-AzDeployment.md
Labels: Waiting for CI :shipit:

#19223 Get-AzPolicyState doc improvements: Explain parameter scoping, add management group level example
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/PolicyInsights/PolicyInsights/Common/ParameterHelpMessages.cs
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyState.md
Labels: Waiting for CI :shipit:

#19131 Improve performance of TestFx
  src/ApiManagement/ApiManagement.ServiceManagement.Test/ScenarioTests/ApiManagementHelper.cs
  src/Attestation/Attestation.Test/ScenarioTests/AttestationTestRunner.cs
  src/Batch/Batch.Test/ScenarioTests/BatchTestRunner.cs
  src/DataLakeAnalytics/DataLakeAnalytics.Test/ScenarioTests/DataLakeAnalyticsTestRunner.cs
  src/OperationalInsights/OperationalInsights.Test/ScenarioTests/OperationalInsightsTestRunner.cs
  src/Sql/Sql.Test/ScenarioTests/SqlTestRunner.cs
  tools/TestFx/ConnectionStringKeys.cs
  tools/TestFx/EnvironmentSetupHelper.cs
  tools/TestFx/Mocks/MockClientFactory.cs
  tools/TestFx/Mocks/MockContext.cs
  tools/TestFx/TestEnvironment.cs
  tools/TestFx/TestEnvironmentFactory.cs
  tools/TestFx/TestManager.cs
Labels: needs-review

#19221 Bug fix: "Get-AzAutomationJob fails for some jobIds" with further improvements
  src/Automation/Automation/Common/PowershellJsonConverter.cs
Labels: Waiting for CI :shipit:

#19226 Add feature of Import-AzAksCredential
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/ImportAzureRmAksCredential.cs
  src/Aks/Aks/help/Import-AzAksCredential.md
Labels: Waiting for CI :shipit:

#18839 Update Set-AzSynapseSqlPoolAuditSetting.md
  src/Synapse/Synapse/help/Set-AzSynapseSqlPoolAuditSetting.md
Labels: Waiting for CI :shipit:

#19144 [Synapse] Updated help doc for [Set-AzSynapseLinkConnection] and [Set-AzSynapseLinkConnectionLinkTable]
  src/Synapse/Synapse/help/Set-AzSynapseLinkConnection.md
  src/Synapse/Synapse/help/Set-AzSynapseLinkConnectionLinkTable.md
Labels: Waiting for CI :shipit:

#19243 Update Enable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupProtection.md
Labels: Waiting for CI :shipit:

#19245 Onboard AgFoodPlatform to PrivatelinkCommonCmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#19256 [Storage] Support HNS soft delete
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2DeletedItem.md
  src/Storage/Storage.Management/help/Restore-AzDataLakeGen2DeletedItem.md
  src/Storage/Storage/Blob/StorageCloudBlobCmdletBase.cs
  src/Storage/Storage/Common/AzureDataLakeGen2DeletedItem.cs
  src/Storage/Storage/Common/AzureDataLakeGen2Item.cs
  src/Storage/Storage/Common/Util.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2DeletedItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RestoreAzDataLakeGen2DeletedItem.cs
  src/Storage/Storage/Storage.generated.format.ps1xml
Labels: needs-review

#19250 Feature/cplat add ip address warning
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
Labels: needs-review

#19266 Changed output format in examples
  src/NetworkFunction/Az.NetworkFunction.psd1
  src/NetworkFunction/README.md
  src/NetworkFunction/docs/Get-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/docs/Get-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/docs/New-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/docs/New-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/docs/Remove-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/docs/Remove-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/docs/Update-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/docs/Update-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/docs/Update-AzNetworkFunctionTrafficCollectorTag.md
  src/NetworkFunction/examples/Get-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/examples/Get-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/examples/New-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/examples/New-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/examples/Remove-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/examples/Remove-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/examples/Update-AzNetworkFunctionCollectorPolicy.md
  src/NetworkFunction/examples/Update-AzNetworkFunctionTrafficCollector.md
  src/NetworkFunction/examples/Update-AzNetworkFunctionTrafficCollectorTag.md
  src/NetworkFunction/test/loadEnv.ps1
Labels: needs-review

#19268 Removing Survey
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSurveyHelper.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ISurveyHelper.cs
Labels: Waiting for CI :shipit:, Az.Tools.Predictor

#19271 Onboard EnergyServices to PrivatelinkCommonCmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:, customer-reported

#19239 [Storage] Support LocalUser & SFTP
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.cs
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestAzureStorageLocalUserSftp.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSLocalUser.cs
  src/Storage/Storage.Management/Models/PSStorageAccount.cs
  src/Storage/Storage.Management/Storage.Management.format.ps1xml
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageLocalUser.cs
  src/Storage/Storage.Management/StorageAccount/GetAzureStorageLocalUserKey.cs
  src/Storage/Storage.Management/StorageAccount/NewAzStorageLocalUserPermissionScope.cs
  src/Storage/Storage.Management/StorageAccount/NewAzStorageLocalUserSshAuthorizedKey.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageLocalUserSshPassword.cs
  src/Storage/Storage.Management/StorageAccount/RemoveAzureStorageLocalUser.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageLocalUser.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/Get-AzStorageLocalUser.md
  src/Storage/Storage.Management/help/Get-AzStorageLocalUserKey.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageLocalUserPermissionScope.md
  src/Storage/Storage.Management/help/New-AzStorageLocalUserSshPassword.md
  src/Storage/Storage.Management/help/New-AzStorageLocalUserSshPublicKey.md
  src/Storage/Storage.Management/help/Remove-AzStorageLocalUser.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageLocalUser.md
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: needs-review

#19280 [Aks] Add some properties for New-AzAksCluster and Set-AzAksCluster
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Commands/SetAzureRmAks.cs
  src/Aks/Aks/Models/Mapper.cs
  src/Aks/Aks/Models/PSKubernetesCluster.cs
  src/Aks/Aks/Models/PSManagedClusterAutoScalerProfile.cs
  src/Aks/Aks/Models/PSManagedClusterAutoUpgradeProfile.cs
  src/Aks/Aks/Models/PSManagedClusterHTTPProxyConfig.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentity.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentityException.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentityProfile.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentityProfileUserAssignedIdentity.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentityProvisioningError.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentityProvisioningErrorBody.cs
  src/Aks/Aks/Models/PSManagedClusterPodIdentityProvisioningInfo.cs
  src/Aks/Aks/help/New-AzAksCluster.md
  src/Aks/Aks/help/Set-AzAksCluster.md
Labels: needs-review

#19135 [Grafana] Update grafana swagger 2022 08 01
  src/Dashboard/Az.Dashboard.psd1
  src/Dashboard/README.md
  src/Dashboard/custom/New-AzGrafana.ps1
  src/Dashboard/custom/New-AzGrafanaMonitorWorkspaceIntegrationObject.ps1
  src/Dashboard/docs/Az.Dashboard.md
  src/Dashboard/docs/New-AzGrafana.md
  src/Dashboard/docs/New-AzGrafanaMonitorWorkspaceIntegrationObject.md
  src/Dashboard/docs/Update-AzGrafana.md
  src/Dashboard/examples/New-AzGrafanaMonitorWorkspaceIntegrationObject.md
  src/Dashboard/test/Get-AzGrafana.Tests.ps1
  src/Dashboard/test/New-AzGrafana.Tests.ps1
  src/Dashboard/test/Remove-AzGrafana.Tests.ps1
  src/Dashboard/test/Update-AzGrafana.Tests.ps1
  tools/StaticAnalysis/Exceptions/Az.Dashboard/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#19323 [Accounts]Fixed an issue of the cmdlet Example
  src/Accounts/Accounts/help/Get-AzSubscription.md
Labels: Waiting for CI :shipit:

#19319 [marketplace ordering] upcoming breaking change message
  src/MarketplaceOrdering/MarketplaceOrdering/ChangeLog.md
  src/MarketplaceOrdering/MarketplaceOrdering/Cmdlets/Agreements/GetAzureRmMarketplaceTerms.cs
Labels: Waiting for CI :shipit:

#19318 [AppConfiguration] Correct Az.AppConfiguration.psd1 and delete BreakingChangeIssues.csv
  src/AppConfiguration/AppConfiguration/Az.AppConfiguration.psd1
  tools/StaticAnalysis/Exceptions/Az.AppConfiguration/BreakingChangeIssues.csv
Labels: needs-revision

#19286 [Synapse] Added spark pool dynamicExecutorAllocation related parameter
  src/Synapse/Synapse.Test/ScenarioTests/Common.ps1
  src/Synapse/Synapse.Test/ScenarioTests/DataClassificationTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/FirewallTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/IntegrationRuntimeTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SparkPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/SqlPoolTests.ps1
  src/Synapse/Synapse.Test/ScenarioTests/WorkspaceTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SparkPoolTests/TestSynapseSparkPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests/TestSynapseSqlPool.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests/TestSynapseWorkspace.json
  src/Synapse/Synapse.Test/Synapse.Test.csproj
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/NewAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/UpdateAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Common/Utils.cs
  src/Synapse/Synapse/Models/ManagementModels/SparkPool/PSDynamicExecutorAllocation.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Synapse.csproj
  src/Synapse/Synapse/help/New-AzSynapseSparkPool.md
  src/Synapse/Synapse/help/Update-AzSynapseSparkPool.md
Labels: Waiting for CI :shipit:

#19267 Remove Get-AzVmRuncommand from generation to write it traditionally
  src/Compute/Compute.Autorest/Az.Compute.psd1
  src/Compute/Compute.Autorest/README.md
  src/Compute/Compute.Autorest/docs/Az.Compute.md
  src/Compute/Compute.Autorest/docs/Get-AzVMRunCommand.md
  src/Compute/Compute.Autorest/docs/New-AzGalleryApplicationVersion.md
  src/Compute/Compute.Autorest/examples/Get-AzVMRunCommand.md
  src/Compute/Compute.Autorest/test/Get-AzVMRunCommand.Recording.json
  src/Compute/Compute.Autorest/test/Get-AzVMRunCommand.Tests.ps1
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: needs-review

#19272 add Get-AzVmRunCommand on SDK built cmdlet
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Manual/PSVirtualMachineRunCommand.cs
  src/Compute/Compute/Models/PSVirtualMachineRunCommandList.cs
  src/Compute/Compute/VirtualMachine/RunCommand/GetAzVmRunCommand.cs
  src/Compute/Compute/help/Get-AzVMRunCommand.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#19333 Make PowerShell 7.2 the default when creating a PowerShell function app
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
  src/Functions/custom/FunctionsStack/WindowsFunctionsStacks.json
  src/Functions/test/New-AzFunctionApp.Tests.ps1
Labels: needs-review

#19339 [Monitor] breaking changes warning for upcoming major release
  src/Monitor/Monitor/ActivityLogAlert/DisableAzureRmActivityLogAlertCommand.cs
  src/Monitor/Monitor/ActivityLogAlert/EnableAzureRmActivityLogAlertCommand.cs
  src/Monitor/Monitor/ActivityLogAlert/GetAzureRmActivityLogAlertCommand.cs
  src/Monitor/Monitor/ActivityLogAlert/NewAzureRmActionGroupCommand.cs
  src/Monitor/Monitor/ActivityLogAlert/NewAzureRmActivityLogAlertConditionCommand.cs
  src/Monitor/Monitor/ActivityLogAlert/RemoveAzureRmActivityLogAlertCommand.cs
  src/Monitor/Monitor/ActivityLogAlert/SetAzureRmActivityLogAlertCommand.cs
  src/Monitor/Monitor/Autoscale/AddAzureRmAutoscaleSettingCommand.cs
  src/Monitor/Monitor/Autoscale/GetAzureRmAutoscaleSettingCommand.cs
  src/Monitor/Monitor/Autoscale/NewAzureRmAutoscaleNotificationCommand.cs
  src/Monitor/Monitor/Autoscale/NewAzureRmAutoscaleProfileCommand.cs
  src/Monitor/Monitor/Autoscale/NewAzureRmAutoscaleRuleCommand.cs
  src/Monitor/Monitor/Autoscale/NewAzureRmAutoscaleWebhookCommand.cs
  src/Monitor/Monitor/Autoscale/RemoveAzureRmAutoscaleSettingCommand.cs
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/Diagnostics/GetAzureRMSubscriptionDiagnosticSettingCategoryCommand.cs
  src/Monitor/Monitor/Diagnostics/GetAzureRmDiagnosticSettingCategoryCommand.cs
  src/Monitor/Monitor/Diagnostics/GetAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/NewAzureRmDiagnosticDetailSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/NewAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/RemoveAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/Diagnostics/SetAzureRmDiagnosticSettingCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/GetScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleAlertingActionCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleAznsActionGroupCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleLogMetricTriggerCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleScheduleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleSourceCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/NewScheduledQueryRuleTriggerConditionCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/RemoveScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/SetScheduledQueryRuleCommand.cs
  src/Monitor/Monitor/ScheduledQueryRules/UpdateScheduledQueryRuleCommand.cs
Labels: Waiting for CI :shipit:

#19331 New-AzPPG cmdlet add the Zone and IntentVMList parameters
  src/Compute/Compute.Test/ScenarioTests/PPGTests.cs
  src/Compute/Compute.Test/ScenarioTests/PPGTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.PPGTests/TestPPGVMIntentListAndZones.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Models/PSProximityPlacementGroup.cs
  src/Compute/Compute/Generated/ProximityPlacementGroup/ProximityPlacementGroupCreateOrUpdateMethod.cs
  src/Compute/Compute/help/New-AzProximityPlacementGroup.md
Labels: needs-review

#19340 [Storage] add warning for coming breaking change
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/File/Cmdlet/GetAzureStorageFileContent.cs
  src/Storage/Storage/File/Cmdlet/GetAzureStorageShare.cs
  src/Storage/Storage/File/Cmdlet/NewAzureStorageDirectory.cs
  src/Storage/Storage/File/Cmdlet/NewAzureStorageShare.cs
  src/Storage/Storage/File/Cmdlet/RemoveAzureStorageShare.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageFileContent.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageShareQuota.cs
  src/Storage/Storage/File/Cmdlet/StartAzureStorageFileCopy.cs
Labels: Waiting for CI :shipit:

#19344 Update `upcoming-breaking-changes.md` in release process
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#19335 Return all valid results when filter subscriptions by name.
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/Subscription/GetAzureRMSubscription.cs
Labels: needs-revision

#19281 [Az.RecoveryServices.Backup] Added support for Archive smart tiering for AzureVM and MSSQL workloads
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RetentionPolicyConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SubPolicyConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Validations/PolicyValidations.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureDbModels/AzureDbPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Enums.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/FeatureSupportAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/RecoveryServices.Backup.ServiceClientAdapter.csproj
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/ServiceClientAdapter.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMMUA.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSHourlyPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMEnhancedPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadPolicy.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesVault.md
Labels: needs-review

#19356 Refine changelog for Sep release
  src/Accounts/Accounts/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/EventGrid/EventGrid/ChangeLog.md
  src/Monitor/Monitor/ChangeLog.md
  src/Network/Network/ChangeLog.md
Labels: needs-review

#19366 Fix the issue that some breaking change message cannot be generated.
  tools/BreakingChanges/GetUpcomingBreakingChange.ps1
Labels: Waiting for CI :shipit:
