Repository Azure/azure-powershell, pull requests merged in 2022-04, with the labels that each got.

#17687 Update RunVersionController.ps1
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#16935 Az.StackHCI Attestation firewall and network updates
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
  tools/StaticAnalysis/Exceptions/Az.StackHCI/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#16552 Perform null check before accessing it
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/RouteTable/Route/AddAzureRmRouteConfigCommand.cs
Labels: Network, needs-revision, Service Attention, customer-reported

#16308 Fix DateTime issue restoring deleted webapp
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/BackupRestore/RestoreAzureDeletedWebApp.cs
Labels: App Services, needs-review, Service Attention, customer-reported

#17601 Fix Az.KeyVault Syntax Errors
  src/KeyVault/KeyVault/help/Export-AzKeyVaultSecurityDomain.md
  src/KeyVault/KeyVault/help/Import-AzKeyVaultSecurityDomain.md
  src/KeyVault/KeyVault/help/Invoke-AzKeyVaultKeyOperation.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultCertificateIssuer.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultManagedHsm.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultSecret.md
Labels: Doc - Reference, needs-review

#17697 Fix Az.NetAppFiles Syntax Errors
  src/NetAppFiles/NetAppFiles/help/Get-AzNetAppFilesActiveDirectory.md
  src/NetAppFiles/NetAppFiles/help/Get-AzNetAppFilesReplicationStatus.md
  src/NetAppFiles/NetAppFiles/help/Initialize-AzNetAppFilesReplication.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesAccount.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesActiveDirectory.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesBackup.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesBackupPolicy.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesPool.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesSnapshot.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesVolume.md
  src/NetAppFiles/NetAppFiles/help/Remove-AzNetAppFilesActiveDirectory.md
  src/NetAppFiles/NetAppFiles/help/Remove-AzNetAppFilesReplication.md
  src/NetAppFiles/NetAppFiles/help/Restore-AzNetAppFilesVolume.md
  src/NetAppFiles/NetAppFiles/help/Resume-AzNetAppFilesReplication.md
  src/NetAppFiles/NetAppFiles/help/Set-AzNetAppFilesAccount.md
  src/NetAppFiles/NetAppFiles/help/Set-AzNetAppFilesBackupPolicy.md
  src/NetAppFiles/NetAppFiles/help/Set-AzNetAppFilesPool.md
  src/NetAppFiles/NetAppFiles/help/Suspend-AzNetAppFilesReplication.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesAccount.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesActiveDirectory.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesPool.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesVolume.md
Labels: Doc - Reference, needs-review

#17698 Fix Az.MonitoringSolutions Syntax Errors in generation
  src/MonitoringSolutions/docs/Get-AzMonitorLogAnalyticsSolution.md
  src/MonitoringSolutions/examples/Get-AzMonitorLogAnalyticsSolution.md
Labels: Doc - Reference, needs-review

#17695 Fix Az.MonitoringSolutions Syntax Errors
  src/MonitoringSolutions/help/Get-AzMonitorLogAnalyticsSolution.md
Labels: Doc - Reference, needs-review

#17600 Fix Az.IotHub Syntax Errors
  src/IotHub/IotHub/help/Get-AzIotHubDeviceConnectionString.md
  src/IotHub/IotHub/help/Get-AzIotHubModuleConnectionString.md
  src/IotHub/IotHub/help/Invoke-AzIotHubConfigurationMetricsQuery.md
  src/IotHub/IotHub/help/Invoke-AzIotHubDeploymentMetricsQuery.md
Labels: Doc - Reference, needs-review

#17597 Fix Az.HDInsight Syntax Errors
  src/HDInsight/HDInsight/help/Add-AzHDInsightClusterIdentity.md
  src/HDInsight/HDInsight/help/Add-AzHDInsightComponentVersion.md
  src/HDInsight/HDInsight/help/Add-AzHDInsightSecurityProfile.md
  src/HDInsight/HDInsight/help/Add-AzHDInsightStorage.md
  src/HDInsight/HDInsight/help/Disable-AzHDInsightAzureMonitor.md
  src/HDInsight/HDInsight/help/Enable-AzHDInsightAzureMonitor.md
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
  src/HDInsight/HDInsight/help/New-AzHDInsightIPConfiguration.md
  src/HDInsight/HDInsight/help/New-AzHDInsightPrivateLinkConfiguration.md
  src/HDInsight/HDInsight/help/New-AzHDInsightStreamingMapReduceJobDefinition.md
  src/HDInsight/HDInsight/help/Set-AzHDInsightClusterAutoscaleConfiguration.md
  src/HDInsight/HDInsight/help/Set-AzHDInsightDefaultStorage.md
Labels: Doc - Reference, needs-review

#17653 Fix Az.Kusto Syntax Errors in generation
  src/Kusto/docs/New-AzKustoDataConnection.md
  src/Kusto/docs/Test-AzKustoClusterPrincipalAssignmentNameAvailability.md
  src/Kusto/docs/Test-AzKustoDataConnectionNameAvailability.md
  src/Kusto/docs/Test-AzKustoDatabasePrincipalAssignmentNameAvailability.md
  src/Kusto/docs/Update-AzKustoDataConnection.md
  src/Kusto/examples/New-AzKustoDataConnection.md
  src/Kusto/examples/Test-AzKustoClusterPrincipalAssignmentNameAvailability.md
  src/Kusto/examples/Test-AzKustoDataConnectionNameAvailability.md
  src/Kusto/examples/Test-AzKustoDatabasePrincipalAssignmentNameAvailability.md
  src/Kusto/examples/Update-AzKustoDataConnection.md
Labels: Doc - Reference, needs-review

#17640 Fix Az.Kusto Syntax Errors
  src/Kusto/help/New-AzKustoDataConnection.md
  src/Kusto/help/Test-AzKustoClusterPrincipalAssignmentNameAvailability.md
  src/Kusto/help/Test-AzKustoDataConnectionNameAvailability.md
  src/Kusto/help/Test-AzKustoDatabasePrincipalAssignmentNameAvailability.md
  src/Kusto/help/Update-AzKustoDataConnection.md
Labels: Doc - Reference, needs-review

#17666 Fix Az.Media Syntax Errors
  src/Media/Media/help/New-AzMediaServiceStorageConfig.md
  src/Media/Media/help/Set-AzMediaService.md
Labels: Doc - Reference, needs-review

#17657 Fix Az.MarketplaceOrdering Syntax Errors
  src/MarketplaceOrdering/MarketplaceOrdering/help/Set-AzMarketplaceTerms.md
Labels: Doc - Reference, needs-review

#17655 Fix Az.ManagedServices Syntax Errors in generation
  src/ManagedServices/docs/New-AzManagedServicesDefinition.md
  src/ManagedServices/docs/Remove-AzManagedServicesAssignment.md
  src/ManagedServices/examples/New-AzManagedServicesDefinition.md
  src/ManagedServices/examples/Remove-AzManagedServicesAssignment.md
Labels: Doc - Reference, needs-review

#17652 Fix Az.ManagedServices Syntax Errors
  src/ManagedServices/help/New-AzManagedServicesDefinition.md
  src/ManagedServices/help/Remove-AzManagedServicesAssignment.md
Labels: Doc - Reference, needs-review

#17651 Fix Az.Maintenance Syntax Errors
  src/Maintenance/Maintenance/help/New-AzMaintenanceConfiguration.md
Labels: Doc - Reference, needs-review

#17654 Fix Az.Logz Syntax Errors in generation
  src/Logz/docs/Invoke-AzLogzHostSubAccount.md
  src/Logz/examples/Invoke-AzLogzHostSubAccount.md
Labels: Doc - Reference, needs-review

#17668 Fix Az.MixedReality Syntax Errors
  src/MixedReality/MixedReality/help/New-AzRemoteRenderingAccount.md
  src/MixedReality/MixedReality/help/New-AzSpatialAnchorsAccount.md
Labels: Doc - Reference, needs-review

#17645 Fix Az.Logz Syntax Errors
  src/Logz/help/Invoke-AzLogzHostSubAccount.md
Labels: Doc - Reference, needs-review

#17643 Fix Az.LogicApp Syntax Errors
  src/LogicApp/LogicApp/help/New-AzLogicApp.md
  src/LogicApp/LogicApp/help/Set-AzIntegrationAccountReceivedIcn.md
  src/LogicApp/LogicApp/help/Test-AzLogicApp.md
Labels: Doc - Reference, needs-review

#17641 Fix Az.Marketplace Syntax Errors
  src/Marketplace/Marketplace/help/Set-AzMarketplacePrivateStoreOffer.md
Labels: Doc - Reference, needs-review

#17638 Fix Az.Mariadb Syntax Errors
  src/MariaDb/help/Restore-AzMariaDbServer.md
  src/MariaDb/help/Update-AzMariaDbFirewallRule.md
Labels: Doc - Reference, needs-review

#17639 Fix Az.Mariadb Syntax Errors in generation
  src/MariaDb/docs/Restore-AzMariaDbServer.md
  src/MariaDb/docs/Update-AzMariaDbFirewallRule.md
  src/MariaDb/examples/Restore-AzMariaDbServer.md
  src/MariaDb/examples/Update-AzMariaDbFirewallRule.md
Labels: Doc - Reference, needs-review

#17611 [SQL] Add examples of Create Server and MI with TDE CMK
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlServer.md
Labels: Waiting for CI :shipit:

#17439 SIG direct sharing
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.cs
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestGalleryDirectSharing.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/Compute/Compute/Generated/Gallery/GalleryCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/Gallery/GalleryGetMethod.cs
  src/Compute/Compute/Generated/GalleryImage/GalleryImageGetMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionDeleteMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionGetMethod.cs
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Generated/Models/PSGallery.cs
  src/Compute/Compute/Generated/Models/PSSharedGallery.cs
  src/Compute/Compute/Generated/Models/PSSharedGalleryImage.cs
  src/Compute/Compute/Generated/Models/PSSharedGalleryImageList.cs
  src/Compute/Compute/Generated/Models/PSSharedGalleryImageVersion.cs
  src/Compute/Compute/Generated/Models/PSSharedGalleryImageVersionList.cs
  src/Compute/Compute/Generated/Models/PSSharedGalleryList.cs
  src/Compute/Compute/help/Get-AzGallery.md
  src/Compute/Compute/help/Get-AzGalleryImageDefinition.md
  src/Compute/Compute/help/Get-AzGalleryImageVersion.md
  src/Compute/Compute/help/New-AzGallery.md
  src/Compute/Compute/help/Update-AzGallery.md
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/Security/Security.Test/Security.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: needs-review

#17708 Add authorization csproj to sln files
  src/CosmosDB/CosmosDB.sln
  src/DeploymentManager/DeploymentManager.sln
  src/DevSpaces/DevSpaces.sln
  src/MachineLearning/MachineLearning.sln
  src/Peering/Peering.sln
Labels: needs-review

#17648 Fix Az.MachineLearning Syntax Errors
  src/MachineLearning/MachineLearning/help/Move-AzMlCommitmentAssociation.md
  src/MachineLearning/MachineLearning/help/Update-AzMlCommitmentPlan.md
Labels: Doc - Reference, Waiting for CI :shipit:

#17727 Use msbuild to build Az.Tools.Predictor.sln
  tools/Az.Tools.Predictor/Az.Tools.Predictor.SourceGenerator/Az.Tools.Predictor.SourceGenerator.csproj
  tools/Az.Tools.Predictor/build.proj
Labels: Az.Tools.Predictor

#17693 adding databricks to private link config
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#17722 [EventHubs] Set-AzEventHubNamespace and New-AzEventHubNamespace: Deprecated old MSI properties
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/Namespace/NewAzureEventHubNamespace.cs
  src/EventHub/EventHub/Cmdlets/Namespace/SetAzureEventHubNamespace.cs
Labels: Waiting for CI :shipit:

#13974 [WIP] Internal authentication doc
  documentation/internal/authentication.md
Labels: needs-revision

#17365 [Storage] support FederatedIdentityClientId
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
Labels: Waiting for CI :shipit:

#17729 Fix a bug can't display the customipprefix in publicipprefix.
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSPublicIpPrefix.cs
  src/Network/Network/Network.format.ps1xml
Labels: Waiting for CI :shipit:

#17544 Optimize pull request validation pipelines
  .azure-pipelines/powershell-core.yml
  .azure-pipelines/util/analyze-steps.yml
  .azure-pipelines/util/build-steps.yml
  .azure-pipelines/util/download-build-steps.yml
  .azure-pipelines/util/test-steps.yml
  .azure-pipelines/windows-powershell.yml
Labels: needs-review

#17730 Add support for Synapse AD only Authentication
  src/Synapse/Synapse.Test/ScenarioTests/ADOnlyAuthenticationTests.cs
  src/Synapse/Synapse.Test/ScenarioTests/ADOnlyAuthenticationTests.ps1
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.ADOnlyAuthenticationTests/TestDisableSynapseADOnlyAuthentication.json
  src/Synapse/Synapse.Test/SessionRecords/Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.ADOnlyAuthenticationTests/TestEnableSynapseADOnlyAuthentication.json
  src/Synapse/Synapse/Az.Synapse.psd1
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/AzureActiveDirectoryOnlyAuthentication/DisableAzureSynapseActiveDirectoryOnlyAuthentication.cs
  src/Synapse/Synapse/Commands/ManagementCommands/AzureActiveDirectoryOnlyAuthentication/EnableAzureSynapseActiveDirectoryOnlyAuthentication.cs
  src/Synapse/Synapse/Commands/ManagementCommands/AzureActiveDirectoryOnlyAuthentication/GetAzureSynapseActiveDirectoryOnlyAuthentication.cs
  src/Synapse/Synapse/Models/ManagementModels/AzureADOnlyAuthentication/PSAzureADOnlyAuthentication.cs
  src/Synapse/Synapse/Models/ManagementModels/SynapseAnalyticsManagementClient.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/Properties/Resources.Designer.cs
  src/Synapse/Synapse/Properties/Resources.resx
  src/Synapse/Synapse/help/Az.Synapse.md
  src/Synapse/Synapse/help/Disable-AzSynapseActiveDirectoryOnlyAuthentication.md
  src/Synapse/Synapse/help/Enable-AzSynapseActiveDirectoryOnlyAuthentication.md
  src/Synapse/Synapse/help/Get-AzSynapseActiveDirectoryOnlyAuthentication.md
Labels: needs-review

#17741 Docs: Update the New-AzApiManagementApiRevision Example 1 command description to match the ApiRevision arg in the code sample
  src/ApiManagement/ApiManagement/help/New-AzApiManagementApiRevision.md
Labels: Waiting for CI :shipit:, customer-reported

#17732 Markup rendering issue?
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
Labels: Waiting for CI :shipit:, customer-reported

#17787 Update Update-AzVpnGateway.md
  src/Network/Network/help/Update-AzVpnGateway.md
Labels: Waiting for CI :shipit:

#17744 Add hyperscale elastic pool read scale
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestHyperscaleElasticPoolCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestHyperscaleElasticPoolCreateWithReplica.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestHyperscaleElasticPoolGet.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestHyperscaleElasticPoolUpdateReplicaCount.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests/TestMoveDatabaseOutHyperscaleElasticPool.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Elastic Pools/Cmdlet/NewAzureSqlElasticPool.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/SetAzureSqlElasticPool.cs
  src/Sql/Sql/Elastic Pools/Model/AzureSqlElasticPoolModel.cs
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/Sql/Sql/help/New-AzSqlElasticPool.md
  src/Sql/Sql/help/Set-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:

#17768 Update build and sign pipeline of Az.Tools.Predictor
  .azure-pipelines/sign-tool-predictor.yml
  tools/Az.Tools.Predictor/Az.Tools.Predictor.SourceGenerator/Az.Tools.Predictor.SourceGenerator.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/build.proj
Labels: Az.Tools.Predictor

#17765 Register BotService in Network cmdlets
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#17792 Upgraded Microsoft.Rest.ClientRuntime to 2.3.24
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.targets
  tools/RepoTasks/RepoTasks.CmdletsForTest/packages.config
  tools/RepoTasks/RepoTasks.RemoteWorker/packages.config
Labels: Waiting for CI :shipit:

#17705 [Resources] fix redundant quotes in list pagination
  src/Resources/MSGraph.Autorest/custom/Module.cs
Labels: needs-revision

#17791 [Az.RecoveryServices.Backup] Added support for MBPD hourly Enhanced policy for workloadType AzureVM
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SchedulePolicyConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMProtection.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupSchedulePolicyObject.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServices.Backup.format.ps1xml
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRetentionPolicyObject.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupSchedulePolicyObject.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
Labels: Waiting for CI :shipit:

#17800 Add hub routing preference in virtual hub, deprecated PreferredRoutingGateway
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/CortexParameterSetNames.cs
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/UpdateAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/VirtualHubBaseCmdlet.cs
  src/Network/Network/Cortex/VpnConnection/UpdateAzureRmVpnConnectionCommand.cs
  src/Network/Network/Models/Cortex/PSVirtualHub.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/help/New-AzVirtualHub.md
  src/Network/Network/help/Update-AzVirtualHub.md
Labels: Waiting for CI :shipit:

#17776 [Aks] Fixed the issue that identity cannot be piped into Set-AzAksCluster
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Models/Mapper.cs
  src/Aks/Aks/Models/PSManagedClusterIdentity.cs
  src/Aks/Aks/Models/PSManagedClusterIdentityUserAssignedIdentitiesValue.cs
Labels: needs-review

#17609 SIG RBAC Cross-tenant sharing
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Custom/VirtualMachineExtensions.cs
  src/Compute/Compute/Custom/VirtualMachineScaleSetExtensions.cs
  src/Compute/Compute/Custom/VirtualMachineScaleSetsOperationsExtensions.cs
  src/Compute/Compute/Custom/VirtualMachinesOperationsExtensions.cs
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/Generated/Disk/DiskCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/ComputeStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/Set-AzVmssStorageProfile.md
Labels: needs-review

#17811 [DataFactory]Updated ADF .Net SDK version to 6.0.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Waiting for CI :shipit:

#17761 [Aks] Updated the decsription of `Force` in `Invoke-AzAksRunCommand`
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/RunAzureRmAksCommand.cs
  src/Aks/Aks/help/Invoke-AzAksRunCommand.md
Labels: Doc - Reference

#17826 Fix the UniqueName property in the examples
  src/Compute/Compute/help/Get-AzGallery.md
Labels: Waiting for CI :shipit:, customer-reported

#17805 Update Set-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Set-AzStorageFileContent.md
Labels: Waiting for CI :shipit:, customer-reported

#17802 Supported empty directory volume and secret volume for creating container group
  src/ContainerInstance/README.md
  src/ContainerInstance/custom/New-AzContainerGroup.ps1
  src/ContainerInstance/custom/New-AzContainerGroupVolumeObject.ps1
  src/ContainerInstance/custom/SpecialHandlerToRemoveDefaultValue.cs
  src/ContainerInstance/docs/Az.ContainerInstance.md
  src/ContainerInstance/docs/New-AzContainerGroup.md
  src/ContainerInstance/docs/New-AzContainerGroupVolumeObject.md
  src/ContainerInstance/docs/New-AzContainerInstanceObject.md
  src/ContainerInstance/examples/New-AzContainerGroupVolumeObject.md
  src/ContainerInstance/test/New-AzContainerInstanceVolumeObject.Tests.ps1
  tools/StaticAnalysis/Exceptions/Az.ContainerInstance/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#17799 Enabled public network access setting
  src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
  src/KeyVault/KeyVault.Test/ScenarioTests/ManagedHsmManagementTests.cs
  src/KeyVault/KeyVault.Test/ScenarioTests/ManagedHsmManagementTests.ps1
  src/KeyVault/KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestPublicNetworkAccessWhenCreateNewVault.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.KeyVaultManagementTests/TestUpdateKeyVaultWithPublicNetworkAccess.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.ManagedHsmManagementTests/TestCreateManagedHsmWithPublicNetworkAccess.json
  src/KeyVault/KeyVault.Test/SessionRecords/Microsoft.Azure.Commands.KeyVault.Test.ScenarioTests.ManagedHsmManagementTests/TestUpdateManagedHsmWithPublicNetworkAccess.json
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/NewAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/UpdateAzureManagedHsm.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/PSKeyVault.cs
  src/KeyVault/KeyVault/Models/PSManagedHsm.cs
  src/KeyVault/KeyVault/Models/VaultCreationOrUpdateParameters.cs
  src/KeyVault/KeyVault/Models/VaultManagementClient.cs
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/New-AzKeyVaultManagedHsm.md
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
  src/KeyVault/KeyVault/help/Update-AzKeyVaultManagedHsm.md
Labels: needs-review

#17830 [Dedicated hsm] update version to 2021-11-03
  src/DedicatedHsm/.gitignore
  src/DedicatedHsm/Az.DedicatedHsm.psd1
  src/DedicatedHsm/README.md
  src/DedicatedHsm/custom/README.md
  src/DedicatedHsm/docs/Az.DedicatedHsm.md
  src/DedicatedHsm/docs/Get-AzDedicatedHsm.md
  src/DedicatedHsm/docs/Get-AzDedicatedHsmOutboundNetworkDependencyEndpoint.md
  src/DedicatedHsm/docs/New-AzDedicatedHsm.md
  src/DedicatedHsm/docs/README.md
  src/DedicatedHsm/docs/Update-AzDedicatedHsm.md
  src/DedicatedHsm/examples/Get-AzDedicatedHsmOutboundNetworkDependencyEndpoint.md
  src/DedicatedHsm/how-to.md
  src/DedicatedHsm/test/Get-AzDedicatedHsmOutboundNetworkDependencyEndpoint.Recording.json
  src/DedicatedHsm/test/Get-AzDedicatedHsmOutboundNetworkDependencyEndpoint.Tests.ps1
  src/DedicatedHsm/test/New-AzDedicatedHsm.Recording.json
  src/DedicatedHsm/test/loadEnv.ps1
Labels: needs-review

#17832 [KeyVault] Skip check for subscription login status for secret management
  src/KeyVault/KeyVault/Az.KeyVault.Extension/Az.KeyVault.Extension.psm1
  src/KeyVault/KeyVault/ChangeLog.md
Labels: Waiting for CI :shipit:

#17778 [KeyVault] Supported getting random number from managed HSM by Get-AzKeyVaultRandomNumber
  src/KeyVault/KeyVault/Az.KeyVault.psd1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Key/GetAzKeyVaultRandomNumber.cs
  src/KeyVault/KeyVault/Commands/Key/KeyVaultOnlyKeyCmdletBase.cs
  src/KeyVault/KeyVault/Models/IKeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Track2Models/Track2HsmClient.cs
  src/KeyVault/KeyVault/Track2Models/Track2KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/help/Get-AzKeyVaultRandomNumber.md
Labels: Waiting for CI :shipit:

#17841 Update helpers with explanations & examples
  src/Security/Security/help/Az.Security.md
  src/Security/Security/help/Confirm-AzSecurityAutomation.md
  src/Security/Security/help/Get-AzSecurityAutomation.md
  src/Security/Security/help/New-AzSecurityAutomation.md
  src/Security/Security/help/New-AzSecurityAutomationActionObject.md
  src/Security/Security/help/New-AzSecurityAutomationRuleObject.md
  src/Security/Security/help/New-AzSecurityAutomationRuleSetObject.md
  src/Security/Security/help/New-AzSecurityAutomationScopeObject.md
  src/Security/Security/help/New-AzSecurityAutomationSourceObject.md
  src/Security/Security/help/Remove-AzSecurityAutomation.md
Labels: Waiting for CI :shipit:

#17816 Fix Az.SpringCloud Syntax Errors in generation
  src/SpringCloud/docs/Restart-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/Start-AzSpringCloudAppDeployment.md
  src/SpringCloud/docs/Stop-AzSpringCloudAppDeployment.md
  src/SpringCloud/examples/Restart-AzSpringCloudAppDeployment.md
  src/SpringCloud/examples/Start-AzSpringCloudAppDeployment.md
  src/SpringCloud/examples/Stop-AzSpringCloudAppDeployment.md
Labels: Doc - Reference, needs-review

#17815 Fix Az.SingaIR Syntax Errors in generation
  src/SignalR/SignalR.Autorest/docs/New-AzWebPubSub.md
  src/SignalR/SignalR.Autorest/docs/Update-AzWebPubSub.md
  src/SignalR/SignalR.Autorest/examples/New-AzWebPubSub.md
  src/SignalR/SignalR.Autorest/examples/Update-AzWebPubSub.md
Labels: Doc - Reference, needs-review

#17804 Fix Az.SpringCloud Syntax Errors
  src/SpringCloud/help/Restart-AzSpringCloudAppDeployment.md
  src/SpringCloud/help/Start-AzSpringCloudAppDeployment.md
  src/SpringCloud/help/Stop-AzSpringCloudAppDeployment.md
Labels: Doc - Reference, needs-review

#17801 Fix Az.SingaIR Syntax Errors
  src/SignalR/SignalR/help/New-AzWebPubSub.md
  src/SignalR/SignalR/help/Test-AzSignalRName.md
  src/SignalR/SignalR/help/Update-AzWebPubSub.md
Labels: Doc - Reference, needs-review

#17777 Fix Az.Search Syntax Errors
  src/Search/Search/help/New-AzSearchQueryKey.md
  src/Search/Search/help/New-AzSearchService.md
Labels: Doc - Reference, needs-review

#17739 Fix Az.PolicyInsights Syntax Errors
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyRemediation.md
  src/PolicyInsights/PolicyInsights/help/Start-AzPolicyRemediation.md
Labels: Doc - Reference, needs-review

#17755 Fix Az.Relay Syntax Errors
  src/Relay/Relay/help/Get-AzRelayAuthorizationRule.md
  src/Relay/Relay/help/New-AzRelayHybridConnection.md
  src/Relay/Relay/help/New-AzRelayKey.md
  src/Relay/Relay/help/New-AzWcfRelay.md
  src/Relay/Relay/help/Set-AzRelayAuthorizationRule.md
  src/Relay/Relay/help/Set-AzRelayHybridConnection.md
  src/Relay/Relay/help/Set-AzWcfRelay.md
Labels: Doc - Reference, needs-review

#17737 Fix Az.Purview Syntax Errors
  src/Purview/Purview/help/Update-AzPurviewAccount.md
Labels: Doc - Reference, needs-review

#17752 Fix Az.RedisCache Syntax Errors
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/Remove-AzRedisCacheDiagnostic.md
Labels: Doc - Reference, needs-review

#17817 OOB release Az.Cdn v1.8.3
  src/Cdn/Cdn/Az.Cdn.psd1
  src/Cdn/Cdn/ChangeLog.md
  src/Cdn/Cdn/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/Tools.Common/SerializedCmdlets/Az.Cdn.json
Labels: needs-review

#17783 [Storage] Use official parameters instead of aliases in examples
  src/Storage/Storage.Management/help/Get-AzStorageAccount.md
  src/Storage/Storage.Management/help/Get-AzStorageAccountKey.md
  src/Storage/Storage.Management/help/Get-AzStorageAccountNetworkRuleSet.md
  src/Storage/Storage.Management/help/Invoke-AzStorageAccountFailover.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Remove-AzStorageAccount.md
  src/Storage/Storage.Management/help/Remove-AzStorageAccountNetworkRule.md
  src/Storage/Storage.Management/help/Set-AzCurrentStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Update-AzStorageAccountNetworkRuleSet.md
Labels: Doc - Reference, Waiting for CI :shipit:

#14907 [Tools] Generate upcomming breaking change document.
  tools/BreakingChanges/GenerateMigrationExcel.ps1
  tools/BreakingChanges/GenerateMigrationGuide.ps1
  tools/BreakingChanges/GetUpcomingBreakingChange.ps1
Labels: needs-revision

#17861 Az.StackHCI Attestation Cluter Network Update
  src/StackHCI/Az.StackHCI.psm1
Labels: needs-review

#17596 Fix Az.EdgeOrder Unknown Parameter in generation
  src/EdgeOrder/docs/New-AzEdgeOrderItem.md
  src/EdgeOrder/examples/New-AzEdgeOrderItem.md
Labels: Doc - Reference, needs-review

#17595 Fix Az.EdgeOrder Unknown Parameter
  src/EdgeOrder/help/New-AzEdgeOrderItem.md
Labels: Doc - Reference, needs-review

#17747 Fix Az.Purview Syntax Errors in generation
  src/Purview/Purview.Autorest/docs/Update-AzPurviewAccount.md
  src/Purview/Purview.Autorest/examples/Update-AzPurviewAccount.md
Labels: Doc - Reference, needs-review

#17753 Fix Az.RecoveryServices Syntax Errors
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupAutoProtection.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesAsrEvent.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesAsrProtectableItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Initialize-AzRecoveryServicesBackupProtectableItem.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrFabric.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrPolicy.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrProtectionContainer.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrRecoveryPlan.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrvCenter.md
  src/RecoveryServices/RecoveryServices/help/Remove-AzRecoveryServicesAsrvCenter.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesAsrReplicationProtectedItem.md
  src/RecoveryServices/RecoveryServices/help/Start-AzRecoveryServicesAsrUnplannedFailoverJob.md
  src/RecoveryServices/RecoveryServices/help/Unregister-AzRecoveryServicesBackupContainer.md
  src/RecoveryServices/RecoveryServices/help/Unregister-AzRecoveryServicesBackupManagementServer.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesAsrNetworkMapping.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesAsrProtectionDirection.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesVault.md
Labels: Doc - Reference, needs-review

#17844 Set-AzAlertProcessingRule support 24-hour clock
  src/AlertsManagement/AlertsManagement/ActionRuleCommands/SetAzureAlertProcessingRule.cs
  src/AlertsManagement/AlertsManagement/ChangeLog.md
Labels: Waiting for CI :shipit:

#17822 Fix the examples of Az.Storage Syntax Errors
  src/Storage/Storage.Management/help/Add-AzRmStorageContainerLegalHold.md
  src/Storage/Storage.Management/help/Close-AzStorageFileHandle.md
  src/Storage/Storage.Management/help/Enable-AzStorageBlobRestorePolicy.md
  src/Storage/Storage.Management/help/Get-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Get-AzStorageFile.md
  src/Storage/Storage.Management/help/Get-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Lock-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageBlobInventoryPolicyRule.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainer.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageContainerLegalHold.md
  src/Storage/Storage.Management/help/Remove-AzRmStorageShare.md
  src/Storage/Storage.Management/help/Restore-AzStorageContainer.md
  src/Storage/Storage.Management/help/Set-AzDataLakeGen2AclRecursive.md
  src/Storage/Storage.Management/help/Set-AzRmStorageContainerImmutabilityPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobInventoryPolicy.md
  src/Storage/Storage.Management/help/Set-AzStorageFileContent.md
  src/Storage/Storage.Management/help/Start-AzStorageBlobIncrementalCopy.md
  src/Storage/Storage.Management/help/Update-AzDataLakeGen2Item.md
  src/Storage/Storage.Management/help/Update-AzRmStorageContainer.md
Labels: Doc - Reference, Waiting for CI :shipit:

#17736 Fix Az.NotificationHubs Syntax Errors
  src/NotificationHubs/NotificationHubs/help/New-AzNotificationHubsNamespace.md
  src/NotificationHubs/NotificationHubs/help/Remove-AzNotificationHubsNamespaceAuthorizationRule.md
Labels: Doc - Reference, needs-review

#17707 Fix Az.Migrate Syntax Errors
  src/Migrate/help/New-AzMigrateReplicationPolicy.md
  src/Migrate/help/New-AzMigrateReplicationProtectionContainerMapping.md
  src/Migrate/help/New-AzMigrateServerReplication.md
  src/Migrate/help/Start-AzMigrateTestMigrationCleanup.md
Labels: Doc - Reference, needs-review

#17617 Fix Az.Functions Syntax Errors in generation
  src/Functions/docs/New-AzFunctionApp.md
  src/Functions/examples/New-AzFunctionApp.md
Labels: Doc - Reference, needs-review

#17613 Fix Az.EventHub Syntax Errors
  src/EventHub/EventHub/help/Add-AzEventHubIPRule.md
  src/EventHub/EventHub/help/Add-AzEventHubVirtualNetworkRule.md
  src/EventHub/EventHub/help/Get-AzEventHub.md
  src/EventHub/EventHub/help/Remove-AzEventHubIPRule.md
  src/EventHub/EventHub/help/Remove-AzEventHubNetworkRuleSet.md
  src/EventHub/EventHub/help/Remove-AzEventHubVirtualNetworkRule.md
  src/EventHub/EventHub/help/Set-AzEventHubNetworkRuleSet.md
Labels: Doc - Reference, needs-review

#17616 Fix Az.Functions Syntax Errors
  src/Functions/help/New-AzFunctionApp.md
Labels: Doc - Reference, needs-review

#17863 Fix Az.Synapse Syntax Errors
  src/Synapse/Synapse/help/Clear-AzSynapseSqlPoolVulnerabilityAssessmentRuleBaseline.md
  src/Synapse/Synapse/help/Convert-AzSynapseSqlPoolVulnerabilityAssessmentScan.md
  src/Synapse/Synapse/help/Get-AzSynapsePipelineRun.md
  src/Synapse/Synapse/help/Invoke-AzSynapseDataFlowDebugSessionCommand.md
  src/Synapse/Synapse/help/New-AzSynapseKustoPoolPrincipalAssignment.md
  src/Synapse/Synapse/help/Remove-AzSynapseKustoPoolDataConnection.md
  src/Synapse/Synapse/help/Remove-AzSynapseRoleAssignment.md
  src/Synapse/Synapse/help/Restore-AzSynapseSqlPool.md
  src/Synapse/Synapse/help/Set-AzSynapseSqlPoolSensitivityClassification.md
  src/Synapse/Synapse/help/Set-AzSynapseSqlPoolVulnerabilityAssessmentRuleBaseline.md
  src/Synapse/Synapse/help/Start-AzSynapseSqlPoolVulnerabilityAssessmentScan.md
  src/Synapse/Synapse/help/Stop-AzSynapseSparkStatement.md
  src/Synapse/Synapse/help/Submit-AzSynapseSparkJob.md
  src/Synapse/Synapse/help/Update-AzSynapseFirewallRule.md
  src/Synapse/Synapse/help/Update-AzSynapseIntegrationRuntime.md
Labels: Doc - Reference, needs-review

#17868 Fix Az.TrafficManager Syntax Errors
  src/TrafficManager/TrafficManager/help/Remove-AzTrafficManagerCustomHeaderFromProfile.md
  src/TrafficManager/TrafficManager/help/Set-AzTrafficManagerProfile.md
Labels: Doc - Reference, needs-review

#17862 Fix Az.Support Syntax Errors
  src/Support/Support/help/New-AzSupportTicket.md
  src/Support/Support/help/Update-AzSupportTicket.md
Labels: Doc - Reference, needs-review

#17869 Fix Az.WebSites Syntax Errors
  src/Websites/Websites/help/Get-AzStaticWebApp.md
  src/Websites/Websites/help/New-AzWebAppAzureStoragePath.md
  src/Websites/Websites/help/New-AzWebAppDatabaseBackupSetting.md
  src/Websites/Websites/help/Remove-AzStaticWebAppAttachedRepository.md
  src/Websites/Websites/help/Remove-AzStaticWebAppUser.md
  src/Websites/Websites/help/Set-AzWebApp.md
  src/Websites/Websites/help/Unregister-AzStaticWebAppBuildUserProvidedFunctionApp.md
  src/Websites/Websites/help/Unregister-AzStaticWebAppUserProvidedFunctionApp.md
Labels: Doc - Reference, needs-review

#17870 Fix Az.WindowsIotServices Syntax Errors
  src/WindowsIotServices/help/Update-AzWindowsIotServicesDevice.md
Labels: Doc - Reference, needs-review

#17874 Fix Az.Websites Syntax Errors in generation
  src/Websites/Websites.Autorest/docs/Get-AzStaticWebApp.md
  src/Websites/Websites.Autorest/docs/Remove-AzStaticWebAppUser.md
  src/Websites/Websites.Autorest/docs/Unregister-AzStaticWebAppBuildUserProvidedFunctionApp.md
  src/Websites/Websites.Autorest/docs/Unregister-AzStaticWebAppUserProvidedFunctionApp.md
  src/Websites/Websites.Autorest/examples/Get-AzStaticWebApp.md
  src/Websites/Websites.Autorest/examples/Remove-AzStaticWebAppUser.md
  src/Websites/Websites.Autorest/examples/Unregister-AzStaticWebAppBuildUserProvidedFunctionApp.md
  src/Websites/Websites.Autorest/examples/Unregister-AzStaticWebAppUserProvidedFunctionApp.md
Labels: Doc - Reference, needs-review

#17876 Fix Az.WindowsIotServices Syntax Errors in generation
  src/WindowsIotServices/docs/Update-AzWindowsIotServicesDevice.md
  src/WindowsIotServices/examples/Update-AzWindowsIotServicesDevice.md
Labels: Doc - Reference, needs-review

#17859 Edited New-AzVm to ensure the PlatformFaultDomain parameter in the VmConfig object is used
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachinePlatformFaultDomain.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
Labels: Waiting for CI :shipit:

#17965 Fixed network rule set typos across ServiceBus module
  src/ServiceBus/ServiceBus.Test/ScenarioTests/NetworkRuleSetTests.ps1
  src/ServiceBus/ServiceBus/ChangeLog.md
  src/ServiceBus/ServiceBus/Cmdlets/AzureServiceBusCmdletBase.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/GetAzureServiceBusNetworkRuleSet.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/RemoveAzureServiceBusNetworkRuleSet.cs
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/SetAzureServiceBusNetworkrule.cs
  src/ServiceBus/ServiceBus/help/Set-AzServiceBusNetworkRuleSet.md
Labels: Waiting for CI :shipit:

#17866 Adding AuxiliaryMode property to New-AzNetworkInterface cmdlet
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkInterfaceTests/TestNetworkInterfaceCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSNetworkInterface.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkInterface/NewAzureNetworkInterfaceCommand.cs
Labels: Waiting for CI :shipit:

#17769 Fix Az.Resources Syntax Errors
  src/Resources/Resources/help/Get-AzManagementGroupDeployment.md
  src/Resources/Resources/help/Get-AzPolicyDefinition.md
  src/Resources/Resources/help/Get-AzPolicySetDefinition.md
  src/Resources/Resources/help/Get-AzResource.md
  src/Resources/Resources/help/Get-AzResourceGroup.md
  src/Resources/Resources/help/Get-AzTag.md
  src/Resources/Resources/help/Invoke-AzResourceAction.md
  src/Resources/Resources/help/New-AzDeployment.md
  src/Resources/Resources/help/New-AzPolicyAssignment.md
  src/Resources/Resources/help/New-AzTag.md
  src/Resources/Resources/help/Remove-AzResourceGroupDeployment.md
  src/Resources/Resources/help/Remove-AzTag.md
  src/Resources/Resources/help/Save-AzManagementGroupDeploymentTemplate.md
  src/Resources/Resources/help/Save-AzTenantDeploymentTemplate.md
  src/Resources/Resources/help/Set-AzPolicyAssignment.md
  src/Resources/Resources/help/Set-AzPolicySetDefinition.md
  src/Resources/Resources/help/Update-AzManagementGroup.md
  src/Resources/Resources/help/Update-AzTag.md
Labels: Doc - Reference, Waiting for CI :shipit:

#17763 Adding AlertsSuppressionRule cmdlets to Az.Security
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Security/Security.Test/ScenarioTests/AlertsSuppressionRuleTests.cs
  src/Security/Security.Test/ScenarioTests/AlertsSuppressionRuleTests.ps1
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.AlertsSuppressionRuleTests/CreateAndDeleteAlertsSuppressionRule.json
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.AlertsSuppressionRuleTests/GetSubscriptionScope.json
  src/Security/Security/Az.Security.psd1
  src/Security/Security/ChangeLog.md
  src/Security/Security/Cmdlets/AlertsSuppressionRules/GetAlertsSuppressionRule.cs
  src/Security/Security/Cmdlets/AlertsSuppressionRules/NewAlertsSuppressionRuleScope.cs
  src/Security/Security/Cmdlets/AlertsSuppressionRules/RemoveAlertsSuppressionRule.cs
  src/Security/Security/Cmdlets/AlertsSuppressionRules/SetAlertsSuppressionRule.cs
  src/Security/Security/Common/ParameterSetNames.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSAlertsSuppressionRule.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSAlertsSuppressionRuleConverters.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSIScopeElement.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSRuleState.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSScopeElementContains.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSScopeElementIn.cs
  src/Security/Security/Models/AlertsSuppressionRules/PSSuppressionAlertsScope.cs
  src/Security/Security/help/Az.Security.md
  src/Security/Security/help/Get-AzAlertsSuppressionRule.md
  src/Security/Security/help/New-AzAlertsSuppressionRuleScope.md
  src/Security/Security/help/Remove-AzAlertsSuppressionRule.md
  src/Security/Security/help/Set-AzAlertsSuppressionRule.md
  tools/StaticAnalysis/Exceptions/Az.Security/SignatureIssues.csv
Labels: Cmdlet Review Complete, Waiting for CI :shipit:

#17974 Changing on-premise to on-premises
  src/StackHCI/help/Register-AzStackHCI.md
Labels: customer-reported

#17748 Fix Az.PostgreSql Syntax Errors
  src/PostgreSql/help/Get-AzPostgreSqlVirtualNetworkRule.md
  src/PostgreSql/help/New-AzPostgreSqlFirewallRule.md
  src/PostgreSql/help/New-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/New-AzPostgreSqlFlexibleServerDatabase.md
  src/PostgreSql/help/New-AzPostgreSqlFlexibleServerFirewallRule.md
  src/PostgreSql/help/New-AzPostgreSqlReplica.md
  src/PostgreSql/help/New-AzPostgreSqlServer.md
  src/PostgreSql/help/New-AzPostgreSqlVirtualNetworkRule.md
  src/PostgreSql/help/Remove-AzPostgreSqlFirewallRule.md
  src/PostgreSql/help/Remove-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/Remove-AzPostgreSqlFlexibleServerDatabase.md
  src/PostgreSql/help/Remove-AzPostgreSqlFlexibleServerFirewallRule.md
  src/PostgreSql/help/Remove-AzPostgreSqlServer.md
  src/PostgreSql/help/Remove-AzPostgreSqlVirtualNetworkRule.md
  src/PostgreSql/help/Restart-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/Restart-AzPostgreSqlServer.md
  src/PostgreSql/help/Restore-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/Start-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/Stop-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/Test-AzPostgreSqlFlexibleServerConnect.md
  src/PostgreSql/help/Update-AzPostgreSqlConfiguration.md
  src/PostgreSql/help/Update-AzPostgreSqlFirewallRule.md
  src/PostgreSql/help/Update-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/help/Update-AzPostgreSqlFlexibleServerConfiguration.md
  src/PostgreSql/help/Update-AzPostgreSqlFlexibleServerFirewallRule.md
  src/PostgreSql/help/Update-AzPostgreSqlServer.md
  src/PostgreSql/help/Update-AzPostgreSqlVirtualNetworkRule.md
Labels: Doc - Reference

#17781 Fix Az.Security Syntax Errors
  src/Security/Security/help/Add-AzSecurityAdaptiveNetworkHardening.md
  src/Security/Security/help/Get-AzRegulatoryComplianceAssessment.md
  src/Security/Security/help/Get-AzRegulatoryComplianceControl.md
Labels: Doc - Reference, Waiting for CI :shipit:

#17570 Fix Az.DeploymentManager Syntax Errors
  src/DeploymentManager/DeploymentManager/help/Stop-AzDeploymentManagerRollout.md
Labels: Doc - Reference, Waiting for CI :shipit:

#17962 Add AksTestRunner and replace TestController
  src/Aks/Aks.Test/ScenarioTests/AksTestRunner.cs
  src/Aks/Aks.Test/ScenarioTests/KubernetesTests.cs
  src/Aks/Aks.Test/ScenarioTests/NodePoolTests.cs
  src/Aks/Aks.Test/ScenarioTests/TestController.cs
Labels: Test Infra

#17961 Add AdvisorTestRunner and replace TestController
  src/Advisor/Advisor.Test/ScenarioTests/AdvisorTestRunner.cs
  src/Advisor/Advisor.Test/ScenarioTests/DisableAzAdvisorRecommendation.cs
  src/Advisor/Advisor.Test/ScenarioTests/EnableAzAdvisorRecommendation.cs
  src/Advisor/Advisor.Test/ScenarioTests/GetAzAdvisorConfiguration.cs
  src/Advisor/Advisor.Test/ScenarioTests/GetAzAdvisorRecommendation.cs
  src/Advisor/Advisor.Test/ScenarioTests/SetAzAdvisorConfiguration.cs
  src/Advisor/Advisor.Test/ScenarioTests/TestController.cs
Labels: Test Infra

#17989 Network 2021 08 01 is delivering final version of monthly
  src/Batch/Batch.Test/Batch.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/ContainerRegistry/ContainerRegistry.Test/ContainerRegistry.Test.csproj
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HPCCache/HPCCache.Test/HPCCache.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/ScenarioTests/ExpressRoutePortTests.cs
  src/Network/Network.Test/ScenarioTests/ExpressRoutePortTests.ps1
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ExpressRoutePortTests/TestExpressRoutePortAuthorizationCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkInterfaceTests/TestNetworkInterfaceCRUD.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Cortex/CortexParameterSetNames.cs
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/UpdateAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/VirtualHubBaseCmdlet.cs
  src/Network/Network/Cortex/VpnConnection/UpdateAzureRmVpnConnectionCommand.cs
  src/Network/Network/ExpressRouteCircuit/NewAzureExpressRouteCircuitCommand.cs
  src/Network/Network/ExpressRoutePort/Authorization/AddAzureExpressRoutePortAuthorizationCommand.cs
  src/Network/Network/ExpressRoutePort/Authorization/GetAzureExpressRoutePortAuthorizationCommand.cs
  src/Network/Network/ExpressRoutePort/Authorization/RemoveAzureExpressRoutePortAuthorizationCommand.cs
  src/Network/Network/ExpressRoutePort/NewAzureRMExpressRoutePortCommand.cs
  src/Network/Network/Generated/Models/PSExpressRouteCircuit.cs
  src/Network/Network/Generated/Models/PSExpressRoutePortAuthorization.cs
  src/Network/Network/Models/Cortex/PSVirtualHub.cs
  src/Network/Network/Models/PSNetworkInterface.cs
  src/Network/Network/Models/PSPublicIpPrefix.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkInterface/NewAzureNetworkInterfaceCommand.cs
  src/Network/Network/help/Add-AzExpressRoutePortAuthorization.md
  src/Network/Network/help/Get-AzExpressRoutePortAuthorization.md
  src/Network/Network/help/New-AzExpressRouteCircuit.md
  src/Network/Network/help/New-AzVirtualHub.md
  src/Network/Network/help/Remove-AzExpressRoutePortAuthorization.md
  src/Network/Network/help/Update-AzVirtualHub.md
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SignalR/SignalR.Test/SignalR.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: Do Not Squash :no_entry_sign:

#17749 Fix Az.PrivateDNS Syntax Errors
  src/PrivateDns/PrivateDns/help/Add-AzPrivateDnsRecordConfig.md
  src/PrivateDns/PrivateDns/help/Get-AzPrivateDnsRecordSet.md
  src/PrivateDns/PrivateDns/help/Get-AzPrivateDnsVirtualNetworkLink.md
  src/PrivateDns/PrivateDns/help/Get-AzPrivateDnsZone.md
  src/PrivateDns/PrivateDns/help/New-AzPrivateDnsRecordConfig.md
  src/PrivateDns/PrivateDns/help/New-AzPrivateDnsRecordSet.md
  src/PrivateDns/PrivateDns/help/New-AzPrivateDnsZone.md
  src/PrivateDns/PrivateDns/help/Remove-AzPrivateDnsRecordConfig.md
  src/PrivateDns/PrivateDns/help/Remove-AzPrivateDnsRecordSet.md
  src/PrivateDns/PrivateDns/help/Set-AzPrivateDnsRecordSet.md
  src/PrivateDns/PrivateDns/help/Set-AzPrivateDnsZone.md
Labels: Doc - Reference, Waiting for CI :shipit:

#17848 [Smoketest]Add try 3 times with 30s sleeping time
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: Waiting for CI :shipit:

#18012 Update related link in Set-AzKeyVaultManagedStorageSasDefinition
  src/KeyVault/KeyVault/help/Get-AzKeyVaultManagedStorageSasDefinition.md
  src/KeyVault/KeyVault/help/Remove-AzKeyVaultManagedStorageSasDefinition.md
  src/KeyVault/KeyVault/help/Set-AzKeyVaultManagedStorageSasDefinition.md
  src/KeyVault/KeyVault/help/Undo-AzKeyVaultManagedStorageSasDefinitionRemoval.md
Labels: needs-revision, Doc - Reference

#17824 Fix module's dependency
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Directory.Build.props
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine.Polyfiller.dll
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine2.dll
  tools/Az.Tools.Predictor/MockPSConsole/MockPSConsole.csproj
Labels: needs-review, Az.Tools.Predictor

#18011 Keep docs align with the implementation of New-AzFirewallHubIpAddress and New-AzFirewallHubPublicIpAddress
  src/Network/Network/help/New-AzFirewallHubIpAddress.md
  src/Network/Network/help/New-AzFirewallHubPublicIpAddress.md
Labels: Doc - Reference

#17971 Introducing Az.Security SecuritySolutionsReferenceData cmdlets
  src/Security/Security.Test/ScenarioTests/SecuritySolutionsReferenceDataTests.cs
  src/Security/Security.Test/ScenarioTests/SecuritySolutionsReferenceDataTests.ps1
  src/Security/Security.Test/SessionRecords/Microsoft.Azure.Commands.Security.Test.ScenarioTests.SecuritySolutionsReferenceDataTests/GetSubscriptionScope.json
  src/Security/Security/Az.Security.psd1
  src/Security/Security/ChangeLog.md
  src/Security/Security/Cmdlets/SolutionsReferenceData/GetSecuritySolutionReferenceData.cs
  src/Security/Security/Models/SolutionsReferenceData/PSSecuritySolutionReferenceDataConverters.cs
  src/Security/Security/Models/SolutionsReferenceData/PSSolutionReferenceData.cs
  src/Security/Security/help/Get-AzSecuritySolutionsReferenceData.md
Labels: needs-revision

#17998 Fixed dead link to the DCR Overview
  src/Monitor/Monitor/help/New-AzDataCollectionRule.md
Labels: Waiting for CI :shipit:, customer-reported

#18013 Update dependencies of Az.Tools.Predictor
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Directory.Build.props
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine.Polyfiller.dll
  tools/Az.Tools.Predictor/MockPSConsole/Microsoft.PowerShell.PSReadLine2.dll
  tools/Az.Tools.Predictor/MockPSConsole/MockPSConsole.csproj
  tools/Az.Tools.Predictor/NuGet.Config
  tools/Az.Tools.Predictor/build.proj
Labels: Az.Tools.Predictor
