Repository Azure/azure-powershell, pull requests merged in 2022-01, with the labels that each got.

#16732 update DataFactoryV2 example
  src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2IntegrationRuntimeOutboundNetworkDependenciesEndpoint.md
Labels: Waiting for CI :shipit:

#16716 Fixed description for NodeOsDiskSize parameter
  src/Aks/Aks/help/Set-AzAksCluster.md
Labels: customer-reported

#16730 Mitigate Get-AzKeyVaultSecret: Invalid Parameter AsPlainText
  src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificate.md
Labels: customer-reported

#16754 fix accountenabled for update-azaduser
  src/Resources/MSGraph.Autorest/custom/Update-AzADUser.ps1
  src/Resources/MSGraph.Autorest/docs/Update-AzADUser.md
Labels: Waiting for CI :shipit:

#16748 Update New-AzADAppCredential.md
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/New-AzADAppCredential.md
Labels: customer-reported

#16743 Add new cmdlet to query port mapping and update existing inboundNatRule cmdlets
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.cs
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.ps1
  src/Network/Network.Test/ScenarioTests/LoadBalancerTests.cs
  src/Network/Network.Test/ScenarioTests/LoadBalancerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestIPBasedBackendPoolQueryInboundNatRulePortMapping.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestNICBasedBackendPoolQueryInboundNatRulePortMapping.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTests/TestLoadBalancerChildResource.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTests/TestLoadBalancerInboundNatRuleV2.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTests/TestLoadBalancerInboundNatRuleV2InternalLB.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Generated/Models/PSInboundNatRule.cs
  src/Network/Network/Generated/Models/PSInboundNatRulePortMapping.cs
  src/Network/Network/LoadBalancer/GetAzureLoadBalancerBackendAddressInboundNatRulePortMapping.cs
  src/Network/Network/LoadBalancer/InboundNatRule/AddAzureRmLoadBalancerInboundNatRuleConfigCommand.cs
  src/Network/Network/LoadBalancer/InboundNatRule/NewAzureRmLoadBalancerInboundNatRuleConfigCommand.cs
  src/Network/Network/LoadBalancer/InboundNatRule/SetAzureRmLoadBalancerInboundNatRuleConfigCommand.cs
  src/Network/Network/Models/PSLoadBalancerBackendAddress.cs
  src/Network/Network/Models/PSNatRulePortMapping.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/help/Add-AzLoadBalancerInboundNatRuleConfig.md
  src/Network/Network/help/Get-AzLoadBalancerBackendAddressInboundNatRulePortMapping.md
  src/Network/Network/help/New-AzLoadBalancerInboundNatRuleConfig.md
  src/Network/Network/help/Set-AzLoadBalancerInboundNatRuleConfig.md
Labels: needs-review

#16789 Fixed a bug when updating key operations on managed HSM
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Track2Models/Track2HsmClient.cs
Labels: Waiting for CI :shipit:

#16292 Update Get-AzDataLakeGen2ChildItem.md
  src/Storage/Storage.Management/help/Get-AzDataLakeGen2ChildItem.md
Labels: needs-revision, Waiting for CI :shipit:, customer-reported, needs-author-feedback

#16811 [Storage] mgmt- Support create/update storage account with ActiveDirectory new properties: SamAccountName,AccountType
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSAzureFilesIdentityBasedAuthentication.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageAccount.cs
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
Labels: Waiting for CI :shipit:

#16823 Fix typo in Az.Tools.Installer
  tools/Az.Tools.Installer/internal/Install-AzModuleInternal.ps1
  tools/Az.Tools.Installer/internal/Install-SingleModuleFromPackage.ps1
Labels: Waiting for CI :shipit:

#16822 update Security
  src/Security/Security/help/Get-AzSecuritySecureScore.md
  src/Security/Security/help/Get-AzSecuritySecureScoreControl.md
  src/Security/Security/help/Get-AzSecuritySecureScoreControlDefinition.md
Labels: Waiting for CI :shipit:

#16821 update FrontDoor
  src/FrontDoor/FrontDoor/help/Get-AzFrontDoorWafManagedRuleSetDefinition.md
Labels: Waiting for CI :shipit:

#16836 Update Get-AzLogProfile examples
  src/Monitor/Monitor/help/Get-AzLogProfile.md
Labels: Waiting for CI :shipit:

#16835 Add examples to Az.Cdn
  src/Cdn/Cdn/help/Disable-AzCdnCustomDomain.md
  src/Cdn/Cdn/help/Enable-AzCdnCustomDomain.md
  src/Cdn/Cdn/help/Get-AzCdnCustomDomain.md
  src/Cdn/Cdn/help/Get-AzCdnEndpoint.md
  src/Cdn/Cdn/help/Get-AzCdnEndpointNameAvailability.md
  src/Cdn/Cdn/help/Get-AzCdnOrigin.md
  src/Cdn/Cdn/help/Get-AzCdnProfile.md
  src/Cdn/Cdn/help/Get-AzCdnProfileSsoUrl.md
  src/Cdn/Cdn/help/New-AzCdnCustomDomain.md
  src/Cdn/Cdn/help/New-AzCdnEndpoint.md
  src/Cdn/Cdn/help/Publish-AzCdnEndpointContent.md
  src/Cdn/Cdn/help/Remove-AzCdnCustomDomain.md
  src/Cdn/Cdn/help/Remove-AzCdnEndpoint.md
  src/Cdn/Cdn/help/Remove-AzCdnProfile.md
  src/Cdn/Cdn/help/Set-AzCdnEndpoint.md
  src/Cdn/Cdn/help/Set-AzCdnOrigin.md
  src/Cdn/Cdn/help/Set-AzCdnProfile.md
  src/Cdn/Cdn/help/Start-AzCdnEndpoint.md
  src/Cdn/Cdn/help/Stop-AzCdnEndpoint.md
  src/Cdn/Cdn/help/Test-AzCdnCustomDomain.md
  src/Cdn/Cdn/help/Unpublish-AzCdnEndpointContent.md
Labels: Waiting for CI :shipit:

#16834 Update Restore-AzDataLakeStoreDeletedItem examples
  src/DataLakeStore/DataLakeStore/help/Restore-AzDataLakeStoreDeletedItem.md
Labels: Waiting for CI :shipit:

#16833 Update Nuget.Config
  NuGet.Config
  tools/NetCoreCsProjSync/NuGet.Config
  tools/NetCorePsd1Sync/NuGet.Config
Labels: AzureRM 6.x

#16786 fix Set-AzVMExtension bug
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/SetAzureVMExtensionBaseCmdlet.cs
  src/Compute/Compute/Extension/SetAzureVMExtensionCommand.cs
  src/Compute/Compute/help/Add-AzVhd.md
  src/Compute/Compute/help/Az.Compute.md
  src/Compute/Compute/help/Set-AzVMADDomainExtension.md
  src/Compute/Compute/help/Set-AzVMAccessExtension.md
  src/Compute/Compute/help/Set-AzVMBginfoExtension.md
  src/Compute/Compute/help/Set-AzVMExtension.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: needs-revision

#16849 [Az.Resources] Fix parameter set for app/sp credential
  src/Resources/MSGraph.Autorest/custom/New-AzADAppCredential.ps1
  src/Resources/MSGraph.Autorest/custom/New-AzADSpCredential.ps1
Labels: Waiting for CI :shipit:

#16561 Typo "Azure CosmosDB"→"Azure Cosmos DB"
  src/CosmosDB/CosmosDB/help/Get-AzCosmosDBLocation.md
Labels: Doc - Reference, Waiting for CI :shipit:, needs-review, Cosmos, Service Attention, customer-reported

#16862 Remove the survey related cmd from suggestion
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
Labels: Waiting for CI :shipit:, Az.Tools.Predictor

#16863 Fix the unit tests
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/CommandLinePredictorTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockPowerShellRuntime.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/ParameterSetTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSurveyHelper.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Utilities/IPowerShellRuntime.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Utilities/PowerShellRunspaceUtilities.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Utilities/PowerShellRuntime.cs
Labels: Az.Tools.Predictor

#16853 update DevTestLabs
  src/DevTestLabs/DevTestLabs/help/Get-AzDtlAllowedVMSizesPolicy.md
  src/DevTestLabs/DevTestLabs/help/Get-AzDtlVMsPerLabPolicy.md
  src/DevTestLabs/DevTestLabs/help/Get-AzDtlVMsPerUserPolicy.md
  src/DevTestLabs/DevTestLabs/help/Set-AzDtlAllowedVMSizesPolicy.md
  src/DevTestLabs/DevTestLabs/help/Set-AzDtlVMsPerLabPolicy.md
  src/DevTestLabs/DevTestLabs/help/Set-AzDtlVMsPerUserPolicy.md
Labels: Doc - Reference, needs-review

#16474 [Account] Use IArgumentCompleter to implement the Environment parameter auto completer.
  src/Accounts/Accounts.Test/ArgumentCompleterTests.ps1
  src/Accounts/Accounts/Common/EnvironmentCompleterAttribute.cs
Labels: Waiting for CI :shipit:

#16876 Remove duplicated header
  src/Resources/Resources/help/Remove-AzADApplication.md
Labels: Waiting for CI :shipit:, customer-reported

#16860 [OperationalInsights] bug fix - PSStorageInsight failed on null value of containers and tables
  src/OperationalInsights/OperationalInsights/ChangeLog.md
  src/OperationalInsights/OperationalInsights/Models/PSStorageInsight.cs
Labels: Waiting for CI :shipit:

#16889 Public Network Access as optional parameter to `Set-AzServiceBusNetworkRuleSet'
  src/ServiceBus/ServiceBus.Test/ScenarioTests/NetworkRuleSetTests.ps1
  src/ServiceBus/ServiceBus.Test/ScenarioTests/ServiceBusServiceTests.ps1
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.NetworkRuleSetTests/NetworkRuleSetCRUD.json
  src/ServiceBus/ServiceBus.Test/SessionRecords/Microsoft.Azure.Commands.ServiceBus.Test.ScenarioTests.ServiceBusServiceTests/ServiceBusNameSpace_CURD_Tests.json
  src/ServiceBus/ServiceBus/ChangeLog.md
  src/ServiceBus/ServiceBus/Cmdlets/NetworkRuleSet/SetAzureServiceBusNetworkrule.cs
  src/ServiceBus/ServiceBus/Models/PSNetworkRuleSetAttributes.cs
  src/ServiceBus/ServiceBus/ServiceBus.format.ps1xml
  src/ServiceBus/ServiceBus/Utilities/ServiceBusClient.cs
  src/ServiceBus/ServiceBus/help/Set-AzServiceBusNetworkRuleSet.md
Labels: Waiting for CI :shipit:

#16896 Update New-AzADServicePrincipal.md
  src/Resources/Resources/help/New-AzADServicePrincipal.md
Labels: Waiting for CI :shipit:, customer-reported

#16877 [HealthcareApis] Add Warning Message for healthcare apis
  src/HealthcareApis/HealthcareApis/ChangeLog.md
  src/HealthcareApis/HealthcareApis/Common/HealthcareApisBaseCmdlet.cs
Labels: Do Not Merge :no_entry_sign:

#16875 [Traffic Manager] Adding new IPv4 and IPv6 specific parameters for minchild endpoints
  src/TrafficManager/TrafficManager.Test/ScenarioTests/EndpointTests.cs
  src/TrafficManager/TrafficManager.Test/ScenarioTests/NestedEndpointsTests.ps1
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestAddAndRemoveCustomHeadersFromEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestAddAndRemoveIpAddressRanges.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestAddEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestCreateExistingEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestCreateExistingEndpointFromNonExistingProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestDeleteEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestDisableEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestDisableEndpointUsingPiping.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestDisableNonExistingEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEnableEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEnableEndpointUsingPiping.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEnableEndpointUsingPipingFromGetProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEnableNonExistingEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEndpointCrud.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEndpointCrudGeo.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEndpointCrudPiping.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestEndpointTypeCaseInsensitive.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestGetExistingEndpointFromNonExistingProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestPipeEndpointFromGetEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestPipeEndpointFromGetProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestRemoveExistingEndpointFromNonExistingProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.EndpointTests/TestRemoveNonExistingEndpointFromProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.NestedEndpointsTests/TestNestedEndpointsCreateUpdate.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.NestedEndpointsTests/TestProfileWithNestedEndpointsGetPut.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestAddAndRemoveCustomHeadersFromProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestAddAndRemoveExpectedStatusCodeRanges.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestCreateDeleteUsingProfile.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestCrudWithEndpoint.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestCrudWithEndpointGeo.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestListProfilesInResourceGroup.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestListProfilesInSubscription.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestListProfilesWhereObject.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileCrud.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileCrudWithPiping.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileDisable.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileDisableNonExisting.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileDisablePipeline.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileEnable.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileEnableNonExisting.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileEnablePipeline.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileMonitorCustom.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileMonitorDefault.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileMonitorParameterAliases.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileMonitorProtocol.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileNewAlreadyExists.json
  src/TrafficManager/TrafficManager.Test/SessionRecords/Microsoft.Azure.Commands.TrafficManager.Test.ScenarioTests.ProfileTests/TestProfileRemoveNonExisting.json
  src/TrafficManager/TrafficManager.Test/TrafficManager.Test.csproj
  src/TrafficManager/TrafficManager.sln
  src/TrafficManager/TrafficManager/ChangeLog.md
  src/TrafficManager/TrafficManager/Endpoint/AddAzureTrafficManagerEndpointConfig.cs
  src/TrafficManager/TrafficManager/Endpoint/NewAzureTrafficManagerEndpoint.cs
  src/TrafficManager/TrafficManager/Models/TrafficManagerEndpoint.cs
  src/TrafficManager/TrafficManager/TrafficManager.csproj
  src/TrafficManager/TrafficManager/Utilities/TrafficManagerClient.cs
  src/TrafficManager/TrafficManager/help/Add-AzTrafficManagerEndpointConfig.md
  src/TrafficManager/TrafficManager/help/New-AzTrafficManagerEndpoint.md
Labels: Waiting for CI :shipit:

#16855 [NetAppFiles]Apply 2021-08-01 Changes
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/BackupTests.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/QuotaLimitTests.cs
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/QuotaLimitTests.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/SnapshotTests.ps1
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountActiveDirectory.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.AccountTests/TestAccountPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.ActiveDirectoryTests/TestActiveDirectoryCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.ActiveDirectoryTests/TestActiveDirectoryPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupPolicyTests/TestBackupPolicyCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupPolicyTests/TestBackupPolicyPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestBackupCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestBackupPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.BackupTests/TestVolumeBackupStatusCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.PoolTests/TestPoolPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.QuotaLimitTests/TestQuotaLimit.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotPolicyTests/TestSnapshotPolicyCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotPolicyTests/TestSnapshotPolicyPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestCreateVolumeFromSnapshot.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestRestoreVolumeFromSnapshot.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.SnapshotTests/TestSnapshotPipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VaultTests/TestVaultCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestSetVolumePool.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumePipelines.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeTests/TestVolumeReplication.json
  src/NetAppFiles/NetAppFiles/Account/NewNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/ActiveDirectory/NewNetAppFilesActiveDirectory.cs
  src/NetAppFiles/NetAppFiles/ActiveDirectory/UpdateNetAppFilesActiveDirectory.cs
  src/NetAppFiles/NetAppFiles/Az.NetAppFiles.psd1
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/BackupExtensions.cs
  src/NetAppFiles/NetAppFiles/Helpers/ModelExtensions.cs
  src/NetAppFiles/NetAppFiles/Helpers/SubscriptionQuotaItemExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSKeyValuePairs.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesActiveDirectory.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesSubscriptionQuotaLimit.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/NetAppFiles.csproj
  src/NetAppFiles/NetAppFiles/QuotaLimits/GetAzureRmNetAppFilesQuotaLimit.cs
  src/NetAppFiles/NetAppFiles/Volume/NewNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/Volume/UpdateNetAppFilesVolume.cs
  src/NetAppFiles/NetAppFiles/help/Az.NetAppFiles.md
  src/NetAppFiles/NetAppFiles/help/Get-AzNetAppFilesQuotaLimit.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesActiveDirectory.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesVolume.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesActiveDirectory.md
Labels: Waiting for CI :shipit:

#16785 Add Hibernate parameter to New-AzVm and Stop-AzVm
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVirtualMachineHibernate.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Action/StopAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVMConfig.md
  src/Compute/Compute/help/Stop-AzVM.md
  src/Compute/Compute/help/Update-AzVM.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#16895 New fix for adding Public Network Access feature to event hub Set and Get Network rule set command.
  src/EventGrid/EventGrid.Test/EventGrid.Test.csproj
  src/EventHub/EventHub.Test/ScenarioTests/NetworkRuleSetTests.ps1
  src/EventHub/EventHub.Test/SessionRecords/Microsoft.Azure.Commands.EventHub.Test.ScenarioTests.NetworkRuleSetTests/NetworkRuleSetCRUD.json
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/Namespace/SetAzureEventHubNamespace.cs
  src/EventHub/EventHub/Cmdlets/NetworkRuleSet/SetAzureEventHubNetworkrule.cs
  src/EventHub/EventHub/EventHub.format.ps1xml
  src/EventHub/EventHub/Models/PSNetworkRuleSetAttributes.cs
  src/EventHub/EventHub/Utilities/EventHubsClient.cs
  src/EventHub/EventHub/help/Set-AzEventHubNetworkRuleSet.md
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Synapse/Synapse.Test/Synapse.Test.csproj
Labels: Waiting for CI :shipit:

#16907 update Az.OperationalInsights examples
  src/OperationalInsights/OperationalInsights/help/Disable-AzOperationalInsightsIISLogCollection.md
  src/OperationalInsights/OperationalInsights/help/Disable-AzOperationalInsightsLinuxCustomLogCollection.md
  src/OperationalInsights/OperationalInsights/help/Disable-AzOperationalInsightsLinuxPerformanceCollection.md
  src/OperationalInsights/OperationalInsights/help/Disable-AzOperationalInsightsLinuxSyslogCollection.md
  src/OperationalInsights/OperationalInsights/help/Enable-AzOperationalInsightsIISLogCollection.md
  src/OperationalInsights/OperationalInsights/help/Enable-AzOperationalInsightsLinuxCustomLogCollection.md
  src/OperationalInsights/OperationalInsights/help/Enable-AzOperationalInsightsLinuxPerformanceCollection.md
  src/OperationalInsights/OperationalInsights/help/Enable-AzOperationalInsightsLinuxSyslogCollection.md
Labels: Doc - Reference, needs-review

#16880 Split Az.Accounts examples
  src/Accounts/Accounts/help/Add-AzEnvironment.md
  src/Accounts/Accounts/help/Clear-AzContext.md
  src/Accounts/Accounts/help/Clear-AzDefault.md
  src/Accounts/Accounts/help/Disable-AzContextAutosave.md
  src/Accounts/Accounts/help/Disable-AzureRmAlias.md
  src/Accounts/Accounts/help/Disconnect-AzAccount.md
  src/Accounts/Accounts/help/Enable-AzureRmAlias.md
  src/Accounts/Accounts/help/Get-AzAccessToken.md
  src/Accounts/Accounts/help/Get-AzContext.md
  src/Accounts/Accounts/help/Get-AzContextAutosaveSetting.md
  src/Accounts/Accounts/help/Get-AzDefault.md
  src/Accounts/Accounts/help/Get-AzEnvironment.md
  src/Accounts/Accounts/help/Get-AzSubscription.md
  src/Accounts/Accounts/help/Get-AzTenant.md
  src/Accounts/Accounts/help/Import-AzContext.md
  src/Accounts/Accounts/help/Invoke-AzRestMethod.md
  src/Accounts/Accounts/help/Open-AzSurveyLink.md
  src/Accounts/Accounts/help/Register-AzModule.md
  src/Accounts/Accounts/help/Remove-AzContext.md
  src/Accounts/Accounts/help/Remove-AzEnvironment.md
  src/Accounts/Accounts/help/Rename-AzContext.md
  src/Accounts/Accounts/help/Resolve-AzError.md
  src/Accounts/Accounts/help/Save-AzContext.md
  src/Accounts/Accounts/help/Select-AzContext.md
  src/Accounts/Accounts/help/Send-Feedback.md
  src/Accounts/Accounts/help/Set-AzContext.md
  src/Accounts/Accounts/help/Set-AzDefault.md
  src/Accounts/Accounts/help/Set-AzEnvironment.md
  src/Accounts/Accounts/help/Uninstall-AzureRm.md
Labels: Doc - Reference, Waiting for CI :shipit:, needs-review

#16911 (AzureCXP) fixes Azure / azure-powershell#16840
  src/Network/Network/help/Set-AzApplicationGatewayFirewallPolicy.md
Labels: Waiting for CI :shipit:

#16878 update Az.ContainerInstance examples in generation
  src/ContainerInstance/README.md
  src/ContainerInstance/custom/Invoke-AzContainerInstanceCommand.ps1
  src/ContainerInstance/custom/New-AzContainerGroup.ps1
  src/ContainerInstance/custom/New-AzContainerGroupImageRegistryCredentialObject.ps1
  src/ContainerInstance/custom/New-AzContainerGroupPortObject.ps1
  src/ContainerInstance/custom/New-AzContainerGroupVolumeObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceEnvironmentVariableObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceHttpHeaderObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceInitDefinitionObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstancePortObject.ps1
  src/ContainerInstance/custom/New-AzContainerInstanceVolumeMountObject.ps1
  src/ContainerInstance/docs/Invoke-AzContainerInstanceCommand.md
  src/ContainerInstance/docs/New-AzContainerInstanceObject.md
  src/ContainerInstance/examples/Invoke-AzContainerInstanceCommand.md
  src/ContainerInstance/examples/New-AzContainerInstanceObject.md
Labels: needs-revision

#16910 The -Force option is not documented and not accepted as parameter
  src/ApiManagement/ApiManagement/help/Remove-AzApiManagementSubscription.md
Labels: customer-reported

#16905 [Compute] ForceDeletion for VM and VMSS
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestRemoveVmssForceDeletion.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMForceDelete.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetDeleteInstancesMethod.cs
  src/Compute/Compute/VirtualMachine/Operation/RemoveAzureVMCommand.cs
  src/Compute/Compute/help/Remove-AzVM.md
  src/Compute/Compute/help/Remove-AzVmss.md
Labels: needs-revision

#16922 Split Az.AlertsManagement Examples
  src/AlertsManagement/AlertsManagement/help/Get-AzActionRule.md
  src/AlertsManagement/AlertsManagement/help/Get-AzAlert.md
  src/AlertsManagement/AlertsManagement/help/Get-AzAlertObjectHistory.md
  src/AlertsManagement/AlertsManagement/help/Get-AzSmartGroup.md
  src/AlertsManagement/AlertsManagement/help/Get-AzSmartGroupHistory.md
  src/AlertsManagement/AlertsManagement/help/Measure-AzAlertStatistic.md
  src/AlertsManagement/AlertsManagement/help/Remove-AzActionRule.md
  src/AlertsManagement/AlertsManagement/help/Set-AzActionRule.md
  src/AlertsManagement/AlertsManagement/help/Update-AzActionRule.md
  src/AlertsManagement/AlertsManagement/help/Update-AzAlertState.md
  src/AlertsManagement/AlertsManagement/help/Update-AzSmartGroupState.md
Labels: Doc - Reference, needs-review

#16921 Split Az.Aks Examples in generation
  src/Aks/Aks.Autorest/docs/Get-AzAksNodePoolUpgradeProfile.md
  src/Aks/Aks.Autorest/docs/Get-AzAksUpgradeProfile.md
  src/Aks/Aks.Autorest/docs/Get-AzAksVersion.md
  src/Aks/Aks.Autorest/docs/Start-AzAksCluster.md
  src/Aks/Aks.Autorest/docs/Stop-AzAksCluster.md
  src/Aks/Aks.Autorest/examples/Get-AzAksNodePoolUpgradeProfile.md
  src/Aks/Aks.Autorest/examples/Get-AzAksUpgradeProfile.md
  src/Aks/Aks.Autorest/examples/Get-AzAksVersion.md
  src/Aks/Aks.Autorest/examples/Start-AzAksCluster.md
  src/Aks/Aks.Autorest/examples/Stop-AzAksCluster.md
Labels: Doc - Reference, needs-review

#16928 Change default branch of swagger from master to main
  src/readme.azure.noprofile.md
Labels: Waiting for CI :shipit:

#16925 Split Az.AnalysisServices Examples
  src/AnalysisServices/AnalysisServices/help/Add-AzAnalysisServicesAccount.md
  src/AnalysisServices/AnalysisServices/help/Export-AzAnalysisServicesInstanceLog.md
  src/AnalysisServices/AnalysisServices/help/Get-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesFirewallConfig.md
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesFirewallRule.md
  src/AnalysisServices/AnalysisServices/help/New-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Remove-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Restart-AzAnalysisServicesInstance.md
  src/AnalysisServices/AnalysisServices/help/Resume-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Set-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Suspend-AzAnalysisServicesServer.md
  src/AnalysisServices/AnalysisServices/help/Sync-AzAnalysisServicesInstance.md
  src/AnalysisServices/AnalysisServices/help/Test-AzAnalysisServicesServer.md
Labels: Doc - Reference, needs-review

#16926 update Az.Advisor examples
  src/Advisor/Advisor/help/Disable-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Enable-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Get-AzAdvisorConfiguration.md
  src/Advisor/Advisor/help/Get-AzAdvisorRecommendation.md
  src/Advisor/Advisor/help/Set-AzAdvisorConfiguration.md
Labels: Doc - Reference, needs-review

#16923 update Az.ADDomainServices examples
  src/ADDomainServices/help/Get-AzADDomainService.md
  src/ADDomainServices/help/New-AzADDomainService.md
  src/ADDomainServices/help/New-AzADDomainServiceForestTrust.md
  src/ADDomainServices/help/New-AzADDomainServiceReplicaSet.md
  src/ADDomainServices/help/Update-AzADDomainService.md
Labels: Doc - Reference, needs-review

#16941 split AppConfiguration examples
  src/AppConfiguration/help/Get-AzAppConfigurationStore.md
  src/AppConfiguration/help/Get-AzAppConfigurationStoreKey.md
  src/AppConfiguration/help/New-AzAppConfigurationStore.md
  src/AppConfiguration/help/New-AzAppConfigurationStoreKey.md
  src/AppConfiguration/help/Remove-AzAppConfigurationStore.md
  src/AppConfiguration/help/Test-AzAppConfigurationStoreNameAvailability.md
  src/AppConfiguration/help/Update-AzAppConfigurationStore.md
Labels: Doc - Reference, needs-review

#16942 Split Az.Billing Examples
  src/Billing/Billing/help/Get-AzBillingAccount.md
  src/Billing/Billing/help/Get-AzBillingInvoice.md
  src/Billing/Billing/help/Get-AzBillingPeriod.md
  src/Billing/Billing/help/Get-AzBillingProfile.md
  src/Billing/Billing/help/Get-AzConsumptionBudget.md
  src/Billing/Billing/help/Get-AzConsumptionMarketplace.md
  src/Billing/Billing/help/Get-AzConsumptionPriceSheet.md
  src/Billing/Billing/help/Get-AzConsumptionReservationDetail.md
  src/Billing/Billing/help/Get-AzConsumptionReservationSummary.md
  src/Billing/Billing/help/Get-AzConsumptionUsageDetail.md
  src/Billing/Billing/help/Get-AzEnrollmentAccount.md
  src/Billing/Billing/help/Get-AzInvoiceSection.md
  src/Billing/Billing/help/Get-UsageAggregates.md
  src/Billing/Billing/help/New-AzConsumptionBudget.md
  src/Billing/Billing/help/Remove-AzConsumptionBudget.md
  src/Billing/Billing/help/Set-AzConsumptionBudget.md
Labels: Doc - Reference, needs-review

#16948 split Az.Attestation examples
  src/Attestation/Attestation/help/Add-AzAttestationPolicySigner.md
  src/Attestation/Attestation/help/Get-AzAttestation.md
  src/Attestation/Attestation/help/Get-AzAttestationPolicy.md
  src/Attestation/Attestation/help/Get-AzAttestationPolicySigners.md
  src/Attestation/Attestation/help/New-AzAttestation.md
  src/Attestation/Attestation/help/Remove-AzAttestation.md
  src/Attestation/Attestation/help/Remove-AzAttestationPolicySigner.md
  src/Attestation/Attestation/help/Reset-AzAttestationPolicy.md
  src/Attestation/Attestation/help/Set-AzAttestationPolicy.md
Labels: Doc - Reference, needs-review

#16944 Split Az.Blueprint Examples
  src/Blueprint/Blueprint/help/Export-AzBlueprintWithArtifact.md
  src/Blueprint/Blueprint/help/Get-AzBlueprint.md
  src/Blueprint/Blueprint/help/Get-AzBlueprintArtifact.md
  src/Blueprint/Blueprint/help/Get-AzBlueprintAssignment.md
  src/Blueprint/Blueprint/help/Import-AzBlueprintWithArtifact.md
  src/Blueprint/Blueprint/help/New-AzBlueprint.md
  src/Blueprint/Blueprint/help/New-AzBlueprintArtifact.md
  src/Blueprint/Blueprint/help/New-AzBlueprintAssignment.md
  src/Blueprint/Blueprint/help/Publish-AzBlueprint.md
  src/Blueprint/Blueprint/help/Remove-AzBlueprintAssignment.md
  src/Blueprint/Blueprint/help/Set-AzBlueprint.md
  src/Blueprint/Blueprint/help/Set-AzBlueprintArtifact.md
  src/Blueprint/Blueprint/help/Set-AzBlueprintAssignment.md
Labels: Doc - Reference, needs-review

#16946 split ApplicationInsights examples
  src/ApplicationInsights/ApplicationInsights/help/Get-AzApplicationInsights.md
  src/ApplicationInsights/ApplicationInsights/help/Get-AzApplicationInsightsApiKey.md
  src/ApplicationInsights/ApplicationInsights/help/Get-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/ApplicationInsights/help/Get-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsights.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsApiKey.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWebTestGeolocationObject.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWebTestHeaderFieldObject.md
  src/ApplicationInsights/ApplicationInsights/help/Remove-AzApplicationInsights.md
  src/ApplicationInsights/ApplicationInsights/help/Remove-AzApplicationInsightsApiKey.md
  src/ApplicationInsights/ApplicationInsights/help/Remove-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/ApplicationInsights/help/Remove-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights/help/Set-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/ApplicationInsights/help/Set-AzApplicationInsightsDailyCap.md
  src/ApplicationInsights/ApplicationInsights/help/Set-AzApplicationInsightsPricingPlan.md
  src/ApplicationInsights/ApplicationInsights/help/Update-AzApplicationInsightsWebTestTag.md
Labels: Doc - Reference, needs-review

#16957 split AzBotServices examples
  src/BotService/examples/Export-AzBotServiceApp.md
  src/BotService/examples/Get-AzBotService.md
  src/BotService/examples/Initialize-AzBotServicePrepareDeploy.md
  src/BotService/examples/New-AzBotService.md
  src/BotService/examples/Publish-AzBotServiceApp.md
  src/BotService/examples/Remove-AzBotService.md
  src/BotService/examples/Update-AzBotService.md
Labels: Doc - Reference, needs-review

#16958 split ApplicationInsights examples
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/Get-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/New-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/New-AzApplicationInsightsWebTestGeolocationObject.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/New-AzApplicationInsightsWebTestHeaderFieldObject.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/Remove-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights.Autorest/examples/Update-AzApplicationInsightsWebTestTag.md
Labels: Doc - Reference, needs-review

#16819 Adding Remote Support cmdlets for Stack HCI
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/Az.StackHCI.psm1
  src/StackHCI/ChangeLog.md
  src/StackHCI/help/Az.StackHCI.md
  src/StackHCI/help/Disable-AzStackHCIRemoteSupport.md
  src/StackHCI/help/Enable-AzStackHCIRemoteSupport.md
  src/StackHCI/help/Get-AzStackHCIRemoteSupportAccess.md
  src/StackHCI/help/Get-AzStackHCIRemoteSupportSessionHistory.md
  src/StackHCI/help/Install-AzStackHCIRemoteSupport.md
  src/StackHCI/help/Remove-AzStackHCIRemoteSupport.md
Labels: needs-review

#16973 Split Az.Communication Examples in generation
  src/Communication/docs/Get-AzCommunicationService.md
  src/Communication/docs/Get-AzCommunicationServiceKey.md
  src/Communication/docs/New-AzCommunicationService.md
  src/Communication/docs/New-AzCommunicationServiceKey.md
  src/Communication/docs/Remove-AzCommunicationService.md
  src/Communication/docs/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/docs/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/docs/Update-AzCommunicationService.md
  src/Communication/examples/Get-AzCommunicationService.md
  src/Communication/examples/Get-AzCommunicationServiceKey.md
  src/Communication/examples/New-AzCommunicationService.md
  src/Communication/examples/New-AzCommunicationServiceKey.md
  src/Communication/examples/Remove-AzCommunicationService.md
  src/Communication/examples/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/examples/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/examples/Update-AzCommunicationService.md
Labels: Doc - Reference, needs-review

#16972 Split Az.Communication Examples
  src/Communication/help/Get-AzCommunicationService.md
  src/Communication/help/Get-AzCommunicationServiceKey.md
  src/Communication/help/New-AzCommunicationService.md
  src/Communication/help/New-AzCommunicationServiceKey.md
  src/Communication/help/Remove-AzCommunicationService.md
  src/Communication/help/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/help/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/help/Update-AzCommunicationService.md
Labels: Doc - Reference, needs-review

#16962 Split examples of Az.CloudService
  src/CloudService/help/Get-AzCloudService.md
  src/CloudService/help/Get-AzCloudServiceInstanceView.md
  src/CloudService/help/Get-AzCloudServiceNetworkInterfaces.md
  src/CloudService/help/Get-AzCloudServiceOSFamily.md
  src/CloudService/help/Get-AzCloudServiceOSVersion.md
  src/CloudService/help/Get-AzCloudServicePublicIPAddress.md
  src/CloudService/help/Get-AzCloudServiceRoleInstance.md
  src/CloudService/help/Get-AzCloudServiceRoleInstanceRemoteDesktopFile.md
  src/CloudService/help/Get-AzCloudServiceRoleInstanceView.md
  src/CloudService/help/Invoke-AzCloudServiceRebuild.md
  src/CloudService/help/Invoke-AzCloudServiceReimage.md
  src/CloudService/help/Invoke-AzCloudServiceRoleInstanceRebuild.md
  src/CloudService/help/Invoke-AzCloudServiceRoleInstanceReimage.md
  src/CloudService/help/New-AzCloudService.md
  src/CloudService/help/New-AzCloudServiceDiagnosticsExtension.md
  src/CloudService/help/New-AzCloudServiceExtensionObject.md
  src/CloudService/help/New-AzCloudServiceLoadBalancerConfigurationObject.md
  src/CloudService/help/New-AzCloudServiceLoadBalancerFrontendIPConfigurationObject.md
  src/CloudService/help/New-AzCloudServiceRemoteDesktopExtensionObject.md
  src/CloudService/help/Remove-AzCloudService.md
  src/CloudService/help/Remove-AzCloudServiceRoleInstance.md
  src/CloudService/help/Restart-AzCloudService.md
  src/CloudService/help/Restart-AzCloudServiceRoleInstance.md
  src/CloudService/help/Set-AzCloudServiceUpdateDomain.md
  src/CloudService/help/Start-AzCloudService.md
  src/CloudService/help/Stop-AzCloudService.md
  src/CloudService/help/Switch-AzCloudService.md
  src/CloudService/help/Update-AzCloudService.md
Labels: Doc - Reference, needs-review

#16966 Update New-AzDedicatedHsm Description
  src/DedicatedHsm/help/New-AzDedicatedHsm.md
Labels: Doc - Reference, needs-review

#16967 Split Az.Cdn Examples
  src/Cdn/Cdn/help/Confirm-AzCdnEndpointProbeURL.md
  src/Cdn/Cdn/help/Disable-AzCdnCustomDomainHttps.md
  src/Cdn/Cdn/help/Enable-AzCdnCustomDomainHttps.md
  src/Cdn/Cdn/help/Get-AzCdnEndpointResourceUsage.md
  src/Cdn/Cdn/help/Get-AzCdnOriginGroup.md
  src/Cdn/Cdn/help/Get-AzCdnProfileResourceUsage.md
  src/Cdn/Cdn/help/Get-AzCdnProfileSupportedOptimizationType.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnCustomDomain.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnEndpoint.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnOrigin.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnOriginGroup.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnProfile.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnRoute.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnRule.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnRuleSet.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnSecret.md
  src/Cdn/Cdn/help/Get-AzFrontDoorCdnSecurityPolicy.md
  src/Cdn/Cdn/help/New-AzCdnDeliveryPolicy.md
  src/Cdn/Cdn/help/New-AzCdnDeliveryRule.md
  src/Cdn/Cdn/help/New-AzCdnDeliveryRuleAction.md
  src/Cdn/Cdn/help/New-AzCdnDeliveryRuleCondition.md
  src/Cdn/Cdn/help/New-AzCdnOrigin.md
  src/Cdn/Cdn/help/New-AzCdnOriginGroup.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnCustomDomain.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnEndpoint.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnOrigin.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnOriginGroup.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnProfile.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnRoute.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnRule.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnRuleAction.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnRuleCondition.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnRuleSet.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnSecret.md
  src/Cdn/Cdn/help/New-AzFrontDoorCdnSecurityPolicy.md
  src/Cdn/Cdn/help/Remove-AzCdnOrigin.md
  src/Cdn/Cdn/help/Remove-AzCdnOriginGroup.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnCustomDomain.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnEndpoint.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnOrigin.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnOriginGroup.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnProfile.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnRoute.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnRule.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnRuleSet.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnSecret.md
  src/Cdn/Cdn/help/Remove-AzFrontDoorCdnSecurityPolicy.md
  src/Cdn/Cdn/help/Set-AzCdnOriginGroup.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnCustomDomain.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnEndpoint.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnOrigin.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnOriginGroup.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnProfile.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnRoute.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnSecret.md
  src/Cdn/Cdn/help/Set-AzFrontDoorCdnSecurityPolicy.md
Labels: Doc - Reference, needs-review

#16961 Split examples of Az.ChangeAnalysis
  src/ChangeAnalysis/help/Get-AzChangeAnalysis.md
Labels: Doc - Reference, needs-review

#16971 Split Az.CognitiveServices Examples
  src/CognitiveServices/CognitiveServices/help/Add-AzCognitiveServicesAccountNetworkRule.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccount.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountCommitmentPlan.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountDeployment.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountKey.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountNetworkRuleSet.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountSku.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountType.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountUsage.md
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesCommitmentTier.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccount.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccountApiProperty.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccountCommitmentPlan.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccountDeployment.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesAccountKey.md
  src/CognitiveServices/CognitiveServices/help/New-AzCognitiveServicesObject.md
  src/CognitiveServices/CognitiveServices/help/Remove-AzCognitiveServicesAccount.md
  src/CognitiveServices/CognitiveServices/help/Remove-AzCognitiveServicesAccountCommitmentPlan.md
  src/CognitiveServices/CognitiveServices/help/Remove-AzCognitiveServicesAccountDeployment.md
  src/CognitiveServices/CognitiveServices/help/Remove-AzCognitiveServicesAccountNetworkRule.md
  src/CognitiveServices/CognitiveServices/help/Set-AzCognitiveServicesAccount.md
  src/CognitiveServices/CognitiveServices/help/Undo-AzCognitiveServicesAccountRemoval.md
  src/CognitiveServices/CognitiveServices/help/Update-AzCognitiveServicesAccountNetworkRuleSet.md
Labels: Doc - Reference, needs-review

#16866 Update New-AzContainerInstanceObject example
  src/ContainerInstance/help/Invoke-AzContainerInstanceCommand.md
  src/ContainerInstance/help/New-AzContainerInstanceObject.md
Labels: Doc - Reference, needs-review

#16968 Split Az.ChangeAnalysis Examples in generation
  src/ChangeAnalysis/docs/Get-AzChangeAnalysis.md
  src/ChangeAnalysis/examples/Get-AzChangeAnalysis.md
Labels: Doc - Reference, needs-review
