Repository Azure/azure-powershell, pull requests merged in 2022-07, with the labels that each got.

#18845 format the help markdown file of Az.Purview in generation
  src/Purview/Purviewdata.Autorest/docs/New-AzPurviewAzureSqlDataWarehouseScanRulesetObject.md
  src/Purview/Purviewdata.Autorest/examples/New-AzPurviewAzureSqlDataWarehouseScanRulesetObject.md
Labels: Doc - Reference, needs-review

#18843 format the help markdown file of Az.Automation
  src/Automation/Automation/help/New-AzAutomationSchedule.md
Labels: Doc - Reference, needs-review

#18835 format the help markdown file of Az.ServiceBus
  src/ServiceBus/ServiceBus/help/Approve-AzServiceBusPrivateEndpointConnection.md
  src/ServiceBus/ServiceBus/help/Deny-AzServiceBusPrivateEndpointConnection.md
  src/ServiceBus/ServiceBus/help/Get-AzServiceBusPrivateEndpointConnection.md
  src/ServiceBus/ServiceBus/help/Get-AzServiceBusPrivateLink.md
  src/ServiceBus/ServiceBus/help/Remove-AzServiceBusPrivateEndpointConnection.md
Labels: Doc - Reference, needs-review

#18834 format the help markdown file of Az.CosmosDB
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBSqlContainer.md
Labels: Doc - Reference, needs-review

#18833 format the help markdown file of Az.Purview
  src/Purview/Purview/help/Get-AzPurviewSystemScanRuleset.md
Labels: Doc - Reference, needs-review

#18828 format the help markdown file of Az.ResourceGraph
  src/ResourceGraph/ResourceGraph/help/Update-AzResourceGraphQuery.md
Labels: Doc - Reference, needs-review

#18826 format the help markdown file of Az.OperationalInsights
  src/OperationalInsights/OperationalInsights/help/Invoke-AzOperationalInsightsQuery.md
Labels: Doc - Reference, needs-review

#18824 format the help markdown files of Az.MySql in generation
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/docs/Get-AzMySqlFlexibleServerLocationBasedCapability.md
  src/MySql/docs/New-AzMySqlFlexibleServer.md
  src/MySql/examples/Get-AzMySqlFlexibleServerLocationBasedCapability.md
  src/MySql/examples/New-AzMySqlFlexibleServer.md
Labels: Doc - Reference, needs-review

#18822 format the help markdown file of Az.Resources
  src/Resources/Resources/help/New-AzADAppCredential.md
  src/Resources/Resources/help/Stop-AzResourceGroupDeployment.md
Labels: Doc - Reference, needs-review

#18821 format the help markdown files of Az.DesktopVirtualization in generation
  src/DesktopVirtualization/docs/New-AzWvdMsixPackage.md
  src/DesktopVirtualization/docs/Update-AzWvdApplicationGroup.md
  src/DesktopVirtualization/docs/Update-AzWvdDesktop.md
  src/DesktopVirtualization/docs/Update-AzWvdMsixPackage.md
  src/DesktopVirtualization/examples/New-AzWvdMsixPackage.md
  src/DesktopVirtualization/examples/Update-AzWvdApplicationGroup.md
  src/DesktopVirtualization/examples/Update-AzWvdDesktop.md
  src/DesktopVirtualization/examples/Update-AzWvdMsixPackage.md
Labels: Doc - Reference, needs-review

#18820 format the help markdown files of Az.DataMigration in generation
  src/DataMigration/DataMigration.Autorest/docs/Get-AzDataMigrationPerformanceDataCollection.md
  src/DataMigration/DataMigration.Autorest/docs/Get-AzDataMigrationSkuRecommendation.md
  src/DataMigration/DataMigration.Autorest/docs/Get-AzDataMigrationSqlService.md
  src/DataMigration/DataMigration.Autorest/docs/Get-AzDataMigrationSqlServiceIntegrationRuntimeMetric.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationToSqlDb.md
  src/DataMigration/DataMigration.Autorest/docs/Register-AzDataMigrationIntegrationRuntime.md
  src/DataMigration/DataMigration.Autorest/docs/Remove-AzDataMigrationSqlServiceNode.md
  src/DataMigration/DataMigration.Autorest/examples/Get-AzDataMigrationPerformanceDataCollection.md
  src/DataMigration/DataMigration.Autorest/examples/Get-AzDataMigrationSkuRecommendation.md
  src/DataMigration/DataMigration.Autorest/examples/Get-AzDataMigrationSqlService.md
  src/DataMigration/DataMigration.Autorest/examples/Get-AzDataMigrationSqlServiceIntegrationRuntimeMetric.md
  src/DataMigration/DataMigration.Autorest/examples/New-AzDataMigrationToSqlDb.md
  src/DataMigration/DataMigration.Autorest/examples/Register-AzDataMigrationIntegrationRuntime.md
  src/DataMigration/DataMigration.Autorest/examples/Remove-AzDataMigrationSqlServiceNode.md
Labels: Doc - Reference, needs-review

#18818 format the help markdown file of Az.Security
  src/Security/Security/help/Set-AzSecurityAutomation.md
Labels: Doc - Reference, needs-review

#18817 format the help markdown files of Az.DataProtection in generation
  src/DataProtection/docs/Backup-AzDataProtectionBackupInstanceAdhoc.md
  src/DataProtection/docs/Edit-AzDataProtectionPolicyRetentionRuleClientObject.md
  src/DataProtection/docs/Edit-AzDataProtectionPolicyTagClientObject.md
  src/DataProtection/docs/Edit-AzDataProtectionPolicyTriggerClientObject.md
  src/DataProtection/docs/Find-AzDataProtectionRestorableTimeRange.md
  src/DataProtection/docs/Get-AzDataProtectionBackupInstance.md
  src/DataProtection/docs/Get-AzDataProtectionBackupPolicy.md
  src/DataProtection/docs/Get-AzDataProtectionBackupVault.md
  src/DataProtection/docs/Get-AzDataProtectionJob.md
  src/DataProtection/docs/Get-AzDataProtectionOperation.md
  src/DataProtection/docs/Get-AzDataProtectionPolicyTemplate.md
  src/DataProtection/docs/Get-AzDataProtectionRecoveryPoint.md
  src/DataProtection/docs/Get-AzDataProtectionResourceGuard.md
  src/DataProtection/docs/Initialize-AzDataProtectionBackupInstance.md
  src/DataProtection/docs/Initialize-AzDataProtectionRestoreRequest.md
  src/DataProtection/docs/New-AzDataProtectionBackupInstance.md
  src/DataProtection/docs/New-AzDataProtectionBackupPolicy.md
  src/DataProtection/docs/New-AzDataProtectionBackupVault.md
  src/DataProtection/docs/New-AzDataProtectionBackupVaultStorageSettingObject.md
  src/DataProtection/docs/New-AzDataProtectionPolicyTagCriteriaClientObject.md
  src/DataProtection/docs/New-AzDataProtectionPolicyTriggerScheduleClientObject.md
  src/DataProtection/docs/New-AzDataProtectionResourceGuard.md
  src/DataProtection/docs/New-AzDataProtectionRetentionLifeCycleClientObject.md
  src/DataProtection/docs/Remove-AzDataProtectionBackupInstance.md
  src/DataProtection/docs/Remove-AzDataProtectionBackupPolicy.md
  src/DataProtection/docs/Remove-AzDataProtectionBackupVault.md
  src/DataProtection/docs/Remove-AzDataProtectionResourceGuard.md
  src/DataProtection/docs/Resume-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/docs/Search-AzDataProtectionBackupInstanceInAzGraph.md
  src/DataProtection/docs/Search-AzDataProtectionJobInAzGraph.md
  src/DataProtection/docs/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/docs/Stop-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/docs/Suspend-AzDataProtectionBackupInstanceBackup.md
  src/DataProtection/docs/Sync-AzDataProtectionBackupInstance.md
  src/DataProtection/docs/Update-AzDataProtectionBackupInstanceAssociatedPolicy.md
  src/DataProtection/docs/Update-AzDataProtectionBackupVault.md
  src/DataProtection/docs/Update-AzDataProtectionResourceGuard.md
  src/DataProtection/examples/Backup-AzDataProtectionBackupInstanceAdhoc.md
  src/DataProtection/examples/Get-AzDataProtectionBackupInstance.md
  src/DataProtection/examples/Get-AzDataProtectionResourceGuard.md
  src/DataProtection/examples/Initialize-AzDataProtectionRestoreRequest.md
  src/DataProtection/examples/New-AzDataProtectionBackupInstance.md
  src/DataProtection/examples/New-AzDataProtectionBackupPolicy.md
  src/DataProtection/examples/New-AzDataProtectionResourceGuard.md
  src/DataProtection/examples/Remove-AzDataProtectionBackupInstance.md
  src/DataProtection/examples/Remove-AzDataProtectionBackupPolicy.md
  src/DataProtection/examples/Remove-AzDataProtectionBackupVault.md
  src/DataProtection/examples/Remove-AzDataProtectionResourceGuard.md
  src/DataProtection/examples/Resume-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/examples/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/examples/Stop-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/examples/Suspend-AzDataProtectionBackupInstanceBackup.md
  src/DataProtection/examples/Sync-AzDataProtectionBackupInstance.md
  src/DataProtection/examples/Update-AzDataProtectionBackupVault.md
  src/DataProtection/examples/Update-AzDataProtectionResourceGuard.md
Labels: Doc - Reference, needs-review

#18816 format the help markdown file of Az.SqlVirtualMachine
  src/SqlVirtualMachine/SqlVirtualMachine/help/Update-AzSqlVM.md
Labels: Doc - Reference, needs-review

#18813 format the help markdown file of Az.ProviderHub
  src/ProviderHub/help/New-AzProviderHubManifest.md
Labels: Doc - Reference, needs-review

#18812 format the help markdown file of Az.PrivateDns
  src/PrivateDns/PrivateDns/help/Add-AzPrivateDnsRecordConfig.md
Labels: Doc - Reference, needs-review

#18809 format the help markdown file of Az.KubernetesConfiguration in generation
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfigFluxOperationStatus.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/New-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/Update-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/Update-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfigFluxOperationStatus.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/New-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/New-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/Update-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/Update-AzKubernetesExtension.md
Labels: Doc - Reference, needs-review

#18808 format the help markdown file of Az.DataBoxEdge
  src/DataBoxEdge/DataBoxEdge/help/New-AzDataBoxEdgeBandwidthSchedule.md
  src/DataBoxEdge/DataBoxEdge/help/Set-AzDataBoxEdgeBandwidthSchedule.md
Labels: Doc - Reference

#18807 format the help markdown file of Az.KubernetesConfiguration
  src/KubernetesConfiguration/help/Get-AzKubernetesConfigFluxOperationStatus.md
  src/KubernetesConfiguration/help/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/help/Get-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/help/Get-AzKubernetesExtension.md
  src/KubernetesConfiguration/help/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/help/New-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/help/New-AzKubernetesExtension.md
  src/KubernetesConfiguration/help/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/help/Remove-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/help/Remove-AzKubernetesExtension.md
  src/KubernetesConfiguration/help/Update-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/help/Update-AzKubernetesExtension.md
Labels: Doc - Reference, needs-review

#18806 format the help markdown file of Az.HDInsight
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
Labels: Doc - Reference, needs-review

#18803 format the help markdown file of Az.EventHub
  src/EventHub/EventHub/help/Approve-AzEventHubPrivateEndpointConnection.md
  src/EventHub/EventHub/help/Deny-AzEventHubPrivateEndpointConnection.md
  src/EventHub/EventHub/help/Get-AzEventHubApplicationGroup.md
  src/EventHub/EventHub/help/Get-AzEventHubPrivateEndpointConnection.md
  src/EventHub/EventHub/help/Get-AzEventHubPrivateLink.md
  src/EventHub/EventHub/help/New-AzEventHubApplicationGroup.md
  src/EventHub/EventHub/help/New-AzEventHubThrottlingPolicyConfig.md
  src/EventHub/EventHub/help/Remove-AzEventHubApplicationGroup.md
  src/EventHub/EventHub/help/Remove-AzEventHubPrivateEndpointConnection.md
  src/EventHub/EventHub/help/Set-AzEventHubApplicationGroup.md
Labels: Doc - Reference, needs-review

#18801 format the help markdown file of Az.ADDomainServices in generation
  src/ADDomainServices/docs/New-AzADDomainService.md
  src/ADDomainServices/examples/New-AzADDomainService.md
Labels: Doc - Reference, needs-review

#18800 format the help markdown file of Az.ADDomainServices
  src/ADDomainServices/help/New-AzADDomainService.md
Labels: Doc - Reference, needs-review

#18796 format the help markdown file of Az.SpringCloud in generation
  src/SpringCloud/docs/New-AzSpringCloudAppDeployment.md
  src/SpringCloud/examples/New-AzSpringCloudAppDeployment.md
Labels: Doc - Reference, needs-review

#18795 format the help markdown file of Az.SpringCloud
  src/SpringCloud/help/New-AzSpringCloudAppDeployment.md
Labels: Doc - Reference, needs-review

#18793 format the help markdown file of Az.ApplicationInsights in generation
  src/ApplicationInsights/docs/Remove-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/docs/Set-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/examples/Remove-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/examples/Set-AzApplicationInsightsContinuousExport.md
Labels: Doc - Reference, needs-review

#18792 format the help markdown file of Az.ApplicationInsights
  src/ApplicationInsights/help/Remove-AzApplicationInsightsContinuousExport.md
  src/ApplicationInsights/help/Set-AzApplicationInsightsContinuousExport.md
Labels: Doc - Reference, needs-review

#18779 add examples in Get-AzQuotaOperation file
  src/Quota/help/Get-AzQuotaOperation.md
Labels: Doc - Reference, needs-review

#18778 format the help markdown files of Az.DedicatedHsm in generation
  src/DedicatedHsm/docs/Remove-AzDedicatedHsm.md
  src/DedicatedHsm/docs/Update-AzDedicatedHsm.md
  src/DedicatedHsm/examples/Update-AzDedicatedHsm.md
Labels: Doc - Reference, needs-review

#18776 format the help markdown files of Az.CloudService in generation
  src/CloudService/docs/Get-AzCloudService.md
  src/CloudService/docs/Get-AzCloudServiceNetworkInterface.md
  src/CloudService/docs/Get-AzCloudServicePublicIPAddress.md
  src/CloudService/examples/Get-AzCloudService.md
  src/CloudService/examples/Get-AzCloudServiceNetworkInterface.md
  src/CloudService/examples/Get-AzCloudServicePublicIPAddress.md
Labels: Doc - Reference, needs-review

#18775 format the help markdown files of Az.CloudService
  src/CloudService/help/Get-AzCloudService.md
  src/CloudService/help/Get-AzCloudServiceNetworkInterface.md
  src/CloudService/help/Get-AzCloudServicePublicIPAddress.md
Labels: Doc - Reference, needs-review

#18772 format the help markdown files of Az.ConnectedNetwork
  src/ConnectedNetwork/help/Get-AzConnectedNetworkDevice.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkDeviceRegistrationKey.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkFunction.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkFunctionVendor.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkVendor.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkVendorFunction.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkVendorFunctionRoleInstance.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkVendorSku.md
  src/ConnectedNetwork/help/Get-AzConnectedNetworkVendorSkuPreview.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkAzureStackEdgeObject.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkDevice.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkFunction.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkFunctionRoleConfigurationObject.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkFunctionUserConfigurationObject.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkFunctionVendorConfigurationObject.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkInterfaceIPConfigurationObject.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkInterfaceObject.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkVendor.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkVendorFunction.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkVendorSku.md
  src/ConnectedNetwork/help/New-AzConnectedNetworkVendorSkuPreview.md
  src/ConnectedNetwork/help/Remove-AzConnectedNetworkDevice.md
  src/ConnectedNetwork/help/Remove-AzConnectedNetworkFunction.md
  src/ConnectedNetwork/help/Remove-AzConnectedNetworkVendor.md
  src/ConnectedNetwork/help/Remove-AzConnectedNetworkVendorSku.md
  src/ConnectedNetwork/help/Remove-AzConnectedNetworkVendorSkuPreview.md
  src/ConnectedNetwork/help/Restart-AzConnectedNetworkVendorFunctionRoleInstance.md
  src/ConnectedNetwork/help/Start-AzConnectedNetworkVendorFunctionRoleInstance.md
  src/ConnectedNetwork/help/Stop-AzConnectedNetworkVendorFunctionRoleInstance.md
  src/ConnectedNetwork/help/Update-AzConnectedNetworkDeviceTag.md
  src/ConnectedNetwork/help/Update-AzConnectedNetworkFunctionTag.md
Labels: Doc - Reference, needs-review

#18771 format the help markdown files of Az.CognitiveServices
  src/CognitiveServices/CognitiveServices/help/Get-AzCognitiveServicesAccountModel.md
  src/CognitiveServices/CognitiveServices/help/Update-AzCognitiveServicesAccountNetworkRuleSet.md
Labels: Doc - Reference, needs-review

#18754 format the help markdown files of Az.Synapse in generation
  src/Synapse/Synapse.Autorest/docs/New-AzSynapseKustoPoolDataConnection.md
  src/Synapse/Synapse.Autorest/examples/New-AzSynapseKustoPoolDataConnection.md
Labels: Doc - Reference, needs-review

#18688 format the help markdown files of Az.Sql
  src/Sql/Sql/help/Disable-AzSqlInstanceAdvancedDataSecurity.md
  src/Sql/Sql/help/Get-AzSqlInstanceAdvancedDataSecurityPolicy.md
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting.md
  src/Sql/Sql/help/Get-AzSqlInstanceEndpointCertificate.md
  src/Sql/Sql/help/Get-AzSqlInstanceLink.md
  src/Sql/Sql/help/Get-AzSqlInstanceServerTrustCertificate.md
  src/Sql/Sql/help/Get-AzSqlInstanceVulnerabilityAssessmentSetting.md
  src/Sql/Sql/help/Get-AzSqlServerRecommendedAction.md
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlInstanceLink.md
  src/Sql/Sql/help/New-AzSqlInstanceServerTrustCertificate.md
  src/Sql/Sql/help/New-AzSqlSyncAgent.md
  src/Sql/Sql/help/New-AzSqlSyncGroup.md
  src/Sql/Sql/help/New-AzSqlSyncMember.md
  src/Sql/Sql/help/Remove-AzSqlInstanceLink.md
  src/Sql/Sql/help/Remove-AzSqlInstanceServerTrustCertificate.md
  src/Sql/Sql/help/Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline.md
  src/Sql/Sql/help/Start-AzSqlInstanceDatabaseLogReplay.md
  src/Sql/Sql/help/Start-AzSqlInstanceDatabaseVulnerabilityAssessmentScan.md
  src/Sql/Sql/help/Update-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting.md
  src/Sql/Sql/help/Update-AzSqlInstanceLink.md
  src/Sql/Sql/help/Update-AzSqlInstanceVulnerabilityAssessmentSetting.md
  src/Sql/Sql/help/Update-AzSqlSyncGroup.md
  src/Sql/Sql/help/Update-AzSqlSyncMember.md
Labels: Doc - Reference, needs-review

#18705 format the help markdown files of Az.PolicyInsights
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyState.md
Labels: Doc - Reference, needs-review

#18708 format the help markdown files of Az.RecoveryServices
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupRPMountScript.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupJob.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRPMountScript.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupWorkloadRecoveryConfig.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesResourceGuardMapping.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVaultSettingsFile.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrPolicy.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrvCenter.md
  src/RecoveryServices/RecoveryServices/help/Remove-AzRecoveryServicesResourceGuardMapping.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesResourceGuardMapping.md
  src/RecoveryServices/RecoveryServices/help/Start-AzRecoveryServicesAsrSwitchAppliance.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesAsrPolicy.md
Labels: Doc - Reference, needs-review

#18710 format the help markdown files of Az.DataProtection
  src/DataProtection/help/Backup-AzDataProtectionBackupInstanceAdhoc.md
  src/DataProtection/help/Get-AzDataProtectionBackupInstance.md
  src/DataProtection/help/Get-AzDataProtectionResourceGuard.md
  src/DataProtection/help/Initialize-AzDataProtectionRestoreRequest.md
  src/DataProtection/help/New-AzDataProtectionBackupPolicy.md
  src/DataProtection/help/New-AzDataProtectionResourceGuard.md
  src/DataProtection/help/Remove-AzDataProtectionBackupInstance.md
  src/DataProtection/help/Remove-AzDataProtectionBackupPolicy.md
  src/DataProtection/help/Remove-AzDataProtectionBackupVault.md
  src/DataProtection/help/Remove-AzDataProtectionResourceGuard.md
  src/DataProtection/help/Resume-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/help/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/help/Stop-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/help/Suspend-AzDataProtectionBackupInstanceBackup.md
  src/DataProtection/help/Sync-AzDataProtectionBackupInstance.md
  src/DataProtection/help/Update-AzDataProtectionBackupVault.md
  src/DataProtection/help/Update-AzDataProtectionResourceGuard.md
Labels: Doc - Reference, needs-review

#18711 format the help markdown files of Az.DataMigration
  src/DataMigration/DataMigration/help/Get-AzDataMigrationPerformanceDataCollection.md
  src/DataMigration/DataMigration/help/Get-AzDataMigrationSkuRecommendation.md
  src/DataMigration/DataMigration/help/Get-AzDataMigrationSqlServiceIntegrationRuntimeMetric.md
  src/DataMigration/DataMigration/help/Invoke-AzDataMigrationCommand.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationConnectionInfo.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationSyncSelectedDBObject.md
  src/DataMigration/DataMigration/help/Register-AzDataMigrationIntegrationRuntime.md
  src/DataMigration/DataMigration/help/Remove-AzDataMigrationSqlServiceNode.md
  src/DataMigration/DataMigration/help/Remove-AzDataMigrationTask.md
Labels: Doc - Reference, needs-review

#18713 format the help markdown files of Az.DesktopVirtualization
  src/DesktopVirtualization/help/New-AzWvdMsixPackage.md
  src/DesktopVirtualization/help/Update-AzWvdApplicationGroup.md
  src/DesktopVirtualization/help/Update-AzWvdDesktop.md
  src/DesktopVirtualization/help/Update-AzWvdMsixPackage.md
Labels: Doc - Reference, needs-review

#18743 format the help markdown files of Az.ContainerInstance in generation
  src/ContainerInstance/docs/New-AzContainerGroupVolumeObject.md
  src/ContainerInstance/docs/New-AzContainerInstanceVolumeMountObject.md
  src/ContainerInstance/examples/New-AzContainerGroupVolumeObject.md
  src/ContainerInstance/examples/New-AzContainerInstanceVolumeMountObject.md
Labels: Doc - Reference, needs-review

#18750 format the help markdown files of Az.Synapse
  src/Synapse/Synapse/help/Disable-AzSynapseActiveDirectoryOnlyAuthentication.md
  src/Synapse/Synapse/help/Enable-AzSynapseActiveDirectoryOnlyAuthentication.md
  src/Synapse/Synapse/help/Get-AzSynapseActiveDirectoryOnlyAuthentication.md
  src/Synapse/Synapse/help/Get-AzSynapseLinkConnection.md
  src/Synapse/Synapse/help/Get-AzSynapseLinkConnectionDetailedStatus.md
  src/Synapse/Synapse/help/Get-AzSynapseLinkConnectionLinkTable.md
  src/Synapse/Synapse/help/Get-AzSynapseLinkConnectionLinkTableStatus.md
  src/Synapse/Synapse/help/Invoke-AzSynapseSparkStatement.md
  src/Synapse/Synapse/help/New-AzSynapseKustoPoolDataConnection.md
  src/Synapse/Synapse/help/Remove-AzSynapseLinkConnection.md
  src/Synapse/Synapse/help/Remove-AzSynapseSqlPoolRestorePoint.md
  src/Synapse/Synapse/help/Set-AzSynapseLinkConnection.md
  src/Synapse/Synapse/help/Set-AzSynapseLinkConnectionLinkTable.md
  src/Synapse/Synapse/help/Start-AzSynapseLinkConnection.md
  src/Synapse/Synapse/help/Start-AzSynapseSqlPoolVulnerabilityAssessmentScan.md
  src/Synapse/Synapse/help/Stop-AzSynapseLinkConnection.md
  src/Synapse/Synapse/help/Update-AzSynapseLinkConnectionLandingZoneCredential.md
  src/Synapse/Synapse/help/Update-AzSynapseSqlPoolVulnerabilityAssessmentSetting.md
Labels: Doc - Reference, needs-review

#18751 format the help markdown files of Az.ManagedServiceIdentity in generation
  src/ManagedServiceIdentity/docs/Get-AzSystemAssignedIdentity.md
  src/ManagedServiceIdentity/docs/Get-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/docs/New-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/docs/Remove-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/docs/Update-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/examples/Get-AzSystemAssignedIdentity.md
  src/ManagedServiceIdentity/examples/Get-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/examples/New-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/examples/Remove-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/examples/Update-AzUserAssignedIdentity.md
Labels: Doc - Reference, needs-review

#18714 format the help markdown files of Az.DeviceProvisioningServices
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Add-AzIoTDeviceProvisioningServiceAccessPolicy.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Add-AzIoTDeviceProvisioningServiceLinkedHub.md
  src/DeviceProvisioningServices/DeviceProvisioningServices/help/Update-AzIoTDeviceProvisioningServiceLinkedHub.md
Labels: Doc - Reference, needs-review

#18717 format the help markdown files of Az.MySql
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/help/Get-AzMySqlFlexibleServerLocationBasedCapability.md
  src/MySql/help/New-AzMySqlFlexibleServer.md
Labels: Doc - Reference, needs-review

#18740 format the help markdown files of Az.ConfidentialLedger
  src/ConfidentialLedger/help/Get-AzConfidentialLedger.md
  src/ConfidentialLedger/help/New-AzConfidentialLedger.md
  src/ConfidentialLedger/help/New-AzConfidentialLedgerAADBasedSecurityPrincipalObject.md
  src/ConfidentialLedger/help/New-AzConfidentialLedgerCertBasedSecurityPrincipalObject.md
  src/ConfidentialLedger/help/Remove-AzConfidentialLedger.md
  src/ConfidentialLedger/help/Test-AzConfidentialLedgerNameAvailability.md
  src/ConfidentialLedger/help/Update-AzConfidentialLedger.md
Labels: Doc - Reference, needs-review

#18741 format the help markdown files of Az.ConfidentialLedger in generation
  src/ConfidentialLedger/docs/Get-AzConfidentialLedger.md
  src/ConfidentialLedger/docs/New-AzConfidentialLedger.md
  src/ConfidentialLedger/docs/New-AzConfidentialLedgerAADBasedSecurityPrincipalObject.md
  src/ConfidentialLedger/docs/New-AzConfidentialLedgerCertBasedSecurityPrincipalObject.md
  src/ConfidentialLedger/docs/Remove-AzConfidentialLedger.md
  src/ConfidentialLedger/docs/Test-AzConfidentialLedgerNameAvailability.md
  src/ConfidentialLedger/docs/Update-AzConfidentialLedger.md
  src/ConfidentialLedger/examples/Get-AzConfidentialLedger.md
  src/ConfidentialLedger/examples/New-AzConfidentialLedger.md
  src/ConfidentialLedger/examples/New-AzConfidentialLedgerAADBasedSecurityPrincipalObject.md
  src/ConfidentialLedger/examples/New-AzConfidentialLedgerCertBasedSecurityPrincipalObject.md
  src/ConfidentialLedger/examples/Remove-AzConfidentialLedger.md
  src/ConfidentialLedger/examples/Test-AzConfidentialLedgerNameAvailability.md
  src/ConfidentialLedger/examples/Update-AzConfidentialLedger.md
Labels: Doc - Reference, needs-review

#18798 format the help markdown file of Az.ConnectedMachine
  src/ConnectedMachine/help/Get-AzConnectedPrivateLinkScope.md
  src/ConnectedMachine/help/Update-AzConnectedMachineExtension.md
  src/ConnectedMachine/help/Update-AzConnectedPrivateLinkScopeTag.md
Labels: Doc - Reference, needs-review

#18805 format the help markdown file of Az.ContainerRegistry
  src/ContainerRegistry/ContainerRegistry/help/Import-AzContainerRegistryImage.md
Labels: Doc - Reference

#18752 format the help markdown files of Az.ManagedServiceIdentity
  src/ManagedServiceIdentity/help/Get-AzSystemAssignedIdentity.md
  src/ManagedServiceIdentity/help/Get-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/help/New-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/help/Remove-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/help/Update-AzUserAssignedIdentity.md
Labels: Doc - Reference, needs-review

#18854 Fix typos in New-AzVM.md&Restore-AzApiManagement.md
  src/ApiManagement/ApiManagement/help/Restore-AzApiManagement.md
  src/Compute/Compute/help/New-AzVM.md
Labels: Waiting for CI :shipit:

#18715 format the help markdown files of Az.DnsResolver
  src/DnsResolver/help/Get-AzDnsForwardingRuleset.md
  src/DnsResolver/help/Get-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/help/Get-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/help/New-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/help/Remove-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/help/Update-AzDnsForwardingRuleset.md
  src/DnsResolver/help/Update-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/help/Update-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/help/Update-AzDnsResolverOutboundEndpoint.md
Labels: Doc - Reference, needs-review

#18823 format the help markdown files of Az.DnsResolver in generation
  src/DnsResolver/docs/Get-AzDnsForwardingRuleset.md
  src/DnsResolver/docs/Get-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/docs/New-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/docs/Remove-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/docs/Update-AzDnsForwardingRuleset.md
  src/DnsResolver/docs/Update-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/docs/Update-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/docs/Update-AzDnsResolverOutboundEndpoint.md
  src/DnsResolver/examples/Get-AzDnsForwardingRuleset.md
  src/DnsResolver/examples/Get-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/examples/Get-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/examples/New-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/examples/Remove-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/examples/Update-AzDnsForwardingRuleset.md
  src/DnsResolver/examples/Update-AzDnsForwardingRulesetVirtualNetworkLink.md
  src/DnsResolver/examples/Update-AzDnsResolverInboundEndpoint.md
  src/DnsResolver/examples/Update-AzDnsResolverOutboundEndpoint.md
Labels: Doc - Reference, needs-review

#18794 format the help markdown file of Az.Monitor
  src/Monitor/Monitor/help/Update-AzDataCollectionRule.md
Labels: Doc - Reference, needs-review

#18774 format the help markdown files of Az.SecurityInsights
  src/SecurityInsights/SecurityInsights/help/New-AzSentinelIncidentOwner.md
  src/SecurityInsights/SecurityInsights/help/Update-AzSentinelAlertRuleAction.md
  src/SecurityInsights/SecurityInsights/help/Update-AzSentinelBookmark.md
  src/SecurityInsights/SecurityInsights/help/Update-AzSentinelIncident.md
Labels: Doc - Reference, needs-review

#18748 format the help markdown files of Az.Migrate in generation
  src/Migrate/docs/Initialize-AzMigrateReplicationInfrastructure.md
  src/Migrate/examples/Initialize-AzMigrateReplicationInfrastructure.md
Labels: Doc - Reference, needs-review

#18747 format the help markdown files of Az.Migrate
  src/Migrate/help/Initialize-AzMigrateReplicationInfrastructure.md
Labels: Doc - Reference, needs-review

#18667 format the help markdown files of Az.Network
  src/Network/Network/help/Add-AzApplicationGatewayPrivateLinkConfiguration.md
  src/Network/Network/help/Add-AzExpressRoutePortAuthorization.md
  src/Network/Network/help/Get-AzApplicationGatewayTrustedRootCertificate.md
  src/Network/Network/help/Get-AzExpressRoutePortAuthorization.md
  src/Network/Network/help/Get-AzNetworkInterfaceTapConfig.md
  src/Network/Network/help/Get-AzNetworkSecurityRuleConfig.md
  src/Network/Network/help/Get-AzNetworkWatcherTopology.md
  src/Network/Network/help/Get-AzVirtualNetworkSubnetConfig.md
  src/Network/Network/help/Get-AzVirtualWan.md
  src/Network/Network/help/Get-AzVpnClientPackage.md
  src/Network/Network/help/New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleSet.md
  src/Network/Network/help/New-AzApplicationGatewayFirewallPolicyManagedRuleSet.md
  src/Network/Network/help/New-AzApplicationGatewayHttpListener.md
  src/Network/Network/help/New-AzFirewallPolicy.md
  src/Network/Network/help/New-AzFirewallPolicyIntrusionDetection.md
  src/Network/Network/help/New-AzFirewallPolicyRuleCollectionGroup.md
  src/Network/Network/help/New-AzLoadBalancerBackendAddressPool.md
  src/Network/Network/help/New-AzLoadBalancerBackendAddressPoolConfig.md
  src/Network/Network/help/New-AzLoadBalancerBackendAddressPoolTunnelInterfaceConfig.md
  src/Network/Network/help/New-AzNetworkInterfaceIpConfig.md
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject.md
  src/Network/Network/help/New-AzVirtualNetworkGatewayConnection.md
  src/Network/Network/help/New-AzVpnGateway.md
  src/Network/Network/help/Remove-AzApplicationGatewayHttpListenerCustomError.md
  src/Network/Network/help/Remove-AzExpressRoutePortAuthorization.md
  src/Network/Network/help/Remove-AzFirewallPolicy.md
  src/Network/Network/help/Remove-AzP2sVpnGateway.md
  src/Network/Network/help/Remove-AzServiceEndpointPolicy.md
  src/Network/Network/help/Remove-AzVirtualHubVnetConnection.md
  src/Network/Network/help/Remove-AzVirtualNetwork.md
  src/Network/Network/help/Set-AzApplicationGatewayHttpListenerCustomError.md
  src/Network/Network/help/Set-AzNetworkInterfaceIpConfig.md
  src/Network/Network/help/Set-AzNetworkWatcherConnectionMonitor.md
  src/Network/Network/help/Set-AzNetworkWatcherFlowLog.md
  src/Network/Network/help/Set-AzPrivateEndpoint.md
  src/Network/Network/help/Set-AzRouteTable.md
  src/Network/Network/help/Set-AzVirtualNetworkGatewayConnection.md
  src/Network/Network/help/Update-AzVirtualNetworkGatewayNatRule.md
Labels: Doc - Reference, needs-review

#18709 format the help markdown files of Az.DedicatedHsm
  src/DedicatedHsm/help/Update-AzDedicatedHsm.md
Labels: Doc - Reference, needs-review

#18694 format the help markdown files of Az.Resources in generation
  src/Resources/Authorization.Autorest/docs/Get-AzRoleAssignmentSchedule.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleAssignmentScheduleInstance.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleAssignmentScheduleRequest.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleEligibilitySchedule.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleEligibilityScheduleInstance.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleEligibilityScheduleRequest.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleEligibleChildResource.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/docs/Get-AzRoleManagementPolicyAssignment.md
  src/Resources/Authorization.Autorest/docs/New-AzRoleAssignmentScheduleRequest.md
  src/Resources/Authorization.Autorest/docs/New-AzRoleEligibilityScheduleRequest.md
  src/Resources/Authorization.Autorest/docs/New-AzRoleManagementPolicyAssignment.md
  src/Resources/Authorization.Autorest/docs/Remove-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/docs/Remove-AzRoleManagementPolicyAssignment.md
  src/Resources/Authorization.Autorest/docs/Stop-AzRoleAssignmentScheduleRequest.md
  src/Resources/Authorization.Autorest/docs/Stop-AzRoleEligibilityScheduleRequest.md
  src/Resources/Authorization.Autorest/docs/Update-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleAssignmentSchedule.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleAssignmentScheduleInstance.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleAssignmentScheduleRequest.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleEligibilitySchedule.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleEligibilityScheduleInstance.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleEligibilityScheduleRequest.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleEligibleChildResource.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/examples/Get-AzRoleManagementPolicyAssignment.md
  src/Resources/Authorization.Autorest/examples/New-AzRoleAssignmentScheduleRequest.md
  src/Resources/Authorization.Autorest/examples/New-AzRoleEligibilityScheduleRequest.md
  src/Resources/Authorization.Autorest/examples/New-AzRoleManagementPolicyAssignment.md
  src/Resources/Authorization.Autorest/examples/Remove-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/examples/Remove-AzRoleManagementPolicyAssignment.md
  src/Resources/Authorization.Autorest/examples/Stop-AzRoleAssignmentScheduleRequest.md
  src/Resources/Authorization.Autorest/examples/Stop-AzRoleEligibilityScheduleRequest.md
  src/Resources/Authorization.Autorest/examples/Update-AzRoleManagementPolicy.md
  src/Resources/MSGraph.Autorest/docs/Get-AzADAppFederatedIdentityCredential.md
  src/Resources/MSGraph.Autorest/docs/New-AzADAppCredential.md
  src/Resources/MSGraph.Autorest/docs/New-AzADUser.md
  src/Resources/MSGraph.Autorest/docs/Update-AzADGroup.md
  src/Resources/MSGraph.Autorest/examples/Get-AzADAppFederatedIdentityCredential.md
  src/Resources/MSGraph.Autorest/examples/New-AzADAppCredential.md
  src/Resources/MSGraph.Autorest/examples/New-AzADUser.md
  src/Resources/MSGraph.Autorest/examples/Update-AzADGroup.md
Labels: Doc - Reference, needs-review

#18799 format the help markdown file of Az.ConnectedMachine in generation
  src/ConnectedMachine/docs/Get-AzConnectedPrivateLinkScope.md
  src/ConnectedMachine/docs/Update-AzConnectedMachineExtension.md
  src/ConnectedMachine/docs/Update-AzConnectedPrivateLinkScopeTag.md
  src/ConnectedMachine/examples/Get-AzConnectedPrivateLinkScope.md
  src/ConnectedMachine/examples/Update-AzConnectedMachineExtension.md
  src/ConnectedMachine/examples/Update-AzConnectedPrivateLinkScopeTag.md
Labels: Doc - Reference, Waiting for CI :shipit:

#18797 format the help markdown file of Az.Compute
  src/Compute/Compute/help/New-AzDiskEncryptionSetConfig.md
  src/Compute/Compute/help/New-AzDiskPurchasePlanConfig.md
  src/Compute/Compute/help/New-AzGalleryImageDefinition.md
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/Set-AzVMBackupExtension.md
  src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
Labels: Doc - Reference, Waiting for CI :shipit:

#18866 [Synapse] Fixed the issue that update spark pool version fail
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/UpdateAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/help/Update-AzSynapseSparkPool.md
Labels: Waiting for CI :shipit:

#18876 Remove the warning messages for MSGraph migration
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/Constants.cs
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/GetAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/RBAC/GetAzureManagedHsmRoleAssignment.cs
  src/KeyVault/KeyVault/Commands/RBAC/NewAzureManagedHsmRoleAssignment.cs
  src/KeyVault/KeyVault/Commands/RBAC/RemoveAzureManagedHsmRoleAssignment.cs
  src/KeyVault/KeyVault/Commands/RemoveAzureKeyVaultAccessPolicy.cs
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs
  src/KeyVault/KeyVault/Helpers/MSGraphMessageHelper.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/DenyAssignments/GetAzureDenyAssignmentCommand.cs
  src/Resources/Resources/Helper/MSGraphMessageHelper.cs
  src/Resources/Resources/RoleAssignments/GetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/SetAzureRoleAssignmentCommand.cs
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Helpers/MSGraphMessageHelper.cs
  src/Sql/Sql/InstanceActiveDirectoryAdministrator/Cmdlet/AzureSqlInstanceActiveDirectoryAdministratorCmdletBase.cs
  src/Sql/Sql/ServerActiveDirectoryAdministrator/Cmdlet/AzureSqlServerActiveDirectoryAdministratorCmdletBase.cs
Labels: Waiting for CI :shipit:

#18857 Fixed SNAT private ranges IP validation bug
  src/Network/Network.Test/ScenarioTests/AzureFirewallPolicyTests.ps1
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallPolicyTests/TestAzureFirewallPolicyPrivateRangeCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallPrivateRangeCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/Models/AzureFirewallPolicy/PSAzureFirewallPolicy.cs
Labels: Waiting for CI :shipit:

#18885 Added -Location parameter to Set- AzVMRunCommand
  src/Compute/Compute.Autorest/examples/Set-AzVMRunCommand.md
Labels: Waiting for CI :shipit:

#18882 Updated parameter name from `-Type` to `-SkuName` for Set-AzStorageAccount cmdlet in help file
  src/Storage/Storage.Management/help/Set-AzStorageAccount.md
Labels: Waiting for CI :shipit:, customer-reported

#18901 Onboarded Device Update for IoT Hub to Private Link Common Cmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#18903 Use "module" instead of "regex" when updating CreateMappings_rules.json
  tools/Gen2Master/MoveFromGeneration2Master.ps1
Labels: Waiting for CI :shipit:

#18917 Update AzPreview.psd1 after each releasae (including OOB and preview release)
  tools/RunVersionController.ps1
Labels: Waiting for CI :shipit:

#18911 Add an example for definition file structure of 'New-AzSynapseManagedPrivateEndpoint'
  src/Synapse/Synapse/help/New-AzSynapseManagedPrivateEndpoint.md
Labels: Waiting for CI :shipit:

#18929 SQL - Declare breaking changes for the AdvancedDataSecurity and AdvancedThreatProtection cmdlets from 9.0.0
  src/Sql/Sql.Test/Sql.Test.csproj
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/DisableAzureSqlManagedInstanceAdvancedDataSecurity.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/DisableAzureSqlServerAdvancedDataSecurity.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/EnableAzureSqlManagedInstanceAdvancedDataSecurity.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/EnableAzureSqlServerAdvancedDataSecurity.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/GetAzureSqlManagedInstanceAdvancedDataSecurityPolicy.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/GetAzureSqlServerAdvancedDataSecurityPolicy.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/SqlManagedInstanceAdvancedDataSecurityCmdletBase.cs
  src/Sql/Sql/AdvancedDataSecurity/Cmdlet/SqlServerAdvancedDataSecurityCmdletBase.cs
  src/Sql/Sql/AdvancedDataSecurity/Model/ManagedInstanceAdvancedDataSecurityPolicyModel.cs
  src/Sql/Sql/AdvancedDataSecurity/Model/ServerAdvancedDataSecurityPolicyModel.cs
  src/Sql/Sql/AdvancedDataSecurity/Services/SqlAdvancedDataSecurityAdapter.cs
  src/Sql/Sql/AdvancedDataSecurity/Templates/DeployInstanceVaTemplate.json
  src/Sql/Sql/AdvancedDataSecurity/Templates/DeployServerVaTemplate.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Sql.csproj
  src/Sql/Sql/ThreatDetection/Cmdlet/GetAzureSqlDatabaseThreatDetection.cs
  src/Sql/Sql/ThreatDetection/Cmdlet/GetAzureSqlServerThreatDetection.cs
  src/Sql/Sql/ThreatDetection/Cmdlet/RemoveSqlDatabaseThreatDetection.cs
  src/Sql/Sql/ThreatDetection/Cmdlet/RemoveSqlServerThreatDetection.cs
  src/Sql/Sql/ThreatDetection/Cmdlet/SetAzureSqlDatabaseThreatDetection.cs
  src/Sql/Sql/ThreatDetection/Cmdlet/SetAzureSqlServerThreatDetection.cs
Labels: Waiting for CI :shipit:

#18935 [Synapse]Added LastCommitId parameter to 'New-AzureSynapseGitRepositoryConfig'
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/NewAzureSynapseGitRepositoryConfig.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/ManagementModels/Workspace/PSWorkspaceRepositoryConfiguration.cs
  src/Synapse/Synapse/help/New-AzSynapseGitRepositoryConfig.md
Labels: Waiting for CI :shipit:

#18921 [Storage] support blobIndexMatch in management policy
  src/Storage/Storage.Management.Test/ScenarioTests/StorageAccountTests.ps1
  src/Storage/Storage.Management.Test/SessionRecords/Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests/TestStorageAccountManagementPolicy.json
  src/Storage/Storage.Management/Az.Storage.psd1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Models/PSDataPolicy.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccountManagementPolicyBlobIndexMatchObject.cs
  src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccountManagementPolicyFilter.cs
  src/Storage/Storage.Management/help/Az.Storage.md
  src/Storage/Storage.Management/help/New-AzStorageAccountManagementPolicyBlobIndexMatchObject.md
  src/Storage/Storage.Management/help/New-AzStorageAccountManagementPolicyFilter.md
  src/Storage/Storage.Management/help/Set-AzStorageAccountManagementPolicy.md
  tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv
Labels: Waiting for CI :shipit:

#18944 Move SQL Server and SQL Instance from AAD Client to MSGraph Client
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceCommunicator.cs
  src/Sql/Sql/Server/Services/AzureSqlServerAdapter.cs
Labels: Waiting for CI :shipit:

#18879 Skip "import az.accounts in parallel" in smoke test in ADO pipeline
  tools/Test/SmokeTest/RmCoreSmokeTests.ps1
Labels: needs-review

#18964 [Resources] Update federated credential cmdlets to use V1.0 API
  src/Resources/MSGraph.Autorest/README.md
  src/Resources/MSGraph.Autorest/custom/Get-AzADAppFederatedIdentityCredential.ps1
  src/Resources/MSGraph.Autorest/custom/New-AzADAppFederatedIdentityCredential.ps1
  src/Resources/MSGraph.Autorest/docs/Az.MSGraph.md
  src/Resources/MSGraph.Autorest/docs/Get-AzADAppCredential.md
  src/Resources/MSGraph.Autorest/docs/Get-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/docs/Get-AzADServicePrincipal.md
  src/Resources/MSGraph.Autorest/docs/Get-AzADSpCredential.md
  src/Resources/MSGraph.Autorest/docs/New-AzADAppCredential.md
  src/Resources/MSGraph.Autorest/docs/New-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/docs/New-AzADServicePrincipal.md
  src/Resources/MSGraph.Autorest/docs/New-AzADSpCredential.md
  src/Resources/MSGraph.Autorest/docs/Remove-AzADAppCredential.md
  src/Resources/MSGraph.Autorest/docs/Remove-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/docs/Remove-AzADApplication.md
  src/Resources/MSGraph.Autorest/docs/Remove-AzADServicePrincipal.md
  src/Resources/MSGraph.Autorest/docs/Remove-AzADSpCredential.md
  src/Resources/MSGraph.Autorest/docs/Update-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/docs/Update-AzADApplication.md
  src/Resources/MSGraph.Autorest/docs/Update-AzADServicePrincipal.md
  src/Resources/MSGraph.Autorest/examples/Get-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/examples/New-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/examples/New-AzADAppFederatedIdentityCredential.md
  src/Resources/MSGraph.Autorest/examples/Remove-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/examples/Remove-AzADAppFederatedIdentityCredential.md
  src/Resources/MSGraph.Autorest/examples/Update-AzADAppFederatedCredential.md
  src/Resources/MSGraph.Autorest/examples/Update-AzADAppFederatedIdentityCredential.md
  src/Resources/MSGraph.Autorest/test/Get-AzADAppFederatedCredential.Tests.ps1
  src/Resources/MSGraph.Autorest/test/New-AzADAppFederatedCredential.Tests.ps1
  src/Resources/MSGraph.Autorest/test/Remove-AzADAppFederatedCredential.Tests.ps1
  src/Resources/MSGraph.Autorest/test/Update-AzADAppFederatedCredential.Tests.ps1
  src/Resources/OpenApiSpecs/v1.0/Applications.yml
  tools/StaticAnalysis/Exceptions/Az.Resources/BreakingChangeIssues.csv
Labels: Do Not Merge :no_entry_sign:

#18948 Added the new switch parameter IdentifyTopFatFlows to Firewall Command
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDIdentifyTopFatFlow.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/Set-AzFirewall.md
Labels: needs-revision

#18972 Update New-AzApplicationGatewayFirewallPolicyManagedRuleSet.md
  src/Network/Network/help/New-AzApplicationGatewayFirewallPolicyManagedRuleSet.md
Labels: Waiting for CI :shipit:, customer-reported

#18983 [Synapse] Set 'ResourceGroupName' parameter as optional for 'Set-AzSynapseSqlAuditSetting'
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/Auditing/SynapseSqlPoolAuditCmdlet.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Auditing/SynapseWorkspaceAuditCmdlet.cs
Labels: Waiting for CI :shipit:

#19015 Updated two new Sql test cases invocation from RunPowerShellTest to TestRunner.RunTestScript
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.cs
Labels: Waiting for CI :shipit:

#19002 NetworkWatcher : Adding VMSS as a source in ConnectionMonitor.
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestConnectionMonitorWithVMSSAsSource.json
  src/Network/Network.Test/TestData/DeploymentParametersVMSS.json
  src/Network/Network.Test/TestData/DeploymentVMSS.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkWatcher/ConnectionMonitor/ConnectionMonitorBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndPointObjectCommand.cs
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointObject.md
Labels: Waiting for CI :shipit:

#18992 Changed IdentifyTopFatFlows to EnableFatFlowLogging on the backend model
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDIdentifyTopFatFlow.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
Labels: Waiting for CI :shipit:

#18977 [AppService]: fix #18028- Publish-AzWebapp doesn't handle relative paths properly
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestPublishWebAppFromZip.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
Labels: Waiting for CI :shipit:

#19030 [Az.Accounts] add examples for invoke-azreset, implement supportsshouldprocess for …
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
  src/Accounts/Accounts/help/Invoke-AzRestMethod.md
Labels: Waiting for CI :shipit:

#19001 Adding new Commandlets for Network Watcher "New-AzNetworkWatcherPacketCaptureV2" and "New-AzPacketCaptureScopeConfig"
  src/Accounts/Accounts/AzureRmAlias/Mappings.json
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestPacketCaptureVMSS.json
  src/Network/Network/ApplicationGateway/SslPolicy/AzureApplicationGatewaySslPolicyBase.cs
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSGetPacketCaptureResult.cs
  src/Network/Network/Models/PSPacketCapture.cs
  src/Network/Network/Models/PSPacketCaptureMachineScope.cs
  src/Network/Network/Models/PSPacketCaptureResult.cs
  src/Network/Network/Models/PSPacketCaptureTargetType.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkWatcher/PacketCapture/GetAzureNetworkWatcherPacketCaptureCommand.cs
  src/Network/Network/NetworkWatcher/PacketCapture/NewAzureNetworkWatcherPacketCaptureCommandV2.cs
  src/Network/Network/NetworkWatcher/PacketCapture/NewPacketCaptureScopeCommand.cs
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/New-AzNetworkWatcherPacketCaptureV2.md
  src/Network/Network/help/New-AzPacketCaptureFilterConfig.md
  src/Network/Network/help/New-AzPacketCaptureScopeConfig.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-review

#18986 [Grafana] Create Az.Dashboard module and use apiverison = 2022-08-01
  src/Dashboard/.gitattributes
  src/Dashboard/.gitignore
  src/Dashboard/Az.Dashboard.psd1
  src/Dashboard/README.md
  src/Dashboard/custom/New-AzGrafana.ps1
  src/Dashboard/custom/README.md
  src/Dashboard/docs/Az.Dashboard.md
  src/Dashboard/docs/Get-AzGrafana.md
  src/Dashboard/docs/New-AzGrafana.md
  src/Dashboard/docs/README.md
  src/Dashboard/docs/Remove-AzGrafana.md
  src/Dashboard/docs/Update-AzGrafana.md
  src/Dashboard/examples/Get-AzGrafana.md
  src/Dashboard/examples/New-AzGrafana.md
  src/Dashboard/examples/Remove-AzGrafana.md
  src/Dashboard/examples/Update-AzGrafana.md
  src/Dashboard/how-to.md
  src/Dashboard/license.txt
  src/Dashboard/resources/README.md
  src/Dashboard/test/AzGrafana.Recording.json
  src/Dashboard/test/AzGrafana.Tests.ps1
  src/Dashboard/test/Get-AzGrafana.Tests.ps1
  src/Dashboard/test/New-AzGrafana.Tests.ps1
  src/Dashboard/test/README.md
  src/Dashboard/test/Remove-AzGrafana.Tests.ps1
  src/Dashboard/test/Update-AzGrafana.Tests.ps1
  src/Dashboard/test/env.json
  src/Dashboard/test/loadEnv.ps1
  src/Dashboard/test/utils.ps1
  src/Dashboard/utils/Unprotect-SecureString.ps1
Labels: Waiting for CI :shipit:

#19027 [Az.Sql] Add support for cross-subscription Azure SQL Database Failover Group creation
  src/Sql/Sql.Test/ScenarioTests/FailoverGroupTests.cs
  src/Sql/Sql.Test/ScenarioTests/FailoverGroupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.FailoverGroupTests/TestCreateFailoverGroup_CrossSubscription.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Failover Group/Cmdlet/NewAzureSqlFailoverGroup.cs
  src/Sql/Sql/Failover Group/Model/AzureSqlFailoverGroupModel.cs
  src/Sql/Sql/Failover Group/Services/AzureSqlFailoverGroupAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabaseFailoverGroup.md
Labels: Waiting for CI :shipit:

#19064 [Recommendation] Add a link to ask for feedback
  src/Accounts/Accounts/Utilities/CommandNotFoundHelper.cs
Labels: Waiting for CI :shipit:

#19084 [Az.App] Update examples
  src/App/docs/Update-AzContainerApp.md
  src/App/examples/Update-AzContainerApp.md
Labels: Waiting for CI :shipit:

#19082 Fixe minor issues in doc and example
  src/KeyVault/KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs
  src/KeyVault/KeyVault/help/Set-AzKeyVaultAccessPolicy.md
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:
