Repository Azure/azure-powershell, pull requests merged in 2022-09, with the labels that each got.

#19121 [Compute] Communitygallery changes
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/Compute/Compute/Generated/Gallery/GalleryCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/Gallery/GalleryGetMethod.cs
  src/Compute/Compute/Generated/GalleryImage/GalleryImageGetMethod.cs
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionGetMethod.cs
  src/Compute/Compute/Generated/Models/PSCommunityGallery.cs
  src/Compute/Compute/Generated/Models/PSCommunityGalleryImage.cs
  src/Compute/Compute/Generated/Models/PSCommunityGalleryImageVersion.cs
  src/Compute/Compute/help/Get-AzGallery.md
  src/Compute/Compute/help/Get-AzGalleryApplication.md
  src/Compute/Compute/help/Get-AzGalleryApplicationVersion.md
  src/Compute/Compute/help/Get-AzGalleryImageDefinition.md
  src/Compute/Compute/help/Get-AzGalleryImageVersion.md
  src/Compute/Compute/help/New-AzGallery.md
  src/Compute/Compute/help/Update-AzGallery.md
Labels: needs-revision

#19321 Added Trusted Launch Configuration Breaking Change warning for NewAzVm, New-AzDisk and New-AzVmss cmdlets
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/DiskCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: needs-revision

#19285 upgrade for new survey machenism
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Feedback/OpenAzSurveyLinkCmdlet.cs
  src/Accounts/Accounts/help/Clear-AzConfig.md
  src/Accounts/Accounts/help/Get-AzConfig.md
  src/Accounts/Accounts/help/Update-AzConfig.md
  src/Accounts/Authentication/Authentication.csproj
  src/Accounts/Authentication/AzureSessionInitializer.cs
  src/Accounts/Authentication/Config/ConfigInitializer.cs
  src/Accounts/Authentication/Config/Definitions/EnableInterceptSurveyConfig.cs
  src/Accounts/Authentication/Models/AzCLIProfileInfo.cs
  src/shared/ConfigKeys.cs
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#19373 Mssql app rule bug fix
  src/Network/Network.Test/ScenarioTests/AzureFirewallPolicyTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallPolicyTests/TestAzureFirewallPolicyCRUD.json
  src/Network/Network/AzureFirewallPolicy/ApplicationRuleCondition/NewAzureFirewallPolicyApplicationRuleCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewallPolicy/PSAzureFirewallPolicyApplicationRuleCollectionProtocol.cs
Labels: needs-review

#19029 Update breaking-changes-messages-help.md
  documentation/breaking-changes/breaking-changes-attribute-help.md
  documentation/breaking-changes/breaking-changes-messages-help.md
Labels: Waiting for CI :shipit:

#19391 {AzureFirewall} fixes Azure/azure-powershell#19371
  src/Network/Network/help/Get-AzFirewallPolicyRuleCollectionGroup.md
Labels: Doc - Conceptual, Waiting for CI :shipit:

#19411 Add DynatraceObservability to the module list
  documentation/azure-powershell-modules.md
Labels: Waiting for CI :shipit:

#19139 Upgrade Azure.Core from 1.24 to 1.25
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#19376 Make GraphAccessToken parameter obselete since it is no more required
  src/StackHCI/ChangeLog.md
  src/StackHCI/custom/stackhci.ps1
Labels: Waiting for CI :shipit:

#19428 Enable udp log optimization
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDEnableUDPLogOptimization.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/help/New-AzFirewall.md
Labels: Waiting for CI :shipit:

#19451 Fixed New-AzApplicationGatewayHttpListener param
  src/Network/Network/help/New-AzApplicationGatewayHttpListener.md
Labels: customer-reported

#19462 [Az.RecoveryServices.Backup] Removed AFEC feature check for Archive smart tiering
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#19461 {AzureRecoveryServices} fixes Azure/azure-powershell#19457
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProperty.md
Labels: Doc - Conceptual, Waiting for CI :shipit:

#19465 Fix API versions for AZ resource calls and improve logging
  src/StackHCI/ChangeLog.md
  src/StackHCI/custom/stackhci.ps1
Labels: needs-revision

#19455 Update cmdlet Update-AzCustomIpPrefix to support NoInternetAdvertise parameter
  src/Network/Network/BYOIP/CustomIpPrefix/UpdateAzureCustomIpPrefixCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/BYOIP/PSCustomIpPrefix.cs
Labels: Waiting for CI :shipit:

#19431 Upgrade Azure.Core to 1.25.0
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  src/lib/NetCorePreloadAssemblies/Azure.Core.dll
  src/lib/NetFxPreloadAssemblies/Azure.Core.dll
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#19467 {AzureCXP} Fix StorageAccountUrl description
  src/SqlVirtualMachine/SqlVirtualMachine/help/New-AzSqlVMGroup.md
Labels: Waiting for CI :shipit:

#19234 Renamed 'IdentifyTopFatFlow' parameter to `EnableFatFlowLogging` on AzureFirewall
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDEnableFatFlowLogging.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallCRUDIdentifyTopFatFlow.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/Set-AzFirewall.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-revision, Breaking Change Release

#19498 Add Asn param to Cortex Virtual hub and Vpn Gateway
  src/Network/Network.Test/ScenarioTests/CortexTests.cs
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestVirtualHubAndVpnGatewayWithCustomAsn.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Cortex/VirtualHub/NewAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VirtualHub/UpdateAzureRmVirtualHubCommand.cs
  src/Network/Network/Cortex/VpnGateway/NewAzureRmVpnGatewayCommand.cs
  src/Network/Network/Cortex/VpnGateway/UpdateAzureRmVpnGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualHub.md
  src/Network/Network/help/New-AzVpnGateway.md
  src/Network/Network/help/Update-AzVirtualHub.md
  src/Network/Network/help/Update-AzVpnGateway.md
Labels: Waiting for CI :shipit:

#19508 [Synapse] Added support to enable public network access for `Update-AzSynapseWorkspace` and 'New-AzSynapseWorkspace'
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/NewAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Commands/ManagementCommands/Workspace/UpdateAzureSynapseWorkspace.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/Models/SynapseConstants.cs
  src/Synapse/Synapse/help/New-AzSynapseWorkspace.md
  src/Synapse/Synapse/help/Update-AzSynapseWorkspace.md
Labels: Waiting for CI :shipit:

#19487 Fix warning message in load balancer command
  src/Network/Network/ChangeLog.md
  src/Network/Network/LoadBalancer/NewAzureRMLoadBalancerCommand.cs
Labels: needs-revision

#19521 Update New-AzServiceBusAuthorizationRuleSASToken.md
  src/ServiceBus/ServiceBus/help/New-AzServiceBusAuthorizationRuleSASToken.md
Labels: Waiting for CI :shipit:, customer-reported

#19534 Exposed `PausedDate` and `ResumedDate` for cmdlet `Get-AzSqlDatabase`
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
Labels: Waiting for CI :shipit:

#19542 [Connect-AzConnectedMachine] Fixes error with return value processing
  src/ConnectedMachine/Changelog.md
  src/ConnectedMachine/custom/Connect-AzConnectedMachine.ps1
Labels: customer-reported

#19566 [Connect-AzConnectedMachine] Fixes error with return value processing
  src/ConnectedMachine/custom/Connect-AzConnectedMachine.ps1
Labels: Waiting for CI :shipit:

#19547 Update Azure.Identity
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Authentication.csproj
  src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
  src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs
  src/Accounts/Authenticators/Authenticators.csproj
  src/Accounts/Authenticators/ClientAssertionAuthenticator.cs
  src/Accounts/Authenticators/Identity/AsyncLockWithValue.cs
  src/Accounts/Authenticators/Identity/ClientAssertionCredential.cs
  src/Accounts/Authenticators/Identity/ClientAssertionCredentialOptions.cs
  src/Accounts/Authenticators/Identity/Constants.cs
  src/Accounts/Authenticators/Identity/CredentialPipeline.cs
  src/Accounts/Authenticators/Identity/HttpPipelineClientFactory.cs
  src/Accounts/Authenticators/Identity/HttpPipelineMessageHandler.cs
  src/Accounts/Authenticators/Identity/ITokenCacheOptions.cs
  src/Accounts/Authenticators/Identity/MsalCacheHelperWrapper.cs
  src/Accounts/Authenticators/Identity/MsalClientBase.cs
  src/Accounts/Authenticators/Identity/MsalConfidentialClient.cs
  src/Accounts/Authenticators/Identity/TaskExtensions.cs
  src/Accounts/Authenticators/Identity/TokenCache.cs
  src/Accounts/Authenticators/Identity/TokenCachePersistenceOptions.cs
  src/Accounts/Authenticators/Identity/TokenCacheUpdatedArgs.cs
  src/Accounts/Authenticators/Identity/UnsafeTokenCacheOptions.cs
  src/Accounts/Authenticators/Identity/Validations.cs
  src/lib/NetCorePreloadAssemblies/Azure.Identity.dll
  src/lib/NetFxPreloadAssemblies/Azure.Identity.dll
Labels: needs-review

#19322 Fixed a bug that does not return HubIPAddresses' PrivateIPAddress during a Get-AzFirewall command
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallVirtualHubMultiPublicIPCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallVirtualHubPrivateIPAddress.json
  src/Network/Network/AzureFirewall/GetAzureFirewallCommand.cs
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/AzureFirewall/SetAzureFirewallCommand.cs
  src/Network/Network/AzureFirewall/VirtualHub/NewAzureFirewallHubIpAddress.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallHubIpAddresses.cs
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-revision, Breaking Change Release

#19590 [Databricks]Modify EnableNoPublicIp parameter description.
  src/Databricks/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/docs/New-AzDatabricksWorkspace.md
Labels: Waiting for CI :shipit:

#19515 Support to enable client certificate revocation check using PS
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayCRUDWithMutualAuthentication.json
  src/Network/Network/ApplicationGateway/ClientAuthConfiguration/AzureApplicationGatewayClientAuthConfigurationBase.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSApplicationGatewayClientAuthConfiguration.cs
  src/Network/Network/help/New-AzApplicationGatewayClientAuthConfiguration.md
  src/Network/Network/help/Set-AzApplicationGatewayClientAuthConfiguration.md
Labels: needs-revision

#19580 Generation
  src/DataMigration/DataMigration.Autorest/.gitignore
  src/DataMigration/DataMigration.Autorest/Az.DataMigration.psd1
  src/DataMigration/DataMigration.Autorest/custom/Cmdlets/New-AzDataMigrationLoginsMigration.ps1
  src/DataMigration/DataMigration.Autorest/custom/Helpers/LoginMigrations.ps1
  src/DataMigration/DataMigration.Autorest/custom/readme.md
  src/DataMigration/DataMigration.Autorest/docs/Az.DataMigration.md
  src/DataMigration/DataMigration.Autorest/docs/Get-AzDataMigrationPerformanceDataCollection.md
  src/DataMigration/DataMigration.Autorest/docs/Get-AzDataMigrationSkuRecommendation.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationLoginsMigration.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationSqlService.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationToSqlDb.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationToSqlManagedInstance.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationToSqlVM.md
  src/DataMigration/DataMigration.Autorest/docs/readme.md
  src/DataMigration/DataMigration.Autorest/examples/Get-AzDataMigrationPerformanceDataCollection.md
  src/DataMigration/DataMigration.Autorest/examples/New-AzDataMigrationLoginsMigration.md
  src/DataMigration/DataMigration.Autorest/how-to.md
  src/DataMigration/DataMigration.Autorest/test/New-AzDataMigrationLoginsMigration.Tests.ps1
  src/DataMigration/DataMigration.Autorest/test/loadEnv.ps1
Labels: needs-revision

#19604 Onboard Project AzureML Registries to Private Link Common Cmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#19532 Add new parameter ASN, Geo, ExpressrouteAdvertise to New-AzCustomIpPrefix command
  src/Network/Network/BYOIP/CustomIpPrefix/NewAzureCustomIpPrefixCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/BYOIP/PSCustomIpPrefix.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/help/New-AzCustomIpPrefix.md
  src/Network/Network/help/Update-AzCustomIpPrefix.md
Labels: needs-review

#19562 DDoS Per-IP SKU - Phase 1 Changes
  src/Network/Network.Test/NrpTeamAlias.cs
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpAddressTests/TestPublicIpDdosProtection.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSDdosProtectionPlan.cs
  src/Network/Network/Models/PSDdosSettings.cs
  src/Network/Network/Models/PSPublicIpAddress.cs
  src/Network/Network/Network.csproj
  src/Network/Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
  src/Network/Network/help/New-AzPublicIpAddress.md
Labels: needs-review

#19554 Network Manager Contributions to May 2022 Az.Network Release
  src/Network/Network.Test/ScenarioTests/NetworkManagerTests.cs
  src/Network/Network.Test/ScenarioTests/NetworkManagerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerManagementGroupConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerResourceMinimumParameterCreate.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerScopeConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerSecurityAdminRuleCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerSubcriptionConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerConnectivityConfigurationCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerGroupCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerStaticMemberCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkManager/DeployAzNetworkManagerCommit.cs
  src/Network/Network/NetworkManager/NetworkManagerConnectivityConfiguration/NewAzNetworkManagerConnectivityConfigurationCommand.cs
  src/Network/Network/NetworkManager/NetworkManagerConnectivityConfiguration/NewAzNetworkManagerConnectivityGroupItemCommand.cs
  src/Network/Network/NetworkManager/NetworkManagerSecurityAdminConfiguration/NetworkManagerSecurityAdminRuleCollection/NetworkManagerSecurityAdminRule/NewAzNetworkManagerSecurityAdminRuleCommand.cs
  src/Network/Network/NetworkManager/NetworkManagerSecurityAdminConfiguration/NewAzNetworkManagerSecurityAdminConfigurationCommand.cs
  src/Network/Network/NetworkManager/NewAzNetworkManagerAddressPrefixItemCommand.cs
  src/Network/Network/NetworkManager/NewAzNetworkManagerCommand.cs
  src/Network/Network/help/Deploy-AzNetworkManagerCommit.md
  src/Network/Network/help/New-AzNetworkManager.md
  src/Network/Network/help/New-AzNetworkManagerAddressPrefixItem.md
  src/Network/Network/help/New-AzNetworkManagerConnectivityConfiguration.md
  src/Network/Network/help/New-AzNetworkManagerConnectivityGroupItem.md
  src/Network/Network/help/New-AzNetworkManagerSecurityAdminConfiguration.md
  src/Network/Network/help/New-AzNetworkManagerSecurityAdminRule.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-revision

#19507 Support for onlink routing
  src/Network/Network.Test/ScenarioTests/CortexTests.cs
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestRoutingIntentCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestStaticRoutesConfig.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Cortex/RoutingIntent/NewAzureRmRoutingIntentCommand.cs
  src/Network/Network/Cortex/VHubRouteTable/NewAzureRmRoutingConfigurationCommand.cs
  src/Network/Network/Models/Cortex/PSRoutingConfiguration.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/New-AzRoutingConfiguration.md
Labels: needs-revision, Waiting for CI :shipit:

#19626 NetworkWatcher : Adding AzureArcVM as a endpoint in ConnectionMonitor.
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkWatcher/ConnectionMonitor/ConnectionMonitorBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/ConnectionMonitor/NewAzureNetworkWatcherConnectionMonitorEndPointObjectCommand.cs
  src/Network/Network/help/New-AzNetworkWatcherConnectionMonitorEndpointObject.md
Labels: Waiting for CI :shipit:

#19577 Add new IsParent parameter to New-AzCustomIpPrefix cmdlet
  src/Network/Network/BYOIP/CustomIpPrefix/NewAzureCustomIpPrefixCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/BYOIP/PSCustomIpPrefix.cs
  src/Network/Network/help/New-AzCustomIpPrefix.md
Labels: needs-revision

#19636 [API Management] breaking change -make Sku property from Enum to String
  src/ApiManagement/ApiManagement/ApiManagementClient.cs
  src/ApiManagement/ApiManagement/ChangeLog.md
  src/ApiManagement/ApiManagement/Commands/AddAzureApiManagementRegion.cs
  src/ApiManagement/ApiManagement/Commands/NewAzureApiManagement.cs
  src/ApiManagement/ApiManagement/Commands/NewAzureApiManagementRegion.cs
  src/ApiManagement/ApiManagement/Commands/UpdateAzureApiManagementRegion.cs
  src/ApiManagement/ApiManagement/Helpers/Mappers.cs
  src/ApiManagement/ApiManagement/Models/PsApiManagement.cs
  src/ApiManagement/ApiManagement/Models/PsApiManagementRegion.cs
  src/ApiManagement/ApiManagement/help/New-AzApiManagement.md
  src/ApiManagement/ApiManagement/help/Update-AzApiManagementRegion.md
  tools/StaticAnalysis/Exceptions/Az.ApiManagement/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:, Breaking Change Release

#19632 Update Az.VMware.md
  src/VMware/help/Az.VMware.md
Labels: Waiting for CI :shipit:

#19609 Update common libs to 1.3.62
  README.md
  documentation/internal/authentication.md
  documentation/testing-docs/test-matrix-for-az-accounts.md
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts.Test/ContextCmdletTests.cs
  src/Accounts/Accounts.Test/EnvironmentCmdletTests.cs
  src/Accounts/Accounts.Test/ModuleAdapterTests.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Get-AzEnvironment.md
  src/Accounts/Authentication.Test/ClientFactoryHandlerTests.cs
  src/Accounts/Authentication.Test/PSSerializationTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.csproj
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#19657 [VMware] update readmd file description
  src/VMware/docs/Az.VMware.md
Labels: Waiting for CI :shipit:

#19660 Support resource type id of App Configuration
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
  src/Accounts/Accounts/Utilities/SupportedResourceNames.cs
  src/Accounts/Accounts/help/Get-AzAccessToken.md
Labels: needs-review

#19377 [Az.RecoveryServices.Backup] Added sub tasks duration for IaasVM job details command
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Validations/PolicyValidations.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmJob.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/Enums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ProtectionCheckTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/PolicyTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/PolicyTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/Common.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/PolicyTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/PolicyTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/GetAzureVmWorkloadContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVMGetContainers.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMCrossRegionRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetItems.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureFSGetJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMSmartTieringPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadSmartTieringPolicy.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Backup-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupProtectableItem.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryLogChain.md
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupRecoveryPoint.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: needs-review

#19674 {AzureAutomation} fixes Azure/azure-powershell#19631
  src/Automation/Automation/help/Register-AzAutomationScheduledRunbook.md
Labels: Doc - Conceptual

#19526 Resolved application gateway example issues.
  src/Network/Network/help/Add-AzApplicationGatewayBackendSetting.md
  src/Network/Network/help/Add-AzApplicationGatewayListener.md
  src/Network/Network/help/Add-AzApplicationGatewayRoutingRule.md
  src/Network/Network/help/Get-AzApplicationGatewayBackendSetting.md
  src/Network/Network/help/Get-AzApplicationGatewayListener.md
  src/Network/Network/help/Get-AzApplicationGatewayRoutingRule.md
  src/Network/Network/help/New-AzApplicationGatewayBackendSetting.md
  src/Network/Network/help/New-AzApplicationGatewayListener.md
  src/Network/Network/help/New-AzApplicationGatewayRoutingRule.md
  src/Network/Network/help/Remove-AzApplicationGatewayBackendSetting.md
  src/Network/Network/help/Remove-AzApplicationGatewayListener.md
  src/Network/Network/help/Remove-AzApplicationGatewayRoutingRule.md
  src/Network/Network/help/Set-AzApplicationGatewayBackendSetting.md
  src/Network/Network/help/Set-AzApplicationGatewayListener.md
  src/Network/Network/help/Set-AzApplicationGatewayRoutingRule.md
Labels: needs-revision, Waiting for CI :shipit:

#19662 Add StorageContainerIdentity to Start-AzSqlInstanceDatabaseLogReplay
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/help/Start-AzSqlInstanceDatabaseLogReplay.md
Labels: Waiting for CI :shipit:, needs-review
