Repository Azure/azure-powershell, pull requests merged in 2023-03, with the labels that each got.

#21067 Update common library versions
  src/Accounts/Accounts/ChangeLog.md
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#21037 Prepare for a new release for Az.Tools.Predictor
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ChangeLog.md
  tools/Az.Tools.Predictor/Directory.Build.props
Labels: Az.Tools.Predictor

#21082 [Az.Ssh] Bug Fix
  src/Ssh/Ssh/Common/SshBaseCmdlet.cs
Labels: Waiting for CI :shipit:

#21000 Bug Fix in New-AzManagementGroup cmdlet
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestCheckNameAvailabilityFalse.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestCheckNameAvailabilityTrue.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestCheckNameWithInvalidCharacters.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetEntities.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroup.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroupSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroupWithExpand.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetManagementGroupWithExpandAndRecurse.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetTenantBackfillStatus.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestGetsubscriptionsUnderManagementGroup.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewAuthorizationHierarcySetting.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewDefaultMGHierarcySetting.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewHierarchySettings.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroup.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroupWithDisplayName.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroupWithDisplayNameAndParentId.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewManagementGroupWithParentId.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestNewRemoveManagementGroupSubscription.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestRemoveHierarcySetting.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestRemoveManagementGroup.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestStartTenantBackfill.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateBothHierarchySettings.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateHierarchySettingsAuth.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateHierarchySettingsDefaultMG.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateManagementGroupWithDisplayName.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateManagementGroupWithDisplayNameAndParentId.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ManagementGroupsTests/TestUpdateManagementGroupWithParentId.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/ManagementGroups/NewAzureRmManagementGroup.cs
Labels: Waiting for CI :shipit:

#21058 Changes to add support for state in WAF Custom Rule
  src/Batch/Batch.Test/Batch.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/ContainerRegistry/ContainerRegistry.Test/ContainerRegistry.Test.csproj
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HPCCache/HPCCache.Test/HPCCache.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayFirewallPolicyWithCustomRules.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/FirewallPolicy/FirewallCustomRule/AzureApplicationGatewayFirewallCustomRuleBase.cs
  src/Network/Network/Models/PSApplicationGatewayFirewallCustomRule.cs
  src/Network/Network/Network.csproj
  src/Network/Network/help/New-AzApplicationGatewayFirewallCustomRule.md
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SignalR/SignalR.Test/SignalR.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: Waiting for CI :shipit:

#21099 Not to append _INTERNAL in the event name
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/AzPredictorTelemetryClient.cs
Labels: Waiting for CI :shipit:

#21104 Fix the issue for daily build
  build.proj
  tools/ExecuteCIStep.ps1
Labels: needs-review

#21106 {AzureStorageSync} fixes Azure/azure-powershell#21100 Fix the example for Get-AzStorageSyncGroup cmdlet
  src/StorageSync/StorageSync/help/Get-AzStorageSyncGroup.md
Labels: needs-review

#21098 CustomBgpIpConfigurations in gateway connections
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestBgpSettingsUpdateVpnGateway.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests/TestVirtualNetworkGatewayConnectionWithBgpCRUD.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Cortex/VpnConnection/NewAzVpnSiteLinkConnectionCommand.cs
  src/Network/Network/Models/Cortex/PSVpnSiteLinkConnection.cs
  src/Network/Network/Models/PSGatewayCustomBgpIpConfiguration.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayConnection.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/VirtualNetworkGatewayConnection/GetAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/NewAzGatewayCustomBgpIpConfigurationObject.cs
  src/Network/Network/VirtualNetworkGatewayConnection/NewAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/UpdateAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/VirtualNetworkGatewayConnectionBaseCmdlet.cs
  src/Network/Network/help/New-AzGatewayCustomBgpIpConfigurationObject.md
  src/Network/Network/help/New-AzVirtualNetworkGatewayConnection.md
  src/Network/Network/help/New-AzVpnSiteLinkConnection.md
  src/Network/Network/help/Set-AzVirtualNetworkGatewayConnection.md
Labels: needs-review

#21114 Update OperationalInsightsTestRunner.cs
  src/OperationalInsights/OperationalInsights.Test/ScenarioTests/OperationalInsightsTestRunner.cs
  src/OperationalInsights/OperationalInsights.sln
Labels: needs-review

#21133 [Az.Resources] Decouple Automapper
  src/Resources/ResourceManager/ResourceManager.csproj
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/DeploymentScriptsAutoMapperProfile.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PSScriptStatus.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsAzureCliScript.cs
  src/Resources/ResourceManager/SdkModels/DeploymentScripts/PsAzurePowerShellScript.cs
  src/Resources/Resources/Az.Resources.psd1
Labels: Waiting for CI :shipit:

#21141 Improve the logic to check whether a cmdlet is supported.
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTelemetryTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorConstants.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ParameterValuePredictor.cs
Labels: Az.Tools.Predictor

#21148 Add missing Assemblyinfo.cs files
  src/Accounts/AssemblyLoading/Properties/AssemblyInfo.cs
  src/Accounts/AuthenticationAssemblyLoadContext/Properties/AssemblyInfo.cs
Labels: Waiting for CI :shipit:

#21157 Upgrade the version CredScan task
  .azure-pipelines/security-tools.yml
Labels: needs-review

#21167 network-2022-09-01
  src/Batch/Batch.Test/Batch.Test.csproj
  src/CognitiveServices/CognitiveServices.Test/CognitiveServices.Test.csproj
  src/Compute/Compute.Test/Compute.Test.csproj
  src/ContainerRegistry/ContainerRegistry.Test/ContainerRegistry.Test.csproj
  src/CosmosDB/CosmosDB.Test/CosmosDB.Test.csproj
  src/DataLakeStore/DataLakeStore.Test/DataLakeStore.Test.csproj
  src/Dns/Dns.Test/Dns.Test.csproj
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HPCCache/HPCCache.Test/HPCCache.Test.csproj
  src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
  src/Monitor/Monitor.Test/Monitor.Test.csproj
  src/NetAppFiles/NetAppFiles.Test/NetAppFiles.Test.csproj
  src/Network/Network.Test/Network.Test.csproj
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/ScenarioTests/CortexTests.ps1
  src/Network/Network.Test/ScenarioTests/NetworkSecurityGroupTests.ps1
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayFirewallPolicyWithCustomRules.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestBgpSettingsUpdateVpnGateway.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.CortexTests/TestCortexCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkSecurityGroupTests/TestNetworkSecurityGroupCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests/TestVirtualNetworkGatewayConnectionWithBgpCRUD.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Cortex/VpnConnection/NewAzVpnSiteLinkConnectionCommand.cs
  src/Network/Network/Cortex/VpnGateway/ResetAzureVpnGatewayCommand.cs
  src/Network/Network/ExpressRoutePort/NewAzureRMExpressRoutePortCommand.cs
  src/Network/Network/FirewallPolicy/FirewallCustomRule/AzureApplicationGatewayFirewallCustomRuleBase.cs
  src/Network/Network/Generated/Models/PSExpressRouteCircuit.cs
  src/Network/Network/Generated/Models/PSExpressRoutePort.cs
  src/Network/Network/Models/Cortex/PSVpnSiteLinkConnection.cs
  src/Network/Network/Models/PSApplicationGatewayFirewallCustomRule.cs
  src/Network/Network/Models/PSGatewayCustomBgpIpConfiguration.cs
  src/Network/Network/Models/PSNetworkSecurityGroup.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayConnection.cs
  src/Network/Network/Network.csproj
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/NetworkSecurityGroup/NewAzureNetworkSecurityGroupCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/GetAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/NewAzGatewayCustomBgpIpConfigurationObject.cs
  src/Network/Network/VirtualNetworkGatewayConnection/NewAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/UpdateAzureVirtualNetworkGatewayConnectionCommand.cs
  src/Network/Network/VirtualNetworkGatewayConnection/VirtualNetworkGatewayConnectionBaseCmdlet.cs
  src/Network/Network/help/Get-AzNetworkSecurityGroup.md
  src/Network/Network/help/New-AzApplicationGatewayFirewallCustomRule.md
  src/Network/Network/help/New-AzExpressRoutePort.md
  src/Network/Network/help/New-AzGatewayCustomBgpIpConfigurationObject.md
  src/Network/Network/help/New-AzNetworkSecurityGroup.md
  src/Network/Network/help/New-AzVirtualNetworkGatewayConnection.md
  src/Network/Network/help/New-AzVpnSiteLinkConnection.md
  src/Network/Network/help/Reset-AzVpnGateway.md
  src/Network/Network/help/Set-AzExpressRoutePort.md
  src/Network/Network/help/Set-AzVirtualNetworkGatewayConnection.md
  src/PrivateDns/PrivateDns.Test/PrivateDns.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/SignalR/SignalR.Test/SignalR.Test.csproj
  src/Sql/Sql.Test/Sql.Test.csproj
  src/SqlVirtualMachine/SqlVirtualMachine.Test/SqlVirtualMachine.Test.csproj
Labels: Waiting for CI :shipit:, Do Not Squash :no_entry_sign:

#21165 Minor Spelling
  src/Network/Network/ChangeLog.md
Labels: customer-reported

#21180 Bug - Invoke-AzCostManagementQuery cmdlet should handle null value in the response rows
  src/CostManagement/Changelog.md
  src/CostManagement/custom/Invoke-AzCostManagementQuery.ps1
Labels: customer-reported

#21193 Update Set-AzNetworkInterfaceIpConfig.md
  src/Network/Network/help/Set-AzApplicationGatewayBackendAddressPool.md
  src/Network/Network/help/Set-AzNetworkInterfaceIpConfig.md
Labels: customer-reported

#21194 Upgrade unsecurity packages
  tools/Tools.Common/Tools.Common.Netcore.csproj
Labels: Waiting for CI :shipit:

#21199 [ArcResourceBridge] Generate ux folder
  src/ArcResourceBridge/UX/Microsoft.ResourceConnector/appliances-upgradeGraphs.json
  src/ArcResourceBridge/UX/Microsoft.ResourceConnector/appliances.json
Labels: Waiting for CI :shipit:

#21204 Az.Cosmos DB Preview - New Restore Parameter
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/RestoreAzCosmosDBAccount.cs
Labels: customer-reported

#21223 [AppService]: fix #21153 Perform an App Service soft restart
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestStartStopRestartWebAppSlot.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppTests/TestStartStopRestartWebApp.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/RestartAzureWebAppSlot.cs
  src/Websites/Websites/Cmdlets/WebApps/RestartAzureWebApp.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
  src/Websites/Websites/help/Restart-AzWebApp.md
  src/Websites/Websites/help/Restart-AzWebAppSlot.md
Labels: needs-review

#21221 [AppService]: fix #5833 Edit-AzureRmWebAppBackupConfiguration always sets Enabled to True
  src/Websites/Websites.Test/ScenarioTests/WebAppBackupRestoreTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestEditAndGetWebAppBackupConfiguration.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests/TestEditAndGetWebAppBackupConfigurationPiping.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/BackupRestore/EditAzureWebAppBackupConfiguration.cs
  src/Websites/Websites/help/Edit-AzWebAppBackupConfiguration.md
Labels: needs-review

#21249 Pricesheet sync API next page link fix (Skip token getting trimmed)
  src/Billing/Billing/ChangeLog.md
  src/Billing/Consumption/Cmdlets/GetAzureRmConsumptionPriceSheet.cs
Labels: needs-review

#21274 Fixed the failed test case New-AzWebPubSubCustomDomain
  src/SignalR/SignalR.Autorest/custom/scripts/New-AzWebPubSubEventHubEndpointObject.ps1
  src/SignalR/SignalR.Autorest/custom/scripts/New-AzWebPubSubEventNameFilterObject.ps1
  src/SignalR/SignalR.Autorest/test/New-AzWebPubSubCustomDomain.Tests.ps1
Labels: needs-review

#20687 [Az.Batch] Adds encryption configuration
  src/Batch/Batch.Test/BatchAccounts/NewBatchAccountCommandTests.cs
  src/Batch/Batch/BatchAccounts/NewBatchAccountCommand.cs
  src/Batch/Batch/ChangeLog.md
  src/Batch/Batch/Models/AccountCreateParameters.cs
  src/Batch/Batch/Models/BatchAccountContext.cs
  src/Batch/Batch/Models/BatchClient.BatchAccounts.cs
  src/Batch/Batch/help/Get-AzBatchAccountKey.md
  src/Batch/Batch/help/New-AzBatchAccount.md
Labels: ready to review
