Repository Azure/azure-powershell, pull requests merged in 2023-02, with the labels that each got.

#20792 Revert the UbuntuLTS image alias to use the version 16.04 instead of 20.04
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Strategies/ComputeRp/Images.json
Labels: needs-review

#20813 [Az.Resources] Fixed query issue when objectId in assignment is empty for Get-DenyAssignment
  src/Resources/Resources/ActiveDirectory/Models/ActiveDirectoryClient.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Models.Authorization/AuthorizationClientExtensions.cs
Labels: needs-review

#20810 Typo "udpate"→"update"
  src/RecoveryServices/RecoveryServices.SiteRecovery/ProtectionContainerMapping/UpdateAzureRmRecoveryServicesAsrProtectionContainerMapping.cs
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesAsrProtectionContainerMapping.md
Labels: Waiting for CI :shipit:, customer-reported

#20819 [MobileNetwork] Update IAny to Hashtable in New-AzMobileNetworkPacketCoreControlPlane…
  src/MobileNetwork/README.md
  src/MobileNetwork/docs/Get-AzMobileNetworkPacketCoreControlPlaneVersion.md
  src/MobileNetwork/docs/New-AzMobileNetworkPacketCoreControlPlane.md
  src/MobileNetwork/examples/Get-AzMobileNetworkPacketCoreControlPlaneVersion.md
Labels: Waiting for CI :shipit:

#20832 [AKS] fix a bug in zip on windows
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/RunAzureRmAksCommand.cs
Labels: needs-revision

#20803 Update Reference to latest swagger for Runbook Cmdlets
  src/Automation/Automation.Sdk/Generated/RunbookDraftOperations.cs
  src/Automation/Automation.Sdk/Generated/RunbookOperations.cs
  src/Automation/Automation.Sdk/Generated/TestJobOperations.cs
  src/Automation/Automation.Sdk/Generated/TestJobStreamsOperations.cs
  src/Automation/Automation.Test/ScenarioTests/RunbookJobTests.cs
  src/Automation/Automation.Test/ScenarioTests/RunbookJobTests.ps1
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.RunbookJobTests/TestImportRunbookPowerShell.json
  src/Automation/Automation.Test/SessionRecords/Commands.Automation.Test.RunbookJobTests/TestRunBookNamePattern.json
  src/Automation/Automation/ChangeLog.md
Labels: Waiting for CI :shipit:, customer-reported

#20851 change storage account link
  src/DataMigration/DataMigration.Autorest/custom/Cmdlets/New-AzDataMigrationLoginsMigration.ps1
Labels: customer-reported, needs-author-feedback

#20840 {AzureDataShare} fixes Azure/azure-powershell#20822 fix the description
  src/DataShare/DataShare/DataSetMapping/GetAzDataShareDataSetMapping.cs
  src/DataShare/DataShare/DataSetMapping/NewAzDataShareDataSetMapping.cs
  src/DataShare/DataShare/DataSetMapping/RemoveAzDataShareDataSetMapping.cs
  src/DataShare/DataShare/help/Get-AzDataShareDataSetMapping.md
  src/DataShare/DataShare/help/New-AzDataShareDataSetMapping.md
  src/DataShare/DataShare/help/Remove-AzDataShareDataSetMapping.md
Labels: Waiting for CI :shipit:

#20842 {AzureSubscription} fixes Azure/azure-powershell#20812 fix the workload parameter
  src/Subscription/Subscription/ChangeLog.md
  src/Subscription/Subscription/Cmdlets/NewAzureRmSubscriptionAlias.cs
  src/Subscription/Subscription/help/New-AzSubscriptionAlias.md
Labels: Waiting for CI :shipit:

#20856 Fix daily smoke test error of ThreadJob installation
  tools/Test/SmokeTest/InstallAzModules.ps1
Labels: Waiting for CI :shipit:

#20855 Bug : classic fw private ranges reverts to default when doing get & set
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
Labels: Waiting for CI :shipit:

#20772 add pipeline yml for syncing fabricbot.json aliases
  .azure-pipelines/sync-aliases.yml
  tools/Github/CreatePR.ps1
  tools/Github/ParseWiki2Json.ps1
Labels: needs-review

#20696 [Policy Insights] Added cmdlets for policy attestations
  src/PolicyInsights/PolicyInsights.Test/EnvSetup/AttestationMetadata.json
  src/PolicyInsights/PolicyInsights.Test/EnvSetup/EnvironmentSetup.ps1
  src/PolicyInsights/PolicyInsights.Test/EnvSetup/ManualPolicyRGDefinition.json
  src/PolicyInsights/PolicyInsights.Test/EnvSetup/ManualPolicyResourceDefinition.json
  src/PolicyInsights/PolicyInsights.Test/EnvSetup/ManualPolicySubDefinition.json
  src/PolicyInsights/PolicyInsights.Test/PolicyInsights.Test.csproj
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/AttestationTests.cs
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/AttestationTests.ps1
  src/PolicyInsights/PolicyInsights.Test/ScenarioTests/Common.ps1
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.AttestationTests/AttestationErrorHandling.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.AttestationTests/AttestationGetCollection.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.AttestationTests/ErrorHandling.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.AttestationTests/ResourceGroupScopeCrud.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.AttestationTests/ResourceScopeCrud.json
  src/PolicyInsights/PolicyInsights.Test/SessionRecords/Microsoft.Azure.Commands.PolicyInsights.Test.ScenarioTests.AttestationTests/SubscriptionScopeCrud.json
  src/PolicyInsights/PolicyInsights/Az.PolicyInsights.psd1
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/PolicyInsights/PolicyInsights/Cmdlets/Attestations/GetAzureRmPolicyAttestation.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Attestations/NewAzureRmPolicyAttestation.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Attestations/RemoveAzureRmAttestation.cs
  src/PolicyInsights/PolicyInsights/Cmdlets/Attestations/SetAzureRmPolicyAttestation.cs
  src/PolicyInsights/PolicyInsights/Common/AttestationCmdletBase.cs
  src/PolicyInsights/PolicyInsights/Common/ParameterHelpMessages.cs
  src/PolicyInsights/PolicyInsights/Models/Attestations/PSAttestation.cs
  src/PolicyInsights/PolicyInsights/Models/Attestations/PSAttestationEvidence.cs
  src/PolicyInsights/PolicyInsights/PolicyInsights.csproj
  src/PolicyInsights/PolicyInsights/Properties/Resources.Designer.cs
  src/PolicyInsights/PolicyInsights/Properties/Resources.resx
  src/PolicyInsights/PolicyInsights/help/Az.PolicyInsights.md
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyAttestation.md
  src/PolicyInsights/PolicyInsights/help/Get-AzPolicyState.md
  src/PolicyInsights/PolicyInsights/help/New-AzPolicyAttestation.md
  src/PolicyInsights/PolicyInsights/help/Remove-AzPolicyAttestation.md
  src/PolicyInsights/PolicyInsights/help/Set-AzPolicyAttestation.md
  src/PolicyInsights/PolicyInsights/help/Start-AzPolicyRemediation.md
Labels: Waiting for CI :shipit:

#20867 Fix ThreadJob installation error of smoke test
  .azure-pipelines/util/smoke-test-steps.yml
  tools/Test/SmokeTest/InstallAzModules.ps1
  tools/Test/SmokeTest/PrepareRequiredPowershell.ps1
Labels: Waiting for CI :shipit:

#20889 update Azure.Core from 1.25.0 to 1.28.0
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/AssemblyLoading/ConditionalAssemblyProvider.cs
  src/lib/netcoreapp2.1/Azure.Core.dll
  src/lib/netfx/Azure.Core.dll
  tools/Common.Netcore.Dependencies.targets
Labels: Waiting for CI :shipit:

#20875 [DataFactory]Updated ADF .Net SDK version to 9.1.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Waiting for CI :shipit:

#20893 [Az.DataMigration] Change Azure Database Migration Service in documentation to Azure Database Migration Service (classic)
  src/DataMigration/DataMigration/Cmdlets/GetAzureDataMigrationService.cs
  src/DataMigration/DataMigration/Cmdlets/GetProjectCmdlet.cs
  src/DataMigration/DataMigration/Cmdlets/NewAzureRmDataMigrationService.cs
  src/DataMigration/DataMigration/Cmdlets/NewDataMigrationTask.cs
  src/DataMigration/DataMigration/Cmdlets/NewProjectCmdlet.cs
  src/DataMigration/DataMigration/Cmdlets/RemoveDataMigrationProject.cs
  src/DataMigration/DataMigration/Cmdlets/RemoveDataMigrationService.cs
  src/DataMigration/DataMigration/Cmdlets/RemoveDataMigrationTask.cs
  src/DataMigration/DataMigration/Cmdlets/StartDataMigrationService.cs
  src/DataMigration/DataMigration/Cmdlets/StopDataMigrationService.cs
  src/DataMigration/DataMigration/Cmdlets/StopDataMigrationTask.cs
  src/DataMigration/DataMigration/help/Az.DataMigration.md
  src/DataMigration/DataMigration/help/Get-AzDataMigrationProject.md
  src/DataMigration/DataMigration/help/Get-AzDataMigrationService.md
  src/DataMigration/DataMigration/help/Get-AzDataMigrationTask.md
  src/DataMigration/DataMigration/help/Invoke-AzDataMigrationCommand.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationFileShare.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationProject.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationService.md
  src/DataMigration/DataMigration/help/New-AzDataMigrationTask.md
  src/DataMigration/DataMigration/help/Remove-AzDataMigrationProject.md
  src/DataMigration/DataMigration/help/Remove-AzDataMigrationService.md
  src/DataMigration/DataMigration/help/Remove-AzDataMigrationTask.md
  src/DataMigration/DataMigration/help/Start-AzDataMigrationService.md
  src/DataMigration/DataMigration/help/Stop-AzDataMigrationService.md
  src/DataMigration/DataMigration/help/Stop-AzDataMigrationTask.md
Labels: Waiting for CI :shipit:

#20902 Remove-AzPolicyAssignment Examples Docs syntax for Confirm parameter incorrect
  src/Resources/Resources/help/Remove-AzPolicyAssignment.md
Labels: Waiting for CI :shipit:, customer-reported

#20905 Added note for scenario when role assignment is created for SPN
  src/Synapse/Synapse/help/New-AzSynapseRoleAssignment.md
Labels: Waiting for CI :shipit:, customer-reported

#20906 Added note for scenario when SPNs role assignment is deleted
  src/Synapse/Synapse/help/Remove-AzSynapseRoleAssignment.md
Labels: Waiting for CI :shipit:, customer-reported

#20907 Added note for scenario when an SPN role assignment is listed
  src/Synapse/Synapse/help/Get-AzSynapseRoleAssignment.md
Labels: Waiting for CI :shipit:, customer-reported

#20908 {AzureFrontDoor} fixes Azure/azure-powershell#20870 Adding Tag parameter to New-AzFrontDoorWafPolicy
  src/FrontDoor/FrontDoor/ChangeLog.md
  src/FrontDoor/FrontDoor/Cmdlets/NewFrontDoorWafPolicy.cs
  src/FrontDoor/FrontDoor/help/New-AzFrontDoorWafPolicy.md
Labels: needs-author-feedback

#20791 adding circuit auth status property
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/Models/PSExpressRouteCircuit.cs
  src/Network/Network/Network.format.ps1xml
Labels: Waiting for CI :shipit:

#20921 Generation of API version 2023-01-31 for Managed Service Identities
  src/ManagedServiceIdentity/Az.ManagedServiceIdentity.psd1
  src/ManagedServiceIdentity/README.md
  src/ManagedServiceIdentity/custom/README.md
  src/ManagedServiceIdentity/docs/Get-AzFederatedIdentityCredentials.md
  src/ManagedServiceIdentity/docs/Get-AzSystemAssignedIdentity.md
  src/ManagedServiceIdentity/docs/Get-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/docs/New-AzFederatedIdentityCredentials.md
  src/ManagedServiceIdentity/docs/New-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/docs/README.md
  src/ManagedServiceIdentity/docs/Remove-AzFederatedIdentityCredentials.md
  src/ManagedServiceIdentity/docs/Update-AzFederatedIdentityCredentials.md
  src/ManagedServiceIdentity/docs/Update-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/how-to.md
  src/ManagedServiceIdentity/test/Get-AzFederatedIdentityCredentials.Recording.json
  src/ManagedServiceIdentity/test/Get-AzSystemAssignedIdentity.Recording.json
  src/ManagedServiceIdentity/test/Get-AzUserAssignedIdentity.Recording.json
  src/ManagedServiceIdentity/test/Get-AzUserAssignedIdentityAssociatedResource.Recording.json
  src/ManagedServiceIdentity/test/New-AzFederatedIdentityCredentials.Recording.json
  src/ManagedServiceIdentity/test/New-AzUserAssignedIdentity.Recording.json
  src/ManagedServiceIdentity/test/Remove-AzFederatedIdentityCredentials.Recording.json
  src/ManagedServiceIdentity/test/Remove-AzUserAssignedIdentity.Recording.json
  src/ManagedServiceIdentity/test/Update-AzFederatedIdentityCredentials.Recording.json
  src/ManagedServiceIdentity/test/Update-AzUserAssignedIdentity.Recording.json
  src/ManagedServiceIdentity/test/deployment-templates/app-service/parameters.json
  src/ManagedServiceIdentity/test/deployment-templates/app-serviceplan/parameters.json
  src/ManagedServiceIdentity/test/env.json
Labels: ready to review

#20941 [AppService]: fix #16816- New-AzWebAppSSLBinding is missing the -WhatIf parameter
  src/Websites/Websites.Test/ScenarioTests/SSLBindingTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TagsNotRemovedByCreateNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestCreateNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestGetNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestGetWebAppCertificate.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestRemoveNewWebAppSSLBinding.json
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.SSLBindingTests/TestWebAppSSLBindingPipeSupport.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/Certificates/NewAzureWebAppSSLBinding.cs
  src/Websites/Websites/help/New-AzWebAppSSLBinding.md
Labels: Waiting for CI :shipit:

#20937 -PerformancePlus for New-AzDiskConfig
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
  src/Compute/Compute/help/New-AzDiskConfig.md
  tools/StaticAnalysis/Exceptions/Az.Compute/SignatureIssues.csv
Labels: needs-revision

#20935 breaking change message for New-AzVmss
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
Labels: Waiting for CI :shipit:

#20946 [Service Connector] rename command name letter case
  src/ServiceLinker/Az.ServiceLinker.psd1
  src/ServiceLinker/custom/Remove-AzServiceLinkerForSpringCloud.ps1
  src/ServiceLinker/docs/Az.ServiceLinker.md
  src/ServiceLinker/docs/Remove-AzServiceLinkerForSpringCloud.md
  src/ServiceLinker/examples/Remove-AzServiceLinkerForSpringCloud.md
Labels: Waiting for CI :shipit:

#20938 [IoT]IoT Hub SDK version update to 4.2.0 and fixed Get-AzIoTHub to work with DigiCert hubs
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/DeviceProvisioningServices.Test.csproj
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsAccessPolicyTests.ps1
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsEnrollmentGroupTests.ps1
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsEnrollmentTests.ps1
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsLinkedHubTests.ps1
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsRegistrationTests.ps1
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsAccessPolicyTests/IotDpsAccessPolicyLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsEnrollmentGroupTests/IotDpsEnrollmentGroupLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsEnrollmentTests/IotDpsEnrollmentLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsLinkedHubTests/IotDpsLinkedHubLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsRegistrationTests/IotDpsRegistrationLifeCycle.json
  src/DeviceProvisioningServices/DeviceProvisioningServices.Test/SessionRecords/Commands.DeviceProvisioningServices.Test.IotDpsTests/IotDpsLifeCycle.json
  src/IotHub/IotHub.Test/IotHub.Test.csproj
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPConfigurationTests/TestAzureIotHubConfigurationLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPDeviceTests/TestAzureIotHubDeviceLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPModuleTests/TestAzureIotHubModuleLifecycle.json
  src/IotHub/IotHub.Test/SessionRecords/Microsoft.Azure.Commands.IotHub.Test.ScenarioTests.IotHubDPTracingTests/TestAzureIotHubTracing.json
  src/IotHub/IotHub/ChangeLog.md
  src/IotHub/IotHub/IotHub.csproj
  src/IotHub/IotHub/IotHub/AddAzureRmIotHubCertificate.cs
  src/IotHub/IotHub/IotHub/AddAzureRmIotHubEventHubConsumerGroup.cs
  src/IotHub/IotHub/Models/PSCapabilities.cs
Labels: Waiting for CI :shipit:

#20950 {Network} Fix Reset-AzVirtualNetworkGateway Example
  src/Network/Network/help/Reset-AzVirtualNetworkGateway.md
Labels: Waiting for CI :shipit:

#20944 [Az.ConnectedKubernetes] support proxy environments and fix issues
  src/ConnectedKubernetes/ChangeLog.md
  src/ConnectedKubernetes/custom/New-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/custom/Remove-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/docs/Az.ConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Get-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Get-AzConnectedKubernetesUserCredential.md
  src/ConnectedKubernetes/docs/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Remove-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/Update-AzConnectedKubernetes.md
  src/ConnectedKubernetes/examples/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/test/AzConnectedKubernetes.Tests.ps1
  src/ConnectedKubernetes/utils/RSAHelper.ps1
Labels: Waiting for CI :shipit:

#20948 Register Microsoft.Monitor RP in Network cmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: Waiting for CI :shipit:

#20955 [Az.ConnectedKubernetes] support proxy environments and fix issues (from generation)
  src/ConnectedKubernetes/custom/New-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/custom/README.md
  src/ConnectedKubernetes/custom/RSAHelper.ps1
  src/ConnectedKubernetes/custom/Remove-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/docs/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/docs/README.md
  src/ConnectedKubernetes/examples/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/how-to.md
  src/ConnectedKubernetes/test/AzConnectedKubernetes.Tests.ps1
Labels: Waiting for CI :shipit:

#20460 analyze cmdlets differences
  .ci-config.json
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/CIFilterTask.cs
  tools/ExecuteCIStep.ps1
  tools/PipelineResultTemplate.json
  tools/StaticAnalysis/CmdletDiffAnalyzer/CmdletDiffAnalyzer.cs
  tools/StaticAnalysis/CmdletDiffAnalyzer/CmdletDiffInfomation.cs
  tools/StaticAnalysis/CollectStaticAnalysisPipelineResult.ps1
  tools/StaticAnalysis/Program.cs
Labels: needs-revision

#20966 [ServiceBus] Bug fix for Set-AzServiceBusQueue
  src/ServiceBus/ServiceBus.Autorest/custom/README.md
  src/ServiceBus/ServiceBus.Autorest/custom/Set-AzServiceBusQueue.ps1
  src/ServiceBus/ServiceBus.Autorest/custom/Set-AzServiceBusSubscription.ps1
  src/ServiceBus/ServiceBus.Autorest/custom/Set-AzServiceBusTopic.ps1
  src/ServiceBus/ServiceBus.Autorest/docs/README.md
  src/ServiceBus/ServiceBus.Autorest/how-to.md
  src/ServiceBus/ServiceBus.Autorest/test/Approve-AzServiceBusPrivateEndpointConnection.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Deny-AzServiceBusPrivateEndpointConnection.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusAuthorizationRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusKey.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusNamespaceV2.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusNetworkRuleSet.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusPrivateEndpointConnection.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusPrivateLink.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusQueue.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusSubscription.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Get-AzServiceBusTopic.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusAuthorizationRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusGeoDRConfiguration.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusKey.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusNamespaceV2.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusQueue.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusSubscription.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/New-AzServiceBusTopic.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusAuthorizationRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusNamespaceV2.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusPrivateEndpointConnection.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusQueue.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusSubscription.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Remove-AzServiceBusTopic.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusAuthorizationRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusGeoDRConfigurationBreakPair.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusGeoDRConfigurationFailOver.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusNamespaceV2.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusNetworkRuleSet.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusQueue.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusQueue.Tests.ps1
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusRule.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusSubscription.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusSubscription.Tests.ps1
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusTopic.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Set-AzServiceBusTopic.Tests.ps1
  src/ServiceBus/ServiceBus.Autorest/test/Start-AzServiceBusMigration.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/Test-AzServiceBusName.Recording.json
  src/ServiceBus/ServiceBus.Autorest/test/deployment-template/DisasterRecoveryParameter.json
  src/ServiceBus/ServiceBus.Autorest/test/deployment-template/keyVaultParameter.json
  src/ServiceBus/ServiceBus.Autorest/test/deployment-template/parameter.json
  src/ServiceBus/ServiceBus.Autorest/test/env.json
  src/ServiceBus/ServiceBus.Autorest/test/localEnv.json
Labels: needs-revision

#20965 Update tests and session records for azure virtual network manager resources
  src/Network/Network.Test/ScenarioTests/NetworkManagerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerManagementGroupConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerResourceMinimumParameterCreate.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerScopeConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerSecurityAdminRuleCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerSubcriptionConnectionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerConnectivityConfigurationCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerGroupCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerStaticMemberCRUD.json
Labels: Waiting for CI :shipit:

#20930 [Relay] added breaking change.
  src/Relay/Relay/ChangeLog.md
  src/Relay/Relay/Cmdlets/Namespace/SetAzureRelayNamespace.cs
  src/Relay/Relay/Cmdlets/Operations/GetAzureRelayOperations.cs
Labels: needs-revision

#20978 [Storage] Support Cold tier in create/copy blob
  src/Storage/Storage.Management.Test/Storage.Management.Test.csproj
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Copy-AzStorageBlob.md
  src/Storage/Storage.Management/help/Set-AzStorageBlobContent.md
  src/Storage/Storage.Management/help/Start-AzStorageBlobCopy.md
  src/Storage/Storage/Blob/Cmdlet/CopyAzureStorageBlob.cs
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/Cmdlet/StartAzureStorageBlobCopy.cs
  src/Storage/Storage/Storage.csproj
Labels: Waiting for CI :shipit:

#20984 [Databricks] upgraded API version.
  src/Databricks/README.md
  src/Databricks/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/custom/README.md
  src/Databricks/custom/Update-AzDatabricksVNetPeering.ps1
  src/Databricks/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/docs/Get-AzDatabricksAccessConnector.md
  src/Databricks/docs/Get-AzDatabricksOutboundNetworkDependenciesEndpoint.md
  src/Databricks/docs/Get-AzDatabricksVNetPeering.md
  src/Databricks/docs/Get-AzDatabricksWorkspace.md
  src/Databricks/docs/New-AzDatabricksAccessConnector.md
  src/Databricks/docs/New-AzDatabricksVNetPeering.md
  src/Databricks/docs/New-AzDatabricksWorkspace.md
  src/Databricks/docs/README.md
  src/Databricks/docs/Update-AzDatabricksAccessConnector.md
  src/Databricks/docs/Update-AzDatabricksVNetPeering.md
  src/Databricks/docs/Update-AzDatabricksWorkspace.md
  src/Databricks/how-to.md
  src/Databricks/test/Get-AzDatabricksAccessConnector.Recording.json
  src/Databricks/test/Get-AzDatabricksOutboundNetworkDependenciesEndpoint.Recording.json
  src/Databricks/test/Get-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Get-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/New-AzDatabricksAccessConnector.Recording.json
  src/Databricks/test/New-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/New-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Remove-AzDatabricksAccessConnector.Recording.json
  src/Databricks/test/Remove-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Remove-AzDatabricksWorkspace.Recording.json
  src/Databricks/test/Update-AzDatabricksAccessConnector.Recording.json
  src/Databricks/test/Update-AzDatabricksVNetPeering.Recording.json
  src/Databricks/test/Update-AzDatabricksWorkspace.Recording.json
  tools/StaticAnalysis/Exceptions/Az.Databricks/BreakingChangeIssues.csv
Labels: needs-revision

#20961 [AppService]: fix #13109 - Assigning user assigned managed identity to app service slot
  src/Websites/Websites.Test/ScenarioTests/WebAppSlotTests.ps1
  src/Websites/Websites.Test/SessionRecords/Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppSlotTests/TestCreateNewWebAppSlot.json
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
  src/Websites/Websites/Utilities/WebsitesClient.cs
  src/Websites/Websites/help/New-AzWebAppSlot.md
Labels: Waiting for CI :shipit:

#21004 Added remove subnet association link example
  src/ContainerInstance/docs/Remove-AzContainerInstanceSubnetServiceAssociationLink.md
  src/ContainerInstance/examples/Remove-AzContainerInstanceSubnetServiceAssociationLink.md
Labels: Waiting for CI :shipit:

#20777 [EventHubs]: Deprecate message retention in days
  src/EventHub/EventHub.Autorest/README.md
  src/EventHub/EventHub.Autorest/custom/Set-AzEventHub.ps1
Labels: Waiting for CI :shipit:

#21023 [StorageMover] Fix job run output format
  src/StorageMover/README.md
  src/StorageMover/docs/Get-AzStorageMoverJobRun.md
  src/StorageMover/examples/Get-AzStorageMoverJobRun.md
Labels: Waiting for CI :shipit:

#20996 Add SecondaryType parameter to commands related to Instance Failover Groups
  src/Sql/Sql.Sdk/Generated/IInstanceFailoverGroupsOperations.cs
  src/Sql/Sql.Sdk/Generated/ISqlManagementClient.cs
  src/Sql/Sql.Sdk/Generated/InstanceFailoverGroupsOperations.cs
  src/Sql/Sql.Sdk/Generated/InstanceFailoverGroupsOperationsExtensions.cs
  src/Sql/Sql.Sdk/Generated/Models/InstanceFailoverGroup.cs
  src/Sql/Sql.Sdk/Generated/Models/SecondaryInstanceType.cs
  src/Sql/Sql.Sdk/Generated/SdkInfo_SqlManagementClient.cs
  src/Sql/Sql.Sdk/Generated/SqlManagementClient.cs
  src/Sql/Sql.Sdk/README.md
  src/Sql/Sql.Test/ScenarioTests/InstanceFailoverGroupTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestCreateInstanceFailoverGroup_AutomaticPolicy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestCreateInstanceFailoverGroup_AutomaticPolicyGracePeriodReadOnlyFailover.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestCreateInstanceFailoverGroup_ManualPolicy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestCreateInstanceFailoverGroup_Named.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestCreateInstanceFailoverGroup_Positional.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestSetInstanceFailoverGroup_AutomaticToManual.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestSetInstanceFailoverGroup_AutomaticWithGracePeriodReadOnlyFailover.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestSetInstanceFailoverGroup_ManualToAutomaticNoGracePeriod.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestSetInstanceFailoverGroup_Named.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.InstanceFailoverGroupTests/TestSetInstanceFailoverGroup_Positional.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Instance Failover Group/Cmdlet/NewAzureSqlInstanceFailoverGroup.cs
  src/Sql/Sql/Instance Failover Group/Cmdlet/SetAzureSqlInstanceFailoverGroup.cs
  src/Sql/Sql/Instance Failover Group/Cmdlet/SwitchAzureSqlDatabaseInstanceFailoverGroup.cs
  src/Sql/Sql/Instance Failover Group/Model/AzureSqlInstanceFailoverGroupModel.cs
  src/Sql/Sql/Instance Failover Group/Services/AzureSqlInstanceFailoverGroupAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabaseInstanceFailoverGroup.md
  src/Sql/Sql/help/Set-AzSqlDatabaseInstanceFailoverGroup.md
  src/Sql/Sql/help/Switch-AzSqlDatabaseInstanceFailoverGroup.md
Labels: Waiting for CI :shipit:

#21024 [DataFactory]Updated ADF .Net SDK version to 9.2.0
  src/DataFactory/DataFactoryV2.Test/DataFactoryV2.Test.csproj
  src/DataFactory/DataFactoryV2/Changelog.md
  src/DataFactory/DataFactoryV2/DataFactoryV2.csproj
Labels: Waiting for CI :shipit:

#21027 [Storage] Fix parameter descriptions of Set-AzStorageLocalUser
  src/Storage/Storage.Management/StorageAccount/SetAzureStorageLocalUser.cs
  src/Storage/Storage.Management/help/Set-AzStorageLocalUser.md
Labels: Waiting for CI :shipit:

#20814 Fixed issue in Resources that a fake token was not updated with a real one
  src/DataLakeStore/DataLakeStore.Test/ScenarioTests/DataLakeStoreTestRunner.cs
  src/Resources/Resources.Test/ScenarioTests/ResourcesTestRunner.cs
Labels: needs-review

#21009 Regional recommender
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/AzureSessionInitializer.cs
  src/Accounts/Authentication/Config/ConfigInitializer.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
  src/Accounts/Authentication/Utilities/Recommendation/DefaultRecommendationService.cs
  src/Accounts/Authentication/Utilities/Recommendation/IRecommender.cs
  src/Accounts/Authentication/Utilities/Recommendation/RegionalRecommender.cs
  src/Accounts/Authentication/Utilities/Telemetry/ParameterTelemetryFormatter.cs
  src/shared/ConfigKeys.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#21006 Clarify behavior of AcountEnabled and Password
  src/Resources/Resources/help/Update-AzADUser.md
Labels: Waiting for CI :shipit:, customer-reported

#21039 [Az.Ssh] [Preview] Version 0.1.1
  src/Ssh/Ssh.Test/ScenarioTests/Common.ps1
  src/Ssh/Ssh.Test/ScenarioTests/GetAzSshConfigTests.cs
  src/Ssh/Ssh.Test/ScenarioTests/GetAzSshConfigTests.ps1
  src/Ssh/Ssh.Test/ScenarioTests/SshTestRunner.cs
  src/Ssh/Ssh.Test/SessionRecords/Microsoft.Azure.Commands.Ssh.Test.ScenarioTests.GetAzSshConfigTests/TestGetArcConfig.json
  src/Ssh/Ssh.Test/SessionRecords/Microsoft.Azure.Commands.Ssh.Test.ScenarioTests.GetAzSshConfigTests/TestGetVmConfig.json
  src/Ssh/Ssh.Test/Ssh.Test.csproj
  src/Ssh/Ssh.sln
  src/Ssh/Ssh/AzureClients/HybridConnectivityClient.cs
  src/Ssh/Ssh/ChangeLog.md
  src/Ssh/Ssh/Common/RelayInformationUtils.cs
  src/Ssh/Ssh/Common/ResourceTypeUtils.cs
  src/Ssh/Ssh/Common/SshBaseCmdlet.cs
  src/Ssh/Ssh/Properties/Resources.Designer.cs
  src/Ssh/Ssh/Properties/Resources.resx
  src/Ssh/Ssh/Ssh.csproj
  src/Ssh/Ssh/SshCommands/EnterAzVMCommand.cs
  src/Ssh/Ssh/SshCommands/ExportAzSshConfig.cs
  src/Ssh/Ssh/help/Az.Ssh.md
  src/Ssh/Ssh/help/Enter-AzVM.md
  src/Ssh/Ssh/help/Export-AzSshConfig.md
Labels: Waiting for CI :shipit:

#21041 Make Get-AzPolicyDefinitions fail if -Id is nonexistent
  src/Resources/ResourceManager/Implementation/Policy/GetAzurePolicyDefinition.cs
  src/Resources/Resources.Test/ScenarioTests/PolicyTests.ps1
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#20811 [Compute] Adding MaxSurge to Set-AzVmssRollingUpgrade And Changes to Get-AzVmImage
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssRollingUpgradePolicyCommand.cs
  src/Compute/Compute/Images/GetAzureVMImageCommand.cs
  src/Compute/Compute/help/Set-AzVmssRollingUpgradePolicy.md
Labels: Waiting for CI :shipit:

#21054 {AzureVirtualHubRouteTable} fixes Azure/azure-powershell#21028 updating about the Get-AzVirtualHubRouteTable Deprecation
  src/Network/Network/help/Get-AzVirtualHubRouteTable.md
Labels: Waiting for CI :shipit:

#21038 Mask the whole command in telemetry when it's not supported
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorServiceTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTelemetryTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/CommandLineTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/Mocks/MockAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/CommandLineSuggestion.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/IAzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/GetSuggestionTelemetryData.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/HistoryTelemetryData.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Utilities/CommandLineUtilities.cs
Labels: Az.Tools.Predictor

#21035 Append _INTERNAL to the event name when it's internal user
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/AzPredictorTelemetryClient.cs
Labels: Az.Tools.Predictor

#21034 Remove the configuration for SetAsInternal
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzContext.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictor.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorSettings.json
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Commands/BasePSCmdlet.cs
Labels: Az.Tools.Predictor
