Repository Azure/azure-powershell, pull requests merged in 2023-10, with the labels that each got.

#22884 Add UseFreeLimit and FreeLimitExhaustionBehavior parameters to DB CRUD
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestCreateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCancelOperation.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithGeoZoneBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithLedgerEnabled.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithSampleName.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGet.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRemove.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRename.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancyNotSpecified.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestFreeLimitDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestFreeLimitDatabaseUpdateFreeLimitExhaustionBehavior.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestUpdateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseCreateWithLicenseType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdateWithLicenseType.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabase.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
Labels: needs-review

#22877 Fix: Remove unintentional inherited properties for GET NVA cmdlet
  src/Network/Network/Models/PSNetworkVirtualApplianceDelegationProperties.cs
Labels: needs-review

#22908 Fix the telemetry collection logic
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/AzPredictorTelemetryTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor.Test/SuggestionSessionTests.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorConstants.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/AzPredictorService.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/ChangeLog.md
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/AggregatedTelemetryData.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/AzPredictorTelemetryClient.cs
  tools/Az.Tools.Predictor/Az.Tools.Predictor/Telemetry/GetSuggestionTelemetryData.cs
  tools/Az.Tools.Predictor/Directory.Build.props
Labels: Az.Tools.Predictor

#22823 [Az.RecoveryServices.Backup] [Autorest migration 8.0.0-preview] Removed SDK based policy commands
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ContainerTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/PolicyTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ContainerTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/PolicyTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ContainerTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/JobTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/PolicyTests.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/RegisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRMRecoveryServicesBackupProtectableItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupRetentionPolicyObject.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/GetAzureRmRecoveryServicesBackupSchedulePolicyObject.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/RemoveAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/Az.RecoveryServices.psd1
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: needs-review

#22986 [Databricks] Fixissue databricks logic for Update-AzDatabricksWorkspace
  src/Databricks/README.md
Labels: Waiting for CI :shipit:

#23003 [KeyVault] Update Live test for creating MHSM in TestSetting.ps1
  src/KeyVault/KeyVault.Test/LiveTests/ManagedHsmDataPlaneLiveTests/TestSetting.ps1
  src/KeyVault/KeyVault.Test/PesterTests/ManagedHsmDataPlaneTests.ps1
  src/KeyVault/KeyVault.sln
Labels: Waiting for CI :shipit:

#22584 AllowBranchToBranch BugFixes
  src/Network/Network.Test/ScenarioTests/RouteServerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.RouteServerTests/TestRouteServerCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Network.generated.format.ps1xml
  src/Network/Network/RouteServer/NewAzureRMRouteServerCommand.cs
  src/Network/Network/RouteServer/UpdateAzureRMRouteServerCommand.cs
  src/Network/Network/help/New-AzRouteServer.md
  src/Network/Network/help/Update-AzRouteServer.md
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: needs-review

#22796 [EventHub] : Parameter `PartitionCount` added to `Set-AzEventHub` cmd
  src/EventHub/EventHub.Autorest/custom/Set-AzEventHub.ps1
  src/EventHub/EventHub.Autorest/docs/Set-AzEventHub.md
  src/EventHub/EventHub.Autorest/test/Approve-AzEventHubPrivateEndpointConnection.Recording.json
  src/EventHub/EventHub.Autorest/test/Deny-AzEventHubPrivateEndpointConnection.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHub.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubApplicationGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubAuthorizationRule.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubClusterNamespace.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubConsumerGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubKey.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubNamespaceV2.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubNetworkRuleSet.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubPrivateEndpointConnection.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubPrivateLink.Recording.json
  src/EventHub/EventHub.Autorest/test/Get-AzEventHubSchemaGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHub.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubApplicationGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubAuthorizationRule.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubConsumerGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubGeoDRConfiguration.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubKey.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubNamespaceV2.Recording.json
  src/EventHub/EventHub.Autorest/test/New-AzEventHubSchemaGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/README.md
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHub.Recording.json
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHubApplicationGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHubAuthorizationRule.Recording.json
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHubConsumerGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHubNamespaceV2.Recording.json
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHubPrivateEndpointConnection.Recording.json
  src/EventHub/EventHub.Autorest/test/Remove-AzEventHubSchemaGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHub.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHub.Tests.ps1
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubApplicationGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubAuthorizationRule.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubConsumerGroup.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubGeoDRConfigurationBreakPair.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubGeoDRConfigurationFailOver.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubNamespaceV2.Recording.json
  src/EventHub/EventHub.Autorest/test/Set-AzEventHubNetworkRuleSet.Recording.json
  src/EventHub/EventHub.Autorest/test/Test-AzEventHubName.Recording.json
  src/EventHub/EventHub.Autorest/test/deployment-template/disasterRecoveryParameter.json
  src/EventHub/EventHub.Autorest/test/deployment-template/keyVaultParameter.json
  src/EventHub/EventHub.Autorest/test/deployment-template/parameter.json
  src/EventHub/EventHub.Autorest/test/env.json
  src/EventHub/EventHub.Autorest/test/localEnv.json
Labels: needs-revision

#22993 [Storage] Remove prefix '?' of the created SAS token
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageBlobSasToken.cs
  src/Storage/Storage/Blob/Cmdlet/NewAzureStorageContainerSasToken.cs
  src/Storage/Storage/Common/AzureStorageBlob.cs
  src/Storage/Storage/Common/Cmdlet/NewAzureStorageAccountSasToken.cs
  src/Storage/Storage/Common/Cmdlet/NewAzureStorageContext.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
  src/Storage/Storage/Common/StorageExtensions.cs
  src/Storage/Storage/Common/Util.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/NewAzDataLakeGen2SasToken.cs
  src/Storage/Storage/File/Cmdlet/NewAzureStorageFileSasToken.cs
  src/Storage/Storage/File/Cmdlet/NewAzureStorageShareSasToken.cs
  src/Storage/Storage/Queue/Cmdlet/NewAzureStorageQueueSasToken.cs
  src/Storage/Storage/Table/Cmdlet/NewAzureStorageTableSasToken.cs
Labels: Breaking Change Release

#23063 [AKS] Remove parameter DockerBridgeCidr from New-AzAksCluster
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/help/New-AzAksCluster.md
  tools/StaticAnalysis/Exceptions/Az.Aks/BreakingChangeIssues.csv
Labels: ready to review
