Repository Azure/azure-powershell, pull requests merged in 2023-09, with the labels that each got.

#22475 Removed info referencing broken links in az.workloads
  src/Workloads/help/New-AzWorkloadsSapVirtualInstance.md
Labels: needs-revision

#22717 Refresh SDK-based dev guide for debugging Azure PowerShell
  documentation/development-docs/azure-powershell-developer-guide.md
Labels: Waiting for CI :shipit:

#22706 Reverted solution update
  src/KeyVault/KeyVault.sln
Labels: needs-revision

#22730 [Az.Resources] Fix unexplicable error message when subscription and scope are both null.
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/Models.ResourceGroups/ResourcesBaseCmdlet.cs
  src/Resources/Resources/Properties/Resources.Designer.cs
  src/Resources/Resources/Properties/Resources.resx
  src/Resources/Resources/RoleAssignments/GetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleDefinitions/GetAzureRoleDefinitionCommand.cs
  src/Resources/Resources/RoleDefinitions/RemoveAzureRoleDefinitionCommand.cs
Labels: needs-review

#22728 Make TemplateFile parameter optional when used with .bicepparam parameter file
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentCmdletBase.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentStacksCmdletBase.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentStacksCreateCmdletBase.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentWhatIfCmdlet.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/TestDeploymentCmdletBase.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/NewAzManagementGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/NewAzResourceGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/NewAzSubscriptionDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SetAzManagmentGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SetAzResourceGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SetAzSubscriptionDeploymentStack.cs
  src/Resources/ResourceManager/SdkClient/DeploymentStacksSdkClient.cs
  src/Resources/ResourceManager/Utilities/BicepUtility.cs
  src/Resources/ResourceManager/Utilities/TemplateUtility.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentStackTests.ps1
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestNewAndSetManagementGroupDeploymentStackWithBicep.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestNewAndSetResourceGroupDeploymentStackWithBicep.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestNewAndSetSubscriptionDeploymentStackWithBicep.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests/TestNewDeploymentFromBicepparamFileOnly.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Get-AzDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzManagementGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzResourceGroupDeploymentWhatIfResult.md
  src/Resources/Resources/help/Get-AzTenantDeploymentWhatIfResult.md
  src/Resources/Resources/help/New-AzDeployment.md
  src/Resources/Resources/help/New-AzManagementGroupDeployment.md
  src/Resources/Resources/help/New-AzManagementGroupDeploymentStack.md
  src/Resources/Resources/help/New-AzResourceGroupDeployment.md
  src/Resources/Resources/help/New-AzResourceGroupDeploymentStack.md
  src/Resources/Resources/help/New-AzSubscriptionDeploymentStack.md
  src/Resources/Resources/help/New-AzTenantDeployment.md
  src/Resources/Resources/help/Set-AzManagementGroupDeploymentStack.md
  src/Resources/Resources/help/Set-AzResourceGroupDeploymentStack.md
  src/Resources/Resources/help/Set-AzSubscriptionDeploymentStack.md
  src/Resources/Resources/help/Test-AzDeployment.md
  src/Resources/Resources/help/Test-AzManagementGroupDeployment.md
  src/Resources/Resources/help/Test-AzResourceGroupDeployment.md
  src/Resources/Resources/help/Test-AzTenantDeployment.md
Labels: Waiting for CI :shipit:

#22456 [SFTP] Specify local user PK is base64 encoded
  src/Storage/Storage.Management/help/Set-AzStorageLocalUser.md
Labels: customer-reported

#22757 Add line for omitted parameter update
  src/SqlVirtualMachine/help/New-AzSqlVM.md
Labels: Waiting for CI :shipit:

#22768 Update Set-AzSecurityPricing.md with limitation note and new names.
  src/Security/Security/help/Set-AzSecurityPricing.md
Labels: Waiting for CI :shipit:

#22781 [Storage] Add warning messages for Queue breaking change
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Queue/Cmdlet/GetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Queue/Cmdlet/SetAzureStorageQueueStoredAccessPolicy.cs
Labels: needs-revision

#22790 Policheck updates - Sept 13 | Bulk Updates (update source)
  src/ApiManagement/ApiManagement/help/Restore-AzApiManagement.md
  src/DataLakeStore/DataLakeStore/help/Get-AzDataLakeStoreDeletedItem.md
  src/DataLakeStore/DataLakeStore/help/Restore-AzDataLakeStoreDeletedItem.md
  src/Functions/help/Get-AzFunctionAppSetting.md
  src/Functions/help/Remove-AzFunctionApp.md
  src/Functions/help/Remove-AzFunctionAppSetting.md
  src/Functions/help/Restart-AzFunctionApp.md
  src/Functions/help/Start-AzFunctionApp.md
  src/Functions/help/Stop-AzFunctionApp.md
  src/Functions/help/Update-AzFunctionApp.md
  src/Functions/help/Update-AzFunctionAppSetting.md
  src/Monitor/Autoscale.Autorest/README.md
  src/Monitor/Autoscale.Autorest/docs/New-AzAutoscaleProfileObject.md
  src/Monitor/Autoscale.Autorest/docs/New-AzAutoscaleSetting.md
  src/Monitor/Autoscale.Autorest/docs/Update-AzAutoscaleSetting.md
  src/Monitor/Monitor/help/New-AzAutoscaleProfileObject.md
  src/Monitor/Monitor/help/New-AzAutoscaleSetting.md
  src/Monitor/Monitor/help/Update-AzAutoscaleSetting.md
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/New-AzFirewallPolicy.md
  src/Network/Network/help/New-AzFirewallPolicyThreatIntelWhitelist.md
  src/Network/Network/help/New-AzFirewallThreatIntelWhitelist.md
  src/Network/Network/help/Set-AzFirewallPolicy.md
Labels: Waiting for CI :shipit:

#22779 Backfill the Az.8.0.0 migration guide for Az.Cdn
  ChangeLog.md
  documentation/migration-guides/Az.8.0.0-migration-guide.md
  src/Cdn/ChangeLog.md
Labels: Waiting for CI :shipit:

#22751 [Az.RecoveryServices.Backup] Added support for customRG with create/modify policy
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/PolicyTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMSmartTieringPolicy.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/GetAzureRmRecoveryServicesBackupWorkloadRecoveryConfig.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/ExampleIssues.csv
Labels: Waiting for CI :shipit:

#22801 Remove trailing space on each line for the yaml to avoid unnecessary PR
  tools/Github/ParseServiceContactsList.ps1
Labels: Waiting for CI :shipit:

#22671 [Az.KeyVault] Security domain Upload Split
  src/KeyVault/KeyVault.Test/PesterTests/ManagedHsmDataPlaneTests.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/ExportAzKeyVaultSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/ImportAzKeyVaultSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/RestoreSecurityDomain.cs
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/SecurityDomainCmdlet.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/ISecurityDomainClient.cs
  src/KeyVault/KeyVault/SecurityDomain/Models/SecurityDomainClient.cs
  src/KeyVault/KeyVault/help/Export-AzKeyVaultSecurityDomain.md
  src/KeyVault/KeyVault/help/Import-AzKeyVaultSecurityDomain.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
  tools/StaticAnalysis/Exceptions/Az.KeyVault/SignatureIssues.csv
Labels: needs-review

#22817 Added support for AlwaysOn soft delete state
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/ExampleIssues.csv
Labels: needs-review

#22831 [Az.KeyVault] Add help example title for Import-AzKeyVaultSecurityDomain
  src/KeyVault/KeyVault/SecurityDomain/Cmdlets/ImportAzKeyVaultSecurityDomain.cs
  src/KeyVault/KeyVault/help/Import-AzKeyVaultSecurityDomain.md
Labels: Waiting for CI :shipit:

#22856 [Breaking Change] Changed parameter SoftDeleteRetentionInDays in New-AzKeyVaultManagedHsm
  src/KeyVault/KeyVault.Test/ScenarioTests/ManagedHsmManagementTests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/ManagedHsm/NewAzKeyVaultManagedHsm.cs
  src/KeyVault/KeyVault/help/New-AzKeyVaultManagedHsm.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review, Breaking Change Release
