Repository Azure/azure-powershell, pull requests merged in 2023-08, with the labels that each got.

#22412 Add UX metadata for MariaDB and PostgreSql
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers-configurations.json
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers-firewallRules.json
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers-virtualNetworkRules.json
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers-configurations.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers-databases.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers-firewallRules.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers-configurations.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers-firewallRules.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers-virtualNetworkRules.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers.json
Labels: needs-review

#22409 Add UX metadata for MariaDB and PostgreSql
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers-configurations.json
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers-firewallRules.json
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers-virtualNetworkRules.json
  src/MariaDb/UX/Microsoft.DBforMariaDB/servers.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers-configurations.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers-databases.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers-firewallRules.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/flexibleServers.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers-configurations.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers-firewallRules.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers-virtualNetworkRules.json
  src/PostgreSql/UX/Microsoft.DBforPostgreSQL/servers.json
Labels: needs-review

#22479 [RecoveryServices] Added ExpiryTime, AFS Job, AFS restore changes
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/JobConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureFileShareModels/AzureFileShareJob.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/RestoreDiskAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/JobTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSRestoreToAnotherRegion.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVmWorkloadBackupProtectionItem.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Backup/BackupAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#22454 Azure SQL MI | API for managed instance needs to be 2018-06-01-preview at least
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/DataClassification/Services/DataClassificationEndpointsCommunicator.cs
Labels: needs-review

#22474 Corrected file not found build warnings in az.batch
  src/Batch/Batch/help/Get-AzBatchPoolUsageMetric.md
Labels: Waiting for CI :shipit:

#22505 Added the example to remove an API from a managed gateway. Users are getting confused and created few support request for the same.
  src/ApiManagement/ApiManagement/help/Remove-AzApiManagementApiFromGateway.md
Labels: Waiting for CI :shipit:

#22515 Fixed websocket related tasks in InvokeAzContainerInstanceCommand_ExecuteExpanded.cs
  src/ContainerInstance/custom/InvokeAzContainerInstanceCommand_ExecuteExpanded.cs
Labels: needs-revision, customer-reported

#22522 [StackHCI] Use correct version of cloud management service
  src/StackHCI/custom/stackhci.ps1
Labels: needs-revision

#22550 Updated ChangeLog.md for Az.ContainerInstance
  src/ContainerInstance/ChangeLog.md
Labels: Waiting for CI :shipit:

#22452 [Synapse] Update artifact to 1.0.0-preview.18
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Synapse.csproj
Labels: needs-revision

#22459 [Compute] update sdk package reference for Compute
  src/Compute/Compute.Test/Compute.Test.csproj
  src/Compute/Compute/Compute.csproj
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssIpConfigCommand.cs
  src/Network/Network.Test/Network.Test.csproj
  src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/RecoveryServices.SiteRecovery.Test.csproj
  src/Security/Security.Test/Security.Test.csproj
  src/Ssh/Ssh.Test/ScenarioTests/SshTestRunner.cs
  src/Ssh/Ssh.Test/SessionRecords/Microsoft.Azure.Commands.Ssh.Test.ScenarioTests.GetAzSshConfigTests/TestGetVmConfig.json
  src/Ssh/Ssh.Test/Ssh.Test.csproj
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Do Not Merge :no_entry_sign:, Breaking Change Release

#22385 Updated Sql.sdk files to include the 2023-02-01 version of LongTermRetentionPolicies
  src/Sql/Sql.Sdk/Generated/ILongTermRetentionBackupsOperations.cs
  src/Sql/Sql.Sdk/Generated/ILongTermRetentionPoliciesOperations.cs
  src/Sql/Sql.Sdk/Generated/LongTermRetentionBackupsOperations.cs
  src/Sql/Sql.Sdk/Generated/LongTermRetentionBackupsOperationsExtensions.cs
  src/Sql/Sql.Sdk/Generated/LongTermRetentionPoliciesOperations.cs
  src/Sql/Sql.Sdk/Generated/LongTermRetentionPoliciesOperationsExtensions.cs
  src/Sql/Sql.Sdk/Generated/Models/LongTermRetentionBackup.cs
  src/Sql/Sql.Sdk/Generated/Models/LongTermRetentionPolicy.cs
  src/Sql/Sql.Sdk/Generated/SdkInfo_SqlManagementClient.cs
  src/Sql/Sql.Sdk/README.md
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/SetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseBackupLongTermRetentionPolicyModel.cs
  src/Sql/Sql/Database Backup/Model/AzureSqlDatabaseLongTermRetentionBackupModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupAdapter.cs
  src/Sql/Sql/help/Set-AzSqlDatabaseBackupLongTermRetentionPolicy.md
Labels: Do Not Merge :no_entry_sign:

#22517 [DataMigration] Update the description of command New-AzDataMigrationToSqlDb
  src/DataMigration/DataMigration.Autorest/docs/Az.DataMigration.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationToSqlDb.md
  src/DataMigration/DataMigration.Autorest/readme.md
Labels: needs-revision

#22546 Bug Fix for Inspection Limit Feature for Application Gateway Firewall Policy Settings
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayFirewallPolicyWithRateLimitRuleGeoLocation.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/FirewallPolicy/FirewallCustomRule/GroupByUserSession/GroupByVariable/NewAzureApplicationGatewayFirewallCustomRuleGroupByVariableCommand.cs
  src/Network/Network/help/New-AzApplicationGatewayFirewallCustomRuleGroupByVariable.md
Labels: needs-revision

#22529 [Config] add config to disable write error to file system
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Clear-AzConfig.md
  src/Accounts/Accounts/help/Get-AzConfig.md
  src/Accounts/Accounts/help/Update-AzConfig.md
  src/Accounts/Authentication/Config/ConfigInitializer.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
  src/shared/ConfigKeys.cs
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#22519 Support deployment stack object as input parameter for Save-Az*DeploymentStack and Remove-Az*DeploymentStack cmdlets
  src/Resources/ResourceManager/Implementation/DeploymentStacks/RemoveAzManagmentGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/RemoveAzResourceGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/RemoveAzSubscriptionDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SaveAzManagmentGroupDeploymentStackTemplate.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SaveAzResourceGroupDeploymentStackTemplate.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SaveAzSubscriptionDeploymentStackTemplate.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentStackTests.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentStackTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestSaveAndRemoveManagementGroupDeploymentStackWithPipeOperator.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestSaveAndRemoveResourceGroupDeploymentStackWithPipeOperator.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestSaveAndRemoveSubscriptionDeploymentStackWithPipeOperator.json
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Remove-AzManagementGroupDeploymentStack.md
  src/Resources/Resources/help/Remove-AzResourceGroupDeploymentStack.md
  src/Resources/Resources/help/Remove-AzSubscriptionDeploymentStack.md
  src/Resources/Resources/help/Save-AzManagementGroupDeploymentStackTemplate.md
  src/Resources/Resources/help/Save-AzResourceGroupDeploymentStackTemplate.md
  src/Resources/Resources/help/Save-AzSubscriptionDeploymentStackTemplate.md
Labels: needs-revision

#22596 Fixed type conversion issue when sending email in live test
  tools/TestFx/Utilities/EmailServiceUtility.psm1
Labels: Waiting for CI :shipit:

#22578 [HDInsight] Add warning message for break changes which plan to release in Nov.
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/Constants.cs
  src/HDInsight/HDInsight/HDInsight.csproj
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightClusterIdentity.cs
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightComponentVersionCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightConfigValuesCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightMetastoreCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightScriptActionCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightSecurityProfile.cs
  src/HDInsight/HDInsight/ManagementCommands/AddAzureHDInsightStorageCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/DisableAzureHDInsightAzureMonitorCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/EnableAzureHDInsightAzureMonitorCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GetAzureHDInsightAzureMonitorCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GetAzureHDInsightClusterAutoscaleConfigurationCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GetAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GetAzureHDInsightHostCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/GetAzureHDInsightPropertiesCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterConfigCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/RemoveAzureHDInsightClusterAutoscaleConfigurationCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightClusterAutoscaleConfigurationCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightClusterDiskEncryptionKeyCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightClusterSizeCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightDefaultStorageCommand.cs
  src/HDInsight/HDInsight/ManagementCommands/SetAzureHDInsightGatewayCredentialCommand.cs
Labels: Waiting for CI :shipit:

#22580 [KeyVault] Formatted the table view of outputs
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Secret/BackupAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/Secret/GetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/Secret/RemoveAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/Secret/RestoreAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/Secret/SetAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/Commands/Secret/UndoAzureKeyVaultSecretRemoval.cs
  src/KeyVault/KeyVault/Commands/Secret/UpdateAzureKeyVaultSecret.cs
  src/KeyVault/KeyVault/KeyVault.format.ps1xml
  src/KeyVault/KeyVault/Models/Certificate/PSDeletedKeyVaultCertificate.cs
  src/KeyVault/KeyVault/Models/Certificate/PSDeletedKeyVaultCertificateIdentityItem.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificate.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateAdministratorDetails.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateContact.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateIdentityItem.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateIssuer.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateIssuerIdentityItem.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateOperation.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificateOrganizationDetails.cs
  src/KeyVault/KeyVault/Models/Certificate/PSKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/Models/Secret/PSDeletedKeyVaultSecret.cs
  src/KeyVault/KeyVault/Models/Secret/PSDeletedKeyVaultSecretIdentityItem.cs
  src/KeyVault/KeyVault/Models/Secret/PSKeyVaultSecret.cs
  src/KeyVault/KeyVault/Models/Secret/PSKeyVaultSecretAttributes.cs
  src/KeyVault/KeyVault/Models/Secret/PSKeyVaultSecretIdentityItem.cs
Labels: Waiting for CI :shipit:

#22602 Update Maintenance ChangeLog.md
  src/Maintenance/Maintenance/ChangeLog.md
Labels: Waiting for CI :shipit:

#22547 Add more parameters on Update-AzSqlVM
  src/SqlVirtualMachine/custom/Update-AzSqlVM.ps1
  src/SqlVirtualMachine/docs/New-AzSqlVM.md
  src/SqlVirtualMachine/docs/Update-AzSqlVM.md
  src/SqlVirtualMachine/examples/New-AzSqlVM.md
  src/SqlVirtualMachine/examples/Update-AzSqlVM.md
  src/SqlVirtualMachine/test/Update-AzSqlVM.Recording.json
  src/SqlVirtualMachine/test/Update-AzSqlVM.Tests.ps1
Labels: needs-revision

#22585 CosmosDB - New Restore Parameter
  src/CosmosDB/CosmosDB.Test/ScenarioTests/RestoreTests.cs
  src/CosmosDB/CosmosDB.Test/ScenarioTests/RestoreTests.ps1
  src/CosmosDB/CosmosDB.Test/SessionRecords/Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.RestoreTests/TestSqlRestoreAccountPublicNetworkAccessCmdlets.json
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/RestoreAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/help/Restore-AzCosmosDBAccount.md
Labels: Waiting for CI :shipit:

#22617 Bump Version for DesktopVirtualization Preview Release
  src/DesktopVirtualization/Az.DesktopVirtualization.psd1
  src/DesktopVirtualization/ChangeLog.md
  src/DesktopVirtualization/Properties/AssemblyInfo.cs
  tools/Az/Az.psd1
  tools/AzPreview/AzPreview.psd1
  tools/Docs/az-ps-latest.csv
Labels: Waiting for CI :shipit:

#22569 Remove PS 7.0 from smoke test matrix
  .azure-pipelines/release-test.yml
Labels: needs-review

#22641 Updated sync aliases pipeline after migrating from fabricbot.json to resourceManagement.yml
  .azure-pipelines/sync-aliases.yml
  tools/Github/ParseServiceContactsList.ps1
  tools/Github/ParseWiki2Json.ps1
Labels: needs-review

#22600 [Compute] Get-AzHostSize and Update-AzHost
  src/Compute/Compute.Test/ScenarioTests/DedicatedHostTests.cs
  src/Compute/Compute.Test/ScenarioTests/DedicatedHostTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DedicatedHostTests/TestDedicatedHostUpdateAndSize.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/DedicatedHost/DedicatedHostSizeGetMethod.cs
  src/Compute/Compute/Generated/DedicatedHost/DedicatedHostUpdateMethod.cs
  src/Compute/Compute/help/Get-AzHostSize.md
  src/Compute/Compute/help/Update-AzHost.md
Labels: needs-revision

#22644 [KeyVault] Purge deleted MHSM in live test
  src/KeyVault/KeyVault.Test/LiveTests/ManagedHsmDataPlaneLiveTests/TestSetting.ps1
Labels: Waiting for CI :shipit:

#22637 Adding Autoscaling Capabilities to Virtual Network Gateway
  src/Network/Network.Management.Sdk/Generated/Models/VirtualNetworkGatewaySkuTier.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSVirtualNetworkGateway.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayAutoscaleConfiguration.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayPropertiesAutoScaleConfigurationBounds.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/VirtualNetworkGateway/UpdateAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
  src/Network/Network/help/Set-AzVirtualNetworkGateway.md
Labels: Waiting for CI :shipit:

#22338 Support in-tool notification for version upgrade
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Clear-AzConfig.md
  src/Accounts/Accounts/help/Get-AzConfig.md
  src/Accounts/Accounts/help/Update-AzConfig.md
  src/Accounts/Authentication.Test/UnitTests/FrequencyServiceTests.cs
  src/Accounts/Authentication/AzureSessionInitializer.cs
  src/Accounts/Authentication/Config/ConfigInitializer.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
  src/Accounts/Authentication/Utilities/FrequencyService.cs
  src/shared/ConfigKeys.cs
Labels: Waiting for CI :shipit:

#22542 [Subscription] Remove the default value of the parameter SubscriptionId from the command
  src/Subscription/README.md
  src/Subscription/docs/Get-AzSubscriptionAcceptOwnershipStatus.md
  src/Subscription/docs/Get-AzSubscriptionPolicy.md
  src/Subscription/docs/Invoke-AzSubscriptionAcceptOwnership.md
  src/Subscription/docs/New-AzSubscriptionAlias.md
  src/Subscription/examples/Get-AzSubscriptionAcceptOwnershipStatus.md
  src/Subscription/examples/New-AzSubscriptionAlias.md
  src/Subscription/test/AzSubscription.Recording.json
  src/Subscription/test/AzSubscription.Tests.ps1
  src/Subscription/test/env.json
Labels: needs-revision

#22638 [Monitor] [data collection rule] breaking change message for autorest generation
  src/Monitor/Monitor/ChangeLog.md
  src/Monitor/Monitor/DataCollectionRules/GetAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/NewAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/RemoveAzureRmDataCollectionRuleAssociationCommand.cs
  src/Monitor/Monitor/DataCollectionRules/RemoveAzureRmDataCollectionRuleCommand.cs
  src/Monitor/Monitor/DataCollectionRules/SetAzureRmDataCollectionRuleCommand.cs
Labels: Waiting for CI :shipit:

#22655 [Storage] Update the description of Permission property of New-AzStorageQueueSasToken
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/New-AzStorageQueueSASToken.md
Labels: needs-revision

#22436 [SQL] Add -EncryptionProtectorAutoRotation param to database cmdlets
  src/Sql/Sql.Sdk/Generated/DatabasesOperations.cs
  src/Sql/Sql.Sdk/Generated/Models/Database.cs
  src/Sql/Sql.Sdk/Generated/Models/DatabaseUpdate.cs
  src/Sql/Sql.Sdk/Generated/Models/FreeLimitExhaustionBehavior.cs
  src/Sql/Sql.Sdk/Generated/Models/Server.cs
  src/Sql/Sql.Sdk/Generated/Models/ServerUpdate.cs
  src/Sql/Sql.Sdk/Generated/SdkInfo_SqlManagementClient.cs
  src/Sql/Sql.Sdk/Generated/ServersOperations.cs
  src/Sql/Sql.Sdk/README.md
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/Sql/Sql.Test/ScenarioTests/DatabaseReplicationTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestCreateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCancelOperation.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithGeoZoneBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithLedgerEnabled.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithPerDBCMK.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithSampleName.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGet.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRemove.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRename.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithPerDBCMK.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancyNotSpecified.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestRevalidateAndRevertAKVKeyForDatabaseWithPerDBCMK.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestUpdateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseCreateWithLicenseType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdateWithLicenseType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseReplicationTests/CreateDatabaseCopyWithPerDBCMK.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database Backup/Cmdlet/RestoreAzureRMSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseCopy.cs
  src/Sql/Sql/Replication/Cmdlet/NewAzureSqlDatabaseSecondary.cs
  src/Sql/Sql/Replication/Model/AzureSqlDatabaseReplicationModelBase.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
  src/Sql/Sql/help/New-AzSqlDatabase.md
  src/Sql/Sql/help/New-AzSqlDatabaseCopy.md
  src/Sql/Sql/help/New-AzSqlDatabaseSecondary.md
  src/Sql/Sql/help/Restore-AzSqlDatabase.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
Labels: Waiting for CI :shipit:, needs-review

#22672 Update code-gen.yml for Azure Pipelines
  .azure-pipelines/code-gen.yml
Labels: Waiting for CI :shipit:

#22601 [Compute] Bug fix for Update-Azvmss
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetAutoRollback.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetImageReferenceSkuUpdate.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetNewEncryptionAtHost.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetRollingUpgrade.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetUpdate.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
Labels: Waiting for CI :shipit:
