Repository Azure/azure-powershell, pull requests merged in 2023-05, with the labels that each got.

#21526 Remove `HostNamePrefix`
  src/SignalR/SignalR/ChangeLog.md
  src/SignalR/SignalR/Cmdlets/GetAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/NewAzureRmSignalR.cs
  src/SignalR/SignalR/Cmdlets/UpdateAzureRmSignalR.cs
  src/SignalR/SignalR/Models/PSSignalRResource.cs
  src/SignalR/SignalR/SignalR.csproj
  src/SignalR/SignalR/help/Get-AzSignalR.md
  src/SignalR/SignalR/help/Get-AzSignalRKey.md
  src/SignalR/SignalR/help/Get-AzWebPubSub.md
  src/SignalR/SignalR/help/Get-AzWebPubSubCustomCertificate.md
  src/SignalR/SignalR/help/Get-AzWebPubSubCustomDomain.md
  src/SignalR/SignalR/help/Get-AzWebPubSubHub.md
  src/SignalR/SignalR/help/Get-AzWebPubSubKey.md
  src/SignalR/SignalR/help/Get-AzWebPubSubSku.md
  src/SignalR/SignalR/help/Get-AzWebPubSubUsage.md
  src/SignalR/SignalR/help/New-AzSignalR.md
  src/SignalR/SignalR/help/New-AzSignalRKey.md
  src/SignalR/SignalR/help/New-AzWebPubSub.md
  src/SignalR/SignalR/help/New-AzWebPubSubCustomCertificate.md
  src/SignalR/SignalR/help/New-AzWebPubSubCustomDomain.md
  src/SignalR/SignalR/help/New-AzWebPubSubEventHubEndpointObject.md
  src/SignalR/SignalR/help/New-AzWebPubSubEventNameFilterObject.md
  src/SignalR/SignalR/help/New-AzWebPubSubHub.md
  src/SignalR/SignalR/help/New-AzWebPubSubKey.md
  src/SignalR/SignalR/help/Remove-AzSignalR.md
  src/SignalR/SignalR/help/Remove-AzWebPubSub.md
  src/SignalR/SignalR/help/Remove-AzWebPubSubCustomCertificate.md
  src/SignalR/SignalR/help/Remove-AzWebPubSubCustomDomain.md
  src/SignalR/SignalR/help/Remove-AzWebPubSubHub.md
  src/SignalR/SignalR/help/Restart-AzWebPubSub.md
  src/SignalR/SignalR/help/Set-AzSignalRUpstream.md
  src/SignalR/SignalR/help/Test-AzSignalRName.md
  src/SignalR/SignalR/help/Test-AzWebPubSubNameAvailability.md
  src/SignalR/SignalR/help/Update-AzSignalRNetworkAcl.md
  src/SignalR/SignalR/help/Update-AzWebPubSub.md
  tools/StaticAnalysis/Exceptions/Az.SignalR/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:, Breaking Change Release

#21667 Fix typo in Update-AzWebAppTrafficRouting.md
  src/Websites/Websites/help/Update-AzWebAppTrafficRouting.md
Labels: Waiting for CI :shipit:, customer-reported

#21674 Update Service Owner Names in Tests
  src/Network/Network.Test/ScenarioTests/CortexTests.cs
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceTests.cs
  src/Network/Network.Test/ScenarioTests/RouteServerTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualHubRouteTableTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualRouterTests.cs
Labels: needs-revision

#21002 Gateway Loadbalancer Get Nic bug fix
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTests.ps1
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTestsGenerated.cs
  src/Network/Network.Test/ScenarioTests/NetworkInterfaceTestsGenerated.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkInterfaceTestsGenerated/TestNetworkInterfaceGatewayLoadBalancerConsumer.json
  src/Network/Network/Models/PSNetworkInterfaceIpConfiguration.cs
  tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
Labels: Breaking Change Release

#21709 Set Standard SKU as defaults for LB and IP creates
  src/Network/Network.Test/ScenarioTests/LoadBalancerTests.cs
  src/Network/Network.Test/ScenarioTests/LoadBalancerTests.ps1
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.cs
  src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTests/TestSetLoadBalancerCRUDInternalStandardSkuAsDefault.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerTests/TestSetLoadBalancerCRUDPublicStandardSkuAsDefault.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.PublicIpAddressTests/TestPublicIpStandardSkuAsDefault.json
  src/Network/Network/LoadBalancer/NewAzureRMLoadBalancerCommand.cs
  src/Network/Network/PublicIpAddress/NewAzurePublicIpAddressCommand.cs
Labels: Waiting for CI :shipit:

#21348 Adding PreferredEnclaveType support for Elastic Pools in Az.Sql cmdlets corresponding to 2022-08-01-preview swagger release
  src/Sql/Sql.Sdk/Generated/ElasticPoolsOperations.cs
  src/Sql/Sql.Sdk/Generated/Models/ElasticPool.cs
  src/Sql/Sql.Sdk/Generated/Models/ElasticPoolUpdate.cs
  src/Sql/Sql.Sdk/Generated/SdkInfo_SqlManagementClient.cs
  src/Sql/Sql.Sdk/README.md
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/ElasticPoolCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithPreferredEnclaveType.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Elastic Pools/Cmdlet/NewAzureSqlElasticPool.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/SetAzureSqlElasticPool.cs
  src/Sql/Sql/Elastic Pools/Model/AzureSqlElasticPoolModel.cs
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/Sql/Sql/help/Get-AzSqlDatabase.md
  src/Sql/Sql/help/Get-AzSqlElasticPool.md
  src/Sql/Sql/help/New-AzSqlDatabase.md
  src/Sql/Sql/help/New-AzSqlElasticPool.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
  src/Sql/Sql/help/Set-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:

#21466 [HDInsight][Breaking Change]Remove deprecated parameters
  src/HDInsight/HDInsight.Test/HDInsight.Test.csproj
  src/HDInsight/HDInsight.Test/ScenarioTests/HDInsightClusterTests.cs
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightAutoscaleTests/TestAutoscaleRelatedCommands.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightAzureMonitorTests/TestAzureMonitorRelatedCommands.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestClusterRelatedCommands.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCreateClusterWithLoadBasedAutoscale.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightClusterTests/TestCreateClusterWithScheduleBasedAutoscale.json
  src/HDInsight/HDInsight.Test/SessionRecords/Commands.HDInsight.Test.ScenarioTests.HDInsightSetGatewayCredentialTest/TestSetGatewayCredential.json
  src/HDInsight/HDInsight.sln
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/Constants.cs
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
  tools/StaticAnalysis/Exceptions/Az.HDInsight/BreakingChangeIssues.csv
Labels: HDInsight, Breaking Change Release, needs-author-feedback

#21693 [Monitor] Create monitor and apiversion is stable/2023-04-03
  src/Monitor/MonitorWorkspace.Autorest/.gitattributes
  src/Monitor/MonitorWorkspace.Autorest/.gitignore
  src/Monitor/MonitorWorkspace.Autorest/Az.MonitorWorkspace.psd1
  src/Monitor/MonitorWorkspace.Autorest/README.md
  src/Monitor/MonitorWorkspace.Autorest/UX/Microsoft.Monitor/accounts.json
  src/Monitor/MonitorWorkspace.Autorest/custom/README.md
  src/Monitor/MonitorWorkspace.Autorest/docs/Az.MonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/docs/Get-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/docs/New-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/docs/README.md
  src/Monitor/MonitorWorkspace.Autorest/docs/Remove-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/docs/Update-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/examples/Get-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/examples/New-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/examples/Remove-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/examples/Update-AzMonitorWorkspace.md
  src/Monitor/MonitorWorkspace.Autorest/how-to.md
  src/Monitor/MonitorWorkspace.Autorest/license.txt
  src/Monitor/MonitorWorkspace.Autorest/resources/README.md
  src/Monitor/MonitorWorkspace.Autorest/test/AzMonitorWorkspace.Recording.json
  src/Monitor/MonitorWorkspace.Autorest/test/AzMonitorWorkspace.Tests.ps1
  src/Monitor/MonitorWorkspace.Autorest/test/Get-AzMonitorWorkspace.Tests.ps1
  src/Monitor/MonitorWorkspace.Autorest/test/New-AzMonitorWorkspace.Tests.ps1
  src/Monitor/MonitorWorkspace.Autorest/test/README.md
  src/Monitor/MonitorWorkspace.Autorest/test/Remove-AzMonitorWorkspace.Tests.ps1
  src/Monitor/MonitorWorkspace.Autorest/test/Update-AzMonitorWorkspace.Tests.ps1
  src/Monitor/MonitorWorkspace.Autorest/test/env.json
  src/Monitor/MonitorWorkspace.Autorest/test/loadEnv.ps1
  src/Monitor/MonitorWorkspace.Autorest/test/utils.ps1
  src/Monitor/MonitorWorkspace.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-review

#21726 [DataBricks] Fix issue Update-AzDatabricksWorkspace doesn't work as expected while …
  src/Databricks/UX/Microsoft.Databricks/accessConnectors.json
  src/Databricks/UX/Microsoft.Databricks/workspaces-virtualNetworkPeerings.json
  src/Databricks/UX/Microsoft.Databricks/workspaces.json
  src/Databricks/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/docs/Az.Databricks.md
  src/Databricks/docs/Get-AzDatabricksAccessConnector.md
  src/Databricks/docs/Get-AzDatabricksOutboundNetworkDependenciesEndpoint.md
  src/Databricks/docs/Get-AzDatabricksVNetPeering.md
  src/Databricks/docs/Get-AzDatabricksWorkspace.md
  src/Databricks/docs/New-AzDatabricksAccessConnector.md
  src/Databricks/docs/New-AzDatabricksVNetPeering.md
  src/Databricks/docs/Remove-AzDatabricksAccessConnector.md
  src/Databricks/docs/Remove-AzDatabricksVNetPeering.md
  src/Databricks/docs/Remove-AzDatabricksWorkspace.md
  src/Databricks/docs/Update-AzDatabricksAccessConnector.md
  src/Databricks/docs/Update-AzDatabricksWorkspace.md
  src/Databricks/examples/Update-AzDatabricksWorkspace.md
Labels: needs-review

#21713 Add -Force parameter on Publish-AzBicepModule
  src/Resources/ResourceManager/Implementation/Bicep/PublishAzureBicepModuleCmdlet.cs
  src/Resources/ResourceManager/Utilities/BicepUtility.cs
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Publish-AzBicepModule.md
Labels: ARM, needs-review, Service Attention, customer-reported

#21739 [Az.Synapse] Remove the unnecessary breaking change of parameter '-SparkConfigFilePath' for Spark Pool related cmdlets
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/NewAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Commands/ManagementCommands/SparkPool/UpdateAzureSynapseSparkPool.cs
  src/Synapse/Synapse/Common/HelpMessages.cs
  src/Synapse/Synapse/help/New-AzSynapseSparkPool.md
  src/Synapse/Synapse/help/Update-AzSynapseSparkPool.md
  tools/StaticAnalysis/Exceptions/Az.Synapse/BreakingChangeIssues.csv
Labels: needs-review, Breaking Change Release, Synapse

#21756 [Synapse]update new role assignment cmdlet help doc
  src/Synapse/Synapse/help/New-AzSynapseRoleAssignment.md
Labels: Waiting for CI :shipit:

#21753 [KeyVault]Change encoding way from ASCII/Default to UTF8
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Key/InvokeAzureKeyVaultKeyOperation.cs
  src/KeyVault/KeyVault/Models/Key/PSKeyOperationResult.cs
  src/KeyVault/KeyVault/help/Invoke-AzKeyVaultKeyOperation.md
Labels: Waiting for CI :shipit:

#21644 Az.StackHCI May release
  src/StackHCI/Az.StackHCI.psd1
  src/StackHCI/README.md
  src/StackHCI/custom/stackhci.ps1
  src/StackHCI/docs/Az.StackHCI.md
  src/StackHCI/docs/Get-AzStackHciArcSetting.md
  src/StackHCI/docs/Get-AzStackHciCluster.md
  src/StackHCI/docs/Get-AzStackHciExtension.md
  src/StackHCI/docs/New-AzStackHciArcSetting.md
  src/StackHCI/docs/New-AzStackHciCluster.md
  src/StackHCI/docs/New-AzStackHciExtension.md
  src/StackHCI/docs/Register-AzStackHCI.md
  src/StackHCI/docs/Remove-AzStackHciArcSetting.md
  src/StackHCI/docs/Remove-AzStackHciCluster.md
  src/StackHCI/docs/Remove-AzStackHciExtension.md
  src/StackHCI/docs/Set-AzStackHCI.md
  src/StackHCI/docs/Test-AzStackHCIConnection.md
  src/StackHCI/docs/Unregister-AzStackHCI.md
  src/StackHCI/docs/Update-AzStackHciCluster.md
  src/StackHCI/examples/Test-AzStackHCIConnection.md
  tools/StaticAnalysis/Exceptions/Az.StackHCI/BreakingChangeIssues.csv
Labels: Breaking Change Release, StackHCI

#21770 [SQL] Powershell cmdlet for SQL Ledger support in Managed Instance
  src/Sql/Sql.Sdk/Generated/IManagedLedgerDigestUploadsOperations.cs
  src/Sql/Sql.Sdk/Generated/ISqlManagementClient.cs
  src/Sql/Sql.Sdk/Generated/ManagedDatabasesOperations.cs
  src/Sql/Sql.Sdk/Generated/ManagedLedgerDigestUploadsOperations.cs
  src/Sql/Sql.Sdk/Generated/ManagedLedgerDigestUploadsOperationsExtensions.cs
  src/Sql/Sql.Sdk/Generated/Models/ManagedDatabase.cs
  src/Sql/Sql.Sdk/Generated/Models/ManagedDatabaseUpdate.cs
  src/Sql/Sql.Sdk/Generated/Models/ManagedLedgerDigestUploads.cs
  src/Sql/Sql.Sdk/Generated/Models/ManagedLedgerDigestUploadsState.cs
  src/Sql/Sql.Sdk/Generated/SdkInfo_SqlManagementClient.cs
  src/Sql/Sql.Sdk/Generated/SqlManagementClient.cs
  src/Sql/Sql.Sdk/README.md
  src/Sql/Sql.Test/ScenarioTests/Common.ps1
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseCrudScenarioTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseCrudScenarioTests.ps1
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceLedgerDigestUploadTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceLedgerDigestUploadTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseCrudScenarioTests/TestManagedDatabaseCreationWithLedgerEnabled.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceLedgerDigestUploadTests/TestGetDefaultLedgerDigestUpload.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceLedgerDigestUploadTests/TestSetLedgerDigestUploadByDatabaseObject.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceLedgerDigestUploadTests/TestSetLedgerDigestUploadByName.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceLedgerDigestUploadTests/TestSetLedgerDigestUploadByResourceId.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedDatabase/Cmdlet/NewAzureSqlManagedDatabase.cs
  src/Sql/Sql/ManagedDatabase/Model/AzureSqlManagedDatabaseModel.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseAdapter.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Cmdlet/AzureSqlManagedDatabaseLedgerDigestUploadBase.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Cmdlet/DisableAzSqlManagedDatabaseLedgerDigestUpload.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Cmdlet/EnableAzSqlManagedDatabaseLedgerDigestUpload.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Cmdlet/GetAzSqlManagedDatabaseLedgerDigestUpload.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Model/AzureSqlManagedDatabaseLedgerDigestLocationModel.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Model/AzureSqlManagedDatabaseLedgerDigestUploadModel.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Services/AzureSqlManagedDatabaseLedgerDigestUploadAdapter.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Services/AzureSqlManagedDatabaseLedgerDigestUploadCommunicator.cs
  src/Sql/Sql/help/Az.Sql.md
  src/Sql/Sql/help/Disable-AzSqlInstanceDatabaseLedgerDigestUpload.md
  src/Sql/Sql/help/Enable-AzSqlInstanceDatabaseLedgerDigestUpload.md
  src/Sql/Sql/help/Get-AzSqlInstanceDatabaseLedgerDigestUpload.md
  src/Sql/Sql/help/New-AzSqlInstanceDatabase.md
Labels: needs-review

#21754 [Storage] Fix issue of getting a single blob with leading slashes
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlob.cs
  src/Storage/Storage/Common/Util.cs
Labels: Storage, Breaking Change Release

#21731 [Networking] - Add Connection Draining support for load balancer backend address
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendAddressConfig.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolCreate.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/LoadBalancer/NewAzLoadBalancerBackendAddressConfig.cs
  src/Network/Network/Models/PSLoadBalancerBackendAddress.cs
  src/Network/Network/help/New-AzLoadBalancerBackendAddressConfig.md
Labels: Waiting for CI :shipit:

#21346 Add New-AzDataMigrationTdeCertificateMigration Cmdlet
  src/DataMigration/DataMigration.Autorest/Az.DataMigration.psd1
  src/DataMigration/DataMigration.Autorest/custom/Cmdlets/New-AzDataMigrationTdeCertificateMigration.ps1
  src/DataMigration/DataMigration.Autorest/docs/Az.DataMigration.md
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationTdeCertificateMigration.md
  src/DataMigration/DataMigration.Autorest/examples/New-AzDataMigrationTdeCertificateMigration.md
  src/DataMigration/DataMigration.Autorest/test/New-AzDataMigrationTdeCertificateMigration.Tests.ps1
Labels: needs-revision

#21687 Add new commandlet 'Add-AzServiceFabricManagedClusterNetworkSecurityRule'
  src/Accounts/Accounts/Utilities/CommandMappings.json
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/ServiceFabricManagedClustersTests.cs
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/ServiceFabricManagedClustersTests.ps1
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.ServiceFabricManagedClustersTests/TestAddNetworkSecurityRule.json
  src/ServiceFabric/ServiceFabric/Az.ServiceFabric.psd1
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/ServiceFabric/ServiceFabric/Commands/ManagedClusters/ManagedClusters/AddAzServiceFabricManagedClusterNetworkSecurityRule.cs
  src/ServiceFabric/ServiceFabric/Commands/ManagedClusters/ManagedClusters/SetAzServiceFabricManagedCluster.cs
  src/ServiceFabric/ServiceFabric/Models/ManagedClusters/NetworkSecurityAccess.cs
  src/ServiceFabric/ServiceFabric/Models/ManagedClusters/NetworkSecurityDirection.cs
  src/ServiceFabric/ServiceFabric/Models/ManagedClusters/NetworkSecurityProtocol.cs
  src/ServiceFabric/ServiceFabric/help/Add-AzServiceFabricManagedClusterNetworkSecurityRule.md
  src/ServiceFabric/ServiceFabric/help/Az.ServiceFabric.md
  src/ServiceFabric/ServiceFabric/help/Set-AzServiceFabricManagedCluster.md
Labels: needs-revision

#21736 CosmosDB: Adds changes to handle enabling partition merge on CosmosDB account
  src/CosmosDB/CosmosDB.Test/ScenarioTests/AccountTests.ps1
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/NewOrUpdateAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccount.cs
  src/CosmosDB/CosmosDB/Helpers/Constants.cs
  src/CosmosDB/CosmosDB/Models/DatabaseAccount/PSDatabaseAccountGetResults.cs
  src/CosmosDB/CosmosDB/help/New-AzCosmosDBAccount.md
  src/CosmosDB/CosmosDB/help/Update-AzCosmosDBAccount.md
Labels: Waiting for CI :shipit:, Cosmos

#21792 [Az.Relay] Fix version for Relay
  src/Relay/Az.Relay.psd1
  tools/StaticAnalysis/Exceptions/Az.Relay/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:

#21744 [Monitor] Generate UX folder and update UX folder
  src/Monitor/ActivityLogAlert.Autorest/UX/Microsoft.Insights/activityLogAlerts.json
  src/Monitor/Autoscale.Autorest/UX/Microsoft.Insights/autoscalesettings.json
  src/Monitor/DiagnosticSetting.Autorest/UX/Microsoft.Insights/diagnosticSettings.json
  src/Monitor/DiagnosticSetting.Autorest/UX/Microsoft.Insights/diagnosticSettingsCategories.json
  src/Monitor/ScheduledQueryRule.Autorest/UX/Microsoft.Insights/scheduledQueryRules.json
Labels: needs-review

#21765 Fixed Get-AzResourceGroup on -Id requires Set-AzContext to given subs…
  src/Resources/ResourceManager/Implementation/ResourceGroups/GetAzureResourceGroupCmdlet.cs
  src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs
  src/Resources/Resources.Test/ResourceGroups/GetAzureResourceGroupCommandTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-review

#21803 Updated Change Log for DataProtection
  src/DataProtection/ChangeLog.md
Labels: needs-review

#21780 Preload assemblies on Windows PowerShell
  src/Compute/Compute/ChangeLog.md
  tools/AzureRM.Example.psm1
  tools/UpdateModules.psm1
Labels: needs-review

#21810 Update common libs to pick up newtonsoft.json update
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#21748 Remove unusable NextLink parameter and parameter set from Get-AzVM
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs
  src/Compute/Compute/help/Get-AzVM.md
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Compute, Breaking Change Release

#21832 [KeyVault] Add breaking change announcement for SoftDeleteRetentionInDays
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/ManagedHsm/GetAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/ManagedHsm/NewAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/ManagedHsm/RemoveAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/ManagedHsm/UpdateAzureManagedHsm.cs
  src/KeyVault/KeyVault/KeyVault.csproj
Labels: needs-review

#21834 Polish Change Logs for release-2023-05-23
  src/Compute/Compute/ChangeLog.md
  src/DataMigration/DataMigration/ChangeLog.md
  src/DataProtection/ChangeLog.md
  src/Databricks/ChangeLog.md
  src/MobileNetwork/ChangeLog.md
  src/Network/Network/ChangeLog.md
  src/RedisEnterpriseCache/ChangeLog.md
  src/Relay/ChangeLog.md
  src/Resources/Resources/ChangeLog.md
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/Sql/Sql/ChangeLog.md
  src/StackHCI/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
  src/Synapse/Synapse/ChangeLog.md
  src/Websites/Websites/ChangeLog.md
Labels: Waiting for CI :shipit:

#21833 [Az.Functions] Use ARM API to get function app stacks information
  src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json
  src/Functions/custom/FunctionsStack/WindowsFunctionsStacks.json
  src/Functions/custom/FunctionsStack/functionAppStacks.json
  src/Functions/custom/HelperFunctions.ps1
  src/Functions/custom/New-AzFunctionApp.ps1
  src/Functions/custom/api/Support/FunctionsVersionType.cs
  src/Functions/custom/api/Support/RuntimeType.cs
  src/Functions/test/Get-AzFunctionApp.Recording.json
  src/Functions/test/Get-AzFunctionAppAvailableLocation.Recording.json
  src/Functions/test/Get-AzFunctionAppPlan.Recording.json
  src/Functions/test/Get-Update-Remove-AzFunctionAppSetting.Recording.json
  src/Functions/test/Get-Update-Remove-AzFunctionAppSetting.Tests.ps1
  src/Functions/test/New-AzFunctionApp.Recording.json
  src/Functions/test/New-AzFunctionApp.Tests.ps1
  src/Functions/test/New-AzFunctionAppPlan.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.Recording.json
  src/Functions/test/New-Update-Remove-AzFunctionApp.Tests.ps1
  src/Functions/test/New-Update-Remove-AzFunctionAppPlan.Recording.json
  src/Functions/test/Remove-AzFunctionApp.Recording.json
  src/Functions/test/Remove-AzFunctionApp.Tests.ps1
  src/Functions/test/Restart-Start-Stop-AzFunctionApp.Recording.json
  src/Functions/test/env.json
  src/Functions/test/utils.ps1
Labels: Functions

#21855 Fix support of PreferredEnclaveType in Elastic Pool cmdlets for Az.Sql
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/Sql/Sql/help/New-AzSqlElasticPool.md
  src/Sql/Sql/help/Set-AzSqlElasticPool.md
Labels: Waiting for CI :shipit:

#21730 [Az.StorageSync] Remove alias "RegisteredServer" for InputObject parameter of Set-AzStorageSyncServerEndpoint
  src/StorageSync/StorageSync/ChangeLog.md
  src/StorageSync/StorageSync/ServerEndpoint/SetServerEndpointCommand.cs
  src/StorageSync/StorageSync/help/Set-AzStorageSyncServerEndpoint.md
  tools/StaticAnalysis/Exceptions/Az.StorageSync/BreakingChangeIssues.csv
Labels: needs-revision, Breaking Change Release, StorageSync

#21863 Enable empty 'Rule' in ManagedRuleGroupOverride to disable whole ruleset
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayFirewallPolicyManagedRuleGroupOverrideEmptyRule.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/FirewallPolicy/ManagedRules/ManagedRuleSet/ManagedRuleGroupOverride/AzureApplicationGatewayFirewallPolicyManagedRuleGroupOverride.cs
  src/Network/Network/help/New-AzApplicationGatewayFirewallPolicyManagedRuleGroupOverride.md
Labels: Waiting for CI :shipit:

#21282 [KubernetesConfiguration] Update api version 2022 11 01
  src/KubernetesConfiguration/Az.KubernetesConfiguration.psd1
  src/KubernetesConfiguration/README.md
  src/KubernetesConfiguration/custom/Get-AzKubernetesConfigFluxOperationStatus.ps1
  src/KubernetesConfiguration/custom/Get-AzKubernetesConfiguration.ps1
  src/KubernetesConfiguration/custom/Get-AzKubernetesConfigurationFlux.ps1
  src/KubernetesConfiguration/custom/Get-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/custom/New-AzKubernetesConfiguration.ps1
  src/KubernetesConfiguration/custom/New-AzKubernetesConfigurationFlux.ps1
  src/KubernetesConfiguration/custom/New-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/custom/Remove-AzKubernetesConfiguration.ps1
  src/KubernetesConfiguration/custom/Remove-AzKubernetesConfigurationFlux.ps1
  src/KubernetesConfiguration/custom/Remove-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/custom/Update-AzKubernetesConfigurationFlux.ps1
  src/KubernetesConfiguration/custom/Update-AzKubernetesExtension.ps1
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfigFluxOperationStatus.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/Get-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/New-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/New-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/Remove-AzKubernetesExtension.md
  src/KubernetesConfiguration/docs/Update-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/docs/Update-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfigFluxOperationStatus.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/Get-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/New-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/New-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesConfiguration.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/Remove-AzKubernetesExtension.md
  src/KubernetesConfiguration/examples/Update-AzKubernetesConfigurationFlux.md
  src/KubernetesConfiguration/examples/Update-AzKubernetesExtension.md
  src/KubernetesConfiguration/test/AzKubernetesConfiguration.Recording.json
  src/KubernetesConfiguration/test/AzKubernetesConfigurationFlux.Recording.json
  src/KubernetesConfiguration/test/AzKubernetesConfigurationFlux.Tests.ps1
  src/KubernetesConfiguration/test/AzKubernetesExtension.Recording.json
  src/KubernetesConfiguration/test/Get-AzKubernetesConfigFluxOperationStatus.Tests.ps1
  src/KubernetesConfiguration/test/Get-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/Get-AzKubernetesConfigurationFlux.Tests.ps1
  src/KubernetesConfiguration/test/Get-AzKubernetesExtension.Tests.ps1
  src/KubernetesConfiguration/test/New-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/New-AzKubernetesConfigurationFlux.Tests.ps1
  src/KubernetesConfiguration/test/New-AzKubernetesExtension.Tests.ps1
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfiguration.Tests.ps1
  src/KubernetesConfiguration/test/Remove-AzKubernetesConfigurationFlux.Tests.ps1
  src/KubernetesConfiguration/test/Remove-AzKubernetesExtension.Tests.ps1
  src/KubernetesConfiguration/test/Update-AzKubernetesConfigurationFlux.Tests.ps1
  src/KubernetesConfiguration/test/Update-AzKubernetesExtension.Tests.ps1
  src/KubernetesConfiguration/test/env.json
  src/KubernetesConfiguration/test/utils.ps1
  tools/StaticAnalysis/Exceptions/Az.KubernetesConfiguration/ExampleIssues.csv
Labels: needs-review

#21839 {Synapse} Fixed issue for Start-AzSynapseTrigger
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Common/Utils.cs
Labels: Waiting for CI :shipit:

#21893 Fix for OS upgrade Migrate
  src/Migrate/custom/Start-AzMigrateServerMigration.ps1
  src/Migrate/custom/Start-AzMigrateTestMigration.ps1
Labels: customer-reported

#21822 Increasing timeout for PublishAzureWebApp cmdlet
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
Labels: Waiting for CI :shipit:

#21906 Fix iops and high availability parameters
  src/MySql/custom/New-AzMySqlFlexibleServer.ps1
  src/MySql/custom/Update-AzMySqlFlexibleServer.ps1
Labels: needs-review

#21908 Typo "resouce"→"resource"
  src/Cdn/examples/Get-AzFrontDoorCdnRuleSetResourceUsage.md
Labels: customer-reported

#21910 Update ExtendedLocation validation in NewAzureVirtualNetworkGateway
  src/Network/Network/ChangeLog.md
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
Labels: Waiting for CI :shipit:

#21907 [Az.RecoveryServices.Backup] Added malaysia south fix for Cross region restore.
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#21646 Implemented multi-threading for live test
  .azure-pipelines/live-test.yml
  .azure-pipelines/util/live-test-steps.yml
  tools/TestFx/Coverage/SaveTestCoverageResult.ps1
  tools/TestFx/Live/InitializeLiveTestEnvironment.ps1
  tools/TestFx/Live/InstallLiveTestAzModules.ps1
  tools/TestFx/Live/InvokeLiveTestScenarios.ps1
  tools/TestFx/Live/LiveTestUtility.psm1
  tools/TestFx/Live/SaveLiveTestResult.ps1
  tools/TestFx/Live/SendLiveTestReport.ps1
  tools/TestFx/Utilities/KustoUtility.psd1
  tools/TestFx/Utilities/KustoUtility.psm1
Labels: needs-review

#21903 [SQL} Adding None as Valid option for minimal tls version
  src/Sql/Sql.Sdk/Generated/Models/Server.cs
  src/Sql/Sql.Sdk/Generated/Models/ServerUpdate.cs
  src/Sql/Sql.Sdk/README.md
  src/Sql/Sql.Test/ScenarioTests/ServerCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/CreateandUpdateServerWithMinimalTlsVersion.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/help/New-AzSqlServer.md
  src/Sql/Sql/help/Set-AzSqlServer.md
Labels: customer-reported

#21905 [MobileNetwork] Create three cmdlets
  src/MobileNetwork/Az.MobileNetwork.psd1
  src/MobileNetwork/README.md
  src/MobileNetwork/docs/Az.MobileNetwork.md
  src/MobileNetwork/docs/Deploy-AzMobileNetworkReinstallPacketCoreControlPlane.md
  src/MobileNetwork/docs/Deploy-AzMobileNetworkRollbackPacketCoreControlPlane.md
  src/MobileNetwork/docs/Trace-AzMobileNetworkCollectPacketCoreControlPlaneDiagnosticPackage.md
  src/MobileNetwork/examples/Deploy-AzMobileNetworkReinstallPacketCoreControlPlane.md
  src/MobileNetwork/examples/Deploy-AzMobileNetworkRollbackPacketCoreControlPlane.md
  src/MobileNetwork/examples/Trace-AzMobileNetworkCollectPacketCoreControlPlaneDiagnosticPackage.md
  src/MobileNetwork/test/Get-AzMobileNetwork.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkAttachedDataNetwork.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkDataNetwork.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkPacketCoreControlPlane.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkPacketCoreControlPlaneVersion.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkPacketCoreDataPlane.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkService.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkSim.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkSimGroup.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkSimPolicy.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkSite.Tests.ps1
  src/MobileNetwork/test/Get-AzMobileNetworkSlice.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetwork.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkAttachedDataNetwork.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkDataNetwork.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkDataNetworkConfigurationObject.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkPacketCoreControlPlane.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkPacketCoreDataPlane.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkPccRuleConfigurationObject.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkService.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkServiceDataFlowTemplateObject.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkServiceResourceIdObject.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSim.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSimGroup.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSimPolicy.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSimStaticIPPropertiesObject.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSite.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSiteResourceIdObject.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSlice.Tests.ps1
  src/MobileNetwork/test/New-AzMobileNetworkSliceConfigurationObject.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetwork.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkAttachedDataNetwork.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkDataNetwork.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkPacketCoreControlPlane.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkPacketCoreDataPlane.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkService.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkSim.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkSimGroup.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkSimPolicy.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkSite.Tests.ps1
  src/MobileNetwork/test/Remove-AzMobileNetworkSlice.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetwork.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkAttachedDataNetwork.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkDataNetwork.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkPacketCoreControlPlane.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkPacketCoreDataPlane.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkService.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkSimGroup.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkSimPolicy.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkSite.Tests.ps1
  src/MobileNetwork/test/Update-AzMobileNetworkSlice.Tests.ps1
Labels: needs-revision

#21881 Fix the test for hybrid module
  src/Aks/Aks.Autorest/custom/Get-AzAksVersion.ps1
  src/Aks/Aks.Autorest/test/New-AzAksMaintenanceConfiguration.Tests.ps1
  src/Compute/Compute.Autorest/test/Remove-AzVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Remove-AzVmssVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Set-AzVMRunCommand.Tests.ps1
  src/Compute/Compute.Autorest/test/Set-AzVmssVMRunCommand.Tests.ps1
  tools/ExecuteCIStep.ps1
Labels: Compute

#21951 Typo "CosmosDB Account"→"Cosmos DB Account"
  src/CosmosDB/CosmosDB/help/Az.CosmosDB.md
Labels: customer-reported

#21950 Typo "CosmosDB Account"→"Cosmos DB Account"
  src/CosmosDB/CosmosDB/help/Get-AzCosmosDBSqlRoleAssignment.md
Labels: customer-reported

#21923 Add helpful New-AzVmConfig examples
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/help/New-AzVMConfig.md
Labels: Compute

#21945 Fix a few typos in Get-AzMarketplaceTerms.md generation branch
  src/MarketplaceOrdering/docs/Get-AzMarketplaceTerms.md
  src/MarketplaceOrdering/examples/Get-AzMarketplaceTerms.md
Labels: customer-reported
