Repository Azure/azure-powershell, pull requests merged in 2024-07, with the labels that each got.

#25385 [Network] Added changes for Allocate function in Azure Firewall
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAllocateByopipAzureHubFirewall.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestByopipAzureHubFirewall.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
Labels: needs-revision

#25419 [Account] Add breaking change in GetAzureRmAccessToken.cs
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
Labels: Breaking Change Preannounce

#25138 Add label message for "codegen-survey"
  .github/workflows/script/PrLabeled.ps1
Labels: needs-review, codegen-survey

#25428 Fix an issue in PR labeling workflow
  .github/workflows/pr-labeled.yml
Labels: needs-review, codegen-survey

#25453 merge main to release-2024-07-09
  .azure-pipelines/security-tools.yml
  .azure-pipelines/util/live-test-steps.yml
  .azure-pipelines/util/smoke-test-steps.yml
  .github/workflows/pr-labeled.yml
  .github/workflows/script/PrLabeled.ps1
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/RedisCache/RedisCache/help/Get-AzRedisCacheKey.md
  src/RedisCache/RedisCache/help/Import-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCache.md
  src/RedisCache/RedisCache/help/New-AzRedisCacheKey.md
Labels: Do Not Squash :no_entry_sign:

#24880 Enabling GPv2 in powershell
  src/Sql/Sql.Test/ScenarioTests/Common.ps1
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedInstanceCrudScenarioTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestCreateManagedInstanceHermesTesting.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceCrudScenarioTests/TestSetManagedInstanceHermesTesting.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Common/Constants.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/SetAzureSqlManagedInstance.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/help/Get-AzSqlInstance.md
  src/Sql/Sql/help/New-AzSqlInstance.md
  src/Sql/Sql/help/Set-AzSqlInstance.md
  tools/StaticAnalysis/Exceptions/Az.Sql/SignatureIssues.csv
Labels: needs-revision

#25555 Move livetest dir to correct projects
  src/ContainerRegistry/ContainerRegistry.Autorest/LiveTests/TestLiveScenarios.ps1
  src/Resources/Resources.Test/LiveTests/TestLiveScenarios.disabled.ps1
  src/Resources/Resources.Test/LiveTests/msgraphtest2.cer
Labels: needs-review

#25413 [Storage] Upgrade DMlib to 2.0.5 in Az.Storage
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Storage.Management.csproj
  src/Storage/Storage.Test/Storage.Test.csproj
  src/Storage/Storage/Storage.csproj
  src/lib/Microsoft.Azure.Storage.DataMovement.dll
Labels: needs-review

#25493 Update New-AzStorageAccount.md
  src/Storage/Storage.Management/help/New-AzStorageAccount.md
Labels: customer-reported

#25570 [Monitor][Metric] Fix example output don't match actual cmdlet
  src/Monitor/Monitor/help/Get-AzMetric.md
Labels: needs-review

#25583 Upgraded the Communication Service swagger version to 2023-06-01-preview
  src/Communication/Communication.Autorest/.gitignore
  src/Communication/Communication.Autorest/README.md
  src/Communication/Communication.Autorest/UX/Microsoft.Communication/communicationServices.json
  src/Communication/Communication.Autorest/custom/README.md
  src/Communication/Communication.Autorest/docs/Get-AzCommunicationService.md
  src/Communication/Communication.Autorest/docs/Get-AzCommunicationServiceKey.md
  src/Communication/Communication.Autorest/docs/New-AzCommunicationService.md
  src/Communication/Communication.Autorest/docs/New-AzCommunicationServiceKey.md
  src/Communication/Communication.Autorest/docs/README.md
  src/Communication/Communication.Autorest/docs/Remove-AzCommunicationService.md
  src/Communication/Communication.Autorest/docs/Set-AzCommunicationServiceNotificationHub.md
  src/Communication/Communication.Autorest/docs/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/Communication.Autorest/docs/Update-AzCommunicationService.md
  src/Communication/Communication.Autorest/examples/Get-AzCommunicationService.md
  src/Communication/Communication.Autorest/examples/New-AzCommunicationService.md
  src/Communication/Communication.Autorest/examples/Test-AzCommunicationServiceNameAvailability.md
  src/Communication/Communication.Autorest/examples/Update-AzCommunicationService.md
  src/Communication/Communication.Autorest/how-to.md
  src/Communication/Communication.Autorest/test/Get-AzCommunicationService.Recording.json
  src/Communication/Communication.Autorest/test/Get-AzCommunicationServiceKey.Recording.json
  src/Communication/Communication.Autorest/test/New-AzCommunicationService.Recording.json
  src/Communication/Communication.Autorest/test/New-AzCommunicationService.Tests.ps1
  src/Communication/Communication.Autorest/test/New-AzCommunicationServiceKey.Recording.json
  src/Communication/Communication.Autorest/test/Set-AzCommunicationServiceNotificationHub.Recording.json
  src/Communication/Communication.Autorest/test/Test-AzCommunicationServiceNameAvailability.Recording.json
  src/Communication/Communication.Autorest/test/Update-AzCommunicationService.Recording.json
  src/Communication/Communication.Autorest/test/Update-AzCommunicationService.Tests.ps1
  src/Communication/Communication.Autorest/test/env.json
  src/Communication/Communication.Autorest/test/loadEnv.ps1
  src/Communication/Communication.Autorest/test/localEnv.json
  src/Communication/Communication.Autorest/test/utils.ps1
  src/Communication/Communication.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
Labels: customer-reported

#25587 Update Import-AzAutomationRunbook.md
  src/Automation/Automation/help/Import-AzAutomationRunbook.md
Labels: customer-reported

#25613 display login announcements less often
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
Labels: needs-review

#25625 Az.StorageSync : Hot fixes for Aug Release
  src/StorageSync/StorageSync/ChangeLog.md
  src/StorageSync/StorageSync/Common/Converters/StorageSyncServiceConverter.cs
  src/StorageSync/StorageSync/Models/PSStorageSyncService.cs
  src/StorageSync/StorageSync/RegisteredServer/RegisterServerCommand.cs
  src/StorageSync/StorageSync/StorageSyncService/SetStorageSyncServiceIdentityCommand.cs
Labels: StorageSync

#25663 [RecoveryServices.Backup] Added support for enabling Disk access settings for managed VM restores
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: needs-review

#25674 Revert "[RecoveryServices.Backup] Added support for enabling Disk access settings for managed VM restores"
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: needs-review

#25431 Email service data plane operations - Send email and get email send status
  src/Communication/EmailServicedata.Autorest/.gitattributes
  src/Communication/EmailServicedata.Autorest/.gitignore
  src/Communication/EmailServicedata.Autorest/Az.EmailServicedata.psd1
  src/Communication/EmailServicedata.Autorest/README.md
  src/Communication/EmailServicedata.Autorest/custom/README.md
  src/Communication/EmailServicedata.Autorest/docs/Az.EmailServicedata.md
  src/Communication/EmailServicedata.Autorest/docs/Get-AzEmailServicedataEmailSendResult.md
  src/Communication/EmailServicedata.Autorest/docs/README.md
  src/Communication/EmailServicedata.Autorest/docs/Send-AzEmailServicedataEmail.md
  src/Communication/EmailServicedata.Autorest/examples/Get-AzEmailServicedataEmailSendResult.md
  src/Communication/EmailServicedata.Autorest/examples/Send-AzEmailServicedataEmail.md
  src/Communication/EmailServicedata.Autorest/how-to.md
  src/Communication/EmailServicedata.Autorest/license.txt
  src/Communication/EmailServicedata.Autorest/resources/README.md
  src/Communication/EmailServicedata.Autorest/test/Get-AzEmailServicedataEmailSendResult.Recording.json
  src/Communication/EmailServicedata.Autorest/test/Get-AzEmailServicedataEmailSendResult.Tests.ps1
  src/Communication/EmailServicedata.Autorest/test/README.md
  src/Communication/EmailServicedata.Autorest/test/Send-AzEmailServicedataEmail.Recording.json
  src/Communication/EmailServicedata.Autorest/test/Send-AzEmailServicedataEmail.Tests.ps1
  src/Communication/EmailServicedata.Autorest/test/env.json
  src/Communication/EmailServicedata.Autorest/test/loadEnv.ps1
  src/Communication/EmailServicedata.Autorest/test/localEnv.json
  src/Communication/EmailServicedata.Autorest/test/utils.ps1
  src/Communication/EmailServicedata.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/Communication/EmailServicedata.Autorest/utils/Unprotect-SecureString.ps1
Labels: customer-reported
