Repository Azure/azure-powershell, pull requests merged in 2024-05, with the labels that each got.

#24607 opt-in error record config
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Clear-AzConfig.md
  src/Accounts/Accounts/help/Get-AzConfig.md
  src/Accounts/Accounts/help/Update-AzConfig.md
  src/Accounts/Authentication/Config/ConfigInitializer.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
  src/shared/ConfigKeys.cs
  tools/Common.Netcore.Dependencies.targets
  tools/StaticAnalysis/Exceptions/Az.Accounts/BreakingChangeIssues.csv
Labels: Breaking Change Release

#24781 Get-AzVmss bug fix
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetGetMethod.cs
  tools/StaticAnalysis/Exceptions/Az.Compute/BreakingChangeIssues.csv
Labels: Breaking Change Release

#24831 Fix the issue that some placeholder is not valued in gen2main
  src/ConnectedVMware/ConnectedVMware/Az.ConnectedVMware.psd1
  src/ConnectedVMware/ConnectedVMware/ChangeLog.md
  src/EdgeZones/EdgeZones/Az.EdgeZones.psd1
  src/EdgeZones/EdgeZones/ChangeLog.md
  src/EdgeZones/EdgeZones/help/Az.EdgeZones.md
  src/FirmwareAnalysis/FirmwareAnalysis/Az.FirmwareAnalysis.psd1
  src/FirmwareAnalysis/FirmwareAnalysis/ChangeLog.md
  src/Fleet/Fleet/Az.Fleet.psd1
  src/Fleet/Fleet/ChangeLog.md
  src/ManagedNetworkFabric/ManagedNetworkFabric/Az.ManagedNetworkFabric.psd1
  src/ManagedNetworkFabric/ManagedNetworkFabric/ChangeLog.md
  src/Sphere/Sphere/Az.Sphere.psd1
  src/Sphere/Sphere/ChangeLog.md
  src/Sphere/Sphere/help/Az.Sphere.md
  src/StackHCIVM/StackHCIVM/Az.StackHCIVM.psd1
  src/StackHCIVM/StackHCIVM/ChangeLog.md
  src/StandbyPool/StandbyPool/Az.StandbyPool.psd1
  src/StandbyPool/StandbyPool/ChangeLog.md
  src/StandbyPool/StandbyPool/help/Az.StandbyPool.md
  tools/Gen2Master/MoveFromGeneration2Master.ps1
Labels: Waiting for CI :shipit:

#24769 Change pattern for access policy
  src/RedisCache/RedisCache.Management.Sdk/Generated/AccessPolicyOperations.cs
  src/RedisCache/RedisCache.Management.Sdk/Generated/Models/RedisCacheAccessPolicyAssignment.cs
  src/RedisCache/RedisCache.Management.Sdk/Generated/Models/RedisCacheAccessPolicyAssignmentProperties.cs
  src/RedisCache/RedisCache.Management.Sdk/Generated/PrivateEndpointConnectionsOperations.cs
  src/RedisCache/RedisCache.Management.Sdk/Generated/RedisOperations.cs
  src/RedisCache/RedisCache.Management.Sdk/README.md
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache.Test/SessionRecords/Microsoft.Azure.Commands.RedisCache.Test.ScenarioTests.RedisCacheTests/TestMicrosoftEntraAuthCache.json
  src/RedisCache/RedisCache/ChangeLog.md
Labels: Waiting for CI :shipit:

#24800 [Storage] Remove Track1 references from Queue cmdlets
  src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/help/Get-AzStorageQueueStoredAccessPolicy.md
  src/Storage/Storage.Management/help/New-AzStorageQueueSASToken.md
  src/Storage/Storage.Management/help/Set-AzStorageQueueStoredAccessPolicy.md
  src/Storage/Storage.Test/Common/AccessPolicyHelperTest.cs
  src/Storage/Storage.Test/Queue/GetAzureStorageQueueTest.cs
  src/Storage/Storage.Test/Queue/NewAzureStorageQueueTest.cs
  src/Storage/Storage.Test/Queue/RemoveAzureStorageQueueTest.cs
  src/Storage/Storage.Test/Queue/StorageQueueTestBase.cs
  src/Storage/Storage.Test/Service/MockStorageQueueManagement.cs
  src/Storage/Storage/Common/AccessPolicyHelper.cs
  src/Storage/Storage/Common/AzureStorageQueue.cs
  src/Storage/Storage/Common/SasTokenHelper.cs
  src/Storage/Storage/Model/Contract/IStorageQueueManagement.cs
  src/Storage/Storage/Model/Contract/StorageQueueManagement.cs
  src/Storage/Storage/Queue/Cmdlet/GetAzureStorageQueue.cs
  src/Storage/Storage/Queue/Cmdlet/GetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Queue/Cmdlet/NewAzureStorageQueue.cs
  src/Storage/Storage/Queue/Cmdlet/NewAzureStorageQueueSasToken.cs
  src/Storage/Storage/Queue/Cmdlet/SetAzureStorageQueueStoredAccessPolicy.cs
  src/Storage/Storage/Queue/StorageQueueBaseCmdlet.cs
  src/Storage/Storage/Storage.format.ps1xml
  src/Storage/Storage/Storage.generated.format.ps1xml
  tools/StaticAnalysis/Exceptions/Az.Storage/BreakingChangeIssues.csv
Labels: Waiting for CI :shipit:, Breaking Change Release

#24845 [KeyVault] DisableRbacAuthorization for live test
  src/KeyVault/KeyVault.Test/LiveTests/KeyVaultDataPlaneLiveTests/TestNetworkRuleSet.ps1
  src/KeyVault/KeyVault.Test/LiveTests/TestLiveScenarios.ps1
Labels: Waiting for CI :shipit:

#24846 Generating the sdk for network
  src/Network/Network.Management.Sdk/Generated/ApplicationGatewaysOperations.cs
  src/Network/Network.Management.Sdk/Generated/AzureFirewallsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ConfigurationPolicyGroupsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ConnectivityConfigurationsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ExpressRouteCircuitAuthorizationsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ExpressRouteCircuitConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ExpressRouteCircuitsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ExpressRouteConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ExpressRouteCrossConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/ExpressRouteGatewaysOperations.cs
  src/Network/Network.Management.Sdk/Generated/HubRouteTablesOperations.cs
  src/Network/Network.Management.Sdk/Generated/HubVirtualNetworkConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/InboundSecurityRuleOperations.cs
  src/Network/Network.Management.Sdk/Generated/NatRulesOperations.cs
  src/Network/Network.Management.Sdk/Generated/NetworkManagementClient.cs
  src/Network/Network.Management.Sdk/Generated/NetworkSecurityGroupsOperations.cs
  src/Network/Network.Management.Sdk/Generated/NetworkVirtualApplianceConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/NetworkWatchersOperations.cs
  src/Network/Network.Management.Sdk/Generated/P2sVpnGatewaysOperations.cs
  src/Network/Network.Management.Sdk/Generated/PrivateDnsZoneGroupsOperations.cs
  src/Network/Network.Management.Sdk/Generated/PrivateLinkServicesOperations.cs
  src/Network/Network.Management.Sdk/Generated/RoutingIntentOperations.cs
  src/Network/Network.Management.Sdk/Generated/ServiceEndpointPolicyDefinitionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualHubBgpConnectionOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualHubBgpConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualHubIpConfigurationOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualHubRouteTableV2sOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualHubsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualNetworkGatewayConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualNetworkGatewayNatRulesOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualNetworkGatewaysOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualNetworksOperations.cs
  src/Network/Network.Management.Sdk/Generated/VirtualWansOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnGatewaysOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnLinkConnectionsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnServerConfigurationsAssociatedWithVirtualWanOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnServerConfigurationsOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnSitesConfigurationOperations.cs
  src/Network/Network.Management.Sdk/Generated/VpnSitesOperations.cs
Labels: Waiting for CI :shipit:

#24657 IF-Match/IF-NOT-MATCH header support for VMSS creation/update
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetDefaultToFlexibleOrchestrationMode.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetEdgeZone.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSecurityTypeAndFlexDefaults.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSecurityTypeNoVMProfile.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSecurityTypeStandard.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Custom/VirtualMachineExtensions.cs
  src/Compute/Compute/Custom/VirtualMachineScaleSetExtensions.cs
  src/Compute/Compute/Custom/VirtualMachineScaleSetsOperationsExtensions.cs
  src/Compute/Compute/Custom/VirtualMachinesOperationsExtensions.cs
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Models/PSVirtualMachine.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/NewAzureVMConfigCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/Update-AzVM.md
  src/Compute/Compute/help/Update-AzVmss.md
  tools/StaticAnalysis/Exceptions/Az.Compute/ExampleIssues.csv
Labels: Compute

#24828 Change parsing logic in ATC custom cmdlet
  src/NetworkFunction/NetworkFunction.Autorest/custom/New-AzNetworkFunctionCollectorPolicy.ps1
  src/NetworkFunction/NetworkFunction.Autorest/custom/Update-AzNetworkFunctionCollectorPolicy.ps1
  src/NetworkFunction/NetworkFunction.Autorest/test/New-AzNetworkFunctionCollectorPolicy.Tests.ps1
  src/NetworkFunction/NetworkFunction.Autorest/test/Update-AzNetworkFunctionCollectorPolicy.Tests.ps1
Labels: needs-revision

#24653 [Get-AzMetric.md]fix: don't worked example 4
  src/Monitor/Monitor/help/Get-AzMetric.md
Labels: customer-reported, Waiting for Verification :mag:

#24796 [SQL DB] Added parameters to enable Manual Cutover feature for Migration for azure sql Sterling database to azure sql hyperscale db
  src/Sql/Sql.Management.Sdk/Generated/DatabaseOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/DatabaseOperationsExtensions.cs
  src/Sql/Sql.Management.Sdk/Generated/DistributedAvailabilityGroupsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/FailoverGroupsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/IDatabaseOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/InstanceFailoverGroupsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/LedgerDigestUploadsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/ManagedInstanceAzureADOnlyAuthenticationsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/ManagedLedgerDigestUploadsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/Models/DatabaseOperation.cs
  src/Sql/Sql.Management.Sdk/Generated/Models/DatabaseOperationProperties.cs
  src/Sql/Sql.Management.Sdk/Generated/Models/Phase.cs
  src/Sql/Sql.Management.Sdk/Generated/Models/PhaseDetails.cs
  src/Sql/Sql.Management.Sdk/Generated/ReplicationLinksOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/ServerAzureADOnlyAuthenticationsOperations.cs
  src/Sql/Sql.Management.Sdk/Generated/ServerTrustCertificatesOperations.cs
  src/Sql/Sql.Management.Sdk/README.md
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.cs
  src/Sql/Sql.Test/ScenarioTests/DatabaseCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestDataClassificationOnSqlDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestEnableDisableRecommendationsOnSqlDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DataClassificationTests/TestErrorIsThrownWhenInvalidClassificationIsSet.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestCreateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCancelOperation.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithGeoZoneBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithLedgerEnabled.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithSampleName.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseCreateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGet.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithBackupStorageRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseGetWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRemove.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseRename.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateFromSterlingToHyperscaleWithManualCutover.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithMaintenanceConfigurationId.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithPreferredEnclaveType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestDatabaseUpdateWithZoneRedundancyNotSpecified.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestFreeLimitDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestFreeLimitDatabaseUpdateFreeLimitExhaustionBehavior.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestUpdateServerlessDatabase.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseCreate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseCreateWithLicenseType.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdate.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DatabaseCrudTests/TestVcoreDatabaseUpdateWithLicenseType.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Cmdlet/SetAzureSqlDatabase.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseActivityModel.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/help/Get-AzSqlDatabaseActivity.md
  src/Sql/Sql/help/Set-AzSqlDatabase.md
Labels: Waiting for CI :shipit:

#24863 Add JobAttempt to artifactname
  .azure-pipelines/util/analyze-steps.yml
  .azure-pipelines/util/test-steps.yml
Labels: Waiting for CI :shipit:

#24861 Update sdk for flowlog without mi
  src/Network/Network.Management.Sdk/Generated/Models/FlowLog.cs
  src/Network/Network.Management.Sdk/Generated/Models/FlowLogInformation.cs
  src/Network/Network.Management.Sdk/README.md
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:

#24870 GA Az.ResourceGraph
  src/ResourceGraph/ResourceGraph/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: Waiting for CI :shipit:

#24413 Bug fix to allow SharedGalleryImangeId and CommunityGalleryImageId parameters to New-AzVMConfig
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Compute, Waiting for CI :shipit:, customer-reported

#24871 Fix ChangeLogs
  src/Communication/Communication/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/ConnectedMachine/ConnectedMachine/ChangeLog.md
  src/Monitor/Monitor/ChangeLog.md
  src/Quota/Quota/ChangeLog.md
  src/Resources/Resources/ChangeLog.md
  src/Security/Security/ChangeLog.md
  src/Sql/Sql/ChangeLog.md
  src/StackHCIVM/StackHCIVM/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
Labels: Waiting for CI :shipit:

#24872 [Networking] - Add Connection Draining support for load balancer backend address
  src/Network/Network.Test/ScenarioTests/LoadBalancerBackendPoolTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendAddressConfig.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerBackendPoolTests/TestLoadBalancerBackendPoolCreate.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/LoadBalancer/NewAzLoadBalancerBackendAddressConfig.cs
  src/Network/Network/Models/PSLoadBalancerBackendAddress.cs
  src/Network/Network/help/New-AzLoadBalancerBackendAddressConfig.md
Labels: Waiting for CI :shipit:

#24865 Fixed a null reference issue during the process of Get-AzContext -ListAvailable
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Context/GetAzureRMContext.cs
Labels: needs-revision

#24841 [StorageAction] onboard StorageAction with autorest
  src/StorageAction/StorageAction.Autorest/.gitattributes
  src/StorageAction/StorageAction.Autorest/.gitignore
  src/StorageAction/StorageAction.Autorest/Az.StorageAction.psd1
  src/StorageAction/StorageAction.Autorest/README.md
  src/StorageAction/StorageAction.Autorest/UX/Microsoft.StorageActions/storageTasks.json
  src/StorageAction/StorageAction.Autorest/custom/README.md
  src/StorageAction/StorageAction.Autorest/docs/Az.StorageAction.md
  src/StorageAction/StorageAction.Autorest/docs/Get-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/docs/Get-AzStorageActionTaskAssignment.md
  src/StorageAction/StorageAction.Autorest/docs/Get-AzStorageActionTasksReport.md
  src/StorageAction/StorageAction.Autorest/docs/Invoke-AzStorageActionTaskPreviewAction.md
  src/StorageAction/StorageAction.Autorest/docs/New-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/docs/New-AzStorageActionTaskOperationObject.md
  src/StorageAction/StorageAction.Autorest/docs/New-AzStorageActionTaskPreviewBlobPropertiesObject.md
  src/StorageAction/StorageAction.Autorest/docs/New-AzStorageActionTaskPreviewKeyValuePropertiesObject.md
  src/StorageAction/StorageAction.Autorest/docs/README.md
  src/StorageAction/StorageAction.Autorest/docs/Remove-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/docs/Update-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/examples/Get-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/examples/Get-AzStorageActionTaskAssignment.md
  src/StorageAction/StorageAction.Autorest/examples/Get-AzStorageActionTasksReport.md
  src/StorageAction/StorageAction.Autorest/examples/Invoke-AzStorageActionTaskPreviewAction.md
  src/StorageAction/StorageAction.Autorest/examples/New-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/examples/New-AzStorageActionTaskOperationObject.md
  src/StorageAction/StorageAction.Autorest/examples/New-AzStorageActionTaskPreviewBlobPropertiesObject.md
  src/StorageAction/StorageAction.Autorest/examples/New-AzStorageActionTaskPreviewKeyValuePropertiesObject.md
  src/StorageAction/StorageAction.Autorest/examples/Remove-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/examples/Update-AzStorageActionTask.md
  src/StorageAction/StorageAction.Autorest/how-to.md
  src/StorageAction/StorageAction.Autorest/license.txt
  src/StorageAction/StorageAction.Autorest/resources/README.md
  src/StorageAction/StorageAction.Autorest/test/Get-AzStorageActionTask.Recording.json
  src/StorageAction/StorageAction.Autorest/test/Get-AzStorageActionTask.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/Get-AzStorageActionTaskAssignment.Recording.json
  src/StorageAction/StorageAction.Autorest/test/Get-AzStorageActionTaskAssignment.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/Get-AzStorageActionTasksReport.Recording.json
  src/StorageAction/StorageAction.Autorest/test/Get-AzStorageActionTasksReport.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/Invoke-AzStorageActionTaskPreviewAction.Recording.json
  src/StorageAction/StorageAction.Autorest/test/Invoke-AzStorageActionTaskPreviewAction.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/New-AzStorageActionTask.Recording.json
  src/StorageAction/StorageAction.Autorest/test/New-AzStorageActionTask.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/New-AzStorageActionTaskOperationObject.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/New-AzStorageActionTaskPreviewBlobPropertiesObject.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/New-AzStorageActionTaskPreviewKeyValuePropertiesObject.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/README.md
  src/StorageAction/StorageAction.Autorest/test/Remove-AzStorageActionTask.Recording.json
  src/StorageAction/StorageAction.Autorest/test/Remove-AzStorageActionTask.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/Update-AzStorageActionTask.Recording.json
  src/StorageAction/StorageAction.Autorest/test/Update-AzStorageActionTask.Tests.ps1
  src/StorageAction/StorageAction.Autorest/test/env.json
  src/StorageAction/StorageAction.Autorest/test/loadEnv.ps1
  src/StorageAction/StorageAction.Autorest/test/utils.ps1
  src/StorageAction/StorageAction.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/StorageAction/StorageAction.Autorest/utils/Unprotect-SecureString.ps1
Labels: Waiting for CI :shipit:

#24873 Minor changes for interactive subscription selection
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#24770 [custom location] Upgrade managed identity
  src/CustomLocation/CustomLocation.Autorest/README.md
  src/CustomLocation/CustomLocation.Autorest/UX/microsoft.extendedlocation/customlocations.json
  src/CustomLocation/CustomLocation.Autorest/custom/New-AzCustomLocation.ps1
  src/CustomLocation/CustomLocation.Autorest/custom/Update-AzCustomLocation.ps1
  src/CustomLocation/CustomLocation.Autorest/docs/Az.CustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/docs/Find-AzCustomLocationTargetResourceGroup.md
  src/CustomLocation/CustomLocation.Autorest/docs/Get-AzCustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/docs/Get-AzCustomLocationResourceSyncRule.md
  src/CustomLocation/CustomLocation.Autorest/docs/New-AzCustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/docs/New-AzCustomLocationResourceSyncRule.md
  src/CustomLocation/CustomLocation.Autorest/docs/Remove-AzCustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/docs/Remove-AzCustomLocationResourceSyncRule.md
  src/CustomLocation/CustomLocation.Autorest/docs/Update-AzCustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/docs/Update-AzCustomLocationResourceSyncRule.md
  src/CustomLocation/CustomLocation.Autorest/examples/New-AzCustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/examples/Update-AzCustomLocation.md
  src/CustomLocation/CustomLocation.Autorest/test/AzCustomLocation.Recording.json
  src/CustomLocation/CustomLocation.Autorest/test/AzCustomLocationResourceSyncRule.Recording.json
  src/CustomLocation/CustomLocation.Autorest/test/env.json
  src/CustomLocation/CustomLocation.Autorest/test/loadEnv.ps1
  src/CustomLocation/CustomLocation.Autorest/test/utils.ps1
  src/CustomLocation/CustomLocation.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  tools/StaticAnalysis/Exceptions/Az.CustomLocation/ExampleIssues.csv
Labels: needs-review

#24874 Make secrets detection option enabled by default and improve the feature
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Authentication/Config/ConfigInitializer.cs
  src/Accounts/Authentication/Sanitizer/Providers/SanitizerCollectionProvider.cs
  src/Accounts/Authentication/Sanitizer/Providers/SanitizerCustomObjectProvider.cs
  src/Accounts/Authentication/Sanitizer/Providers/SanitizerDictionaryProvider.cs
  src/Accounts/Authentication/Sanitizer/Providers/SanitizerProviderBase.cs
  src/Accounts/Authentication/Sanitizer/Services/DefaultSanitizerService.cs
Labels: Waiting for CI :shipit:

#24893 set minimal version for Az.Sql
  tools/VersionController/MinimalVersion.csv
Labels: Waiting for CI :shipit:

#24807 [KeyVault] Switch the location of skr policy from github to maa endpoint
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Key/AddAzureKeyVaultKey.cs
  src/KeyVault/KeyVault/Models/Client/IKeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/Client/KeyVaultDataServiceClient.cs
  src/KeyVault/KeyVault/Models/Client/VaultManagementClient.cs
  src/KeyVault/KeyVault/Models/KeyVaultCmdletBase.cs
  src/KeyVault/KeyVault/Models/KeyVaultManagementCmdletBase.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/Resources/skr-policy.json
Labels: needs-review, Breaking Change Release

#24773 [PSCmdAssistant] New-AzVM and Vmss default image to Win2022AzureEdition when user explicitly sets SecurityType to Standard
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetDefaultImgWhenStandard.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestVMDefaultsToTrustedLaunchImgWhenStnd.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Common/ConstantStringTypes.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Compute, needs-review, Breaking Change Release

#24887 remove breaking change messages
  src/Accounts/Accounts/Config/ClearConfigCommand.cs
  src/Accounts/Accounts/Config/GetConfigCommand.cs
  src/Accounts/Accounts/Config/UpdateConfigCommand.cs
  src/Batch/Batch/Certificates/GetBatchCertificateCommand.cs
  src/Batch/Batch/Certificates/NewBatchCertificateCommand.cs
  src/Batch/Batch/ChangeLog.md
  src/Compute/Compute/Generated/GalleryImage/GalleryImageCreateOrUpdateMethod.cs
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/CosmosDBAccount/GetAzCosmosDBAccountKey.cs
  src/KeyVault/KeyVault/Commands/Key/AddAzureKeyVaultKey.cs
  src/Sql/Sql/Failover Group/Cmdlet/NewAzureSqlFailoverGroup.cs
  src/Sql/Sql/Failover Group/Cmdlet/SetAzureSqlFailoverGroup.cs
Labels: Waiting for CI :shipit:

#24898 Added support for Inbound Security Rule for Network Virtual Appliance
  src/Network/Network.Test/ScenarioTests/InboundSecurityRuleTests.cs
  src/Network/Network.Test/ScenarioTests/InboundSecurityRuleTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.InboundSecurityRuleTests/TestInboundSecurityRule.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSInboundSecurityRule.cs
  src/Network/Network/Models/PSInboundSecurityRulesProperty.cs
  src/Network/Network/NetworkVirtualAppliance/InboundSecurityRule/NewVirtualApplianceInboundSecurityRulesPropertyCommand.cs
  src/Network/Network/NetworkVirtualAppliance/InboundSecurityRule/UpdateVirtualApplianceInboundSecurityRuleCommand.cs
  src/Network/Network/NetworkVirtualAppliance/InboundSecurityRule/VirtualApplianceInboundSecurityRuleBaseCmdlet.cs
  src/Network/Network/help/New-AzVirtualApplianceInboundSecurityRulesProperty.md
  src/Network/Network/help/Update-AzVirtualApplianceInboundSecurityRule.md
Labels: Network, Waiting for CI :shipit:

#24869 [Breaking Change] Default New-AzGalleryImageDefinition to HyperV Gen2 and Trusted Launch
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.cs
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestGalleryImageDefinitionDefaults.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/GalleryImage/GalleryImageCreateOrUpdateMethod.cs
  src/Compute/Compute/help/New-AzGalleryImageDefinition.md
Labels: Compute, Breaking Change Release

#24866 Added Support for Network Profile in Virtual Appliance
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceTests.ps1
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSNetworkVirtualAppliance.cs
  src/Network/Network/Models/PSVirtualApplianceNetworkProfile.cs
  src/Network/Network/NetworkVirtualAppliance/NetworkProfile/NewVirtualApplianceIpConfigurationCommand.cs
  src/Network/Network/NetworkVirtualAppliance/NetworkProfile/NewVirtualApplianceNetworkInterfaceConfigurationCommand.cs
  src/Network/Network/NetworkVirtualAppliance/NetworkProfile/NewVirtualApplianceNetworkProfileCommand.cs
  src/Network/Network/NetworkVirtualAppliance/NetworkProfile/VirtualApplianceNetworkProfileBaseCmdlet.cs
  src/Network/Network/NetworkVirtualAppliance/NewNetworkVirtualApplianceCommand.cs
  src/Network/Network/help/New-AzNetworkVirtualAppliance.md
  src/Network/Network/help/New-AzVirtualApplianceIpConfiguration.md
  src/Network/Network/help/New-AzVirtualApplianceNetworkInterfaceConfiguration.md
  src/Network/Network/help/New-AzVirtualApplianceNetworkProfile.md
Labels: Network, Waiting for CI :shipit:

#24918 Fix typo
  .ci-config.json
Labels: Waiting for CI :shipit:

#24917 Refine words for login experience
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Accounts/Utilities/InteractiveSubscriptionSelectionHelper.cs
Labels: Waiting for CI :shipit:

#24792 Upgrade Azure.Identity and MSAL versions and WAM
  .azure-pipelines/security-tools.yml
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/AssemblyLoading/ConditionalAssemblyProvider.cs
  src/Accounts/Authentication/Authentication.csproj
  src/Accounts/Authentication/Authentication/TokenCache/AdalTokenMigrator.cs
  src/Accounts/Authentication/Authentication/TokenCache/PowerShellTokenCacheProvider.cs
  src/Accounts/Authentication/Config/Definitions/EnableLoginByWamConfig.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/Authentication/Identity/MsalConfidentialClient.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
  src/Accounts/Authentication/Utilities/AzConfigReader.cs
  src/Accounts/Authenticators/SilentAuthenticator.cs
  src/lib/netstandard2.0/Azure.Core.dll
  src/lib/netstandard2.0/Azure.Identity.Broker.dll
  src/lib/netstandard2.0/Azure.Identity.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.Broker.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.Extensions.Msal.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.NativeInterop.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.dll
  src/lib/netstandard2.0/Microsoft.IdentityModel.Abstractions.dll
  src/lib/netstandard2.0/System.ClientModel.dll
  src/lib/netstandard2.0/msalruntime.dll
  src/lib/netstandard2.0/msalruntime_arm64.dll
  src/lib/netstandard2.0/msalruntime_x86.dll
  tools/Common.Netcore.Dependencies.targets
  tools/StaticAnalysis/DependencyAnalyzer/DependencyAnalyzer.cs
Labels: needs-revision

#24949 Resolve the solution files after final RC
  src/Blueprint/Blueprint.sln
  src/CosmosDB/CosmosDB.sln
  src/MachineLearning/MachineLearning.sln
Labels: needs-review

#24952 Fix minor testfx issues and update doc.
  documentation/testing-docs/using-azure-test-framework.md
  src/Aks/Aks.Test/ScenarioTests/AksTestRunner.cs
  tools/TestFx/DelegatingHandlers/HttpMockServer.cs
  tools/TestFx/TestEnvironment.cs
Labels: Waiting for CI :shipit:

#24957 [NVA] Fix update NVA connection cmdlet
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkVirtualAppliance/Connections/UpdateAzureNetworkVirtualConnectionCommand.cs.cs
Labels: Waiting for CI :shipit:

#24928 Update Update-AzSynapseSparkPool.md
  src/Synapse/Synapse/help/Update-AzSynapseSparkPool.md
Labels: customer-reported

#25026 Email communication service - Added Communication Send Email end points for AAD authentication and updated azure PowerShell common version to 1.3.96-preview in tools
  src/Accounts/Accounts.Test/EnvironmentCmdletTestsExtension.cs
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
  src/Accounts/Accounts/Utilities/SupportedResourceNames.cs
  src/Accounts/Accounts/help/Get-AzAccessToken.md
  tools/Common.Netcore.Dependencies.targets
Labels: customer-reported
