Repository Azure/azure-powershell, pull requests merged in 2024-12, with the labels that each got.

#26788 [Az.RecoveryServices.Backup] Improve Policy Error Code
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/PolicyTests.ps1
Labels: customer-reported

#26844 [Kusto] Fix incorrect examples
  src/Kusto/Kusto.Autorest/docs/Add-AzKustoClusterCalloutPolicy.md
  src/Kusto/Kusto.Autorest/docs/Get-AzKustoClusterCalloutPolicy.md
  src/Kusto/Kusto.Autorest/examples/Get-AzKustoClusterCalloutPolicy.md
Labels: Waiting for CI :shipit:

#26843 Update Restore-AzSqlInstanceDatabase.md
  src/Sql/Sql/help/Restore-AzSqlInstanceDatabase.md
Labels: customer-reported

#26868 [Az.DataProtection] Added support for UAMI in Backup Instance
  src/DataProtection/DataProtection.Autorest/.gitignore
  src/DataProtection/DataProtection.Autorest/Properties/AssemblyInfo.cs
  src/DataProtection/DataProtection.Autorest/README.md
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Initialize-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Update-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Vault/New-AzDataProtectionBackupVault.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Vault/Set-AzDataProtectionMSIPermission.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Vault/Update-AzDataProtectionBackupVault.ps1
  src/DataProtection/DataProtection.Autorest/docs/Initialize-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/docs/New-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/docs/Set-AzDataProtectionMSIPermission.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/examples/Set-AzDataProtectionMSIPermission.md
  src/DataProtection/DataProtection.Autorest/examples/Update-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/examples/Update-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/test/Update-AzDataProtectionBackupInstanceAssociatedPolicy.Recording.json
  src/DataProtection/DataProtection.Autorest/test/Update-AzDataProtectionBackupInstanceAssociatedPolicy.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/env.json
  src/DataProtection/DataProtection.Autorest/test/utils.ps1
Labels: needs-review

#24116 Adding SBM support
  src/Migrate/Migrate.Autorest/custom/Initialize-AzMigrateReplicationInfrastructure.ps1
  src/Migrate/Migrate.Autorest/test/Initialize-AzMigrateReplicationInfrastructure.Tests.ps1
Labels: needs-revision, Waiting for Verification :mag:

#26884 Adding managed identity support to sql import export
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ImportExport/Model/AuthenticationType.cs
  src/Sql/Sql/ImportExport/Model/StorageKeyType.cs
  src/Sql/Sql/help/New-AzSqlDatabaseExport.md
  src/Sql/Sql/help/New-AzSqlDatabaseImport.md
Labels: customer-reported

#26905 Remove GitHub Token From CI Pipeline
  .azure-pipelines/security-tools.yml
  .azure-pipelines/util/build-steps.yml
  .azure-pipelines/util/get-pr-changed-files.yml
  build.proj
  src/Resources/DataBoundary.Autorest/UX/Microsoft.Resources/dataBoundaries.json
  tools/BuildPackagesTask/Microsoft.Azure.Build.Tasks/CIFilterTask.cs
  tools/StaticAnalysis/Exceptions/Az.Resources/UXMetadataIssues.csv
Labels: needs-review

#26945 Fixed the Managed Identity Parameter Set Description of AccountId in Connect-AzAccounts
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/help/Connect-AzAccount.md
Labels: needs-review
