Repository Azure/azure-powershell, pull requests merged in 2024-09, with the labels that each got.

#25976 [CI] Update ESRP Config for Task v5
  .azure-pipelines/daily-build.yml
Labels: needs-review

#25995 [CostManagement] Bug - Invoke-AzCostManagementQuery cmdlet should handle null value in the response rows
  src/CostManagement/CostManagement.Autorest/custom/Invoke-AzCostManagementQuery.ps1
Labels: Waiting for CI :shipit:

#25947 Fix the azstackhcivm update bug
  src/StackHCIVM/StackHCIVM.Autorest/README.md
  src/StackHCIVM/StackHCIVM.Autorest/custom/New-AzStackHCIVMVirtualMachine_New.ps1
  src/StackHCIVM/StackHCIVM.Autorest/custom/README.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/New-AzStackHCIVMVirtualMachine.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/README.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMLogicalNetwork.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMNetworkInterface.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMStoragePath.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMVirtualHardDisk.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/New-AzStackHCIVMVirtualMachine.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/README.md
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMImageNew.Recording.json
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMImageNew.Tests.ps1
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMLogicalNetwork.Recording.json
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMLogicalNetwork.Tests.ps1
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMNetworkInterface.Recording.json
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMNetworkInterface.Tests.ps1
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMStoragePath.Recording.json
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMVirtualHardDisks.Recording.json
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMVirtualMachine.Recording.json
  src/StackHCIVM/StackHCIVM.Autorest/test/AzStackHCIVMVirtualMachine.Tests.ps1
  src/StackHCIVM/StackHCIVM.Autorest/test/README.md
  src/StackHCIVM/StackHCIVM.Autorest/test/env.json
  src/StackHCIVM/StackHCIVM.Autorest/test/envVariables.json
  src/StackHCIVM/StackHCIVM.Autorest/test/loadEnv.ps1
Labels: needs-author-feedback

#25955 Introduce Fabric Az PowerShell
  src/Fabric/Fabric.Autorest/.gitattributes
  src/Fabric/Fabric.Autorest/.gitignore
  src/Fabric/Fabric.Autorest/Az.Fabric.psd1
  src/Fabric/Fabric.Autorest/README.md
  src/Fabric/Fabric.Autorest/UX/Microsoft.Fabric/capacities.json
  src/Fabric/Fabric.Autorest/custom/README.md
  src/Fabric/Fabric.Autorest/docs/Az.Fabric.md
  src/Fabric/Fabric.Autorest/docs/Get-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/docs/Get-AzFabricCapacitySku.md
  src/Fabric/Fabric.Autorest/docs/New-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/docs/README.md
  src/Fabric/Fabric.Autorest/docs/Remove-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/docs/Resume-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/docs/Suspend-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/docs/Test-AzFabricCapacityNameAvailability.md
  src/Fabric/Fabric.Autorest/docs/Update-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/examples/Get-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/examples/Get-AzFabricCapacitySku.md
  src/Fabric/Fabric.Autorest/examples/New-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/examples/Remove-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/examples/Resume-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/examples/Suspend-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/examples/Test-AzFabricCapacityNameAvailability.md
  src/Fabric/Fabric.Autorest/examples/Update-AzFabricCapacity.md
  src/Fabric/Fabric.Autorest/how-to.md
  src/Fabric/Fabric.Autorest/license.txt
  src/Fabric/Fabric.Autorest/resources/README.md
  src/Fabric/Fabric.Autorest/test/Get-AzFabricCapacity.Recording.json
  src/Fabric/Fabric.Autorest/test/Get-AzFabricCapacity.Tests.ps1
  src/Fabric/Fabric.Autorest/test/Get-AzFabricCapacitySku.Recording.json
  src/Fabric/Fabric.Autorest/test/Get-AzFabricCapacitySku.Tests.ps1
  src/Fabric/Fabric.Autorest/test/New-AzFabricCapacity.Recording.json
  src/Fabric/Fabric.Autorest/test/New-AzFabricCapacity.Tests.ps1
  src/Fabric/Fabric.Autorest/test/README.md
  src/Fabric/Fabric.Autorest/test/Remove-AzFabricCapacity.Recording.json
  src/Fabric/Fabric.Autorest/test/Remove-AzFabricCapacity.Tests.ps1
  src/Fabric/Fabric.Autorest/test/Resume-AzFabricCapacity.Recording.json
  src/Fabric/Fabric.Autorest/test/Resume-AzFabricCapacity.Tests.ps1
  src/Fabric/Fabric.Autorest/test/Suspend-AzFabricCapacity.Recording.json
  src/Fabric/Fabric.Autorest/test/Suspend-AzFabricCapacity.Tests.ps1
  src/Fabric/Fabric.Autorest/test/Test-AzFabricCapacityNameAvailability.Recording.json
  src/Fabric/Fabric.Autorest/test/Test-AzFabricCapacityNameAvailability.Tests.ps1
  src/Fabric/Fabric.Autorest/test/Update-AzFabricCapacity.Recording.json
  src/Fabric/Fabric.Autorest/test/Update-AzFabricCapacity.Tests.ps1
  src/Fabric/Fabric.Autorest/test/common.ps1
  src/Fabric/Fabric.Autorest/test/deployment-templates/test-resources.json
  src/Fabric/Fabric.Autorest/test/deployment-templates/test-resources.parameters.json
  src/Fabric/Fabric.Autorest/test/env.json
  src/Fabric/Fabric.Autorest/test/loadEnv.ps1
  src/Fabric/Fabric.Autorest/test/localEnv.json
  src/Fabric/Fabric.Autorest/test/utils.ps1
  src/Fabric/Fabric.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/Fabric/Fabric.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-review

#25980 New VMSS Instance Mix Flex Create and Update Parameters for Powershell
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfile.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Models/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/Manual/PSVirtualMachineScaleSet.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Update-AzVmss.md
Labels: Compute, Waiting for CI :shipit:

#25844 [KeyVault] Handle Nullable Parameters for Certificate Auto-Renewal in Set-AzKeyVaultCertificatePolicy
  src/KeyVault/KeyVault.Test/PesterTests/CertificatePolicy.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Certificate/Policy/SetAzureKeyVaultCertificatePolicy.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/help/Set-AzKeyVaultCertificatePolicy.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review

#26032 Update New-AzKeyVault.md
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
Labels: Waiting for CI :shipit:, customer-reported

#25623 [Bastion] Add support for Bastion shareable links
  src/Network/Network.Test/ScenarioTests/BastionTests.cs
  src/Network/Network.Test/ScenarioTests/BastionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionShareableLink.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/Bastion/Constants.cs
  src/Network/Network/Bastion/ShareableLink/GetAzBastionShareableLinkCommand.cs
  src/Network/Network/Bastion/ShareableLink/NewAzBastionShareableLinkCommand.cs
  src/Network/Network/Bastion/ShareableLink/RemoveAzBastionShareableLinkCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/Bastion/ShareableLink/PSBastionShareableLink.cs
  src/Network/Network/Models/Bastion/ShareableLink/PSBastionShareableLinkRequest.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/Get-AzBastionShareableLink.md
  src/Network/Network/help/New-AzBastionShareableLink.md
  src/Network/Network/help/Remove-AzBastionShareableLink.md
Labels: Waiting for CI :shipit:

#26039 Onboard Microsoft.VideoIndexer/accounts to private link cmdlets
  src/Network/Network/ChangeLog.md
  src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs
Labels: needs-team-attention

#26054 [CI] Run external CredScan in Security tools pipeline
  .azure-pipelines/security-tools.yml
Labels: needs-review

#25992 [eng] Remove changed modules from minimalVersion.csv only
  tools/VersionController/Program.cs
Labels: Waiting for CI :shipit:

#26087 Resolve Conflict Network Change Log
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:

#26075 Add destination IP address as parameter for PLS
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSPrivateLinkService.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/PrivateLinkService/NewAzurePrivateLinkServiceCommand.cs
  src/Network/Network/help/New-AzPrivateLinkService.md
Labels: Waiting for CI :shipit:

#25901 Powershell release StandbyPool 2024-03-01
  src/StandbyPool/StandbyPool.Autorest/Az.StandbyPool.psd1
  src/StandbyPool/StandbyPool.Autorest/README.md
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyContainerGroupPools-runtimeViews.json
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyContainerGroupPools.json
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyVirtualMachinePools-runtimeViews.json
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyVirtualMachinePools.json
  src/StandbyPool/StandbyPool.Autorest/docs/Az.StandbyPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyContainerGroupPoolStatus.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyVMPoolStatus.md
  src/StandbyPool/StandbyPool.Autorest/docs/New-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/New-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Remove-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Update-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Update-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyContainerGroupPoolStatus.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyVMPoolStatus.md
  src/StandbyPool/StandbyPool.Autorest/examples/New-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Update-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyContainerPool.Recording.json
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyContainerPool.Tests.ps1
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyVMPool.Recording.json
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyVMPool.Tests.ps1
  src/StandbyPool/StandbyPool.Autorest/test/env.json
  src/StandbyPool/StandbyPool.Autorest/test/loadEnv.ps1
  src/StandbyPool/StandbyPool.Autorest/test/localEnv.json
  tools/StaticAnalysis/Exceptions/Az.StandbyPool/UXMetadataIssues.csv
Labels: needs-revision, needs-team-attention

#26109 Update Test Templates
  src/ServiceFabric/ServiceFabric.Test/Resources/parameters.json
  src/ServiceFabric/ServiceFabric.Test/Resources/parametersCNCert.json
  src/ServiceFabric/ServiceFabric.Test/Resources/template.json
  src/ServiceFabric/ServiceFabric.Test/Resources/templateCNCert.json
Labels: Waiting for CI :shipit:

#26084 [Marketplace] Remove Microsoft.Azure.Management.Marketplace 1.1.0 dependencies on released track 1 SDK
  src/Marketplace/Marketplace.Management.Sdk/Generated/IMarketplaceManagementClient.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/IOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/IPrivateStoreOfferOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/IPrivateStoreOffersOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/IPrivateStoreOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/IPrivateStorePrivateOfferOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/IPrivateStorePrivateOffersOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/MarketplaceManagementClient.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/Availability.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/ErrorResponse.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/ErrorResponseError.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/ErrorResponseException.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/Offer.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/OfferProperties.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/Operation.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/OperationDisplay.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/OperationListResult.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/Page.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/Plan.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/PrivateStore.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/PrivateStoreProperties.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Models/Resource.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/Operations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/OperationsExtensions.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStoreOfferOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStoreOfferOperationsExtensions.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStoreOffersOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStoreOffersOperationsExtensions.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStoreOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStoreOperationsExtensions.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStorePrivateOfferOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStorePrivateOfferOperationsExtensions.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStorePrivateOffersOperations.cs
  src/Marketplace/Marketplace.Management.Sdk/Generated/PrivateStorePrivateOffersOperationsExtensions.cs
  src/Marketplace/Marketplace.Management.Sdk/Marketplace.Management.Sdk.csproj
  src/Marketplace/Marketplace.Management.Sdk/Properties/Assemblyinfo.cs
  src/Marketplace/Marketplace.Management.Sdk/README.md
  src/Marketplace/Marketplace.Test/Marketplace.Test.csproj
  src/Marketplace/Marketplace.sln
  src/Marketplace/Marketplace/Az.Marketplace.psd1
  src/Marketplace/Marketplace/ChangeLog.md
  src/Marketplace/Marketplace/Cmdlets/SetAzMarketplacePrivateStoreOffer.cs
  src/Marketplace/Marketplace/Marketplace.csproj
Labels: needs-review

#26127 Re-merge Workload Identity Federation (WIF) changes
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/custom/Az.ConnectedKubernetes.custom.psm1
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/custom/New-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/custom/README.md
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/custom/Set-AzConnectedKubernetes.ps1
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/docs/New-AzConnectedKubernetes.md
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/docs/README.md
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/docs/Set-AzConnectedKubernetes.md
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/resources/README.md
  src/ConnectedKubernetes/ConnectedKubernetes.Autorest/test/README.md
Labels: needs-revision

#26121 [Billing] Re-name about Get-UsageAggregates and added alias
  src/Billing/Billing/Az.Billing.psd1
  src/Billing/Billing/ChangeLog.md
  src/Billing/Billing/help/Az.Billing.md
  src/Billing/Billing/help/Get-AzUsageAggregate.md
  src/Billing/UsageAggregates.Test/ScenarioTests/UsageAggregatesTests.cs
  src/Billing/UsageAggregates.Test/ScenarioTests/UsageAggregatesTests.ps1
  src/Billing/UsageAggregates/GetAzureRmUsageAggregateCommand.cs
Labels: Waiting for CI :shipit:

#26070 [DataFactory]Support New Features In ADF
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/IcebergDataset.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/IcebergDatasetTypeProperties.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/IcebergSink.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/IcebergWriteSettings.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/MariaDBLinkedService.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/MariaDBLinkedServiceTypeProperties.cs
  src/DataFactory/DataFactory.Management.Sdk/README.md
  src/DataFactory/DataFactory/ChangeLog.md
Labels: needs-revision, needs-team-attention

#26065 Update New-AzApplicationInsightsWebTest.md
  src/ApplicationInsights/ApplicationInsights/help/New-AzApplicationInsightsWebTest.md
Labels: Waiting for CI :shipit:

#26135 [HDInsight] Fix a bug
  src/HDInsight/HDInsight/ChangeLog.md
  src/HDInsight/HDInsight/ManagementCommands/NewAzureHDInsightClusterCommand.cs
  src/HDInsight/HDInsight/help/New-AzHDInsightCluster.md
Labels: Waiting for CI :shipit:

#26147 Fixing bug for replication to Managed disk for HyperV to Azure scenario in Azure site recovery service
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/CreateRPIWithMangedDisksForReplication.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/NewAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrReplicationProtectedItem.md
Labels: needs-review

#26112 Update Get-AzStorageBlob.md
  src/Storage/Storage.Management/help/Get-AzStorageBlob.md
Labels: Waiting for CI :shipit:

#26167 Fix bug in `Publish-AzWebApp` to allow params to be toggled off
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
  tools/SecurityTools/CredScanSuppressions.json
Labels: Waiting for CI :shipit:, Do Not Squash :no_entry_sign:
