Repository Azure/azure-powershell, pull requests merged in 2024-08, with the labels that each got.

#25728 Generate Defender for Storage V2 cmdlets
  src/Security/DefenderForStorage.Autorest/.gitattributes
  src/Security/DefenderForStorage.Autorest/.gitignore
  src/Security/DefenderForStorage.Autorest/Az.DefenderForStorage.psd1
  src/Security/DefenderForStorage.Autorest/README.md
  src/Security/DefenderForStorage.Autorest/UX/Microsoft.Security/defenderForStorageSettings.json
  src/Security/DefenderForStorage.Autorest/custom/README.md
  src/Security/DefenderForStorage.Autorest/docs/Az.DefenderForStorage.md
  src/Security/DefenderForStorage.Autorest/docs/Get-AzSecurityDefenderForStorage.md
  src/Security/DefenderForStorage.Autorest/docs/README.md
  src/Security/DefenderForStorage.Autorest/docs/Update-AzSecurityDefenderForStorage.md
  src/Security/DefenderForStorage.Autorest/examples/Get-AzSecurityDefenderForStorage.md
  src/Security/DefenderForStorage.Autorest/examples/Update-AzSecurityDefenderForStorage.md
  src/Security/DefenderForStorage.Autorest/how-to.md
  src/Security/DefenderForStorage.Autorest/license.txt
  src/Security/DefenderForStorage.Autorest/resources/README.md
  src/Security/DefenderForStorage.Autorest/test/Get-AzSecurityDefenderForStorage.Recording.json
  src/Security/DefenderForStorage.Autorest/test/Get-AzSecurityDefenderForStorage.Tests.ps1
  src/Security/DefenderForStorage.Autorest/test/README.md
  src/Security/DefenderForStorage.Autorest/test/Update-AzSecurityDefenderForStorage.Recording.json
  src/Security/DefenderForStorage.Autorest/test/Update-AzSecurityDefenderForStorage.Tests.ps1
  src/Security/DefenderForStorage.Autorest/test/deploymentTemplates/parameters.json
  src/Security/DefenderForStorage.Autorest/test/deploymentTemplates/template.json
  src/Security/DefenderForStorage.Autorest/test/env.json
  src/Security/DefenderForStorage.Autorest/test/loadEnv.ps1
  src/Security/DefenderForStorage.Autorest/test/localEnv.json
  src/Security/DefenderForStorage.Autorest/test/utils.ps1
  src/Security/DefenderForStorage.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/Security/DefenderForStorage.Autorest/utils/Unprotect-SecureString.ps1
  tools/StaticAnalysis/Exceptions/Az.Security/UXMetadataIssues.csv
Labels: needs-revision

#25835 adding missing Name flag - line 29
  src/Network/Network/help/Set-AzPrivateLinkService.md
Labels: customer-reported

#25816 [NetAppFiles] Bug Fix adding EncryptionType to Get-AzNetAppFilesPool
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/ModelExtensions.cs
Labels: customer-reported

#25837 [NetAppFiles] Add missing parameter SnapshotName
  src/NetAppFiles/NetAppFiles/Backups/NewNetAppFilesBackup.cs
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/BackupExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesBackup.cs
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesBackup.md
Labels: customer-reported

#25886 Update Get-AzConfigurationAssignment.md to include Guest scope examples
  src/Maintenance/Maintenance/help/Get-AzConfigurationAssignment.md
Labels: customer-reported

#25888 fixing packet capture call to be async
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestInvokeAzureFirewallPacketCapture.json
  src/Network/Network/AzureFirewall/InvokeAzureFirewallPacketCaptureCommand.cs
  src/Network/Network/ChangeLog.md
Labels: needs-review, Network - Firewall

#25931 added CMK migration changes
  src/RecoveryServices/RecoveryServices.Backup.Models/VaultModels/VaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRSVaultCMK.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVaultSoftDelete.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/GetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVault.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
Labels: needs-review

#25939 minor fix MUAEncryption settings
  src/RecoveryServices/RecoveryServices.Backup.ServiceClientAdapter/BMSAPIs/VaultAPIs.cs
Labels: needs-review

#25954 [Storage] Refine track2 OAuth context logic
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage.Management/Common/LazyAzureStorageContext.cs
Labels: Waiting for CI :shipit:
