Repository Azure/azure-powershell, pull requests merged in 2024-01, with the labels that each got.

#23695 [Azure Monitor] Metrics Data Plane API 2023-10-01
  src/Monitor/Metrics.Autorest/.gitattributes
  src/Monitor/Metrics.Autorest/.gitignore
  src/Monitor/Metrics.Autorest/Az.Metric.psd1
  src/Monitor/Metrics.Autorest/README.md
  src/Monitor/Metrics.Autorest/custom/README.md
  src/Monitor/Metrics.Autorest/docs/Az.Metric.md
  src/Monitor/Metrics.Autorest/docs/Get-AzMetricsBatch.md
  src/Monitor/Metrics.Autorest/docs/README.md
  src/Monitor/Metrics.Autorest/examples/Get-AzMetricsBatch.md
  src/Monitor/Metrics.Autorest/how-to.md
  src/Monitor/Metrics.Autorest/license.txt
  src/Monitor/Metrics.Autorest/resources/README.md
  src/Monitor/Metrics.Autorest/test/Get-AzMetricsBatch.Recording.json
  src/Monitor/Metrics.Autorest/test/Get-AzMetricsBatch.Tests.ps1
  src/Monitor/Metrics.Autorest/test/README.md
  src/Monitor/Metrics.Autorest/test/env.json
  src/Monitor/Metrics.Autorest/test/loadEnv.ps1
  src/Monitor/Metrics.Autorest/test/utils.ps1
  src/Monitor/Metrics.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-review

#23811 [NVA] Update NVA connection cmdlet
  src/Accounts/Accounts/Utilities/CommandMappings.json
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceConnectionTests.cs
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceConnectionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkVirtualApplianceConnectionTests/TestNetworkVirtualApplianceConnectionUpdate.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/NetworkVirtualAppliance/Connections/UpdateAzureNetworkVirtualConnectionCommand.cs.cs
  src/Network/Network/NetworkVirtualAppliance/Connections/VirtualConnectionBaseCmdlet.cs
  src/Network/Network/NetworkVirtualAppliance/NetworkVirtualApplianceBaseCmdlet.cs
  src/Network/Network/help/Update-AzNetworkVirtualApplianceConnection.md
Labels: needs-review

#23888 Fixed Ambiguous Positional Argument for
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
  src/Websites/Websites/help/New-AzWebAppSlot.md
  tools/StaticAnalysis/Exceptions/Az.Websites/BreakingChangeIssues.csv
Labels: App Services, Breaking Change Release, customer-reported

#23861 [Az.RecoveryServices.Backup] Minor fixes
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Providers/AzureWorkloadProviderHelper.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/UnregisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Models/RSBackupVaultAADCreds.cs
  src/RecoveryServices/RecoveryServices/Vault/GetAzureRMRecoveryServicesVaultSettingsFile.cs
  src/RecoveryServices/RecoveryServices/help/Unregister-AzRecoveryServicesBackupContainer.md
Labels: needs-review

#23923 [SQL] Added Breaking change messages
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Failover Group/Cmdlet/NewAzureSqlFailoverGroup.cs
  src/Sql/Sql/Failover Group/Cmdlet/SetAzureSqlFailoverGroup.cs
Labels: Breaking Change Preannounce

#23916 [Az.KeyVault] User mi support for backup/restore hsm
  src/KeyVault/KeyVault.Test/PesterTests/ManagedHsmDataPlaneTests.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/FullBackupRestore/BackupAzureManagedHsm.cs
  src/KeyVault/KeyVault/Commands/FullBackupRestore/FullBackupRestoreCmdletBase.cs
  src/KeyVault/KeyVault/Commands/FullBackupRestore/RestoreAzureManagedHsm.cs
  src/KeyVault/KeyVault/KeyVault.csproj
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
  src/KeyVault/KeyVault/help/Backup-AzKeyVault.md
  src/KeyVault/KeyVault/help/Restore-AzKeyVault.md
Labels: needs-review

#23959 Changed the group way from TenantId to TenantName+Id for `Get-AzContext`
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.cs
  src/Accounts/Accounts.Test/SubscriptionCmdletTests.ps1
  src/Accounts/Accounts.Test/TenantCmdletMockTests.cs
  src/Accounts/Accounts.Test/TenantCmdletTests.cs
  src/Accounts/Accounts/Accounts.generated.format.ps1xml
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Authentication.ResourceManager/Models/PSAzureContext.cs
Labels: needs-review

#23986 Update Unregister-AzAutomationDscNode.md
  src/Automation/Automation/help/Unregister-AzAutomationDscNode.md
Labels: Automation, Doc - Reference

#24011 [Az.RecoveryServices.Backup] Added TWN/TNW region support for Cross Region Restore
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review

#23997 Use --stdout flag for bicep build
  src/Resources/ResourceManager/Components/TemplateSpecPackagingEngine.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentCmdletBase.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentStacksCmdletBase.cs
  src/Resources/ResourceManager/Implementation/CmdletBase/DeploymentStacksCreateCmdletBase.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/NewAzManagementGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/NewAzResourceGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/NewAzSubscriptionDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SetAzManagmentGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SetAzResourceGroupDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/DeploymentStacks/SetAzSubscriptionDeploymentStack.cs
  src/Resources/ResourceManager/Implementation/TemplateSpecs/NewAzTemplateSpec.cs
  src/Resources/ResourceManager/Implementation/TemplateSpecs/SetAzTemplateSpec.cs
  src/Resources/ResourceManager/Utilities/BicepUtility.cs
  src/Resources/Resources.Test/UnitTests/Utilities/BicepUtilityTests.cs
  src/Resources/Resources/ChangeLog.md
Labels: needs-revision

#24003 Adding support for AzureFirewallPacketCapture in powershell
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestInvokeAzureFirewallPacketCapture.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/AzureFirewall/AzureFirewallBaseCmdlet.cs
  src/Network/Network/AzureFirewall/GetAzureFirewallCommand.cs
  src/Network/Network/AzureFirewall/InvokeAzureFirewallPacketCaptureCommand.cs
  src/Network/Network/AzureFirewall/PacketCaptureParameter/NewAzureFirewallPacketCaptureParameterCommand.cs
  src/Network/Network/AzureFirewall/PacketCaptureRule/NewAzureFirewallPacketCaptureRuleCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallPacketCaptureFlags.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallPacketCaptureParameters.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallPacketCaptureRule.cs
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/Invoke-AzFirewallPacketCapture.md
  src/Network/Network/help/New-AzFirewallPacketCaptureParameter.md
  src/Network/Network/help/New-AzFirewallPacketCaptureRule.md
Labels: needs-revision

#23914 [SQL] Add managed instances external governance status update
  src/Sql/Sql.Test/ScenarioTests/RefreshSqlInstanceExternalGovernanceCmdletTests.cs
  src/Sql/Sql.Test/ScenarioTests/RefreshSqlInstanceExternalGovernanceCmdletTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.RefreshSqlInstanceExternalGovernanceCmdletTests/TestSqlInstanceRefreshExternalGovernanceCmdlet.json
  src/Sql/Sql/Az.Sql.psd1
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedInstance/Cmdlet/AzureSqlInstanceRefreshExternalGovernanceCmdletBase.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/InvokeAzSqlInstanceExternalGovernanceStatusRefresh.cs
  src/Sql/Sql/ManagedInstance/Model/AzureSqlManagedInstanceModel.cs
  src/Sql/Sql/ManagedInstance/Model/RefreshExternalGovernanceMIModel.cs
  src/Sql/Sql/ManagedInstance/Services/AzureSqlManagedInstanceAdapter.cs
  src/Sql/Sql/ManagedInstance/Services/RefreshExternalGovernanceAdapter.cs
  src/Sql/Sql/ManagedInstance/Services/RefreshExternalGovernanceCommunicator.cs
  src/Sql/Sql/help/Invoke-AzSqlInstanceExternalGovernanceStatusRefresh.md
Labels: needs-review, ready to review

#24040 Upgrade System.Net.Http.WinHttpHandler from 4.0.2.0 to 4.0.4.0
  src/Accounts/AssemblyLoading/ConditionalAssemblyProvider.cs
  src/lib/netstandard2.0/System.Net.Http.WinHttpHandler.dll
Labels: needs-review

#24026 Az.StackHCI OOB Release - Jan 25
  src/StackHCI/StackHCI.Autorest/custom/stackhci.ps1
  src/StackHCI/StackHCI.Autorest/docs/Unregister-AzStackHCI.md
Labels: Do Not Merge :no_entry_sign:

#24041 Fix exception in Get-AzResource with ApiVersion
  src/Resources/ResourceManager/SdkModels/Resources/PSResource.cs
  src/Resources/Resources/ChangeLog.md
Labels: customer-reported

#23665 [Account]Redirect DeviceCode Info from warning stream to information stream in `Connect-AzAccount`
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Properties/Resources.Designer.cs
  src/Accounts/Accounts/Properties/Resources.resx
  src/Accounts/Authenticators/DeviceCodeAuthenticator.cs
Labels: Waiting for CI :shipit:

#24068 Implemention of aux tenant parameter in New-AzResourceGroupDeployment.
  src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCmdlet.cs
  src/Resources/ResourceManager/SdkClient/NewResourceManagerSdkClient.cs
  src/Resources/ResourceManager/SdkModels/Deployments/PSDeploymentCmdletParameters.cs
  src/Resources/Resources.sln
Labels: Do Not Merge :no_entry_sign:
