Repository Azure/azure-powershell, pull requests merged in 2024-10, with the labels that each got.

#26179 Email communication services - data plane - added new feature - inline attachment while sending an email.
  src/Communication/EmailServicedata.Autorest/README.md
  src/Communication/EmailServicedata.Autorest/docs/Send-AzEmailServicedataEmail.md
  src/Communication/EmailServicedata.Autorest/examples/Send-AzEmailServicedataEmail.md
  src/Communication/EmailServicedata.Autorest/test/Get-AzEmailServicedataEmailSendResult.Recording.json
  src/Communication/EmailServicedata.Autorest/test/Send-AzEmailServicedataEmail.Recording.json
  src/Communication/EmailServicedata.Autorest/test/Send-AzEmailServicedataEmail.Tests.ps1
  src/Communication/EmailServicedata.Autorest/test/env.json
  src/Communication/EmailServicedata.Autorest/test/inline-attachment.jpg
  src/Communication/EmailServicedata.Autorest/test/localEnv.json
Labels: customer-reported

#26198 To deprecate alias 'Resolve-Error'
  documentation/breaking-changes/upcoming-breaking-changes.md
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Errors/ResolveError.cs
Labels: needs-review, Breaking Change Preannounce

#26259 Update New-AzGalleryImageVersion.md
  src/Compute/Compute/help/New-AzGalleryImageVersion.md
Labels: Waiting for CI :shipit:, customer-reported

#26193 [AnalysisService] Remove Microsoft.Azure.Management.Analysis and add AnalysisService.Management.Sdk
  src/AnalysisServices/AnalysisService.Management.Sdk/AnalysisService.Management.Sdk.csproj
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/AnalysisServicesManagementClient.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/IAnalysisServicesManagementClient.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/IOperations.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/IServersOperations.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/AnalysisServicesServer.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/AnalysisServicesServerMutableProperties.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/AnalysisServicesServerProperties.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/AnalysisServicesServerUpdateParameters.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/CheckServerNameAvailabilityParameters.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/CheckServerNameAvailabilityResult.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/ConnectionMode.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/ErrorResponse.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/ErrorResponseException.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/GatewayDetails.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/GatewayError.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/GatewayListStatusError.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/GatewayListStatusErrorException.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/GatewayListStatusLive.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/IPv4FirewallRule.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/IPv4FirewallSettings.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/Operation.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/OperationDisplay.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/OperationStatus.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/Page.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/Page1.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/ProvisioningState.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/Resource.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/ResourceSku.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/ServerAdministrators.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/SkuDetailsForExistingResource.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/SkuEnumerationForExistingResourceResult.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/SkuEnumerationForNewResourceResult.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/SkuTier.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/State.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Models/Status.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/Operations.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/OperationsExtensions.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/ServersOperations.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Generated/ServersOperationsExtensions.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/Properties/AssemblyInfo.cs
  src/AnalysisServices/AnalysisService.Management.Sdk/README.md
  src/AnalysisServices/AnalysisServices.Test/AnalysisServices.Test.csproj
  src/AnalysisServices/AnalysisServices.Test/ScenarioTests/AsTests.ps1
  src/AnalysisServices/AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServer.json
  src/AnalysisServices/AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerFirewall.json
  src/AnalysisServices/AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerScaleOutIn.json
  src/AnalysisServices/AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestAnalysisServicesServerScaleUpDown.json
  src/AnalysisServices/AnalysisServices.Test/SessionRecords/Microsoft.Azure.Commands.AnalysisServices.Test.ScenarioTests.AsTests/TestNegativeAnalysisServicesServer.json
  src/AnalysisServices/AnalysisServices.sln
  src/AnalysisServices/AnalysisServices/AnalysisServices.csproj
  src/AnalysisServices/AnalysisServices/Az.AnalysisServices.psd1
  src/AnalysisServices/AnalysisServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#26261 Fix CustomPrinter Test Case Failure in MacOs for Monitor
  src/Monitor/Monitor.Test/CustomPrinterTests.cs
  src/Monitor/Monitor/OutputClasses/CustomPrinter.cs
Labels: needs-review

#26091 Add PrivateEndpointVNetPolicies parameter
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkPrivateEndpointVNetPolicies.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSVirtualNetwork.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/VirtualNetwork/NewAzureVirtualNetworkCommand.cs
  src/Network/Network/help/New-AzVirtualNetwork.md
Labels: Waiting for CI :shipit:

#26290 VMSS Instance Mix Flex Update Bug Fix
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfile.json
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
Labels: Compute, needs-revision

#26249 Alecb/generation api upgrade preannounce
  documentation/breaking-changes/upcoming-breaking-changes.md
  src/DesktopVirtualization/DesktopVirtualization.Autorest/README.md
Labels: needs-review, Breaking Change Preannounce

#26425 Skip the Test Cases Which Fail Because of DateTime.String() Output on MacOS
  .azure-pipelines/powershell-core.yml
  src/CosmosDB/CosmosDB.Test/ScenarioTests/RestoreTests.cs
  src/CosmosDB/CosmosDB.Test/ScenarioTests/TableOperationsTests.cs
Labels: needs-review

#26269 Preannouncement of DesktopVirtualization Upcoming Breaking Changes
  documentation/breaking-changes/upcoming-breaking-changes-desktopvirtualization.md
Labels: Breaking Change Preannounce

#26194 [Attestation] Remove Microsoft.Azure.Management.Attestation and add Attestation.Management.Sdk generated by autorest powershell
  src/Attestation/Attestation.Management.Sdk/Attestation.Management.Sdk.csproj
  src/Attestation/Attestation.Management.Sdk/Generated/AttestationManagementClient.cs
  src/Attestation/Attestation.Management.Sdk/Generated/AttestationProvidersOperations.cs
  src/Attestation/Attestation.Management.Sdk/Generated/AttestationProvidersOperationsExtensions.cs
  src/Attestation/Attestation.Management.Sdk/Generated/IAttestationManagementClient.cs
  src/Attestation/Attestation.Management.Sdk/Generated/IAttestationProvidersOperations.cs
  src/Attestation/Attestation.Management.Sdk/Generated/IOperations.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/AttestationProvider.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/AttestationProviderListResult.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/AttestationServiceCreationParams.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/AttestationServiceCreationSpecificParams.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/AttestationServicePatchParams.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/AttestationServiceStatus.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/JSONWebKey.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/JSONWebKeySet.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/OperationList.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/OperationsDefinition.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/OperationsDisplayDefinition.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/Resource.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/StatusResult.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Models/TrackedResource.cs
  src/Attestation/Attestation.Management.Sdk/Generated/Operations.cs
  src/Attestation/Attestation.Management.Sdk/Generated/OperationsExtensions.cs
  src/Attestation/Attestation.Management.Sdk/Properties/AssemblyInfo.cs
  src/Attestation/Attestation.Management.Sdk/README.md
  src/Attestation/Attestation.Test/Attestation.Test.csproj
  src/Attestation/Attestation.sln
  src/Attestation/Attestation/Attestation.csproj
  src/Attestation/Attestation/Az.Attestation.psd1
  src/Attestation/Attestation/ChangeLog.md
Labels: Waiting for CI :shipit:, needs-review

#26449 Use the real release date for breaking change notification
  src/DesktopVirtualization/DesktopVirtualization.Autorest/README.md
Labels: Waiting for CI :shipit:

#26185 Update New-AzSentinelAlertRule.md
  src/SecurityInsights/SecurityInsights/help/New-AzSentinelAlertRule.md
Labels: Waiting for CI :shipit:

#26473 made note to address a limitation on AppGW PowerShell
  src/Network/Network/help/New-AzApplicationGateway.md
Labels: Waiting for CI :shipit:, customer-reported

#26500 revert relative changes about Azure.core
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Directory.Build.targets
  src/Accounts/AssemblyLoading/ConditionalAssemblyProvider.cs
  src/Accounts/Authentication/Authentication.csproj
  src/CodeSigning/CodeSigning/ChangeLog.md
  src/Compute/Compute/ChangeLog.md
  src/ContainerRegistry/ContainerRegistry/ChangeLog.md
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/KeyVault/KeyVault/ChangeLog.md
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/PolicyInsights/PolicyInsights/ChangeLog.md
  src/Storage/Storage.Management/ChangeLog.md
  src/Synapse/Synapse/ChangeLog.md
  src/lib/netfx/System.Text.Encodings.Web.dll
  src/lib/netstandard2.0/Azure.Core.dll
  src/lib/netstandard2.0/Azure.Identity.dll
  src/lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll
  src/lib/netstandard2.0/System.Buffers.dll
  src/lib/netstandard2.0/System.ClientModel.dll
  src/lib/netstandard2.0/System.Memory.Data.dll
  src/lib/netstandard2.0/System.Memory.dll
  src/lib/netstandard2.0/System.Text.Json.dll
  tools/Common.Netcore.Dependencies.targets
Labels: Do Not Squash :no_entry_sign:

#26377 [Storage] Added a breaking warning : download blob will block input parameter -AbsoluteUri and -Context together
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/GetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/StorageDataMovementCmdletBase.cs
  src/Storage/Storage/Common/AzureStorageBlob.cs
Labels: needs-review

#26257 Azure Firewall Autoscale Configuration Support
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.cs
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallAutoscaleConfiguration.json
  src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
  src/Network/Network/Models/AzureFirewall/PSAzureFirewallAutoscaleConfiguration.cs
  src/Network/Network/help/Get-AzFirewall.md
  src/Network/Network/help/New-AzFirewall.md
  src/Network/Network/help/Set-AzFirewall.md
Labels: Waiting for CI :shipit:, Network - Firewall

#26509 Update New-AzGalleryImageVersion.md example with correct value for StorageAccountType
  src/Compute/Compute/help/New-AzGalleryImageVersion.md
Labels: Waiting for CI :shipit:

#26515 Added cx warning to the New-AzVM cmdlet, The default value of publicIpSku parameter will be changed from Basic to Standard.
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
Labels: Waiting for CI :shipit:

#26481 Preview Release ArcGateway 2024-07-31
  src/ArcGateway/ArcGateway.Autorest/.gitattributes
  src/ArcGateway/ArcGateway.Autorest/.gitignore
  src/ArcGateway/ArcGateway.Autorest/Properties/AssemblyInfo.cs
  src/ArcGateway/ArcGateway.Autorest/README.md
  src/ArcGateway/ArcGateway.Autorest/UX/Microsoft.HybridCompute/gateways.json
  src/ArcGateway/ArcGateway.Autorest/custom/New-AzArcGateway.ps1
  src/ArcGateway/ArcGateway.Autorest/custom/README.md
  src/ArcGateway/ArcGateway.Autorest/custom/Update-AzArcSetting.ps1
  src/ArcGateway/ArcGateway.Autorest/docs/Az.ArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/docs/Get-AzArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/docs/New-AzArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/docs/README.md
  src/ArcGateway/ArcGateway.Autorest/docs/Remove-AzArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/docs/Update-AzArcSetting.md
  src/ArcGateway/ArcGateway.Autorest/examples/Get-AzArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/examples/New-AzArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/examples/Remove-AzArcGateway.md
  src/ArcGateway/ArcGateway.Autorest/examples/Update-AzArcSetting.md
  src/ArcGateway/ArcGateway.Autorest/how-to.md
  src/ArcGateway/ArcGateway.Autorest/resources/README.md
  src/ArcGateway/ArcGateway.Autorest/test/Get-AzArcGateway.Recording.json
  src/ArcGateway/ArcGateway.Autorest/test/Get-AzArcGateway.Tests.ps1
  src/ArcGateway/ArcGateway.Autorest/test/New-AzArcGateway.Recording.json
  src/ArcGateway/ArcGateway.Autorest/test/New-AzArcGateway.Tests.ps1
  src/ArcGateway/ArcGateway.Autorest/test/README.md
  src/ArcGateway/ArcGateway.Autorest/test/Remove-AzArcGateway.Recording.json
  src/ArcGateway/ArcGateway.Autorest/test/Remove-AzArcGateway.Tests.ps1
  src/ArcGateway/ArcGateway.Autorest/test/Update-AzArcSetting.Recording.json
  src/ArcGateway/ArcGateway.Autorest/test/Update-AzArcSetting.Tests.ps1
  src/ArcGateway/ArcGateway.Autorest/test/env.json
  src/ArcGateway/ArcGateway.Autorest/test/loadEnv.ps1
  src/ArcGateway/ArcGateway.Autorest/test/utils.ps1
  src/ArcGateway/ArcGateway.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/ArcGateway/ArcGateway.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-revision

#26479 [Az.Dataprotection] Added support for AKS vault tier and Resource modifier
  src/DataProtection/DataProtection.Autorest/README.md
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Common/Unlock-AzDataProtectionResourceGuardOperation.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Initialize-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Stop-AzDataProtectionBackupInstanceProtection.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Suspend-AzDataProtectionBackupInstanceBackup.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Update-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Update-AzDataProtectionBackupInstanceAssociatedPolicy.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Restore/Initialize-AzDataProtectionRestoreRequest.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Restore/New-AzDataProtectionRestoreConfigurationClientObject.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Restore/Start-AzDataProtectionBackupInstanceRestore.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Vault/Update-AzDataProtectionBackupVault.ps1
  src/DataProtection/DataProtection.Autorest/custom/Helpers/CommonHelpers.ps1
  src/DataProtection/DataProtection.Autorest/custom/manifests/AzureKubernetesService.json
  src/DataProtection/DataProtection.Autorest/docs/Initialize-AzDataProtectionRestoreRequest.md
  src/DataProtection/DataProtection.Autorest/docs/New-AzDataProtectionBackupPolicy.md
  src/DataProtection/DataProtection.Autorest/docs/New-AzDataProtectionRestoreConfigurationClientObject.md
  src/DataProtection/DataProtection.Autorest/docs/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/DataProtection.Autorest/docs/Stop-AzDataProtectionBackupInstanceProtection.md
  src/DataProtection/DataProtection.Autorest/docs/Suspend-AzDataProtectionBackupInstanceBackup.md
  src/DataProtection/DataProtection.Autorest/docs/Unlock-AzDataProtectionResourceGuardOperation.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupInstanceAssociatedPolicy.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/examples/Initialize-AzDataProtectionRestoreRequest.md
  src/DataProtection/DataProtection.Autorest/examples/New-AzDataProtectionBackupPolicy.md
  src/DataProtection/DataProtection.Autorest/examples/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupPolicy.Recording.json
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupPolicy.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupVault.Recording.json
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupVault.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/env.json
  src/DataProtection/DataProtection.Autorest/test/utils.ps1
  tools/StaticAnalysis/Exceptions/Az.DataProtection/BreakingChangeIssues.csv
Labels: needs-review

#26528 [Recovery Services] Bug fix for update cmdlet in HyperV to Azure provider scenario of Azure Site recovery
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/B2A/AsrB2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrB2ATests/UpdateRPIWithMangedDisksForReplication.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/ReplicationProtectedItem/SetAzureRmRecoveryServicesAsrReplicationProtectedItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  tools/StaticAnalysis/UXMetadataAnalyzer/UXMetadataAnalyzer.cs
Labels: needs-review
