Repository Azure/azure-powershell, pull requests merged in 2024-06, with the labels that each got.

#25048 [Eng] Test PR Validation
  src/Databricks/Databricks.Autorest/README.md
  src/Databricks/Databricks.Autorest/generate-info.json
Labels: Do Not Merge :no_entry_sign:

#25080 Update New-AzADGroupOwner.md
  src/Resources/Resources/help/New-AzADGroupOwner.md
Labels: customer-reported

#25127 Adding optional target subscription Id parameter in order to enable cross-subscription movement
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseMoveCopyTests.cs
  src/Sql/Sql.Test/ScenarioTests/ManagedDatabaseMoveCopyTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseMoveCopyTests/TestCrossSubscriptionManagedDatabaseCopy.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedDatabaseMoveCopyTests/TestCrossSubscriptionManagedDatabaseMove.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/ManagedDatabase/Cmdlet/MoveCopy/MoveCopyAzureSqlManagedDatabaseBase.cs
  src/Sql/Sql/ManagedDatabase/Model/MoveCopyManagedDatabaseModel.cs
  src/Sql/Sql/help/Complete-AzSqlInstanceDatabaseCopy.md
  src/Sql/Sql/help/Complete-AzSqlInstanceDatabaseMove.md
  src/Sql/Sql/help/Copy-AzSqlInstanceDatabase.md
  src/Sql/Sql/help/Move-AzSqlInstanceDatabase.md
  src/Sql/Sql/help/Stop-AzSqlInstanceDatabaseCopy.md
  src/Sql/Sql/help/Stop-AzSqlInstanceDatabaseMove.md
Labels: needs-revision

#25125 Adding trusted access parameter in Create and Register VIS
  src/Workloads/Workloads.Autorest/README.md
  src/Workloads/Workloads.Autorest/custom/New-AzWorkloadsSapVirtualInstance/New-AzWorkloadsSapVirtualInstance_CreateWithDiscovery.ps1
  src/Workloads/Workloads.Autorest/custom/New-AzWorkloadsSapVirtualInstance/New-AzWorkloadsSapVirtualInstance_CreateWithJsonTemplatePath.ps1
  src/Workloads/Workloads.Autorest/docs/New-AzWorkloadsSapVirtualInstance.md
  src/Workloads/Workloads.Autorest/docs/Start-AzWorkloadsSapApplicationInstance.md
  src/Workloads/Workloads.Autorest/docs/Start-AzWorkloadsSapCentralInstance.md
  src/Workloads/Workloads.Autorest/docs/Start-AzWorkloadsSapDatabaseInstance.md
  src/Workloads/Workloads.Autorest/docs/Start-AzWorkloadsSapVirtualInstance.md
  src/Workloads/Workloads.Autorest/docs/Stop-AzWorkloadsSapApplicationInstance.md
  src/Workloads/Workloads.Autorest/docs/Stop-AzWorkloadsSapCentralInstance.md
  src/Workloads/Workloads.Autorest/docs/Stop-AzWorkloadsSapDatabaseInstance.md
  src/Workloads/Workloads.Autorest/docs/Stop-AzWorkloadsSapVirtualInstance.md
  src/Workloads/Workloads.Autorest/examples/New-AzWorkloadsSapVirtualInstance.md
  src/Workloads/Workloads.Autorest/examples/Start-AzWorkloadsSapApplicationInstance.md
  src/Workloads/Workloads.Autorest/examples/Start-AzWorkloadsSapCentralInstance.md
  src/Workloads/Workloads.Autorest/examples/Start-AzWorkloadsSapDatabaseInstance.md
  src/Workloads/Workloads.Autorest/examples/Start-AzWorkloadsSapVirtualInstance.md
  src/Workloads/Workloads.Autorest/examples/Stop-AzWorkloadsSapApplicationInstance.md
  src/Workloads/Workloads.Autorest/examples/Stop-AzWorkloadsSapCentralInstance.md
  src/Workloads/Workloads.Autorest/examples/Stop-AzWorkloadsSapDatabaseInstance.md
  src/Workloads/Workloads.Autorest/examples/Stop-AzWorkloadsSapVirtualInstance.md
  src/Workloads/Workloads.Autorest/test/New-AzWorkloadsSapVirtualInstance.Recording.json
  src/Workloads/Workloads.Autorest/test/New-AzWorkloadsSapVirtualInstance.Tests.ps1
  src/Workloads/Workloads.Autorest/test/env.json
  src/Workloads/Workloads.Autorest/test/loadEnv.ps1
  src/Workloads/Workloads.Autorest/test/msi.json
  src/Workloads/Workloads.Autorest/test/utils.ps1
  src/Workloads/Workloads.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
Labels: needs-revision

#25122 Fix validation error surfacing in Deployment Stack cmdlets.
  src/Resources/ResourceManager/SdkClient/DeploymentStacksSdkClient.cs
  src/Resources/Resources.Test/ScenarioTests/DeploymentStackTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestNewResourceGroupDeploymentStack.json
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentStackTests/TestNewSubscriptionDeploymentStack.json
  src/Resources/Resources.Test/StacksRGBadStorageAccountName.bicep
  src/Resources/Resources.Test/StacksRGBadStorageAccountName.bicepparam
  src/Resources/Resources.Test/StacksSubBadRGName.bicep
  src/Resources/Resources.Test/StacksSubBadRGName.bicepparam
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:

#25291 [Eng] Comment-workflow-folder-from-synctools
  .azure-pipelines/SyncFromMainBranchConfig.json
Labels: Waiting for CI :shipit:

#25292 [Eng] Add github action to sync commit from generation to future
  .github/workflows/sync-generation-to-future.yml
Labels: Waiting for CI :shipit:

#25308 [NetAppFiles] Bug Fix for coolnessPeriod min value
  src/NetAppFiles/NetAppFiles.Management.Sdk/Custom/Models/VolumePatch.cs
  src/NetAppFiles/NetAppFiles.Management.Sdk/Generated/Models/Volume.cs
  src/NetAppFiles/NetAppFiles.Management.Sdk/Generated/Models/VolumeGroupVolumeProperties.cs
  src/NetAppFiles/NetAppFiles.Management.Sdk/Generated/Models/VolumePatch.cs
  src/NetAppFiles/NetAppFiles.Management.Sdk/Generated/Models/VolumePatchProperties.cs
  src/NetAppFiles/NetAppFiles.Management.Sdk/Generated/Models/VolumeProperties.cs
  src/NetAppFiles/NetAppFiles.Management.Sdk/README.md
  src/NetAppFiles/NetAppFiles/ChangeLog.md
Labels: Waiting for CI :shipit:

#25333 Fixed Key Vault Certificate Merge issue
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Certificate/ImportAzureKeyVaultCertificate.cs
  src/KeyVault/KeyVault/Properties/Resources.Designer.cs
  src/KeyVault/KeyVault/Properties/Resources.resx
Labels: Waiting for CI :shipit:

#25284 Added new properties NetworkIdentifier and ServiceEndpointConfig in Vnet/Subnet config for setting SNAT/VIP.
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetServiceEndpointConfig.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests/TestVirtualNetworkSubnetServiceEndpointWithNetworkIdentifier.json
  src/Network/Network/Models/PSServiceEndpoint.cs
  src/Network/Network/VirtualNetwork/Subnet/AddAzureVirtualNetworkSubnetConfigCommand.cs
  src/Network/Network/VirtualNetwork/Subnet/AzureVirtualNetworkSubnetConfigBase.cs
  src/Network/Network/VirtualNetwork/Subnet/AzureVirtualNetworkSubnetConfigHelper.cs
  src/Network/Network/VirtualNetwork/Subnet/NewAzureVirtualNetworkSubnetConfigCommand.cs
  src/Network/Network/VirtualNetwork/Subnet/SetAzureVirtualNetworkSubnetConfigCommand.cs
  src/Network/Network/help/Add-AzVirtualNetworkSubnetConfig.md
  src/Network/Network/help/New-AzVirtualNetworkSubnetConfig.md
  src/Network/Network/help/Set-AzVirtualNetworkSubnetConfig.md
Labels: needs-revision

#25352 Updated Change Log for Subnet Network Identifier.
  src/Network/Network/ChangeLog.md
Labels: Waiting for CI :shipit:

#25096 [Bastion] Add support for 'Premium' Sku and 'enableSessionRecording' feature flag
  src/Network/Network.Test/ScenarioTests/BastionTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.BastionTests/TestBastionCreateWithFeatures.json
  src/Network/Network/Bastion/BastionBaseCmdlet.cs
  src/Network/Network/Bastion/Constants.cs
  src/Network/Network/Bastion/GetAzBastionCommand.cs
  src/Network/Network/Bastion/NewAzBastionCommand.cs
  src/Network/Network/Bastion/RemoveAzBastionCommand.cs
  src/Network/Network/Bastion/SetAzBastionCommand.cs
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/Bastion/PSBastion.cs
  src/Network/Network/Models/Bastion/PSBastionSku.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/New-AzBastion.md
  src/Network/Network/help/Set-AzBastion.md
Labels: Waiting for CI :shipit:, Network - Bastion

#25318 Upgrade Azure.Idenntity to 1.12.0 For CVE
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/AssemblyLoading/ConditionalAssemblyProvider.cs
  src/Accounts/Authentication/Authentication.csproj
  src/CosmosDB/CosmosDB/ChangeLog.md
  src/CosmosDB/CosmosDB/Helpers/CosmosDBSessionCredential.cs
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Common/AzureSessionCredential.cs
  src/Synapse/Synapse/ChangeLog.md
  src/Synapse/Synapse/Common/AzureSessionCredential.cs
  src/lib/netstandard2.0/Azure.Core.dll
  src/lib/netstandard2.0/Azure.Identity.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.Broker.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.Extensions.Msal.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.NativeInterop.dll
  src/lib/netstandard2.0/Microsoft.Identity.Client.dll
  src/lib/netstandard2.0/msalruntime.dll
  src/lib/netstandard2.0/msalruntime_arm64.dll
  src/lib/netstandard2.0/msalruntime_x86.dll
  tools/Common.Netcore.Dependencies.targets
Labels: needs-review

#25314 Add param to Add-AzVMDataDisk
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests/TestAddVMDataDisk.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.format.ps1xml
  src/Compute/Compute/VirtualMachine/Config/AddAzureVMDataDiskCommand.cs
  src/Compute/Compute/help/Add-AzVMDataDisk.md
Labels: Compute

#25313 Fix /32 validation for PrivateRange on firewall and firewall policy
  src/Network/Network.Test/ScenarioTests/AzureFirewallPolicyTests.ps1
  src/Network/Network.Test/ScenarioTests/AzureFirewallTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallPolicyTests/TestAzureFirewallPolicyPrivateRangeCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.AzureFirewallTests/TestAzureFirewallPrivateRangeCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/Utils.cs
Labels: Waiting for CI :shipit:

#25322 NoHealthyBackendsBehavior
  src/Network/Network/ChangeLog.md
  src/Network/Network/Generated/Models/PSProbe.cs
  src/Network/Network/LoadBalancer/Probe/AddAzureRmLoadBalancerProbeConfigCommand.cs
  src/Network/Network/LoadBalancer/Probe/NewAzureRmLoadBalancerProbeConfigCommand.cs
  src/Network/Network/LoadBalancer/Probe/SetAzureRmLoadBalancerProbeConfigCommand.cs
  src/Network/Network/help/Add-AzLoadBalancerProbeConfig.md
  src/Network/Network/help/New-AzLoadBalancerProbeConfig.md
  src/Network/Network/help/Set-AzLoadBalancerProbeConfig.md
Labels: Waiting for CI :shipit:

#25129 Update Set-AzSqlDatabaseAudit.md
  src/Sql/Sql/help/Set-AzSqlDatabaseAudit.md
Labels: Service Attention

#25128 Update Set-AzSqlServerAudit.md
  src/Sql/Sql/help/Set-AzSqlServerAudit.md
Labels: Service Attention

#25367 Updated the Az Databricks cmdlets to 2024-05-01 api version.
  src/Databricks/Databricks.Autorest/README.md
  src/Databricks/Databricks.Autorest/UX/Microsoft.Databricks/accessConnectors.json
  src/Databricks/Databricks.Autorest/UX/Microsoft.Databricks/workspaces-virtualNetworkPeerings.json
  src/Databricks/Databricks.Autorest/UX/Microsoft.Databricks/workspaces.json
  src/Databricks/Databricks.Autorest/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/Databricks.Autorest/custom/New-AzDatabricksWorkspaceProviderAuthorizationObject.ps1
  src/Databricks/Databricks.Autorest/custom/Update-AzDatabricksVNetPeering.ps1
  src/Databricks/Databricks.Autorest/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/Databricks.Autorest/docs/Az.Databricks.md
  src/Databricks/Databricks.Autorest/docs/Get-AzDatabricksAccessConnector.md
  src/Databricks/Databricks.Autorest/docs/Get-AzDatabricksOutboundNetworkDependenciesEndpoint.md
  src/Databricks/Databricks.Autorest/docs/Get-AzDatabricksVNetPeering.md
  src/Databricks/Databricks.Autorest/docs/Get-AzDatabricksWorkspace.md
  src/Databricks/Databricks.Autorest/docs/New-AzDatabricksAccessConnector.md
  src/Databricks/Databricks.Autorest/docs/New-AzDatabricksVNetPeering.md
  src/Databricks/Databricks.Autorest/docs/New-AzDatabricksWorkspace.md
  src/Databricks/Databricks.Autorest/docs/New-AzDatabricksWorkspaceProviderAuthorizationObject.md
  src/Databricks/Databricks.Autorest/docs/Remove-AzDatabricksAccessConnector.md
  src/Databricks/Databricks.Autorest/docs/Remove-AzDatabricksVNetPeering.md
  src/Databricks/Databricks.Autorest/docs/Remove-AzDatabricksWorkspace.md
  src/Databricks/Databricks.Autorest/docs/Update-AzDatabricksAccessConnector.md
  src/Databricks/Databricks.Autorest/docs/Update-AzDatabricksVNetPeering.md
  src/Databricks/Databricks.Autorest/docs/Update-AzDatabricksWorkspace.md
  src/Databricks/Databricks.Autorest/test/AzDatabricksAccessConnector.Recording.json
  src/Databricks/Databricks.Autorest/test/AzDatabricksVNetPeering.Recording.json
  src/Databricks/Databricks.Autorest/test/AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/Databricks.Autorest/test/AzDatabricksWorkspace.Recording.json
  src/Databricks/Databricks.Autorest/test/Get-AzDatabricksAccessConnector.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Get-AzDatabricksOutboundNetworkDependenciesEndpoint.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Get-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Get-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/Databricks.Autorest/test/New-AzDatabricksAccessConnector.Tests.ps1
  src/Databricks/Databricks.Autorest/test/New-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/Databricks.Autorest/test/New-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/Databricks.Autorest/test/New-AzDatabricksWorkspaceProviderAuthorizationObject.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Remove-AzDatabricksAccessConnector.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Remove-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Remove-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Update-AzDatabricksAccessConnector.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Update-AzDatabricksVNetPeering.Tests.ps1
  src/Databricks/Databricks.Autorest/test/Update-AzDatabricksWorkspace.Tests.ps1
  src/Databricks/Databricks.Autorest/test/env.json
  src/Databricks/Databricks.Autorest/test/loadEnv.ps1
  src/Databricks/Databricks.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  tools/Tools.Common/SerializedCmdlets/Az.Databricks.json
Labels: needs-revision

#25387 [Resources] Update ChangeLog.md
  src/Resources/Resources/ChangeLog.md
Labels: Waiting for CI :shipit:
