Repository Azure/azure-powershell, pull requests merged in 2024-04, with the labels that each got.

#24531 add ExlucdeFromLatest field to TargetRegion parameter New/Update-AzGalleryImageVersion
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestGalleryVersionWithSourceImageVMId.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/GalleryImageVersion/GalleryImageVersionCreateOrUpdateMethod.cs
Labels: Waiting for CI :shipit:

#24604 Feature standbypool powershell init
  documentation/azure-powershell-modules.md
  src/StandbyPool/StandbyPool.Autorest/.gitattributes
  src/StandbyPool/StandbyPool.Autorest/.gitignore
  src/StandbyPool/StandbyPool.Autorest/Az.StandbyPool.psd1
  src/StandbyPool/StandbyPool.Autorest/README.md
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyContainerGroupPools.json
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyVirtualMachinePools-standbyVirtualMachines.json
  src/StandbyPool/StandbyPool.Autorest/UX/Microsoft.StandbyPool/standbyVirtualMachinePools.json
  src/StandbyPool/StandbyPool.Autorest/custom/README.md
  src/StandbyPool/StandbyPool.Autorest/docs/Az.StandbyPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Get-AzStandbyVMPoolVM.md
  src/StandbyPool/StandbyPool.Autorest/docs/New-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/New-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/README.md
  src/StandbyPool/StandbyPool.Autorest/docs/Remove-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Remove-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Update-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/docs/Update-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Get-AzStandbyVMPoolVM.md
  src/StandbyPool/StandbyPool.Autorest/examples/New-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/New-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Remove-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Remove-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Update-AzStandbyContainerGroupPool.md
  src/StandbyPool/StandbyPool.Autorest/examples/Update-AzStandbyVMPool.md
  src/StandbyPool/StandbyPool.Autorest/how-to.md
  src/StandbyPool/StandbyPool.Autorest/license.txt
  src/StandbyPool/StandbyPool.Autorest/resources/README.md
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyContainerPool.Recording.json
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyContainerPool.Tests.ps1
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyVMPool.Recording.json
  src/StandbyPool/StandbyPool.Autorest/test/AzStandbyVMPool.Tests.ps1
  src/StandbyPool/StandbyPool.Autorest/test/README.md
  src/StandbyPool/StandbyPool.Autorest/test/env.json
  src/StandbyPool/StandbyPool.Autorest/test/loadEnv.ps1
  src/StandbyPool/StandbyPool.Autorest/test/localEnv.json
  src/StandbyPool/StandbyPool.Autorest/test/utils.ps1
  src/StandbyPool/StandbyPool.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/StandbyPool/StandbyPool.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-revision

#24557 Added vault tier restore and update backup instance for blobs
  src/DataProtection/DataProtection.Autorest/Az.DataProtection.psd1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Backupcenter/Search-AzDataProtectionBackupVaultInAzGraph.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Initialize-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/New-AzDataProtectionBackupConfigurationClientObject.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/New-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Update-AzDataProtectionBackupInstance.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/BackupInstance/Update-AzDataProtectionBackupInstanceAssociatedPolicy.ps1
  src/DataProtection/DataProtection.Autorest/custom/Cmdlets/Platform/Restore/Initialize-AzDataProtectionRestoreRequest.ps1
  src/DataProtection/DataProtection.Autorest/docs/Az.DataProtection.md
  src/DataProtection/DataProtection.Autorest/docs/Initialize-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/docs/Initialize-AzDataProtectionRestoreRequest.md
  src/DataProtection/DataProtection.Autorest/docs/New-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/docs/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/examples/Initialize-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/examples/New-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/examples/Start-AzDataProtectionBackupInstanceRestore.md
  src/DataProtection/DataProtection.Autorest/examples/Update-AzDataProtectionBackupInstance.md
  src/DataProtection/DataProtection.Autorest/test/Backup-AzDataProtectionBackupInstanceAdhoc.Recording.json
  src/DataProtection/DataProtection.Autorest/test/Backup-AzDataProtectionBackupInstanceAdhoc.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/BlobHardeningScenario.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupInstance.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupPolicy.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupVault.Recording.json
  src/DataProtection/DataProtection.Autorest/test/New-AzDataProtectionBackupVault.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/Start-AzDataProtectionBackupInstanceRestore.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/Update-AzDataProtectionBackupInstance.Tests.ps1
  src/DataProtection/DataProtection.Autorest/test/env.json
  src/DataProtection/DataProtection.Autorest/test/loadEnv.ps1
  src/DataProtection/DataProtection.Autorest/test/localEnv.json
  src/DataProtection/DataProtection.Autorest/test/utils.ps1
  src/DataProtection/DataProtection.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
Labels: needs-review

#24600 [Storage] Update Get-AzStorageFileContent download offset and content length calc logic
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/File/Cmdlet/GetAzureStorageFileContent.cs
Labels: Waiting for CI :shipit:

#24634 Upgrade Github Action to remove v3 Node 16 deprecation warning
  .github/workflows/pr-labeled.yml
Labels: customer-reported

#24668 Fix for various docs erroneously pointing to Postgres instead of MySQL
  src/MySql/MySql.Autorest/custom/Restore-AzMySqlFlexibleServer_PointInTimeRestore.ps1
  src/MySql/MySql.Autorest/docs/Restore-AzMySqlFlexibleServer.md
Labels: customer-reported

#24692 Cmk encryption examples text update
  src/DataProtection/DataProtection.Autorest/docs/Get-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/docs/New-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/docs/Update-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/examples/Get-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/examples/New-AzDataProtectionBackupVault.md
  src/DataProtection/DataProtection.Autorest/examples/Update-AzDataProtectionBackupVault.md
Labels: needs-review

#24675 Replaced parameter `EnableRbacAuthorization` by `DisableRbacAuthorization` in `New-AzKeyVault` and `Update-AzKeyVault`
  src/KeyVault/KeyVault.Test/LiveTests/TestLiveScenarios.ps1
  src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultManagementTests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/KeyVault/GetAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/KeyVault/NewAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/KeyVault/RemoveAzureKeyVault.cs
  src/KeyVault/KeyVault/Commands/KeyVault/UndoAzureKeyVaultRemoval.cs
  src/KeyVault/KeyVault/Commands/KeyVault/UpdateAzureKeyVault.cs
  src/KeyVault/KeyVault/help/New-AzKeyVault.md
  src/KeyVault/KeyVault/help/Update-AzKeyVault.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review, Breaking Change Release

#24651 Remove parameter `Value` from `Invoke-AzKeyVaultKeyOperation` and property Result from the output type `PSKeyOperationResult`
  src/KeyVault/KeyVault.Test/PesterTests/Key.Tests.ps1
  src/KeyVault/KeyVault/ChangeLog.md
  src/KeyVault/KeyVault/Commands/Key/InvokeAzureKeyVaultKeyOperation.cs
  src/KeyVault/KeyVault/Models/Key/PSKeyOperationResult.cs
  src/KeyVault/KeyVault/help/Invoke-AzKeyVaultKeyOperation.md
  tools/StaticAnalysis/Exceptions/Az.KeyVault/BreakingChangeIssues.csv
Labels: needs-review, Breaking Change Release

#24425 JavaScript Challenge Feature for Application Gateway Firewall Policy Settings
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.ApplicationGatewayTests/TestApplicationGatewayFirewallPolicyWithJSChallenge.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/FirewallPolicy/PolicySettings/AzureApplicationGatewayFirewallPolicySetting.cs
  src/Network/Network/Models/PSApplicationGatewayFirewallPolicySettings.cs
  src/Network/Network/help/New-AzApplicationGatewayFirewallPolicySetting.md
  tools/StaticAnalysis/Exceptions/Az.Network/SignatureIssues.csv
Labels: needs-revision, needs-review

#24635 [PSCmdAssistant] Grant-AzDiskAccess new parameter SecureVMGuestStateSAS
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.cs
  src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DiskRPTests/TestDiskGrantAccessGetSASWithTL.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/Disk/DiskGrantAccessMethod.cs
  src/Compute/Compute/Generated/Models/PSAccessUri.cs
  src/Compute/Compute/help/Grant-AzDiskAccess.md
Labels: needs-revision

#24379 Update Add-AzServiceFabricNodeType command to use location from cluster
  src/ServiceFabric/ServiceFabric.Test/ScenarioTests/TestServiceFabric.ps1
  src/ServiceFabric/ServiceFabric.Test/SessionRecords/Microsoft.Azure.Commands.ServiceFabric.Test.ScenarioTests.TestServiceFabric/TestAddAzureRmServiceFabricNodeType.json
  src/ServiceFabric/ServiceFabric/ChangeLog.md
  src/ServiceFabric/ServiceFabric/Commands/AddAzureRmServiceFabricNodeType.cs
Labels: needs-revision

#23873 [Breaking Change] Renamed the property ResouceType of ASRVaultSettings to ResourceType
  src/RecoveryServices/RecoveryServices.SiteRecovery/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Vault/GetAzureRmRecoveryServicesAsrVaultContext.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Vault/ImportAzureRmRecoveryServicesAsrVaultSettingsFile.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery/Vault/SetAzureRmRecoveryServicesAsrVaultContext.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  tools/StaticAnalysis/Exceptions/Az.RecoveryServices/BreakingChangeIssues.csv
Labels: Breaking Change Release

#24731 Update template utility to throw exception on uri download failure.
  src/Resources/ResourceManager/Utilities/TemplateUtility.cs
  src/Resources/Resources.Test/ScenarioTests/ResourceGroupTests.ps1
  src/Resources/Resources.Test/SessionRecords/Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests/TestRemoveDeployment.json
  src/Resources/Resources/ChangeLog.md
Labels: needs-revision

#24750 Resolve the solution files
  src/Blueprint/Blueprint.sln
  src/CodeSigning/CodeSigning.sln
  src/CosmosDB/CosmosDB.sln
  src/MachineLearning/MachineLearning.sln
  src/Network/Network.sln
  src/Resources/Resources.sln
  src/Sql/Sql.sln
  src/Synapse/Synapse.sln
Labels: Waiting for CI :shipit:

#24751 Revert "PS Changes for User Managed Identity (#24560)"
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.cs
  src/Network/Network.Test/ScenarioTests/NetworkWatcherAPITests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestCRUDVnetFlowLogWithManagedIdentity.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestCRUDVnetFlowLogWithNoneManagedIdentity.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkWatcherAPITests/TestSetVnetFlowLogWithManagedIdentityFromNoMIInput.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSFlowLogResource.cs
  src/Network/Network/NetworkWatcher/FlowLog/FlowLogBaseCmdlet.cs
  src/Network/Network/NetworkWatcher/FlowLog/NewAzNetworkWatcherFlowLogCommand.cs
  src/Network/Network/NetworkWatcher/FlowLog/SetAzNetworkWatcherFlowLogCommand.cs
  src/Network/Network/Properties/Resources.Designer.cs
  src/Network/Network/Properties/Resources.resx
  src/Network/Network/help/New-AzNetworkWatcherFlowLog.md
  src/Network/Network/help/Set-AzNetworkWatcherFlowLog.md
Labels: Waiting for CI :shipit:

#23693 Update Invoke-AzVMRunCommand.md with more Windows Examples
  src/Compute/Compute/help/Invoke-AzVMRunCommand.md
Labels: Compute, Do Not Merge :no_entry_sign:, customer-reported
