Repository Azure/azure-powershell, pull requests merged in 2025-02, with the labels that each got.

#27008 Add Managed Identity Support in Azure Disk Encryption for VMSS
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetExtensionTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetExtensionTests.ps1
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetExtensionTests/TestAzureDiskEncryptionWithEncryptionIdentityAddedInAzVmssConfig.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetExtensionTests/TestAzureDiskEncryptionWithEncryptionIdentityAddedInSetADEVMssCmdlet.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetExtensionTests/TestAzureDiskEncryptionWithIdentityNotSetInVirtualMachineScaleSet.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetExtensionTests/TestAzureVmssDiskEncryptionWithIdentityNotAckledInKeyVault.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestAddEncryptionIdentityInAzureVmssConfig.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestEncryptionIdentityNotPartOfAzureVmssConfig.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Extension/VmssDiskEncryption/SetAzureVmssDiskEncryptionExtension.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Set-AzVmssDiskEncryptionExtension.md
Labels: Compute

#26891 [Az.Resources] Adding examples of how to use ServicePrincipalName parameter
  src/Resources/Resources/help/Get-AzRoleAssignment.md
Labels: needs-revision, customer-reported

#26993 Update CMS Version to 1 for CodeSigningCIPolicySigning
  src/CodeSigning/CodeSigning/ChangeLog.md
  src/CodeSigning/CodeSigning/Helpers/CmsSigner.cs
Labels: needs-revision

#27056 Fixing issue #12417
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Database/Services/AzureSqlDatabaseAdapter.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/GetAzureSqlElasticPoolDatabase.cs
Labels: Waiting for CI :shipit:

#27052 Update Restore-AzRecoveryServicesBackupItem to support restore to NoZone.
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureCrossZonalRestoreToNoZone.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: Waiting for CI :shipit:

#27087 Update smoke test and live test to use .NET 9 for PS7.5
  .azure-pipelines/live-test.yml
  .azure-pipelines/release-test.yml
  .azure-pipelines/util/smoke-test-steps.yml
Labels: Waiting for CI :shipit:

#27098 Update Connect-AzAccount.md
  src/Accounts/Accounts/help/Connect-AzAccount.md
Labels: customer-reported

#27060 Adding new cmdlet to retrieve NVA boot diagnostics
  src/Accounts/Accounts/Utilities/CommandMappings.json
  src/Network/Network.Management.Sdk/Generated/INetworkVirtualAppliancesOperations.cs
  src/Network/Network.Management.Sdk/Generated/LoadBalancerLoadBalancingRulesOperations.cs
  src/Network/Network.Management.Sdk/Generated/Models/LoadBalancerHealthPerRulePerBackendAddress.cs
  src/Network/Network.Management.Sdk/Generated/NetworkVirtualAppliancesOperations.cs
  src/Network/Network.Management.Sdk/Generated/NetworkVirtualAppliancesOperationsExtensions.cs
  src/Network/Network.Management.Sdk/README.md
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceBootDiagnosticsTest.cs
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceBootDiagnosticsTest.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkVirtualApplianceBootDiagnosticsTest/TestNetworkVirtualApplianceBootDiagnostics.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/PSNetworkVirtualApplianceBootDiagnosticsOperationStatusResponse.cs
  src/Network/Network/NetworkVirtualAppliance/GetNetworkVirtualApplianceBootDiagnosticsCommand.cs
  src/Network/Network/help/Az.Network.md
  src/Network/Network/help/Get-AzNetworkVirtualApplianceBootDiagnostics.md
  src/Resources/Resources.Test/Resources/DeploymentTests/ExtensibleResourceDeployment/kubernetes.bicep
Labels: needs-revision

#27139 Consolidate live test for synapse
  src/Synapse/LiveTests/Synapse/TestLiveScenarios.ps1
Labels: Waiting for CI :shipit:

#26890 [Az.Resources] Adding ApplicationId parameter to get- and remove-azRoleAssignment cmdlets
  src/Resources/Resources/RoleAssignments/GetAzureRoleAssignmentCommand.cs
  src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
Labels: needs-revision, customer-reported

#27187 Use SecureString for sas url inputs in GetNetworkVirtualApplianceBootDiagnosticsCommand
  src/Network/Network.Test/ScenarioTests/NetworkVirtualApplianceBootDiagnosticsTest.ps1
  src/Network/Network/NetworkVirtualAppliance/GetNetworkVirtualApplianceBootDiagnosticsCommand.cs
  src/Network/Network/help/Get-AzNetworkVirtualApplianceBootDiagnostics.md
Labels: Waiting for CI :shipit:

#27199 Update New-AzPolicyExemption.md
  src/Resources/Resources/help/New-AzPolicyExemption.md
Labels: customer-reported

#27214 GA Az.Workloads
  src/Workloads/Workloads/ChangeLog.md
  tools/Az/Az.psd1
  tools/VersionController/MinimalVersion.csv
Labels: Waiting for CI :shipit:
