Repository Azure/azure-powershell, pull requests merged in 2025-05, with the labels that each got.

#27524 [Az.AppConfiguration] Update generation tool version: autorest.powershell v3->v4
  src/AppConfiguration/AppConfiguration.Autorest/.gitignore
  src/AppConfiguration/AppConfiguration.Autorest/Properties/AssemblyInfo.cs
  src/AppConfiguration/AppConfiguration.Autorest/README.md
  src/AppConfiguration/AppConfiguration.Autorest/custom/KeyVaultProperties.json.cs
  src/AppConfiguration/AppConfiguration.Autorest/custom/New-AzAppConfigurationStore.ps1
  src/AppConfiguration/AppConfiguration.Autorest/custom/Update-AzAppConfigurationStore.ps1
  src/AppConfiguration/AppConfiguration.Autorest/docs/Az.AppConfiguration.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Clear-AzAppConfigurationDeletedStore.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Get-AzAppConfigurationDeletedStore.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Get-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Get-AzAppConfigurationStoreKey.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/New-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/New-AzAppConfigurationStoreKey.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Remove-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Test-AzAppConfigurationStoreNameAvailability.md
  src/AppConfiguration/AppConfiguration.Autorest/docs/Update-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration.Autorest/generate-info.json
  src/AppConfiguration/AppConfiguration.Autorest/test/AzAppConfigurationStore.Recording.json
  src/AppConfiguration/AppConfiguration.Autorest/test/env.json
  src/AppConfiguration/AppConfiguration.Autorest/test/utils.ps1
  src/AppConfiguration/AppConfiguration.sln
  src/AppConfiguration/AppConfiguration/Az.AppConfiguration.psd1
  src/AppConfiguration/AppConfiguration/ChangeLog.md
  src/AppConfiguration/AppConfiguration/help/Az.AppConfiguration.md
  src/AppConfiguration/AppConfiguration/help/Clear-AzAppConfigurationDeletedStore.md
  src/AppConfiguration/AppConfiguration/help/Get-AzAppConfigurationDeletedStore.md
  src/AppConfiguration/AppConfiguration/help/Get-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration/help/Get-AzAppConfigurationStoreKey.md
  src/AppConfiguration/AppConfiguration/help/New-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration/help/New-AzAppConfigurationStoreKey.md
  src/AppConfiguration/AppConfiguration/help/Remove-AzAppConfigurationStore.md
  src/AppConfiguration/AppConfiguration/help/Test-AzAppConfigurationStoreNameAvailability.md
  src/AppConfiguration/AppConfiguration/help/Update-AzAppConfigurationStore.md
  tools/StaticAnalysis/Exceptions/Az.AppConfiguration/BreakingChangeIssues.csv
Labels: Breaking Change Release

#27679 Fix address prefixes overlapping between hub and remote virtual network
  src/Network/Network/help/Update-AzVirtualHubVnetConnection.md
Labels: Waiting for CI :shipit:

#27678 Add support for Automatic Zone Rebalancing Policy in VMSS cmdlets
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestRebalancingPolicyVMSS.json
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestResilientVMCreateDelete.json
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/NewAzureRmVmssConfigCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs
  src/Compute/Compute/help/New-AzVmssConfig.md
  src/Compute/Compute/help/Update-AzVmss.md
Labels: needs-revision

#27666 [Storage] Remove MD5 related code from B/F upload cmdlet.
  src/Storage/Storage.Management/ChangeLog.md
  src/Storage/Storage/Blob/Cmdlet/SetAzureStorageBlobContent.cs
  src/Storage/Storage/Blob/StorageDataMovementCmdletBase.cs
  src/Storage/Storage/Common/StorageCloudCmdletBase.cs
  src/Storage/Storage/File/Cmdlet/SetAzureStorageFileContent.cs
Labels: needs-review

#27350 [PS] Migrate ManagedServiceIdentity module to autorest v4
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/.gitignore
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/Properties/AssemblyInfo.cs
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/README.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/custom/AzureResource.cs
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Az.ManagedServiceIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Get-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Get-AzSystemAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Get-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Get-AzUserAssignedIdentityAssociatedResource.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/New-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/New-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Remove-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Remove-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Update-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/docs/Update-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity.Autorest/generate-info.json
  src/ManagedServiceIdentity/ManagedServiceIdentity.sln
  src/ManagedServiceIdentity/ManagedServiceIdentity/Az.ManagedServiceIdentity.psd1
  src/ManagedServiceIdentity/ManagedServiceIdentity/ChangeLog.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Az.ManagedServiceIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Get-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Get-AzSystemAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Get-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Get-AzUserAssignedIdentityAssociatedResource.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/New-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/New-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Remove-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Remove-AzUserAssignedIdentity.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Update-AzFederatedIdentityCredential.md
  src/ManagedServiceIdentity/ManagedServiceIdentity/help/Update-AzUserAssignedIdentity.md
  tools/StaticAnalysis/Exceptions/Az.ManagedServiceIdentity/BreakingChangeIssues.csv
Labels: Breaking Change Release

#27668 Add new Carbon Optimization module
  src/Carbon/Carbon.Autorest/.gitattributes
  src/Carbon/Carbon.Autorest/.gitignore
  src/Carbon/Carbon.Autorest/Properties/AssemblyInfo.cs
  src/Carbon/Carbon.Autorest/README.md
  src/Carbon/Carbon.Autorest/custom/Az.Carbon.custom.psm1
  src/Carbon/Carbon.Autorest/custom/README.md
  src/Carbon/Carbon.Autorest/custom/autogen-model-cmdlets/New-AzCarbonItemDetailsQueryFilterObject.ps1
  src/Carbon/Carbon.Autorest/custom/autogen-model-cmdlets/New-AzCarbonMonthlySummaryReportQueryFilterObject.ps1
  src/Carbon/Carbon.Autorest/custom/autogen-model-cmdlets/New-AzCarbonOverallSummaryReportQueryFilterObject.ps1
  src/Carbon/Carbon.Autorest/custom/autogen-model-cmdlets/New-AzCarbonTopItemsMonthlySummaryReportQueryFilterObject.ps1
  src/Carbon/Carbon.Autorest/custom/autogen-model-cmdlets/New-AzCarbonTopItemsSummaryReportQueryFilterObject.ps1
  src/Carbon/Carbon.Autorest/custom/csharp/GetAzCarbonEmissionDataAvailableDateRange_Get.cs
  src/Carbon/Carbon.Autorest/custom/csharp/GetAzCarbonEmissionReport_Get.cs
  src/Carbon/Carbon.Autorest/custom/csharp/RestErrorHandler.cs
  src/Carbon/Carbon.Autorest/docs/Az.Carbon.md
  src/Carbon/Carbon.Autorest/docs/Get-AzCarbonEmissionDataAvailableDateRange.md
  src/Carbon/Carbon.Autorest/docs/Get-AzCarbonEmissionReport.md
  src/Carbon/Carbon.Autorest/docs/New-AzCarbonItemDetailsQueryFilterObject.md
  src/Carbon/Carbon.Autorest/docs/New-AzCarbonMonthlySummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/docs/New-AzCarbonOverallSummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/docs/New-AzCarbonTopItemsMonthlySummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/docs/New-AzCarbonTopItemsSummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/docs/README.md
  src/Carbon/Carbon.Autorest/examples/Get-AzCarbonEmissionDataAvailableDateRange.md
  src/Carbon/Carbon.Autorest/examples/Get-AzCarbonEmissionReport.md
  src/Carbon/Carbon.Autorest/examples/New-AzCarbonItemDetailsQueryFilterObject.md
  src/Carbon/Carbon.Autorest/examples/New-AzCarbonMonthlySummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/examples/New-AzCarbonOverallSummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/examples/New-AzCarbonTopItemsMonthlySummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/examples/New-AzCarbonTopItemsSummaryReportQueryFilterObject.md
  src/Carbon/Carbon.Autorest/generate-info.json
  src/Carbon/Carbon.Autorest/how-to.md
  src/Carbon/Carbon.Autorest/resources/README.md
  src/Carbon/Carbon.Autorest/test/Get-AzCarbonEmissionDataAvailableDateRange.Recording.json
  src/Carbon/Carbon.Autorest/test/Get-AzCarbonEmissionDataAvailableDateRange.Tests.ps1
  src/Carbon/Carbon.Autorest/test/Get-AzCarbonEmissionReport.Recording.json
  src/Carbon/Carbon.Autorest/test/Get-AzCarbonEmissionReport.Tests.ps1
  src/Carbon/Carbon.Autorest/test/README.md
  src/Carbon/Carbon.Autorest/test/env.json
  src/Carbon/Carbon.Autorest/test/loadEnv.ps1
  src/Carbon/Carbon.Autorest/test/localEnv.json
  src/Carbon/Carbon.Autorest/test/utils.ps1
  src/Carbon/Carbon.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/Carbon/Carbon.Autorest/utils/Unprotect-SecureString.ps1
  src/Carbon/Carbon.sln
  src/Carbon/Carbon/Az.Carbon.psd1
  src/Carbon/Carbon/Carbon.csproj
  src/Carbon/Carbon/ChangeLog.md
  src/Carbon/Carbon/Properties/AssemblyInfo.cs
  src/Carbon/Carbon/help/Az.Carbon.md
  src/Carbon/Carbon/help/Get-AzCarbonEmissionDataAvailableDateRange.md
  src/Carbon/Carbon/help/Get-AzCarbonEmissionReport.md
  src/Carbon/Carbon/help/New-AzCarbonItemDetailsQueryFilterObject.md
  src/Carbon/Carbon/help/New-AzCarbonMonthlySummaryReportQueryFilterObject.md
  src/Carbon/Carbon/help/New-AzCarbonOverallSummaryReportQueryFilterObject.md
  src/Carbon/Carbon/help/New-AzCarbonTopItemsMonthlySummaryReportQueryFilterObject.md
  src/Carbon/Carbon/help/New-AzCarbonTopItemsSummaryReportQueryFilterObject.md
  tools/CreateMappings_rules.json
Labels: needs-revision

#27684 Adding 22H2 EOL Message In Az.StackHCI
  src/StackHCI/StackHCI.Autorest/custom/stackhci.ps1
  src/StackHCI/StackHCI/ChangeLog.md
Labels: needs-revision

#27664 [Auditing] Support server-level audit action group with new architecture
  src/Sql/Sql/Auditing/Model/ServerAuditModel.cs
  src/Sql/Sql/ChangeLog.md
Labels: needs-revision

#27637 [Az.ScVmm] Minor Doc/Description Update for Az.ScVmm Cmdlets
  src/ScVmm/ScVmm.Autorest/custom/Get-AzScVmmVMDisk.ps1
  src/ScVmm/ScVmm.Autorest/custom/Get-AzScVmmVMGuestAgent.ps1
  src/ScVmm/ScVmm.Autorest/custom/Get-AzScVmmVMNic.ps1
  src/ScVmm/ScVmm.Autorest/custom/New-AzScVmmVMExtension.ps1
  src/ScVmm/ScVmm.Autorest/custom/New-AzScVmmVMGuestAgent.ps1
  src/ScVmm/ScVmm.Autorest/docs/Az.ScVmm.md
  src/ScVmm/ScVmm.Autorest/docs/Get-AzScVmmVMGuestAgent.md
  src/ScVmm/ScVmm.Autorest/docs/New-AzScVmmVMExtension.md
  src/ScVmm/ScVmm.Autorest/docs/New-AzScVmmVMGuestAgent.md
  src/ScVmm/ScVmm.Autorest/generate-info.json
  src/ScVmm/ScVmm.sln
  src/ScVmm/ScVmm/Az.ScVmm.psd1
  src/ScVmm/ScVmm/help/Az.ScVmm.md
  src/ScVmm/ScVmm/help/Get-AzScVmmVMGuestAgent.md
  src/ScVmm/ScVmm/help/New-AzScVmmVMExtension.md
  src/ScVmm/ScVmm/help/New-AzScVmmVMGuestAgent.md
Labels: needs-review

#27705 Update in SDK for RecoveryServices.Backup
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureFileShareRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureIaaSClassicComputeVMProtectedItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureIaaSComputeVMProtectedItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureIaaSVMProtectedItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureVmWorkloadSAPAseDatabaseProtectableItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureWorkloadSAPAsePointInTimeRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureWorkloadSAPAsePointInTimeRestoreRequest.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureWorkloadSAPAseRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/AzureWorkloadSAPAseRestoreRequest.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/Models/ResourceList.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/Generated/RecoveryServicesBackupClient.cs
  src/RecoveryServices/RecoveryServices.Backup.Management.Sdk/README.md
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/GetAzureVmWorkloadContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureFSUnregisterContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVMGetContainers.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestAzureVmWorkloadUnDeleteContainer.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureCrossZonalRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureCrossZonalRestoreToNoZone.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSFullRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSGetRPs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSProtection.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSRestoreToAnotherRegion.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRSVaultCMK.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRSVaultMSI.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMBackup.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVMGetItems.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVaultSoftDelete.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVmWorkloadBackupProtectionItem.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVmWorkloadCrossRegionRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureVmWorkloadCrossSubscriptionRestore.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureFSGetJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMCancelJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobs.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMGetJobsTimeFilter.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests/TestAzureVMWaitJob.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSHourlyPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureFSVaultPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMCrashconsistentPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMEnhancedPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMEnhancedPolicyAsDefaultPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMNonUTCPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVMSmartTieringPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadNonUTCPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadPolicy.json
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.PolicyTests/TestAzureVmWorkloadSmartTieringPolicy.json
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: ready to review

#27641 Add VM validation for Hyper-V/VMware to Azure local replication
  src/Migrate/Migrate.Autorest/Properties/AssemblyInfo.cs
  src/Migrate/Migrate.Autorest/custom/AzLocalDiskInput.cs
  src/Migrate/Migrate.Autorest/custom/Helper/AzLocalCommonSettings.ps1
  src/Migrate/Migrate.Autorest/custom/Helper/CommonHelper.ps1
  src/Migrate/Migrate.Autorest/custom/New-AzMigrateLocalServerReplication.ps1
  src/Migrate/Migrate.Autorest/docs/Az.Migrate.md
  src/Migrate/Migrate.Autorest/generate-info.json
  src/Migrate/Migrate.sln
  src/Migrate/Migrate/Az.Migrate.psd1
  src/Migrate/Migrate/ChangeLog.md
Labels: needs-revision

#27695 [NetAppFiles] update to 2025-01-01v2
  src/NetAppFiles/NetAppFiles/Account/NewNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/Account/SetNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/Account/UpdateNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/Helpers/BackupExtensions.cs
  src/NetAppFiles/NetAppFiles/Helpers/ModelExtensions.cs
  src/NetAppFiles/NetAppFiles/Helpers/NetAppAccountExtensions.cs
  src/NetAppFiles/NetAppFiles/Helpers/ReplicationExtensions.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesAccount.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesBackup.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesDestinationReplication.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesReplicationObject.cs
  src/NetAppFiles/NetAppFiles/Models/PSNetAppFilesVolumeDataProtection.cs
  src/NetAppFiles/NetAppFiles/VolumeGroup/NewNetAppFilesVolumeGroup.cs
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesAccount.md
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesVolumeGroup.md
  src/NetAppFiles/NetAppFiles/help/Set-AzNetAppFilesAccount.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesAccount.md
Labels: needs-review

#27759 Add Get-AzMigrateServerMigrationStatus cmdlet and associated documentation.
  src/Migrate/Migrate.Autorest/Properties/AssemblyInfo.cs
  src/Migrate/Migrate.Autorest/custom/Get-AzMigrateServerMigrationStatus.ps1
  src/Migrate/Migrate.Autorest/docs/Az.Migrate.md
  src/Migrate/Migrate.Autorest/docs/Get-AzMigrateServerMigrationStatus.md
  src/Migrate/Migrate.Autorest/examples/Get-AzMigrateServerMigrationStatus.md
  src/Migrate/Migrate.Autorest/generate-info.json
  src/Migrate/Migrate.Autorest/test/Get-AzMigrateServerMigrationStatus.Tests.ps1
  src/Migrate/Migrate.sln
  src/Migrate/Migrate/Az.Migrate.psd1
  src/Migrate/Migrate/ChangeLog.md
  src/Migrate/Migrate/help/Az.Migrate.md
  src/Migrate/Migrate/help/Get-AzMigrateServerMigrationStatus.md
Labels: customer-reported

#27785 [Az.RecoveryServices.Backup] Added fix for resume protection with AzureFileshare
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureModels/AzureItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureWorkloadSQLDatabaseProtectedItem.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureFiles/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureFSStopAndResumeProtection.json
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#27773 [SpringCloud] Update LiveTest unit test case
  src/SpringCloud/LiveTests/SpringCloud.Autorest/TestLiveScenarios.ps1
Labels: needs-review

#27766 [DataFactory]Powershell Release
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/HiveLinkedService.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/HiveLinkedServiceTypeProperties.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/ImpalaLinkedService.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/ImpalaLinkedServiceTypeProperties.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/ImpalaThriftTransportProtocol.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/SparkLinkedService.cs
  src/DataFactory/DataFactory.Management.Sdk/Generated/Models/SparkLinkedServiceTypeProperties.cs
  src/DataFactory/DataFactory.Management.Sdk/README.md
  src/DataFactory/DataFactory/ChangeLog.md
Labels: Waiting for CI :shipit:

#27729 Enhance Restore-AzMySqlFlexibleServer functionality with GeoRestore support
  src/MySql/MySql.Autorest/Properties/AssemblyInfo.cs
  src/MySql/MySql.Autorest/custom/Restore-AzMySqlFlexibleServer_GeoRestore.ps1
  src/MySql/MySql.Autorest/docs/Az.MySql.md
  src/MySql/MySql.Autorest/docs/Restore-AzMySqlFlexibleServer.md
  src/MySql/MySql.Autorest/generate-info.json
  src/MySql/MySql.Autorest/resources/README.md
  src/MySql/MySql.sln
  src/MySql/MySql/Az.MySql.psd1
  src/MySql/MySql/ChangeLog.md
  src/MySql/MySql/help/Az.MySql.md
  src/MySql/MySql/help/New-AzMySqlFlexibleServer.md
  src/MySql/MySql/help/New-AzMySqlServer.md
  src/MySql/MySql/help/Restore-AzMySqlFlexibleServer.md
  src/MySql/MySql/help/Test-AzMySqlFlexibleServerConnect.md
Labels: Waiting for On Demand

#27760 Add Geo-restore functionality to Az.PostgreSql module
  src/PostgreSql/PostgreSql.Autorest/Properties/AssemblyInfo.cs
  src/PostgreSql/PostgreSql.Autorest/custom/Restore-AzPostgreSqlFlexibleServer_GeoRestore.ps1
  src/PostgreSql/PostgreSql.Autorest/docs/Az.PostgreSql.md
  src/PostgreSql/PostgreSql.Autorest/docs/Restore-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/PostgreSql.Autorest/generate-info.json
  src/PostgreSql/PostgreSql.Autorest/resources/README.md
  src/PostgreSql/PostgreSql.sln
  src/PostgreSql/PostgreSql/Az.PostgreSql.psd1
  src/PostgreSql/PostgreSql/ChangeLog.md
  src/PostgreSql/PostgreSql/help/Az.PostgreSql.md
  src/PostgreSql/PostgreSql/help/Restore-AzPostgreSqlFlexibleServer.md
  src/PostgreSql/PostgreSql/help/Test-AzPostgreSqlFlexibleServerConnect.md
Labels: Waiting for CI :shipit:

#27749 Addressed EEE.doc task #27241291
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupProtection.md
Labels: Waiting for CI :shipit:

#27772 sql registration fix
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ContainerTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/AzureWorkload/ContainerTests.ps1
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/RegisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-revision, customer-reported

#27805 [ENG] Remove useless check in generated SDK Verifier
  tools/StaticAnalysis/GeneratedSdkAnalyzer/SDKGeneratedCodeVerify.ps1
Labels: needs-review

#27808 Using SourceResourceId instead of ResourceId to fetch vm RG
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests/TestSQLContainerRegError.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/RegisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: Waiting for CI :shipit:

#27783 [NetAppFiles] Anf 52155 ora volume group
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeGroup.cs
  src/NetAppFiles/NetAppFiles.Test/ScenarioTests/VolumeGroupTests.ps1
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeGroupTests/TestOracleVolumeGroupCrud.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeGroupTests/TestOracleVolumeGroupToManyVolumes.json
  src/NetAppFiles/NetAppFiles.Test/SessionRecords/Microsoft.Azure.Commands.NetAppFiles.Test.ScenarioTests.ScenarioTest.VolumeGroupTests/TestVolumeGroupCrud.json
  src/NetAppFiles/NetAppFiles.Test/UnitTests/VolumeGroupUnitTest.cs
  src/NetAppFiles/NetAppFiles/ChangeLog.md
  src/NetAppFiles/NetAppFiles/VolumeGroup/NewNetAppFilesVolumeGroup.cs
  src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesVolumeGroup.md
  src/NetAppFiles/NetAppFiles/help/Set-AzNetAppFilesAccount.md
  src/NetAppFiles/NetAppFiles/help/Update-AzNetAppFilesAccount.md
Labels: needs-revision

#27811 Az.Migrate - Fix ErrorAction duplication error
  src/Migrate/Migrate.Autorest/custom/Get-AzMigrateLocalServerReplication.ps1
  src/Migrate/Migrate.Autorest/custom/Helper/CommonHelper.ps1
  src/Migrate/Migrate.Autorest/custom/New-AzMigrateLocalServerReplication.ps1
  src/Migrate/Migrate/ChangeLog.md
Labels: Waiting for CI :shipit:

#27836 docs(datamigration): add examples for New-AzDataMigrationToSqlManagedInstance cmdlet
  src/DataMigration/DataMigration.Autorest/docs/New-AzDataMigrationToSqlManagedInstance.md
  src/DataMigration/DataMigration.Autorest/examples/New-AzDataMigrationToSqlManagedInstance.md
  src/DataMigration/DataMigration.Autorest/generate-info.json
  src/DataMigration/DataMigration.sln
  src/DataMigration/DataMigration/Az.DataMigration.psd1
  src/DataMigration/DataMigration/help/New-AzDataMigrationToSqlManagedInstance.md
Labels: Waiting for CI :shipit:

#27839 [PS] Migrate SelfHelp module to autorest v4
  src/SelfHelp/SelfHelp.Autorest/Properties/AssemblyInfo.cs
  src/SelfHelp/SelfHelp.Autorest/README.md
  src/SelfHelp/SelfHelp.Autorest/UX/Microsoft.Help/solutions.json
  src/SelfHelp/SelfHelp.Autorest/UX/Microsoft.Help/troubleshooters.json
  src/SelfHelp/SelfHelp.Autorest/docs/Az.SelfHelp.md
  src/SelfHelp/SelfHelp.Autorest/docs/Get-AzSelfHelpDiagnostic.md
  src/SelfHelp/SelfHelp.Autorest/docs/Get-AzSelfHelpDiscoverySolution.md
  src/SelfHelp/SelfHelp.Autorest/docs/Get-AzSelfHelpSimplifiedSolution.md
  src/SelfHelp/SelfHelp.Autorest/docs/Get-AzSelfHelpSolution.md
  src/SelfHelp/SelfHelp.Autorest/docs/Get-AzSelfHelpSolutionSelfHelp.md
  src/SelfHelp/SelfHelp.Autorest/docs/Get-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp.Autorest/docs/Invoke-AzSelfHelpCheckNameAvailability.md
  src/SelfHelp/SelfHelp.Autorest/docs/Invoke-AzSelfHelpContinueTroubleshooter.md
  src/SelfHelp/SelfHelp.Autorest/docs/Invoke-AzSelfHelpDiscoverySolutionNlpSubscriptionScope.md
  src/SelfHelp/SelfHelp.Autorest/docs/Invoke-AzSelfHelpDiscoverySolutionNlpTenantScope.md
  src/SelfHelp/SelfHelp.Autorest/docs/Invoke-AzSelfHelpWarmSolutionUp.md
  src/SelfHelp/SelfHelp.Autorest/docs/New-AzSelfHelpDiagnostic.md
  src/SelfHelp/SelfHelp.Autorest/docs/New-AzSelfHelpSimplifiedSolution.md
  src/SelfHelp/SelfHelp.Autorest/docs/New-AzSelfHelpSolution.md
  src/SelfHelp/SelfHelp.Autorest/docs/New-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp.Autorest/docs/Restart-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp.Autorest/docs/Stop-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp.Autorest/docs/Update-AzSelfHelpSolution.md
  src/SelfHelp/SelfHelp.Autorest/generate-info.json
  src/SelfHelp/SelfHelp.Autorest/resources/README.md
  src/SelfHelp/SelfHelp.sln
  src/SelfHelp/SelfHelp/Az.SelfHelp.psd1
  src/SelfHelp/SelfHelp/ChangeLog.md
  src/SelfHelp/SelfHelp/help/Az.SelfHelp.md
  src/SelfHelp/SelfHelp/help/Get-AzSelfHelpDiagnostic.md
  src/SelfHelp/SelfHelp/help/Get-AzSelfHelpDiscoverySolution.md
  src/SelfHelp/SelfHelp/help/Get-AzSelfHelpSimplifiedSolution.md
  src/SelfHelp/SelfHelp/help/Get-AzSelfHelpSolution.md
  src/SelfHelp/SelfHelp/help/Get-AzSelfHelpSolutionSelfHelp.md
  src/SelfHelp/SelfHelp/help/Get-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp/help/Invoke-AzSelfHelpCheckNameAvailability.md
  src/SelfHelp/SelfHelp/help/Invoke-AzSelfHelpContinueTroubleshooter.md
  src/SelfHelp/SelfHelp/help/Invoke-AzSelfHelpDiscoverySolutionNlpSubscriptionScope.md
  src/SelfHelp/SelfHelp/help/Invoke-AzSelfHelpDiscoverySolutionNlpTenantScope.md
  src/SelfHelp/SelfHelp/help/Invoke-AzSelfHelpWarmSolutionUp.md
  src/SelfHelp/SelfHelp/help/New-AzSelfHelpDiagnostic.md
  src/SelfHelp/SelfHelp/help/New-AzSelfHelpSimplifiedSolution.md
  src/SelfHelp/SelfHelp/help/New-AzSelfHelpSolution.md
  src/SelfHelp/SelfHelp/help/New-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp/help/Restart-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp/help/Stop-AzSelfHelpTroubleshooter.md
  src/SelfHelp/SelfHelp/help/Update-AzSelfHelpSolution.md
Labels: needs-revision

#27786 Update live test script for background jobs.
  .azure-pipelines/live-test.yml
  .azure-pipelines/util/live-test-steps.yml
  src/Storage/LiveTests/Storage.Management/FileTests.ps1
  tools/TestFx/Live/LiveTestUtility.psm1
Labels: Waiting for CI :shipit:
