Repository Azure/azure-powershell, pull requests merged in 2025-07, with the labels that each got.

#28075 Spelling Fixes
  src/ServiceLinker/ServiceLinker.Autorest/custom/New-AzServiceLinkerSecretAuthInfoObject.ps1
  src/ServiceLinker/ServiceLinker.Autorest/docs/New-AzServiceLinkerSecretAuthInfoObject.md
  src/SpringCloud/SpringCloud.Autorest/custom/Deploy-AzSpringCloudApp.ps1
  src/SpringCloud/SpringCloud.Autorest/docs/Deploy-AzSpringCloudApp.md
  src/SpringCloud/SpringCloud.Autorest/test/utils.ps1
  src/StackHCI/StackHCI.Autorest/custom/stackhci.ps1
  src/StackHCI/StackHCI.Autorest/docs/Disable-AzStackHCIRemoteSupport.md
  src/StackHCI/StackHCI.Autorest/docs/Enable-AzStackHCIRemoteSupport.md
  src/StackHCI/StackHCI.Autorest/docs/Install-AzStackHCIRemoteSupport.md
  src/StackHCI/StackHCI.Autorest/docs/Unregister-AzStackHCI.md
  src/StackHCI/StackHCI.Autorest/examples/Disable-AzStackHCIRemoteSupport.md
  src/StackHCI/StackHCI.Autorest/examples/Enable-AzStackHCIRemoteSupport.md
  src/StackHCI/StackHCI.Autorest/examples/Install-AzStackHCIRemoteSupport.md
  src/StackHCIVM/StackHCIVM.Autorest/custom/New-AzStackHCIVMImage.ps1
  src/StackHCIVM/StackHCIVM.Autorest/custom/New-AzStackHCIVMVirtualMachine_New.ps1
  src/StackHCIVM/StackHCIVM.Autorest/custom/utilities/VirtualNetworkValidations.ps1
  src/StackHCIVM/StackHCIVM.Autorest/docs/Get-AzStackHCIVMVirtualMachine.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/New-AzStackHCIVMImage.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/New-AzStackHCIVMVirtualMachine.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMImage.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMLogicalNetwork.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMNetworkInterface.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMStoragePath.md
  src/StackHCIVM/StackHCIVM.Autorest/docs/Update-AzStackHCIVMVirtualHardDisk.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/Get-AzStackHCIVMVirtualMachine.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/Update-AzStackHCIVMImage.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/Update-AzStackHCIVMLogicalNetwork.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/Update-AzStackHCIVMNetworkInterface.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/Update-AzStackHCIVMStoragePath.md
  src/StackHCIVM/StackHCIVM.Autorest/examples/Update-AzStackHCIVMVirtualHardDisk.md
Labels: customer-reported

#28072 Spelling Fixes
  src/Reservations/Reservations.Autorest/docs/Get-AzReservationCatalog.md
  src/Reservations/Reservations.Autorest/examples/Get-AzReservationCatalog.md
  src/ResourceMover/ResourceMover.Autorest/docs/Invoke-AzResourceMoverBulkRemove.md
  src/ResourceMover/ResourceMover.Autorest/docs/Invoke-AzResourceMoverCommit.md
  src/ResourceMover/ResourceMover.Autorest/docs/Invoke-AzResourceMoverDiscard.md
  src/ResourceMover/ResourceMover.Autorest/docs/Invoke-AzResourceMoverInitiateMove.md
  src/ResourceMover/ResourceMover.Autorest/docs/Invoke-AzResourceMoverPrepare.md
  src/ResourceMover/ResourceMover.Autorest/examples/Invoke-AzResourceMoverCommit.md
  src/ResourceMover/ResourceMover.Autorest/examples/Invoke-AzResourceMoverDiscard.md
  src/ResourceMover/ResourceMover.Autorest/examples/Invoke-AzResourceMoverInitiateMove.md
  src/ResourceMover/ResourceMover.Autorest/examples/Invoke-AzResourceMoverPrepare.md
  src/ScVmm/ScVmm.Autorest/README.md
  src/ScVmm/ScVmm.Autorest/custom/New-AzScVmmVM.ps1
  src/ScVmm/ScVmm.Autorest/custom/Update-AzScVmmVM.ps1
  src/ScVmm/ScVmm.Autorest/docs/Update-AzScVmmVMNic.md
  src/ScVmm/ScVmm.Autorest/examples/Update-AzScVmmVMNic.md
  src/Search/Search/SearchService/SearchServiceBaseCmdlet.cs
  src/Security/DefenderForStorage.Autorest/test/utils.ps1
  src/Security/Security.Autorest/test/New-AzSecurityConnector.Tests.ps1
  src/Security/Security.Autorest/test/New-AzSecurityConnectorDevOpsConfiguration.Tests.ps1
  src/Security/Security.Test/ScenarioTests/IotSecuritySolutionAnalyticsTests.ps1
  src/Security/Security.Test/ScenarioTests/SecurityComplianceTests.ps1
  src/Security/Security.Test/ScenarioTests/SecurityTopologyTests.ps1
  src/Security/Security.Test/ScenarioTests/SqlVulnerabilityAssessmentTests.ps1
  src/Security/Security/Common/ParameterHelpMessages.cs
  src/Security/Security/Resources.Designer.cs
  src/Security/Security/Resources.resx
Labels: customer-reported

#28070 Spelling Fixes
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/RecoveryPointConversions.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/HelperUtils.cs
  src/RecoveryServices/RecoveryServices.Backup.Helpers/Validations/PolicyValidations.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmModels/AzureVmRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/AzureVmWorkloadModels/AzureWorkloadRecoveryPoint.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/BaseObjects.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyRetentionObjects.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/GetAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/RegisterAzureRmRecoveryServicesBackupContainer.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Container/UndoAzureRmRecoveryServicesBackupContainerDeletion.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/GetAzureRmRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/NewAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/GetAzureRmRecoveryServicesBackupWorkloadRecoveryConfig.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/TestAzureRMRecoveryServicesDSMove.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices.Backup/RecoveryServicesBackupCmdletBase.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Common/PSRecoveryServicesVaultClient.cs
  src/RecoveryServices/RecoveryServices/Common/PSRecoveryServicesVaultExtendedInfoClient.cs
  src/RecoveryServices/RecoveryServices/Models/PSObjects.cs
  src/RecoveryServices/RecoveryServices/Models/PSParameterSets.cs
  src/RecoveryServices/RecoveryServices/Vault/GetAzureRMRecoveryServicesVaultSettingsFile.cs
  src/RecoveryServices/RecoveryServices/Vault/GetAzureRmRecoveryServicesVaults.cs
Labels: customer-reported

#28069 Spelling Fixes
  src/Portal/Portal.Autorest/docs/Remove-AzPortalDashboard.md
  src/Portal/Portal.Autorest/docs/Set-AzPortalDashboard.md
  src/Portal/Portal.Autorest/examples/Remove-AzPortalDashboard.md
  src/Portal/Portal.Autorest/examples/Set-AzPortalDashboard.md
  src/PostgreSql/PostgreSql.Autorest/docs/Update-AzPostgreSqlFlexibleServerConfiguration.md
  src/PostgreSql/PostgreSql.Autorest/examples/Update-AzPostgreSqlFlexibleServerConfiguration.md
  src/PostgreSql/PostgreSql.Autorest/test/AzPostgreSqlFlexibleServer.Tests.ps1
  src/PostgreSql/PostgreSql.Autorest/test/utils.ps1
  src/PostgreSql/PostgreSql/ChangeLog.md
  src/PowerBIEmbedded/PowerBI.Test/ScenarioTests/PowerBITests.ps1
  src/PowerBIEmbedded/PowerBI/Commands/GetAzureRmPowerBIEmbeddedCapacity.cs
  src/PowerBIEmbedded/PowerBIEmbedded/Properties/Resources.Designer.cs
  src/PowerBIEmbedded/PowerBIEmbedded/Properties/Resources.resx
  src/PrivateDns/PrivateDns/Models/PSPrivateDnsRecordSet.cs
  src/ProviderHub/ProviderHub.Autorest/docs/Get-AzProviderHubCustomRollout.md
  src/ProviderHub/ProviderHub.Autorest/examples/Get-AzProviderHubCustomRollout.md
  src/Purview/Purviewdata.Autorest/docs/New-AzPurviewTrigger.md
  src/Purview/Purviewdata.Autorest/examples/New-AzPurviewTrigger.md
  src/Qumulo/Qumulo.Autorest/test/AzQumuloStorage.Tests.ps1
  src/Quota/Quota.Autorest/README.md
  src/RedisCache/RedisCache.Test/ScenarioTests/RedisCacheTests.ps1
  src/RedisCache/RedisCache/Commands/GetAzureRedisCache.cs
  src/RedisCache/RedisCache/Commands/NewAzureRedisCache.cs
  src/RedisCache/RedisCache/Commands/SetAzureRedisCache.cs
  src/RedisCache/RedisCache/Models/RedisCacheAttributes.cs
Labels: customer-reported

#28019 Az.Migrate - New-AzMigrateServerReplication - Minor change to switch deprecated Get-AzVMSize -loc to Get-AzComputeResourceSKU -loc
  src/Migrate/Migrate.Autorest/custom/New-AzMigrateServerReplication.ps1
  src/Migrate/Migrate/ChangeLog.md
Labels: needs-revision, customer-reported

#28077 Improving Test-AzPostgreSqlFlexibleServerConnect
  src/PostgreSql/PostgreSql.Autorest/Properties/AssemblyInfo.cs
  src/PostgreSql/PostgreSql.Autorest/custom/Test-AzPostgreSqlFlexibleServerConnect.ps1
  src/PostgreSql/PostgreSql.Autorest/docs/Test-AzPostgreSqlFlexibleServerConnect.md
  src/PostgreSql/PostgreSql.Autorest/generate-info.json
  src/PostgreSql/PostgreSql.sln
  src/PostgreSql/PostgreSql/Az.PostgreSql.psd1
  src/PostgreSql/PostgreSql/ChangeLog.md
  src/PostgreSql/PostgreSql/help/Test-AzPostgreSqlFlexibleServerConnect.md
Labels: Waiting for CI :shipit:

#27936 ProxyAgent support in Compute
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestProxyAgentSetting.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Common/ConstantStringTypes.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/SetAzVmssProxyAgentSetting.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSetVM/VirtualMachineScaleSetVMUpdateMethod.cs
  src/Compute/Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineScaleSetStrategy.cs
  src/Compute/Compute/Strategies/ComputeRp/VirtualMachineStrategy.cs
  src/Compute/Compute/VirtualMachine/Config/SetAzVMProxyAgentSetting.cs
  src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
  src/Compute/Compute/help/New-AzVM.md
  src/Compute/Compute/help/New-AzVmss.md
  src/Compute/Compute/help/Set-AzVMProxyAgentSetting.md
  src/Compute/Compute/help/Set-AzVmssProxyAgentSetting.md
  src/Compute/Compute/help/Update-AzVmssVM.md
  tools/StaticAnalysis/Exceptions/Az.Compute/ExampleIssues.csv
  tools/StaticAnalysis/Exceptions/Az.Compute/SignatureIssues.csv
Labels: Compute

#27987 Proxy Agent support for Gallery
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.cs
  src/Compute/Compute.Test/ScenarioTests/GalleryTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.GalleryTests/TestInVMAccessControlProfileVersion.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Compute.format.ps1xml
  src/Compute/Compute/Generated/ComputeAutomationBaseCmdlet.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfile/GetAzGalleryInVMAccessControlProfile.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfile/NewAzGalleryInVMAccessControlProfile.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfile/RemoveAzGalleryInVMAccessControlProfile.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfile/UpdateAzGalleryInVMAccessControlProfile.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/AddAzGalleryInVMAccessControlProfileVersionRulesIdentity.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/AddAzGalleryInVMAccessControlProfileVersionRulesPrivilege.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/AddAzGalleryInVMAccessControlProfileVersionRulesRole.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/AddAzGalleryInVMAccessControlProfileVersionRulesRoleAssignment.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/NewAzGalleryInVMAccessControlProfileVersionConfig.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/RemoveAzGalleryInVMAccessControlProfileVersionRulesIdentity.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/RemoveAzGalleryInVMAccessControlProfileVersionRulesPrivilege.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/RemoveAzGalleryInVMAccessControlProfileVersionRulesRoleAssignment.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/Config/RemoveAzGalleryInVmAccessControlProfileVersionRulesRole.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/GetAzGalleryInVMAccessControlProfileVersion.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/NewAzGalleryInVMAccessControlProfileVersion.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/RemoveAzGalleryInVMAccessControlProfileVersion.cs
  src/Compute/Compute/Generated/GalleryInVMAccessControlProfileVersion/UpdateAzGalleryInVMAccessControlProfileVersion.cs
  src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs
  src/Compute/Compute/Generated/Models/PSGalleryInVMAccessControlProfile.cs
  src/Compute/Compute/Generated/Models/PSGalleryInVMAccessControlProfileList.cs
  src/Compute/Compute/Generated/Models/PSGalleryInVMAccessControlProfileVersion.cs
  src/Compute/Compute/Generated/Models/PSGalleryInVMAccessControlProfileVersionList.cs
  src/Compute/Compute/help/Add-AzGalleryInVMAccessControlProfileVersionRulesIdentity.md
  src/Compute/Compute/help/Add-AzGalleryInVMAccessControlProfileVersionRulesPrivilege.md
  src/Compute/Compute/help/Add-AzGalleryInVMAccessControlProfileVersionRulesRole.md
  src/Compute/Compute/help/Add-AzGalleryInVMAccessControlProfileVersionRulesRoleAssignment.md
  src/Compute/Compute/help/Get-AzGalleryInVMAccessControlProfile.md
  src/Compute/Compute/help/Get-AzGalleryInVMAccessControlProfileVersion.md
  src/Compute/Compute/help/New-AzGalleryInVMAccessControlProfile.md
  src/Compute/Compute/help/New-AzGalleryInVMAccessControlProfileVersion.md
  src/Compute/Compute/help/New-AzGalleryInVMAccessControlProfileVersionConfig.md
  src/Compute/Compute/help/Remove-AzGalleryInVMAccessControlProfile.md
  src/Compute/Compute/help/Remove-AzGalleryInVMAccessControlProfileVersion.md
  src/Compute/Compute/help/Remove-AzGalleryInVMAccessControlProfileVersionRulesIdentity.md
  src/Compute/Compute/help/Remove-AzGalleryInVMAccessControlProfileVersionRulesPrivilege.md
  src/Compute/Compute/help/Remove-AzGalleryInVMAccessControlProfileVersionRulesRole.md
  src/Compute/Compute/help/Remove-AzGalleryInVMAccessControlProfileVersionRulesRoleAssignment.md
  src/Compute/Compute/help/Update-AzGalleryInVMAccessControlProfile.md
  src/Compute/Compute/help/Update-AzGalleryInVMAccessControlProfileVersion.md
  tools/StaticAnalysis/Exceptions/Az.Compute/SignatureIssues.csv
Labels: Compute

#28091 Spelling Fixes
  src/Storage/Storage/DatalakeGen2/Cmdlet/DataLakeGen2ACLRecursiveBaseCmdlet.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2ChildItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/GetAzDataLakeGen2FileContent.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RemoveAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/RestoreAzDataLakeGen2DeletedItem.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/SetAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/DatalakeGen2/Cmdlet/UpdateAzDataLakeGen2ACLRecursive.cs
  src/Storage/Storage/File/AzureStorageFileException.cs
  src/Storage/Storage/File/Cmdlet/GetAzureStorageFileCopyState.cs
  src/Storage/Storage/File/Cmdlet/NewAzureStorageFileSasToken.cs
  src/Storage/Storage/File/Cmdlet/NewAzureStorageShareSasToken.cs
  src/Storage/Storage/File/Cmdlet/RemoveAzureStorageShare.cs
  src/Storage/Storage/File/Cmdlet/RenameAzureStorageDirectory.cs
  src/Storage/Storage/File/Cmdlet/StartAzureStorageFileCopy.cs
  src/Storage/Storage/File/StorageFileDataManagementCmdletBase.cs
  src/Storage/Storage/Model/Contract/IStorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/IStorageManagement.cs
  src/Storage/Storage/Model/Contract/StorageBlobManagement.cs
  src/Storage/Storage/Model/Contract/StorageQueueManagement.cs
  src/Storage/Storage/Model/Contract/StorageTableManagement.cs
  src/Storage/Storage/Model/Contract/StorageTableV2Management.cs
  src/Storage/Storage/Queue/Cmdlet/NewAzureStorageQueueSasToken.cs
  src/Storage/Storage/Resources.Designer.cs
  src/Storage/Storage/Resources.resx
  src/Storage/Storage/Table/Cmdlet/NewAzureStorageTableSasToken.cs
Labels: customer-reported

#28088 Spelling Fixes
  src/Sql/Sql/Ipv6FirewallRule/Cmdlet/AzureSqlServerIpv6FirewallRuleCmdletBase.cs
  src/Sql/Sql/LedgerDigestUploads/Cmdlet/AzureSqlDatabaseLedgerDigestUploadBase.cs
  src/Sql/Sql/LedgerDigestUploads/Services/AzureSqlDatabaseLedgerDigestUploadCommunicator.cs
  src/Sql/Sql/Location Capabilities/Model/ServerVersionCapabilityModel.cs
  src/Sql/Sql/Location Capabilities/Model/ServiceObjectiveCapabilityModel.cs
  src/Sql/Sql/ManagedDatabase/Cmdlet/MoveCopy/GetMoveCopyAzureSqlManagedDatabaseOperationsBase.cs
  src/Sql/Sql/ManagedDatabase/Model/AzureSqlManagedDatabaseModel.cs
  src/Sql/Sql/ManagedDatabase/Model/AzureSqlRecoverableManagedDatabaseModel.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseAdapter.cs
  src/Sql/Sql/ManagedDatabase/Services/AzureSqlManagedDatabaseCommunicator.cs
  src/Sql/Sql/ManagedInstance/Cmdlet/ManagedInstanceCmdletBase.cs
  src/Sql/Sql/ManagedInstanceDtc/Cmdlet/ManagedInstanceDtcCmdletBase.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Cmdlet/AzureSqlManagedDatabaseLedgerDigestUploadBase.cs
  src/Sql/Sql/ManagedInstanceLedgerDigestUploads/Services/AzureSqlManagedDatabaseLedgerDigestUploadCommunicator.cs
  src/Sql/Sql/ManagedInstanceOperation/Cmdlet/ManagedInstanceOperationCmdletBase.cs
  src/Sql/Sql/ManagedInstanceSchedule/Cmdlet/NewAzureSqlManagedInstanceSchedule.cs
  src/Sql/Sql/OutboundFirewallRules/Cmdlet/AzureSqlServerOutboundFirewallRulesCmdletBase.cs
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/RecommendedAction/Cmdlet/RecommendedActionState.cs
  src/Sql/Sql/RecommendedAction/Service/AzureSqlRecommendedActionCommunicatorBase.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationAdapter.cs
  src/Sql/Sql/Replication/Services/AzureSqlDatabaseReplicationCommunicator.cs
  src/Sql/Sql/Server/Cmdlet/AzureSqlServerCmdletBase.cs
  src/Sql/Sql/Server/Services/AzureSqlServerAdapter.cs
Labels: customer-reported

#28087 Spelling Fixes
  src/Sql/Sql/Advisor/Cmdlet/AdvisorAutoExecuteStatus.cs
  src/Sql/Sql/Advisor/Service/AzureSqlAdvisorCommunicatorBase.cs
  src/Sql/Sql/Auditing/DefinitionsCommon.cs
  src/Sql/Sql/Data Sync/Model/AzureSqlSyncGroupModel.cs
  src/Sql/Sql/Data Sync/Model/AzureSqlSyncMemberModel.cs
  src/Sql/Sql/Database Backup/Services/AzureSqlDatabaseBackupCommunicator.cs
  src/Sql/Sql/Database/Model/AzureSqlDatabaseModel.cs
  src/Sql/Sql/DistributedAvailabilityGroup/Cmdlet/AzureSqlManagedInstanceLinkCmdletBase.cs
  src/Sql/Sql/DistributedAvailabilityGroup/Services/AzureSqlManagedInstanceLinkAdapter.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/Agent/AzureSqlElasticJobAgentCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/Credential/AzureSqlElasticJobCredentialCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/Job/AzureSqlElasticJobCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/JobExecution/StartAzureSqlElasticJob.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/JobStep/AzureSqlElasticJobStepCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/JobStep/SetAzureSqlElasticJobStep.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/PrivateEndpoint/AzureSqlElasticJobPrivateEndpointCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/Target/AzureSqlElasticJobTargetCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Cmdlet/TargetGroup/AzureSqlElasticJobTargetGroupCmdletBase.cs
  src/Sql/Sql/Elastic Jobs/Services/AzureSqlElasticJobAdapter.cs
  src/Sql/Sql/Elastic Pools/Cmdlet/StopAzureSqlElasticPoolActivity.cs
  src/Sql/Sql/Elastic Pools/Services/AzureSqlElasticPoolAdapter.cs
  src/Sql/Sql/EndpointCertificate/Cmdlet/AzureSqlInstanceEndpointCertificateCmdletBase.cs
  src/Sql/Sql/Failover Group/Services/AzureSqlFailoverGroupAdapter.cs
  src/Sql/Sql/FirewallRule/Cmdlet/AzureSqlServerFirewallRuleCmdletBase.cs
  src/Sql/Sql/ImportExport/Cmdlet/GetAzureSqlDatabaseImportExportStatus.cs
  src/Sql/Sql/ImportExport/Cmdlet/ImportExportCmdletArmBase.cs
  src/Sql/Sql/Instance Failover Group/Cmdlet/NewAzureSqlInstanceFailoverGroup.cs
  src/Sql/Sql/Instance Pools/Cmdlet/SetAzureSqlInstancePool.cs
  src/Sql/Sql/InstanceActiveDirectoryOnlyAuthentication/Services/AzureSqlInstanceActiveDirectoryOnlyAuthenticationAdapter.cs
  src/Sql/Sql/InstanceActiveDirectoryOnlyAuthentication/Services/AzureSqlInstanceActiveDirectoryOnlyAuthenticationCommunicator.cs
Labels: customer-reported

#28051 Spelling Fixes
  src/EventGrid/EventGrid.Autorest/docs/Grant-AzEventGridPartnerConfiguration.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridChannel.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridDomain.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridDomainEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridDomainTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridDynamicRoutingEnrichmentObject.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridNamespace.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridNamespaceTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridPartnerConfiguration.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridPartnerNamespace.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridPartnerTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridSystemTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/New-AzEventGridTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Revoke-AzEventGridPartnerConfiguration.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridDomain.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridDomainEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridDomainTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridNamespace.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridNamespaceTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridPartnerTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridSystemTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/docs/Update-AzEventGridTopicEventSubscription.md
  src/EventGrid/EventGrid.Autorest/examples/New-AzEventGridDynamicRoutingEnrichmentObject.md
  src/EventHub/EventHub.Autorest/docs/New-AzEventHub.md
  src/EventHub/EventHub.Autorest/docs/Set-AzEventHubApplicationGroup.md
  src/EventHub/EventHub.Autorest/docs/Set-AzEventHubNamespace.md
  src/EventHub/EventHub.Autorest/examples/New-AzEventHub.md
  src/EventHub/EventHub.Autorest/examples/Set-AzEventHubApplicationGroup.md
  src/EventHub/EventHub.Autorest/examples/Set-AzEventHubNamespace.md
  src/EventHub/EventHub/ChangeLog.md
  src/EventHub/EventHub/Cmdlets/AuthorizationRule/NewAzureEventhubAuthorizationRuleSASToken.cs
  src/EventHub/EventHub/Resources.Designer.cs
  src/EventHub/EventHub/Resources.resx
Labels: needs-revision, customer-reported

#27943 [PS Resource] Add breaking change announcement
  src/Resources/Authorization.Autorest/Az.Authorization.nuspec
  src/Resources/Authorization.Autorest/Properties/AssemblyInfo.cs
  src/Resources/Authorization.Autorest/README.md
  src/Resources/Authorization.Autorest/docs/Az.Authorization.md
  src/Resources/Authorization.Autorest/generate-info.json
  src/Resources/Authorization.Autorest/resources/README.md
  src/Resources/Resources.sln
  src/Resources/Resources/Az.Resources.psd1
  src/Resources/Resources/ChangeLog.md
  src/Resources/Resources/help/Get-AzManagementGroupDeploymentStack.md
  src/Resources/Resources/help/Get-AzRoleEligibleChildResource.md
  src/Resources/Resources/help/New-AzRoleEligibilityScheduleRequest.md
  src/Resources/Resources/help/Save-AzManagementGroupDeploymentStackTemplate.md
Labels: Breaking Change Preannounce

#28203 Add new optional parameter `CVMOsDiskEncryptionSetId` in `Restore-AzRecoveryServicesBackupItem`
  src/RecoveryServices/RecoveryServices.Backup.Models/CmdletParamEnums.cs
  src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/IaasVmPsBackupProvider.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.cs
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup.Test/SessionRecords/Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ItemTests/TestAzureRestoreWithCVMOsDiskEncryptionSetId.json
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
Labels: Do Not Merge :no_entry_sign:
