Repository Azure/azure-powershell, pull requests merged in 2025-09, with the labels that each got.

#28486 [PS] Add breaking change message for SecurityInsights
  src/SecurityInsights/SecurityInsights.Autorest/Properties/AssemblyInfo.cs
  src/SecurityInsights/SecurityInsights.Autorest/README.md
  src/SecurityInsights/SecurityInsights.Autorest/docs/Az.SecurityInsights.md
  src/SecurityInsights/SecurityInsights.Autorest/generate-info.json
  src/SecurityInsights/SecurityInsights.Autorest/resources/README.md
  src/SecurityInsights/SecurityInsights.sln
  src/SecurityInsights/SecurityInsights/Az.SecurityInsights.psd1
  src/SecurityInsights/SecurityInsights/ChangeLog.md
Labels: Breaking Change Preannounce

#28502 Update Update-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/docs/Update-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/examples/Update-AzRoleManagementPolicy.md
  src/Resources/Resources/help/Update-AzRoleManagementPolicy.md
Labels: customer-reported

#28515 Patch 2025-09-05-03 Fix typo in docs of subsciption to subscription
  src/DynatraceObservability/DynatraceObservability.Autorest/docs/Get-AzDynatraceMonitor.md
  src/DynatraceObservability/DynatraceObservability.Autorest/examples/Get-AzDynatraceMonitor.md
Labels: customer-reported

#28512 Update Update-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/docs/Update-AzRoleManagementPolicy.md
  src/Resources/Authorization.Autorest/examples/Update-AzRoleManagementPolicy.md
  src/Resources/Resources/help/Update-AzRoleManagementPolicy.md
Labels: customer-reported

#28560 [Az.Databricks] The code base is going to be refactored, the following cmdlet adds a BreakingChange announcement
  src/Databricks/Databricks.Autorest/Properties/AssemblyInfo.cs
  src/Databricks/Databricks.Autorest/README.md
  src/Databricks/Databricks.Autorest/custom/New-AzDatabricksWorkspace.ps1
  src/Databricks/Databricks.Autorest/custom/Update-AzDatabricksVNetPeering.ps1
  src/Databricks/Databricks.Autorest/custom/Update-AzDatabricksWorkspace.ps1
  src/Databricks/Databricks.Autorest/docs/Az.Databricks.md
  src/Databricks/Databricks.Autorest/generate-info.json
  src/Databricks/Databricks.Autorest/resources/README.md
  src/Databricks/Databricks.sln
  src/Databricks/Databricks/Az.Databricks.psd1
  src/Databricks/Databricks/ChangeLog.md
Labels: Breaking Change Preannounce

#28373 Feature/sftp module
  src/Sftp/Sftp.Test/ScenarioTests/CmdletParameterCompatibilityTests.cs
  src/Sftp/Sftp.Test/ScenarioTests/Common.ps1
  src/Sftp/Sftp.Test/ScenarioTests/ConnectAzSftpTests.ps1
  src/Sftp/Sftp.Test/ScenarioTests/ConnectAzSftpTestsRunner.cs
  src/Sftp/Sftp.Test/ScenarioTests/FileUtilsTests.cs
  src/Sftp/Sftp.Test/ScenarioTests/NewAzSftpCertificateTests.ps1
  src/Sftp/Sftp.Test/ScenarioTests/NewAzSftpCertificateTestsRunner.cs
  src/Sftp/Sftp.Test/ScenarioTests/RSAParserTests.cs
  src/Sftp/Sftp.Test/ScenarioTests/SftpConstantsTests.cs
  src/Sftp/Sftp.Test/ScenarioTests/SftpScenarioTests.cs
  src/Sftp/Sftp.Test/ScenarioTests/SftpTestRunner.cs
  src/Sftp/Sftp.Test/ScenarioTests/SftpUtilsTests.cs
  src/Sftp/Sftp.Test/ScenarioTests/TestCoverageBootstrap.cs
  src/Sftp/Sftp.Test/Sftp.Test.csproj
  src/Sftp/Sftp.sln
  src/Sftp/Sftp/Az.Sftp.psd1
  src/Sftp/Sftp/CHANGELOG.md
  src/Sftp/Sftp/Common/FileUtils.cs
  src/Sftp/Sftp/Common/RSAParser.cs
  src/Sftp/Sftp/Common/SftpBaseCmdlet.cs
  src/Sftp/Sftp/Common/SftpConstants.cs
  src/Sftp/Sftp/Common/SftpUtils.cs
  src/Sftp/Sftp/Models/AuthenticationFIles.cs
  src/Sftp/Sftp/Models/ConnectionInfo.cs
  src/Sftp/Sftp/Models/PSCertificateInfo.cs
  src/Sftp/Sftp/Models/RuntimeState.cs
  src/Sftp/Sftp/Models/SFTPSession.cs
  src/Sftp/Sftp/Models/SessionConfiguration.cs
  src/Sftp/Sftp/README.md
  src/Sftp/Sftp/Sftp.csproj
  src/Sftp/Sftp/SftpCommands/ConnectAzSftpCommand.cs
  src/Sftp/Sftp/SftpCommands/NewAzSftpCertificateCommand.cs
  src/Sftp/Sftp/UX/Microsoft.Storage/sftp.json
  src/Sftp/Sftp/help/Connect-AzSftp.md
  src/Sftp/Sftp/help/New-AzSftpCertificate.md
Labels: needs-revision

#28619 Improve validation for EnabledSoftDelete and SoftDeleteRetentionDay params
  src/Sql/Sql.Test/ScenarioTests/ServerCrudTests.ps1
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerCreateWithCustomSoftRetentionEnabled.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerCreateWithDefaultSoftRetentionEnabled.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerRestoreDeletedServer.json
  src/Sql/Sql.Test/SessionRecords/Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerCrudTests/TestServerUpdateWithSoftRetentionEnabled.json
  src/Sql/Sql/ChangeLog.md
  src/Sql/Sql/Properties/Resources.Designer.cs
  src/Sql/Sql/Properties/Resources.resx
  src/Sql/Sql/Server/Cmdlet/NewAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/RestoreAzureSqlServer.cs
  src/Sql/Sql/Server/Cmdlet/SetAzureSqlServer.cs
  src/Sql/Sql/help/Set-AzSqlServer.md
Labels: customer-reported
