Repository Azure/azure-powershell, pull requests merged in 2025-04, with the labels that each got.

#27323 Added support for SMTP Username CRUD operations
  src/Communication/Communication.sln
  src/Communication/Communication/Az.Communication.psd1
  src/Communication/Communication/ChangeLog.md
  src/Communication/Communication/help/Az.Communication.md
  src/Communication/Communication/help/Get-AzCommunicationServiceSmtpUsername.md
  src/Communication/Communication/help/New-AzCommunicationServiceSmtpUsername.md
  src/Communication/Communication/help/Remove-AzCommunicationServiceSmtpUsername.md
  src/Communication/Communication/help/Update-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/.gitattributes
  src/Communication/CommunicationServiceSmtpUsername.Autorest/.gitignore
  src/Communication/CommunicationServiceSmtpUsername.Autorest/Properties/AssemblyInfo.cs
  src/Communication/CommunicationServiceSmtpUsername.Autorest/README.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/UX/Microsoft.Communication/communicationServices-smtpUsernames.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/Az.CommunicationServiceSmtpUsername.custom.psm1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/README.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/csharp/GetAzCommunicationServiceSmtpUsername_Get.cs
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/csharp/GetAzCommunicationServiceSmtpUsername_List.cs
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/csharp/RemoveAzCommunicationServiceSmtpUsername_Delete.cs
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/csharp/RemoveAzCommunicationServiceSmtpUsername_DeleteViaIdentity.cs
  src/Communication/CommunicationServiceSmtpUsername.Autorest/custom/csharp/RemoveAzCommunicationServiceSmtpUsername_DeleteViaIdentityCommunicationService.cs
  src/Communication/CommunicationServiceSmtpUsername.Autorest/docs/Az.CommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/docs/Get-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/docs/New-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/docs/README.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/docs/Remove-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/docs/Update-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/examples/Get-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/examples/New-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/examples/Remove-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/examples/Update-AzCommunicationServiceSmtpUsername.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/generate-info.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/how-to.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/resources/README.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/Get-AzCommunicationServiceSmtpUsername.Recording.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/Get-AzCommunicationServiceSmtpUsername.Tests.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/New-AzCommunicationServiceSmtpUsername.Recording.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/New-AzCommunicationServiceSmtpUsername.Tests.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/README.md
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/Remove-AzCommunicationServiceSmtpUsername.Recording.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/Remove-AzCommunicationServiceSmtpUsername.Tests.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/Update-AzCommunicationServiceSmtpUsername.Recording.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/Update-AzCommunicationServiceSmtpUsername.Tests.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/env.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/loadEnv.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/localEnv.json
  src/Communication/CommunicationServiceSmtpUsername.Autorest/test/utils.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/utils/Get-SubscriptionIdTestSafe.ps1
  src/Communication/CommunicationServiceSmtpUsername.Autorest/utils/Unprotect-SecureString.ps1
Labels: needs-revision, customer-reported

#27103 Add etag property to ipam pool and verifier workspace
  src/Network/Network.Test/ScenarioTests/NetworkManagerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerIpamPoolCRUD.json
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/NetworkManagerVerifierWorkspaceReachabilityAnalysisRunCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Models/NetworkManager/PSIpamPoolBaseResource.cs
  src/Network/Network/Models/NetworkManager/PSVerifierWorkspaceBaseResource.cs
  src/Network/Network/help/Get-AzNetworkManagerIpamPool.md
  src/Network/Network/help/Get-AzNetworkManagerVerifierWorkspace.md
  src/Network/Network/help/New-AzNetworkManagerIpamPool.md
  src/Network/Network/help/New-AzNetworkManagerVerifierWorkspace.md
  src/Network/Network/help/Set-AzNetworkManagerIpamPool.md
  src/Network/Network/help/Set-AzNetworkManagerVerifierWorkspace.md
Labels: needs-review

#27282 Quantum v3 to v4
  src/Quantum/Quantum.Autorest/Properties/AssemblyInfo.cs
  src/Quantum/Quantum.Autorest/README.md
  src/Quantum/Quantum.Autorest/custom/New-AzQuantumProviderObject.ps1
  src/Quantum/Quantum.Autorest/docs/Az.Quantum.md
  src/Quantum/Quantum.Autorest/docs/Get-AzQuantumOffering.md
  src/Quantum/Quantum.Autorest/docs/Get-AzQuantumWorkspace.md
  src/Quantum/Quantum.Autorest/docs/New-AzQuantumProviderObject.md
  src/Quantum/Quantum.Autorest/docs/New-AzQuantumWorkspace.md
  src/Quantum/Quantum.Autorest/docs/Remove-AzQuantumWorkspace.md
  src/Quantum/Quantum.Autorest/docs/Test-AzQuantumWorkspaceNameAvailability.md
  src/Quantum/Quantum.Autorest/docs/Update-AzQuantumWorkspace.md
  src/Quantum/Quantum.Autorest/examples/New-AzQuantumWorkspace.md
  src/Quantum/Quantum.Autorest/generate-info.json
  src/Quantum/Quantum.Autorest/resources/README.md
  src/Quantum/Quantum.Autorest/test/AzQuantumWorkspace.Tests.ps1
  src/Quantum/Quantum.sln
  src/Quantum/Quantum/Az.Quantum.psd1
  src/Quantum/Quantum/ChangeLog.md
  src/Quantum/Quantum/help/Az.Quantum.md
  src/Quantum/Quantum/help/Get-AzQuantumOffering.md
  src/Quantum/Quantum/help/Get-AzQuantumWorkspace.md
  src/Quantum/Quantum/help/New-AzQuantumProviderObject.md
  src/Quantum/Quantum/help/New-AzQuantumWorkspace.md
  src/Quantum/Quantum/help/Remove-AzQuantumWorkspace.md
  src/Quantum/Quantum/help/Test-AzQuantumWorkspaceNameAvailability.md
  src/Quantum/Quantum/help/Update-AzQuantumWorkspace.md
Labels: needs-revision

#27406 [Az.RecoveryServices.Backup] Handling breaking change for SecureToken in Get-AzAccessToken command
  src/RecoveryServices/RecoveryServices.Backup.Helpers/HelperUtils.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices.Backup.Models/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices.Backup.Test/ScenarioTests/IaasVm/ItemTests.ps1
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/DisableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Item/EnableAzureRmRecoveryServicesBackupProtection.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/ProtectionPolicy/SetAzureRmRecoveryServicesBackupProtectionPolicy.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/RestoreAzureRMRecoveryServicesBackupItem.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/RemoveAzureRmRecoveryServicesResourceGuardMapping.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesResourceGuardMapping.cs
  src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Vault/SetAzureRmRecoveryServicesVaultProperty.cs
  src/RecoveryServices/RecoveryServices.Backup/Helpers/BackupUtils.cs
  src/RecoveryServices/RecoveryServices.Backup/ParamHelpMsgs.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
  src/RecoveryServices/RecoveryServices/Properties/Resources.Designer.cs
  src/RecoveryServices/RecoveryServices/Properties/Resources.resx
  src/RecoveryServices/RecoveryServices/RecoveryServices.csproj
  src/RecoveryServices/RecoveryServices/Vault/UpdateAzureRmRecoveryServicesVault.cs
  src/RecoveryServices/RecoveryServices/help/Disable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupProtection.md
  src/RecoveryServices/RecoveryServices/help/Remove-AzRecoveryServicesResourceGuardMapping.md
  src/RecoveryServices/RecoveryServices/help/Restore-AzRecoveryServicesBackupItem.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesResourceGuardMapping.md
  src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesVault.md
Labels: needs-review

#26549 Health API
  src/Network/Network.Test/ScenarioTests/LoadBalancerHealthPerRuleTests.cs
  src/Network/Network.Test/ScenarioTests/LoadBalancerHealthPerRuleTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.LoadBalancerHealthPerRuleTests/TestLoadBalancerHealthPerRule.json
  src/Network/Network/Az.Network.psd1
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/LoadBalancer/GetAzureLoadBalancerRuleHealth.cs
  src/Network/Network/Models/PSLoadBalancerHealthPerRule.cs
  src/Network/Network/Models/PSLoadBalancerHealthPerRulePerBackendAddress.cs
  src/Network/Network/Network.format.ps1xml
  src/Network/Network/Network.generated.format.ps1xml
  src/Network/Network/help/Get-AzLoadBalancerRuleHealth.md
Labels: Network, Waiting for CI :shipit:

#27322 High Bandwidth VPNGW changes
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.cs
  src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests/TestHighBandwidthVpnGatewayCreation.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/PSTunnelConfig.cs
  src/Network/Network/Models/PSVirtualNetworkGateway.cs
  src/Network/Network/Models/PSVirtualNetworkGatewayConnection.cs
  src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs
  src/Network/Network/help/New-AzVirtualNetworkGateway.md
Labels: Network, needs-revision

#27532 [Az.RecoveryServices] Fix for A2A Reprotect cmdlet
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/A2A/AsrA2ATests.cs
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/ScenarioTests/A2A/AsrA2ATests.ps1
  src/RecoveryServices/RecoveryServices.SiteRecovery.Test/SessionRecords/RecoveryServices.SiteRecovery.Test.AsrA2ATests/A2AReprotectTest.json
  src/RecoveryServices/RecoveryServices.SiteRecovery/Utilities/SiteRecoveryAutoMapperProfile.cs
  src/RecoveryServices/RecoveryServices/ChangeLog.md
Labels: needs-review, OOB Release

#27519 Add connectivity capabilities for Network Manager connectivity configuration
  src/Network/Network.Management.Sdk/Generated/IIpamPoolsOperations.cs
  src/Network/Network.Management.Sdk/Generated/IVerifierWorkspacesOperations.cs
  src/Network/Network.Management.Sdk/Generated/IpamPoolsOperations.cs
  src/Network/Network.Management.Sdk/Generated/IpamPoolsOperationsExtensions.cs
  src/Network/Network.Management.Sdk/Generated/Models/ConnectedGroupPrivateEndpointsScale.cs
  src/Network/Network.Management.Sdk/Generated/Models/ConnectivityConfigurationPropertiesConnectivityCapabilities.cs
  src/Network/Network.Management.Sdk/Generated/Models/NatGateway.cs
  src/Network/Network.Management.Sdk/Generated/Models/NatGatewayPropertiesFormat.cs
  src/Network/Network.Management.Sdk/Generated/Models/NatGatewaySku.cs
  src/Network/Network.Management.Sdk/Generated/Models/NatGatewaySkuName.cs
  src/Network/Network.Management.Sdk/Generated/Models/PublicIPAddressSku.cs
  src/Network/Network.Management.Sdk/Generated/Models/PublicIPAddressSkuName.cs
  src/Network/Network.Management.Sdk/Generated/Models/PublicIPPrefixSku.cs
  src/Network/Network.Management.Sdk/Generated/Models/PublicIPPrefixSkuName.cs
  src/Network/Network.Management.Sdk/Generated/Models/VirtualNetwork.cs
  src/Network/Network.Management.Sdk/Generated/Models/VirtualNetworkPropertiesFormat.cs
  src/Network/Network.Management.Sdk/Generated/VerifierWorkspacesOperations.cs
  src/Network/Network.Management.Sdk/Generated/VerifierWorkspacesOperationsExtensions.cs
  src/Network/Network.Management.Sdk/README.md
  src/Network/Network.Test/ScenarioTests/NetworkManagerTests.ps1
  src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.NetworkManagerTests/TestNetworkManagerConnectivityConfigurationCRUD.json
  src/Network/Network/ChangeLog.md
  src/Network/Network/Common/NetworkResourceManagerProfile.cs
  src/Network/Network/Models/NetworkManager/PSNetworkManagerConnectivityCapabilities.cs
  src/Network/Network/Models/NetworkManager/PSNetworkManagerConnectivityConfiguration.cs
  src/Network/Network/NetworkManager/NetworkManagerConnectivityConfiguration/NetworkManagerConnectivityConfigurationBaseCmdlet.cs
  src/Network/Network/NetworkManager/NetworkManagerConnectivityConfiguration/NewAzNetworkManagerConnectivityConfigurationCommand.cs
  src/Network/Network/help/Get-AzNetworkManagerConnectivityConfiguration.md
  src/Network/Network/help/New-AzNetworkManagerConnectivityConfiguration.md
  src/Network/Network/help/Set-AzNetworkManagerConnectivityConfiguration.md
Labels: needs-review

#27520 Az.Compute - New VMSS Instance Mix SkuProfile Add and Remove Commands
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.cs
  src/Compute/Compute.Test/ScenarioTests/VirtualMachineScaleSetTests.ps1
  src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfilePrioritized.json
  src/Compute/Compute/Az.Compute.psd1
  src/Compute/Compute/ChangeLog.md
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/AddAzureRmVmssSkuProfileVmSizeCommand.cs
  src/Compute/Compute/Generated/VirtualMachineScaleSet/Config/RemoveAzureRmVmssSkuProfileVmSizeCommand.cs
  src/Compute/Compute/help/Add-AzVmssSkuProfileVMSize.md
  src/Compute/Compute/help/Remove-AzVmssSkuProfileVMSize.md
Labels: needs-revision

#27463 [PS] migrate VoiceServices module to autorest v4
  src/VoiceServices/VoiceServices.Autorest/Properties/AssemblyInfo.cs
  src/VoiceServices/VoiceServices.Autorest/README.md
  src/VoiceServices/VoiceServices.Autorest/custom/New-AzVoiceServicesCommunicationsGatewayServiceRegionObject.ps1
  src/VoiceServices/VoiceServices.Autorest/docs/Az.VoiceServices.md
  src/VoiceServices/VoiceServices.Autorest/docs/Get-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices.Autorest/docs/Get-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices.Autorest/docs/New-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices.Autorest/docs/New-AzVoiceServicesCommunicationsGatewayServiceRegionObject.md
  src/VoiceServices/VoiceServices.Autorest/docs/New-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices.Autorest/docs/Remove-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices.Autorest/docs/Remove-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices.Autorest/docs/Test-AzVoiceServicesNameAvailability.md
  src/VoiceServices/VoiceServices.Autorest/docs/Update-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices.Autorest/docs/Update-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices.Autorest/generate-info.json
  src/VoiceServices/VoiceServices.Autorest/resources/README.md
  src/VoiceServices/VoiceServices.sln
  src/VoiceServices/VoiceServices/Az.VoiceServices.psd1
  src/VoiceServices/VoiceServices/ChangeLog.md
  src/VoiceServices/VoiceServices/help/Az.VoiceServices.md
  src/VoiceServices/VoiceServices/help/Get-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices/help/Get-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices/help/New-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices/help/New-AzVoiceServicesCommunicationsGatewayServiceRegionObject.md
  src/VoiceServices/VoiceServices/help/New-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices/help/Remove-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices/help/Remove-AzVoiceServicesCommunicationsTestLine.md
  src/VoiceServices/VoiceServices/help/Test-AzVoiceServicesNameAvailability.md
  src/VoiceServices/VoiceServices/help/Update-AzVoiceServicesCommunicationsGateway.md
  src/VoiceServices/VoiceServices/help/Update-AzVoiceServicesCommunicationsTestLine.md
Labels: needs-revision

#27551 Changing Get-AzKeyVaultCertificate to Get-AzKeyVaultSecret
  src/Network/Network/help/Add-AzApplicationGatewaySslCertificate.md
Labels: customer-reported

#27288 migrate Portal module to autorest v4
  src/Portal/Portal.Autorest/Properties/AssemblyInfo.cs
  src/Portal/Portal.Autorest/README.md
  src/Portal/Portal.Autorest/custom/New-AzPortalDashboard.ps1
  src/Portal/Portal.Autorest/custom/Set-AzPortalDashboard.ps1
  src/Portal/Portal.Autorest/docs/Az.Portal.md
  src/Portal/Portal.Autorest/docs/Get-AzPortalDashboard.md
  src/Portal/Portal.Autorest/docs/New-AzPortalDashboard.md
  src/Portal/Portal.Autorest/docs/Remove-AzPortalDashboard.md
  src/Portal/Portal.Autorest/docs/Set-AzPortalDashboard.md
  src/Portal/Portal.Autorest/docs/Update-AzPortalDashboard.md
  src/Portal/Portal.Autorest/generate-info.json
  src/Portal/Portal.Autorest/resources/README.md
  src/Portal/Portal.sln
  src/Portal/Portal/Az.Portal.psd1
  src/Portal/Portal/ChangeLog.md
  src/Portal/Portal/help/Az.Portal.md
  src/Portal/Portal/help/Get-AzPortalDashboard.md
  src/Portal/Portal/help/New-AzPortalDashboard.md
  src/Portal/Portal/help/Remove-AzPortalDashboard.md
  src/Portal/Portal/help/Set-AzPortalDashboard.md
  src/Portal/Portal/help/Update-AzPortalDashboard.md
Labels: needs-revision

#27586 Update Get-AzAccessToken.md
  src/Accounts/Accounts/help/Get-AzAccessToken.md
Labels: customer-reported

#27582 Double Quotation marks in Get-AzPolicyAssignment Assignment Example 3
  src/Resources/Resources/help/Get-AzPolicyAssignment.md
Labels: customer-reported

#27326 [AppService] Add Pv4 and Pmv4 ASP support
  src/Websites/Websites/ChangeLog.md
  src/Websites/Websites/Cmdlets/AppServicePlans/NewAzureAppServicePlan.cs
  src/Websites/Websites/Cmdlets/AppServicePlans/SetAzureAppServicePlan.cs
  src/Websites/Websites/Utilities/CmdletHelpers.cs
Labels: needs-review

#27618 (AzureCXP) fixes MicrosoftDocs/azure-powershell#27148940
  src/RecoveryServices/RecoveryServices/help/Update-AzRecoveryServicesAsrProtectionContainerMapping.md
Labels: customer-reported

#27560 Collect Authentication Telemetry
  src/Accounts/Accounts.Test/AccessTokenCmdletTest.cs
  src/Accounts/Accounts.Test/AutosaveTests.cs
  src/Accounts/Accounts.Test/AzureRMProfileTests.cs
  src/Accounts/Accounts.Test/AzureSessionTestInitializer.cs
  src/Accounts/Accounts.Test/ContextCmdletTests.cs
  src/Accounts/Accounts.Test/EnvironmentCmdletTests.cs
  src/Accounts/Accounts.Test/ErrorResolutionTests.cs
  src/Accounts/Accounts.Test/ProfileCmdletTests.cs
  src/Accounts/Accounts.Test/SilentReAuthByTenantCmdletTest.cs
  src/Accounts/Accounts.Test/TenantCmdletMockTests.cs
  src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
  src/Accounts/Accounts/ChangeLog.md
  src/Accounts/Accounts/Common/AzureContextModificationCmdlet.cs
  src/Accounts/Accounts/Context/GetAzureRMContext.cs
  src/Accounts/Accounts/Default/GetAzureRmDefault.cs
  src/Accounts/Accounts/Default/SetAzureRMDefault.cs
  src/Accounts/Accounts/Environment/GetAzureRMEnvironment.cs
  src/Accounts/Accounts/Models/RMProfileClient.cs
  src/Accounts/Accounts/Rest/InvokeAzRestMethodCommand.cs
  src/Accounts/Accounts/Subscription/GetAzureRMSubscription.cs
  src/Accounts/Accounts/Tenant/GetAzureRMTenant.cs
  src/Accounts/Accounts/Token/GetAzureRmAccessToken.cs
  src/Accounts/Authentication.ResourceManager/AzureRmProfile.cs
  src/Accounts/Authentication.Test/AuthenticationFactoryConcurrencyTest.cs
  src/Accounts/Authentication.Test/AuthenticationFactoryTests.cs
  src/Accounts/Authentication.Test/AuthenticatorsTest/SilentAuthenticatorTests.cs
  src/Accounts/Authentication.Test/Cmdlets/ConnectAccount.cs
  src/Accounts/Authentication.Test/Mocks/MockAuthenticationTestBase.cs
  src/Accounts/Authentication/Authentication/DelegatingAuthenticator.cs
  src/Accounts/Authentication/Authentication/IAuthenticator.cs
  src/Accounts/Authentication/Authentication/PassThroughAuthenticator.cs
  src/Accounts/Authentication/Authentication/TokenCache/PowerShellTokenCacheProvider.cs
  src/Accounts/Authentication/Factories/AuthenticationFactory.cs
  src/Accounts/Authentication/Factories/ClientFactory.cs
  src/Accounts/Authentication/KeyStore/AzKeyStore.cs
  src/Accounts/Authentication/Properties/Resources.Designer.cs
  src/Accounts/Authentication/Properties/Resources.resx
  src/Accounts/Authenticators/AccessTokenAuthenticator.cs
  src/Accounts/Authenticators/ClientAssertionAuthenticator.cs
  src/Accounts/Authenticators/DeviceCodeAuthenticator.cs
  src/Accounts/Authenticators/InteractiveUserAuthenticator.cs
  src/Accounts/Authenticators/InteractiveWamAuthenticator.cs
  src/Accounts/Authenticators/ManagedServiceIdentityAuthenticator.cs
  src/Accounts/Authenticators/ServicePrincipalAuthenticator.cs
  src/Accounts/Authenticators/SilentAuthenticator.cs
  src/Accounts/Authenticators/UsernamePasswordAuthenticator.cs
  tools/Common.Netcore.Dependencies.targets
  tools/TestFx/Mocks/MockCertificateAuthenticationFactory.cs
  tools/TestFx/Mocks/MockClientFactory.cs
  tools/TestFx/Mocks/MockTokenAuthenticationFactory.cs
Labels: needs-review

#27639 [Az.FluidRelay] Update generation tool version: autorest.powershell v3->v4
  src/FluidRelay/FluidRelay.Autorest/Properties/AssemblyInfo.cs
  src/FluidRelay/FluidRelay.Autorest/README.md
  src/FluidRelay/FluidRelay.Autorest/docs/Az.FluidRelay.md
  src/FluidRelay/FluidRelay.Autorest/docs/Get-AzFluidRelayContainer.md
  src/FluidRelay/FluidRelay.Autorest/docs/Get-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay.Autorest/docs/Get-AzFluidRelayServerKey.md
  src/FluidRelay/FluidRelay.Autorest/docs/New-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay.Autorest/docs/New-AzFluidRelayServerKey.md
  src/FluidRelay/FluidRelay.Autorest/docs/Remove-AzFluidRelayContainer.md
  src/FluidRelay/FluidRelay.Autorest/docs/Remove-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay.Autorest/docs/Update-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay.Autorest/examples/New-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay.Autorest/examples/Update-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay.Autorest/generate-info.json
  src/FluidRelay/FluidRelay.Autorest/resources/README.md
  src/FluidRelay/FluidRelay.Autorest/test/AzFluidRelayServer.Recording.json
  src/FluidRelay/FluidRelay.Autorest/test/AzFluidRelayServer.Tests.ps1
  src/FluidRelay/FluidRelay.Autorest/test/AzFluidRelayServerKey.Recording.json
  src/FluidRelay/FluidRelay.Autorest/test/env.json
  src/FluidRelay/FluidRelay.sln
  src/FluidRelay/FluidRelay/Az.FluidRelay.psd1
  src/FluidRelay/FluidRelay/ChangeLog.md
  src/FluidRelay/FluidRelay/help/Az.FluidRelay.md
  src/FluidRelay/FluidRelay/help/Get-AzFluidRelayContainer.md
  src/FluidRelay/FluidRelay/help/Get-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay/help/Get-AzFluidRelayServerKey.md
  src/FluidRelay/FluidRelay/help/New-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay/help/New-AzFluidRelayServerKey.md
  src/FluidRelay/FluidRelay/help/Remove-AzFluidRelayContainer.md
  src/FluidRelay/FluidRelay/help/Remove-AzFluidRelayServer.md
  src/FluidRelay/FluidRelay/help/Update-AzFluidRelayServer.md
Labels: needs-revision

#27663 [Az.Aks] Disable setting the default NodeVmSize value
  src/Aks/Aks/ChangeLog.md
  src/Aks/Aks/Commands/CreateOrUpdateKubeBase.cs
  src/Aks/Aks/Commands/NewAzureRmAks.cs
  src/Aks/Aks/Commands/NewAzureRmAksNodePool.cs
  src/Aks/Aks/help/New-AzAksCluster.md
  src/Aks/Aks/help/New-AzAksNodePool.md
Labels: Breaking Change Release
